### ISSUE TITLE
FEATURE REQUEST: Block group creation by users as an optional Standard

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#1005]
**Is your feature request related to a problem? Please describe.**
Users creating Teams with Teams app for every little thing, leading to messy / disorganized Teams experience

**Describe the solution you'd like**
Have a switch in the Standards wizard to block creation of groups by end users as per https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide  - and that will prevent new Teams creation. This standard should be off by default and optional!

**Describe alternatives you've considered**
Running the script from PowerShell which works quite well on a single tenant basis.

**Additional context**
That customer that had a new Team for every project - 1000's of teams to cleanup 
![NightmareSimpsonsGIF](https://user-images.githubusercontent.com/17422069/177421638-020bd400-8ac0-45bb-b796-faf71653fadc.gif)

**Comment by KelvinTegelaar** [comment]
discussed in Discord; planned

**Comment by KelvinTegelaar** [comment]
added in dev via these two checkboxes;

![image](https://user-images.githubusercontent.com/49186168/179401718-262c1b20-c390-445d-b6c1-6e148a90034b.png)

**Comment by dan-baird** [comment]
> added in dev via these two checkboxes;
> 
> ![image](https://user-images.githubusercontent.com/49186168/179401718-262c1b20-c390-445d-b6c1-6e148a90034b.png)

Oh... cool... thanks. Do you know if this setting applies to group creation via Teams as well? I assume Teams is using the API to create groups?

**Comment by dan-baird** [comment]
> added in dev via these two checkboxes;
> 
> ![image](https://user-images.githubusercontent.com/49186168/179401718-262c1b20-c390-445d-b6c1-6e148a90034b.png)

Oh... cool... thanks. Do you know if this setting applies to group creation via Teams as well? I assume Teams is using the API to create groups?
