### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by obitbg** [KelvinTegelaar/CIPP#1010]
**Describe the bug**
Step 2 of the SAM wizard fails with "Could not find admin role on your user. Try refreshing this page fully (CTRL+F5) or logging in under the right user."

**To Reproduce**

Account is cipp@domain.com, is a global administrator on the tenant. Was used for step 1 to setup powershell device login.
Step 2 of the SAM Token Wizard succeeds in allowing cipp@ user to grant app permissions, and then immediately fails to:
"Could not find admin role on your user. Try refreshing this page fully (CTRL+F5) or logging in under the right user."

**Expected behavior**
Once permissions are granted, I would expect it to go to the next step without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/103391883/177613463-47e0f015-3246-47da-b71e-ddd40d9fa5b1.png)

**Desktop (please complete the following information):**

Windows 11, Edge Browser, Up to Date

**Additional context**

**Comment by KelvinTegelaar** [comment]
Fixed in dev
