### ISSUE TITLE
BUG: Standards not changing

### ISSUE THREAD

**Issue by xtechsnik** [KelvinTegelaar/CIPP#1013]
**Describe the bug**
After enabling Disable Basic Authentication in standards when I uncheck check box and click edit standard it says it is saved. When I go back into standards check box is still checked and turned on.

**To Reproduce**

1. Go to '...' Standards
2. Click on '....' Toggle switch for Disable Basic Authentication.

**Expected behavior**
When I turn toggle off it should stay off.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KelvinTegelaar** [comment]
cannot replicate,  are you running the latest version of the frontend and API?

**Comment by KelvinTegelaar** [comment]
Just to check, you are unchecking the standard, scrolling down, and clicking "Edit Standard" right?

**Comment by xtechsnik** [comment]
Hi. Yes. I unchecked the toggle then clicked Edit Standard at bootom.
When I check back a few minutes later that toggle is on.

**Comment by KelvinTegelaar** [comment]
Have you tried refreshing the page? We tried across multiple instances and can't replicate. When saving the settings, navigating away or refrehsing the page you see the change directly reflected.

**Comment by xtechsnik** [comment]
Hi. I have done that. I even signed out then back in.

**Comment by KelvinTegelaar** [comment]
Wait, do you mean that it's still disabled inside of the tenant? That's expected behaviour and why we have the big banner pointing to the documentation at the Apply Standard screen.

**Comment by xtechsnik** [comment]
Not inside the tenant. In the List and Edit Standards in CIPP.

**Comment by xtechsnik** [comment]
Basically. I have went back into some of the tenants and re-enabled basic auth. I want to make sure the standards is not going to disable again.

**Comment by xtechsnik** [comment]
Hi. So when I went to my home computer and made the change the change stuck. Looks good to go now. We can mark this one as closed. I do have another question.  We are an MSP and have our tenants in our CIPP app. I have a co-managed client with internal IT. Can I deploy to their Azure and just use my fork from GIT or have them create a GIT account and fork from your repository? Thanks.

**Comment by KelvinTegelaar** [comment]
You can reuse your fork for as many deployments as you want, up to 100. :)

**Comment by xtechsnik** [comment]
Hi. I forgot to mention. When I checked from my home computer toggle was still on. 
I turned off function app and waited 10 minutes then turned it back on.
After turning it back on when I toggled the basic auth it kept the settings.
Just an FYI in case it comes up anywhere else.
Also. A big thank you for creating such a great app.

**Comment by xtechsnik** [comment]
I have turned off toggle and clicked Edit Standards and when  go back it look like this.

[cid:f66d5667-ba0c-4b0a-8d94-85da9b7b5bba]
________________________________

Nik Margulski
MCSE | MCITP-E | MCP
