### ISSUE TITLE
BUG: SAM Wizard Step 2

### ISSUE THREAD

**Issue by seanpcook** [KelvinTegelaar/CIPP#1016]
Description
After clicking the link and approving permissions for the app it returns the following error and does not move through the remaining steps. "No authentication code found. Please go back to the wizard and click the URL again."

To Reproduce

1. Start automated SAM wizard
2. Copy code from step 1 and click on link to authenticate
3. Return to Wizard click on link in step 2
4. Sign-on with GA to approve consent
5. Error about no auth code is returned

Expected behavior
Expected the wizard to continue to step 3

Device
- OS: WIN10Pro
- Browser: Edge
-Version: 103.0.1264.49

**Comment by seanpcook** [comment]
Upgraded the CIPP platform and error has changed to saying the user does not have admin access. Will troubleshoot and submit another issue if I' not able to resolve.

**Comment by KelvinTegelaar** [comment]
Make sure you're running the latest version. if you're getting an error about the admin role, click on the URL bar and hit enter again.

**Comment by seanpcook** [comment]
> Make sure you're running the latest version. if you're getting an error about the admin role, click on the URL bar and hit enter again.

That fixed the admin msg issue. Got through all 7 steps. Thanks Kelvin!
