### ISSUE TITLE
FEATURE REQUEST: Monitoring Apple Push Notification Certificate Expiration

### ISSUE THREAD

**Issue by davidpfox** [KelvinTegelaar/CIPP#1018]
I could not see anything in DISCORD already so thought I would throw this at you - we use to get email alerts from Apple about an expiring certificate (12 months validity), but now we are left to put something in a calendar for reminding our team to renew before expiry. Any chance this has been considered for CIPP?

**Comment by KelvinTegelaar** [comment]
This seems like more of a task for a documentation system than CIPP, closing.
