### ISSUE TITLE
[Feature Request]: Report all Global Admins without MFA enabled

### ISSUE THREAD

**Issue by Robby-Swartenbroekx** [KelvinTegelaar/CIPP#1020]
### Description of the new feature - must be in-depth. Follow a [user story](https://www.techtarget.com/searchsoftwarequality/definition/user-story#:~:text=A%20user%20story%20is%20a,simplified%20description%20of%20a%20requirement.)

We would love to see a possibility to report on specifics of user accounts over all tenants. Reporting everyone with a Global Admin role that hasn't MFA enabled is our top 1. But we have other requests for specific reports that we would like to run over all our tenants:
- All Global admins with licenses applied to them
- All Users without active MFA over all tenants

**Comment by KelvinTegelaar** [comment]
You can use the Graph Reporter for this. See https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter for filtering options etc
