### ISSUE TITLE
[Feature Request]: Alert on maxxing out SharePoint storage

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#1021]
### Description of the new feature - must be in-depth. Follow a [user story](https://www.techtarget.com/searchsoftwarequality/definition/user-story#:~:text=A%20user%20story%20is%20a,simplified%20description%20of%20a%20requirement.)

We often get clients maxxing out the storage available in SharePoint - and since that has to be constantly manually provisioned - it can be hard to stay on top of.

### Proposed implementation details

Can you add an alert that will tell us when a tenant has reached 95% of SharePoint storage?

**Comment by KelvinTegelaar** [comment]
This one is a little hard to do, as we don't have APIs that tell us the quota of a site vs how full it is. Closing for now, but feel free to reopen in the future. MS is working on Sharepoint APIs in graph, so this might change in weeks or months.
