### ISSUE TITLE
Usage Location isn't remembered or autofilled

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#1024]
### Description

When editing a user under **Administration >> Users** the "Usage Location" box is always empty. Any changes require you to re-fill this box before you can save. In the "Raw User Data" section, you can see that this information is pulled from Microsoft every time.

### Environment data

```PowerShell
Front end 2.8.0
Back end 1.13.1
```

**Comment by KelvinTegelaar** [comment]
not a bug, the userprofile in your settings(setting -> avatar) is overwriting the existing one. You probably blanked that somewhere down the line.
