### ISSUE TITLE
[Feature Request]: Expand "multi-select" to Groups & Mailboxes

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1025]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I think it would be helpful to have multi select in

Identity Management\Administration\Groups
as well as
EMAIL & EXCHANGE\Administration\Mailboxes (after clicking edit button on a mailbox)

if i want to remove/add multiple members of a group or add multiple users mailboxes/permissions etc

### PowerShell commands you would normally use to achieve above request

'user1','user2' | Get-Mailbox | Add-MailboxPermission -User me -AccessRights FullAccess -InheritanceType All

or

$users = 'user1','user2'
ForEach ($user in $users) {

**Comment by KelvinTegelaar** [comment]
added in dev
