### ISSUE TITLE
Creating a 'Transport Rule' template or deploying changes text to lowercase.

### ISSUE THREAD

**Issue by MC344** [KelvinTegelaar/CIPP#1028]
### Description

Under Email and Exchange > Transport Rules.

If I use 'Add Template' and enter the JSON parameters, it automatically changes all text to lowercase, even if it had some words in Caps (If there is a message to be deployed, it looks untidy if it's all lowercase)

In the prebuilt templates, you can see that Display Name and the JSON has both upper and lowercase characters. 

If I use List Transport Rules, and then create Template on an existing rule, this also changes the Display Name to lowercase, along with any text inside the JSON.

![2022-07-22 09_39_47-CIPP - Transport Rule Templates — Mozilla Firefox](https://user-images.githubusercontent.com/105486808/180401571-0eff06dc-aec1-4583-9b25-96e973716dec.png)
![2022-07-22 09_40_02-CIPP - Transport Rule Templates — Mozilla Firefox](https://user-images.githubusercontent.com/105486808/180401574-8f19630d-6291-4975-acc6-d4e1affbc72c.png)
![2022-07-22 09_42_19-CIPP - List Transport rules — Mozilla Firefox](https://user-images.githubusercontent.com/105486808/180401576-424e1a6f-69ec-470d-ae11-dcfa48baf336.png)
![2022-07-22 09_42_52-CIPP - Transport Rule Templates — Mozilla Firefox](https://user-images.githubusercontent.com/105486808/180401581-047b05b9-5720-474f-83bd-48dcba82a72a.png)
![Before-CIPP](https://user-images.githubusercontent.com/105486808/180401584-1aacfe96-a764-4b35-b90d-7bf4979507e5.png)
![CIPP-After](https://user-images.githubusercontent.com/105486808/180401586-a5356aa8-3730-4665-ba35-dd325db80590.png)

### Environment data

```PowerShell
Azure - hosted by us.
Front End: 2.8.0
Backend: 1.13.1
```

**Comment by MC344** [comment]
Thank you Kelvin.

**Comment by KelvinTegelaar** [comment]
and fixed in dev.
