### ISSUE TITLE
Sam Setup stuck on stage 2

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#1033]
### Description

Hi,

Due to a few issues that started when (I think) I moved subscriptions, I've been having random errors within CIPP and decided to install from scratch.

I went through the setup without doing the SAM as I thought I would try the new online wizard.

Stage 2 seems to always return:

`Could not find admin role on your user. Try reloading this page by copying the URL, and visiting it once more or logging in under the right user.
`
Despite the user having both GA and being in the AdminAgents group.

If anyone wants to see, I recorded a video and feel free to @Me on Discord and I will send.

(Version 2.9.0 / 1.14.0)

### Environment data

```PowerShell
New install in Azure, just ran the deployment.
```

**Comment by Pukkahq** [comment]
We got the same error but I closed window and clicked the link again and then it went through ok, I needed to do this twice.

**Comment by wilhil** [comment]
Hi @Pukkahq - I heard this was my fault... I was following Gavin's blog (gavsto.com) about best implementation for SAM users and I created a dedicated user for running CIPP.

I however did not add this user to CIPP, so, the redirect back to CIPP after authenticating was broken.

I set up everything manually and it worked.

**Comment by Pukkahq** [comment]
I created a dedicated new user, waited 20 min then ran through installer once done I ran the SAM wizard and got the error message

**Comment by wilhil** [comment]
Did you invite the user to CIPP in the same way as you invite yourself as a user?

**Comment by Pukkahq** [comment]
I only invited the SAM user and ran the wizard as the SAM user.
