### ISSUE TITLE
[Feature Request]: Allow setting Out of Office message from Identity Management

### ISSUE THREAD

**Issue by LNS-MElliott** [KelvinTegelaar/CIPP#1036]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great if, similar to the O365 admin portal, we were able to set end-user Automatic Replies from Identity Management. I know this feature is built into the offboarding wizard, but it's a fairly common task for us to turn it on for people who forget when they are on vacation, not just for offboarding.

### PowerShell commands you would normally use to achieve above request

Set-MailboxAutoReplyConfiguration -Identity tony@contoso.com -AutoReplyState Enabled -InternalMessage "Internal auto-reply message." -ExternalMessage "External auto-reply message."

**Comment by PremierOne1130** [comment]
Love this idea
