### ISSUE TITLE
Unable to deploy git to Azure

### ISSUE THREAD

**Issue by BITsmartIT** [KelvinTegelaar/CIPP#1038]
### Description

I have tried to run the deployment using the Deploy button as well as manually following the instructions. Both have resulted in the following error when deploying from Git to Azure. 

Can you advise. Thank you. 

Detecting platforms...
Detected following platforms:
  nodejs: 14.19.1
Version '14.19.1' of platform 'nodejs' is not installed. Generating script to install it...
Error: Could not find either 'build' or 'build:azure' node under 'scripts' in package.json. Could not find value for custom run build command using the environment variable key 'RUN_BUILD_COMMAND'.Could not find tools for building monorepos, no 'lerna.json' or 'lage.config.js' files found.

---End of Oryx build logs---
Oryx could not find a 'build' or 'build:azure' script in the package configuration. Please add one of these commands to your package configuration file (i.e. package.json). Alternatively, you can add the app_build_command to the build/deploy section of your workflow file. For example, app_build_command: 'npm run docs:build'

### Environment data

```PowerShell
Azure
```

**Comment by johnduprey** [comment]
It appears you're missing a fork of this repository as you only have CIPP-API.
Take a look [here](https://cipp.app/docs/user/gettingstarted/prerequisites)/ and jump on the CyberDrain discord if you have questions.

**Comment by BITsmartIT** [comment]
Thank for such a quick response. I believe that I have both CIPP and CIP-API setup. CIPP is marked as private. Could that be an issue?

Regards
Raoul
[BITsmart.IT_logo]
BITsmart.IT – IT Solutions
PO Box 580 Sutherland, NSW, 1499
P:  02 9881 5678
E: ***@***.******@***.***>
W. www.bitsmart.it<http://www.bitsmart.it/>
Please consider the environment before printing this email.

This email is confidential. The views and opinions expressed in this email are those of the sender and do not necessarily reflect the views of the organisation by whom they are employed, except when the sender expressly and with authority states them to be so.
