### ISSUE TITLE
FEATURE REQUEST: Allow push notifications to be sent to Duo(Existing setup using Microsoft Conditional Access)

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#1044]
Love to push the notification button in CIPP. We have a lot of clients using Duo MFA which is done using a conditional access Policy that sends MFA requests to Duo.
Is it possible for the push notification button to trigger this?

**Comment by KelvinTegelaar** [comment]
No, not possible. completely different approach.
