### ISSUE TITLE
[Feature Request]: Add N-able to MSP Apps list

### ISSUE THREAD

**Issue by pricenfi** [KelvinTegelaar/CIPP#1048]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Expanding on the MSP App functionality, it would be nice to have support for the N-Central agent.  A generic agent installer can be downloaded from the system and used with all clients by adjusting the install command.  

### PowerShell commands you would normally use to achieve above request

Distribute intunewin package and use the following values:

Install Command: 
`WindowsAgentSetup.exe /s /v" /qn CUSTOMERID=<clientid> REGISTRATION_TOKEN=<registrationtoken> CUSTOMERSPECIFIC=1 SERVERPROTOCOL=HTTPS SERVERADDRESS=<nableserver> SERVERPORT=443"`

Uninstall Command:
`MsiExec.exe /X {<registrationtoken>}`

Detection: 
C:\Program Files (x86)\N-able Technologies\Windows Agent\bin\agent.exe

**Comment by KelvinTegelaar** [comment]
As none of the current contributors are N-Central users, our team(mainly me) would need to invest time into this. It's not just the process of adding it a single time - MSP apps need to be maintained to always deploy the right version and prepared to make changes whenever the manufacture/vendor does.

I highly recommend sharing our sponsorship page with your N-Central account manager and product managers to see if they could add a sponsorship https://github.com/sponsors/KelvinTegelaar. This could make it so we can invest some time into adding it. :)
