### ISSUE TITLE
GitHubBot - Dead Link

### ISSUE THREAD

**Issue by TechEnvyPtyLtd** [KelvinTegelaar/CIPP#1051]
### Description

The GitHub bot that mentions being a contributor goes to a dead URL: https://kelvintegelaar.github.io/CIPP/GettingStarted/Contributions.html

### Environment data

```PowerShell
See https://github.com/KelvinTegelaar/CIPP/issues/1050 and the url contained within.
```

**Comment by TechEnvyPtyLtd** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed, thank you for reporting!
