### ISSUE TITLE
Deploy Standards not excluding tenats in the excluded list.

### ISSUE THREAD

**Issue by rthenter1212** [KelvinTegelaar/CIPP#1058]
### Description

Standards is applying to all customer tenants even the excluded ones listed in the excluded tenants under settings.  

### Environment data

```PowerShell
Hosted in Azure on frontend verison 2.10.0 and backend 1.15.2
```

**Comment by KelvinTegelaar** [comment]
Have you checked the latest release notes that you must recreate your excluded tenants?
