### ISSUE TITLE
Cannot Scroll Some Pages

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#1061]
### Description

The "Administration>Users>Edit and "Administration>Users>Research Compromised Account" screens cannot be scrolled due to the CSS using the "overflow: fidden" element:

![image](https://user-images.githubusercontent.com/20848373/183420142-032c8950-3f0c-4938-8156-07000d4330b9.png)

### Environment data

```PowerShell
Azure 2.10.0
```

**Comment by matstocks** [comment]
This is being pulled directly from _themes.css. I've tested this by changing _themes.css on lines 517 and 335 to "overflow: auto" which resolves the problem, however, I'm aware this may not be where the ultimate change is needed, as it is probably over-ridden elsewhere.

**Comment by KelvinTegelaar** [comment]
That doesn't fix it, but your refresh did. It's been a bug for a while and a refresh temporarily resolves it. Still looking for permanent solution. :)

**Comment by KelvinTegelaar** [comment]
Finally fixed thanks to discovering the source; our offcanvas(the side menu that slides out) caused this.
