### ISSUE TITLE
[Feature Request]: Add date & time column(s) to Email & Exchange > Quarantine list as it's difficult to determine age

### ISSUE THREAD

**Issue by bowatts** [KelvinTegelaar/CIPP#1065]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

[Feature Request]: Add date & time column(s) to Email & Exchange > Quarantine list as it's difficult to determine age

**Comment by KelvinTegelaar** [comment]
added in dev
