### ISSUE TITLE
FEATURE REQUEST: Variables in Templates

### ISSUE THREAD

**Issue by Aldenwil** [KelvinTegelaar/CIPP#1068]
We have built a drive mapping template for Intune, but I can see this being useful in other cases as well, As it currently stands, our JSON for the template sits as such:

```
"Description"
: 
"Map letter drive to a UNC path of choice. Correct all placeholder variables."
,
  
"RAWJson"
: 
"{\"id\":\"00000000-0000-0000-0000-000000000000\",\"displayName\":\"Map Network Drive\",\"description\":\"Maps network drive. OMA-URI and some strings will require manual modification. Assign this to the user or user group that will need the drive.\",\"roleScopeTagIds\":[\"0\"],\"@odata.type\":\"#microsoft.graph.windows10CustomConfiguration\",\"omaSettings\":[{\"displayName\":\"Drive <letter>\",\"description\":\"Maps <letter> drive to a network share\",\"omaUri\":\"./user/Vendor/MSFT/Policy/Config/DriveMapping~Policy~DriveMapping/Drive_<letter>\",\"@odata.type\":\"#microsoft.graph.omaSettingString\",\"value\":\"<enabled/>\\n<data id=”Drive_<letter>_RemotePath” value=”\\\\\\\\MyFileServer\\\\MyFileShare“/>\\n<data id=”Drive_<letter>_RemotePath_IsDFS” value=”False“/>\"}]}"
,
  
"Type"
: 
"Device"
,
  
"GUID"
: 
"587fc9f0-3d08-4094-979a-3d0ddd7fb5a7"

}
```

It would be a great QOL feature if I could replace the `<letter>` and `\\\\MyFileServer\\\\MyFileShare` instances with a linked String input, that would then allow myself or other technicians to fill out, for example, a "Drive letter" and "Folder path" field and have it pull into the the script, without having to have our techs manually step through the JSON to replace all instances of <letter> with the correct letter - one less possible error when trying to go fast. Please let me know if a screenshot would better illustrate what I'm asking for.

**Comment by KelvinTegelaar** [comment]
as discussed on Discord this is already planned, expected for the next release after tomorrow's :)

**Comment by KelvinTegelaar** [comment]
This is still planned, just got shuffled around a little.

**Comment by KelvinTegelaar** [comment]
Added in dev. You can now use %varname% in templates and it'll ask you for a replacement
