### ISSUE TITLE
Logon to demo tenant requires MFA

### ISSUE THREAD

**Issue by Lowell-Syncrety** [KelvinTegelaar/CIPP#1069]
### Description

The logon to the demo tenant is requiring authenticator app MFA.

### Environment data

```PowerShell
This is referring to the demo tenant for CIPP.
```

**Comment by KelvinTegelaar** [comment]
Not an issue or bug. We disabled it on purpose as a competitor kept breaking it on purpose... :)

**Comment by Lowell-Syncrety** [comment]
Fair enough, but then a notice should be added that the demo link is disabled.
