### ISSUE TITLE
[Feature Request]: add Defender for Business deployment

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#1072]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

1. Enable Defender for Business in the Security admin center 
2. Enable the connector between Defender and MEM
3. Add the Endpoint Detection & Response profile configured as per screenshot:

![image](https://user-images.githubusercontent.com/17422069/185639285-90100df9-6522-4c3d-9d7a-11fd2f742012.png)

This could all be added to the Defender deployment wizard as a new Step in the process....

**Comment by KelvinTegelaar** [comment]
Adding, I somehow missed this in the first screen.

**Comment by KelvinTegelaar** [comment]
added in dev

**Comment by knightian** [comment]
> Adding, I somehow missed this in the first screen.

It's possible that when you looked it wasn't showing the Auto from connector option. Sometimes I have seen it take some hours to show even when enabling the MDE connector to intune, and it won't show it unless that is enabled.

**Comment by dan-baird** [comment]
> It's possible that when you looked it wasn't showing the Auto from connector option. Sometimes I have seen it take some hours to show even when enabling the MDE connector to intune, and it won't show it unless that is enabled.

Can confirm. This is the behaviour we've seen too. As per steps 1 and 2 in my FR, the Defender for Biz has to be enabled in Sec portal first then the connector has to be enabled for a little while (hous/days?) before this policy option shows up.
