### ISSUE TITLE
Unable to create conditional access template based on existing rule

### ISSUE THREAD

**Issue by just-jenb-fairoaksit** [KelvinTegelaar/CIPP#1073]
### Description

1. Go to Conditional Access
2. Go to List Policies
3. Scroll to the right and click on Actions for the policy you want
4. Choose Create template based on rule
5. Choose Continue <---- choosing continue does nothing/just highlights as if you are pressing the button but it sits there

In addition, all the templates I had set up before are now gone, not so much an issue if I could copy the existing ones again!
Thanks!
![image](https://user-images.githubusercontent.com/98419389/185699773-0a48009c-fed1-45da-bf1e-a51e483daf0e.png)

### Environment data

```PowerShell
Self-hosted environment, just updated to latest release and changed the Github connection as instructed in the release notes
```

**Comment by KelvinTegelaar** [comment]
Fixed in hotfix
