### ISSUE TITLE
Creating OMA-URI Intune MEM Policy results in error

### ISSUE THREAD

**Issue by PuulCampai** [KelvinTegelaar/CIPP#1075]
### Description

After having created an OMA-URI policy to deploy within Intune through CIPP, it returns an error. We captured the json data and entered this in the policy template

The policy is created succesfully, it has the correct OMA-URI but when trying to edit the OMA-URI afterwards it returns an error with error code 404. There is no way to edit the record to adjust the settings/string contained within it. Also deleting the string and adding a new one is now allowed because of the same error.

{  "shellProps": {    "sessionId": "48ab22888f5b40d08ddf4413fe33d933",    "extName": "Microsoft_Intune_DeviceSettings",    "contentName": "TableUpdate",    "code": 404  },  "error": {    "message": "Not found",    "code": 404  }}

The only way to solve it is to manually create a new policy, after which we're able to add another OMA-URI or string value
![2022-08-22 11_44_21-Not found - Microsoft Endpoint Manager admin center -  InPrivate  - Microsoft​ E](https://user-images.githubusercontent.com/111741508/185891921-d4dd100c-f614-4a13-8a24-e468b1216429.png)
.

### Environment data

```PowerShell
Azure self hosted but sponsored (Campai)
```

**Comment by PuulCampai** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Please paste the OMA URI you're using so I can use that for tests. :)

**Comment by PuulCampai** [comment]
The JSON data we pulled:
{"id":"00000000-0000-0000-0000-000000000000","displayName":"BP - Set Local Administrator 2022.8","description":"Set Local Administrator 2022.8","roleScopeTagIds":["0"],"@odata.type":"#microsoft.graph.windows10CustomConfiguration","omaSettings":[{"displayName":"LocalAdminsV2","omaUri":"./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure","@odata.type":"#microsoft.graph.omaSettingString","value":"<GroupConfiguration>\n    <accessgroup desc = \"Administrators\">\n        <group action = \"R\"/> \n            <add member = \"Administrator\"/>\n            <add member = \"AzureAD\\deviceadmin@klantnaam.nl\"/>\n    </accessgroup>\n</GroupConfiguration>"}]}

This should result in:

OMA-URI: 
./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure
Value: 
<GroupConfiguration>
    <accessgroup desc = "Administrators">
        <group action = "R"/> 
            <add member = "Administrator"/>
            <add member = "AzureAD\deviceadmin@klantnaam.nl"/>
    </accessgroup>
</GroupConfiguration>

**Comment by KelvinTegelaar** [comment]
this is looking like a MS issue, not a CIPP issue. When I use the template:
```json
{"id":"00000000-0000-0000-0000-000000000000","displayName":"BP - Set Local Administrator 2022.8","description":"Set Local Administrator 2022.8","roleScopeTagIds":["0"],"@odata.type":"#microsoft.graph.windows10CustomConfiguration","omaSettings":[{"displayName":"LocalAdminsV2","omaUri":"./Device/Vendor/MSFT/Policy/Config/LocalUsersAndGroups/Configure","@odata.type":"#microsoft.graph.omaSettingString","value":"<GroupConfiguration>\n    <accessgroup desc = \"Administrators\">\n        <group action = \"R\"/> \n            <add member = \"Administrator\"/>\n            <add member = \"AzureAD\\deviceadmin@klantnaam.nl\"/>\n    </accessgroup>\n</GroupConfiguration>"}]}
```
and apply it to any tenant, I'm able to do everything without receiving a 404. Have you tried multiple tenants? It might just be a browser issue or Azure intermittence.

![image](https://user-images.githubusercontent.com/49186168/185896208-c594d6f7-97f7-44eb-ad65-08e83de29e61.png)

**Comment by PuulCampai** [comment]
You are right, it does appear to be an issues on some tenants. We will look into this from our side!

Thank you for the quick response!

**Comment by KelvinTegelaar** [comment]
No problem! let me know if this gets figured out. Might be good to document.

**Comment by PuulCampai** [comment]
Somehow it shows the error when signing in using the global admin account of the tenant. When approaching endpoint manager using our partner portal, it does work.

**Comment by PuulCampai** [comment]
Somehow it shows the error when signing in using the global admin account of the tenant. When approaching endpoint manager using our partner portal, it does work.

**Comment by KelvinTegelaar** [comment]
So I hit up my Microsoft contacts for this and it turns out it's an intune known issue; when you create OMI settings as a partner it encrypt the values of the string contents with your partners tenant ID. they are working on a fix for this so it's an MS issue. :)

**Comment by PuulCampai** [comment]
Thank you for this! Happy to know that its a known issue and not something we did. We can use the workaround for now.
