### ISSUE TITLE
FEATURE REQUEST: Login Location Montioring

### ISSUE THREAD

**Issue by top-dbrodie** [KelvinTegelaar/CIPP#1077]
Hi,

This would be really cool, if you could make this part of the alerts wizard.
https://www.cyberdrain.com/monitoring-with-powershell-o365-location-alerts/

If we could turn on an alert for monitoring and be able to add 'allowed' locations set per tenant or per user.  These locations could be country, city, region, IP address, ISP etc.  

This would be check the logins and if it's logged in successfully outside of the these regions, it'd send alert.

**Comment by KelvinTegelaar** [comment]
did not use correct template
