### ISSUE TITLE
AddMSPApp: Datto RMM detection is intermittent

### ISSUE THREAD

**Issue by ChrisFoulstone** [KelvinTegelaar/CIPP#1078]
### Description

The current deployment of Datto RMM works fine most of the time. In odd cases, like during recent Datto platform instabilities, it's possible that the AEMAgent.exe exists in programdata, but the associated service has not managed to initialise properly. In this case, the device obviously does not report into DRMM.

Adjusting the detection to path `%programfiles(x86)%\\CentraStage` and file `CagService.exe.config` has provided more reliable results. MEM will then retry the installation if there is a failure due to those odd instances.

### Environment data

```PowerShell
Self-hosted
```

**Comment by ChrisFoulstone** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Changing in next major release. :)

**Comment by ChrisFoulstone** [comment]
> Changing in next major release. :)

Awesome, thank you
