### ISSUE TITLE
[Feature Request]: All Tenant reports to allow more than one hour to complete

### ISSUE THREAD

**Issue by CalTechCSEngineer** [KelvinTegelaar/CIPP#1081]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When I run a report for Basic Authentication for All Tenants it takes longer than one hour for it to complete and so the report is incomplete because the first tenants scanned info has timed out of the cache by that point.

**Comment by KelvinTegelaar** [comment]
We're not upping that limit. If it takes too long I'd recommend doing a tenant per tenant report.
