### ISSUE TITLE
Newly added Conditional Access templates cannot be removed

### ISSUE THREAD

**Issue by Richard5831** [KelvinTegelaar/CIPP#1082]
### Description

We can no longer remove newly added Condititonal Access Policy templates. 

Steps to reproduce on Build-in template:
1. Go to Tenant Administration --> Conditional Access --> List Templates
2. Copy the JSON from a build in Template (for instance: 'Enforce Multi-factor authentication for Static Web Apps')
3. Remove this Build-in Template (this will be succesful).
4. Add the Template; Tenant Administration --> Conditional Access --> Add Template. Paste the copied JSON
5. Remove the Template, this will fail.

The same steps also work with a custom build template.

![Failed_Template_removal](https://user-images.githubusercontent.com/104357126/186610907-43a2c1d3-16f5-43bf-919c-2f63509ba4df.jpg)

### Environment data

```PowerShell
Azure
```

**Comment by Richard5831** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by Richard5831** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
You cant copy and paste the examples as they contain a GUID. If you remove the GUID before pasting. It does work. This is working as intended.

**Comment by Richard5831** [comment]
Thanks Kevin. 
Can we remove the templates who are incorrectly pasted? Because they fail to remove right now.

**Comment by KelvinTegelaar** [comment]
Go to CIPP -> Settings -> Backend -> Resource group

Select the storage account
Click on Storage Explorer (preview)
go to Tables
Templates
Delete the incorrect templates
