### ISSUE TITLE
Your Function App is running in write mode. 

### ISSUE THREAD

**Issue by vitmsadmin** [KelvinTegelaar/CIPP#1090]
Have just updated to version 2.0.3 and receive this message
Your Function App is running in write mode. Please check the release notes to enable Run from Package mode.

Where is the release notes to explain how to enable Run from Package mode.

Or can you advise in this post how to change Function App from running in write mode to run from Package mode.

Thanks
Peter

**Comment by KelvinTegelaar** [comment]
https://github.com/KelvinTegelaar/CIPP/releases :)
