### ISSUE TITLE
[Feature Request]: Templates for Groups

### ISSUE THREAD

**Issue by niegit** [KelvinTegelaar/CIPP#1091]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have several standard groups that we often deploy to tenants while migrating them to the cloud, specific product implementations, customer onboardings, etc. It would be awesome to have "group" templates that we can push down to multiple tenants at once. Being able to reference these groups in other CIPP templates would be ideal, but not sure on the technical side of how to best achieve it. Examples:

"CA Excluded Users" is a group we make for any accounts we exclude from CA policies. Ideally, being able to make a template for this group that we can push to any tenant would be helpful, but furthermore, being able to reference it in the CA templates would be the icing on the cake. I tried poking around with the CA templates and looks like you must reference the Group/Object ID when excluding something other than 'All'. Looking into the New-AzureADGroup commands it doesn't appear that you can set the ObjectID on creation, and I'm not familiar enough with the JSON and automated resource deployment just yet to know if there's another method to achieve this, but referencing the group template in the CA templates somehow would be amazing! Perhaps being able to assign a variable to a group template and pass that into JSON templates?..

"AutoPilot Devices" is a dynamic group we setup whenever we're migrating a customer to the cloud and Intune management. Being able to push this out from CIPP would be nice. In a case like this, the dynamic validation rules are always the same for us, we're just always creating the same things over and over again with each project. 

Furthermore, like the other "templateable" items in CIPP, doing the reverse and creating a template from an existing group would be amazing!

**Comment by KelvinTegelaar** [comment]
group templates implemented in dev.
