### ISSUE TITLE
FEATURE REQUEST: Seamless Single Sign-on status and automation

### ISSUE THREAD

**Issue by Nakazen** [KelvinTegelaar/CIPP#1092]
Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Check and show the current state and expiration date of all the Seamless Single Sign-on Kerberos token status in all the connected tenants at a glance.

When you enable Seamless Single Sign-on Microsoft highly recommends that you rollover the kerberos token every 30 days to ensure an adequate level of security.
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-faq#how-can-i-roll-over-the-kerberos-decryption-key-of-the--azureadsso--computer-account-

This means that for every single tenant this needs to be done and monitored separately.
It would be great if this can be monitored in CIPP to make this easier for a MSP to maintain up to date kerberos keys and possibly automate / partially automate this process.
This feature has been requested at Microsoft for multiple years, but no answer from so far. https://feedback.azure.com/d365community/idea/e0b9222b-b525-ec11-b6e6-000d3a4f0789

If you need any more information please let me know.

**Comment by KelvinTegelaar** [comment]
Can;t be done via Partner creds unfortantelly, feel free to remake in a couple of months when everyone is forced to use GDAP, might be possible then!

**Comment by Nakazen** [comment]
Will do, thanks for looking into it!
