### ISSUE TITLE
FEATURE REQUEST: Chocolatey version attribute

### ISSUE THREAD

**Issue by RickItum** [KelvinTegelaar/CIPP#1093]
-CustomVersion attribute in the cipp options or/and the intunepackage install.ps1 script
preferably with the option to use the --allow-downgrade argument

i think this would be a nice thing to have and should be a minor change.

Another option would be to be able to add custom agruments.

**Comment by KelvinTegelaar** [comment]
This seems like a bad plan - Version pinning is considered insecure by both the Chocolately team and general security advisement. Why exactly are you looking for this version?

**Comment by RickItum** [comment]
We have the following scenario:
We deploy Citrix Workspace via intune using a choco app.
there are to many issues in the latest Citrix release so we cannot use that one.

**Comment by NigelColtellaIT** [comment]
Just to add here we use Unity for our game dev customers and projects are pinned to Major versions but minor versions (security fixes) are applied to all ‘supported’ major versions. We often have to deploy multiple versions of Unity to the same desktop.

**Comment by KelvinTegelaar** [comment]
Not going to do this; I'm seeing more risk than reward of people pinning ancient versions of software. If you'd like this option to be available you can make it for yourself(https://cipp.app/docs/dev/)
