### ISSUE TITLE
FEATURE REQUEST: Azure Reports (Like VMs with Reserved Instance active)

### ISSUE THREAD

**Issue by JMBero** [KelvinTegelaar/CIPP#1094]
Love this project, thank you !

Would be nice to have some basic reporting into Azure.

We use an RMM (Datto) currently for VM specific alerts but there are a few things we have to check in each tenant's Azure portal.

One of our pain points is auditing VMs to make sure compute Reserved Instance is applied.

Other interesting data could be:
VM scheduled maintenance / maintenance windows, unplanned outages (reboots or host moves), and Azure-specific errors would be nice.
Unassigned disks report
List of VM names, region, and size SKU
Network info like vNets, Network security group assignments
Recovery Services vault info / backup reports

Thank you for your consideration.

Jeremy

**Comment by hardinxcore** [comment]
> Love this project, thank you !
> 
> Would be nice to have some basic reporting into Azure.
> 
> We use an RMM (Datto) currently for VM specific alerts but there are a few things we have to check in each tenant's Azure portal.
> 
> One of our pain points is auditing VMs to make sure compute Reserved Instance is applied.
> 
> Other interesting data could be: VM scheduled maintenance / maintenance windows, unplanned outages (reboots or host moves), and Azure-specific errors would be nice. Unassigned disks report List of VM names, region, and size SKU Network info like vNets, Network security group assignments Recovery Services vault info / backup reports
> 
> Thank you for your consideration.
> 
> Jeremy

Posted in wrong project? But I’m also interested in they project you wanted to replying to. ;)

**Comment by JMBero** [comment]
:) Meant for CIPP (I know it's 365 focused but some Azure data would be awesome since multi-tenant management has the same pains as 365).  Was thinking the SAM connection method would allow access to query partner Azure tenants as well.

**Comment by hardinxcore** [comment]
CIPP for Azure! Also a vote from me!

**Comment by KelvinTegelaar** [comment]
No, CIPP is only for m365 management. Azure authentication works entirely different using AOBA or Azure Lighthouse.
