### ISSUE TITLE
[Feature Request]: Add forwarding option for mailboxes

### ISSUE THREAD

**Issue by entrion** [KelvinTegelaar/CIPP#1096]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Looking to add an option under mailboxes to set up forwarding. It is pretty easy in the 365 admin center these days but having it in CIPP would just be another reason not to use the 365 admin center. 

### PowerShell commands you would normally use to achieve above request

Set-Mailbox <Mailbox> -ForwardingAddress <Destination Recipient E-mail address>

**Comment by KelvinTegelaar** [comment]
This already exists in the Offboarding Wizard. Tip; you can run that without any other settings to just enabled forwarding.
