### ISSUE TITLE
Deploy CA - Template Sort Order

### ISSUE THREAD

**Issue by dylanminter** [KelvinTegelaar/CIPP#1097]
### Description

On Step 2 of "Deploy Conditional Access"

The Template list does not sort alphabetically by display name. As expected based on other Template Lists.

![image](https://user-images.githubusercontent.com/12819121/187585002-0139b4cc-58bb-4efc-9c5e-d637d706a7fb.png)

![image](https://user-images.githubusercontent.com/12819121/187585612-ce8a6252-c31a-491e-b632-261291c091e5.png)

### Environment data

```PowerShell
hosted version
```

**Comment by dylanminter** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Nice catch. Fixed in dev :)
