### ISSUE TITLE
[Feature Request]: Add Valimail Dynamics SPF as valid SPF record 

### ISSUE THREAD

**Issue by FrankSchuurman68** [KelvinTegelaar/CIPP#1099]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

when checking individual Domain Check, we have  a SPF record like this: v=spf1 include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all from Valimail.  While dynamically generated by Valimail, the ~all is the same as -all, they state the ~all gives beter results. Maybe this could be added as valid ?

**Comment by KelvinTegelaar** [comment]
We had this discussion before(search for Valimail). Unfortunately, no matter what Vali says; its incorrect usage of SPF. They advise it because it makes deliverability better, but it sacrifices a lot of security.

**Comment by dan-baird** [comment]
@FrankSchuurman68  we used to use Valimail and we chose to move our SPF to -all without issue.
