### ISSUE TITLE
[Feature Request]: Editing of MS Groups - External Senders emailing MS groups

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#1100]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would it be possible to to add an option to "Let people outside the organization email this team" within an MS Group, as per the option in the admin portal below?

![image](https://user-images.githubusercontent.com/105069544/187873400-4582ab1e-9e49-4dbb-ada2-b99b9f0c11a8.png)

**Comment by KelvinTegelaar** [comment]
Yeah we can add this easy. :)

**Comment by dc-castlerock** [comment]
Thanks Kelvin :)

**Comment by KelvinTegelaar** [comment]
in dev.
