### ISSUE TITLE
Disable M365 Group creation by users not working

### ISSUE THREAD

**Issue by JeroenB-Tredion** [KelvinTegelaar/CIPP#1101]
### Description

We testing the standards on our test tenants and we noticed that the standard "Disable M365 Group creation by users" is not changing the setting in Azure. 

We don't have this issue for example with the standard "Disable Security Group creation by users".

![Azure_Screenshot](https://user-images.githubusercontent.com/103125142/187907744-2754169d-6e67-4cc0-9133-1926d07ed436.png)

### Environment data

```PowerShell
We are running CIPP in Azure.
```

**Comment by JeroenB-Tredion** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

***@***.***
Met vriendelijke groet,​​​
Jeroen

Burggraaf
CCT Engineer
***@***.***
***@***.***<https://www.linkedin.com/company/tredion-ict-&-telecom>
***@***.***<https://twitter.com/tredion>
***@***.***<https://www.facebook.com/TredionICTenTelecom>
***@***.***<https://www.youtube.com/channel/UCB1IJPVVaklzLSivZBo8etw>
algemeen
e‑mail
​adres
+31 183 610 550
***@***.******@***.***>
Avelingen‑West 11
​4202 MS  Gorinchem

Disclaimer: Aan dit bericht kunnen geen rechten worden ontleend. Dit bericht is uitsluitend bestemd voor de geadresseerde. ​Als u dit bericht per abuis hebt ontvangen, wordt u verzocht het te vernietigen en de afzender te informeren. ​Wij adviseren u om bij twijfel over de juistheid of de volledigheid van de e-mail contact met de afzender op te nemen.

**Comment by JeroenB-Tredion** [comment]
> Great! I assigned you (@JeroenB-Tredion) to the issue. Have fun working on it!

I made the Bug reports, I think the bot is not functioning correctly.

**Comment by KelvinTegelaar** [comment]
It is, you just replied with all the text, including the assigning.

**Comment by KelvinTegelaar** [comment]
Consulting with MS about this - There's been a graph update that breaks some features.

**Comment by KelvinTegelaar** [comment]
MS is fixing this in the coming 2 weeks. They've made a little mistake on a Graph endpoint.
