### ISSUE TITLE
[Feature Request]: Keep a copy of forwarded email in this mailbox

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#1102]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would it be possible to add a check box "Keep a copy of forwarded email in this mailbox" when setting a mail forward?

![image](https://user-images.githubusercontent.com/105069544/187951157-0b9a24b7-6cf6-45b8-8e56-a6475afee20d.png)

As per setting in MS

![image](https://user-images.githubusercontent.com/105069544/187951251-a89ebfef-64b7-473f-8341-2aa8a2b6e2b3.png)

**Comment by KelvinTegelaar** [comment]
added
