### ISSUE TITLE
[Feature Request]: Ability to create groups of tenants, similar to AllTenants

### ISSUE THREAD

**Issue by CalTechCSEngineer** [KelvinTegelaar/CIPP#1106]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We tend to manage customers in groups by needs and this applies to certain standards/ca policies/namedlocations/etc. being deployed to one group and not another. Being able to define a group, like AllTenants but only being a select number of tenants and then being able to use that group or collection of tenants to apply standards, etc., to would be very useful.

**Comment by KelvinTegelaar** [comment]
No for now. Feel free to rerequest for a later release.
