### ISSUE TITLE
Currently Applied Standards export broken

### ISSUE THREAD

**Issue by CalTechCSEngineer** [KelvinTegelaar/CIPP#1107]
### Description

Under List and Edit Standards is Currently Applied Standards, when I try to export to pdf or csv the name of the file is Standards}.csv/pdf and it properly shows the Tenant name or AllTenants, but the Applied Standards column is just [object Object]

### Environment data

```PowerShell
Azure
CIPP 2.12.0
CIPP-API 2.1.1
```

**Comment by CalTechCSEngineer** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by KelvinTegelaar** [comment]
Fixed
