### ISSUE TITLE
Demo site requires 2FA but none can be provided so access is denied

### ISSUE THREAD

**Issue by vitmsadmin** [KelvinTegelaar/CIPP#1108]
### Description

Trying to show others the benefits of CIPP using demo site but when I access the following URL: https://github.com/KelvinTegelaar/CIPP/blob/website/docs/general/demo.md

Using incognito mode, user name and password provided on page, you are asked to enter 2FA code.  

How can I provide a code displayed on authenticator app or mobile device when it is not my account?

Please create an app password to bypass 2FA and provide this so we can access demo site.

### Environment data

```PowerShell
Demo Site
https://github.com/KelvinTegelaar/CIPP/blob/website/docs/general/demo.md
```

**Comment by vitmsadmin** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by KelvinTegelaar** [comment]
Demo is disabled due to abuse.
