### ISSUE TITLE
[Feature Request]: Add link to Release Notes on "Your Function App is running in write mode. Please check the release notes to enable Run from Package mode."

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#1116]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Dashboard message re Run Mode should include a link to Release Notes https://github.com/KelvinTegelaar/CIPP/releases/tag/v2.1.11.0 or specific instructions on how to enable Run mode

I spent several hours finding this page :)

**Comment by TechEnvyPtyLtd** [comment]
I also couldn't find the documentation and when googling and going to this page (https://cipp.app/releases/) it's only showing old release notes.

**Comment by KelvinTegelaar** [comment]
added
