### ISSUE TITLE
Attempting to remove Intune Windows configuration profile templte

### ISSUE THREAD

**Issue by RobWellesley** [KelvinTegelaar/CIPP#1118]
I list the templates, click the Bin icon and get the following for all templates tried so far.
templates were created by listing a profile for a client, then creating a template from that.
error is:
Failed to remove template: Cannot validate argument on parameter 'Entity'. Value cannot be null. (Parameter 'source')

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
