### ISSUE TITLE
Suspect '&' In Company Name reduces functionality.

### ISSUE THREAD

**Issue by TechEnvyPtyLtd** [KelvinTegelaar/CIPP#1119]
### Description

Some CIPP buttons are not working and I suspect it's when the company has an ampersand in the name as I'm seeing that pattern only.

**Issue One**
Click on Tenant Administration -> Administration -> List Tenants
Click on the '...' for a Tenant that contains a & in the Name and the button does nothing (no menu popups up etc).

**Issue Two**
Click on Tenant Administration -> Administration -> Standards (BPA)
Clicking on unused licenses for a company that contains the & in the name doesn't do anything (like it's not hyperlinked).

### Environment data

```PowerShell
Running latest self hosted (2.12.0 / 2.1.1) and recently re-deployed CIPP (issue existed before and after).
```

**Comment by TechEnvyPtyLtd** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by adamburley** [comment]
Attempted to replicate - Ellipsis menu in *List Tenants* responds as I'd expect.  I have seen the error you're reporting - usually the ellipsis is unresponsive but a blinking cursor appears, as if the input is being rendered as a text field. I haven't been able to narrow down when it occurs.

I **am** able to replicate the error in Standards > Best Practices Analyzer.  It occurs if the tenant Company Name value contains any symbol other than period (.).  My sample pool shows failures like this on comma, ampersand, hyphen, and parentheses. It appears the Company Name value may not be urlencoded for that query.

```
Something went wrong.
TypeError: t.filter is not a function

P@https://cipp.ashton.tools/static/js/main.98513513.js:2:15239
div
27998/Rr<@https://cipp.ashton.tools/static/js/main.98513513.js:2:201597
div
27998/Nr<@https://cipp.ashton.tools/static/js/main.98513513.js:2:198029
div
27998/Cr<@https://cipp.ashton.tools/static/js/main.98513513.js:2:198299
div
t@https://cipp.ashton.tools/static/js/main.98513513.js:2:130374
27998/wr<@https://cipp.ashton.tools/static/js/main.98513513.js:2:199028
ce@https://cipp.ashton.tools/static/js/main.98513513.js:2:45981
ie@https://cipp.ashton.tools/static/js/main.98513513.js:2:44736
div
M@https://cipp.ashton.tools/static/js/6971.dd17bab9.chunk.js:1:6566
se@https://cipp.ashton.tools/static/js/main.98513513.js:2:44993
f@https://cipp.ashton.tools/static/js/main.98513513.js:2:2210782
W@https://cipp.ashton.tools/static/js/main.98513513.js:2:41115
Suspense
p@https://cipp.ashton.tools/static/js/main.98513513.js:2:2210282
u@https://cipp.ashton.tools/static/js/main.98513513.js:2:2207409
b
t@https://cipp.ashton.tools/static/js/main.98513513.js:2:2377690
u@https://cipp.ashton.tools/static/js/main.98513513.js:2:2204538
```

**Comment by KelvinTegelaar** [comment]
Can't replicate in neither dev nor prod. The issue @adamburley has is related to another issue that has been solved in dev.
