### ISSUE TITLE
[Feature Request]: Add SchedulingMailbox to Exchange Standards - Disable Shared Mailbox AAD Accounts

### ISSUE THREAD

**Issue by signalit** [KelvinTegelaar/CIPP#1124]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

To enhance the Exchange Standard of "Disable Shared Mailbox AAD accounts", it would be great if this would include the mailboxes that are created when a user or admin creates a Bookings page. Since a Bookings page generates a user account when created, I would think that this could be as vulnerable as a regular shared mailbox user account. 

### PowerShell commands you would normally use to achieve above request

To find the Bookings mailboxes you can use:

Get-EXOMailbox -Filter {RecipientTypeDetails -eq "SchedulingMailbox"}

**Comment by KelvinTegelaar** [comment]
added
