### ISSUE TITLE
MSP App - Ninjaone asking for Chocolatey

### ISSUE THREAD

**Issue by mrapoc** [KelvinTegelaar/CIPP#1127]
### Description

Instead of asking for a URL or script etc it appears to have a placeholder for the field as Chocolatey package name. I saw in discord this was opened as an issue before but I couldn't find it hence opening this. 

### Environment data

```PowerShell
Azure, self hosted, up to date
```

**Comment by KelvinTegelaar** [comment]
Yeah, This is a bug. @stephen-iamroot @gavsto you guys should help on this. How do we get an intune win32 app for Ninja without having a publicly downloadable agent that we can install with parameters. :) Plz ask technical people.

**Comment by KelvinTegelaar** [comment]
Discussed with Ninja; Leaving this open for a bit. :)
