### ISSUE TITLE
New alerts not visible in Alerts Wizard

### ISSUE THREAD

**Issue by karstentredion** [KelvinTegelaar/CIPP#1131]
### Description

In the new update 2.13.0 there should be extra options for the following:
![image](https://user-images.githubusercontent.com/47554581/192159181-3f972724-29ae-49ac-ae2c-61f8634dfebf.png)

If you go to the Alert Wizard there isn't  any option to select them:
![image](https://user-images.githubusercontent.com/47554581/192159205-e5a4434c-cfe7-4767-b17d-5d48b99c298d.png)

### Environment data

```PowerShell
2.13.0 Frontend
2.2.0 Backend
Azure hosted
```

**Comment by karstentredion** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
You're absolutely right. Small oversight and will be released with fridays out-of-band release.

**Comment by KelvinTegelaar** [comment]
fixed in dev
