### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by Jeremyp87** [KelvinTegelaar/CIPP#1134]
### Description

Deploy CIPP with default settings, worked in previous versions, deployment error

cipp4c6ha/web
Microsoft.Web/sites/sourcecontrols
NotFound

{
    "status": "Failed",
    "error": {
        "code": "NotFound",
        "message": "Cannot find SourceControlToken with name GitHub.",
        "details": [
            {
                "message": "Cannot find SourceControlToken with name GitHub."
            },
            {
                "code": "NotFound"
            },
            {}
        ]
    }
}

### Environment data

```PowerShell
Azure, Central US, deploy as global admin, github token is correct, app registration was deleted before deploy, resource group cleared.
```

**Comment by KelvinTegelaar** [comment]
https://github.com/KelvinTegelaar/CIPP/issues/1133
