### ISSUE TITLE
BUG: Root Sharepoint does not match client name/primary domain

### ISSUE THREAD

**Issue by SEI-Mkittok** [KelvinTegelaar/CIPP#1135]
I have found several tenants where their root SharePoint doesn't follow the default schema for the root SharePoint admin URL. An example is a tenant we took over from AppRiver that uses a root URL (e.g.: appriver1234567890-admin.sharepoint.com) This results in a dead link when following via CIPP.

**Comment by KelvinTegelaar** [comment]
confirmed in Discord and planned for maybe fridays out of band release, or otherwise the week after for the normal release.

**Comment by SEI-Mkittok** [comment]
So, is this going the way of "it's a feature!"?
