### ISSUE TITLE
[Feature Request]: Ability to filter in reports such as MFA report

### ISSUE THREAD

**Issue by jchurchh** [KelvinTegelaar/CIPP#1136]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The MFA reports & User list are great and I use this to provide exports to the clients, however the reports are filled with accounts that are already disabled.

It would be great to have the ability to filter for enabled accounts only.

### PowerShell commands you would normally use to achieve above request

n/a

**Comment by KelvinTegelaar** [comment]
Already possible, but I'll add it as an actual filter option: the text filter is "accountEnabled":true
