### ISSUE TITLE
Conditional Access state is not evaluated in ListMFAUsers

### ISSUE THREAD

**Issue by adamburley** [KelvinTegelaar/CIPP#1138]
### Description

When running the MFA Report, Conditional Access (CA) policies are evaluated for AllUsers and membership but not for the state of the policy.  A policy in *Disabled* or *Report Only* status will still show as enforcing MFA in the CIPP view.  Graph API conditionalAccessPolicy resource provides a [state](https://learn.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy)  property but this is not evaluated by the [ListMFAUsers](../../CIPP-API/tree/master/ListMFAUsers) API endpoint.

**Initial triage** - Modify line 26 of `run.ps1` from

```PowerShell
            if (($policy.grantControls.builtincontrols -eq 'mfa') -or ($policy.grantControls.customAuthenticationFactors -eq 'RequireDuoMfa')) {
```

to
```PowerShell
            if ($policy.state -ieq 'enabled' -and (($policy.grantControls.builtincontrols -eq 'mfa') -or ($policy.grantControls.customAuthenticationFactors -eq 'RequireDuoMfa'))) {
```

**Long term** - Add a description modifier to the policy name to indicate its state, similar to the *Excluded from...* marker.

![Screenshot - MFA Report view showing enforcement via All Users](https://user-images.githubusercontent.com/52085927/193034243-8ab05664-1e93-4a81-8f6c-b105b5fa01fc.png)

![Screenshot - CA policy in Report-Only](https://user-images.githubusercontent.com/52085927/193035169-46a90b9d-a538-403f-9eac-ab7fc3fb6dfe.png)

### Environment data

```PowerShell
Hosted - Current
```

**Comment by KelvinTegelaar** [comment]
Weren't you going to make a PR for this?! ;) Kidding.  I took a slightly different approach and added it to the "Enforced via" text. It looks nicer imho and doesn't make the table even larger causing UX issues.
