### ISSUE TITLE
GDAP Migration Tool Fails Mapping Groups, and creating groups

### ISSUE THREAD

**Issue by dag-gremache** [KelvinTegelaar/CIPP#1141]
### Description

After setting up all the required permissions, and running the migration tool, we get the following errors. 

Also,  If we choose Helpdesk Role in GDAP migration tool for 10 clients, then in Azure AD we will see a total 10 M365 GDAP Helpdesk groups. Is that expected behavior? See error below. 

```
Migration Failed. Could not create group mapping for group b9f7da77-6429-4b6... Cannot process the request because it is malformed or incorrect.

Migration Failed. Could not create group mapping for group 06228862-f822-451b-b9fa-cb4357c4ea83 2e45dc6c-8559-4555-a7d2-fef832349cc0 536ba29c-37ef-4afb-915e-2b00f486d201 82578a7c-abb2-41be-881c-10997c09682e....: An unexpected error occurred in the server.
```
![image](https://user-images.githubusercontent.com/95181778/193439140-48efa908-cfb9-4bca-b904-3ed3efde680b.png)

We confirmed that the all the customers get added to the Customers | Granular administration list, multiple Groups for the same role get created in Azure. 

### Environment data

```PowerShell
We are running the latest version of CIPP. 

Version Frontend
Latest: 2.14.0
Current: 2.14.0

Version Backend
Latest: 2.3.0
Current: 2.3.0

Permissions Check: 
Your refresh token matches key vault.
Your access token contains the MFA claim.
Your Secure Application Model has all required permissions
```

**Comment by KelvinTegelaar** [comment]
![image](https://user-images.githubusercontent.com/49186168/193443598-d28ff6cd-fa26-4aec-a7ea-794f899019d4.jpeg)

We're currently hitting the apis a bit too hard, execute whats on the screenshot and you'll be good to go.
