### ISSUE TITLE
BUG: The service principal cannot be created, updated, or restored because the service principal name is already in use

### ISSUE THREAD

**Issue by Nepenthe-x64** [KelvinTegelaar/CIPP#1142]
After clicking the Enable GDAP API button I'm getting the following error:

Failed to add SPN. Please manually execute 'New-AzureADServicePrincipal -AppId <appID ommited for security>' The error was Insufficient privileges to complete the operation.

When I execute the command in Azure AD PowerShell I get the following message:

New-AzureADServicePrincipal : Error occurred while executing NewServicePrincipal
Code: Request_MultipleObjectsWithSameKeyValue
Message: The service principal cannot be created, updated, or restored because the service principal name
https://api.partnercustomeradministration.microsoft.com is already in use.
RequestId: bf68ceca-bbff-42f9-a80f-e3d46a1c58c9
DateTimeStamp: Tue, 04 Oct 2022 03:44:47 GMT
HttpStatusCode: Conflict
HttpStatusDescription: Conflict
HttpResponseStatus: Completed
At line:1 char:1
+ New-AzureADServicePrincipal -AppId

When I look in Enterprise apps the AppId it lists is tied to an app called Partner Customer Delegated Administration, but I can't update the API permissions per your KB.  How do I proceed from here?

Thanks,

Adam

**Comment by KelvinTegelaar** [comment]
Not a bug. Someone already used the GDAP migration tool so you can skip that step.
