### ISSUE TITLE
[Feature Request]: Disable inactive guest accounts

### ISSUE THREAD

**Issue by SEI-Mkittok** [KelvinTegelaar/CIPP#1143]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Normally this type of automation requires "Identity Governance" but this is a heavy lift for most SMBs and frankly overkill. 
Monitoring and reducing the guest account clutter in an environment makes for more efficient account management as well as increased security.
I would request this be added to a Standards Policy

### PowerShell commands you would normally use to achieve above request
```powershell
$date = (Get-Date).adddays(-90)
$zuludate = get-date $date -format "yyyy-MM-ddTHH:mm:ssZ"
$users = Get-MgUser -Filter "signInActivity/lastSignInDateTime le $zuludate"
$users | ? {$_.UserType -eq "Guest"} | ForEach-Object {@{ UserId=$_.Id}} | Update-MgUser -Settings $DisableUserHash -WhatIf
```

**Comment by KelvinTegelaar** [comment]
added in dev
