### ISSUE TITLE
"Copy group membership from other user" unexpected behaviour

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#1146]
### Description

We have numerous groups that themselves have membership of other groups.

(For the curious - Job role security group, and each job role has security groups associated with various permissions for different non inherited Sharepoint permissions for folders).

I've used the "Copy group membership from other user" a few times at less complex clients without issue, however, this is the first time I tried it a bigger one with the above structure.

It did copy the direct permissions - however, it also copied all the sub group memberships as well.

I don't know if this by design or intention, however, it certainly isn't what I wanted to happen, so, raising as a bug to check.

### Environment data

```PowerShell
Hosted in Azure/latest version
```

**Comment by KelvinTegelaar** [comment]
That's expected behaviour, it looks at *all* the groups another user is in, and copies that membership.

**Comment by wilhil** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

(as you said via DM, and don't want this auto closing...)

**Comment by wilhil** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
