### ISSUE TITLE
BUG: When using the GDAP Migration tool it stalls

### ISSUE THREAD

**Issue by RUSITSSVC** [KelvinTegelaar/CIPP#1147]
When we have tested using the GDAP tool we have seen it will create the relationship on the customer portal but is not adding the roles. In the CIPP portal under the status it has been stuck on Step 2: Groups created, creating new GDAP relationship for over 12 hours on our test portal. Suggestions on how to restart this on this portal?

**Comment by KelvinTegelaar** [comment]
This tool is offered as-is, without support, warranties, or guarantees. If you are having GDAP migration problems, contact Microsoft via the Partner Support Center.
You can always try the migration process again.

**Comment by chrisdeke** [comment]
Having the same issue, have tested it multiple times, the process seems to stall out and get stuck. 
Have some stalled at Step 2: Groups created, others at Step 3: GDAP Relationship active.

Have retried multiple times over the last week, they all seem to just get stuck. Have not managed to get any to work. 

Understand its offered as-is, just adding our experience to the record in case it helps anyone else.
