### ISSUE TITLE
[Feature Request]: Batch Convert Mailboxes to Shared/User Mailbox

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1148]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Often during 365 migration projects it becomes neccesary to batch convert mailboxes to shared/user mailboxes, this can be achieved in PS, so hopefully we can do it in cipp, whether in Mailboxes section or as a seperate tool

appreciate though that at the moment one cannot multi-select mailboxes in cipp, so that may need to come first?

### PowerShell commands you would normally use to achieve above request

foreach {Get-Mailbox -Identity $_.Email | Where-Object {$_.RecipientTypeDetails -eq "UserMailbox"} | Set-Mailbox -Type Shared}

https://www.alitajran.com/bulk-convert-user-mailbox-to-shared-mailbox-with-powershell/

**Comment by KelvinTegelaar** [comment]
Batch options are coming in a later release.
