### ISSUE TITLE
Office App deployment results in error

### ISSUE THREAD

**Issue by Eruestani** [KelvinTegelaar/CIPP#1151]
### Description

When attempting to add an office app. we get an error returned as the default file format version is not set.

1 - Go to Endpoint management > Applications > Add Office App

2 - Choose Tenant

3 - Fill out information as below:
![image](https://user-images.githubusercontent.com/2509864/195136525-952fba99-553d-4f55-93d0-40f8ed7bc6d4.png)

4 - Confirm and receive below error:
![image](https://user-images.githubusercontent.com/2509864/195136182-90cf9a92-7a23-4df5-bee0-32324d8f6e6f.png)

What is expected:

![image](https://user-images.githubusercontent.com/2509864/195137102-332e1ca1-5db7-4a7c-a343-c59d8a350bc9.png)

### Environment data

```PowerShell
Self-hosted on Azure

Frontend Version: 2.14.0
Backed Version 2.3.1
```

**Comment by Eruestani** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by Eruestani** [comment]
I also could not find any documentation on Office App deployment in the user guide.
![image](https://user-images.githubusercontent.com/2509864/195138275-9e19eb2c-2de5-47e0-b459-3583f306b1f0.png)

**Comment by KelvinTegelaar** [comment]
Feel free to update the docs, and bug confirmed. fixing in next release :)

**Comment by KelvinTegelaar** [comment]
And fixed in dev, seems like this became a mandatory field recently.
