### ISSUE TITLE
Edit User Usage Location Populate

### ISSUE THREAD

**Issue by schneiderbw** [KelvinTegelaar/CIPP#1153]
### Description

When editing an existing user, the Usage Location is populated in the Raw User Data section, but not in the Account Details section of the edit user screen.  Could we prefill the Usage Location with the current user information?

Screenshot: https://i.imgur.com/m5JQU92.png

### Environment data

```PowerShell
Azure

Frontend: 2.14.0 (Latest)
Backend: 2.3.1 (Latest)
```

**Comment by KelvinTegelaar** [comment]
This is because your usage location in Avatar -> Profile is set to blank, either set it to the preferred location or anything not blank.

**Comment by schneiderbw** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by dsghi** [comment]
@KelvinTegelaar, this should be classified as a bug; the usage location should be populated from the user account, not the logged-in user, as user accounts can vary per tenant, and we're not always managing a tenant that is in our geographic location.
