### ISSUE TITLE
Tenant->Standards->Individual Domain Check isn't respecting MX record priority

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1154]
### Description

Priority	Hostname
10	{redacted}.com.1.0001.arsmtp.com.
20	{redacted}.com.2.0001.arsmtp.com.
99	d232434b.ess.barracudanetworks.com.
99	d232434a.ess.barracudanetworks.com.

while the MX Results card erroneously shows

MX Results
Mail Provider: Barracuda Email Security Service
Mail exchanger records record(s) are present for this domain.

Mail Provider should show AppRiver

### Environment data

```PowerShell
Hosted

V 2.14FE
V 2.3.1 BE
```

**Comment by johnduprey** [comment]
This is likely a bug with run from package mode - I've got a fix in place already:
https://github.com/KelvinTegelaar/CIPP-API/pull/222/commits/7b08f43feceeac0faaf0d1166dcae0576181caec

**Comment by KelvinTegelaar** [comment]
Yeah, tested and resolve in dev :)
