### ISSUE TITLE
Exchange Token Error

### ISSUE THREAD

**Issue by dsghi** [KelvinTegelaar/CIPP#1156]
### Description

Any advice on how to deal with this error?

Failed to connect to Exchange: Failed to obtain Classic API Token for <domain> - {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-11-10T02:49:07.6225734Z and the maximum allowed lifetime for this request is 3600."}

I ran the clear token cache script, guessing it may help, but it didn't.

### Environment data

```PowerShell
Azure hosted
Token refresh dates
Refresh token: 2022-10-09
Exchange Token: 2022-10-09
Version Frontend
Current: 2.14.0
Version Backend
Current: 2.3.1
```

**Comment by KelvinTegelaar** [comment]
Not a bug. Use the troubleshooting guides or community support to try and solve this.
