### ISSUE TITLE
GDAP Migration Failed error

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#1160]
### Description

When running the GDAP wizard i first get the following error:

`Failed to add SPN. Please manually execute 'New-AzureADServicePrincipal -AppId XXXX-ec63-45fb-976f-5d45a7d4bb91' The error was The service principal cannot be created, updated, or restored because the service principal name https://api.partnercustomeradministration.microsoft.com is already in use.`

Proceeding on the basis that this means it is already enabled, i select a single tenant but then get this error:

`Migration Failed. Could not create relationship: Object reference not set to an instance of an object.
`

### Environment data

```PowerShell
Running version 2.15.0/2.4.0
```

**Comment by KelvinTegelaar** [comment]
Please check the docs at https://cipp.app/docs/user/usingcipp/GDAP/migration/#using-the-gdap-wizard

**Comment by matstocks** [comment]
Turns out i had 4 SAM applications in our account from previous CIPP deployments. i'd updated the wrong one.
