### ISSUE TITLE
[Feature Request]: On copy from other user group permissions - also copy shared mailboxe permissions.

### ISSUE THREAD

**Issue by TricoreService** [KelvinTegelaar/CIPP#1161]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When creating new user accounts it mostly occurs that we have to take a copy from a user who works in the same function as the new user. It's very useful to use the copy group membership part which saves a lot of time, but we also have to make sure the user has access to the same mailboxes (for example, orders/invoices/...).
Currently we still have to manually add those permissions, but I'd like to know if it could be implemented that we also have the option to copy those permissions when creating a user. (or even editing when for example a function within the comany changes)

### PowerShell commands you would normally use to achieve above request

Get-Mailbox | Get-MailboxPermission -User ToCopyFromUser
Afterwards depending on automapping or not use the Add-MailboxPermission command.

**Comment by TricoreService** [comment]
Besides being able to perform this, it would also be useful to show all mailboxes to which this user has access. (same like it shows of which groups the user is a member).

**Comment by KelvinTegelaar** [comment]
No, not going to implement this. This seems like a recipe for disaster.
