### ISSUE TITLE
[Feature Request]: Vulnerability dashboard 

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#1162]
**Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.**

Similar to how the Incidents & Alerts dashboards work, could there be a dashboard that would surface the endpoint Vulnerability info from each tenant's Security center?

A multi-tenant dashboard to review  vulnerabilities would make it easier to stay on top of these for clients. 

Benefit to MSPs - currently MSPs are using a bunch of different expensive 3rd-party solutions that fail in one of two ways: 1. no agent, net scan only, leads to incomplete results, OR 2. agent-based, leads to additional agents to install + maintain and is itself another potential attack vector. 

Therefore reading this data from embedded Defender endpoint components is the best possible solution, if we could just make it available in a multi-tenant dashboard. 

**PowerShell commands** none that I am aware of, this is a request to display something in a GUI

**Comment by KelvinTegelaar** [comment]
Thisnis already in dev.
