### ISSUE TITLE
[Feature Request]: Allow customization of TAP policy for TAP standard

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#1163]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We often find we are needing TAP for multiple use, over a specific period of time, in order to help get a device setup, and during new user onboarding or device swaps.

It would be extremely helpful for our techs if we had complete control over the TAP policy options that are provisioned with the TAP standard. 

![image](https://user-images.githubusercontent.com/17422069/196467374-cb339a9d-fede-4218-a148-6108e6fe1627.png)

### PowerShell commands you would normally use to achieve above request

not applicable

**Comment by KelvinTegelaar** [comment]
I am only adding the option "Is Usable Once" as I am too worried that other MSPs might use this with infinite lifetimes to be able to get access to accounts easily.
