### ISSUE TITLE
[Feature Request]: SharePoint Show Site Name

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#1165]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

In the SharePoint tab, add the "Site Name" to match the website view.
![image](https://user-images.githubusercontent.com/15746724/196480633-e58c1a9b-ad4b-4042-a698-8ced25f11178.png)

It would be good if we could copy the URL onedrive sync button.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/15746724/196481407-de740546-28dc-4807-8c01-cbc44be6e860.png)

### PowerShell commands you would normally use to achieve above request

pass

**Comment by KelvinTegelaar** [comment]
Not possible with the way we access this data, we get this from a report and the API to retrieve these details is much heavier, causing slowness in the application.
