### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by mmartinFF** [KelvinTegelaar/CIPP#1166]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would like to have an additional field on the MFA report that notates the assigned user license and if possible exclude mailboxes that don't have licenses from the report entirely. We often finding conflicting information with the current report, and this would help us in our quarterly meetings with our clients to explain what is missing and how we need to address it moving forward using just one report.

**Comment by KelvinTegelaar** [comment]
No, you can compile this data yourself. This report is already quite heavy, adding this data is fairly useless.
