### ISSUE TITLE
[Feature Request]: add "State", "Office Location", and "Fax Number" as editable fields when editing a user

### ISSUE THREAD

**Issue by michael-squeezetech** [KelvinTegelaar/CIPP#1167]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Some companies use "State", "Office Location", and "Fax Number" to automatically populate information in signatures or assign users to dynamic groups and MSPs would need to edit and manage for some clients

### PowerShell commands you would normally use to achieve above request

Set-MsolUser -UserPrincipalName $username -State $state -Office $office -Fax $fax

**Comment by KelvinTegelaar** [comment]
this wasn't available in the API at the time we made the add user component, it is now, so it's added, except for Fax. number, as that's a deprecated field.

**Comment by guhri88** [comment]
I am not seeing the Office or State options when editing or creating new users?
Has this been removed? could we get it added back?

We use it to separate locations for billing and signatures.
