### ISSUE TITLE
[Feature Request]: Sorting of user sign in logs, and/or Export logs to CSV to have a standard date format

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#1169]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I'm trying to investigate a user and the "user sign in logs" section has date in a completely random order (attached at the bottom)

It would be great if the grid allowed sorting, however, I've tried exporting to CSV, but, this makes the date column export with the full date as "Friday, October 14, 2022 11:56:11 AM", which does not allow it to be sorted neatly. It isn't the end of the world to delimiter on the comma, but, just throwing this out there as a low low priority request for one day!

![image](https://user-images.githubusercontent.com/2283808/198050164-19993822-fb8f-4aa3-a90c-a56ad0707280.png)

**Comment by KelvinTegelaar** [comment]
Fixed in #1171

**Comment by PeakeIT** [comment]
Looks like this was fixed on the report but still shows random order under the user details page. Not a big deal as you can just go to the report page instead.
