### ISSUE TITLE
Identity Management->Reports->Sign-in Report Issues

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1171]
### Description

1. Date sort is oldest to newest.  Should be newest to oldest (newest at top)
2. Additional Details column is clipped and I'm unable to select the full text (chrome)
3. CSV export doesn't match report (doesn't contain Failure reason - "[Object][Object]" or the Additional Details) which is more important because you can't get to the full text (see #2).
4. Clicking to change the sort on any column (so far) resizes the hell out of the column widths.  Failure Reason becomes unreasonably wide, but now I can at least see the entire Additional Details column.

### Environment data

```PowerShell
Hosted version 
Frontend 2.15.0
Backend 2.40
```

**Comment by KelvinTegelaar** [comment]
Marked as valid

**Comment by KelvinTegelaar** [comment]
Most are fixed, except 4. We use a component that resizes columns dynamically based on which columns contain data and which not, we can set maximum sizes but that often makes the usability lower, so that's a wontfix.
