### ISSUE TITLE
Install fails on Cipp-SAM Stage 2 - 2.16.0

### ISSUE THREAD

**Issue by burtonmsp** [KelvinTegelaar/CIPP#1174]
### Description

Set up SAM using wizard, selecting MS Partner.
Click step 1 and connect to PowerShell
Click Next on step 2 and it fails with errors:
address bar: api/ExecSAMSetup?error=invalid_client&error_description=AADSTS650051%3a+Claim+is+invalid%3a+Vulnerability.Read+does+not+exist+on+resource+application+fc780465-2017-40d4-a0c5-30XXX1b92.%0d%0aTrace+ID%3a+326cXXXd3-9c7f-44ee-935a-a51bXXX21600%0d%0aCorrelation+ID%3a+807c5e2d-58fc-4908-a4d9-74ec431XXX%0d%0aTimestamp%3a+2022-10-29+16%3a19%3a42Z#

Page: Client ID was not found in Azure. Try waiting 10 seconds to try again, if you have gotten this error after 5 minutes, please restart the process.

Confirmed that Cipp-SAM app has been created, but if you try to accpet for org, it says claim not valid

### Environment data

```PowerShell
Azure, v2.16.0 new setup.
Created dedicated admin user with partner admin etc. Invited as admin and accepted/set up.
Cipp loads fine, but Cipp-SAM section fails.
```

**Comment by burtonmsp** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by burtonmsp** [comment]
I had to delete the 2 MS Defender API permissions from the Cipp-SAM application

**Comment by KelvinTegelaar** [comment]
This is not the place for support. You can get a hosted version for basic support, or community support on our discord.

**Comment by burtonmsp** [comment]
not asking for support. If we don't have the defender licenses we should be able to exclude that so we don;t fail permissions check?
