### ISSUE TITLE
Possible to deploy using Docker / K8s?

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1175]
We are a heavy Kubernetes user - all of our internal apps are dockerized and run in a k8s cluster.

I'm wondering, is it possible the way this app is written now to dockerize it?

IE, are there specific reasons that require it to run as an Azure Static Web App?

**Comment by KelvinTegelaar** [comment]
No, cipp is writen specificly for swa and azure functions, you cannot use it in a container.

**Comment by joeldeteves** [comment]
Answered my own question - TLDR; even though it's not supported (and I don't expect you to support it), it *is* possible to run Azure functions in a local docker container https://hub.docker.com/_/microsoft-azure-functions-node

**Comment by KelvinTegelaar** [comment]
Even then it wont work, you will still need something to handle authentication, which is currently done by swa. To even be able to access the frontend you will need to completely recode how the frontend handles claims, Then there's credential management which requires kv, and then you'll need to make the api endpoint available via the same endpoint somehow. Even if you hack it all together it's going to be a terrible experience.
