### ISSUE TITLE
Documentation - Click to Deploy failure on Storage Account name - 2.16.0

### ISSUE THREAD

**Issue by arejaytee** [KelvinTegelaar/CIPP#1176]
### Description

The "Base Name" option in Instance Details in Azure custom deployment allows for characters that are not supported for the storage account naming conventions.

`{"code":"InvalidTemplateDeployment","details":[{"code":"PreflightValidationCheckFailed","message":"Preflight validation failed. Please refer to the details for the specific errors.","details":[{"code":"AccountNameInvalid","target":"az-cippstgd2zxz","message":"az-cippstgd2zxz is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only."}]}],"message":"The template deployment 'Microsoft.Template-20221031144820' is not valid according to the validation procedure. The tracking id is ''. See inner errors for details."}`

### Environment data

```PowerShell
Click to Deploy in Azure
```

**Comment by KelvinTegelaar** [comment]
You've added az- yourself, that's not a part of the default template.
