### ISSUE TITLE
Post GDAP Authentication Issues

### ISSUE THREAD

**Issue by Danpoulter97** [KelvinTegelaar/CIPP#1177]
### Description

I know that there is limited or no support in relation to the GDAP Migration tool but, I can perform the migration fine but once the DAP permissions are removed, I can no longer access the tenant. I get the error 'The user you have used for your Secure Application Model is a guest in this tenant, or your are using GDAP and have not added the user to the correct group. Please delete the guest user to gain access to this tenant.' (There is not a guest user associated with this)
I have added the CIPP-SAM user and my own user to the below groups/roles:
GDAP 365 - Application Administrator
GDAP 365 -User Administrator
GDAP 365 -Intune Administrator
GDAP 365 -Exchange Administrator
GDAP 365 -Security Administrator
GDAP 365 -Cloud App Security Administrator
Am I missing a critical group?

I am running the latest version of CIPP and CIPP-API.

### Environment data

```PowerShell
Hosted:
Version Frontend
Latest: 2.16.0
Current: 2.16.0

Version Backend
Latest: 2.5.2
Current: 2.5.2
```
Edit: I have followed the steps here https://cipp.app/docs/user/usingcipp/GDAP/migration/#recommended-roles-for-cipp

**Comment by icisupport** [comment]
We're having this issue as well.

**Comment by KelvinTegelaar** [comment]
![image](https://user-images.githubusercontent.com/49186168/199070706-73ec676a-f4cb-400d-8a1c-dce122c13a6e.png)
