### ISSUE TITLE
CIPP SAM Wizard - Permissions deprecated

### ISSUE THREAD

**Issue by arejaytee** [KelvinTegelaar/CIPP#1179]
### Description

Using the Wizard it was failing on Admin consent, I had to remove the following entries for it to complete successfully.

WindowsDefenderATP (2)
41269fc5-d04d-4bfd-bce7-43a51cea049a
Delegated No
63a677ce-818c-4409-9d12-5c6d2e2a6bfe
Application No

### Environment data

```PowerShell
Azure
```

**Comment by arejaytee** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug. Make sure you update to the latest version.
