### ISSUE TITLE
[Feature Request]:  Add option to let users request APP admin consent

### ISSUE THREAD

**Issue by karstentredion** [KelvinTegelaar/CIPP#1181]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be nice to have the option in the standards wizard to let users request admin consent for apps. Now the user needs to create a manual support ticket while the options to automate this are available in the Azure GUI. We are already using the require admin consent standard in CIPP.

The option in Azure:

It could be an idea to add the "reviewer type" for Global admins or make an input field in the CIPP wizard.
 
![image](https://user-images.githubusercontent.com/47554581/199221337-9646f305-a30e-4d9a-8fe5-7aa5c4bbe1c9.png)

### PowerShell commands you would normally use to achieve above request

The commands that can be used for Graph:
https://learn.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&tabs=http

**Comment by KelvinTegelaar** [comment]
Thank you for creating a feature request!

Your current priority is set to "No Priority". No Priority Feature requests automatically get closed in two days if a contributor does not accept the FR.
            
If you are a sponsor you can request an upgrade of priority. To upgrade the priority type "I would like to upgrade the priority". 

If you want this feature to be integrated you can always do this yourself by checking out our contributions guide at https://cipp.app/docs/dev/.

Contributors to the CIPP project reserve the right to close feature requests at will.  If you'd like this feature request to be assigned to you, please comment "I would like to work on this please!".
