### ISSUE TITLE
[Feature Request]: Add function to grant roles to users

### ISSUE THREAD

**Issue by leonardder** [KelvinTegelaar/CIPP#1182]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

For Azure Static Web Apps, there is a function in preview that allows you to [assign roles using a severless function](https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-authorization?tabs=function).
Would it be possible to add such a function to the function app as well as add per role Azure AD groups to the tenant CIPP is running on? This would allow granting access to CIPP based on Azure AD groups rather than the current invitation system. It would also introduce the possibility to utilize [Privileged identity management](https://learn.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-configure) if I'm correct.

**Comment by KelvinTegelaar** [comment]
Not possible, this would increase the complexity extremely, not allow automated deployments, and remove too many protection that SWA auth puts in place.
