### ISSUE TITLE
[Feature Request]: Add Delegated Admins Report

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1184]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

please can you add a "DAP/GDAP" REPORT under tenants\reports\graph explorer?

so we can see easily who has delegated access to our customers tenants

**Comment by KelvinTegelaar** [comment]
There's no Graph endpoint for this :(
