### ISSUE TITLE
[Feature Request]: List Onedrive URLS

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1185]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

In Teams & Sharepoint\Onedrive\List Onedrive, can one of the columns show the onedrive personal sharepoint urls?

this would be super helpful for mapping home folder migrations to onedrive

**Comment by KelvinTegelaar** [comment]
Added in dev
