### ISSUE TITLE
[Feature Request]: Pre-Provision all user onedrives

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1186]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

can we have a standard to  pre-provision all licensed users onedrives please?

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/sharepoint/pre-provision-accounts#pre-provision-onedrive-for-all-licensed-users-in-your-organization

**Comment by KelvinTegelaar** [comment]
I've been playing with this, but cannot get this to work using the APIs we have available, will revisit in the future.

**Comment by cardonet-helpdesk** [comment]
any chance of revisiting this KT?
