### ISSUE TITLE
Reset password asks to change at login

### ISSUE THREAD

**Issue by dpcomputing** [KelvinTegelaar/CIPP#1187]
### Description

1. Go to 'Users' under Identity Management
2. Click 'Edit User'
3. Click 'Reset password' and enter a new password
4. Make sure 'Require password change at next logon' is UNCHECKED
5. Change 'Usage Location' to Australia
6. Click 'Edit user' at the bottom
7. Log in with new password entered in rest password
8. Asks to change the password as its the first time the user logged in
![cipp_rp](https://user-images.githubusercontent.com/58459785/199641669-0a1b9845-63ae-4cf4-abc5-b89502c5e6af.png)
![cipp_rp1](https://user-images.githubusercontent.com/58459785/199641663-a4e459f9-68da-4c25-9d7c-2a9f0e3f1f9c.png)

### Environment data

```PowerShell
Azure, up-to-date
```

**Comment by dpcomputing** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by dpcomputing** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
