### ISSUE TITLE
Last Login Details missing from Mailbox view

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1188]
### Description

Email & Exchange -> Mailboxes.  Click the eye icon on any mailbox.

Every mailbox show

Last Login Details
Last Sign in Date (UTC)
Last Sign in Application
Last Sign in Status
Last Sign in Result                  Failure
Last Sign in Failure Reason

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
