### ISSUE TITLE
View Mobiles Devices for any mailbox returns error

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1189]
### Description

Email & Exchange -> Mailboxes
Pick a mailbox and click the Smartphone icon

An Error Has Occurred
The value is set to empty Parameter name: base64EncodedData
[Detail]
403 - Request failed with status code 403

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Resolved in dev
