### ISSUE TITLE
Unable to change and rerun Graph Explorer query once it has been run

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1190]
### Description

Go into Graph Explorer and create/run a manual query

Once you get results, you appear to be unable to modify the query and run it fresh; you have to leave the Graph Explorer page and go back to it to clear the results.

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Have you tried unfolding the top menu to retry/change/etc?

**Comment by joncz** [comment]
Yes, I did.  Clicking the query button doesn't give me a throbber or new results.

Note that this behavior doesn't occur if I change prebuilt queries, only if I've started with a manual query and then tried to tune it.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
