### ISSUE TITLE
[Feature Request]: Offboarding Wizard Review and Confirm - change checkmarks to green

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1191]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

On the Review and Confirm page of the offboarding wizard the checkmarks and x's are all orange.  In most other areas of the portal, checkmarks are green.  Changing them to green here would help to highlight the selections that have been chosen.

**Comment by KelvinTegelaar** [comment]
GREEN IS WRONG, ORANGE IS RIGHT. We're putting this under the "by design" for now - Tackling in the future with a bit of redesign magic.
