### ISSUE TITLE
Best Practice Analyzer - Unused Licenses Detail brings up blank page

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1193]
### Description

This occurs only for entries with a single SKU

Go into BPA.  Locate a tenant with 1 SKU in their Unused Licenses column.
Click on the button to bring up the details.
You get a blank screen

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev
