### ISSUE TITLE
Domains Analyzer / Individual Domain Check - MX Results misreports Mail Provider

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1194]
### Description

Tenant1 - tenant1.com
MX 10 tenant1-com.mx1.arsmtp.com
MX 20 tenant1-com.mx2.arsmtp.com
MX 30 tenant10-com.mail.protection.outlook.com
Reported mail provider is O365

Tenant2 - tenant2.com
MX 10 tenant2-com.mx1.arsmtp.com
MX 20 tenant2-com.mx2.arsmtp.com
Reported mail provider is AppRiver

### Environment data

```PowerShell
Hosted
```

**Comment by johnduprey** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Fixed in dev
