### ISSUE TITLE
[Feature Request]: Alerts Wizard - read existing settings into template and apply by template

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1198]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would like the ability to read the configured alerts from a tenant and build a template out of them, and then apply that template to other tenants.

**Comment by joncz** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
Still under consideration.

**Comment by KelvinTegelaar** [comment]
merging with new FR
