### ISSUE TITLE
[Feature Request]: Exclude "Excluded Tenants" from the BPA display

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1199]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

So I added a tenant to the excluded tenants.  They no longer show up in the tenants drop-down nor does the BPA run against them (I refreshed it and see everyone else has updated and their last run still shows last night).  _However_ the excluded tenant still shows in the BPA window.

**Comment by joncz** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
