### ISSUE TITLE
A document (DeployPolicy.md) is a bad link (404)

### ISSUE THREAD

**Issue by zenmechanic** [KelvinTegelaar/CIPP#12]
**Describe the bug**
Link to documentation page is 404

**To Reproduce**
1. Go to '/index.html?page=AddPolicy'
2. Select a tenant and click next
3. Click "this link" for doc on raw JSON help
4. 404

**Screenshots**
![image](https://user-images.githubusercontent.com/13618241/137397157-357db161-d054-48c7-9d5c-d5b94c287f15.png)

**Comment by gavsto** [comment]
This doesn't seem to have an appropriate documentation that I can find. @KelvinTegelaar ?
