### ISSUE TITLE
[Feature Request]: Filter MFA Report by User Type (IE Be able to spot admins without MFA easily)

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1200]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

 (IE Be able to spot admins without MFA easily)

**Comment by KelvinTegelaar** [comment]
planned

**Comment by KelvinTegelaar** [comment]
I thought we already had this data available in the report, but we do not. Adding this would be a pretty heavy query so for now this is a no.
