### ISSUE TITLE
[Feature Request]: OneDrive User Profiles in SharePoint Admin Center - Manage User Profiles

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#1203]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great if we can edit SharePoint site collection administrators from within CIPP.

We often have use cases where we need to move OneDrive data from a user's profile, into a shared SharePoint library during offboarding, but it's quite a manual process at the moment.

We currently have to do this by assigning a site administrator via direct Tenant access, as we don't have the ability to do this via the MS partner center.

![image](https://user-images.githubusercontent.com/105069544/200502627-7588a644-4131-4c33-8702-e516002e5772.png)

**Comment by KelvinTegelaar** [comment]
Not possible, there's no APIs for this right now.
