### ISSUE TITLE
[Feature Request]: Adding External Contact & Adding External Contact to Groups / DL

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#1204]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great if we can add an external contact from CIPP, and if possible, add this contact to a group or a distribution list?

We sometimes have use cases where a client will require an external contact to be added to a group or a distribution list manually.

Currently we are able to do this via the MS Admin Center:

![image](https://user-images.githubusercontent.com/105069544/200504543-d51e0ce7-853a-4d47-a43f-6ea5484380fc.png)

**Comment by KelvinTegelaar** [comment]
Planned

**Comment by KelvinTegelaar** [comment]
added in dev.
