### ISSUE TITLE
Error for a readonly user shows the raw HTML in the error message

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1205]
### Description

I created a readonly user, and when they attempt to look at 

Incidents & Alerts -> Incidents
Incidents & Alerts -> Alerts
Tenant Administrations -> Reports - Graph Explorer

they receive the following in the error box:

`<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="description" content="The CyberDrain Improved Partner Portal is a portal to help manage administration for Microsoft Partners."/><meta name="author" content="CIPP Contributors"/><title>CIPP</title><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/><link rel="manifest" href="/manifest.json"/><link rel="mask-icon" href="/safari-pinned-tab.svg" color="#f77f00"/><meta name="msapplication-TileColor" content="#da532c"/><meta name="theme-color" content="#ffffff"/><script defer="defer" src="/static/js/main.35737641.js"></script><link href="/static/css/main.762ebb16.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>Details
403 - Request failed with status code 403
`

I understand from support that the API that is used to view alerts can also modify so CIPP denies access to the endpoint completely - fair enough.  I don't think the raw HTML is meant to be displayed in the error box.

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Fixed in Dev, html errors get turncated to readable errors now.
