### ISSUE TITLE
Add an alias feature - is not working

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1208]
### Description

when i try to add an alias to a user (odd that this is in users and not mailboxes btw?)

it claims to have worked "user succesfully edited" but then doesnt..

the alias does not appear in exchange properties even after an hour

### Environment data

```PowerShell
self hosted - forked from master
```

**Comment by cardonet-helpdesk** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by DirectITServicesUK** [comment]
Same here.

**Comment by KelvinTegelaar** [comment]
Bit too much cleanup with the last release - This is now fixed.
