### ISSUE TITLE
[Feature Request]: View to which mailboxes a user has access.

### ISSUE THREAD

**Issue by TricoreService** [KelvinTegelaar/CIPP#1211]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Like it shows to which groups a user belongs, it would nice to also see to which mailboxes a particular user has access. This simply on the same user overview page as the other information is shown currently.

I know I already asked this when creating a user to do copy permissions, but simply viewing those permissions would help a lot since this only can be done by Powershell.

### PowerShell commands you would normally use to achieve above request

Get-Mailbox | Get-MailboxPermission -User <userofwhichthedetailspageisopen>

**Comment by KelvinTegelaar** [comment]
This query is extremely heavy and a wont implement due to the performance hit it would give. Retrieving these permissions for a decent sized tenants can take 30 minutes to several hours, heavily impacting performance.
