### ISSUE TITLE
[Feature Request]: Compromised account remediation

### ISSUE THREAD

**Issue by drew5901** [KelvinTegelaar/CIPP#1213]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When running the compromised account remediation tool, could we add an "Are you sure" prompt that includes the user account to be remediated to confirm the account remediation. 

The reasoning why is I learned the hard way that it works very well.

The benefit would be staff being aware and confirming the action they are about to take in the event they miss-click or to avoid a careless mistake.

**Comment by KelvinTegelaar** [comment]
added in dev
