### ISSUE TITLE
[Feature Request]: Multiple Language Support

### ISSUE THREAD

**Issue by Mtothee** [KelvinTegelaar/CIPP#1214]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We are a small MSP Shop in Germany and would love to contribute with a german translation of the UI. 
Also we have sources of italian and french speaking persons in our team. So we could provide a translation for that languages as well.

**Comment by KelvinTegelaar** [comment]
We're not going to support internationalization, mostly because that effort would depend too much on external sources. and contributors. It would get outdated too fast when adding new features where I'd be receiving complaints I can't fix. Sorry!
