### ISSUE TITLE
[Feature Request]: Add additional query filters for Sign-in Reports

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1218]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Per the discussion on Discord it would be useful to have additional query filters for the Sign-in Reports.

The reason for this is we have some tenants that exceed the 45 second threshold, which often leads to failure / tmeouts when pulling the reports (while other tenants work fine).

Being able to fine-tune these reports would allow us to get only the data we need without exceeding the timeout. It also provides flexibility in terms of the reporting.

### PowerShell commands you would normally use to achieve above request

**Get Failed Sign Ins**
```createdDateTime gt 2022-10-01 and (status/errorCode eq 50126)```

**Get All Sign Ins Outside Canada**
```createdDateTime gt 2022-10-01 and (location/countryOrRegion ne 'CA') and (location/countryOrRegion ne '') and (status/errorCode eq 0)```

**PS Command**
```New-GraphGetRequest -uri "https://graph.microsoft.com/beta/auditLogs/signIns?api-version=beta&`$filter=$($filters)" -tenantid $TenantFilter -erroraction stop```

**PS Command using $top**
```New-GraphGetRequest -uri "https://graph.microsoft.com/beta/auditLogs/signIns?api-version=beta&`$top=10&`$filter=$($filters)" -tenantid $TenantFilter -erroraction stop```

**Comment by KelvinTegelaar** [comment]
Custom filters added
