### ISSUE TITLE
[Feature Request]: Schedule Conditional Access Exceptions

### ISSUE THREAD

**Issue by sembeeuk** [KelvinTegelaar/CIPP#1220]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I see from Discord that scheduling is coming soon - so this could fit with that. 

We use conditional access to restrict countries that users can login from, which I think is a fairly common use of CA. That is fine until a user goes on holiday or visits a supplier outside of the home country and needs to take work devices with them. 

Sites where they know that we are using that conditional access rule will often have users who email the helpdesk team to say that they are traveling in advance and when they will be back. However a ticket then has to be created to remind people to setup the exception rule the day before, then either leave the ticket open for two weeks (oh the metrics chaos), create another one, create a manual calendar entry or use some other process to remove the exception. What often happens is that the exception just remains in place until the user asks next time, or there is just a long list which someone updates every Monday by hand. 

Therefore it would help if the exception rule could be setup as soon as notified to activate on the specified date, with an end date also set to remove the rule when the user returns. It would not only allow more granular control of conditional access, but for the helpdesk technician it is a set and forget task, which will not require follow up work. 
As a bonus, if it could show on the user's properties page that an exception is in place and its expiry (perhaps that is where it is actually set) it would help a technician diagnose a country conditional access issue, avoid duplications etc. 
A further benefit is that it allows a helpdesk to setup the rule, without having to go in to the Conditional Access ruleset which could cause them to lock the user or others out.

**Comment by KelvinTegelaar** [comment]
Would you like a unicorn with those fries? ;)

Seriously; this sounds like a really cool feature but performing a correct implementation of this that does not decrease security as a whole is nigh-impossible. My suggestion would be to create your CA policies with a default exclusion group in place, and monitor that group membership instead.

Closing as it's a wontfix.

**Comment by KelvinTegelaar** [comment]
> It is being done by another product... so can be done.

Yes, it can be done. But not correctly and securely, without detriment to security, which are the pillars of CIPP. We don't allow users to shoot themselves in the foot.
