### ISSUE TITLE
Exclude tenant icon brings up generic Add Excluded Tenants dialog

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1223]
### Description

CIPP->Settings->Tenants

If I click the eyeball icon beside a tenant to exclude them, I expected to receive a dialog that was basically a confirmation popup:

Exclude <TenantName>
[Continue] [Cancel]

Instead, I got the same popup as if I'd clicked the Add Excluded Tenant button at the top right, giving me the full list.

If you need to use that same dialog, I'd expect to see the selected tenant preselected

![image](https://user-images.githubusercontent.com/9025749/202726178-c575bac4-2e83-4b3b-8f95-5ad378dbd08d.png)

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Whoops, oversight. Should indeed be a "Are you sure you want to exclude this tenant?" Fixing.

**Comment by KelvinTegelaar** [comment]
fixed in dev
