### ISSUE TITLE
[Feature Request]: Selected line indicator

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1226]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

So this is something of a system-wide UI request.

When you have a long table of items (users, tenants, whatever) and you mouse over an action icon at the far right, the action icon highlights on the mouseover, yet there can be so much whitespace, it's hard to see which line you're working on.

I think it would be beneficial to also indicate the line being operated on.  Off-hand, I can see a couple options:
1. Highlight the tenant/user name (whatever the left column is)
2. Update each table to include a blank column at the left that changes to an arrow or right-pointing triangle (⏵)

I think I'd prefer the name column to also highlight to not complicate exports, column selectors, or to lose space.

**Comment by KelvinTegelaar** [comment]
added subtle text hover in dev.
