### ISSUE TITLE
Research Compromised Account throws error

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1227]
### Description

Identity Management -> Administration -> Users -> <User> -> Research Compromised Account

An error has occurred!
An error has appeared while trying to load your data. For troubleshooting, the error information can be found in the table below.

This type of error is usually indicative an application issue. To troubleshoot this issue check if your API is running and reachable, or use below error to troubleshoot

Error
Cannot convert undefined or null to object	

Error Location
TypeError: Cannot convert undefined or null to object at Function.keys (<anonymous>) at n (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:17366) at https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:17870 at Object.useMemo (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2129970) at t.useMemo (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2309905) at P (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:17316) at oo (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2124005) at $s (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2176305) at xl (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2163546) at Rl (https://cipp.dynamicquest.com/static/js/main.b3bdc96d.js:2:2163474)

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
Can't simulate this, might this have been an unlicensed user?
