### ISSUE TITLE
[Feature Request]: Add column filters

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1228]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would be nice to be able to filter columns down to specific values.
Workaround is to export the table to CSV and do so in Excel

Example - Security & Compliance -> Alerts
Filtering the Severity column to _not_ show Informational alerts.

### PowerShell commands you would normally use to achieve above request

Hosted

**Comment by KelvinTegelaar** [comment]
This is on the roadmap. I'm looking into improving filtering but this won't be for a release or two.
