### ISSUE TITLE
Systemwide Red Error boxes dismiss themselves

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#1229]
### Description

Any page throwing an error box at the top right should leave the box there until dismissed.

ie,
![image](https://user-images.githubusercontent.com/9025749/202732806-40a3f65a-71bf-4b1c-b555-f703f8ceb6f9.png)

These boxes should not dismiss themselves; if the user's not watching closely, the error can be overlooked.

### Environment data

```PowerShell
Hosted
```

**Comment by KelvinTegelaar** [comment]
They dismiss themselves because otherwise errors stack, which makes it confusing on when which error occurred. The timeout is 5 seconds, long enough to notice imho ;)
