### ISSUE TITLE
[Feature Request]: Add option to block 'tenant registration by users' in Azure AD

### ISSUE THREAD

**Issue by BruinsmaICT-Jorik** [KelvinTegelaar/CIPP#1232]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

In Azure AD (user settings) there is an option to allow/disallow users to create a new azure AD tenant. I would like to add this option to the standards in CIPP, so we can manage and monitor this for our customers.

**Comment by KelvinTegelaar** [comment]
Added in dev
