### ISSUE TITLE
[Feature Request]: Alert on expiring GDAP Relationship

### ISSUE THREAD

**Issue by jwalker343** [KelvinTegelaar/CIPP#1233]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Microsoft's [GDAP](https://learn.microsoft.com/en-us/partner-center/gdap-introduction) creates an ongoing relationship between the MSP (Microsoft Partner) and a tenant for administration purposes. The **maximum** age of this relationship is 730 days, but it could be significantly less (90 days, Annual, or co-termed with contract expirations). _Over time we expect that we will have customers with vastly different GDAP renewal dates._

The dates for this expiration can be found inside your partner portal and are available via a [partner insights report](https://learn.microsoft.com/en-us/partner-center/gdap-relationship-analytics) showing upcoming expirations.

It would be beneficial if CIPP could alert on this expiration as it already does with DEP, APN, VPP certs and tokens.

### PowerShell commands you would normally use to achieve above request

Microsoft has some documentation using a REST API here: [https://learn.microsoft.com/en-us/partner-center/develop/list-delegated-admin-customers](https://learn.microsoft.com/en-us/partner-center/develop/list-delegated-admin-customers).

**Comment by KelvinTegelaar** [comment]
As MS will do this themselves quite rigorously I'm wondering if we should. Can you tell me some more use cases on how you'd miss MS's email barrage about this?

**Comment by jwalker343** [comment]
I think the biggest difference is that the MS email notifications will go to individuals while CIPP is configured to send directly to our ticketing system.

Once these renewals become common & begin to be routine, it's probable that most of the individuals that receive direct email alerts from MS just "assume someone else was handling it."

We get emails from other vendors (Cisco, Meraki, Dell, etc..) renewals, but we proactively track these items outside of email & generate tickets automatically due to the high potential for user error.
