### ISSUE TITLE
[Feature Request] : Email only domains in Analyser

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#1234]
As some domains are not used for email could their security score be calculated with different parameters? Like a null value for MX record give green etc? Maybe it could look for a TXT record with a value of "not_used_for_email" to report accordingly?

**Comment by procradminator** [comment]
I wonder if I can remember my issue number for this?

**Comment by procradminator** [comment]
Actually, scrap the dedicated TXT records any of these would do.

SPF Set TXT record to “v-spf1 -all”
DKIM Set TXT to “*._domainkey.example.com” “v=DKIM1; p=”
DMARC Set TXT to “_dmarc.example.com” “v=DMARC1;p=reject;sp=reject;adkim=s;aspf=s”

**Comment by johnduprey** [comment]
Hey @procradminator! We already have Null MX support built in, including extra checks to help prevent your domain from being abused for spoofing.

**Comment by procradminator** [comment]
Well, the little question marks offering to take me to "Null DKIM documentation" don't seem to work. Is that just me or a seperate issue that needs raising?

**Comment by johnduprey** [comment]
There's just one info link on the MX record: https://github.com/KelvinTegelaar/CIPP-API/blob/master/MailProviders/Null.json

**Comment by procradminator** [comment]
I'm guessing once I've correctly added all the relevant records this request will no longer be relevant so it can be removed. TIA.

**Comment by KelvinTegelaar** [comment]
Removed, thanks for reporting anyway :)
