### ISSUE TITLE
[Feature Request]: HidenFromGAL option

### ISSUE THREAD

**Issue by ZNL-BKA** [KelvinTegelaar/CIPP#1239]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

recently while offboarding some users, I noticed that I could not hide the email address from GAL.
I had a good look and could not find it, had to complete it from the tenant portal.

could you look at adding this option if possible

### PowerShell commands you would normally use to achieve above request

Set-Mailbox -Identity username@domain.com -HiddenFromAddressListsEnabled $true/$false

**Comment by joncz** [comment]
Are you saying this doesn't work?

![image](https://user-images.githubusercontent.com/9025749/204850232-0f3c54a8-ff91-4ce1-8144-e95daffc28b5.png)

**Comment by ZNL-BKA** [comment]
i did not see that and now I feel a bit sheepish.

thanks jon

**Comment by KelvinTegelaar** [comment]
It happens, trees, forest. Closing as implemented ;)
