### ISSUE TITLE
Feature Request: Extend on user templates #72

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#124]
**Is your feature request related to a problem? Please describe.**
In #72 we discussed copying user membership, we should extend on this in the next version to allow users to create presets and select these from a dropdown, including the correct license.

**Describe alternatives you've considered**
Keeping just the copy-user option is nice for memberships, but not enough.

**Additional context**
Ref #72

**Comment by KelvinTegelaar** [comment]
@scubes13 @zenmechanic could you tell me a little more about how you'd see the templating feature work.

**Comment by zenmechanic** [comment]
For my use case, it'd mostly be about license assignment and security group and Teams/SharePoint group memberships based on a pre-existing user. eg, when adding someone to the finance department, I can select someone else from the finance department to copy memberships from to get the new user into all the right groups. eg, it adds them to the SSO provisioning group for QuickBooks online, it adds them to both the finance and accounting SharePoint sites/teams.

It'd be swell if somehow it could also set allowed apps under license settings. EG, front line workers will have the same license as everyone else, but we don't want to give them SharePoint access at all, so we disable the SharePoint app under the license settings for that user. Doubt that can be done programmatically though.

[cid:00a55b8c-021f-47c7-814a-f493ac81dda1]




Adam Thorn
President, IT Consultant, Tech Wizard
TUCU - We Fix Techaches and make people happy<https://tucu.ca/client-reviews/>.
(416) 292-3300 x101

Book a Call with Adam ***@***.***/bookings/>

________________________________

**Comment by scubes13** [comment]
Very similar to what @zenmechanic shared. However, I'd like to create a template for the tenant (ie, Finance, Sales, etc) that would encapsulate these settings. Perhaps the creation of the template could be the result of copying settings from a selected user. However, every user might be different or carry multiple roles. So, while John Doe may be in Finance - perhaps they also have access to Sales (for whatever reason). Copying his settings might have negative consequences that we weren't aware of at the time (ie, access to things the new user should not inherit). 

So, I think the better approach would be creating a template for the roles....

Items to consider... License(s), security groups, Teams/SharePoint, Shared Mailboxes, Distribution Groups(?)...

**Comment by KelvinTegelaar** [comment]
Thanks, that already helps loads!

**Comment by zenmechanic** [comment]
@scubes13  great point, I hadn't thought about role crossover. 

I thought about truly templated users, but how do you hide the templated users from the associated groups. I can see the ongoing questions from every department head at every company "Who is this 'Template' person that can see the payroll reports". 

Is it possible to hide the template users from all group memberships? 

Or is it possible to add the templates to CIPP under the standards section and not pulling data from a 'live user' but instead pulling it from settings that have been pre-configured.

-"Tenant Administration"
    -"Standards"
        -"Standard user roles"
        -Select Tenant
        -Select role
             -*Edit role*
                  -"Add group memberships to role" ((pulls list of group names from tenant)) **maybe split this between sec grps and SP/Teams groups as different dropdowns in case of large orgs with too many groups combined to effectively list in a single dropdown.
                  -"Add standard license settings to role"
                  -"More settings and stuff" 
                  -"Save role"
** Write above settings as a static entry in CIPP (or as a SharePoint list in the customer or partner tenant) to be referenced in the user creation screen**


Then
-"Administration"
    -"Users"
        -"Add new user"
        -"Select tenant" which populates the new user templates created for the tenant in the standards section and reads the settings held in CIPP or the SharePoint list populated earlier.

Not sure how feasible, but this would be awesome.

**Comment by KelvinTegelaar** [comment]
Moved to release 1.4, this will be one of the pillars for that release.
