### ISSUE TITLE
Message Trace reports are not filtering

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#1241]
### Description

I went to do a message trace and selected previous one day.

I added a sender, however, it pulled every email irrespective of that sender I selected.

Filtering on the results worked fine.

### Environment data

```PowerShell
Latest version of CIPP
```

**Comment by KelvinTegelaar** [comment]
Works here. Can you let me know if the sender email contained any special characters, such as -,_, etc. :)

**Comment by wilhil** [comment]
Nope, all normal

it happened each time I tried yesterday... I just saw your comment and tried to record a video that I was going to send you the link to... and... it's working like normal now :(

So... sorry, yhank you and happy to close!
