### ISSUE TITLE
[Feature Request]: Service and health links from Partner Center

### ISSUE THREAD

**Issue by MichaelBerntsen** [KelvinTegelaar/CIPP#1242]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would it be possible to incorporate all service and health links from Microsoft Partner Center within CIPP?

Menu:
Tenant administration > Administration > Administer Services > LINKS
Tenant administration > Administration > Service Health > LINKS
 
Service and health links = https://partner.microsoft.com/en-us/dashboard/commerce2/customers/list

This would greatly benefit MPSs and increase the usage of CIPP.

**Comment by KelvinTegelaar** [comment]
Already exists
