### ISSUE TITLE
Feature request: Intune import support multiple policy types

### ISSUE THREAD

**Issue by freezscholte** [KelvinTegelaar/CIPP#125]
**Describe the solution you'd like**
Currently you can only upload administrative templates in JSON form, it would be useful if you could upload multiple policy/setting types. This way setting up a new tenant or adding new policy's to existing tenants would not be restricted to Administrative Templates only.

**Describe alternatives you've considered**
We currently use this -> https://github.com/nicolonsky/ModernWorkplaceConcierge/wiki
Also, the reason opening this issue is to point out this solution and mayby you can look at it for inspiration how they achieve it and implement this in the CIPP. 

**Additional context**
When we export with the "ModernWorkplaceConcierge" all the data is stored in json files. Furthermore, with my limited coding skill if I look up the code it most certainly looks like they are using GraphAPI to export and import policies.

Anyway, maybe you already have something planned to support multiple policy types in Intune and this information is obsolete. Or some other good reason not to do it...

**Comment by KelvinTegelaar** [comment]
Added in Dev
