### ISSUE TITLE
[Feature Request]: Exchange Online Permission Report

### ISSUE THREAD

**Issue by coolriku** [KelvinTegelaar/CIPP#1250]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

A new Report with all Exchange Permissions per Tenant.
Including:
- Exchange Mailbox permissions (including 'Full Access','Send As','Send on Behalf'
- Exchange Calendar permissions (including non primary calendars)

Features:
- Search Permissions per Trustee/User
- Export Report

This Feature is currently missing in CIPP, and would be a great addition for MSP's.
You can use this report to Audit Permissions across the Tenant.

### PowerShell commands you would normally use to achieve above request

Get-EXOMailbox
Get-EXOMailboxPermission
Get-EXOMailboxFolderStatistics
Get-EXORecipientPermission

**Comment by coolriku** [comment]
I'd like to work on this please!

**Comment by coolriku** [comment]
Initial setup finished but slow performance, may take long time to load report on large tenants.
I heard that the Devs are working on batch functions for ExoRequests, maybe it's better to wait for that?

@KelvinTegelaar What is the best option? Do I need to create a PR, or wait till the new functions are available?

**Comment by KelvinTegelaar** [comment]
Let's wait for the batching endpoint because of the timing issues. We can then rewrite your reports. I'm hoping to sneak it into tomorrow's release if I get it stable enough. :)

**Comment by KelvinTegelaar** [comment]
no no, bad bot.
