### ISSUE TITLE
FEATURE REQUEST: Ability to Add Channels to a Team

### ISSUE THREAD

**Issue by jvduval** [KelvinTegelaar/CIPP#1254]
One of the biggest Teams administration tasks we have to perform is the adding, removal and management of Channels (public, private and shared) in the Teams Administration console, it would be incredible if we could have this functionality from within the Teams Administration section of the CIPP.

Thanks,

Jason

**Comment by KelvinTegelaar** [comment]
incomplete. please use the template.
