### ISSUE TITLE
FEATURE REQUEST: Manage Mailbox Size Allocation

### ISSUE THREAD

**Issue by jvduval** [KelvinTegelaar/CIPP#1255]
In order to simplify mailbox management, it would be great if we could manage the space allocation for the various user mailboxes.  While the CIPP shows the space allocated, there currently is no way to extend the size allocation without directly using PowerShell, this would be an outstanding addition to the CIPP.

**Comment by KelvinTegelaar** [comment]
incomplete. please use the template.
