### ISSUE TITLE
[Feature Request]: Scheduled Alerts split by customer

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1258]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently with the Scheduled Alerts, the email will come with alerts from any/all customers you have alerts setup for.

To better integrate these alerts with a ticket system (as an example) it would be great if the alerts could be split per customer. IE

1 Email for customer A detailing all scheduled alerts for that customer
1 Email for customer B detailing all scheduled alerts for that customer.
1 Email for customer C detailing all scheduled alerts for that customer.

Ideally the email alert should of course include the customer tenant name/default domain or other easily identifiable information.  That can be used with automation rules within a ticket system to log a ticket directly under the relevant customer.

I think this would benefit all MSP's who are using the scheduled alerts to log tickets in their ticketing platform.

**Comment by BNWEIN** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
added checkbox to allow splitting at notification config.
