### ISSUE TITLE
FEATURE REQUEST: 

### ISSUE THREAD

**Issue by maxirish94** [KelvinTegelaar/CIPP#1259]
It would be awesome to have some sort of template feature for the Offboarding Wizard where you can just save the typical offboarding options for a select tenant and situation (office user vs warehouse user etc.) and apply to a user account to automate the offboarding process that much more (although still have the ability to edit and review options easily) rather than selecting each option that needs change in the wizard each time you are offboarding a user account. I am sure many would appreciate something like that.

Thanks,

Ricardo

**Comment by KelvinTegelaar** [comment]
Merging with new FR
