### ISSUE TITLE
[Feature Request]: Deploying multiple CA policies/Intune Configuration profiles at once

### ISSUE THREAD

**Issue by Hellstromtech** [KelvinTegelaar/CIPP#1263]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would like to be able to deploy multiple CA profiles and Intune configuration profiles to one customer at a time.

Right now if we want to deploy 5 CA policies to one customer, we have to go through the process 5 times.

![image](https://user-images.githubusercontent.com/59050959/208078306-692d348b-d86b-4b4b-8dd1-320d7634feb3.png)

Select the green box multiple times, to add an extra deployment so to say.

**Comment by KelvinTegelaar** [comment]
So this is going on the backlog for the template engine. I have some plans to make this possible but requires some prework. I'll close this issue, but create a project task.
