### ISSUE TITLE
Teams - Add Team available for "All Tenants"

### ISSUE THREAD

**Issue by coolriku** [KelvinTegelaar/CIPP#1266]
### Description

Steps to reproduce:
1. Set selected tenant to "All Tenants"
2. open Add Team menu item in Teams.
3. You see the Team details form, and get a http 500 error.

![image](https://user-images.githubusercontent.com/52283549/208113093-2ca8c99f-76f3-402b-ab85-c6f4e0f7824b.png)

Desired Behaviour:
Get a generic message: "This page does not yet support the All Tenants overview. Please use the tenant selector to select a tenant."

### Environment data

```PowerShell
Self Hosted Azure
Frontend: 2.19.0
Backend: 2.8.0
```

**Comment by KelvinTegelaar** [comment]
Fixed in Dev
