### ISSUE TITLE
[Feature Request]: Get Bitlocker Recovery Key 

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1268]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Under Intune > Devices > Device Management, it would be great to be able to get the bitlocker recovery key of a device.

We would like our engineers to be able to use CIPP as much as possible so we can restrict their access to logging into customer tenants.  Recovering a bitlocker key is something that do regularly. 

I am sure many MSP's do the same

### PowerShell commands you would normally use to achieve above request

Microsoft.Graph PowerShell Module

 $Device = Get-MGDevice -filter "deviceName eq 'ComputerName'"
 $BTKey = Get-MgInformationProtectionBitlockerRecoveryKey -filter "deviceId eq $device.guid"

**Comment by BNWEIN** [comment]
I would like to upgrade the priority

Sent from Outlook for iOS<https://aka.ms/o0ukef>

Ben Weinberg
Operations Director
Tel020 7443 5618
Mob07515 482 580
***@***.***
www.prime-networks.co.uk
Unit GI.4.06, 60 Gray’s Inn Road, London WC1X 8LU
This message is intended exclusively for the individuals to whom it is addressed and may contain information that is privileged, or confidential. 
​If you are not the addressee, you must not read, use or disclose the contents of this e-mail. If you receive this e-mail in error, please advise us 
​immediately and delete the e-mail. Prime & Modern LTD has taken every reasonable precaution to ensure that any attachment to this e-mail 
​has been swept for viruses. However, Prime & Modern LTD cannot accept liability for any damage sustained as a result of software viruses and 
​would advise that you carry out your own virus checks before opening any attachment. Prime & Modern Ltd is a limited company registered in 
​England and Wales. Registered Company No: 08403368 Registered Office: 16 Great Queen Street, London, WC2B 5AH.
________________________________

**Comment by KelvinTegelaar** [comment]
Added in dev
