### ISSUE TITLE
Intune > Device Management > Devices Table issues

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1269]
### Description

Issue 1: 
"AutoPilotEnrolled" column is always empty. No sign/symbol showing when a device is AutoPilot Enrolled, even though the devices do show under Intune > AutoPilot > AutPilot Devices 

Issue 2:

Choosing the "LoggedOnUser" column causes an repeatable error 

![image](https://user-images.githubusercontent.com/28929905/208192786-55e6c2a6-f303-40ee-90d9-97f7cde4dc69.png)

### Environment data

```PowerShell
Self Hosted Azure
Frontend: 2.19.0
Backend: 2.8.0
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

Sent from Outlook for iOS<https://aka.ms/o0ukef>

Ben Weinberg
Operations Director
Tel020 7443 5618
Mob07515 482 580
***@***.***
www.prime-networks.co.uk
Unit GI.4.06, 60 Gray’s Inn Road, London WC1X 8LU
This message is intended exclusively for the individuals to whom it is addressed and may contain information that is privileged, or confidential. 
​If you are not the addressee, you must not read, use or disclose the contents of this e-mail. If you receive this e-mail in error, please advise us 
​immediately and delete the e-mail. Prime & Modern LTD has taken every reasonable precaution to ensure that any attachment to this e-mail 
​has been swept for viruses. However, Prime & Modern LTD cannot accept liability for any damage sustained as a result of software viruses and 
​would advise that you carry out your own virus checks before opening any attachment. Prime & Modern Ltd is a limited company registered in 
​England and Wales. Registered Company No: 08403368 Registered Office: 16 Great Queen Street, London, WC2B 5AH.
________________________________

**Comment by KelvinTegelaar** [comment]
Fixed in dev
