### ISSUE TITLE
[Feature Request]: Clear ImmutableId for User

### ISSUE THREAD

**Issue by coolriku** [KelvinTegelaar/CIPP#1271]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When you have a tenant with Azure AD Connect sync, and you remove an onpremise user, it will be automatically removed from Office 365.
If you want restore the  user in Offic365 to Cloud only it will be removed again by AD Connect with the next sync.
To overcome this issue you need to restore the user and remove/clear the ImmutableId attribute in Office365.

I saw that on FR #57 there was a discussion about it, but can't find anything related to it in the code.

### PowerShell commands you would normally use to achieve above request

Set-MsolUser -ImmutableId ""

**Comment by coolriku** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Added in dev!
