### ISSUE TITLE
OneDrive not showing names

### ISSUE THREAD

**Issue by Exigo-CIPP** [KelvinTegelaar/CIPP#1278]
### Description

Within our hosted CIPP session. I have noticed OneDrive is showing what I assume is the hex data of the user rather than the username. 
Permissions Check all successful. 
Your refresh token matches key vault.
Your access token contains the MFA claim.
Your Secure Application Model has all required permissions
When checking tenant access permission, it showed connect and connected to exchange. It's the same with all our clients except one. When I run the access check, still successful. 

### Environment data

```PowerShell
Hosted in Azure, the same after updating the frontend this morning. Hosted in Australia East, except Static Web App, which is hosted in Central US.
```

**Comment by KelvinTegelaar** [comment]
Not a bug, please check the documentation.
