### ISSUE TITLE
BUG: Deploy Security Group Issues

### ISSUE THREAD

**Issue by mbohdeTA** [KelvinTegelaar/CIPP#1279]
I've seen multiple issues pop up working with groups.

Groups > Add Groups
I haven't been able to recreate this a second time, but the first time I attempted to use this to deploy a Security Group, the Type selector kept switching back to Mail Enabled Security Group upon the first click after setting it back to Security Group. Apart from that first time, I can successfully deploy an individual group, even though it still requires an email address when it shouldn't need one for this type.
![image](https://user-images.githubusercontent.com/118937593/209017357-a58467ed-687b-4efe-bd3a-a2c8661735db.png)

Deploy Group Templates > Select Tenant > Select Template (security group in this instance)
Where it shows Confirm and Apply, the first two show up correctly, but the third (type) has an X. Couple things here. 
1) Not sure what it is, but there appears to be a rogue type box. The location depends on the size of the window, but full screen on 2560 x 1440, it's to the left of the Submit button.
![image](https://user-images.githubusercontent.com/118937593/209016168-3761814d-02a7-414f-8211-f0118efe5a65.png)
2) There appears to be an issue with the Group Username field here. First, it shouldn't be a required field for Security Groups, as it isn't tied to an email account like the other types are (I think). When you enter the first part of the username, expecting it to take the default @domain, it fails asking for the full address, showing the group name with an @ at the end.
![image](https://user-images.githubusercontent.com/118937593/209016719-ca606808-9313-40e4-8cee-5435c2c5a3e9.png)
If you then go back and try adding the full address, it fails again, this time showing the full address with an @ at the end. It appears to be appending this @ regardless what you put in, so it will always fail.
![image](https://user-images.githubusercontent.com/118937593/209016917-8c418801-d879-4b73-ae82-2bda0d4c03c2.png)
I would expect working would be the Group Username being removed when Security Group is selected. I'm not quite sure how this is supposed to work with bulk deployments, but at least with individual deployments through template, you could also add the domain selector like the single group add page has to prevent any confusion there.

**Comment by KelvinTegelaar** [comment]
1.) This is your browser interpreting this. Most likely you have an adblocker active that is blocking the "ad" div, causing rendering issues

2.) The group username is the part before the @. no domain added.

**Comment by mbohdeTA** [comment]
For 1, no worries. I do have an ad blocker, but first time I've seen it cause that. For 2, I tried it with and without the domain, and both failed. I included screenshots of both failures.


-Mike Bohde
Insight Analyst
________________________________
