### ISSUE TITLE
[Feature Request]: Disable Out of Office

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1285]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Whilst we are able to enable out of office messages we are not able to disable them. Seems logical to have the ability to do both things.

Im sure this would help all MSP's :) 

### PowerShell commands you would normally use to achieve above request

Set-MailboxAutoReplyConfiguration -Identity username -AutoReplyState disabled

**Comment by KelvinTegelaar** [comment]
Added in dev
