### ISSUE TITLE
BUG: GDAP migration failure

### ISSUE THREAD

**Issue by mat9922** [KelvinTegelaar/CIPP#1287]
there is an error when activating the "User Administrator" group in the GDAP Wizard

Migration Failed. Could not create group mapping for group 4f017429-48eb-41a9-9586-946b21880342
c02b32b3-f12f-4958-82b2-5d79039e61d7: An unexpected error occurred in the server

Without this group it's working. Unfortunately this group is quite important. Any idea?

**Comment by mat9922** [comment]
I followed the instructions on this site. The roles which are recommended by you beside the "User Administrator" role are working.

**Comment by KelvinTegelaar** [comment]
![image](https://user-images.githubusercontent.com/49186168/210761275-755bfa04-2401-4fcb-a22e-372662e0ed23.png)

**Comment by mat9922** [comment]
ok ... 

I red this and therefore give it a chance 
![grafik](https://user-images.githubusercontent.com/86627046/210761522-419a8e57-87d5-499d-82e9-3d6f75c96eb3.png)
