### ISSUE TITLE
[Feature Request]: Send test notification option

### ISSUE THREAD

**Issue by jpeerbolte** [KelvinTegelaar/CIPP#1296]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When setting up notifications it would be handy if there was a "send test notification" to verify notifications work as intended.

After setting up our CIPP portal we discovered that the notifications were sent using an undesirable account. 
This turned out to be documented in https://cipp.app/docs/user/usingcipp/settings/notifications/

We had to redo the SAM Wizard to change this, but after doing that a quick Notification Test would be handy, instead of having to trigger an event and wait.

**Comment by KelvinTegelaar** [comment]
you can now select all log sources to generate an event, that's just as easy :)
