### ISSUE TITLE
BUG: Email permissions does not show who has "Send-As"

### ISSUE THREAD

**Issue by wilkinsalex** [KelvinTegelaar/CIPP#1301]
In the user view, it will list users with FullAccess, but it doesn't list if a user has Send-As.

Additionally, in the "Email & Exchange > Mailboxes > Edit" view where you can see the "raw" output of the permissions, it also does not show if the user has Send-As Permissions.

The use case here is users with shared mailbox access (Full Access) also need Send-As if they are replying inside the mailbox. So, we apply both of those permissions.

We can apply it, and it does work as shown in the second "part" of the screenshot below, it just doesn't report it back into CIPP =)

Example here: https://app.screencast.com/Mk7HM5QTxTfAf

**Comment by KelvinTegelaar** [comment]
Fixed in dev
