### ISSUE TITLE
[Feature Request]: Add Intune Endpoint security profiles

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1311]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I think it would be really awesome if CIPP had the EndPoint Security Settings added to the InTune Device Management section, so we can configure stuff like Disk Encryption, Local Admin Group Membership, etc. using CIPP Templates

The blade in question is here: https://endpoint.microsoft.com/#view/Microsoft_Intune_Workflows/SecurityManagementMenu/~/overview

Thank you,

### PowerShell commands you would normally use to achieve above request

There's a good article on it here: https://powers-hell.com/2020/04/21/creating-endpoint-security-policies-with-powershell/

**Comment by KelvinTegelaar** [comment]
Adding as planned. :)

**Comment by KelvinTegelaar** [comment]
List policies now show all possible policies, and added templating options.
