### ISSUE TITLE
When you add a contact, the success alert/message says "succesfully added shared mailbox"

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1315]
### Description

When you add a contact, the success alert/message says "succesfully added shared mailbox",

please change this to "succesfully added contact"

### Environment data

```PowerShell
azure, main branch :)
```

**Comment by BNWEIN** [comment]
Fixed in dev :)

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
PR Created. This can be set as resolved.
