### ISSUE TITLE
[Feature Request]: Ability to add a mail contact/contact to distribution groups

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1316]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

at the moment we can only add users with existing internal domain suffixes, cant add contacts with external domains

please can you add this ability :)

**Comment by BNWEIN** [comment]
Kelvin has made this change in the latest Dev version.
