### ISSUE TITLE
Error hiding from address list during offboarding.

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1330]
### Description

During Offboarding, its fairly common for the "Hide from Address list" function to fail.  No error message in the logbook other than it was not able to hide the address from the global address list.

Tenant Access Check shows no issues for the customers when it happens

### Environment data

```PowerShell
Azure
Front End: 2.20.1
Backend 2.9.2
```

**Comment by BNWEIN** [comment]
confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Fixed in dev
