### ISSUE TITLE
FEATURE REQUEST: Display Mailbox Type on Mailbox Statistics Page

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1332]
It would be very helpful on the Mailbox Statistics page to see whether a mailbox is a UserMailbox or SharedMailbox. This is particularly useful because we are interested in finding Shared Mailboxes exceeding 50GB of data (and thus requiring a license) versus Shared Mailboxes less than 50GB.

Ultimately, we're looking for a better way to utilize the data between the Mailbox Statistics and the List Mailboxes screens to find Shared Mailboxes with Licenses that don't actually need them.

**Comment by DChorn-ANS** [comment]
I'd like to work on this please!

**Comment by DChorn-ANS** [comment]
PR has been submitted to add Mailbox type to mailbox statistics

**Comment by KelvinTegelaar** [comment]
and added in dev.
