### ISSUE TITLE
SPF Details Falsely Reporting Failure on Domain

### ISSUE THREAD

**Issue by ErlachSupport** [KelvinTegelaar/CIPP#1340]
### Description

One of my tenants is showing an error when doing an SPF check on their domain.  When I looked into the SPF details, it showed it was expecting the default O365 SPF needed to be included at the beginning of the record despite existing near the end of the current record.  I've moved the order and placed the O365 include statement near the front of the record.  This resolved the SPF check error.

I am not sure if the SPF logic is meant to only check a certain number of statements before assuming the spf.protection.outlook.com record is missing.  Scanners such as the MX Toolbox SPF checker do not show an error with the include placed at the end of the record.  Attached a copy of the SPF details to show what is happening.  Is this expected behavior?

![Snag_341c57e](https://user-images.githubusercontent.com/74732781/214911799-6a89641c-f6bd-4e39-b1bc-9a5075e4b372.png)

### Environment data

```PowerShell
Self-hosted in Azure using pay-as-you-go plan. Frontend version: 2.20.1. Backend version: 2.9.2. We are managing 75 tenants with 110 domains.
```

**Comment by johnduprey** [comment]
That certainly sounds like a bug. If you're on Discord, send me a PM with some details so I can look into it.

**Comment by johnduprey** [comment]
Disregard, it's one of your Barracuda MX lookups. One or both of them do not resolve anything and are causing an exception that breaks the SPF check. I've added some additional warnings for that.

**Comment by johnduprey** [comment]
@ErlachSupport try to test the SPF record against The Kitterman SPF tool, it should report SPF ambiguous if my hunch is correct. https://www.kitterman.com/spf/validate.html

Example:
```The explanation returned was, SPF Ambiguity Warning: No MX records found for mx mechanism```

**Comment by ErlachSupport** [comment]
John, thank you for taking a look so quickly!  I tested the record against the tool but it looks like it is coming back clean:

evaluating...
SPF record passed validation test with pySPF (Python SPF library)!

**Comment by ErlachSupport** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by johnduprey** [comment]
I still think it's a bug with the MX parsing - I'd like to see the record for that domain to confirm that it's fixed though. Happy to chat on Discord so you aren't publicly posting it.

**Comment by ErlachSupport** [comment]
@johnduprey I've send a message via Discord.  Thank you for digging into this!
