### ISSUE TITLE
Cannot edit a user created in On Premise AD and Synched that has not had a license assigned.

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1341]
### Description

if you create a user in on premise AD.
Synch that user to Office 365
Then try and use cipp to edit that user (so you can assign it a license)

You get an object with keys error

As discussed in Discord, raising the bug here.

### Environment data

```PowerShell
Hosted
Latest version
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
