### ISSUE TITLE
[Feature Request]: Add User assigned Manager attribute functionality

### ISSUE THREAD

**Issue by sgexcit** [KelvinTegelaar/CIPP#1342]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We use the Manager attribute in User objects extensively for our clients for all sorts of workflows for onboarding, offboarding, change requests, and automation on their end for Power Automate flows, etc. I believe other MSPs would benefit from the following enhancements in CIPP:

1. View the Manager attribute in CIPP as a column in **Identity Management > Administration > Users**, and also when you expand a User object.
2. The ability to assign, reassign, or unassign Manager's from user entries, one at a time, or in bulk in **Identity Management > Administration > Users**.
3. The ability reassign a Manager for downline user objects during Offboarding if you are removing a Manager from the system.

**Comment by ChrisEnvisage** [comment]
Would like to request this feature be implemented. Adding a Manager as a part of the onboarding flow and being able to edit the Manager attribute from within the users pane, or selecting multiple users at once and updating their manager, would all be very helpful for us.

We regularly need to assign a Manager attribute as a part of onboarding and is one of the only things we need to routinely do outside of CIPP.
