### ISSUE TITLE
Issue with some reports not having any data for visible columns

### ISSUE THREAD

**Issue by joelkino** [KelvinTegelaar/CIPP#1344]
### Description

There seems to be an issue with exporting the reports from this location: 
Teams & SharePoint > Teams > View a Team > Installed Applications

- The report shows as empty 
- If i add the optional columns (id and teamsAppDefinition) and then export then only those columns show
- seems the problem is that the original columns are not available in the column picker like in other areas

I have checked and the same issue is present for all the reports on the Teams page as well: Team Owners, Team Members, Channels

### Environment data

```PowerShell
Self Hosted

Version Frontend
Latest: 2.20.1
Current: 2.20.1

Version Backend
Latest: 2.9.2
Current: 2.9.2
```

**Comment by joelkino** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Those should not an an export button as we can't access that data easily, so removing in next release. :)
