### ISSUE TITLE
MFA Report for AllTenants not reporting "IsLicensed" correctly.

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1350]
### Description

When running the MFA Report (Identity>reports>MFA Report) for "AllTenants" it is not reporting the "isLicensed" information correctly. 

This same information reports fine when only a single tenant is chosen. 

### Environment data

```PowerShell
Azure.
Frontend: 2.20.1
Backend: 2.9.2
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
