### ISSUE TITLE
Best Practice Analyser shows "No data" in several columns after upgrade to 3.0 for all tenants

### ISSUE THREAD

**Issue by NielsKoelle** [KelvinTegelaar/CIPP#1355]
### Description

Looks like it happens for "Passwords never expire setting" and "Basic Auth States" and "SSPR".
HTTP error 440 logged in logbook.
All permisions checks are OK.

### Environment data

```PowerShell
Self hosted in Azure.

Frontend 3.0.0
Backend 3.0.0
```

**Comment by NielsKoelle** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by Hannes7c** [comment]
Also have this issue after updating to v3, permission checks reporting no missing permissions

**Comment by Pixelizm** [comment]
Also having the issue after upgrade. Have perform Tenant Access check and a Permission Test which were all OK. Worked before recent update. Currently 'Passwords do not expire'. 'Self Service Password', 'Modern Auth', 'Secure Score' are all 'No Data'

**Comment by KelvinTegelaar** [comment]
Bad bot

**Comment by NielsKoelle** [comment]
It's still a bug...

**Comment by Aleix441** [comment]
Hello,

I have the same problem on the column "Password Do Not Expire", "Self Service Password Reset Enabled", "Modern Auth Enabled"

But not on the SecureScore like Pixelizm

**Comment by KelvinTegelaar** [comment]
Fixed in dev :) release is this friday.
