### ISSUE TITLE
What permissions are granted when adding a new tenant via the SAM Wizard?

### ISSUE THREAD

**Issue by jinithin** [KelvinTegelaar/CIPP#1358]
Looking around for some documentation on what's granted for a new tenant when it's added via the "SAM Wizard".
I can understand the first step with the Graph permissions, but the other ones are a bit obfuscated imo.
https://github.com/KelvinTegelaar/CIPP-API/blob/master/ExecSAMSetup/run.ps1

Like this one below:
`$Results = @{ message = "Give the next approval by clicking "  ; step = $step; url = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/authorize?scope=https://graph.microsoft.com/.default+offline_access+openid+profile&response_type=code&client_id=$($appid)&redirect_uri=$($url)" }`

Some clarification in the process would be great.
Would definitely help us integrating the product into our organization.
Thanks.

**Comment by KelvinTegelaar** [comment]
You can see exactly which permissions are granted when creating the app, or via https://cipp.app/docs/user/gettingstarted/permissions/.

**Comment by BNWEIN** [comment]
The SAM wizard is not used to add a new tenant into an existing CIPP setup. The SAM Wizard is used to either create the CIPP-SAM App during its first run, or to update/refresh your tokens.
