### ISSUE TITLE
[Feature Request]: Intune - Add application as template

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1359]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have applications deployed to clients, and want to deploy these to other clients e.g 7-ZIP, Adobe Reader.

It would be nice to be able to add these as templates to re-use for other clients, in the same way you can create templates from the Device Management screen.

**Comment by KelvinTegelaar** [comment]
Not for now, but we'll revisit later.
