### ISSUE TITLE
Exchange Deploy Connector

### ISSUE THREAD

**Issue by SMMRIT** [KelvinTegelaar/CIPP#1360]
### Description

Hi

First of all, a great product we just have started using :)

When we try to add a new Exchange Connector and press the "Deploy Connector Button:
![image](https://user-images.githubusercontent.com/124346230/217254674-470d27c4-a2c4-432b-a5a5-03eff6b52108.png)

We get the following error:
![image](https://user-images.githubusercontent.com/124346230/217254388-9293df62-9a20-43cb-bb93-d548715a9994.png)

### Environment data

```PowerShell
Azure
Version Frontend: 3.0.0
Version Backend: 3.0.0
```

**Comment by SMMRIT** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev, the link is also in the side menu "deploy connector template" or some such,.
