### ISSUE TITLE
FEATURE REQUEST: Implement "All Tenants" View for Certain Pages

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1363]
There are a few key pages that we'd find it particularly helpful to have an option to choose "All Tenants" on. Below are the pages and the use case for why seeing all tenants in one view would be extremely helpful.

**Identity Management > Administration > Users**
- Licensed Users that are Disabled
_This would help us identify cases where we are paying for licenses that are no longer in use. It would allow us to identify these users as needing to be converted to shared mailboxes and having the licenses removed._

**Email & Exchange > Administration > Mailboxes**
- Shared Mailboxes with a License
_This would help us identify shared mailboxes that unnecessarily have a license assigned._

Email & Exchange > Reports > Mailbox Statistics
- Users with large mailboxes or mailboxes approaching quota
_We can proactively notify users to cleanup mailboxes or upgrade their license to allow a higher quota._

- Shared mailboxes with over 50GB of usage
_This would help us identify cases where a shared mailbox may legitimately need a license like Exchange Online Plan 2 to allow more than 50GB of mail.

**Comment by KelvinTegelaar** [comment]
I think this should be possible maybe, we'll try to see if we can make these all tenant capable in one or two releases away.

**Comment by KelvinTegelaar** [comment]
added user, and added mailbox statistics. For Mailboxes themselves we'll need an MS based fix, as that query is almost impossible without.
