### ISSUE TITLE
Intune Policies/Templates

### ISSUE THREAD

**Issue by SolutionsIT-General** [KelvinTegelaar/CIPP#1366]
### Description

Running into an issue where I want to either convert an existing policy into a template or I export the JSON and try to manually add it and they get blocked by: 

`Intune Template Deployment failed: The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less. RequestId:51bc8936-e002-006b-18f9-3bba75000000 Time:2023-02-08T20:07:44.0677314Z Status: 400 (Bad Request) ErrorCode: PropertyValueTooLarge Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:51bc8936-e002-006b-18f9-3bba75000000\nTime:2023-02-08T20:07:44.0677314Z"}}} Headers: X-Content-Type-Options: REDACTED Cache-Control: no-cache DataServiceVersion: 3.0; Content-Type: application/json;odata=minimalmetadata;streaming=true; charset=utf-8`

Now what is interesting is I tried an even larger one and got the same message but the maximum allowed size was now 1 MB.

From what I can see 64KB is incredibly small. Even just a handful of policies seems to exceed that limit

### Environment data

```PowerShell
Running in our azure tenant. Fully up to date
```

**Comment by KelvinTegelaar** [comment]
Not a bug, Microsoft limitation.

**Comment by SolutionsIT-General** [comment]
Is there any way around it? I was really hoping CIPP would be the answer for deploying our baseline policies. The one policy only has maybe 10 settings and it fails :(
