### ISSUE TITLE
Add group template - selecting "Security Group" selects, then jumps down to "Mail enabled security group"

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1367]
### Description

When adding a group template via "Add group template" - clicking the radio button for "Security Group" selects, then changes down to "Mail enabled security group".

Clicking security group again, will have it selected and remain, but clicking on anything else (e.g display name field) will change the selection from Security group to Mail enabled security group

### Environment data

```PowerShell
M365 CIPP in Azure.
Version 3.0.0 for both front and back end.
```

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
This has been fixed in Dev. PR - 1369
