### ISSUE TITLE
Feature Request: Show shared mailboxes statistics

### ISSUE THREAD

**Issue by tech-squid** [KelvinTegelaar/CIPP#137]
**Is your feature request related to a problem? Please describe.**
Currently only user mailboxes are visible on the Mailbox Statistics page. 

**Describe the solution you'd like**
Shared mailboxes could be added to the existing list, have them become visible with a toggle or even get their own page called "Shared Mailbox Statistics".

**Comment by gavsto** [comment]
So I've had a look in to this and it is not going to be simple to do. The reports that we rely on pulling from the Graph just don't include these statistics in them and there is no graph alternative I can find to get these statistics.

If you can present a graph/API endpoint we can hit we can re-visit this, but for now there's no realistic way to implement this I'm afraid.
