### ISSUE TITLE
Single Tenant SAM Creation

### ISSUE THREAD

**Issue by tekjc** [KelvinTegelaar/CIPP#1372]
### Description

When you run the SAM wizard and pick I want to run this for my own tenant and I am not a partner the first step doesn't open a new window after generating the code when clicking on HERE.  It needs to open in a new window so you can enter the code and sign in and then go back to the wizard.  The setup.js file needs a target=_blank under the partner=false section.

### Environment data

```PowerShell
Azure - single tenant for testing
```

**Comment by tekjc** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
