### ISSUE TITLE
[Feature request]:  editable Transport Rules

### ISSUE THREAD

**Issue by paronubimaster** [KelvinTegelaar/CIPP#1373]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Chris Moroz idea from https://portal.thetechtribe.com/community/topic/16719-a-one-file-onenote-malicious-email-campaign-is-ramping-up-quickly/?do=findComment&comment=145059

Basically if you have TR setup to block .exe but now you want it to block .one as well - would be nice to edit right in CIPP 

In addition, maybe editable TR templates that can overwrite existing TRs of same name? I dunno if that's doable, just an idea for being able to push out changes like this quickly.

**Comment by KelvinTegelaar** [comment]
Rules now automatically set if the same name has been found.
