### ISSUE TITLE
FEATURE REQUEST: Enable Multiple Filters at Once with AND/OR Operators

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1374]
With bulk actions coming soon, it would be useful to be able to apply multiple filters at once on a table.

As an example, it would be useful to be able to filter by BOTH synced users AND users without a license so that a bulk action such as assigning a license could be applied:
![image](https://user-images.githubusercontent.com/101881895/218272898-f27f7c6e-988b-4047-8328-16fbcd0a2c31.png)

Something like a | operator to act as an OR or a & or (comma) operator to act as AND - something like:

Synced Users AND No License:
`"onPremisesSyncEnabled":true,"assignedLicenses":[]`

Synced Users OR Licensed
`"onPremisesSyncEnabled":true|"assignedLicenses":[{`

**Comment by johnduprey** [comment]
If you're syncing users from AD, why not just do group based license assignment?

**Comment by PremierOneData** [comment]
Yeah, that could just be a bad example. There are probably a ton of other uses for and/or combinations of filters, especially for larger environments or screens with "All Tenants" views enabled.

**Comment by KelvinTegelaar** [comment]
Not possible for now, but considering for later release. :)
