### ISSUE TITLE
Server 500 error when navigating to the Add User page

### ISSUE THREAD

**Issue by clownwilleatme** [KelvinTegelaar/CIPP#1375]
We have upgraded to CIPP v3 a few days ago and are now getting an error when navigating to the Add User page. The error says "A generic error has occurred." and shows "500 - Request failed with status code 500" under the Details section.

The error occurs when trying to add a user for multiple tenants. The tenant access check does not show any issues.
No other actions in CIPP are failing, and other user related actions (viewing, editing) work without problems.

Troubleshooting steps that have been done:
 - Frontend and backend are both on the latest version (3.0.0)
 - Permission check has been run after upgrading to v3, additional permissions were added to the SAM app registration, the permission check does not return any issues
 - Cleared all CIPP cache
 - Restarted the web and API app service instances
 - Tested by multiple CIPP users, all get the same error
 - Tested with multiple tenants, all get the same error
 - Tenants pass the tenant access check
 - Nothing relevant visible in the CIPP logs

Is there any detailed error logging available to help diagnose further?

**Comment by KelvinTegelaar** [comment]
Temporary issue, does not break usage, just annoying. :) fixed in next release
