### ISSUE TITLE
"Error Count: x - Last Error:"

### ISSUE THREAD

**Issue by dveldkamp** [KelvinTegelaar/CIPP#1382]
Tenant Administration > Administration > Tenants

Shows some tenants with:

"Error Count: # - Last Error:"

But there is no error listed, so not sure how to troubleshoot this.

**Comment by KelvinTegelaar** [comment]
Not a bug, if you'd like support, please check our sponsor options.

**Comment by dveldkamp** [comment]
Thanks for clarifying, I can't seem to find sponsor options on the website though?
