### ISSUE TITLE
Unable to approve CIPP app within partner tenant (GDAP)

### ISSUE THREAD

**Issue by re-geeks** [KelvinTegelaar/CIPP#1384]
### Description

Receive the following error when trying to authorize app as Global Admin within GDAP enabled tenant using the link(s) generated within CIPP:

_"AADSTS900144: The request body must contain the following parameter: 'scope'."_

Link format generated is as follows:

https://login.microsoftonline.com/{TenantID}/v2.0/adminconsent?client_id={AppID}

When removing "v2.0" from the URI sign-in is attempted, but hangs and app approval does not appear to succeed.

### Environment data

```PowerShell
Azure
```

**Comment by KelvinTegelaar** [comment]
Not a sponsor, and Gdap migration tools are unsupported
