### ISSUE TITLE
[Feature Request]: Monitor for overprovisioned O365 licenses.

### ISSUE THREAD

**Issue by IgorMeynin** [KelvinTegelaar/CIPP#1386]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Due to the new Microsoft NCE license model, we need a better way to monitor for overprovisioned licenses.  It would be helpful to be alerted when the number of O365 consumed licenses is higher than provisioned licenses.

### PowerShell commands you would normally use to achieve above request

#Connect to Microsoft Graph.
Connect-Graph -Scopes Organization.Read.All
#Read all assigned licenses for the SKU part that contain O365 in the part name.
$Licenses = Get-MgSubscribedSku | where{$_.SkuPartNumber -like "*O365*"} | select {$_.PrepaidUnits.enabled}, ConsumedUnits, skupartnumber
#Identify the total number of consumed and prepaid licenses.
[int]$Consumed = $Licenses.ConsumedUnits
[int]$Prepaid = $Licenses.{$_.PrepaidUnits.enabled}
#Compare the number of consumed and prepaid licenses to identify overprovisioning.
If($Consumed -gt $Prepaid){Write-Host -ForegroundColor Red "Licenses have been overprovisioned. Total Count $Consumed/$Prepaid"}

**Comment by IgorMeynin** [comment]
I would like to upgrade the priority

**Comment by BNWEIN** [comment]
This already exists as an alert in the alerts wizard in version 3.0 

![image](https://user-images.githubusercontent.com/28929905/220950991-dd11a077-d362-4cc9-a691-80bd5c649575.png)

**Comment by BNWEIN** [comment]
Re-Reading your Feature Request, it might be the alert above the one i have circled that you want, but its there.

**Comment by IgorMeynin** [comment]
Thank you for all the comments.  I missed the existing alert.  All good now. :)
