### ISSUE TITLE
Add Autopilot Device - Case Sensitive CSV

### ISSUE THREAD

**Issue by Ben-ITLogic** [KelvinTegelaar/CIPP#1388]
### Description

When using the Add Device function the CSV columns are case sensitive on import which causes issues with vendor provided CSV files who use different heading casing.

Our vendors (and HP direct) provide us with the CSV file with the case as:
- Device Serial Number
- Windows Product ID
- Hardware Hash

The CSV file needs these in the below case:
- Device serial number
- Windows product ID
- Hardware hash

### Environment data

```PowerShell
Self Hosted in Azure.
```

**Comment by Ben-ITLogic** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by BNWEIN** [comment]
This has been fixed in PR #1390, should be added in the next update.
