### ISSUE TITLE
FEATURE REQUEST: Alphabetize Choco App Search Selection

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1389]
Alphabetizing the results of a choco app search would help find the correct app more easily:

![image](https://user-images.githubusercontent.com/101881895/220903768-2f986873-0d18-42da-b6ae-1a1847d5866b.png)

**Comment by PremierOneData** [comment]
Same for MS Store App:

![image](https://user-images.githubusercontent.com/101881895/220904955-fcce37b4-8bad-4c31-bbc2-83bc342b518d.png)

**Comment by KelvinTegelaar** [comment]
Fixed in dev
