### ISSUE TITLE
Unable to set up Alerts Wizard on current dev version 

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1391]
### Description

Just letting you know before the next update. This is not actually causing me any issues, but in the current Dev version you are unable to setup alerts. When you go to the Alerts Wizard, select a customer, and try and click "Next" you get an error at the bottom of the page that simple says "Required"

### Environment data

```PowerShell
Dev Environment
Local
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
