### ISSUE TITLE
Administration\User view does not display all license types next to users

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1393]
for instance

Dynamics 365 Professional

will not show up against users in the license column view

**Comment by TechEnvyPtyLtd** [comment]
Not sure if it's related but I have noticed licenses not showing when they are removed using the Offboarding Wizard. E.g. If I offboard a Business Premium license and a Cloud PC license, it will only show it has removed the Business Premium (and not the cloud PC one, even known it has done so).

**Comment by KelvinTegelaar** [comment]
By default dynamic licenses are in the excluded license table.
