### ISSUE TITLE
[Feature Request]: Custom Attribute Viewer/Editor

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1395]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Several of our customers use Exclaimer for email signatures with Office 365. They also use Exchange Custom Attributes to populate some of the data in their signature. 

Right now there is no way to view or edit this using CIPP.

Would be handy if on the edit mailbox page, there was another button that let you view/edit/save custom attributes.

I believe Exclaimer is widely used so think other MSP's would find this handy.

### PowerShell commands you would normally use to achieve above request

Get-mailbox User@domain.com | FL CustomAttribute*
Set-Mailbox User@domain.com -CustomAttribute1 <the new value>
Get-Mailbox | Set-Mailbox -CustomAttribute5 <the new value>

**Comment by BNWEIN** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
Not going to happen exactly, we'll have a "Attribute" mapper inside of the edit user screen that you'll be able to use for this.
