### ISSUE TITLE
Feature Request: Additional User Details

### ISSUE THREAD

**Issue by mdewart-springpoint** [KelvinTegelaar/CIPP#140]
**Is your feature request related to a problem? Please describe.**
It helps to have contextual information when managing users.

**Describe the solution you'd like**
On the Users List screen, or on the Edit User screen when additional user details are retrieved, it would be nice Last password change timestamp, last sign-in attempt timestamp and success/failure

**Describe alternatives you've considered**
Using the Tenant Administration > 365 Portal option to view this information.

**Additional context**
Data from admin.microsoft.com portal:
![image](https://user-images.githubusercontent.com/69530446/139147051-e03ce0a9-93df-4a5d-84d1-e7601e140f9f.png)

**Comment by KelvinTegelaar** [comment]
Added in Dev.
