### ISSUE TITLE
Conditional Access Import fails if there is exclusions set

### ISSUE THREAD

**Issue by Ray-MRQ** [KelvinTegelaar/CIPP#1400]
### Description

You get this error message if you try to import a policy that has an exclusion set.
![image](https://user-images.githubusercontent.com/10146271/222403217-fb7ca20a-629e-46f0-9d9a-ad4241b97a08.png)

Snippet of the json.
![image](https://user-images.githubusercontent.com/10146271/222403721-845457c0-36a6-4831-b49a-e93bf00fe888.png)

The exclusions I normally set is to exclude anything external, however, there's a preview tab that displays to exclude specific Azure AD Orgs.
![image](https://user-images.githubusercontent.com/10146271/222403470-2198aae5-a057-479b-becf-5cda8e747e52.png)

To get around it I've just removed the exclusions and added a note internally to add exclusions after setting it up.

### Environment data

```PowerShell
Azure latest.
```

**Comment by Ray-MRQ** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
