### ISSUE TITLE
[Feature Request]: Add Standard to disable Bing Data Collection

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1402]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be good to add an option to disable Bing Data Collection to the CIPP Standards. This is a new "feature" Microsoft added recently. Currently, we are doing it manually for every client as we value our clients' privacy and none of them see the need to participate in Microsoft's ChatGPT experiment (or anything else they claim to be using it for).

Thanks for your consideration,

**Comment by joeldeteves** [comment]
> without any PowerShell or screenshots, I'm not sure what you're talking about.

It's under **Org Settings -> Security & Privacy**. Here you go:

![image](https://user-images.githubusercontent.com/33190570/222512304-566fc553-f276-4101-8b1a-fbf02abde1a4.png)

I'm still looking for the PowerShell method myself - will let you know as soon as I find the solution

**Comment by rvdwegen** [comment]
Don't think there's anything Microsoft native.

The [O365Essentials](https://www.powershellgallery.com/packages/O365Essentials/) module POSTs some JSON to https://admin.microsoft.com/admin/api/settings/security/bingdatacollection to set the value.

**Comment by joeldeteves** [comment]
Thks @rvdwegen - I couldn't find anything in the Graph API docs so I think you're right. That said, might be worth poking someone @ Microsoft - don't see why they wouldn't bake this into Graph as they seem to base almost everything in the 365 backend off of Graph these days.
