### ISSUE TITLE
BUG: User Offboarding issue

### ISSUE THREAD

**Issue by sasinduk** [KelvinTegelaar/CIPP#1407]
Hello Kelvin,

Got the following error while a user offboarding.
This is user from one of our clients.
We have completed the SAM wizard already.
Please help us go get through.

Thank you in advance,

Could not convert test@test.com to a shared mailbox. Error: Response status code does not indicate success: 401 ().
Could not remove user from group M3-AutoPilot: Unable to update the specified properties for on-premises mastered Directory Sync objects or objects currently undergoing migration.. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group UA Team Projects: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group abc@xyz.com: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group Social committee: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group Xyz Team: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group All Users: Insufficient privileges to complete the operation.. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group Xyzz Team: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group abc@def.com: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group Technology Training/Support: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group bc@def.com: Response status code does not indicate success: 401 ().. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group MedThree - Toronto: Response status code does not indicate success: 401 (Unauthorized).. This is likely because its a Dynamic Group or synched with active directory
Could not remove user from group bc@def.com: Response status code does not indicate success: 401 (Unauthorized).. This is likely because its a Dynamic Group or synched with active directory
Could not hide user@domain.com from address list. Error: Unable to update the specified properties for on-premises mastered Directory Sync objects or objects currently undergoing migration.
Disabled user account for user@domain.com
Could not add forwarding for user@domain.com. Error: Response status code does not indicate success: 401 (Unauthorized).
Removed current licenses: MICROSOFT 365 BUSINESS PREMIUM,MICROSOFT FLOW FREE
Could not delete mobile devices for user@domain.com. Error: Response status code does not indicate success: 401 (Unauthorized).

**Comment by KelvinTegelaar** [comment]
These are access denied errors, and not a bug.
