### ISSUE TITLE
Domain Analyzer CSV export mislabeled values

### ISSUE THREAD

**Issue by daileycomputer** [KelvinTegelaar/CIPP#1408]
### Description

The DMARCActivityPolicy column in the Domain Analyzer CSV export shows "None" when it should show "Report Only", and blank when it should show "No DMARC".

![image](https://user-images.githubusercontent.com/10691495/222852835-137a4f45-84c0-4ea6-840a-faee67e093e7.png)![image](https://user-images.githubusercontent.com/10691495/222852969-ca226de6-fd0b-48f2-804c-3f9a4886d3ef.png)

### Environment data

```PowerShell
Azure
3.1.0
```

**Comment by daileycomputer** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev, partly. Some of the output text will remain different but blank fields and "none" have been resolved. :)
