### ISSUE TITLE
FEATURE REQUEST: Automatic Reports

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#1413]
Would like to request the ability to request automatic reports from CIPP that would be helpful. 

- Individual report for each tenant showing M365 license quantities and usage - Unable to action via CIPP using all tenants currently

- Individual report for each tenant showing license assignments (ie username\email and the licenses allocated to that user) - Unable to action via CIPP using all tenants currently

- Aggregate report for all tenants showing users that do not have MFA enforced where the account is enabled and licensed. - CIPP has this but would like to ability for the reports to be generated via email.

**Comment by KelvinTegelaar** [comment]
due to the next release getting pretty big, and the workload involved we're only accepting feature requests by sponsors at the moment.
