### ISSUE TITLE
'LastGraphError' cannot be found on this object

### ISSUE THREAD

**Issue by twilson-gl** [KelvinTegelaar/CIPP#1421]
### Description

Under Settings > CIPP > Settings > Tenant Access Check

Running an access check on any tenant results in the following message:

_Failed to connect to The property 'LastGraphError' cannot be found on this object. Verify that the property exists and can be set._
_Failed to connect to Exchange: The property 'LastGraphError' cannot be found on this object. Verify that the property exists and can be set._

![image](https://user-images.githubusercontent.com/61714585/226074194-13bb4f98-0ab9-427d-8d72-97b63f94b334.png)

Not quite sure what this is referencing or where to look to resolve it.

### Environment data

```PowerShell
Azure - Frontend/Backend Version: 3.2.0
```

**Comment by twilson-gl** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
I'm thinking this might be a bug we introduced with the new tenant overview. Can you try removing your tenant cache and seeing if that helps?

**Comment by twilson-gl** [comment]
Noiiice! That did it.

Thanks Kelvin :)

**Comment by KelvinTegelaar** [comment]
awesome! no problem :)
