### ISSUE TITLE
DNS resolver limit?

### ISSUE THREAD

**Issue by NielsKoelle** [KelvinTegelaar/CIPP#1422]
### Description

This is still an issue.
Only getting a fraction of tenant domains (104 domains out of 370 tenants).
No change in behaivour changing the DNS resolver.

Found this one error message in logbook but do not know id this is related:

Domain Analyser GetTenantDomains Error 88:The batch request contains multiple changes with same row key. An entity can appear only once in a batch request. RequestId:494e5623-c002-0057-4a64-xxxxxx000000 Time:2023-03-13T04:32:40.2642665Z The index of the entity that caused the error can be found in FailedTransactionActionIndex. Status: 400 (Bad Request) ErrorCode: InvalidDuplicateRow Additional Information: FailedEntity: 88 Content: {"odata.error":{"code":"InvalidDuplicateRow","message":{"lang":"en-US","value":"88:The batch request contains multiple changes with same row key. An entity can appear only once in a batch request.\nRequestId:494e5623-c002-0057-4a64-xxxxxx000000\nTime:2023-03-13T04:32:40.2642665Z"}}} Headers: X-Content-Type-Options: REDACTED Cache-Control: no-cache DataServiceVersion: 3.0; Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

### Environment data

```PowerShell
Self hosted
Front end: 3.2.0
Back end: 3.2.0
```

**Comment by NielsKoelle** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
The report "The batch request contains multiple changes with same row key" explains that it found a duplicate domain in between tenants and stopped because of that. Try checking if there are duplicate domain names across your clients and remove where the domain name is no longer in use.
