### ISSUE TITLE
Tenant exclusions appears bugged/duped

### ISSUE THREAD

**Issue by Ray-MRQ** [KelvinTegelaar/CIPP#1423]
### Description

So it appears exclusions we set for Tenants had to be re-done, the tenants appear twice, I've re-applied the exclusions but I can't seem to remove the duplicate. 

I did see all tenants being duplicated initially but clearing the cache fixed that, however, tenants that were excluded can't be removed and had to re-apply for the exclusion.

Attempted to remove a duplicate exclusion/original exclusion appears with this.
![image](https://user-images.githubusercontent.com/10146271/226318848-754db1f6-e789-44d5-bdba-0ac37b8e4f64.png)

### Environment data

```PowerShell
Azure 3.2
```

**Comment by Ray-MRQ** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by onladmin** [comment]
yeah i've just done that, now all fine, thanks!
