### ISSUE TITLE
Outlook Spoof Warning Not Working

### ISSUE THREAD

**Issue by CorneliousJD** [KelvinTegelaar/CIPP#1424]
### Description

I had been in discussion via Discord with MrGeek who I know was also in discussion with you as well at some point on this.

The issue is that the spoof warning set to be turned on only logs in the CIPP logs as "Spoofing warnings set to false" when it should be ENABLING it for all of them.
**What's worse is after manually enabling it and then manually running a standard, it gets RESET to false again.**

If I check later with Get-ExternalInOutlook it confirms that the Spoof warning is indeed set to false.
Here's a sample of that.
![image](https://user-images.githubusercontent.com/724777/226338721-1e4148c6-5183-4fdc-a7cf-192b2ac814e7.png)
![image](https://user-images.githubusercontent.com/724777/226338781-d31572f2-238a-49a7-a542-08be098d8690.png)

My Standards config is a single line in the standards table for AllTenants -- no other standards applied.
Note that I have also deleted/recreated this table, and tried to delete/recreate the standard on 3.1.0 and 3.2.0 but issues persist the same regardless.

My actual standard config is here, with e-mails redacted.
`{  "Tenant": "AllTenants",  "AddedBy": "me@domain.net",  "AppliedAt": "2023-03-17T20:35:42",  "Standards": {    "SendFromAlias": true,    "DisableSelfServiceLicenses": true,    "AutoExpandArchive": true,    "AnonReportDisable": true,    "PWdisplayAppInformationRequiredState": true,    "DelegateSentItems": true,    "AuditLog": true,    "DisableViva": true,    "DisableUserSiteCreate": true,    "NudgeMFA": true,    "PasswordExpireDisabled": true,    "TAP": {      "Enabled": true,      "config": "true"    },    "DeletedUserRentention": true,    "ModernAuth": true,    "MailContacts": {      "MarketingContact": {        "Enabled": true,        "Mail": "365marketing@domain.net"      },      "GeneralContact": {        "Enabled": true,        "Mail": "365general@domain.net"      },      "SecurityContact": {        "Enabled": true,        "Mail": "365security@domain.net"      },      "TechContact": {        "Enabled": true,        "Mail": "365technical@domain.net"      }    },    "SecurityDefaults": true,    "SpoofWarn": {      "enable": true    }  }}`

If I manually PowerShell into a tenant it does indeed let me enable it...
![image](https://user-images.githubusercontent.com/724777/226337863-ae4733d8-2965-4bba-b70d-673f047a26fa.png)

**What's worse is after manually enabling it and then manually running a standard, it gets RESET to false again.**

### Environment data

```PowerShell
self-hosted via Azure app, latest production version. (3.2 at time of writing)
```

**Comment by CorneliousJD** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev. @BNWEIN See latest commit for the changed you needed to make.
