### ISSUE TITLE
[Feature Request]: As its a standard, please can we add "Shared Mailboxes with an enabled account" to graph explorer?

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1431]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

as this would be helpful

**Comment by KelvinTegelaar** [comment]
Not possible, graph does not have access to what type of mailbox something is.

**Comment by cardonet-helpdesk** [comment]
but then how does this exist
https://github.com/KelvinTegelaar/CIPP-API/blob/master/Standards_DisableSharedMailbox/run.ps1
?

isnt that graph checking for smbs then checking if the user is active?

**Comment by KelvinTegelaar** [comment]
No, these are not graph commands but exo powershell commands.
