### ISSUE TITLE
Bulk Action Checkboxes Not Cleared When Switching Tenants

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1433]
### Description

Issue I ran into with Bulk selection (in this example under Identity Management > Administration > Users)

If I go into a tenant, select multiple users, and perform some action, THEN I use the tenant switcher dropdown at the top and check some users in the 2nd tenant and perform some action, it still thinks the items are checked from the original tenant that I am no longer on. See screenshot.

![image](https://user-images.githubusercontent.com/101881895/226714775-8a2a526b-4205-4293-9e28-cb536b62b616.png)

### Environment data

```PowerShell
Sponsored
instance Front end version number: 3.2.0
Back end version number: 3.2.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by PremierOneData** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev. :)
