### ISSUE TITLE
Could not load tenants: Failed to connect to API:

### ISSUE THREAD

**Issue by karnophage** [KelvinTegelaar/CIPP#144]
**Describe the bug**
Permissions test says: We could not connect to the API to retrieve the permissions. There might be a problem with the secure application model configuration. The returned error is: 400 - Response status code does not indicate success: 400 (Bad Request).

I understand this is to do with the Secure App Model config, but I don't know where to start troubleshooting that.

Running the checkup script you posted, produces the following:

C:\kris\cyberdrain\checkup.ps1 : Could not connect to Graph API for *******.onmicrosoft.com. Cannot validate argument on parameter 'Tenant'. The argument is
null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1
+ .\checkup.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,checkup.ps1

New-PSSession : [ps.outlook.com] Connecting to remote server ps.outlook.com failed with the following error message :  For more information, see the
about_Remote_Troubleshooting Help topic.
At C:\kris\cyberdrain\checkup.ps1:33 char:20
+ ...  $session = New-PSSession -ConfigurationName Microsoft.Exchange -Conn ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : -2144108477,PSSessionOpenFailed
C:\kris\cyberdrain\checkup.ps1 : Could not connect to Exchange for ******.onmicrosoft.com. Cannot validate argument on parameter 'Session'. The argument is
null. Provide a valid value for the argument, and then try running the command again.
At line:1 char:1
+ .\checkup.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,checkup.ps1

C:\kris\cyberdrain\checkup.ps1 : Could not connect to Graph API for *****.onmicrosoft.com. Cannot validate argument on parameter 'Tenant'. The argument is
null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1
+ .\checkup.ps1
+ ~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,checkup.ps1

This would point to a permission error in the SAM, but I've no idea where to start looking. I've run it and it returns keys fine. I've put those into the scripts.

**Comment by karnophage** [comment]
Sorted using your direction, thanks @gavsto

**Comment by joshk1902** [comment]
@karnophage What was the fix?
