### ISSUE TITLE
[Feature Request]: Add an export button inside SMB feature in BPA

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1440]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

can you please add an export button on the 
Shared Mailboxes with Enabled User Accounts
popup, so i can export these?

**Comment by BNWEIN** [comment]
A new report has been added in Dev. This feature request can be closed.

![image](https://user-images.githubusercontent.com/28929905/228566513-a945ee2a-bb0c-418a-9ccc-c700082aa587.png)
