### ISSUE TITLE
Settings -> Tenants overview shows Unknown for GDAP relations

### ISSUE THREAD

**Issue by KennieNL** [KelvinTegelaar/CIPP#1443]
### Description

1.) Go to Settings -> CIPP in the menu
2.) Go to Tenants

We have several Relationship Type's showing 'unknown'.
When using the column selector and unticking 'delegatedPrivilegeStatus' and ticking it again it shows 'granularDelegatedAdminPrivileges' for those customers.

When viewing the code: https://github.com/KelvinTegelaar/CIPP/blob/72247c5f1f92d6be7a02e784fce55a89fcb550de/src/views/cipp/CIPPSettings.js#L659

The If statement there checks on 'GranularDelegetedAdminPrivileges' whilest this should probably be 'granularDelegatedAdminPrivileges' (lowercase g and Deleg**a**ted instead of Deleg**e**ted).

I currently don't have a dev envoirement to test this myself and make a pull request.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 3.2.1
Back end version number: 3.2.3
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Fixed by @rvdwegen
