### ISSUE TITLE
FEATURE REQUEST: Logged items filter for hidden tenants

### ISSUE THREAD

**Issue by steven-techtron** [KelvinTegelaar/CIPP#1446]
It would be very nice if the items shown in the log, default to not showing logs from tenants that are hidden/disabled.  They should only show those logs if a tick box is ticket to show logs from hidden tenants.

This will clear up the noise in the logs when looking at the logs.

When exporting the logs their should be an additional column with status to easily filter out logs from hidden tenants.

Thanks for the great app!

**Comment by KelvinTegelaar** [comment]
What @BNWEIN said. They might appear for one day but that should be it, unless you still have them in the standards or somesuch, then it's a good reminder to remove them from that ;)
