### ISSUE TITLE
Cannot exclude tenants

### ISSUE THREAD

**Issue by MBstatsara** [KelvinTegelaar/CIPP#1449]
### Description

When adding tenants to be excluded the following message appears

Failed. Cannot validate argument on parameter 'Entity'. PartitionKey must be provided in the input psobject entity in the correct casing!

Doesn't matter if i tick them individually or type the names at the top, the same issues appear.

Tenants tables were deleted at the last big update, as they all duplicated, and thus all exclusions were lost.
I have since cleaned tenant cache as well (over 24hrs ago) and still the same issues appear.

### Environment data

```PowerShell
Version Frontend
Latest: 3.2.1
Current: 3.2.1
Version Backend
Latest: 3.2.5
Current: 3.2.5
```

**Comment by KelvinTegelaar** [comment]
due to the next release getting pretty big, and the workload involved we're only accepting bugs or feature requests by sponsors at the moment.
