### ISSUE TITLE
Feature Request: Compromised account remediation 

### ISSUE THREAD

**Issue by mrapoc** [KelvinTegelaar/CIPP#145]
**Is your feature request related to a problem? Please describe.**

It would be nice to standardise a response to a user knowing they have fell victim to phishing or suspicious activity

**Describe the solution you'd like**

Reset password, force logouts, list rules set/forwarders and offer to remove. 

**Describe alternatives you've considered**

Manual work, various PS scripts out there (non GUI)

**Additional context**

**Comment by KelvinTegelaar** [comment]
Discussed in #cipp on mspgeek; something like a reverse engineered HAWK would be cool, we'll have to see how far we want to go on this.

**Comment by KelvinTegelaar** [comment]
work for this is underway. First analysis will select a tenant, and specific user and collect relevant information and steps to take.

**Comment by KelvinTegelaar** [comment]
Added BECView to user overview in dev
