### ISSUE TITLE
Error on settings page.

### ISSUE THREAD

**Issue by jpstarvin** [KelvinTegelaar/CIPP#1459]
### Description

TypeError: t.filter is not a function at k (https://cipp.agileis.com/static/js/main.c10f366e.js:2:18696) at oo (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2131565) at Ho (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2141132) at $s (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2184856) at xl (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2171106) at Rl (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2171034) at wl (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2170897) at vl (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2167863) at https://cipp.agileis.com/static/js/main.c10f366e.js:2:2117357 at t.unstable_runWithPriority (https://cipp.agileis.com/static/js/main.c10f366e.js:2:2332373)

### Environment data

```PowerShell
Sponsered
Front End: 3.3.0
Backend: 3.3.0

Cache clear: false
token clear: false
```

**Comment by rvdwegen** [comment]
Perhaps good to add if you're experiencing this in a dedicated tenant or a partner context. (are you using it to manage one solo tenant, or are you a MS partner managing many tenants)

**Comment by jpstarvin** [comment]
This is a partner tenant.

**Comment by jpstarvin** [comment]
Sorry. This is a non-sponsored instance deployed today using the click to deploy.

**Comment by KelvinTegelaar** [comment]
Yeah no.
