### ISSUE TITLE
Failed to retrieve tenants. Perform a permission checks ().

### ISSUE THREAD

**Issue by Exigo-CIPP** [KelvinTegelaar/CIPP#1467]
All of sudden CIPP has stopped retrieving the tenants and showing following error. Please help to fix this issue soon possible.

![CIPP_Error](https://user-images.githubusercontent.com/120699528/230467771-481e1bab-5c01-458d-add0-63841823d045.jpg)

**Comment by KelvinTegelaar** [comment]
This is not the place for support. if you are a sponsor you can contact the helpedesk for this.
