### ISSUE TITLE
We cannot view some of our tenants on the List

### ISSUE THREAD

**Issue by sasinduk** [KelvinTegelaar/CIPP#1473]
### Description

Hello Kelvin,

As we can see in the tenant list, we can see some of our client's tenants are not shown. 
Is there anything that we can shown them on the same?

### Environment data

```PowerShell
Latest version upgraded
```

**Comment by KelvinTegelaar** [comment]
incomplete

**Comment by sasinduk** [comment]
I'm a Microsoft partner and we have 40+ managing tenants.

We have two clients who noticed to be on the CIPP Portal.
But we cannot see them in the Tenant List drop-down.

What could be the issue? Do you need any more information regarding this?

**Comment by KelvinTegelaar** [comment]
This is not the place for support, and your request was incomplete. It explicitly asks for information you chose to ignore. If you want support, you can sponsor and get basic email support, otherwise you're on your own.

**Comment by sasinduk** [comment]
Sorry for the confusion.
Which Sponsor Tier should I need to choose?
