### ISSUE TITLE
Non-compliant Devices showing Compliant

### ISSUE THREAD

**Issue by McKailaPEntara** [KelvinTegelaar/CIPP#1485]
### Description

Under Intune -> Device Management, all devices are showing compliant. We have confirmed devices that are non-compliant are showing compliant.

### Environment data

```PowerShell
Non-sponsored instance
Frontend Version Latest: 3.3.0
Version Backend Latest: 3.3.1
Tried Tenant Cache Clear: True
Tried Token Cache Clear: True
```

**Comment by McKailaPEntara** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
This has been fixed in Dev although no PR has been raised yet as I am waiting to PR something else that we discussed in Discord. When @KelvinTegelaar gets a second to tell me why my other fix is not working, we will PR them both.

**Comment by BNWEIN** [comment]
![image](https://user-images.githubusercontent.com/28929905/232728010-2679bed3-9c51-45b5-afea-39651200d3ac.png)

**Comment by KelvinTegelaar** [comment]
fixed in dev
