### ISSUE TITLE
FEATURE REQUEST: Include 15 Custom Attributes Fields available in Microsoft 365

### ISSUE THREAD

**Issue by CirrusITS** [KelvinTegelaar/CIPP#1492]
We have solicitors as customers and they have professional qualifications that need to appended to the end of their names and a secure email address they need to publish, so we have to store this extra info in the Custom Attributes fields that are available in MS365 in order to access this data from the directory when producing Email Signatures for example.
It would be great to be able to edit and view these fields in CIPP rather than having to access the tenant each time.

**Comment by KelvinTegelaar** [comment]
currently only allowing feature requests by sponsors.
