### ISSUE TITLE
Adding User does not work - No Action when pressing button

### ISSUE THREAD

**Issue by I-T-D** [KelvinTegelaar/CIPP#1540]
### Description

Creating a user via Identity Management -> Users -> Create user has no effect.
Clicking the 'add user' button has no action and does nothing.

Have re-produced this on multiple tenants and have tried other browsers and clearing local cache. I suspect it is a permissions issue however the permissions check passes OK. 

### Environment data

```PowerShell
Non-sponsored instance 
Front end version number: 3.5.0
Back end version number: 3.5.0
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Not a bug, and no sponsor. So no support.

**Comment by I-T-D** [comment]
100% reproduction rate across different environments. Seems like a bug to me.
