### ISSUE TITLE
Out of Office reply doesn't work when email is forwarded to another user (potential fix included)

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1549]
### Description

**Problem:** If Out of Office is set via offboarding wizard and the mailbox is also configured to forward to another user, the OOO reply never gets sent. This happens because the email gets forwarded to another user rather than hitting the deactivated user's Shared Mailbox.

**Potential Fix**
1. Configure the mailbox to forward **with deliver to both the forwarding address and the mailbox checked.**
2. Sign in to the [Microsoft 365 portal](https://portal.office.com/) as an administrator.
3. To open the Exchange admin center, select **Admin**, and then select **Exchange**.
4. In the upper-right corner, select your name, and then select **Open Another user**.
5. Select **Organize Mail**, and then select **Inbox Rules**.
6. Select **New** (![plus-sign-icon](https://learn.microsoft.com/en-us/exchange/troubleshoot/exchangeonline/send-emails/media/senders-not-receiving-out-of-office-notifications/plus-sign-icon.png)), and then select **Create a new rule for arriving messages**.
7. In the **Name** box, specify a name for the rule, and then select **More options**.
8. Under **When the Message Arrives**, select **Apply to all messages**.
9. Under **Do the Following**, point to **Mark the message**, and then select **Mark as read**.
10. Under **Do the Following**, point to **Move, copy or delete**, and then select **Delete the message**.
11. Select **Save**.

With this setup, the Out Of Office message is still delivered, the email can still be forwarded and the Shared Mailbox will not get filled up with items. I am therefore wondering if it is possible to have CIPP perform these steps in the backend when configuring OOO + forwarding in the offboarding wizard

Thanks,

### Environment data

```PowerShell
- Sponsored (self-hosted)
- Frontend: 3.5.0
- Backend: 3.5.0
- Tenant Cache Cleared: N/A
- Token Cache Cleared: N/A
```

**Comment by BNWEIN** [comment]
Additional mailbox forwarding settings have added to the "Edit Mailbox" page under the "Email and Exchange" section which will be released on the next update. With this you can choose to forward and deliver or forward and not deliver. 

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/6143e76a-64e9-4da9-827d-d31ba3933de7)

**Comment by KelvinTegelaar** [comment]
Nkt a bimug, works as designed.
