### ISSUE TITLE
[Feature Request]: Licensing Conflicts/Duplication Alerting/Reporting

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1553]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

hello

please can we have a report or alert that tells us when two licenses are added to a single user that have the same benefits/apps/licenses

had an issue in the past where client is racking up bills paying for two services that have same features

ie Business Basic and Business Standard both contain Exchange Online Plan 1
or Teams Phone and Business Voice etc

appreciate it would be better to know the licensing stack well enough to not need this at the procurement stage, but think it would be helpful...

**Comment by KelvinTegelaar** [comment]
Planned but for one or two releases away
