### ISSUE TITLE
[Feature Request]: Standards - External Quarintine Notification Email

### ISSUE THREAD

**Issue by TetraAsh** [KelvinTegelaar/CIPP#1554]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Easily set an additional recipient for 'RequestRelease' on Quarintined Emails

Microsoft are increasing their protection around 'High Confidence Phishing'.
It is not possible to allow users to actually release these emails, they must be reviewed and released by an admin.

As an MSP we do not monitor individual admin emails in every Tenant, thus we would like to be able to set these alerts to email to external recipients, this would allow such requests from across our tenant base to be forwarded to our ticketing system and dealt with efficiently. 

This has clear benefits for all MSP's to assist in managing these requests

### PowerShell commands you would normally use to achieve above request

Under Connect-IPPSession
https://learn.microsoft.com/en-us/powershell/module/exchange/get-protectionalert?view=exchange-ps
https://learn.microsoft.com/en-us/powershell/module/exchange/set-protectionalert?view=exchange-ps

There is a standard alert called 'User requested to release a quarantined message'
The attribute to be edited is 'NotifyUser' and 'NotificationEnabled'

**Comment by KelvinTegelaar** [comment]
We currently only accept feature requests by sponsors
