### ISSUE TITLE
Failed to set contact emails: Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by MBstatsara** [KelvinTegelaar/CIPP#1559]
### Description

Hello
On all tenants I'm getting the following standards error
Failed to set contact emails: Insufficient privileges to complete the operation.

The email it is setting as the contact look to be correct, but the standard should re-apply, but is obviously erroring and potentially causing issues with other items as we keep seeing items in the same area wiped out.

### Environment data

```PowerShell
backend 3.5.1
Frontend 3.5.1 
Tenant cache has been cleared since the last update.
Permission checks on the tenants and app are all coming back correct.

Non-Sponsored instance.
```

**Comment by KelvinTegelaar** [comment]
Missing GDAP permission. No a bug.

**Comment by KelvinTegelaar** [comment]
This isn't the place for support. If you'd like support you can sponsor the app. :)
