### ISSUE TITLE
[Feature Request]:  Disable/Enable "Add shortcut to OneDrive" from SharePoint Sites in SharePoint Standards

### ISSUE THREAD

**Issue by EtherMadness** [KelvinTegelaar/CIPP#1563]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would like to see a Disable/Enable "Add shortcut to OneDrive" from SharePoint Sites in the SharePoint Standards.

We have several customers that use a synced SharePoint document library instead of a traditional file share.
For a SharePoint document library, you can't use both the Sync and Add shortcut to My files features.

End users add a shortcut to a synced library and the sync breaks.

Microsoft Documentation States:

Symptoms
You create a shortcut to a folder that's stored in a SharePoint Online document library, and then you add the shortcut to OneDrive. When you try to sync the SharePoint Online document library with the Microsoft OneDrive sync app, the sync stops working, and you receive the following error message:

Sorry, we can't sync this folder. You're already syncing a shortcut to a folder from this shared library.

(P.S. Thank you to everyone involved with this project.  Great work!!!)

### PowerShell commands you would normally use to achieve above request

Set-SPOTenant -DisableAddShortcutsToOneDrive $True
Set-SPOTenant -DisableAddShortcutsToOneDrive $False

**Comment by KelvinTegelaar** [comment]
Currently only accepting FR's from sponsors.
