### ISSUE TITLE
Offboarding Wizard Errors 

### ISSUE THREAD

**Issue by joelmacklow** [KelvinTegelaar/CIPP#1565]
I've run the offboarding wizard a couple of times today and got the same errors when deleting users from different tenants:

- Could not add owner to Onedrive for xxxxx@xxxxxxxx.nz. Error: Response status code does not indicate success: 401 (Unauthorized).
- Could not remove license as the users mailbox is still being converted to a shared mailbox.

Not sure what is causing the first error, and the second one appears to be a timing issue when the action is to convert to a shared mailbox AND remove the licensing.

**Comment by KelvinTegelaar** [comment]
Not a bug, support issue. Sponsors can get basic email support.
