### ISSUE TITLE
[Feature Request]: Improve Device Management Actions

### ISSUE THREAD

**Issue by gigacodedev** [KelvinTegelaar/CIPP#1569]
### Current Behavior
The Devices page under Intune Device Management has the following options for Wipes:
- Wipe Device, keep enrollment data: `{ keepUserData: 'false', keepEnrollmentData: 'true' }`
- Wipe Device and Continue at Power Loss: `{ keepUserData: 'false', keepEnrollmentData: 'false', useProtectedWipe: 'true' }`

### Proposed Changes
I would like to update the options available to more accurately match what is available from Intune, adding two additional wipe options. This will provide the following:
- Wipe Device, keep enrollment data: `{ keepUserData: 'false', keepEnrollmentData: 'true' }`
- Wipe Device, remove enrollment data: `{ keepUserData: 'false', keepEnrollmentData: 'true' }`
- Wipe Device, keep enrollment data, and Continue at Power Loss: `{ keepUserData: 'false', keepEnrollmentData: 'true', useProtectedWipe: 'true' }`
- Wipe Device, remove enrollment data, and Continue at Power Loss: `{ keepUserData: 'false', keepEnrollmentData: 'false', useProtectedWipe: 'true' }`

### Reason for Changes
In some scenarios, users may want to decide to remote enrollment data from a device during a wipe, such as when an asset is retired fully and sent for e-waste. Additionally, currently the option to "Wipe Device and Continue at Power Loss" is set by default to remove enrollment data which is not shown to the user initiating the wipe action and may not be wanted. I had initially considered proposing all wipe actions assume proceeding at power loss, but as this may be a destructive action that can prevent the device from properly booting again after, I feel it is best to leave that action as its own option. 

### PowerShell commands you would normally use to achieve above request

N/A, no backend changes are needed. Front end needs to be updated to add additional options to `CippActionsOffcanvas` with different `modalBody` as shown above

**Comment by gigacodedev** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
And resolved. Thank you giga
