### ISSUE TITLE
Admin Password Alert

### ISSUE THREAD

**Issue by CHRIS-BRANNON** [KelvinTegelaar/CIPP#1577]
### Description

The "/roleManagement/directory/roleAssignments?`$filter=roleDefinitionId eq '62e90394-69f5-4237-9190-012177145e10'" endpoint returns all objects, such as users and service principals. When checking a service principal's last admin password change, the graph call fails and increases the graph error count.

### Environment data

```PowerShell
Non-sponsored instance: True
Front end version number: 3.6.0
Back end version number: 3.6.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by CHRIS-BRANNON** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by CHRIS-BRANNON** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
And fixed! Thank you Chris.
