### ISSUE TITLE
[Feature Request]: Add another style of password generation e.g M365

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1578]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

This isn't a big one, but one I think would be worthwhile.

The two password options currently available (classic / correct-battery-horse) generate passwords that aren't the easiest to communicate verbally with the type of user that normally needs a password reset.

If there were 2 options I would add if I had the skills.
M365 Basic > this would result in a password like Buq38449 / Pox44876 etc
M365 Plus > Buqox55873 / Rekux59492

### PowerShell commands you would normally use to achieve above request

This is the PS code I use to create such passwords in ISE

##########################
#     Create Password    #
##########################
function Get-RandomCharacters($length, $characters) {
    $random = 1..$length | ForEach-Object { Get-Random -Maximum $characters.length }
    $private:ofs=""
    return [String]$characters[$random]
}

function Scramble-String([string]$inputString){     
    $characterArray = $inputString.ToCharArray()   
    $scrambledStringArray = $characterArray | Get-Random -Count $characterArray.Length     
    $outputString = -join $scrambledStringArray
    return $outputString 
}
$password = Get-RandomCharacters -length 1 -characters 'BCDFGHKLMNOPRSTVWXYZ'
$password += Get-RandomCharacters -length 1 -characters 'aeiou'
$password += Get-RandomCharacters -length 1 -characters 'bdghklmnprtvz'
$password += Get-RandomCharacters -length 1 -characters 'aeiou'
$password += Get-RandomCharacters -length 1 -characters 'bcdfghklmnprstvwxyz'
$password += Get-RandomCharacters -length 5 -characters '1234567890'

##########################################

Write-Host $password

**Comment by RedRhombus001** [comment]
The problem being solved is communicating passwords verbally to the technically illiterate.

**Comment by KelvinTegelaar** [comment]
No, we have two and that's enough, there is also a danger of having weak passwords as permanent passwords with this method. Sorry :)
