### ISSUE TITLE
Issues with Reporting for User Licensing in Prod

### ISSUE THREAD

**Issue by AlivaTH** [KelvinTegelaar/CIPP#1579]
### Description

1.) Go to User Licensing Reports
2.) Generate a .xlsx or .pdf report for users
3.) Observe the user licensing column as [Object]

### Environment data

```PowerShell
Non-Sponsored instance
Front end version number: 3.6.0 (Latest as of 23/06/2023)
Back end version number- 3.6.1 (Latest as of 23/06/2023)
Tried Tenant Cache Clear: True
Tried Token Cache Clear: True
Reboot static web app: True
```

**Comment by PremierOneData** [comment]
I am seeing the same behavior.

**Comment by digitalfireinc** [comment]
Also seeing the same. Previously this bug has been looked at but at the time the exports contained all fields including LicJoined which has the information correct. But now can't see that field, so we have no license information.
