### ISSUE TITLE
Feature Request: Offboarding Wizard - Display name Prefix

### ISSUE THREAD

**Issue by freedomitltd** [KelvinTegelaar/CIPP#158]
Currently when offboarding a user we add a prefix to their Display Name (We use EXSTAFF but I have seen other MSP's use ZZZ) so that they are easily identified in the user list. For example 'Joe Blogs' becomes 'EXSTAFF Joe Blogs'. Would it be possible to add a field into the offboarding wizard so that a display name prefix could be added?

**Comment by KelvinTegelaar** [comment]
This has been discussed with some community members, and is too unique to implement. We're not considering it for any version under v2.0 but feel free to rerequest.
