### ISSUE TITLE
[Feature Request]: Localization

### ISSUE THREAD

**Issue by PSIT-smiro** [KelvinTegelaar/CIPP#1581]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

CIPP is great and may be greater if localization is implemented. 

i18n should do the job and I would be happy to help. 
https://www.freecodecamp.org/news/how-to-add-localization-to-your-react-app/

**Comment by KelvinTegelaar** [comment]
No, it would add so much work for little reward. We're considering this a wontfix, especially because all m365 core documentation is only available jn english, or badly translated other languages ;)
