### ISSUE TITLE
FEATURE REQUEST: Scheduled Alert when 90% Sharepoint Quota used

### ISSUE THREAD

**Issue by RAVNIT-TR** [KelvinTegelaar/CIPP#1591]
It could be very cool to get an alarm when the SharePoint quota reaches 90%, so that you can buy extra space before the capacity is exceeded.

**Comment by KelvinTegelaar** [comment]
Seeing as we now have that api, sure! added to the list.

**Comment by KelvinTegelaar** [comment]
Added sharepoint quota
