### ISSUE TITLE
[Feature Request]: Version Check - Webhook alert 

### ISSUE THREAD

**Issue by etopple** [KelvinTegelaar/CIPP#1603]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The webhook framework already exists to send webhook alerts - 
It would be nice if we could configure a check to very installed version vs the current version release and then alert when out of sync.

**Comment by gigacodedev** [comment]
I would like to work on this please!
