### ISSUE TITLE
Display Bug: Tenant Selector

### ISSUE THREAD

**Issue by klearnet** [KelvinTegelaar/CIPP#1606]
### Description

Teants with long names overlap the next cell in the tenant dropdown selector, like the below screenshot.

<img width="315" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/99508622/4f240bcb-6bc8-4fcc-b7e3-e74c3d9e109c">

### Environment data

```PowerShell
Front End: 3.7.0
API: 3.7.1
Cache cleared.
Multple web browsers used (Edge, Chrome, Firefox)
```

**Comment by klearnet** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by jbbehar** [comment]
I can confirm I see the same display on Mac and PC with both Edge and Chrome.

**Comment by KelvinTegelaar** [comment]
going to cut these off, search will still work, but display will just be '...' after a specific amount of characters :)
