### ISSUE TITLE
FEATURE REQUEST: Update a mail-enabled security groups and or distribution list from Copy group membership

### ISSUE THREAD

**Issue by Layer-2-Computers** [KelvinTegelaar/CIPP#1607]
Allow the "Copy group membership from other user" when creating or editing a user to work with mail groups:
Right now we get these errors: 
We've failed to add the group supportvm: Cannot Update a mail-enabled security groups and or distribution list.
We've failed to add the group All Users: Insufficient privileges to complete the operation.
We've failed to add the group Support: One or more added object references already exist for the following modified properties: 'members'.
We've failed to add the group Support Team: Cannot Update a mail-enabled security groups and or distribution list.
We've failed to add the group MainOffice: Cannot Update a mail-enabled security groups and or distribution list.

See screenshot below

![image](https://github.com/KelvinTegelaar/CIPP/assets/122993824/3efc890b-1a81-4b7f-a42d-17b6d729f47c)

I would love for this feature to be added :)

Thanks!

**Comment by KelvinTegelaar** [comment]
Added to dev
