### ISSUE TITLE
Permissions Check failed

### ISSUE THREAD

**Issue by MK-Kamal** [KelvinTegelaar/CIPP#1608]
### Description

Thank you a lot for this great project, i had tried to setup CIPP twice but in every time i am getting the same error when running permission check , i had review the document and the application register permission and all is set as the documentation , had cleared the token many time and same permission check error for sure i am missing something , please can you help 

We could not connect to the API to retrieve the permissions. There might be a problem with the secure application model configuration. The returned error is: invalid_grant:AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2023-06-04T07:39:05.6301866Z' and the TokensValidFrom date (before which tokens are not valid) for this user is

### Environment data

```PowerShell
Azure
```

**Comment by KelvinTegelaar** [comment]
Incomplete and not a bug or issue, but support question.

**Comment by MK-Kamal** [comment]
Hi Kelvin,
Can you elaborate more on your comment , are the github repo is not for support ?
Thanks

**Comment by KelvinTegelaar** [comment]
You can pay for support via the 99 dollar sponsorship, Github is only for bugs or feature requests
