### ISSUE TITLE
Performing bulk operations from Identity Management>Administration>Users with "All Tenants" selected error

### ISSUE THREAD

**Issue by shinomen** [KelvinTegelaar/CIPP#1609]
### Description

I was attempting to search all users across "All Tenants" for the word z(Archived) which is what we put in when we are off-boarding a user but don't want to delete the account yet.  When I got the result, I wanted to disable any of these accounts that were still mistakenly enabled so I checked several users from about 4 different tenants and attempted to disable the account of the selected users and got the following error

Specified tenant identifier 'alltenants' is neither a valid DNS name, nor a valid external domain

### Environment data

```PowerShell
Sponsored, Front End: 3.7.0, API: 3.7.2.  Did not clear any tenant caches.
```

**Comment by shinomen** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
