### ISSUE TITLE
FEATURE REQUEST: Reconcile GDAP info with Current Status

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1612]
After a cleanup of GDAP roles in our tenant, the GDAP role list in CIPP still lists all of the roles from it's own internal table. Same for GDAP Migration Status.

For GDAP roles: ideally, there would be a reconciliation/cleanup that makes this list in CIPP match the current GDAP roles that still exist in our partner tenant.

For GDAP Migration Status: ideally, the list would show the current DAP and GDAP status of all known tenants, possibly even allowing for the inclusion of normally skipped tenants, to get a better view of current status rather than the current wizard results log.

**Comment by KelvinTegelaar** [comment]
This is actually done on purpose. You want CIPP to track the groups it has created in the past, and using the role Wizard you can recreate those groups if required.
