### ISSUE TITLE
FEATURE REQUEST:  Improve Filter Visibility and Usage

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1613]
The GDAP Relationship and Exchange Mailbox list views are examples where there are pre-defined filters via the dropdown beside the icon on the filter line as shown in the screenshot below:
![image](https://github.com/KelvinTegelaar/CIPP/assets/33136816/6dfa58ca-39d5-4299-b07e-4d38231eda91)

Ideally, there could be visible buttons that invoke these filters, and are sticky to your user profile. Allowing for multiple filters simultaneously (or condition) could be an added bonus. A mockup to convey what I'm asking is below:
![image](https://github.com/KelvinTegelaar/CIPP/assets/33136816/17bf36a7-e7e5-4a23-b021-48c9392a6f29)

Adding a clear filter button in the text area would also be great!

**Comment by KelvinTegelaar** [comment]
This makes the interface very messy and is not really possible with the structure of the project right now. We'll revisit this after cleaning up the way our filters work.
