### ISSUE TITLE
New CIPP user invite script doesnt work

### ISSUE THREAD

**Issue by MBstatsara** [KelvinTegelaar/CIPP#1615]
### Description

Go to settings, click maintenance select add-cippuser.ps1

This doesnt work unless a custom domain is valid, i have edited the script and tested at my end and it works with the default domain if the value in the script is null.

### Environment data

```PowerShell
Frontend Version
Latest: 3.7.0
Current: 3.7.0
API Version
Latest: 3.7.2
Current: 3.7.2
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev. :)
