### ISSUE TITLE
[Feature Request]: Add standard for Alert Policies

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1617]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have alert policies setup for all customers which we check as part of our regular health checks. However, if we could apply these with a standard it would save us huge amounts of time. 

I think all MSP's would benefit from being able to apply these globally.

**Comment by BNWEIN** [comment]
I would like to upgrade the priority

**Comment by Jr7468** [comment]
```
$alert = Get-ProtectionAlert -Identity "Elevation of Exchange Admin Privilege"

if ($alert.NotifyUser) {
    $Amended = $alert.NotifyUser += ",123@123.com"
} else {
    $Amended = "123@123.com"
}

Set-ProtectionAlert -Identity $alert.Identity -NotifyUser $Amended
```

**Comment by KelvinTegelaar** [comment]
Not possible. Don't have access to these cmdlets
