### ISSUE TITLE
Errors deploying Group Template for a Dynamic Group

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1621]
### Description

I created a template for a dynamic group. When attempting to **Deploy Group Template** after selecting a tenant, and updating the options, in Step 3 of the wizard, I get an error: 

_Failed to create group. Invalid value specified for property 'mailNickname' of resource 'Group'._
![image](https://github.com/KelvinTegelaar/CIPP/assets/33136816/2e44dcf8-9069-416c-9d9c-33abd5f24e0f)

I made sure the UPN suffix matches the tenant's valid domains, and the name hasn't been used before.

I did find one thing suspicious in step 3 of the wizard before the error is given:
![image](https://github.com/KelvinTegelaar/CIPP/assets/33136816/81091439-a4f4-40fa-ba44-8d15bee9b591)
There's an "X" beside the Type instead of a check like the other two items above it.

### Environment data

```PowerShell
Sponsored Instance 
Frontend Version Latest: 3.7.0
API Version Latest: 3.7.2
Tenant Cache Clear: true
Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
the groupnickname is automatically generated for group templates - Try just adding the part before the @ and try again :)

**Comment by jbbehar** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

From: github-actions[bot] ***@***.***>
Date: Thursday, July 13, 2023 at 3:25 PM
To: KelvinTegelaar/CIPP ***@***.***>
Cc: Jim-Barry Behar ***@***.***>, Author ***@***.***>
Subject: Re: [KelvinTegelaar/CIPP] Errors deploying Group Template for a Dynamic Group (Issue #1621)

Thank you for creating a bug. Please make sure your bug is indeed a unique case by checking current and past issues, and reading the complete documentation at https://docs.cipp.app/
If your bug is a known documentation issue, it will be closed without notice by a contributor. To confirm that this is not a bug found in the documentation, please copy and paste the following comment: "I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.".

Without confirming, your report will be closed in 24 hours. If you'd like this bug to be assigned to you, please comment "I would like to work on this please!".

**Comment by jbbehar** [comment]
What happens if there are multiple valid domains in the tenant? Will it then autoselect?

Our use case in this case is to create Dynamic Groups based on the UPN suffix for multi-domain tenants so that we can use the groups with LetSignIt signature solution so in a perfect world, we would be able to specify the domain suffix of the group to match the group we’re creating.

I did just test it and it seems to work.

Maybe the PR becomes an FR to allow you to pick the domain?

From: KelvinTegelaar ***@***.***>
Date: Thursday, July 13, 2023 at 3:35 PM
To: KelvinTegelaar/CIPP ***@***.***>
Cc: Jim-Barry Behar ***@***.***>, Author ***@***.***>
Subject: Re: [KelvinTegelaar/CIPP] Errors deploying Group Template for a Dynamic Group (Issue #1621)

the groupnickname is automatically generated for group templates - Try just adding the part before the @ and try again :)

**Comment by KelvinTegelaar** [comment]
So this works as expected - It could be a feature request, but templates don't make make sense for this unless I'm misunderstanding.
