### ISSUE TITLE
Archive Mailbox Size Miscalculated

### ISSUE THREAD

**Issue by itlogic-github** [KelvinTegelaar/CIPP#1622]
### Description

When looking at a user's Mailbox Archive size - either from the User or Mailbox interface the total size is incorrect. I assume it's just a simple math error.

Example CIPP Shows:
> Total Archive Size: 479.9 GB
> Total Archive Items: 682

Get-MailboxStatistics:
> TotalItemSize: 479.9 MB (503,211,854 bytes)
>  682

### Environment data

```PowerShell
Non-Sponsored Instance
Frontend version: 3.7.0
Backend Version: 3.7.2
Tried Tenant Cache Clear: true
Token Cache Clear: true
```

**Comment by itlogic-github** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
This has been fixed in 

https://github.com/KelvinTegelaar/CIPP-API/pull/378
and
https://github.com/KelvinTegelaar/CIPP/pull/1623
