### ISSUE TITLE
403 Error - User is not allowed to call Get-RecipientPermission

### ISSUE THREAD

**Issue by BrandonKSP** [KelvinTegelaar/CIPP#1626]
### Description

1.) Choose a tenant
2.)Under Email & Exchange, go into Administration - Mailboxes
3.)Click on edit mailbox permissions under any user to open up the new page
4.)Account information will not show up, gives an error top right
![image](https://github.com/KelvinTegelaar/CIPP/assets/128621589/c56cc6d2-d6d6-4cff-9d32-afb6d80bd821)

---

Also spits out:

<html><body>
<div class="card-header d-flex justify-content-between align-items-center"><h5 class="card-title">An error has occurred!</h5></div><div class="card-body"><div class="row"><div class="col-md-6">An
 error has appeared while trying to load your data. For troubleshooting,
 the error information can be found in the table below.<br> <br> This 
type of error is usually indicative an application issue. To 
troubleshoot this issue check if your API is running and reachable, or 
use below error to troubleshoot</div><br> <br><div class="row"><div class="col">

Error | Error Location
-- | --
t.filter is not a function | F@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:19762 oo@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2139361 $s@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2191661 xl@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2178904 Rl@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2178832 Ol@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2178693 vl@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2175659 30534/Ka/<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2125153 13095/t.unstable_runWithPriority@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2340169 Va@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2124930 Ka@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2125100 $a@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2125033 yl@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2175980 notify@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2227312 notifyNestedSubs@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2227724 a@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2227147 _@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:376447 x/</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2450566 357/ae/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:113017 357/re/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:111200 357/te/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:110416 357/ee/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:108946 357/J/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:108304 357/X/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:107283 357/ie/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:114085 357/le/init/middleware/k/k@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:119080 R/</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:2449974 82379/i/</</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:362747 dispatch@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:377945 82379/P/</</g</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:372029 82379/c/s/</<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:364218 82379/c/s/<@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:364323 o@https://365.ksp.ca/static/js/main.5bd9bca3.js:2:365010

</div></div></div></div>
</body>
</html>

### Environment data

```PowerShell
non-sponsored instance
front end version : Latest: 3.7.0
Current: 3.7.0

back end version : (api): Latest: 3.7.2
Current: 3.7.2 

Tried tenant cache clear : true

Tried token cache clear : false
```

**Comment by KelvinTegelaar** [comment]
Not a bug, would be a support issue. There's something wrong with your GDAP/DAP configuration.

**Comment by BrandonKSP** [comment]
Appreciate it! We'll get it rebuilt. Thank you Kelvin. Your project has been outstanding.
