### ISSUE TITLE
[Feature Request]: Add "Offboard User" from user properties

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1629]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The offboarding wizard is great. Before running the user through the offboarding wizard, I verify if the user is active / enabled before running the offboard wizard. Often the end of business week offboarding have the users being disabled, with complete offboarding the following Monday.

I am doing this check from admin > users. 

The request is to add a link from the user panel when you click the 3 vertical dots that goes to "offboard wizard", step 3 of the offboarding wizard.

**Comment by KelvinTegelaar** [comment]
Sounds good. Added.
