### ISSUE TITLE
Offboarding Wizard Not Hiding User from GAL

### ISSUE THREAD

**Issue by PhilTSUK** [KelvinTegelaar/CIPP#1633]
### Description

If i select Hide GAL from the Offboarding Wizard, I get a success response;
![image](https://github.com/KelvinTegelaar/CIPP/assets/140014701/73ebf49e-36c0-4f8e-ab7a-4a9881d493c3)

Howerer the item has not been hidden from the GAL
![image](https://github.com/KelvinTegelaar/CIPP/assets/140014701/5b94e303-2b9a-4d25-938b-6bcf2ee16cc8)

### Environment data

```PowerShell
sponsored instance
front end version : Latest: 3.7.0
Current: 3.7.0

back end version : (api): Latest: 3.7.2
Current: 3.7.2 

Tried tenant cache clear : true

Tried token cache clear : false
```

**Comment by PhilTSUK** [comment]
I have looked through past issues and documentation

**Comment by KelvinTegelaar** [comment]
Solved in dev.

**Comment by PhilTSUK** [comment]
Thanks Kevin, How long will it be before this is released to the hosted version?
