### ISSUE TITLE
[Feature Request]: Send on Behalf

### ISSUE THREAD

**Issue by seerxgith** [KelvinTegelaar/CIPP#1641]
### Description of the new feature - 

It was mentioned under "https://github.com/KelvinTegelaar/CIPP/issues/927" but only "Send As" was added, which is great but could we get "Send on Behalf" added as well? Thanks

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
This has been added https://github.com/KelvinTegelaar/CIPP/pull/1656
