### ISSUE TITLE
FEATURE REQUEST: Alert on User Creation & Deletion outside of CIPP

### ISSUE THREAD

**Issue by johnf-wwit** [KelvinTegelaar/CIPP#1642]
Is your feature request related to a problem? Please describe.
There are times when an account may be created or deleted outside of CIPP such as by directory tools, integrations or by someone else with tenant access. Having sight of when these events happen allows for appropriate actions to be taken in a timely manner as needed.

Describe the solution you'd like
The addition of tenant administration alerts for user create and delete events.

Describe alternatives you've considered
Microsoft Alert Policies does not have the option for these alerts.

**Comment by KelvinTegelaar** [comment]
currently not accepting bug reports/feature requests by non-sponsors due to CIPP workload. Feel free to sponsor and request a reopen.
