### ISSUE TITLE
Azure portal link on the dashboard opens the wrong tenant

### ISSUE THREAD

**Issue by PeakeIT** [KelvinTegelaar/CIPP#1646]
### Description

The Azure portal link on the Dashboard doesn't work (it always goes to our Azure portal instead of the client's).

The URL is currently that CIPP uses is: https://<span/>portal.azure.com/?tid=\<client domain> but it should be: https://<span/>portal.azure.com/#@\<Tenant ID>

### Environment data

```PowerShell
non-sponsored instance
front end version : Latest: 3.8.0
Current: 3.8.0

back end version : (api): Latest: 3.8.1
Current: 3.8.1 

Tried tenant cache clear : false

Tried token cache clear : false
```

**Comment by PeakeIT** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
currently not accepting bug reports/feature requests by non-sponsors due to CIPP workload. Feel free to sponsor and request a reopen.
