### ISSUE TITLE
Feature request: Manage breakglass accounts

### ISSUE THREAD

**Issue by mrapoc** [KelvinTegelaar/CIPP#165]
Be able to create breakglass admin accounts across all tenants, push password changes or even schedule. Get alerts on breakglass usage.

Future expansion is document this account and password to hudu and it glue which would be useful for technician use or if end user (manager) would like access in emergency

**Comment by KelvinTegelaar** [comment]
Microsoft partners are not allowed to have breakglass accounts per the Microsoft Partnership security requirements. Your SAM credentials are a breakglass method,. that you can use to create a temporary account as required at moments it is needed. Closing this as a wontfix :)
