### ISSUE TITLE
Error when Enabling Online Archive from Email & Exchange

### ISSUE THREAD

**Issue by STG-Tanner** [KelvinTegelaar/CIPP#1655]
### Description

1). Go to Email & Exchange > Administration > Mailboxes and View a user
2). Select Enable Online Archive
3). Receive an error: "...The operation couldn't be performed because object 'null' couldn't be found..."

The request URL appears to reference the account UPN rather than the GUID like it is under Identity Management > Administration > Users > View.

### Environment data

```PowerShell
Sponsored instance
Frontend Version number: 3.8.0
Backend Version number: 3.8.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by STG-Tanner** [comment]
I would like to work on this please!

**Comment by STG-Tanner** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by BNWEIN** [comment]
Fixed in Dev https://github.com/KelvinTegelaar/CIPP/pull/1656
