### ISSUE TITLE
[Feature Request]: New Scheduled Alert Option for Licensed Users without MFA

### ISSUE THREAD

**Issue by DarkPhoenixMike** [KelvinTegelaar/CIPP#1661]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently the only alerts available are:
- "users without any form of MFA"
- "admins without any form of MFA"

It would be very helpful to be able to alert on any licensed users without any form of MFA. Having something like a toggle filter for IsLicensed/IsEnabled or additional options for them to get the automated alerts would save a lot of time over having to manually pull/generate reports for every client every time as usually we don't necessarily care about the disabled/non-licensed users and having them included in every alert email when the base alert is enabled is very cumbersome and not as helpful as one would hope!

**Comment by BNWEIN** [comment]
The current alert for users with MFA only looks users that are enabled as can be seen in the code on line 107 here: https://github.com/KelvinTegelaar/CIPP-API/blob/master/Scheduler_Alert/run.ps1

`$users | Where-Object { $_.Usertype -eq 'Member' -and $_.BlockCredential -eq $false }`

A user being licensed or not, should not be a blocker to enabling MFA. Any enabled user who can sign in should have MFA.

**Comment by KelvinTegelaar** [comment]
Next to just accepting FRs from sponsors at the moment, above is true too :)
