### ISSUE TITLE
Editing Mailbox permissions - adding multiple users with send as permissions

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1662]
### Description

I just added 4 users with send-as permissions on a mailbox.

When I clicked "Edit user permissions" to assign, I got 4 lines that all said the same thing 
eg. "Added user1@domain.com user3@domain.com user3@domain.com user4@domain.com with send as permissions".

Permissions seemed to apply OK.

### Environment data

```PowerShell
Self hosted
Front 3.8.0
Back 3.8.2
```

**Comment by BNWEIN** [comment]
I would like to work on this please!

**Comment by BNWEIN** [comment]
This has been fixed in Dev https://github.com/KelvinTegelaar/CIPP-API/pull/400
