### ISSUE TITLE
[Feature Request]: Group Targeting for Intune Configuration Policies and Intune Apps

### ISSUE THREAD

**Issue by quinc007** [KelvinTegelaar/CIPP#1666]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

At the moment the only assignment options for Intune Configuration Policies and Applications within CIPP are "All Users" and "All Devices". Very often applications or policies only need to be applied to a subset of users/devices within a client tenant, and therefore having the ability to select an Azure AD group as the target for these would be extremely helpful.

**Comment by KelvinTegelaar** [comment]
Currently only accepting FRs from sponsors.
