### ISSUE TITLE
Standards Not Applying to All Selected Tenants

### ISSUE THREAD

**Issue by DarrenChap** [KelvinTegelaar/CIPP#167]
**Describe the bug**
Standards do not seem to apply when selecting multiple tenants

**To Reproduce**
When applying standards to multiple tenants (9 in this case) I select the tenants I want to apply the standards to and then the standards to apply (Audit Log in this case) and then Apply.  I then check the applied standards section and only one or two of the tenants are listed as having the standard applied.  Checking in the log also confirms the standard only applied to two tenants.

**Expected behavior**
The standard I select should be applied to all tenants I selected

Running on Dev Branch.
CIPP Version: 1.2.1
CIPP API Version: 1.2.3

**Comment by KelvinTegelaar** [comment]
We'll need some more info, the standards only run every 3 hours. Did you wait the full amount? two runs maybe? 

Please check if your exchange SAM key is working, as we're using that for most of the standards.

**Comment by DarrenChap** [comment]
Yes applied this morning and then this afternoon.  The standards appear in the applied standards list immediately though and there are only two tenants there?  Will check it again in the morning and also by then the BPA should hgave run so I can see easily if the red crosses are gone.

**Comment by KelvinTegelaar** [comment]
The "Applied" tenant list is a bit of a misnomer, its more "Planned Standards". If you only see two devices there, it has not scheduled the other ones. Try readding those.

**Comment by DarrenChap** [comment]
Ok will leave it for now and check again in the AM just so it has time to get all straight with the world.  If I selected 9 tenants and applied a single standard to 9 tenants at the same time then I expect I would be able to see that somewhere unless I was unlucky enough to press Apply a microsecond before the scheduled task ran?

Lovin' it by the way.

**Comment by DarrenChap** [comment]
Updated to dev version (1.2.2/1.2.4) and tested again and now it seems to be working as expected.
