### ISSUE TITLE
Editing user reverts changes when pressing "edit user"

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1672]
### Description

Editing user reverts changes when pressing "edit user".

I have tried the following
Test 1: Changing
Display name
Username
Primary Domain
>Click edit user
>> Message "Success. The user has been edited."
:: Result is that all changes revert back

Test 2: Changing just the Primary domain
>Click edit user
>> Message "Success. The user has been edited." (appears at both top and bottom of page)
:: Result is that all changes revert back
:: After refreshing page it appears the change was successful.

Test 3: Changing just the Display Name
>Click edit user
>> Message "Success. The user has been edited." (appears at both top and bottom of page)
:: Result is that all changes revert back
:: After refreshing page it appears the change was successful.

Test 4: Changing just the username
>Click edit user
>> Message "Success. The user has been edited." (appears at both top and bottom of page)
:: Result is that all changes revert back
:: After refreshing page it appears the change was NOT successful after first attempt, but was after the second.

### Environment data

```PowerShell
3.8.0
3.8.2
```

**Comment by KelvinTegelaar** [comment]
It doesn't revert. The Graph API can take up to 10 minutes to process a change.

**Comment by RedRhombus001** [comment]
> It doesn't revert. The Graph API can take up to 10 minutes to process a change.

Thanks. It was just odd that as soon as I clicked "edit user" all my changes disappeared and refreshing showed the changes I made actually worked. It seemed like it was a UI issue.
