### ISSUE TITLE
Dashboard "Not supported"

### ISSUE THREAD

**Issue by ChristianVoigtJensen** [KelvinTegelaar/CIPP#1680]
### Description

On the dashboard, it says "Not supported" at "Total Users" etc.

Is it because I have more than 2500 users / clients?

Can we make the limit higher ? For example 25.000 users? Would be appreciated! 

### Environment data

```PowerShell
Self hosted instance - (as a start to check out the features.)
Front end version number: 3.8.0
Back end version number: 3.8.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by rvdwegen** [comment]
The AllTenants selection doesn't support the user counts at all, regardless of the total users over all customers.
