### ISSUE TITLE
Unable to see tenants added after setup

### ISSUE THREAD

**Issue by TFSimon** [KelvinTegelaar/CIPP#1682]
### Description

We have added 2 new tenants to our partner center, unfortunately, they're not visible in CIPP.

Steps taken:
Waited 24+ hours
Tenant Cache cleared
Browser Cache cleared
Different browser used
Added Azure plan to one of the tenants

### Environment data

```PowerShell
Sponsored edition.
Front: 3.8

All cahes cleared
```

**Comment by KelvinTegelaar** [comment]
Sponsors can get support via support email, check your welcome email for the email address. :) You might just need to add a Lighthouse license because you added it as GDAP instead of DAP: https://docs.cipp.app/setup/installation/index

**Comment by TFSimon** [comment]
> 

They don't.  We've got GDAP on these but I don't think people ran a reseller relationship.
Running these now.
