### ISSUE TITLE
Create new user in client tenant

### ISSUE THREAD

**Issue by ChristianVoigtJensen** [KelvinTegelaar/CIPP#1683]
### Description

When I create a new user in a client tenant, it works fine, but the user doesnt appear in "Identity Management" > "Users".

It says a total of 21 users, but on the dashboard it says 22 users?

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 3.8.0
Back end version number: 3.8.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Not a bug, only sponsors get support.
