### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Rithmatist** [KelvinTegelaar/CIPP#1684]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hello, could this be a potential new feature for SharePoint Standards?

This feature would prevent items from this site from being downloaded by offline clients.

Currently, it's not possible to apply this at the site collection level (to the best of my knowledge). Moreover, if this feature runs every 4 hours, it could automatically apply to newly created sites.

### PowerShell commands you would normally use to achieve above request

#Parameters
$AdminSiteURL = "https://YourTenantName-admin.sharepoint.com"
  
#Connect to SharePoint Online Admin Center
Connect-PnPOnline -Url $AdminSiteURL -Interactive
  
#Get All Site Collections
$Sites = Get-PnPTenantSite
  
ForEach ($Site in $Sites)
{
    #Connect to the Site
    Connect-PnPOnline -Url $Site.Url -Interactive
  
    #Get the Web
    $Web = Get-PnPWeb -Includes ExcludeFromOfflineClient
  
    #Set "Allow items from this site to be downloaded to offline clients?" to "No"
    $web.ExcludeFromOfflineClient = $False
    $web.Update()
    Invoke-PnPQuery
 
    Write-Host "Offline Client Availability is Disabled for $($Site.Url)" -f Green
}

**Comment by KelvinTegelaar** [comment]
only accepting FR's by sponsors.
