### ISSUE TITLE
[Feature Request]: Add standard for llow user consent for apps from verified publishers, for selected permission

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#1685]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

At the moment within CIPP > **Tenant Administration > Standards > Azure AD Standards,** you can enable 'Require admin consent for applications' in bulk. 

This is great, but would there be a way to enable the MS recommended option of 'Allow user consent for apps from verified publishers, for selected permissions' please? 

I feel this would be useful for MSP's as it's enforcing MS recommended practices in bulk to their managed tenants. 

Thanks! 

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?pivots=ms-powershell

**Comment by KelvinTegelaar** [comment]
While I don't mind adding the standard, I do feel the need to add a note that this is less secure than the general option we have at the moment, and doesn't follow the CIS benchmark as **anyone** can create a cerified app with "read user" and "read user inbox" and get permitted by the default state.

**Comment by KelvinTegelaar** [comment]
added

**Comment by Novem-MSP** [comment]
> While I don't mind adding the standard, I do feel the need to add a note that this is less secure than the general option we have at the moment, and doesn't follow the CIS benchmark as **anyone** can create a cerified app with "read user" and "read user inbox" and get permitted by the default state.
> 
> I do understand there's a need for this standard though, especially when you have changed the allowed permissions map yourself.

Thanks for adding Kelvin. Noted your advice the allowed permissions map. Appreciate it!
