### ISSUE TITLE
Can we please get the ability to Set the Conditional Access Policy status when we deploy from a template?

### ISSUE THREAD

**Issue by pro2022m** [KelvinTegelaar/CIPP#1688]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Can we please get the ability to Set the Conditional Access Policy status when we deploy from a template?

**Comment by KelvinTegelaar** [comment]
implemented

**Comment by pro2022m** [comment]
Thank you!
