### ISSUE TITLE
[Feature Request]: Offboarding Wizard - Allow Multiple Selections in "Give Other User Full Access" & "Forward Email to Another User" Section

### ISSUE THREAD

**Issue by JRivett-ITSG** [KelvinTegelaar/CIPP#1689]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Requesting the ability to select multiple users when assigning full access within the offboarding wizard for the following fields:
![image](https://github.com/KelvinTegelaar/CIPP/assets/121971416/36ba74b2-6d88-46aa-915d-cd700e5d121e)

This would improve operations by allowing MSPs to fulfill the client request for multiple users to have full access to the mailbox, onedrive, multiple forwards, etc. without having to go back to the admin portal / powershell to finish assigning permissions / forwards.

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/powershell/module/exchange/add-mailboxpermission?view=exchange-ps
https://activedirectorypro.com/how-to-give-onedrive-access-to-another-user/
https://learn.microsoft.com/en-us/exchange/recipients/user-mailboxes/email-forwarding?view=exchserver-2019

**Comment by JRivett-ITSG** [comment]
> we only accept FRs by sponsors

We are sponsors:
![image](https://github.com/KelvinTegelaar/CIPP/assets/121971416/35ddb562-8330-44a1-96d9-8007d2566775)

**Comment by KelvinTegelaar** [comment]
Implemented in dev
