### ISSUE TITLE
Region Selection

### ISSUE THREAD

**Issue by AussieDumbAss** [KelvinTegelaar/CIPP#17]
Don't seem to be able to select many regions, have tried in multiple tenants to make sure it's not some fancy setting I'm missing.
![image](https://user-images.githubusercontent.com/26104461/137448895-bf26727d-e9c2-4d94-8160-29b0ae22e957.png)

Would like to be able to deploy in Australia

**Comment by WindowsPSAdmin** [comment]
https://twitter.com/nthonyChu/status/1449099782559911936?t=fNe8IefSCv285hsMCi99fw&s=19

Got a reply from your boys. 
Anything you can do?

**Comment by KelvinTegelaar** [comment]
Please see the updated installation manual @WindowsPSAdmin
