### ISSUE TITLE
[Feature Request]: Report on DL members

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#1700]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

 Reporting Distribution List Membership
Would ideally like a report that generates  Distribution Lists and  members 

### PowerShell commands you would normally use to achieve above request

Here are some resources how to achieve the report via Graph   

https://office365itpros.com/2022/12/06/distribution-list-membership-sdk/
https://github.com/12Knocksinna/Office365itpros/blob/master/ReportDLMembershipsCounts-MgGraph.PS1

**Comment by Novem-MSP** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
You can already do this via Groups -> Edit group, where it has an export button for the member/owner list.

**Comment by Novem-MSP** [comment]
I would like a report of all distribution groups and members.

**Comment by Novem-MSP** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
Added the optional column in the group overview "membersCSV, which gives you the members for each list.
