### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by danielwojcikcodux** [KelvinTegelaar/CIPP#1701]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great to have a way of automating user-device affinity without the need for SCCM cross-tenant. Our approach would be to add an extended attribute to each device (for MEM filtering) or generate a device group (containing devices based on the primary users' membership of a management group). In summary we intend to add users to a single group called "Microsoft 365 Managed Users" and by extension each user-assigned device in this group will receive our policy stack.

**Comment by KelvinTegelaar** [comment]
we currently only accept Frs by sponsors.

**Comment by danielwojcikcodux** [comment]
> Thanks, we would be happy to become a sponsor. Love the project.
