### ISSUE TITLE
Error when using Password reset (must change) from action menu

### ISSUE THREAD

**Issue by dsghi** [KelvinTegelaar/CIPP#1709]
### Description

If I go to Identity Management> Administration > Users and tick the box next to an account, then use the menu to select 'Password reset (must change)' I receive an error message:

An error has occurred!
An error has appeared while trying to load your data. For troubleshooting, the error information can be found in the table below.

This type of error is usually indicative an application issue. To troubleshoot this issue check if your API is running and reachable, or use below error to troubleshoot

Error	Error Location
o.join is not a function	TypeError: o.join is not a function at https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:25097 at Array.map (<anonymous>) at F (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:24882) at oo (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2141314) at Ho (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2150881) at $s (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2194605) at xl (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2180855) at Rl (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2180783) at Ol (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2180646) at vl (https://cipp.ignitetheday.com/static/js/main.5483038f.js:2:2177612)

If I instead open the user record to edit and check the boxes for 'Reset Password' and 'Require password change at next logon', the update is successful.

### Environment data

```PowerShell
Non-sponsored instance
Front end: 4.0.1
Back end: 4.0.1
Clear Tenant cache: true
Token cache clear: true
```

**Comment by dsghi** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
solved in dev
