### ISSUE TITLE
Send an interactive authorization request for this user and resource.

### ISSUE THREAD

**Issue by Danpoulter97** [KelvinTegelaar/CIPP#1716]
### Description

All of our tenants get the below error when attempting to connect to:

Graph Error: invalid_grant:AADSTS65001: The user or administrator has not consented to use the application with ID 'App_ID' named 'CIPP_'. Send an interactive authorization request for this user and resource.

### Environment data

```PowerShell
Non Sponsored
Frontend:4.1.0
API:4.1.1
Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Not a but, only sponsors get support.
