### ISSUE TITLE
FEATURE REQUEST: OneDrive Disable Sync

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1717]
Per the Discord discussion on the topic of OneDrive Sync vs Shortcuts, provide a way in CIPP to block OneDrive Sync to Desktop.

Per @rvdwegen 

PATCH https://TENANTNAME-admin.sharepoint.com/_api/SPOInternalUseOnly.Tenant
body:
{
  "HideSyncButtonOnODB": true
}

**Comment by jbbehar** [comment]
It occurs to me that through the UI, users can possibly already have some shortcuts, and OneDrive doesn't like duplicate shortcuts or even partial path duplicates and errors out.

Perhaps if this is being designed as a standard, with a desired state configuration, part of the rollout of the standard might need to be list all shortcuts, remove the shortcuts, and add them back in a consistent way. When you do create a shortcut from the SharePoint library or Teams library UI, the first shared folder is named one way, and the subsequent folders are named slightly differently.

**Comment by Pukkahq** [comment]
We have been testing this and I think this is the command that need to be ran.
https://learn.microsoft.com/en-us/sharepoint/sharepoint-sync#sharepoint-file-sync-and-onedrive-shortcuts

Would also be nice if we can add the shortcut to the users one drive,
https://github.com/derpenstiltskin/onedriveshortcuts

**Comment by KelvinTegelaar** [comment]
That's already possible, and hiding the button does not disable the sync. You can copy and paste the URL, or just use onedrive and set it up.

**Comment by KelvinTegelaar** [comment]
So Microsoft makes this pretty dang hard to actually achieve over all venues/approaches. Closing this for now as we've requested a new MS API for it.
