### ISSUE TITLE
FEATURE REQUEST: Publish OneDrive Shortcuts to Users

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1718]
Based on the Discord discussion, push Document Libraries to Users as OneDrive Shortcuts for Document Libraries.

This will make OneDrive/SharePoint/Teams document libraries easier for end users to navigate and provides significant benefits to mobile users for accessing documents.

**Comment by jbbehar** [comment]
It occurs to me that through the UI, users can possibly already have some shortcuts, and OneDrive doesn't like duplicate shortcuts or even partial path duplicates and errors out.

Perhaps if this is being designed as a standard, with a desired state configuration, part of the rollout of the standard might need to be list all shortcuts, remove the shortcuts, and add them back in a consistent way. When you do create a shortcut from the SharePoint library or Teams library UI, the first shared folder is named one way, and the subsequent folders are named slightly differently.

**Comment by KelvinTegelaar** [comment]
added in dev.
