### ISSUE TITLE
Tenant Lookup tool - HTTP 500

### ISSUE THREAD

**Issue by haidars** [KelvinTegelaar/CIPP#1724]
### Description

CIPP Version: 4.1.0
CIPP-API Version : 4.1.1

Page in error:

https://{#CIPP-URL}/tenant/administration/tenantlookup?tenant={#domain.tld}&SearchNow=true&random=dc8qy

Whenever we try to use the Tenant Lookup function, it end up with HTTP 500 erreur code.

We have already try to clear all cache and redeployed the app and update to latest version.

To my understanding, it seem that the issue with the graphApi on the tenantrelationship call.

regards

### Environment data

```PowerShell
CIPP Version: 4.1.0
CIPP-API Version : 4.1.1
```

**Comment by KelvinTegelaar** [comment]
Not a bug, support issue. If you need support you can sponsor and contact the helpdesk
