### ISSUE TITLE
Tenant Selector match failure for domain names

### ISSUE THREAD

**Issue by DarrenWhite99** [KelvinTegelaar/CIPP#1726]
### Description

When selecting the Tenant Selector dropdown in the page Header and searching for a tenant, you are shown a list with Organization Names and Default Domains, like "MyCompany, Inc (bigbusiness.com)"
Searching for "MyCompany" or "Company" or "Inc" matches as expected, but searching for "big" or "business" fails to match.

I discovered that searching with a leading "(" will match the domain, so "(bigbus" will return a match. I could not find a way to get a partial domain match to work.

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 4.1.0
Back end version number: 4.1.1? (API Version, I don't see "Back end" version in the UI)
Tried Tenant Cache Clear: true
Tried Token Cache Clear: false
```

**Comment by DarrenWhite99** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by DarrenWhite99** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.".

**Comment by DarrenWhite99** [comment]
Come on @github-actions bot... What does it take to mark an issue as confirmed by user?

**Comment by KelvinTegelaar** [comment]
Resolved, we use Fuse Fuzzy Search, Fuse had a maximum distance and matching logic which caused this to not match. Replaced with a bit more custom function.

**Comment by DarrenWhite99** [comment]
Yay!
