### ISSUE TITLE
[Feature Request]: Domains Analyser Filter by Fallback Domain

### ISSUE THREAD

**Issue by STG-Tanner** [KelvinTegelaar/CIPP#1739]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to be able to filter by onmicrosoft.com domains from the Domains Analyser. The addition a predefined filter to hide fallback domains would be a nice touch.

I pictured something like this:
![image](https://github.com/KelvinTegelaar/CIPP/assets/102822322/e225faa5-9217-423e-b78d-1bd1af02700f)

Having all domains included all the time can make it difficult to determine domain health at a glance.

**Comment by rvdwegen** [comment]
Nothing that immediately indicates the domain is an onmicrosoft gets shipped to the front end. From what I can google the table filter doesn't have the capability to do a -like or regex so I think the only solution here is to include a isOnmicrosoft = $true/$false and we can then include a filter for that?

**Comment by STG-Tanner** [comment]
After some more reading today, I think fallback domain was the wrong term to use here. Multiple onmicrosoft.com domains can exist under a single tenant, while only one is designated as the fallback domain. This probably makes IsInitial an unreliable source as well.

If there was a simple way to inverse the table filter, I suppose that would work as well.

**Comment by KelvinTegelaar** [comment]
Resolved with new filters: https://docs.cipp.app/user-documentation/shared-features/filters

`Complex: domain notlike onmicrosoft`
