### ISSUE TITLE
FEATURE REQUEST: Exclude domains from domain analyser

### ISSUE THREAD

**Issue by CortComp** [KelvinTegelaar/CIPP#1744]
Under Domain Analyser, many vendor domains get pulled (signatures, email markup vendors, etc).  Some have already been excluded (exclaimer, codetwo, etc).  I would like to ask that Inky Phish Fence be excluded as well (all of their domains are in the format of somerandomstring.client.inkyphishfence.com).

Or, alternatively, add a place under settings where you can add domains to exclude. If you go this route, recommend a button to replace or next to "delete this domain" under domain's advanced view to add said domain to the list on a one by one basis right from the domain analyser view.

**Comment by KelvinTegelaar** [comment]
Only sponsors can make feature requests

**Comment by KelvinTegelaar** [comment]
Reopened, sponsor label shown up right when closed. Thanks for soonsoring. We're putting this under consideration.

**Comment by KelvinTegelaar** [comment]
Resolved with new filters: https://docs.cipp.app/user-documentation/shared-features/filters

`Complex: domain notlike onmicrosoft`
