### ISSUE TITLE
[Feature Request]: Exclude Tenants from Standards/All Tenants

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#1746]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I need to be able to exclude some tenants from the Standards/All Tenants deployment

as although we have partnering for licensing/viewing purposes, some clients we dont manage their env so don't wana make those changes

FYI, I am sponsor - raffi/raf

**Comment by KelvinTegelaar** [comment]
Closing as part of a bigger picture thing that's on the roadmap. something like this may be coming.
