### ISSUE TITLE
Corrupted IntuneTemplates when editing them

### ISSUE THREAD

**Issue by DanielWahlgren** [KelvinTegelaar/CIPP#1750]
### Description

When updating an IntuneTemplate by clicking the eye-icon under Intune - Device Management - Templates, making a change, for example updating the displayName, and pressing enter, the new JSON saved to the AzureTable is broken.

Testupdate on a copy of build in CIPP-Template (since CIPP restores the built in ones):
`{
  "name": "EVT Screen Timeout Settings",
  "platforms": "windows10",
  "technologies": "mdm",
  "roleScopeTagIds": [
    "0"
  ],
  "settings": [
    {
      "@odata.type": "#microsoft.graph.deviceManagementConfigurationSetting",
      "settingInstance": {
        "@odata.type": "#microsoft.graph.deviceManagementConfigurationSimpleSettingInstance",
        "settingDefinitionId": "device_vendor_msft_policy_config_localpoliciessecurityoptions_interactivelogon_machineinactivitylimit_v2",
        "simpleSettingValue": {
          "@odata.type": "#microsoft.graph.deviceManagementConfigurationIntegerSettingValue",
          "value": 300
        }
      }
    }
  ],
  "displayName": "TEST EVT Screen Timeout Settings",
  "description": "Sets the screen to lock after 5 minutes of inactivity",
  "Type": "Catalog",
  "GUID": "12160216-bf64-4eba-b730-1f2946d73655"
}`

Though instead of the above being saved to table storage, the following is saved:
`{
    "name": "EVT Screen Timeout Settings",
    "displayName": "TEST EVT Screen Timeout Settings",
    "description": "Sets the screen to lock after 5 minutes of inactivity",
    "Type": "Catalog",
    "settings": [{
            "@odata.type": "#microsoft.graph.deviceManagementConfigurationSetting",
            "settingInstance": "System.Collections.Hashtable"
        }
    ],
    "technologies": "mdm",
    "platforms": "windows10",
    "roleScopeTagIds": ["0"]
}`

The policy also no longer shows up in the list of Templates.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 4.2.1
Back end version number: 4.2.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by DanielWahlgren** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
confirmed to be a bug, the issue is that the JSON templates for intune are retrieved in a different way than all other templates, when you save a template the data is saved in the format for all regular templates, it needs to have it's own schema to be able to work.

To resolve this we'll have to revisit the template system for Intune, and make this match the schema we need for all other templates. That's going to be done in the next iteration, so expect +-3 weeks.

**Comment by cslfmsp** [comment]
We hit this too, thank you!

**Comment by DanielWahlgren** [comment]
Just poking this so it isn't closed automatically, preventing users from finding it as easily.
