### ISSUE TITLE
[Feature Request]: Applied Standards list in Tenant Dashboard

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#1752]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

While having the visibility of the applied standards is very welcome on the dashboard, the list can be very long and it makes the dashboard require scrolling to reach potentially more important features such as actions and portals.

There are two possible visual solutions that quickly come to mind:
1. reordering the sections so that standards are below the pods for portals or actions
2. collapsing the standards into an outline or tree view that can be expanded by the viewer as needed

**Comment by KelvinTegelaar** [comment]
showing 5 per default now, with a see more button if there are more available.
