### ISSUE TITLE
Feature Request: 3rd Party Spam Filter IP Rules

### ISSUE THREAD

**Issue by scubes13** [KelvinTegelaar/CIPP#176]
**Is your feature request related to a problem? Please describe.**
For all tenants, we have to setup connector rules for the third party email filter that is in use (ProofPoint).

**Describe the solution you'd like**
It would be great to deploy the connector and monitor for its accuracy across all tenants.

**Describe alternatives you've considered**
Manually deploying the rules via PowerShell scripts.

**Additional context**
Example: https://www.reddit.com/r/PowerShell/comments/happdo/o365_proofpoint_essentials_connector_creation/

**Comment by KelvinTegelaar** [comment]
As discussed in the CIPP discord, we've nixed this for now, as it's too specific for where we are in the process. This might be a feature for later though.
