### ISSUE TITLE
[Feature Request]: Add Guests to Groups

### ISSUE THREAD

**Issue by Jr7468** [KelvinTegelaar/CIPP#1764]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, guests are shown properly in the user list, but when trying to modify a group to add the guests, it doesn't pick them up properly. Would be good if we were able to add Guests to groups properly.

**Comment by KelvinTegelaar** [comment]
Resolved by MrGeek
