### ISSUE TITLE
Feature request: Windows defender monitoring overview (single pane of glass)

### ISSUE THREAD

**Issue by zenmechanic** [KelvinTegelaar/CIPP#177]
With this just being announced: https://techcommunity.microsoft.com/t5/small-and-medium-business-blog/introducing-microsoft-defender-for-business/ba-p/2898701 .. I'm sure that M365 lighthouse will have some level of tenant defender monitoring (likely half baked), but will CIPP integrate defender status with an overview from all delegated tenants?

Currently only CSP tenants are listed in lighthouse. If you are a partner that is more of an advisor than a reseller, you don't get to see your customer base in lighthouse.

**Comment by KelvinTegelaar** [comment]
We'll have to wait until these APIs become available, I've marked this one to review at a later version in Q2 2022, when M365 Business is expected to release fully. :)
