### ISSUE TITLE
[Feature Request]: Notification for when a tenant becomes available in CIPP

### ISSUE THREAD

**Issue by Yoshify** [KelvinTegelaar/CIPP#1770]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have webhook alerts set up over all available tenants in CIPP that reach out to a monitoring system that executes some workflows (such as inbox rule monitoring) and feeds information back into ConnectWise Manage.

What we're worried about is the ongoing maintenance of adding tenants to these webhook alerts - we want it to apply to all tenants, so a human will need to have a look and see if the tenant is available in CIPP yet, and if so, add a webhook alert for them.

What we'd like to do (if it isn't possible already) is be alerted when a tenant becomes available in CIPP. This would allow us to execute workflows that'll schedule a person to add the webhook alert for that tenant explicitly and ensures that our webhook alert list stays up to date.

I'd also settle for the ability to have a webhook alert apply to all tenants in general, but understand there'd be limitations with that as is given that webhooks need to be created in the tenant and depends on audit logs being enabled, etc.

**Comment by KelvinTegelaar** [comment]
We only accept FR's by sponsors.

**Comment by Yoshify** [comment]
Our org, @HealthITAU , was happy to sponsor given the benefit we've gained from CIPP. Could we reopen this FR? :)
