### ISSUE TITLE
[Feature Request]: Bulk disable Shared Mailboxes with Enabled Account

### ISSUE THREAD

**Issue by bayonhealth** [KelvinTegelaar/CIPP#1772]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I see the CIPP can report on Shared Mailboxes with Enabled Account, but I don't see a while to bulk disable all of them at once. I can click on each one, but that is tedious. This would be a handy feature for tenants that first get introduced to CIPP to get to a good baseline. Then we can use CIPP to disable enabled account using the offboarding wizard moving forward to further prevent the problem.

I'm also new to CIPP and maybe there is already a way to do this, but I poked around and didn't see a way.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
