### ISSUE TITLE
[Feature Request]: CIPP based tenant grouping/collection

### ISSUE THREAD

**Issue by IzzyBizzy45** [KelvinTegelaar/CIPP#1774]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Feature would be a group/collection that you have in CIPP that contains tenants that you specify and can have stuff that apply to the "All Tenants" option apply to that group/collection instead.

Useful for MSPs that have a level system where they'd like policies/standards only apply to a select amount of their tenants in their Partner portal. 
Allows them to save a lot of time when initially setting up policies/standards and then changing them in the future as at the moment, you'll need to apply the policies/standards individually or to all tenants

**Comment by KelvinTegelaar** [comment]
We only accept frs by sponsors.
