### ISSUE TITLE
MFA Report

### ISSUE THREAD

**Issue by stienjo1993** [KelvinTegelaar/CIPP#1778]
### Description

![MicrosoftTeams-image](https://github.com/KelvinTegelaar/CIPP/assets/129944407/3f44504e-60ee-4723-b03d-a0590610fd76)
![MicrosoftTeams-image (1)](https://github.com/KelvinTegelaar/CIPP/assets/129944407/b33974e3-a3c4-4616-b4af-07cda32a7038)
MFA report in CIPP is showing that MFA is enforced through Conditional access for this customer see the report attached.
When you sign in to the customers office 365 portal it is showing that there is a conditional access on report-only, MFA is not enforced only reported.
CIPP is showing it is enforced.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 4.2.1
Back end version number: 4.2.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by stienjo1993** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by leonminnee** [comment]
Even the AccountEnabled field isn't correct filled in this report. We've checked multiple accounts at Tenant Users page which are Enabled there, but in the report are disabled and visaversa.
We are on:
Front 4.3.1
Back: 4.3.1
Cleared the Tenant cache.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
