### ISSUE TITLE
Tenant Access Check Exchange Error

### ISSUE THREAD

**Issue by mr-macedawg** [KelvinTegelaar/CIPP#178]
**Describe the bug**
When running the Tenant Access Checker the following error appears when testing Exchange.

> Failed to connect to Exchange: AADSTS9002313: Invalid request. Request is malformed or invalid. Trace ID: f8eaa7cf-6e0a-48bb-9916-12bc4af21600 Correlation ID: b11ebb73-2ada-4d1a-902e-953712ae2355 Timestamp: 2021-11-03 11:04:56Z

**To Reproduce**
1. Go to Configuration Settings
2. Select a Tenant under Tenant Access Checker
3. Click Run access check

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version: 95.0.4638.69 

**Additional context**
CIPP Version 1.2.1
CIPP API Version 1.2.3

**Comment by KelvinTegelaar** [comment]
Not a bug, you either entered an incorrect ExchangeRefreshToken, or left it empty.
