### ISSUE TITLE
[Feature Request]: Tenant ID in Alerts

### ISSUE THREAD

**Issue by Yoshify** [KelvinTegelaar/CIPP#1780]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

FR sponsored by our team, @HealthITAU

We have a custom made app listening to webhook alerts - when we receive alerts I see a Tenant field in the alert with the tenants primary domain. Is it possible we can get the Tenant ID as well?

Reasoning for this is that we have a data mapping solution in place that maps ConnectWise Manage company ID's to their matching Tenant ID's for working with integrations. By having a Tenant ID provided in an alert, we can match it back to a company in Manage and create a ticket specifically for that company.

**Comment by KelvinTegelaar** [comment]
While I understand and respect the need, we won't make changes to ease the integration with non-sponsoring vendors, if you'd like this change the vendor that you want the changes for would need to sponsor the application. Contact and ask your vendors about this. :)
