### ISSUE TITLE
Permissions check - update information for ActivityFeed.Read - Delegated

### ISSUE THREAD

**Issue by Absoblogginlutely** [KelvinTegelaar/CIPP#1782]
### Description

Running permissions check, I was receiving ActivityFeed.Read - Delegated as missing. 
The description for this should be ActivityFeed.Read - Delegated (Office 365 Management) as this is not part of the Graph API.
![image](https://github.com/KelvinTegelaar/CIPP/assets/21364480/fa7aef6b-826b-43d8-a175-754e38d616c7)

Added permissions manually, and issue is fixed. 
Seems to be a slight gui change required for the description of this permission.
Searched the repo's but couldn't find reference to where this information is kept.

### Environment data

```PowerShell
Non-sponsored instance 
Front end version number: 4.3.1
Back end version number: 4.3.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by BNWEIN** [comment]
There is a link to the docs within the error and the docs clearly show (Office 365 Management). You can see this here: 

https://docs.cipp.app/setup/installation/permissions

**Comment by CallumAlbert** [comment]
Although it is in the docs I do think it might be better if it just said it on the permissions check. I was playing around with this last night and have something which works.

**Comment by CallumAlbert** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
fixed in dev.
