### ISSUE TITLE
"Set Technical Contact e-mail"  Standard and others...

### ISSUE THREAD

**Issue by akraker99** [KelvinTegelaar/CIPP#1784]
### Description

I have tried setting the Technical Contact e-mail in the individual standards section but it does not appear to be taking effect.  I have tried at the All Tenants level and at individual tenant levels.  I have also tried pushing the standards and waiting several hours for the normal 3 hour interval push.
All Permission checks come back good.  I can verify that the address has not changed both by looking at the Org Contact settings in the GUI and by using Get-MsolCompanyInformation | FL DisplayName, TechnicalNotificationEmails
Unless this is setting a different address?

Along these lines, I am unsure about what the other setttings in CIPP are supposed to set (Security, Marketing and General).  The only other contact available to change with Set-MsolCompanyInformation according to Microsoft is the Marketing Contact
https://learn.microsoft.com/en-us/powershell/module/msonline/set-msolcompanycontactinformation?view=azureadps-1.0

### Environment data

```PowerShell
Non-sponsored instance 
Front end version number: 4.3.1
Back end version number: 4.3.1  (API Version)
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Not a bug, support question.  as a sponsor you can get support.
