### ISSUE TITLE
GDAP Wizard failing

### ISSUE THREAD

**Issue by bandicootlimited** [KelvinTegelaar/CIPP#1786]
### Description

We have followed the various prep steps for the GDAP migration wizard and run through for two clients.

The first now shows no missing GDAP roles, but still won't connect to Exchange to provide information on mailboxes etc. In CIPP settings Tenant Access Check I get "Failed to connect to Exchange: Response status code does n".

On second client again I cannot access mailboxes etc but in CIPP settings Tenant Access Check I get "Failed to connect to Exchange: Insufficient privileges to co".

In both cases in GDAP Migration List I get Status Migration Complete.

### Environment data

```PowerShell
Sponsored hosted environment
Tried Tenant Cache Clear: true
Frontend Version Latest: 4.3.1 Current: 4.3.1
API Version Latest: 4.3.1 Current: 4.3.1
Permissions Check Your refresh token matches key vault. Your access token contains the MFA claim.Your Secure Application Model has all required permissions
```

**Comment by rvdwegen** [comment]
Do a CPV refresh in Settings > Tenants

**Comment by bandicootlimited** [comment]
CPV Refresh worked thanks
