### ISSUE TITLE
Halo Webhooks for Alerts not working

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1788]
### Description

Halo Webhooks for CIPP > Settings > Notifications are working fine

Halo Webhooks for Alert Policies are not. Error 400 as previously discussed in Discord. 

### Environment data

```PowerShell
Back end and front end: 4.3.1
Tenant cache not relevant.
Token cache also not relevant.
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Resolved in dev. Waiting for confirmation.

**Comment by KelvinTegelaar** [comment]
considering fixed
