### ISSUE TITLE
[Feature Request]: Standards - Enable Microsoft OTP in Auth methods

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#1789]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Many of our customers are using the MS NPS extension for VPN authendication and after number matching has become mandatory, now rely on the OTP code from the Authendicator app instead of getting a push notification. The current CIPP standard "[Enable Passwordless with Location information and Number Matching](https://github.com/KelvinTegelaar/CIPP-API/blob/dev/Standards_PWdisplayAppInformationRequiredState/run.ps1)" changes this to Disabled everytime standards run.

Having a dropdown to chose if it should be enabled or disabled like with "[Set Authenticator Lite state](https://github.com/KelvinTegelaar/CIPP-API/blob/dev/Standards_PWcompanionAppAllowedState/run.ps1)" would be nice. 
Default set to "No" for backwards compatability.

Since the feature is locked behind registering the Authendicator app and this is just an add-on, it should not decrease security. At least to my knowledge.

### PowerShell commands you would normally use to achieve above request

This is your own code, only part modified is: "isSoftwareOathEnabled" being set to true instead of false

```
try {
    $body = @"
{"@odata.type":"#microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration","id":"MicrosoftAuthenticator","includeTargets":[{"id":"all_users","isRegistrationRequired":false,"targetType":"group","authenticationMode":"any"}],"excludeTargets":[],"state":"enabled","isSoftwareOathEnabled":true,"featureSettings":{"displayLocationInformationRequiredState":{"state":"enabled","includeTarget":{"id":"all_users","targetType":"group","displayName":"All users"}},"displayAppInformationRequiredState":{"state":"enabled","includeTarget":{"id":"all_users","targetType":"group","displayName":"All users"}},"companionAppAllowedState":{"state":"default","includeTarget":{"id":"all_users","targetType":"group","displayName":"All users"}}}}
"@
    (New-GraphPostRequest -tenantid $tenant -Uri "https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/microsoftAuthenticator" -Type patch -Body $body -ContentType "application/json")

    Write-LogMessage  -API "Standards" -tenant $tenant -message "Enabled passwordless with Information and Number Matching." -sev Info
}
catch {
    Write-LogMessage  -API "Standards" -tenant $tenant -message "Failed to enable passwordless with Information and Number Matching. Error: $($_.exception.message)" -sev "Error"
}
```

**Comment by KelvinTegelaar** [comment]
only sponsors can crate FRs,

**Comment by kris6673** [comment]
I'm now a sponsor :)

**Comment by KelvinTegelaar** [comment]
Added in dev; we no longer send that in the patch at all, so users can decide themselves if to enable/not.

**Comment by kris6673** [comment]
> Added in dev; we no longer send that in the patch at all, so users can decide themselves if to enable/not.

Awesome thanks!
