### ISSUE TITLE
M365 Portal - Error

### ISSUE THREAD

**Issue by kayvanaarssen** [KelvinTegelaar/CIPP#18]
When we click on the M365 portal link we get an error.
Is this because of some rights in the Secure App? Or Something different.

The Exchange Portal Works same for other portals.

![image](https://user-images.githubusercontent.com/672841/137470133-c0dca63f-53a5-4c5c-a2cf-29b839a9ae1f.png)

![image](https://user-images.githubusercontent.com/672841/137470076-faa2feb6-b8b4-4714-abad-55b4d0c3cca4.png)

**Comment by KelvinTegelaar** [comment]
I can't replicate this, can you make sure you fill out the complete bug report? It helps in finding the exact cause, currently I'm guessing(wild guess really) that this is a browser issue or maybe you're not logged in under your partner credentials? Wild guesses of course. :)
