### ISSUE TITLE
Best Practice Analyser sorting not working correctly

### ISSUE THREAD

**Issue by stienjo1993** [KelvinTegelaar/CIPP#1803]
### Description

When you sort on current secure score in the Best Practice Analyser and set rows per page on 500, its not sorting correctly.
See picture.
![sorting](https://github.com/KelvinTegelaar/CIPP/assets/129944407/e8ddddf5-fda4-4150-8110-b5884ba84b7c)

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 4.4.0
Back end version number: 4.4.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by stienjo1993** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
