### ISSUE TITLE
Most firewall rulesets exceed the 64 KB max size limit for Azure Table Storage

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1806]
### Description

When trying to create a template from a Firewall Ruleset, if there are more than 3 - 4 rules in the set, it results in the following error:

`
Intune Template Deployment failed: The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less. RequestId:2e8148cf-6002-0012-1351-feb161000000 Time:2023-10-14T03:47:04.1477813Z Status: 400 (Bad Request) ErrorCode: PropertyValueTooLarge Content: {"odata.error":{"code":"PropertyValueTooLarge","message":{"lang":"en-US","value":"The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less.\nRequestId:2e8148cf-6002-0012-1351-feb161000000\nTime:2023-10-14T03:47:04.1477813Z"}}} Headers: X-Content-Type-Options: REDACTED Cache-Control: no-cache DataServiceVersion: 3.0; Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
`

As discussed with @johnduprey, it might be prudent to move templates into Azure Blob Storage.

As of right now, we can't template firewall rulesets without splitting them up - I suspect the same issue will occur with any sufficiently large settings policies.

### Environment data

```PowerShell
Frontend: 4.4.0
API: 4.4.3
Sponsored (self-hosted)
Tenant Cache Clear: true
Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Already known and on roadmap :)
