### ISSUE TITLE
Account Duplication Problem in Gradient MSP Integration

### ISSUE THREAD

**Issue by gradientbryan** [KelvinTegelaar/CIPP#1808]
### Description

Accounts are duplicating because there's no unique identifier for them.

Problem with Synthesize integration during account creation. Accounts are getting duplicated because the description is being used as the "ID," and the description contains the domains of the M365 tenant. Since it's common to have multiple domains for a tenant, we end up with duplicate companies being created. 

We need to identify an alternative unique identifier source to avoid creating multiple accounts and ensure that usage is synced correctly for each tenant.

Example, we are returning duplicate accounts in Synthesize, and the "ID" appears to be the description or domain:

Account 1:

Name: "ABC Corporation"
Description: "[abccsrporation.onmicrosoft.com](http://abccsrporation.onmicrosoft.com/)"
Account 2:

Name: "ABC Corporation"
Description: "[abccorporation.com](http://abccorporation.com/)"

We need to identify an alternative unique identifier source to prevent such duplicates and ensure accurate usage syncing for each tenant.

### Environment data

```PowerShell
Sponsored instance
```

**Comment by KelvinTegelaar** [comment]
Looking into this without breaking existing integrations. Normally the defaultDomainName does not change as it's only retrieved once. The user that reported this changed the partner center connection too so we'll have to find a nice way to handle that. :)

**Comment by gradientbryan** [comment]
Good to know! I figured there was a fringe case here, but it's good to know you're using the defaultDomainName as your identifier here.

**Comment by KelvinTegelaar** [comment]
Resolved in dev
