### ISSUE TITLE
[Feature Request]: Add the ability to exclude tenants from "AllTenants" standards

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1810]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Rather than have to add a standard to each individual customer, it would be good if we could use "AllTenants" but have an exclusion from it. We have an "AllTenants" Standard and we have just one customer we do not want to include in that standard. Right now this would require us to disable the "AllTenants" standard, and apply a standard to every other customer individually, which is much harder to manage than having an exclusion list.

**Comment by KelvinTegelaar** [comment]
prework done, planned.

**Comment by KelvinTegelaar** [comment]
Added in dev
