### ISSUE TITLE
[Feature Request]: New Standard for Require MFA to register or join devices with Microsoft Entra

### ISSUE THREAD

**Issue by STG-Tanner** [KelvinTegelaar/CIPP#1816]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would like to set a standard to flip the Entra device setting: "Require Multifactor Authentication to register or join devices with Microsoft Entra"

This is a useful security standard to have for tenants without Conditional Access.

### PowerShell commands you would normally use to achieve above request

Set-MsolDeviceRegistrationServicePolicy -RequireMultiFactorAuth $True

**Comment by KelvinTegelaar** [comment]
Added in dev.
