### ISSUE TITLE
[Feature Request]: Tenants Groups 

### ISSUE THREAD

**Issue by hansendennis** [KelvinTegelaar/CIPP#1826]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have tenants that are under management and some there arent. 
Therefore we would like to be able to add tenants into Groups and be able to deploy Tenant Standards based on memberships.

**Comment by KelvinTegelaar** [comment]
Currently only sponsors can create Frs, this is also a duplicate.

**Comment by hansendennis** [comment]
I would like to upgrade the priority

**Comment by hansendennis** [comment]
and how do I get a sponsor?

**Comment by rvdwegen** [comment]
https://github.com/sponsors/KelvinTegelaar/sponsorships?sponsor=KelvinTegelaar&tier_id=101398&preview=false
