### ISSUE TITLE
Best Practice Analyser / Report

### ISSUE THREAD

**Issue by hansendennis** [KelvinTegelaar/CIPP#1827]
### Description

We have tenants that are excluded under Application Settings --> Tenants but under Best Practice Report/analyser are these tenants visible so we are getting alot of errors on tenants that we dont have access to.

### Environment data

```PowerShell
Sponsored Front end version number: 
Latest: 4.4.0
Current: 4.4.0

Back end version number: 
Latest: 4.4.5
Current: 4.4.5

Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
BPA filters out excluded tenants in dev
