### ISSUE TITLE
BUG - The version of CIPP-API you are running is out of date. Your version is 1.2.0 and the latest version is 1.2.3. Please Update your CIPP-API Repository.

### ISSUE THREAD

**Issue by karnophage** [KelvinTegelaar/CIPP#183]
GIT master for API says 1.2.0 is the latest, but CIPP itself says 1.2.3.

**Comment by karnophage** [comment]
Think I've fixed this myself by pulling the dev branch down, but yeah I don't think this should be occurring on stable.

**Comment by karnophage** [comment]
Nope, pulling that branch and restarting the Azure app didn't help.

**Comment by KelvinTegelaar** [comment]
CIP API is currently at 1.2.3. Are you sure you've executed the update correctly? The updating documentation is located here https://github.com/KelvinTegelaar/CIPP/blob/dev/Documentation/Updating.md

**Comment by karnophage** [comment]
Definitely missed the "sync" on the function. Thanks!

**Comment by KelvinTegelaar** [comment]
Awesome, thanks for reporting anyway!
