### ISSUE TITLE
[Feature Request]: Set Outbound Mail Limit

### ISSUE THREAD

**Issue by MattDunn12** [KelvinTegelaar/CIPP#1839]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Ability to set an outbound mail limit on messages sent out in a day / hour etc. In the event that an account maybe compromised and spam sent out of an account, want to minimise the amount of people it could be sent to, so implementing sending limits could mean it only goes to 100 people rather than a 1000.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create Feature Requests
