### ISSUE TITLE
[Feature Request]: Standard: Configure default Timezone for new SharePoint sites

### ISSUE THREAD

**Issue by MattDunn12** [KelvinTegelaar/CIPP#1841]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Tends to default to US TimeZones, having a Standard to apply so that all new SharePoint sites default to time zone "allow to chose from list" means any new SharePoint sites created are correct.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create Feature Requests
