### ISSUE TITLE
[Feature Request]: Standards - Enable preset Defender for Office 365 policy

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#1848]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would be good being able to enable the either the standard or strict preset Defender for Office 365 policy as a Standard.
This would be a quick way to be sure that customers are at least getting a base level of protection, without the need for any technicians to remember to enable the spam filter.

### PowerShell commands you would normally use to achieve above request

Enable-EOPProtectionPolicyRule -Identity "Standard Preset Security Policy"; Enable-ATPProtectionPolicyRule -Identity "Standard Preset Security Policy" -ErrorAction Continue

**Comment by kris6673** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
Don't these policies require a first manual setup before they become available? I think on tenants without these commands will just fail.

**Comment by kris6673** [comment]
I think you're right, all my tests must have been done on tenants where it had been enabled before. However I think we can do it manually too, according to [this](https://learn.microsoft.com/en-us/powershell/module/exchange/new-atpprotectionpolicyrule?view=exchange-ps) article
