### ISSUE TITLE
[Feature Request]: Scheduler: Auto add / remove user from AAD Group

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#1850]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

*Copiedfrom Discord*

Hey guys - I realize this is somewhat outside the scope of CIPP but I think it could be an amazing idea.

Right now, we have users who travel outside the country.

Every time they do this we have to exclude them from the Geo Filter (and then remember to add them back again when they return).

My thinking of a simple way to address this would be to automatically remove the user from a specified group after a set period of time.

I there is now a task scheduler so it seems like CIPP already has some scheduling capabilities built in.

If we could trigger an operation to auto add / remove a user from a group, it would solve this problem and probably a few more.

To clarify, here's our current workflow:

1. We exclude a single AAD / Entra group from the Geo Filter "Bypass Geo Filter"
2. Add the user's to the group when they travel
3. Remove them from the group when they return

I think scheduling adding / removing from groups could solve this problem and many more.

Thanks for your consideration!

### PowerShell commands you would normally use to achieve above request

```
# Fetch the user
$user = Get-AzureADUser -Filter "DisplayName eq 'John Doe'"

# Add user to the group
Add-AzureADGroupMember -ObjectId $group.ObjectId -RefObjectId $user.ObjectId

# Remove user from the group
Remove-AzureADGroupMember -ObjectId $group.ObjectId -MemberId $user.ObjectId
```

**Comment by KelvinTegelaar** [comment]
Already roadmapped! :) coming soon
