### ISSUE TITLE
FEATURE REQUEST: Offboarding user OneDrive Data

### ISSUE THREAD

**Issue by craigsummers88** [KelvinTegelaar/CIPP#1854]
It would be good to be able to move all OneDrive data to a specific SharePoint folder before converting the user to a Shared Mailbox and then if requested providing someone access to that folder

**Comment by KelvinTegelaar** [comment]
Incomplete, and only sponsors can  create frs.

**Comment by craigsummers88** [comment]
> Incomplete, and only sponsors can create frs.

Ah sorry, what am I missing to make it complete? I am a sponsor, I just realised I submitted this under my personal GitHub and not my work one. Does it need to be the github that setup the sponsor, or can it be any github that is of the same domain?
