### ISSUE TITLE
[Feature Request]: automate a monthly report for all licensed M365 users

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#1856]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Individual reports per tenant that email in to us that shows Username, Email, Active\Inactive, Assigned Licenses.

You can already manually generate this report via CIPP, but doesn't look like there is a currently a way to automate this process. 

I have tried to get the user information via the schedular and via CIPP API /ListUsers, but provides the assigned licensee SKU instead of the actual licensee name.  

Would you be able to add this as a report to the schedular?

**Comment by KelvinTegelaar** [comment]
everything in the API will always return the internal name, the frontend does the translation.

**Comment by Novem-MSP** [comment]
Would you be able to add a schedule to download the users with licensee name correct in the scheduler?

**Comment by KelvinTegelaar** [comment]
No, there is nothing in the backend to handle that translation. This isn't something we can accomdate.
