### ISSUE TITLE
[Feature Request]: Tenant Groups

### ISSUE THREAD

**Issue by JohnV-SCC** [KelvinTegelaar/CIPP#1857]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I KNOW this is not the first time this has been requested, but it is the first time I believe someone from a CIPP sponsor has :)

CIPP **needs** Tenant Groups! Like many other MSP's, we have different service tiers for our clients and so we would love a way to group our clients' tenants based on these service tiers. This would allow us to mass deploy certain conditional access policy sets and standards for our fully managed clients, while deploying other policies and standards for our lower tier clients. 

From a UX perspective, I guess "Groups" could get squeezed in under Tenants under the Tenant Administration > Administration sub-menu.

![cipp tenant admin](https://github.com/KelvinTegelaar/CIPP/assets/150265380/7ad542ec-818c-43e1-9c73-05dba1b0c9c8)

Creating the group could be a simple "Name" text box with a checklist showing all tenants in order to select which tenants should be added to the group. Maybe at some point down the line there can be an advanced/dynamic group creation menu that can auto-add or remove tenants based on certain attributes (licensing, PSA integration syncing with contracts, etc.).

Once the group is created, it will show up as an option in the "Standards Wizard" and "Deploy Conditional Access" menus, much like how *All Tenants functions today

**Comment by JohnV-SCC** [comment]
I would like to upgrade the priority

**Comment by JohnV-SCC** [comment]
> I would like to upgrade the priority

**Sponsored via our organization page, Suffolk Computer Consultants

**Comment by perrytrienekens** [comment]
+1 from other Sponsor :)
