### ISSUE TITLE
[Feature Request]: Hide Lighthouse search

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1865]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

If you don't have lighthouse, there is no reason for it to be there. 

A toggle to hide / show would be nice.

**Comment by KelvinTegelaar** [comment]
We're considering making the lighthouse license mandatory, closing this as we wont make effort for it.
