### ISSUE TITLE
Scheduled Tasks Webhook results to Halo Fail to send

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1868]
### Description

We have set our scheduler to send Webhooks to Halo upon the scheduling running, but its failing to send them with the below error: 

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/d2f57e8c-5a31-4622-baf9-405777227c15)

A test of our Halo Connection in CIPP returns fine

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/322a297e-bef7-44cf-aaef-110a86f5bc2c)

The expected result is a webhook sent to Halo, and no errors in the event log.

To recreate the issue:
Setup a scheduled event task
(We set the subject as "Hide from GAL [ID:4553]", but i dont think this is important, but could be!)
Set alert to send Email and Send Webhook

When the task runs, we get the email, but we get an error in the logbook that it cannot send the webhook. As per image above. 

### Environment data

```PowerShell
4.5 Self Hosted.
```

**Comment by KelvinTegelaar** [comment]
set the ticket type correctly?

**Comment by BNWEIN** [comment]
Jeez you dont mess around! :)

I left it at default which should set them as "alerts" i believe?

**Comment by BNWEIN** [comment]
For full clarity and as mentioned in Discord

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/b4b19553-5af0-444d-9426-4b67a13e0566)

We do have a special character in the name of the schedule. Unsure if this is related

I believe other alerts from CIPP to Halo are working fine. So just an issue with the scheduler ones. I will confirm this within the next 24 hours as we get other CIPP alerts.

**Comment by BNWEIN** [comment]
Have now confirmed other alerts from CIPP Notifications are coming through as a webhook fine to Halo. 

Have also set the Alert ID just to confirm if that makes any difference but it does not.

**Comment by KelvinTegelaar** [comment]
Please fill in all data in your bug report(we need to set the right example).

**Comment by KelvinTegelaar** [comment]
Please enabled debug logging in your instance and test the function. If you need more help contact the helpdesk to enable your debug logs.

**Comment by BNWEIN** [comment]
Keeping the ticket up to date, I have monitored the ExecScheduledCommand using my function app, and it shows the below, which is basically the same as the log its self

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/c4679a71-5238-4742-aa5c-395d53adaa15)

I have now emailed the helpdesk to find out how to enable additional debugging logs.

**Comment by KelvinTegelaar** [comment]
So Ben, please share with the group what the issue was.

**Comment by Jr7468** [comment]
Also interested to know the issue here

**Comment by rvdwegen** [comment]
Yes, very interested too!

**Comment by BNWEIN** [comment]
The solution here was very technical, and complicated. I dont want to get too much into the full technical details behind the solution, but for anyone else having a similar issue, it does help if you select the correct option before wasting Kelvin's time! 

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/42002ee9-61a4-43ce-aacf-2b25deea4fc2)
