### ISSUE TITLE
[Feature Request]: Add OWA link within mailbox permissions screen

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#1873]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Just a suggestion - hoping others might see value in this.

When an employee leaves and we convert to a shared mailbox etc, we often give their manager permissions to their mailbox without automapping.

Would it be possible to get a link to https://outlook.office.com/mail/user@company.com/ added to the mailbox permissions screen, maybe under "Account Information - user@company.com" or within the "User information" under Email & exchange > admin > 3 dots.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs, also don't see much use in this.
