### ISSUE TITLE
[Feature Request]: Schedule performing Offboarding Wizard

### ISSUE THREAD

**Issue by cmcclend** [KelvinTegelaar/CIPP#1877]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be a great feature to be able to schedule the tasks performed in the Offboarding Wizard so that it will execute the request at a predetermined time.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs./
