### ISSUE TITLE
[Feature Request]: Add ability to upload MSI files

### ISSUE THREAD

**Issue by ShiftITCorp** [KelvinTegelaar/CIPP#1883]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have various applications that are still installed via MSI and are not in Choco or winget. We would like the ability to keep these in CIPP in a sort of custom application section, sort of like the other template sections, and then push them to customers as needed. I know that the moving of the data itself would be an issue, and so I propose that MSP's be required to host the file externally, say in an Azure storage container, and then put the URL of the MSI file into CIPP. When deploying, CIPP could use this external URL as the source of the MSI which would then be streamed into Intune.

I've used this script before: https://github.com/microsoftgraph/powershell-intune-samples/blob/master/LOB_Application/readme.md
It works for local files, but I haven't tried using it to upload files stored from a cloud URL.

**Comment by ShiftITCorp** [comment]
I would like to upgrade the priority

**Comment by KelvinTegelaar** [comment]
There is something else planned for this on our roadmap, for now we're closing this FR but something like this is incoming.

**Comment by ShiftITCorp** [comment]
Thanks!
