### ISSUE TITLE
[Feature Request]: New Tenant On-Boarding Wizard

### ISSUE THREAD

**Issue by SplitLogic** [KelvinTegelaar/CIPP#1884]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I did everything in the wrong order when on-boarding a tenant and took. I had to waste the time of people in the discord to get it done in the correct order. 

A simple wizard in CIPP that takes you through step by step, Adding the tenant with the partner centre before adding the gdap relationship in CIPP, ensures you have the right groups setup for the tenant etc. I think this would help a lot of people simply add new tenants and reduce some of the support requests in the discord.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
