### ISSUE TITLE
[Feature Request]: Schedule Exchange Alias Addition and Removal

### ISSUE THREAD

**Issue by alexxdavid** [KelvinTegelaar/CIPP#1899]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have been receiving requests recently to have aliases added to mailboxes but for a specific amount of time.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs

**Comment by alexxdavid** [comment]
Apologies, thought it was general feature requests 😱
