### ISSUE TITLE
Remove Mobile Device Scheduled tasks has an empty output

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1904]
### Description

Create a scheduled task for remove mobile devices, wait for the task to run, and the results that it will return are empty

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/c74be5e1-abcd-4fd0-bf79-d62e225d2405)

### Environment data

```PowerShell
Self Hosted
Clearing tenant cache is not relevant
Frontend version: 4.6.0
backend version: 4.6.1
```

**Comment by BNWEIN** [comment]
@Jr7468 can you try and look at this whilst also making a change to the Out of Office function so the output is no longer an array

Thanks!

**Comment by KelvinTegelaar** [comment]
Fixed in dev
