### ISSUE TITLE
[Feature Request]: Custom Email address for scheduled task results

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#1912]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The ability already exists in CIPP to email scheduled task results. This uses the same email address which is setup for all CIPP Notifications. 

We would like scheduled task email notifications to go to a different mailbox than our standard CIPP Notifications. This is so we can process them differently than we process standard CIPP notifications.

Having the ability to customise this for the scheduler function would be useful to other MSP's who also want to process scheduled task results differently to how they schedule other CIPP notifications.

**Comment by KelvinTegelaar** [comment]
No, this would require an entire rewrite of the notification system to do right, so we're not considering this at this time.
