### ISSUE TITLE
[Feature Request]: Standards - Autopilot Profiles and Status Pages

### ISSUE THREAD

**Issue by MWGMorningwood** [KelvinTegelaar/CIPP#1913]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I want to be able to add a standardized Autopilot Profile and Status Page to our "All Tenants" standard.
During the SIP & CIPP, Kelvin pointed out that you can already deploy one to all tenants once, but this wouldn't ensure that newly created/associated tenants receive these by default.

This may make more sense to implement _after_ the ability to manage MAM/MDM enable/disable is added.
The end goal would be to have Standards account for the entire Intune/Autopilot setup for a tenant (using policy template functionality like Intune Configuration profiles), automating essentially the whole process.

### PowerShell commands you would normally use to achieve above request

I would usually do this through CIPP! This request is just adding an existing feature to another.

**Comment by KelvinTegelaar** [comment]
Planned.
