### ISSUE TITLE
[Feature Request]: Configure ability to create notifications on Temporary Access Password usage through CIPP

### ISSUE THREAD

**Issue by cbaumhart** [KelvinTegelaar/CIPP#1914]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As discussed in the 11/27 SIP & CIPP, Cyberdrain has an internal configuration which sends out a notification email to users when a Temporary Access Password is created through CIPP. Can that notification be configurable through CIPP?

**Comment by KelvinTegelaar** [comment]
added in dev
