### ISSUE TITLE
[Feature Request]: Add Option to Export Visible Columns or All Columns for CSV Export

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#1915]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Many data tables in CIPP have a lot of columns that are hidden by default and aren't needed for day-to-day CIPP usage. However there are cases where dumping all available data within a table to CSV could be useful. This includes auditing, scripting, migration preparation, and much more.

Currently to achieve this, you would need to enable visibility of all columns, one-by-one, run the CSV export, then re-hide any columns not needed for day-to-day use within CIPP.

My suggestion is to have a dropdown on the CSV export button which would allow the option to export only visible columns or export all columns in the CSV.

**Comment by KelvinTegelaar** [comment]
Added in dev.
