### ISSUE TITLE
ENHANCEMENT: Move JSON Standards to a Subfolder in CIPP-API

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#192]
**Is your feature request related to a problem? Please describe.**
Having them in the root is messy - they need to be in a sub directory. It also makes .gitignore easier to deal with

**Describe the solution you'd like**
All generated standards move to a sub folder

**Comment by lwhitelock** [comment]
We should also move logs and the tenant cache while we are at it.

**Comment by KelvinTegelaar** [comment]
All moved except tenantcache and excludedtenants
