### ISSUE TITLE
[Feature Request]: Multi-Select for Forward Email to Another User in Offboarding Wizard

### ISSUE THREAD

**Issue by JRivett-ITSG** [KelvinTegelaar/CIPP#1929]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Previously requested allowing multiple automapping for full access to mailbox and One Drive, also would like it in "forward email to other user".

Contributor status is on https://github.com/ITSupportGuys, not this account, I cannot submit requests as the org.

This would make all offboardings faster, as we wouldn't have to manually make the transport rule.

We could use a transport rule to do this, as it looks like you only have the option to forward to a single recipient when using forwarding at the user level.  Maybe we could add a switch to forward as a transport rule.

### PowerShell commands you would normally use to achieve above request

New-TransportRule -name TestPwshForward -RecipientAddressMatchesPatterns email@email.com -BlindCopyTo address1,address2

**Comment by KelvinTegelaar** [comment]
Planned.

**Comment by KelvinTegelaar** [comment]
You can only set one address as a forwarding address in exchange, however we now show the option to forward to mailing lists/dls as well.

**Comment by JRivett-ITSG** [comment]
> You can only set one address as a forwarding address in exchange, however we now show the option to forward to mailing lists/dls as well.

Right which is why I suggested a switch to convert the forwarding within CIPP to a transport rule forward.  Something like this:
New-TransportRule -name TestPwshForward -RecipientAddressMatchesPatterns email@email.com -BlindCopyTo address1,address2
