### ISSUE TITLE
[Feature Request]: Offboarding user OneDrive Data

### ISSUE THREAD

**Issue by bonlewy** [KelvinTegelaar/CIPP#1930]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be good to be able to move all OneDrive data to a specific SharePoint folder before converting the user to a Shared Mailbox and then if requested providing someone access to that folder.
This would be useful as 95% of our client's users utilise OneDrive and we would want to archive this off to convert the user to a shared mailbox and release the licence for customer cost savings. 

### PowerShell commands you would normally use to achieve above request

We havent done this through powershell before only through the GUI. It would involve going to a sharepoint site such as Leavers, creating a new folder with the leavers display name and then moving/copying the OneDrive contents to this location

**Comment by KelvinTegelaar** [comment]
Not possible, no apis. Sorry
