### ISSUE TITLE
[Feature Request]: Mail quarantine default settings and notification.

### ISSUE THREAD

**Issue by CIPP-SGNG** [KelvinTegelaar/CIPP#1933]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

A way to enable default quarantine behaviour for all accounts in a tenant, for example create a new quarantine policy where you can select if user is notified and if an admin or user can release mail from quarantine.
Change the default anti spam policy to use the new quarantine policy when for example the mail is high phish or high spam.
Most importantly update the users who get a notification about a release request, this should then be set for an MSP mail in most cases.
I noticed when creating a new ProtectionAlert it gives back an error if the tenant doesn't own an E5 license.
I haven't found another way of changing who gets the mail notification, maybe there is way around this?

This would greatly improve customers handling of "lost mail", and you can get all of the quarantine notifications to a single mail address.

### PowerShell commands you would normally use to achieve above request

```
Connect-ExchangeOnline -DelegatedOrganization $CustomerDomain

Enable-OrganizationCustomization -Confirm:$false

New-QuarantinePolicy -Name POLICYNAME -EndUserQuarantinePermissionsValue 27 -ESNEnabled $true

Set-HostedContentFilterPolicy -Identity Default -HighConfidencePhishAction Quarantine -HighConfidencePhishQuarantineTag POLICYNAME -HighConfidenceSpamAction Quarantine -HighConfidenceSpamQuarantineTag POLICYNAME 



Connect-IPPSSession -UserPrincipalName 'ADDRESS' -DelegatedOrganization $CustomerDomain -AzureADAuthorizationEndpointUri 'https://login.microsoftonline.com/common'

New-ProtectionAlert -Name "Quarantine Release Request Alert" -Category Mailflow -ThreatType Activity -Operation QuarantineReleaseRequest -Severity Medium -NotifyUser MSP@MAIL.COM  -AggregationType None  -Description "Quarantine Release Requested"
```

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
