### ISSUE TITLE
FEATURE REQUEST: Allow "Block Sign In" from "Shared Mailbox with Enabled Account" report results

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#1938]
The "Shared Mailbox with Enabled Account" report shows shared mailboxes with login capabilities and the "Administration > Users" interface allows the "Block Sign In" function to be executed for those shared mailboxes. Why not put that action directly on the report results as well?

Thanks for considering!

**Comment by KelvinTegelaar** [comment]
added in dev.
