### ISSUE TITLE
BUG:  Block Device Usage During Setup

### ISSUE THREAD

**Issue by Da180DegreesIT** [KelvinTegelaar/CIPP#1948]
Looks to be a bit of a bug but when setting up status pages "Block Device Usage During Setup" seems to do the opposite effect.

Enabled = Off on InTune
Disabled = Block on InTune

Done this multiple times now and same effect. 

Added a couple screenshots for you to view, and see the "Custom error" message i set.

Nothing major. Just a tiny bug.

![Screenshot_70](https://github.com/KelvinTegelaar/CIPP/assets/87954396/2ec1c644-1369-4b61-81dc-fc132b4ee668)
![Screenshot_69](https://github.com/KelvinTegelaar/CIPP/assets/87954396/8d97b916-e2e8-4fee-86f7-4858b68cb986)
![Screenshot_68](https://github.com/KelvinTegelaar/CIPP/assets/87954396/e86efa78-bdbf-4d93-af53-93bb60c24ec5)
![Screenshot_67](https://github.com/KelvinTegelaar/CIPP/assets/87954396/611ebc71-c0f6-4ec0-a55b-0f25739d18d2)

**Comment by KelvinTegelaar** [comment]
Absolutely right, I seem to have flipped these. Fixed in dev. :)
