### ISSUE TITLE
HaloPSA Ke

### ISSUE THREAD

**Issue by stefano5885** [KelvinTegelaar/CIPP#1951]
### Description

1) go to Application Settings, Extensions
2) Fill all data in "Halo PSA Ticketing Integration" (except HaloPSA Ticket Type ID)
Resource server: https://enneuno.halopsa.com/api
Authorisation server: https://enneuno.halopsa.com/auth
Tenant: enneuno
ClientID: hidden
Secret: hidden

3) Click "Set extension settings"

Failed to set configuration: The property 'APIKey' cannot be found on this object. Verify that the property exists and can be set. Linenumber: 46

4) Tested all parameters above with "Enable integration set to TRUE"

![image](https://github.com/KelvinTegelaar/CIPP/assets/7619692/6f98e9fc-40d8-480d-902a-4f28d219ab0f)

### Environment data

```PowerShell
Non-sponsored instance
Front end version number:4.8.0
Back end version number:4.8.4
Tried Tenant Cache Clear: true
Tried Token Cache Clear: false
Clear All Caches: true
```

**Comment by stefano5885** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug. Sponsors can contact the helpdesk for support.
