### ISSUE TITLE
[Feature Request]: Ability to create Tenant Contacts 

### ISSUE THREAD

**Issue by NeckbeardThePirate** [KelvinTegelaar/CIPP#1957]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Ability to create and manage contacts in the same way as active users. including adding to/removing from groups etc. We have clients that maintain emailing lists through a Distro and contacts for family of employees/former employees these come up on a regular basis for us and it would be convenient not have to connect to their tenant to create/manage those.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
