### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by CatCodez** [KelvinTegelaar/CIPP#1958]
Hi,

thanks for your great project. Installation was somehow difficult for me, not having a lot expierience with github/azure function automation. But to the topic:

within Documentation / Prerequisites it is not mentioned that you need to add a connection with Azure App Service for your github account upfront, without that, it will fail to deploy with error: "Cannot find SourceControlToken with name GitHub."

Once adding this connection, the next installation attempt will work fine. So please add this also to your prerequisite documentation :)

thanks

**Comment by KelvinTegelaar** [comment]
No need to do that, if you found that to be required it's something you've done in your environment.
