### ISSUE TITLE
[Feature Request]: Manage Tenant Contacts

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#1959]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Management of Tenant Contacts under [IDENTITY MANAGEMENT > Administration > Contacts] -- or some such location.

Many clients use Tenant Contacts, along with Distribution Lists to communicate with internal users and external partners. The [IDENTITY MANAGEMENT > Administration > Groups > edit] page allows adding an existing contact to the group, but nowhere in CIPP is there a way to create or edit existing contacts.

Having the ability to add and edit these contacts will further reduce the need to log into the Microsoft 365 admin center.

Thanks!

### PowerShell commands you would normally use to achieve above request

# To add a new contact.
New-MailContact -Name "Luke Skywalker (Jedi Knight)" -ExternalEmailAddress "master_yoda_taught_me@theforce.com" -DisplayName "Luke Skywalker" -FirstName "Luke" -LastName "Skywalker"
# https://learn.microsoft.com/en-us/powershell/module/exchange/new-mailcontact?view=exchange-ps

# To update existing contact.
Set-MailContact -Identity "Luke Skywalker (Jedi Knight)" -ExternalEmailAddress "who_is_my_daddy@theforce.com"
# https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailcontact?view=exchange-ps

**Comment by JeremyMcM** [comment]
I'm not qualified to work on it I suspect... I've done anything but stand-alone PowerShell. (Where could I learn how to incorporate into a project like this? Is it a "If you have to ask, you can't hope to help" thing?)

Thanks!

**Comment by KelvinTegelaar** [comment]
In the product. Exchange -> Contacts

**Comment by kris6673** [comment]
> In the product. Exchange -> Contacts

Fyi you can only delete and create new, the edit button on the page does nothing
