### ISSUE TITLE
[Feature Request]: Auto fill Display Name

### ISSUE THREAD

**Issue by ocsed** [KelvinTegelaar/CIPP#1962]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

![image](https://github.com/KelvinTegelaar/CIPP/assets/152999404/f5b4790c-ce94-4191-85d1-2c950de2d84f)
When adding a user, it could prove useful to auto-fill the Display Name field just like when creating users in the M365 Admin portal as it is a repetitive task.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs

**Comment by ocsed** [comment]
Hi Kelvin,
Good day.
I’m working for Joe Goldstein as his tech and working on the CIPP deployment and management.
How can I get under his sponsorship to be able to do FR and other applicable functions?

Regards,

Ed Bautista
***@***.***
239.323.2111
https://www.ocsit.com
[OCS IT Logo]

**Comment by KelvinTegelaar** [comment]
Please add FRs under that account or sent a link/have them confirm it :) I've reopened this one now.

**Comment by KelvinTegelaar** [comment]
Added in dev
