### ISSUE TITLE
[Feature Request]: Alert types to have ability to target separate email addresses and or, have the alert subjects start with their types

### ISSUE THREAD

**Issue by morrie-morrie** [KelvinTegelaar/CIPP#1967]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Different parts of our business would like to consume the alerts, and instead of having them all go to everyone, we would like to target say, Storage and Email space running low to go to sales and things like Tokens about to expire going to an engineer's email.

Potentially as an interim step, that each role could have a different subject so that rules can be set in Exchange to move them around ourselves. This could also be used by PSA's with inbound Email capabilities to automatically create tickets.

Andrew Morison, CTO.
Techno Group Australia.

### PowerShell commands you would normally use to achieve above request

None.

**Comment by KelvinTegelaar** [comment]
Only sponsors can creste FRs
