### ISSUE TITLE
Feature Request: Add a user view page

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#197]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to have a single page to view common information on users, that you normally have to visit multiple pages to see.

**Describe the solution you'd like**
I would like a page that is equivalent to the edit page but with many different details on a user

**Describe alternatives you've considered**
Manually visiting multiple M365 Portals.

**Comment by lwhitelock** [comment]
Please assign me.

**Comment by KelvinTegelaar** [comment]
@lwhitelock are we calling the version in dev final for 1.4.0? aka, can this one be closed ? :)

**Comment by lwhitelock** [comment]
We can do. I am working on swapping out the user history table to be a data table. There is also an infinite amount more things we can add. One thing that I want to add is a check for if the user's mailbox is on the blocked list (`Get-BlockedSenderAddress -SenderAddress <emailaddress>`)
But this stuff can wait until 1.5 or the React front end.
The version in Dev works and is useful enough for the moment.

**Comment by lwhitelock** [comment]
It would also be good to get some feedback on what info other people want on the page.

**Comment by KelvinTegelaar** [comment]
Leaving open, markering as done for V1.4.0

**Comment by KelvinTegelaar** [comment]
Added to v1.5.0 for upgrades

**Comment by lwhitelock** [comment]
I am going to close this for now as this work makes more sense just to do as part of the React rewrite
