### ISSUE TITLE
[Feature Request]: Option to view the status of "Self-service Purchase" and the ability to disable or enable

### ISSUE THREAD

**Issue by DigitalN** [KelvinTegelaar/CIPP#1974]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Not sure if it's possible with GDAP now, we're an MSP and our clients have been surprised by Microsoft charges appearing on their credit card statements due to the "Self-service Purchase" option that Microsoft enables by default. This was implemented in CIPP previously, but with the change to GDAP it doesn't seem to be possible to anymore. Can this be fixed so we can adjust this setting across all clients we manage via GDAP too?

It looks like you can disable this function via a PowerShell module: https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide

Here is the previous request:
https://github.com/KelvinTegelaar/CIPP/issues/281

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
