### ISSUE TITLE
Logout doesn't "fully" logout

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#198]
**Describe the bug**
Clicking logout (at least from the home page) just refreshes the home page/dashboard. Refreshing the page or clicking other links then forwards you to the login page.

**To Reproduce**
1. Go to the home page.
2. Click on your "avatar"
3. click logout.

**Expected behavior**
clicking logout should either say it's logged you out or take you to the login page (I guess...)

**Comment by KelvinTegelaar** [comment]
resolved in dev
