### ISSUE TITLE
[Feature Request]: Baseline DKIM Records for 3rd Party spam filters

### ISSUE THREAD

**Issue by sfaxluke** [KelvinTegelaar/CIPP#1983]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When using the Domains Analyser or the individual domain check on a domain that uses a 3rd party spam filter that does not have DKIM specified under the [mail providers](https://github.com/KelvinTegelaar/CIPP-API/tree/eef8ed8adc089c40b52b9b56acd12bf7f61d8a04/Modules/DNSHealth/1.0.6/MailProviders) or uses additional DKIM records then it shows that DKIM is disabled for the domain.

For example we use Barracuda and they do not require any additional DKIM records as they do not edit the message, so the Microsoft Selector1 and Selector2 are the valid DKIM records.

Would it be possible to have an a fallback check that works out DKIM is setup for the Microsoft selectors for a domain and have this as an option for mail providers to set.

An idea for how to manage this would be to add it as an extra variable for the mail providers [config](https://github.com/KelvinTegelaar/CIPP-API/tree/eef8ed8adc089c40b52b9b56acd12bf7f61d8a04/Modules/DNSHealth/1.0.6/MailProviders)

```
{
    "Name": "Barracuda Email Security Service",
    "_MxComment": "https://campus.barracuda.com/product/essentials/doc/86545480/step-2-configure-office-365-for-inbound-and-outbound-mail/",
    "MxMatch": "ess(?<Country>.[a-z]{2})?.barracudanetworks.com",
    "_SpfComment": "https://campus.barracuda.com/product/essentials/doc/73702276/sender-policy-framework-for-outbound-mail",
    "SpfInclude": "spf.ess{0}.barracudanetworks.com",
    "SpfReplace": ["Country"],
    "_DkimComment": "No configuration found",
    "Selectors": [""],
    "UsingMicrosoftDKIM": "True"
}
```

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
