### ISSUE TITLE
Scheduled reports to say when they were generated

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#199]
**Is your feature request related to a problem? Please describe.**
I'm getting a data tables error despite clearing cache and regenerating reports.

I know this is most likely an error here, but, Luke made a good call that it's probably an outdated report causing an error despite the fact I clicked regenerate report.

I'm guessing the report is still being generated and I just clicked too soon.

**Describe the solution you'd like**
I would like to see somewhere (possibly hidden by default) the time/date a report was generated (such as BPA) so it can be seen when needed.

Possibly add extra debug info like execution time for nerdy info.

**Comment by lwhitelock** [comment]
I think we need to update the docs to make it clearer it runs daily at midnight https://github.com/KelvinTegelaar/CIPP/blob/master/Documentation/BestPracticeAnalyser.md

**Comment by KelvinTegelaar** [comment]
see #174
