### ISSUE TITLE
[Feature Request]: Edit Group Membership From UserBlade

### ISSUE THREAD

**Issue by vandergaagR** [KelvinTegelaar/CIPP#1990]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

just like Entra ID- The convenience to edit the Group Membership fromout the User Blade.
Add / Change / Delete please

### PowerShell commands you would normally use to achieve above request

Add-AzureADGroupMember -ObjectId <GroupObjectId> -RefObjectId <UserObjectId>

Remove-AzureADGroupMember -ObjectId <GroupObjectId> -MemberId <UserObjectId>

**Comment by KelvinTegelaar** [comment]
Implemented in dev.
