### ISSUE TITLE
Edit mailbox does not work when entering page from view mailbox

### ISSUE THREAD

**Issue by IzyIsaac** [KelvinTegelaar/CIPP#1994]
### Description

When entering the edit mailbox permissions page from the edit button, everything works as intended. I am able to edit mailbox properties. See screenshot below for the button I am talking about:
![image](https://github.com/KelvinTegelaar/CIPP/assets/9093725/f702d537-3f9b-433d-9a2c-43e709ecd9a6)

The issue occurs when entering the edit mailbox page from the view mailbox page. See below screenshot for the button I am talking about:
![image](https://github.com/KelvinTegelaar/CIPP/assets/9093725/5228ac84-f106-4c69-9edc-1165f00b81b6)

When I click "Edit Mailbox Permissions" under the "Actions" component, it opens up the edit mailbox page, but with a null mailbox user, so none of the commands work. See below screenshots:
![image](https://github.com/KelvinTegelaar/CIPP/assets/9093725/fe2bb2a8-f6e2-4b72-9e41-88268ec49ee9)
![image](https://github.com/KelvinTegelaar/CIPP/assets/9093725/f814a9f4-b057-4f1b-9c1b-13a81ec4a414)

And to re-iterate, everything works fine if I go to edit the mailbox directly from the edit button. I can reproduce this behavior consistently between multiple tenants and mailboxes.

I would like to fix this issue, but I am a new open source contributor so I will probably be slow 🐌

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Sponsored
Front end version number: 4.9.1 
Back end version number: 4.9.3
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by IzyIsaac** [comment]
I would like to work on this please!

**Comment by IzyIsaac** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
As a hint; This issue is due to it passing the wrong variable. Let me know if you want extra help trying to fix this :)

**Comment by IzyIsaac** [comment]
Thanks Kelvin! I am still working on getting dev env up and running properly

**Comment by KelvinTegelaar** [comment]
sorry Izy, Fixed it for you :) I was on the page anyway. The issue was that the "userEmail" variable was the users "mail" attribute - this can be blanked for synced users, instead we use the "UserPrinicipalName" attribute now.

**Comment by IzyIsaac** [comment]
No worries Kelvin! This is the first time I have really looked at the project(or any react project), and now I have a much better idea what is going on. 

I thought the issue was what was being passed as the userId parameter in MailboxesList "View User" button

Here? https://github.com/KelvinTegelaar/CIPP/blob/f6bf6beee15009a9da936ae24a8bcd451c26b451/src/views/identity/administration/ViewUser.jsx#L64
userEmail -> userId

This makes it work in my dev instance
