### ISSUE TITLE
[Feature Request]: Azure Enterprise Application removal outside of offboarding

### ISSUE THREAD

**Issue by Midnigh7** [KelvinTegelaar/CIPP#2000]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Due to client on boarding and sun setting of tools we see the need to be able to remove Azure Enterprise Applications across all of our customer tenants. Ideally we could selecting the app from the Enterprise Applications menu and execute across all/select tenants.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs

**Comment by Midnigh7** [comment]
We are a sponsor, and my account is part of our Org that is sponsoring. How can we get this added as a FR?
