### ISSUE TITLE
[Feature Request]: Include Company Display Name in the Subject Line of every notification

### ISSUE THREAD

**Issue by ronrosenbaum** [KelvinTegelaar/CIPP#2001]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I suggest adding an option to the Notifications to include the Company Display Name in the subject line.
This will allow PSA's such as ConnectWise to properly pull the company name from the subject line via their parsing engine and assign the notification to the appropriate company/client in the PSA.  Currently the tenant ID (domain) is included in the body of the e-mail, which can't be parsed.  We can make ConnectWise lookup via domain name or company name, but not the Tenant ID.

### PowerShell commands you would normally use to achieve above request

N/A

**Comment by KelvinTegelaar** [comment]
Planned.

**Comment by KelvinTegelaar** [comment]
Wanted to make a completely flexible system, but for now the Customer Name is prepended on alert emails. Made Feature Request for added future flexibility.
