### ISSUE TITLE
Security Admin Center: Policies configuration

### ISSUE THREAD

**Issue by Pikelis** [KelvinTegelaar/CIPP#2003]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As MSP admin there is alot of clients where we update Anti-Spam, Anti-Phishing, Anti-Malware policies following best reccomendations (Secure Score) from Microsoft which suggest to enable functions like mentioned below. It guess if it's possible it would be useful to add ability to:
1. Create custom policies: AntiSpam, Anti-Malware, Anti-Phishing, Safe-Links,Safe-Attachments
2. In "Standards" settings have ability to Enabled or Disable below mentioned settings
3. Ability to Create Custom "Standards/BaseLine" which could be applied for selected tenant.
4. Ability to enable Microsoft presets: Standard or Strict.

Ensure that intelligence for impersonation protection is enabled
Move messages that are detected as impersonated users by mailbox intelligence
Enable impersonated domain protection
Set the phishing email level threshold at 2 or higher
Enable impersonated user protection
Quarantine messages that are detected from impersonated domains
Quarantine messages that are detected from impersonated users
Ensure Safe Attachments policy is enabled
Enable the domain impersonation safety tip
Enable the user impersonation safety tip
Enable the user impersonation unusual characters safety tip 
Ensure that an anti-phishing policy has been created
Set maximum number of external recipients that a user can email per hour
Set maximum number of internal recipients that a user can send to within an hour
Set the email bulk complaint level (BCL) threshold to be 6 or lower
Set action to take on high confidence spam detection
Set action to take on phishing detection
Create Safe Links policies for email messages
Ensure that mailbox intelligence is enabled
Create zero-hour auto purge policies for malware
Ensure the Common Attachment Types Filter is enabled
Set action to take on high confidence phishing detection
Set action to take on spam detection
Create zero-hour auto purge policies for phishing messages
Set action to take on bulk spam detection
Create zero-hour auto purge policies for spam messages
Retain spam in quarantine for 30 days

Most of the functions are in single policy.

### PowerShell commands you would normally use to achieve above request

New-AntiPhishPolicy (https://learn.microsoft.com/en-us/powershell/module/exchange/new-antiphishpolicy?view=exchange-ps)
Set-AntiPhishPolicy (https://learn.microsoft.com/en-us/powershell/module/exchange/set-antiphishpolicy?view=exchange-ps)
New-SafeAttachmentPolicy (https://learn.microsoft.com/en-us/powershell/module/exchange/new-safeattachmentpolicy?view=exchange-ps)
New-SafeLinksPolicy (https://learn.microsoft.com/en-us/powershell/module/exchange/new-safelinkspolicy?view=exchange-ps)
New-HostedContentFilterPolicy (https://learn.microsoft.com/en-us/powershell/module/exchange/new-hostedcontentfilterpolicy?view=exchange-ps)
Enable-ATPProtectionPolicyRule -Identity "Standard Preset Security Policy"; Enable-EOPProtectionPolicyRule -Identity "Standard Preset Security Policy"

**Comment by KelvinTegelaar** [comment]
only sponsors can create FRs
