### ISSUE TITLE
[Feature Request]: Standards deviation approval

### ISSUE THREAD

**Issue by AADAutomatisering** [KelvinTegelaar/CIPP#2007]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We were looking into which tool to start using to make managing our customers' tenants easier, and in the end CIPP came out on top because of the pricing and integration with NinjaOne, but we are missing one big feature of compared to other solutions that we feel would be extremely useful for other MSPs:

When you have a standard, there will always be deviations from that standard for certain customers. For example;
SMS OTP is disabled in our standard, but we have a few customers that do still require it, meaning that the customer must have a deviation in the Standard.
CIPP has support for this via the scope-based standards, but it would be nice to be able to leave a note that explains the deviation for other users so that they won't disable this standard when they see it deviates from the global standards.
![image](https://github.com/KelvinTegelaar/CIPP/assets/147389004/30a54ff2-a952-448b-ab03-af8694b688d4)

It would be most preferable to make this field required as soon as a standard deviates from the global standards so that we can ensure that everything is documented for future reference.

### PowerShell commands you would normally use to achieve above request

Not applicable

**Comment by MWGMorningwood** [comment]
This might be a bit more relevant when/if standards start to do inheritance-
In your example, unless you decouple the tenant from All Tenant Standards, it would still attempt to disable MFA.

Would it make more sense to have the deviation notes be applied to the Tenant's standards list in general rather than a specific one? It could, in theory, be tied in with this https://github.com/KelvinTegelaar/CIPP/issues/2037 to provide a list of tenants excluded from all tenants with a reason why.

**Comment by MWGMorningwood** [comment]
> I feel like it would be better and more logical to have standards inherit the "All tenants" standard with overrides unless the "Do not apply All Tenants Standard to this tenant" is enabled

I agree 100%, but designing something like that would add heaps of complexity.
I was tempted to open an FR about inheritance when I read this, but I feel like the #cipp-dev guys would immediately hate me 🤣

**Comment by KelvinTegelaar** [comment]
Would you like faster than light travel with that quantum computer? ;) This FRs is becoming a mess of requests upon requests upon requests. Closing as it doesn't apply, and we're not going to implement any of the other ideas.
