### ISSUE TITLE
[Feature Request]: Total Licenses available for each tenant

### ISSUE THREAD

**Issue by Cavanite** [KelvinTegelaar/CIPP#2009]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Periodically we check our customers there licenses on total consumed licenses and when they are gonna expire.
Many times our support desk buys a license and forgets to tell our administration department.
So basically we are not billing the right amount to our customers.

### PowerShell commands you would normally use to achieve above request

Get-MgSubscribedSku | Select -Property Sku*, ConsumedUnits -ExpandProperty PrepaidUnits | Format-List

https://office365itpros.com/2023/07/06/microsoft-365-subscriptions-ps/

**Comment by KelvinTegelaar** [comment]
Already possible in license overview.
