### ISSUE TITLE
Add Office Location as a field that can be edited for users

### ISSUE THREAD

**Issue by guhri88** [KelvinTegelaar/CIPP#2010]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Add Office Location as a field that can be edited/added for users.
We have multiple clients that have various office locations under a single Office 365 Tenant. We use the Office location for billing and easier management.  

There was a request that asked for this before: 1167, it was marked as completed but I am still not seeing the Office option for users.

**Comment by KelvinTegelaar** [comment]
You can jsr the custom property fields for this.

**Comment by guhri88** [comment]
I am not sure I understand what you mean?
Is there someway I can add the Office location as a field when making or editing a user?

**Comment by kris6673** [comment]
https://github.com/KelvinTegelaar/CIPP/releases/tag/v4.4.0
See under User Attributes 😊

**Comment by guhri88** [comment]
If we add the field does it stick? or does that attribute need to be added each time?
The option is not showing for Editing users, only for new users.

**Comment by ChrisEnvisage** [comment]
Can confirm we can add the custom attribute for officeLocation while onboarding but cannot edit within the "Edit Users" screen.

Possibly could we have the ability to edit custom attributes added to the edit user screen?
