### ISSUE TITLE
[Feature Request]: Set a custom 'friendly name' for tenants within the CIPP GUI

### ISSUE THREAD

**Issue by LachlanBenson** [KelvinTegelaar/CIPP#2018]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Feature Description: Can set a custom or 'friendly' name for an M365 tenant. This friendly name should be viewable under the tenant administration screen such as shown below.
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/8e80502f-123c-4fef-80e2-1716e37ff27d)

Also, it should be viewable in the select tenant dropdown list.
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/6f5ef417-3ec1-43b1-8862-bc4dacc2563e)

As an MSP, we manage hundreds of client tenants. Some of our clients are known by various entity names and our clients often have different names within our PSA tool (ConnectWise in our case) to the names of their M365 tenants. We would like a custom field to be created that allows a Custom "Friendly name" to be set for each TenantID, to allow for ease of searchability in the event that a client can be known by multiple names, or where their M365 tenant does not match up to the name within our PSA tool.

### PowerShell commands you would normally use to achieve above request

N/A

**Comment by KelvinTegelaar** [comment]
Not going to be implemented. You can change the display name of tenants via the edit tenant functionality, that only impacts your partner center side and not the client.
