### ISSUE TITLE
[Feature Request]: Autopilot - Sync and assign user via CIPP

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2020]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

A button to assign the autopilot device to a user in the tenant, via the Autopilot Devices page(or somewhere else).
A sync button somewhere would be very nice too. Maybe at the end of the "Add Autopilot Device" wizard it could be pushed to a queue to execute after a minute or so?

Having everything available in CIPP, and not need to go into the Intune portal would simplify things when adding new devices.

### PowerShell commands you would normally use to achieve above request

Portal only

**Comment by KelvinTegelaar** [comment]
Actually the add-autopilot and listing devices secretly does a background sync, so we have that covered.

Let's see if we can add the assign device :)

**Comment by kris6673** [comment]
Oh that's sneaky, I like it!

Sounds good, thanks! :D

**Comment by KelvinTegelaar** [comment]
added in dev.
