### ISSUE TITLE
[Feature Request]: Scan tenants for already enabled standards

### ISSUE THREAD

**Issue by robm82** [KelvinTegelaar/CIPP#2029]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great if there was an option to scan a tenant in the Edit Standards screen to obtain whether some of the standards have already been enabled or configured. In doing this, you then know what the customer or a previous MSP has configured, and you can review what is already in place before overwriting them with the standards that you want to set. I'm not sure how easy this would be to implement, but I think it would need to have a set of PowerShell scripts that gets the status of the configuration and displays it correctly within the CIPP portal.

**Comment by KelvinTegelaar** [comment]
Thats what the alert report features are for. You set them to report, discover their state using bpa and decide how to continue.
