### ISSUE TITLE
[Feature Request]: Standards - All Tenants excluded list

### ISSUE THREAD

**Issue by MWGMorningwood** [KelvinTegelaar/CIPP#2037]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, when a tenant is excluded from "All Tenants" standards, maintaining them gets a bit tricky.
Because standards do not inherit, any tenants de-coupled from "All Tenants" standards might not be addressed when adjusting standards that _should_ still be applied to those de-coupled tenants.

Having a sort of list at the top of the Standards Menu for "All Tenants" listing all of those that are de-coupled could greatly help with this, allowing admins to follow up on tenants listed there instead of needing to browse through every tenant.

### PowerShell commands you would normally use to achieve above request

Platform change, I believe this is all .JSX, not PS

**Comment by KelvinTegelaar** [comment]
added to list standards
