### ISSUE TITLE
[Feature Request]: Conditional Acces Improvements

### ISSUE THREAD

**Issue by PvtClubby** [KelvinTegelaar/CIPP#2043]
Hi Kevin,

I have a few suggestions that would be handy in the CIPP CA settings:

- When creating a CA policy, you can manually add the users/groups to the include or exclude menu (and also add the location).
**Why:** Because if multiple people need to work with CIPP, everyone needs to know JSON language, and that is very challenging and unpleasant to work with.
- You can create a 'temporary' CA policy that fits the Vacation mode. For example, you can make a CA policy that will be deleted after the 'End Date.'
**Why:** This would be useful in case someone needs to be available abroad.
Otherwise, a separate CA policy would have to be set up so that he can still log in.

Thanks!

**Comment by KelvinTegelaar** [comment]
only sponsors can create FRs
