### ISSUE TITLE
Errors on the new remove groups user panel

### ISSUE THREAD

**Issue by LachlanBenson** [KelvinTegelaar/CIPP#2044]
### Description

When you click on the 'remove from group' button within the users pane, the modal menu text reads "add" not remove
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/f2330b66-3e03-4911-ae46-19fc4ec40752)

Additionally, it lists all groups created in the tenant in the dropdown list, not just the ones the user is in. 
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/63a921ec-9ff3-42e6-975c-0fc8f02972cc)

When you attempt to remove a group that the user is not a part of, just throws this error:
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/381e4dd1-b74f-47ad-a120-7f7d5a0b9dfe)

Otherwise, the functionality of the remove feature works okay, provided that the user is already in the group you are trying to remove it from.

### Environment data

```PowerShell
Sponsored
Front-end version: 5.0.1
Backend version: 5.0.3

Tried tenant cache clear: false
Tried token cache clear: false
```

**Comment by LachlanBenson** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
