### ISSUE TITLE
[Feature Request]: Add Last Successful Sign-In Date to Users List

### ISSUE THREAD

**Issue by robm82** [KelvinTegelaar/CIPP#2046]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Microsoft introduced a new property to identify the last successful sign-in date and time. I know that there is an Inactive Users report, but it would be good to add the last successful sign-in date and time to the normal users view (under Identity Management | Administration | Users) so that you know when any user last signed in. 

### PowerShell commands you would normally use to achieve above request

I was reading this blog post from AdminDroid: https://blog.admindroid.com/get-last-successful-sign-in-date-report-for-microsoft-365-users/

The syntax appears to be: 
((Get-MgBetaUser -UserId <UserId> -Property SigninActivity).SignInActivity.AdditionalProperties).lastSuccessfulSignInDateTime

**Comment by KelvinTegelaar** [comment]
This is only available to P1 subscribers, so we're not implementing this as otherwise the entire API call would error out :)
