### ISSUE TITLE
[Feature Request]: add the "alias" field to new shared mailbox creation

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#2048]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

when you create a shared mailbox on the exchange portal in 365, you get 4 fields, not 3,

a crucial one is alias, which although alot of people dont use all the time, is important,

for instance if you are making several manager@ or receptionist@ on different domains, even though the upn might be manager @ you would specify manager_location or manager-location to diffrentiate these on 365, 

if there is no alias box, the ability to diffrentiate doesnt exist, therefore cipp assumes your upn should be mirrored to alias, therefore you can never create multiple manager@ even if you have 40 different domains with the possibility

please add the alias field

muchas gracias
Raffi

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Added in dev.
