### ISSUE TITLE
Feature Request: View/Update access rights to (shared) mailboxes

### ISSUE THREAD

**Issue by tech-squid** [KelvinTegelaar/CIPP#205]
Allow adding/removing user rights to both user and shared mailboxes, with granular settings for:

For user and shared mailboxes:
- Read and manage permissions
- Send as permissions
- Send on behalf of permissions

For shared mailboxes only:
- disable/enable automapping

**Comment by KelvinTegelaar** [comment]
Planned for v1.5

**Comment by KelvinTegelaar** [comment]
added in dev
