### ISSUE TITLE
[Feature Request]: Be able to save my column view and not select it every time

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#2050]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

1. in mailboxes/ columns - the column "additional email addresses" whilst useful creates too much width on the page
2. when i select the columns to avoid this, they column selection doesnt save
please can we save our column profiles somehow? have it remember my last selection

**Comment by cardonet-helpdesk** [comment]
hello please can this be worked on

**Comment by KelvinTegelaar** [comment]
Implemented, your last selected columns are saved.

**Comment by cardonet-helpdesk** [comment]
is that implemented in live or only in dev? doesnt seem to be working for me in live

**Comment by cardonet-helpdesk** [comment]
now implemented, thanks!
