### ISSUE TITLE
[Feature Request]: Template Replacement Variables

### ISSUE THREAD

**Issue by MWGMorningwood** [KelvinTegelaar/CIPP#2053]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

This feature is currently on the [roadmap](https://github.com/users/KelvinTegelaar/projects/3?pane=issue&itemId=49316500), and I am primarily opening this to raise its priority and possibly discuss execution.

We are currently utilizing CIPP's All Tenant Standards to carry much of the weight of setting up a Microsoft tenant and ensuring no config drift.
When implementing Conditional Access templates, entering a templated group in its exclusions is currently impossible.
This mostly comes from the fact that the templates are not aware of each other, and the Conditional Access policy ends up being pushed with an excluded GUID that does not exist in the tenant.

Considering this feature is on the [roadmap](https://github.com/users/KelvinTegelaar/projects/3?pane=issue&itemId=49316500), the team already likely has a good idea of how they want to do this.

A potentially decent way to go about this could be to refer to the template GUIDs in CIPP wrapped or preceded by some sort of identifying character.

### PowerShell commands you would normally use to achieve above request

```
Install-Module Microsoft.Graph
Connect-MgGraph -Scopes "Group.ReadWrite.All"
$param = @{
 description="My Demo Group"
 displayName="DemoGroup"
 mailEnabled=$false
 securityEnabled=$true
 mailNickname="Demo"
}

New-MgGroup @param
```

```
Import-Module Microsoft.Graph.Identity.SignIns

$params = @{
	displayName = "Access to EXO requires MFA"
	state = "enabled"
	conditions = @{
		clientAppTypes = @(
			"mobileAppsAndDesktopClients"
			"browser"
		)
		applications = @{
			includeApplications = @(
				"00000002-0000-0ff1-ce00-000000000000"
			)
		}
		users = @{
			includeGroups = @(
				"ba8e7ded-8b0f-4836-ba06-8ff1ecc5c8ba"
			)
		}
		locations = @{
			includeLocations = @(
				"All"
			)
			excludeLocations = @(
				"AllTrusted"
			)
		}
	}
	grantControls = @{
		operator = "OR"
		builtInControls = @(
			"mfa"
		)
	}
}

New-MgIdentityConditionalAccessPolicy -BodyParameter $params
```

I wouldn't honestly be sure where to begin attempting to implement cross-awareness, but these are the basic PS commands.

**Comment by MWGMorningwood** [comment]
I would like to raise the priority (idk if this will work since my org is the sponsor)

**Comment by KelvinTegelaar** [comment]
Its on the roadmap and priotized, no need for this fr :)
