### ISSUE TITLE
Searching "Device Management" > "Policy Templates" for "Bitlocker" causes duplication

### ISSUE THREAD

**Issue by abulgatz** [KelvinTegelaar/CIPP#2054]
### Description

1. Click on Device Management
2. Click on Policy Templates
3. Search for "Bitlocker"
4. Backspace to delete search
5. Type in "Bitlocker" again
6. A duplicate "CIPP: Enable Bitlocker Encryption for OS drives" appears
7. Repeat steps 4-5 and a new copy of "CIPP: Enable Bitlocker Encryption for OS drives" appears each time the search returns results
8. Clicking the refresh button or refreshing the page clears the duplicated "CIPP: Enable Bitlocker Encryption for OS drives" results

![Kapture 2024-01-25 at 23 39 07](https://github.com/KelvinTegelaar/CIPP/assets/1438193/64391d99-519e-4a8f-a841-0ff1d0f95b88)

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 5.0.1
Back end version number: 5.0.4
Tried Tenant Cache Clear: true
Tried Token Cache Clear: cleared all cache. Is clearing token cache still recommended? Per: https://docs.cipp.app/setup/installation/cleartokencache, it is not?
```

**Comment by abulgatz** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by abulgatz** [comment]
It looks like performing _any_ search on that page causes the Bitlocker template to be duplicated in the results. I cannot delete the original Bitlocker template either. It says it is deleted but it is not.

**Comment by KelvinTegelaar** [comment]
You cant delete CIPP default templates. The other bug has been solved in dev.
