### ISSUE TITLE
[Feature Request]: lastSignInDateTime field in users

### ISSUE THREAD

**Issue by Novem-MSP** [KelvinTegelaar/CIPP#2059]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

get the last login time as a column in the Users tab so we can add it to our reports

https://learn.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-1.0

lastSignInDateTime would be the data required 

### PowerShell commands you would normally use to achieve above request

$user = Get-MgUser -UserId -ConsistencyLevel eventual -Property UserPrincipalName SignInActivity

$user.SignInActivity.LastSignInDateTime

**Comment by KelvinTegelaar** [comment]
This is a P1 only property, and would make any call without P1 fail, you can report on this yourself using the Graph Explorer instead :)

**Comment by Novem-MSP** [comment]
Hi Kelvin, 

I have tried using the graph explorer, but trying to export all fields to a csv, the SignInActivity exports to [object object]. 

How would I just return the lastSignInDateTime field? 

Thanks,
Liam
