### ISSUE TITLE
"Enables DKIM for all domains" Omits Domains with no existing DKIM setup

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2062]
### Description

The "Enables DKIM for all domains" uses Get-DkimSigningConfig as a basis for listing out domain names in the tenant. The problem is that this command only returns results for domains that have some DKIM configuration already and not all verified, accepted domains. Please consider revising the logic of this standard to pull a list of ALL accepted domains, not just ones from the Get-DkimSigningConfig command.

### Environment data

```PowerShell
Sponsored instance
Front end version number: 5.0.1
Back end version number: 5.0.5
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by PremierOneData** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by kris6673** [comment]
Already fixed in dev. Logic is now getting all email enabled domains and handling results based on that
https://github.com/KelvinTegelaar/CIPP-API/pull/602

**Comment by KelvinTegelaar** [comment]
Resolved in dev.
