### ISSUE TITLE
[Feature Request]: Add and edit a user's Manager

### ISSUE THREAD

**Issue by LachlanBenson** [KelvinTegelaar/CIPP#2063]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Very similar to #1342 which was closed without implementing.

A number of our larger clients with complex organisational structures rely on having an accurate Manager being set for each of their users for approvals to oversee direct report approvals in their day-to-day operations. Without having the ability to edit Manager in CIPP, it means that as an addition to using the CIPP onboard/offboarding flow, our staff still need to visit the M365 portal to create/remove users.

As a part of onboarding and offboarding we are requested to 
1. Add a Manager attribute when new staff join
2. Update the manager attribute if a user is promoted
3. Change the manager of mulitple staff at once when a Manager is offboarded

The feature request would involve:
1. Can set Manager attribute within onboarding flow.
2. Being able to view the Manager attribute under **Identity Management > Administration > Users > View/Edit**.
3. Can update the manager of one user at a time by visiting "Edit Users" pane
4. Can select multiple users at once within the Users screen and click "update manager"
5. The ability reassign a Manager for downline user objects during Offboarding if you are removing a Manager from the system.

**Comment by ChrisEnvisage** [comment]
I would like to upgrade the priority

**Comment by sgexcit** [comment]
I'll second Chris's motion to upgrade the priority, being the requester of #1342

**Comment by KelvinTegelaar** [comment]
@sgexcit Only sponsors can make FRs or prioritize them.

**Comment by ChrisEnvisage** [comment]
@KelvinTegelaar Request was made on my behalf for this feature. Will I need to create a request of my own or can we leave this one open?

**Comment by KelvinTegelaar** [comment]
added in dev.
