### ISSUE TITLE
[Feature Request]: Add Office Location & State attributes as fields that can be edited for users

### ISSUE THREAD

**Issue by ChrisEnvisage** [KelvinTegelaar/CIPP#2064]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Similar to #2010

We have multiple clients that operate throughout various office locations within different states and use those attributes to run reports on which employees are based in which offices, or within certain states.

The feature request is to add Office Location and State as an editable attribute within the edit users screen, and also as part of the onboarding flow. We can currently do this using the custom attributes field to set the location & state within onboarding, but have no way to update this if the user moves office or state without logging into M365.

If this is not desired able to be implemented, allowing for the editing of custom attributes (similarly to the onboarding flow) within the edit user screen would be a viable backup option.

**Comment by KelvinTegelaar** [comment]
Custom attributes are available in edit user now.

**Comment by ChrisEnvisage** [comment]
@KelvinTegelaar can you confirm if this is a next release feature or should currently be available? Can't seem to see it within our edit users pane.

We are on frontend 5.0.1 and backend 5.0.5
