### ISSUE TITLE
[Feature Request]: Ability to synchronize "total license counts"

### ISSUE THREAD

**Issue by gradientbryan** [KelvinTegelaar/CIPP#2078]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, the extension integration with Gradient MSP only syncs over "assigned" licenses and some MSPs want the ability to sync "total license counts" including both assigned and unassigned licenses.

**Comment by KelvinTegelaar** [comment]
Planned.

**Comment by KelvinTegelaar** [comment]
Total licenses are now synced.
