### ISSUE TITLE
[Feature Request]: Ability to sync commitment and billing terms to Microsoft NCE licenses on service creation

### ISSUE THREAD

**Issue by gradientbryan** [KelvinTegelaar/CIPP#2079]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Need to append the commitment and billing terms to Microsoft NCE licenses, so MSPs can allocate these licenses appropriately to their products/services in their PSA, since they could have a combination of commitment/billing terms for the same Microsoft NCE license.

**Comment by KelvinTegelaar** [comment]
Planned
