### ISSUE TITLE
Partner Centre Permissions check not listed as missing permissions

### ISSUE THREAD

**Issue by devallllll** [KelvinTegelaar/CIPP#2080]
### Description

![image](https://github.com/KelvinTegelaar/CIPP/assets/93842433/a721bc59-c178-4315-a3ab-b6656cd70b0d)

Running the permissions check should identify that the Microsoft Partner Center user_impersonation permission had not been granted

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Non-sponsored instance
Front end version number: 5.0.1
Back end version number: 5.0.5
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: false
```

**Comment by devallllll** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by KelvinTegelaar** [comment]
Not a bug, it says "no" because consent is not required. If you had an issue, it wasn't this, unless you enabled your own partner tenant which isn't supported.
