### ISSUE TITLE
Alerts are not getting through to the configured email

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2082]
### Description

I've configured my email address in Application Settings > notifications and applied all severities. I've then setup a few rules for a specific tenant (ex: when an account is enabled/disabled) and manual disabled one in O365 admin portal to trigger the alert, but no email is received.

I've looked in my Inbox, Junk Email, Office365 quarantine and searched via the Message Trace, but no email has come through. Is some extra configuration needed for this? I looked in the documentation, but the page for "Alerting setup" is still empty. 

Also, how are the email alerts send exactly? Is that using the Exchange server of our tenant or a general one for all CIPP users? Do we need to configure the SMTP settings anywhere or can they be changed to our own SMTP server (ex Office365 via Modern Authentication)?

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 5.0.1
Back end version number: 5.0.5
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by Lenwe666** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug. If you need support you require sponsorship.

**Comment by shaun-cns** [comment]
@Lenwe666 did you ever figure it out?
