### ISSUE TITLE
[Feature Request]: Actions for Onedrive/Sharepoint/Teams

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2083]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Can more actions be implemented for OneDrive/Sharepoint/Teams management in CIPP? At the moment, only a table with all existing items are shown, but no actions can be executed on it. For Teams, only a new Team can be created, editing a existing one is not possible.

It would be saving a lot of time if we could make simple adjustments (like the info on the pages General, membership and settings in Sharepoint admin center) to Sharepoint sites/Onedrive/Teams. Now, we still have to switch to the corresponding admin portal.

### PowerShell commands you would normally use to achieve above request

Set-SPOSite -Identity [url to site] -StorageQuota 3000 -StorageQuotaWarningLevel 2000 -DisableSharingForNonOwners [other options]

Set-Team -GroupId [id] -DisplayName "Updated TeamName" -Visibility Public

**Comment by Lenwe666** [comment]
Perhaps this can also be available for the Enterprise Application page as this has the same setup (only a table with items shown, but no actions)

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
