### ISSUE TITLE
Using custom reports made with the BPA report builder

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2084]
### Description

I've made a custom report with the BPA report builder and clicked "Publish" to save it. My Github opened but the new file doesn't automatically include the data generated in the BPA report builder. I thus copied the generated JSON manually and saved the report to the master branch.

After clearing all caches, I can find the report in the list of BPA report builder, but can't seem to execute it anywhere. How/where do I use/execute the custom reports in CIPP? 

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 5.0.1
Back end version number: 5.0.5
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by Lenwe666** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support question, not a bug. If you require support you can sponsor.
