### ISSUE TITLE
[Feature Request]: Ability to see inside sharepoints, and see which security groups apply to which folders

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#2090]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

appreciate you adding some more sharepoint abilities, however in my experience, mostly we dont work with just members of sites, we work with azure sec groups tied to sites/folders

so please can you give us the option to dial down into the site and at least see which sec groups are applied to which folders?

thanks
Raffi

**Comment by KelvinTegelaar** [comment]
No APIs available for that, so closing as "not possible" for now.
