### ISSUE TITLE
[Feature Request]: New Standard for Disabling Legacy Protocols in SharePoint

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2094]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Our clients get audited by third parties, and often the auditors find the following setting set to **true**, which is bad:  **isLegacyAuthProtocolsEnabled**

If the CIPP standard is enabled, we'd want CIPP to set the following setting in Graph: 
**isLegacyAuthProtocolsEnabled**: "**false**"

Here is the graph endpoint: https://learn.microsoft.com/en-us/graph/api/sharepointsettings-update?view=graph-rest-1.0&tabs=http

### PowerShell commands you would normally use to achieve above request

Per this article: https://stealthbits.com/blog/how-to-harden-you-sharepoint-online-environment-by-disabling-legacy-authentication/
`Set-SPOTenant –LegacyAuthProtocolsEnabled $false`

OR

Here is the MS Graph endpoint: https://learn.microsoft.com/en-us/graph/api/sharepointsettings-update?view=graph-rest-1.0&tabs=http

**Comment by kris6673** [comment]
I want to work on this!

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
added in dev.

**Comment by HappyEarthDay** [comment]
Can this be added to the SharePoint Best Practices Report as well?
