### ISSUE TITLE
Mailbox Quota Alert Error occurred: Attempted to divide by zero.

### ISSUE THREAD

**Issue by STG-Tanner** [KelvinTegelaar/CIPP#2095]
### Description

If mailbox quota alerts are enabled for a tenant without Exchange licensing, an error is sent to the alert destination. "Mailbox Quota Alert Error occurred: Attempted to divide by zero."

Reproduce by enabling classic alert "Alert on 90% mailbox quota used" for a tenant with only Microsoft 365 Apps for Business licenses.

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.1.0
Back end version number: 5.1.0 
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
fixed in dev
