### ISSUE TITLE
Unable to save user settings for dark/light mode

### ISSUE THREAD

**Issue by LachlanBenson** [KelvinTegelaar/CIPP#2109]
### Description

Under Settings -> CIPP -> User Settings
![image](https://github.com/KelvinTegelaar/CIPP/assets/109946739/79e1e81e-79a4-47f2-9ab1-885e25303247)

You can click either Light or Dark Mode, but then clicking "Save Settings" does not seem to do anything (no success message as feedback).

Therefore, it does not apply the change permanently - it resets upon closing browser.

### Environment data

```PowerShell
Sponsored

Front end version: 5.1.1
Backend API version: 5.1.0
Tried Tenant Cache Clear: True
Tried Token Cache Clear: True

```

**Comment by LachlanBenson** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Hi Lachlan,

This isn't a bug, someone probably set the default for all users as Dark Mode, or your browser is forcing dark mode.
