### ISSUE TITLE
[Feature Request]: Improve Efficiency of Mailbox Statistics Report for All Tenants

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2110]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

On the Mailbox Statistics report, when selecting All Tenants when there are a decent number of Tenants in CIPP, the request times out stating "The Azure Function has taken too long to response." We would love to see the efficiency of this report improved for the All Tenants selection so that it can run properly without timing out when there are many tenants under management in CIPP.

**Comment by KelvinTegelaar** [comment]
Resolved in dev.
