### ISSUE TITLE
[Feature Request]: Ability to manage Entra ID Registered Devices

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2111]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

CIPP currently allows for management of devices that are in the InTune portal, however this feature request would expand the capabilities of CIPP to manage device registrations that appear in the Entra ID portal (i.e. https://portal.azure.com/#view/Microsoft_AAD_Devices/DevicesMenuBlade/~/Devices/menuId~/null)

Useful data fields would include: Device Name, Enabled/Disabled State, OS, Version, Join Type, Owner, Owner UPN, MDM, Registered Date, and Last Activity Date

Useful actions would be: Disable, Delete (this would allow us to easily clean up inactive devices beyond a certain date threshold based on the Last Activity Date)

This capability would give us a broader overview of devices interacting with Microsoft Services in a customer's tenant and allow us to better understand assets that may need more oversight. It would also help us plan for enforcing Intune enrollment and compliance by providing a list of assets that are currently accessing company resources without Intune enrollment.  Overall, this would benefit our efforts towards CIS Control 1: Inventory and Control of Enterprise Assets (1.1, 1.2, and 1.3) and somewhat Controls 3.6, 4.5-4.12, 10.1-10.2, 13.5 by helping us identify and enroll registered but unmanaged devices into InTune.

**Comment by KelvinTegelaar** [comment]
Added to dev under Identity -> Devices.
