### ISSUE TITLE
[Feature Request]: Turn off Microsoft Managed Policies

### ISSUE THREAD

**Issue by MBstatsara** [KelvinTegelaar/CIPP#2113]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Microsoft are rolling out Microsoft-Managed policies across all customers.
This means that at some random point, the tenant could have MFA enabled, but causing lots of issues as its not know about.
We developed a script to report and then one to remediate the issues by disabling all these policies.
Sharing this as it has helped us out, and could be implemented into CIPP.

### PowerShell commands you would normally use to achieve above request

To remediate
```
##Gather all policies which are Microsoft managed

$policies = Get-MgIdentityConditionalAccessPolicy -Filter "startswith(displayName,'Microsoft')"
##loop through each policy and set them to disabled

foreach ($policy in $policies){
if ($policy.State -eq "enabledForReportingButNotEnforced")
{Update-MgIdentityConditionalAccessPolicy -ConditionalAccessPolicyId $policy.id -State disabled
    Write-Host $policy.displayName is now disabled}
elseif ($policy.State -eq "disabled") {Write-Host $policy.DisplayName is not enabled.
    Write-Host $policy.State
}
}

```
To find 

```
$policies = Get-MgIdentityConditionalAccessPolicy -Filter "startswith(displayName,'Microsoft')"
$policies |select DisplayName,State
foreach ($policy in $policies) {if ($policy.state -eq "Enabled"){write-host $policy.DisplayName}}
```

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
