### ISSUE TITLE
Permissions Check Still Looking for Azure Active Directory Graph Permissions

### ISSUE THREAD

**Issue by litechsupport** [KelvinTegelaar/CIPP#2115]
### Description

It seems like the Permissions checker is still looking for Azure Active Directory permissions before showing the "You have all the required permissions" 3rd line in the Permissions check box that appears. 

I get these,

Your refresh token matches key vault.
Your access token contains the MFA claim.

but not the 3rd one. I know it was previously mentioned that the old Azure Active Directory Graph API wasn't being used anymore in the application. Figured it would be wise to stop checking for it as you can't add permissions for that via the Azure UX anymore. 

### Environment data

```PowerShell
Non-sponsored
Front/Back: Latest 5.1.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
support question, not a bug.

**Comment by litechsupport** [comment]
How is this a support question? Earlier issue reports state from you that these permissions aren't required any more. But yet the app still checks for them on permissions check in the UX. Adding or removing them via Azure CLI is the difference between successful permissions check and not on our CIPP instance. That is either a bug, a known issue that you aren't fixing or a documentation correction. It's not in any way a support question.......

**Comment by KelvinTegelaar** [comment]
Not to answer your entire question, but the permissions are still required. Feel free to sponsor for support.

**Comment by litechsupport** [comment]
Well with that being the case, at least add the permissions back into this list: https://docs.cipp.app/setup/installation/permissions

They aren't listed there anymore. I'm just trying to help....... Thanks.
