### ISSUE TITLE
Failed to remove template: Cannot validate argument on parameter 'Entity'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

### ISSUE THREAD

**Issue by jmv-support** [KelvinTegelaar/CIPP#2118]
### Description

There's an issue with removing templates from Intune/Device Management. 

Steps to reproduce: 

1: Go to Intune/Device Management/Policy Templates
2: Select a policy and click on the View icon to see the JSON.
3: Copy the JSON displayed here
4: Go to Intune/Device Management/Add Policy Template
5: Enter a display name, a description and select a policy Type (they all have the same effect). In this case I selected the Settings Catalog since that was the JSON I copied.
6: Paste the copied Raw JSON from step 3
7: Click Add Template. "Successfully added template" will appear at the top of the screen.
8: Go to Intune/Device Management/Policy Templates
9: Select the policy created in 5. 
10: Press the Delete icon. 
11: Press the Continue button on the "Do you want to delete the template?" dialog.
12:  An error message appears: Failed to remove template: Cannot validate argument on parameter 'Entity'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

Going in from this point:

13: Click the View icon on the policy created in step 5
14: Click 'Save Changes' and see the "Successfully saved the template" message. Close the dialog
15: Press the Delete icon on the same policy created in step 5
16: Press the Continue button on the "Do you want to delete the template?" dialog.
17: A success message appears: "Successfully removed Intune Template"

The template is NOT removed from the list. Trying to repeat from step 10 results in the same sequence. 

Is this related to [#1750](https://github.com/KelvinTegelaar/CIPP/issues/1750)? 

### Environment data

```PowerShell
Sponsored / Hosted
Front end version number: 5.1.1
Back end version number: 5.1.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by jmv-support** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by DanielWahlgren** [comment]
I have the same issue, so it is not unique to your environment. Also on 5.1.1

**Comment by jmv-support** [comment]
So when 'bugs' are ignored, they become 'features' and you're on your own and need to solve the issues yourself? Weird way of working.... 
The reply you need to send back that you confirm that this _is_ a bug is weird as well. But I think that bot explained it well: CIPP is flawless and everything a user does is a bug: the first thing it says: Thank you for _creating_ a bug.

**Comment by jmv-support** [comment]
Thanks for the suggestion, I'll give it a go. 

To be honest, the template is created by CIPP (I only added the json) so I would expect either a working, deployable template or the correct checks before creating it. Even if I copy it from an existing one, this error occurs so somewhere along the line something goes wrong.

**Comment by KelvinTegelaar** [comment]
Solved in dev

**Comment by lraikhman** [comment]
I have this exact problem on the hosted Cyberdrain instance, and obviously can't access the backend as suggested by @DanielWahlgren.

How can I raise a support case?

**Comment by axxs** [comment]
I also have this problem on a hosted instance, but with transport rule templates.

**Comment by jonmonsystems** [comment]
I have this problem with my hosted instance when trying to modify or remove Intune templates that were built in
