### ISSUE TITLE
[Feature Request]: Allow adding devices to groups

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2119]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

With Intune device management (Endpoint manager etc) where devices are assigned certain policies, profiles and applications. This is typically completed via groups. (i.e. the app or config profile is assigned to the group).
Adding the device to the group would then allow these devices to get their configurations.

Using the below powershell command I utilise the 'IsManaged' part of the object to ensure that it is a managed and enrolled device into Intune.

.

### PowerShell commands you would normally use to achieve above request

$Device = get-mgdevice | where {($_.displayname -eq "COMPUTERNAME") -and ($_.ismanaged -eq "True")}
$Group = get-mggroup | where -Property Displayname -eq "GROUPNAME"
$CR_AddMember = New-MgGroupMember -GroupId $group.id -DirectoryObjectId $device.id

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs.
