### ISSUE TITLE
[Feature Request]: Ability to export, view and add Compliance Policies in Intune

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2120]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

For Microsoft Intune, the built in feature for marking devices as compliant, then utilising Conditional Access based on this compliance status is a big one for us for device security and data access for our customers.
We have over 30 customers utilising a pretty standard format, which is a pain to have to dial into each tenant manually and either run a custom PowerShell script/function or add manually each time we want to adjust.

This would be the same ability as the current Intune section in CIPP with the configuration profiles.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs.
