### ISSUE TITLE
[Feature Request]: Webhook For Offboarding Wizard

### ISSUE THREAD

**Issue by cptech-bweese** [KelvinTegelaar/CIPP#2125]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I'd like to be able to check a box in the off boarding Wizard and fire off a webhook.  We were demoing CIPP to a few team members and someone brought up that we have a manual process currently when off boarding users to archive their Egnyte.  I can setup an automation around the Egnyte work but I was thinking that if there was a checkbox in CIPP that would trigger the webhook if they have Egnyte that'd be cool.  There are probably a lot of other use cases that could benefit from being able to setup webhooks for various app offboarding.

**Comment by KelvinTegelaar** [comment]
Already possible, see notifications configuration

**Comment by cptech-bweese** [comment]
I have the webhook notification setup currently for all alerts, it feeds to n8n and then creates a Slack message.  I was hoping for more granular setup for specific instances like this Egnyte scenario.  I can probably make the existing setup work with some more flow in my automations.
