### ISSUE TITLE
Tenant onboarding stuck on GDAP Group Mapping

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2129]
### Description

Hello!
I've not tested this enough to say if its reproducible but there should be a way to cancel the tenant onboarding job.
On Friday i ran the Tenant Onboarding job and it got stuck on Step 3: GDAP Group Mapping
![image](https://github.com/KelvinTegelaar/CIPP/assets/15158490/8690d764-0b67-4562-9f3c-c38385c31f17)
![image](https://github.com/KelvinTegelaar/CIPP/assets/15158490/0b093547-0f8b-4ce2-81f3-6dd4a7639105)

I've rebased the API, restarted the Function App and waited for Timeout but there appears to be no such thing? Would it be possible to add a way to cancel the operation?

### Environment data

```PowerShell
Currently Non-sponsored
Frontend Version: 5.1.1
Backend API Version: 5.1.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: ? (not used anymore? used Clear all cache)
```

**Comment by OfficialEsco** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support question, not a bug

**Comment by OfficialEsco** [comment]
So its a intended feature that "Onboarding Status" gets stuck on "GDAP Group Mapping" for multiple days without a way to cancel the operation?
