### ISSUE TITLE
(Minor) /api/EditUser fails silently with empty/misformatted body

### ISSUE THREAD

**Issue by jonc3tech** [KelvinTegelaar/CIPP#2131]
### Description

1.) Open Powershell 7
2.) Initialize API specific variables and generate token based on CIPP Documentation
```
$CIPPAPIUrl = "xxxx"
$ApplicationId = "xxxx"
$TenantId = "xxxx"
$apiSecret = "xxxx"

$token = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token" -Method POST -Body 
```
3.) Submit API Post request with empty body
```
$AuthBody = @{
    client_id     = $ApplicationId
    client_secret = $ApplicationSecret
    scope         = "api://$($ApplicationId)/.default"
    grant_type    = 'client_credentials'
}
$AuthHeader = @{ Authorization = "Bearer $($token.access_token)" }
Invoke-RestMethod -Uri "$CIPPAPIUrl/api/EditUser" -Method POST -Headers $AuthHeader -ContentType "application/json" -Body @{}
```
4.) A success response is received:
![image](https://github.com/KelvinTegelaar/CIPP/assets/153545031/37d258f6-5e22-4f2e-9dd2-6e1c8955e1ac)5.) CIPP Logbook notes an action with no content
![image](https://github.com/KelvinTegelaar/CIPP/assets/153545031/84b96482-106c-4ba8-8098-1a57331df125)

### Environment data

```PowerShell
Sponsored instance
Front end version number: 5.1.1
Back end version number: 5.1.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
because theoritically, the user {} has been edited. ;) hahaha, fixed in dev.
