### ISSUE TITLE
phone support

### ISSUE THREAD

**Issue by LevitSmith** [KelvinTegelaar/CIPP#2136]
### Description

can someone call me to give me support? I dont want to pay for the software but I just need someone to walk me through the setup. 

### Environment data

```PowerShell
can someone call me to give me support? I dont want to pay for the software but I just need someone to walk me through the setup.
```

**Comment by KelvinTegelaar** [comment]
This has to be a troll, but if you need support you can sponsor to contact our helpdesk.

**Comment by LevitSmith** [comment]
not trolling i just need someone to call me, walk through azure setup and create all accounts for me. its a complex setup and im not going to pay for free software. if you release it for free you should support it for free

**Comment by simislearning** [comment]
@LevitSmith  [how to call support](https://letmegooglethat.com/?q=what+is+open+source+)

**Comment by Jr7468** [comment]
![image](https://github.com/KelvinTegelaar/CIPP/assets/126574444/c2cdc0f1-e55c-474b-a658-b2744c7a3dd0)

**Comment by rvdwegen** [comment]
This can't be real.
