### ISSUE TITLE
Extended user information sidebar width issue

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2139]
### Description

On the page Identity management > Administration > Users
In the extended information sidebar opens, when you select the 3 dots beside a user, the columns are small, which make the values and properties span multiple lines

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Non-sponsored 
Front end version number: 5.1.1
Back end version number: 5.1.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
more a feature request, only sponsors can create FRs.
