### ISSUE TITLE
Add Onedrive shortcut modal dialog has empty values 

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2140]
### Description

The combobox in "Add OneDrive shortcut" in modal dialog is listing items on URL, which gives blank values for some sites

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Non-sponsored 
Front end version number: 5.1.1
Back end version number: 5.1.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
support request, you probably have anonymized names enabled. Only sponsors get support.

**Comment by Lenwe666** [comment]
Are you really always going to answer that, because we didn't sponsor (yet, still testing this application).
This has nothing to do with anonymized names as some are listed with the URL. So definitely and issue

![image](https://github.com/KelvinTegelaar/CIPP/assets/38354708/5a398127-4199-4953-9f4d-f2423abb873e)
