### ISSUE TITLE
Adding aliases when adding/editing users fails 

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2142]
### Description

Extra aliases can not be added via the CIPP application. This is both when adding a new user, or editing a existing one.

The error when adding one: "Failed to create the Aliases: Invalid value specified for property 'mail' of resource 'User'."

The error when editing one: "Success. The user has been edited. Successfully edited user. The password is . We've failed to create the Aliases: Invalid value specified for property 'mail' of resource 'User'"

Also, there was no password change requested, but the error still states something about the password

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Non-sponsored 
Front end version number: 5.1.1
Back end version number: 5.1.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by Lenwe666** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, please stop creating support requests. These are all input issues/support requests.
