### ISSUE TITLE
Named locations "last modified" property always "invalid date"

### ISSUE THREAD

**Issue by Lenwe666** [KelvinTegelaar/CIPP#2144]
### Description

On the page Tenant administration  > Conditional Access > Named locations
The property "last modified" for all items is always "invalid date", both for items made via CIPP and in Azure itself

![image](https://github.com/KelvinTegelaar/CIPP/assets/38354708/c9e5e494-d751-4db8-b135-5f308446966f)

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Non-sponsored 
Front end version number: 5.1.1
Back end version number: 5.1.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by Lenwe666** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Again, support issue. This has to do with incorrect GDAP setups. Please stop creating issues or we'll be forced to ban you.

**Comment by Lenwe666** [comment]
How is that not a bug? The GDAP relations has all permissions it needs, like stated in your documentation, and confirmed when checking this from inside the application

![image](https://github.com/KelvinTegelaar/CIPP/assets/38354708/27a108df-b7e3-44fe-a64b-d51b01cf6a5e)
