### ISSUE TITLE
[Feature Request]: Exclude from AllTenants standards when onboarding new tenants

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2147]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It's not always that when onboarding a customer, that you are allowed to rollout your standards but you are allowed to set yourself as partner and make a GDAP relationship.
Either having the AllTenants standard as opt-in and new tenants excluded by default, or having a toggle in the onboarding phase to set the exclusion would be very nice :)

**Comment by kris6673** [comment]
> This would require a complete rewrite on both onboarding, and standards, so it's not going to happen for a long time. Closing for now.

Couldn't we technically set the OverrideAllTenants standard as a toggle out of the box without needing to rewrite the whole thing?

**Comment by KelvinTegelaar** [comment]
> Couldn't we technically set the OverrideAllTenants standard as a toggle out of the box without needing to rewrite the whole thing?

No, because that would be that the tenant table becomes fully persistent instead of dynamic as it is currently, and we'd need to rewrite the GDAP mapping wizard, remove the timers, change the docs to always have people execute onboarding, etc etc. It would remove a lot of dynamic parts of CIPP.
