### ISSUE TITLE
[Feature Request]: Create Standard that allows us to set Exchange Message Expiration

### ISSUE THREAD

**Issue by shinomen** [KelvinTegelaar/CIPP#2148]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We are setting up external connectors that will route outgoing email to any domain (*) to go through the connector which will have a requirement of TLS in an effort to force all email communication to communicate securely with the recipients server.  However, Microsoft has a 24 hour time limit for emails to be retried before they are finally bounced back as undeliverable.  This is too long in my opinion for a user to be notified (ideally it would be great for the mail to bounce back right away but that does not seem to be an option right now) so we would like to set the MessageExpiration to 12 hours.  It would be nice to have a standard that we could apply for this setting.  I got the command from this website:  https://m365scripts.com/exchange-online/customize-undelivered-message-retry-period-in-exchange-online/  

### PowerShell commands you would normally use to achieve above request

Set-TransportConfig –MessageExpiration 12:00:00

**Comment by KelvinTegelaar** [comment]
added in dev
