### ISSUE TITLE
[Feature Request]: Bulk Actions on Administration > Devices Page

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2154]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The new Devices page would greatly benefit from being able to bulk select devices and perform a Disable or Delete operation.

**Comment by KelvinTegelaar** [comment]
good idea, didn't think of this, let's add it. :)
