### ISSUE TITLE
[Feature Request]: Ability to block/whitelist emails/domains 

### ISSUE THREAD

**Issue by Jhohbein-centrexit** [KelvinTegelaar/CIPP#2155]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Our Helpdesk frequently has to make those changes and would be more efficient if we have the ability to modify the spam filter settings and whitelist or blacklist emails. 

### PowerShell commands you would normally use to achieve above request

New-TenantAllowBlockListItems -ListType Sender -Block -Entries "DomainOrEmailAddress1","DomainOrEmailAddress1",..."DomainOrEmailAddressN" <-ExpirationDate Date | -NoExpiration> [-Notes <String>]

New-TenantAllowBlockListItems -ListType Sender -Block -Entries "test@badattackerdomain.com","test2@anotherattackerdomain.com" -ExpirationDate 8/20/2022

**Comment by jmwisc** [comment]
Yes please!
