### ISSUE TITLE
[Feature Request]: Ability to mass enable/disable guest accounts

### ISSUE THREAD

**Issue by MFM-IT** [KelvinTegelaar/CIPP#2157]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

After adding 90 day disablement of guest access this did cause issues in some of our enironments, mass unblock sign in doesnt appear to work stating 'unable to unblock xxxxxx'. However in individual guest accounts this works fine.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs :)
