### ISSUE TITLE
[Feature Request]: New User Onboarding Template

### ISSUE THREAD

**Issue by ContinuousJay** [KelvinTegelaar/CIPP#2159]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great to have the ability to create templates on a per tenant basis or global for new user onboarding so we can include by default additional attributes such as officeLocation and require them to be mandatory or not.

**Comment by BNWEIN** [comment]
I am working on this.

**Comment by KelvinTegelaar** [comment]
Added in dev.

**Comment by KelvinTegelaar** [comment]
> Any news on this? Really want this feature

This has been implemented by adding a copy feature from any user. If you want anything else, you'll have to sponsor CIPP to be able to create feature requests.
