### ISSUE TITLE
[Feature Request]: Start an email newsletter to share about new releases please.

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2165]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

LinkedIn Posts are sometimes missed, and it would be nice if the sponsored/hosted clients atleast receive a newsletter email with all the latest features so they can test them out

**Comment by KelvinTegelaar** [comment]
This is something we won't do, maintaining an email platform etc is not something we want; however we recommend registering at our discord at https://discord.gg/cyberdrain where you get tagged with each release and webinar we give.
