### ISSUE TITLE
[Feature Request]: Enable Duo Integration for MFA push please

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2166]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As a lot of MSPs are using Duo for MFA for 365 and majority of apps that their client uses, it would be good to enable Duo push functionality within CIPP using API

**Comment by KelvinTegelaar** [comment]
MFA is untrusted by Microsoft, and as such single factor authentication. Until Duo fixes that this is a hard no.
