### ISSUE TITLE
The help icon within CIPP hosted platform takes to a "Page not found" area

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2167]
### Description

Clicking the help sign, we end up on this screen: https://docs.cipp.app/user-documentation/home
<img width="550" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/48207765/6be97341-be13-4a64-bc60-9bd54f9696a4">

### Environment data

```PowerShell
Sponsored
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev
