### ISSUE TITLE
[Feature Request]: Provide Secure Score data

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2168]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Pulling secure score data from 365 Graph and displaying it and if it's possible to retain the history too to see how the secure score has grown and shrunk over time would be absolutely fabulous

**Comment by KelvinTegelaar** [comment]
This is already done in BPA, and using custom BPA reports you can create history.

**Comment by techiemate** [comment]
Sorry, what is BPA?
________________________________
