### ISSUE TITLE
[Feature Request]: Offboarding rollback of user

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2169]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Allow an option within X number of days after completing offboarding of a user to rollback all actions that CIPP did to reinstate the user

**Comment by KelvinTegelaar** [comment]
As CIPP doesn't save the state of any offboarding and wont we won't be able to do this.
