### ISSUE TITLE
[Feature Request]: CIPP docs, add a little video logo next to the article if it has video in it and allow to filter for articles with videos

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2170]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I noticed from LinkedIn posts that some videos have been added to documentation. I clicked on the first 10 articles and couldn't find them so thought rather than clicking on 10s of articles one by one, it would be nice to see a little video logo or a filter or both to see which articles have videos in it.

**Comment by KelvinTegelaar** [comment]
The videos are spread out over the text documentation, for example in the SAM wizard: https://docs.cipp.app/setup/installation/samwizard

The videos simply contain the text of the document in video form.
