### ISSUE TITLE
[Feature Request]: Bulk user creation from csv file

### ISSUE THREAD

**Issue by ChrisEnvisage** [KelvinTegelaar/CIPP#2171]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Recently we needed to create 122 new user accounts. Using a CSV template would be much more efficient for this.
I picture this as each field being individually filled in for each user and blanks being skipped.
Copying from existing users would be useful for most cases.
Another column that applies groups on top or instead of the copied user would make this a flexible for many use cases

**Comment by KelvinTegelaar** [comment]
First part, absolutely, the last however is a case of "What colour would you like your dragon to be"

Planned for implementation :)

**Comment by KelvinTegelaar** [comment]
Added to dev
