### ISSUE TITLE
[Feature Request]: Manage App Protection Policies in CIPP

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#2172]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The ability to manage application protection policies. This is particularly useful for devices that need application / data protection, but not necessarily require full device management (BYOD use-cases)

Currently managing this via direct tenant admin through Endpoint Manager -> Endpoint Security -> Apps -> App Protection Policies

**Comment by KelvinTegelaar** [comment]
Added in dev.
