### ISSUE TITLE
[Feature Request]: Conditional Access User Group Variables

### ISSUE THREAD

**Issue by SuperGaco** [KelvinTegelaar/CIPP#2173]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It is best practice to assign Conditional Access policies to groups, rather than all users, especially for exclusions. An example of this would be exclude the BreakGlass Admin User Group, which is something I use personally in every policy. The problem is that O365 only allows you to specify Groups by the UUID, which is unique in every tenant. 

The ability to have a drop down while applying the CA templates to list the available groups to exclude and include would be huge. Especially if it can be applied to Group Templates, as that would allow CA Policy templates to be used in the Standard.

Currently, I manage this by going to the Endpoint Admin Portal, and importing each policy, and then selecting the groups there.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
