### ISSUE TITLE
[Feature Request]: Sharepoint reports

### ISSUE THREAD

**Issue by ruffmeister69** [KelvinTegelaar/CIPP#2179]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Ability to pull off permission reports from sharepoint as to whom has access to what sites and export to a csv if possible

### PowerShell commands you would normally use to achieve above request

Connect-PnPOnline

**Comment by KelvinTegelaar** [comment]
only sponsors can create FRs, and very incomplete.
