### ISSUE TITLE
Enhancement: Add select All/Select None to Standard apply Wizard

### ISSUE THREAD

**Issue by DarrenChap** [KelvinTegelaar/CIPP#218]
Minor issue.  I tend to apply one standard at a time to multiple tenants.  Unticking all the standards in Step 2 of the "Standard apply Wizard" is a bit of a pain.  Would be great if there was a Select All toggle the same as in Step 1 of the same wizard.

![image](https://user-images.githubusercontent.com/47539594/140667736-1279c0e8-7b41-40b4-82d6-ee02e200064d.png)

**Comment by gavsto** [comment]
I actually think these should all be unticked by default. I am not sure then there'd be a need for a select all box. @KelvinTegelaar what do you think?

**Comment by DarrenChap** [comment]
Yes, that would work.  I think it is probably pretty risky/brave/stupid to apply all of them all at the same time even if I only select a single tenant.

**Comment by KelvinTegelaar** [comment]
Fixed in dev

**Comment by KelvinTegelaar** [comment]
Sidenote; there is still a minor bug I wil fix, when using select all it also selects the standards. Will get their own class to prevent.
