### ISSUE TITLE
[Feature Request]:  CA policy/Intune Device Management template with dynamic variables (Such as Group/Location)

### ISSUE THREAD

**Issue by chetayone** [KelvinTegelaar/CIPP#2184]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

**Want:** Ability to add dynamic GUIDs/variables such as groups pushed out via the group template to link to the Conditional Access and Device configuration templates.

**Explanation:**
Currently, there is no way to template a tenant rollout that doesn't require manual GUID updates per tenant as far as I can tell (I have mentioned this in the discord with no response so assumed you cant).

1. Currently no ability to create group templates at an all-tenant level
2. CA template does not support dynamic GUIDs/variables 
3. Device Configurations - looks like it might support variables but documentation is unclear and looks like it would run into the same issue of not being able to assign a unique GUID

 
**Benefit:**
The idea would be that an MSP can quickly onboard and standardize new tenants or update/upgrade existing tenants via the template system.

Script dump below (p.s please dont judge my code im self taught haha)

### PowerShell commands you would normally use to achieve above request

**Create Group**
``` 
$Group1 = Invoke-RestMethod -Method Get -Uri "https://graph.microsoft.com/beta/groups/?`$filter=startswith(displayName,'CA_MFA_Exclusions')" -Headers $authHeader
if ($($Group1.value.id))
{
Write-Host "Group CA_MFA_Exclusions Already Exists!" -ForegroundColor $Output
}
else {
    

$JSON = @"

{
    "description": "Conditional Access MFA Excluded Accounts",
    "displayName": "CA_MFA_Exclusions",
    "mailEnabled": false,
    "mailNickname": "false",
    "securityEnabled": true
}

"@

Invoke-RestMethod -Method Post -Uri "https://graph.microsoft.com/beta/groups/" -ContentType 'Application/JSON' -Headers $authHeader -Body $JSON | Out-Null
Write-Host "Group CA_MFA_Exclusions Successfully Created" -ForegroundColor $Output
}
```
**Create CA with called Group GUID**
``` $JSON4 = @"
{
    "displayName": "BLOCK: Legacy Authentication",
    "state": "disabled",
    "sessionControls": null,
    "conditions": {
        "userRiskLevels": [],
        "signInRiskLevels": [],
        "clientAppTypes": [
            "exchangeActiveSync",
            "other"
        ],
        "platforms": null,
        "locations": null,
        "deviceStates": null,
        "devices": null,
        "clientApplications": null,
        "applications": {
            "includeApplications": [
                "All"
            ],
            "excludeApplications": [],
            "includeUserActions": [],
            "includeAuthenticationContextClassReferences": []
        },
        "users": {
            "includeUsers": [
                "All"
            ],
            "excludeUsers": [],
            "includeGroups": [],
            "excludeGroups": [
                "$($Group1.value.id)"
            ],
            "includeRoles": [],
            "excludeRoles": []
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "block"
        ],
        "customAuthenticationFactors": [],
        "termsOfUse": []
    }
}
"@

Invoke-RestMethod -Method Post -Uri "https://graph.microsoft.com/beta/identity/conditionalAccess/policies" -ContentType 'Application/JSON' -Headers $authHeader -Body $JSON4 | Out-Null
```

**Comment by KelvinTegelaar** [comment]
Can you be a little more verbose Hooch

**Comment by KelvinTegelaar** [comment]
as this is already on the roadmap, closing :)
