### ISSUE TITLE
Modify User loads wrong username, replaces with alias

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#2188]
### Description

1.) Load a user /identity/administration/users/edit, 2.) Compare username to Microsoft Admin center. 

In some situations, an email alias is loaded into the username field instead of the user's login username. If a change to the user account is made, in my situation a license was added, when the Edit User button is pressed to save the change, the user's login username is also changed in Microsoft.
![Login Changed](https://github.com/KelvinTegelaar/CIPP/assets/93686819/eedf4fb9-1308-4f24-bf7e-6548229280e2)

### Environment data

```PowerShell
Sponsored
Backend version: 5.2.1
Frontend version: 5.2.1
Tenant Cache Cleared: true
Token Cach Cleared: true
```

**Comment by JeremyMcM** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug; Microsoft no longer supports having a different username than the primary SMTP address. If you **must** have a differencve between the two, you **must** setup ADFS with alternate login ID

![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/6ac943b1-635e-495d-8680-fcc10bfa69fe)


This would happen in any Graph portal, and is not unique to CIPP.
