### ISSUE TITLE
[Feature Request]: New Report: Username Discrepancy

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#2189]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

A new report that shows users across tenants that have a mismatch between their "userPrincipalName", their "mailNickname" and their "mail" values. With Microsoft's recommended best practices now requiring the UPN and primary SMTP address match, there are users with name changes, typo corrections and for other reasons may be in "not supported" status because of these discrepancies. If the report had a link directly to the user's /identity/administration/users/edit form and the form was modified to allow editing of the "mailNickname" value and also raised a red flag of some kind when the "mailNickname" and current value do not match their username, this would also prevent unknowingly changing the user's Login ID when the edit form was loaded through other means.

This would help MSPs keep their client tenants in line with Microsoft best practices and would help eliminate customer friction if a login name was inadvertently changed by them during other routine user account changes.

![Discrepancy Report](https://github.com/KelvinTegelaar/CIPP/assets/93686819/c5419cbf-2734-4122-ac6e-de70af3522b1)

**Comment by KelvinTegelaar** [comment]
I like this. Big red box, maybe not allow an edit until they match or have a second confirm.

**Comment by KelvinTegelaar** [comment]
added in dev.
