### ISSUE TITLE
[Feature Request]: Ability to View Expired Subscriptions in License Report

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2190]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I suspect that there may be a little delay before Microsoft's system has a refreshed nextLifecycleDateTime on the License Report. 

CIPP appears to filter out anything that has a nextLifecycleDateTime in the past. But Microsoft has some grace period and their nextLifecycleDateTime isn't always completely up-to-date it would be helpful for CIPP to show subscriptions even if they are technically reporting past the nextLifecycleDateTime. 

### PowerShell commands you would normally use to achieve above request

$LicOverviewRequest = New-GraphGetRequest -uri 'https://graph.microsoft.com/beta/directory/subscriptions' -tenantid $TenantFilter | Where-Object -Property nextLifecycleDateTime -GT **(Get-Date [minus 30 days])**

**Comment by KelvinTegelaar** [comment]
Resolved in dev.
