### ISSUE TITLE
[Feature Request]: Detect Pseudo-Anonymized Values on Mailbox Statistics Report

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2191]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

On the mailbox statistics report, either include a note and link prominently at the top of the page to https://docs.cipp.app/troubleshooting/frequently-asked-questions#my-usernames-or-sites-are-guids-or-blank

Or use regex to detect when the report is returning pseudo anonymized data and only display such a warning if so.

This is one of the most frequently asked questions, and this kind of warning could cut down on support requests from new CIPP users.

**Comment by KelvinTegelaar** [comment]
added in dev.
