### ISSUE TITLE
[Feature Request]: Create GDAP invite via API

### ISSUE THREAD

**Issue by enthus-csp** [KelvinTegelaar/CIPP#2193]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi, i want to create a new GDAP invite link via API.
https://CIPPURL.com/api//ExecGDAPInvite

I use this and use 
Invoke-RestMethod -Uri "$CIPPAPIUrl/api/ExecGDAPInvite" -Method POST -Headers $AuthHeader -ContentType "application/json" -Body $gdaproles

with the variable:

$gdaproles = '{"gdapRoles":[
    {
        "GroupName": "M365 GDAP Intune Administrator - enthus-csp",
        "GroupId": "1fa0023b-c90b-4639-a890-3f957e3e133c",
        "RoleName": "Intune Administrator",
        "roleDefinitionId": "3a2c62db-5318-420d-8d74-23affee5d9d5"
      }
]}'

but its getting me a Error create GDAP relationsship.

29.02.24, 13:34
None
None
CIPP
Created GDAP Invite - https://admin.microsoft.com/AdminPortal/Home#/partners/invitation/granularAdminRelationships/e048030c-be2a-4858-a5e1-bcae90404a5e-100191a4-b2b4-4661-991f-17f1c9000383
Z_CIPPHttpTrigger
Info
29.02.24, 13:34
100191a4-b2b4-4661-991f-17f1c9000383
None
CIPP
Error creating GDAP relationship: You cannot call a method on a null-valued expression.

**Comment by KelvinTegelaar** [comment]
This is a support request. Only sponsors get support
