### ISSUE TITLE
Unable to template Bitlocker Settings Catalog

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#2194]
### Description

Our setup relies on Bitlocker Settings Catalog (there are a number of items in here that are not present in the outdated Admin Templates). Therefore we would like to be able to template and apply Bitlocker policies as a standard (under the Endpoint security blade in InTune).

While creating the template from an existing policy does not generate an error, trying to apply it results in the following error:

`Failed to add policy for org: Property children in payload has a value that does not match schema.`

I tried creating the template using Settings Catalog / Device Configuration instead and it results in the same error, so it's not specific to the Endpoint Security blade.

I also tried extracting using Graph X-Ray and [InTune Management](https://github.com/Micke-K/IntuneManagement) and both result in errors about mismatched `odata` properties.

Hoping this can be added / fixed so we don't have to manually configure Bitlocker for every new client - it's a time-consuming and error-prone process that can break things if the settings aren't done exactly correct.

Thank you,

### Environment data

```PowerShell
- Sponsored: yes
- Front end version number: 5.2.1
- Back end version number: 5.2.1
- Tried Tenant Cache Clear: n/a
- Tried Token Cache Clear: n/a
```

**Comment by KelvinTegelaar** [comment]
Not a bug. @joeldeteves Contact support and they'll help you make the template :)

**Comment by joeldeteves** [comment]
Hi @KelvinTegelaar Woody and I already worked on this in the Discord and we weren't able to get the template working no matter what.

I can send you the template settings if you want to see for yourself.
