### ISSUE TITLE
Duplicate Licenses during "New User" setup.

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2196]
### Description

When adding a new user and selecting a license, there is a duplication for several licenses. Selecting one, selects the duplicate too.

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/84d52737-a82d-4596-a56c-2a64dcde37d3)

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/06734dd9-011f-4e87-8f89-4513b238daa3)

### Environment data

```PowerShell
Self Hosted 
Latest: 5.2.1 (Both back and front ends)
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Resolved in dev
