### ISSUE TITLE
[Feature Request]: Ability to toggle the MessageCopyForSentAsEnabled and MessageCopyForSendOnBehalfEnabled for Shared Mailboxes

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#2197]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Many customers user Shared Mailboxes to share responsibility for incoming and outgoing communications. Oftentimes someone would like to see the sent items another employee sent from that mailbox. The default behavior is for the sent item to be stored in the "Sent Items" folder of the user who sent the message. Unfortunately, that means others cannot see these communications. Microsoft 365 does have the option to store these messages in the Shared Mailbox's "Sent Items" folder instead of the sending user's, but toggling that setting is not available through the Admin Center UI.

Having the ability to toggle the MessageCopyForSentAsEnabled and MessageCopyForSendOnBehalfEnabled settings for Shared Mailboxes would allow an MSP to fulfill these requests easily.

I would envision the feature being added under [EMAIL & EXCHANGE > Mailboxes] with either a new "tab" for mailbox settings in the edit page or a menu option in the "three dot" menu from the list of mailboxes.

### PowerShell commands you would normally use to achieve above request

Similar code to change the MessageCopyForSentAsEnabled value can be found on Cyberdrain.com here: https://www.cyberdrain.com/documenting-with-powershell-increasing-the-office365-secure-score/

**Comment by kris6673** [comment]
We have a standard for this: Set mailbox Sent Items delegation (Sent items for shared mailboxes)
Is that sufficient?

**Comment by JeremyMcM** [comment]
The option you mention allows a user to be granted "Send As" (and "Send on Behalf of" permissions but doesn't affect where the copy of the sent item ends up being stored. The requested feature/change will instruct Exchange Online to put the mail item into the "Sent Items" folder of the Shared Mailbox itself, instead of the sending user's "Sent Items" folder.

**Comment by kris6673** [comment]
No, unless I'm misunderstanding,the standard does what you are requesting. 😊
This is the code for it:
```powershell
New-ExoRequest -tenantid $Tenant -cmdlet 'Set-Mailbox' -cmdParams @{Identity = $_.GUID ; MessageCopyForSendOnBehalfEnabled = $True; MessageCopyForSentAsEnabled = $True } -anchor $username
```

**Comment by JeremyMcM** [comment]
Well, look at that! Yes, that fits the current need for sure.
