### ISSUE TITLE
Unable to save APIKey  in 'Application Setings' -> 'Extensions'

### ISSUE THREAD

**Issue by NVerheyen** [KelvinTegelaar/CIPP#2198]
### Description

When trying to enable any integration in  'Application Setings' -> 'Extensions' an error 'Failed to set configuration: The property 'APIKey' cannot be found on this object. Verify that the property exists and can be set. Linenumber: 46' appears. The data in the form does not get saved.

Reported the issue in 'cipp-community-help' subthread 'Cipp - Ninja' and some others are reporting the same issue.
![chrome_2024-03-07_08-42-06](https://github.com/KelvinTegelaar/CIPP/assets/117900680/fe08a84d-b3c5-4bb4-9804-fcc0af1fea5e)

### Environment data

```PowerShell
Non-sponsored instance
Frontend version 5.2.1
Backend API Version 5.2.1
Tried Tenant Casche Clear: True
Tried Token Cache Clear: True
```

**Comment by NVerheyen** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug - User error. If you require support you can sponsor.
