### ISSUE TITLE
Excluded Tenants List Needs Refresh After Adding Tenant

### ISSUE THREAD

**Issue by bionemesis** [KelvinTegelaar/CIPP#22]
**Describe the bug**
When adding a tenant to the Excluded Tenants list, the website doesn't automatically refresh, making it impossible to add another tenant.

**To Reproduce**
1. Go to Settings - Tenants.
2. Click Add Excluded Tenant and select a tenant.
3. After seeing the "Success" message, click Close.
4. The tenant isn't listed and if you click "Add Excluded Tenant" again you see the same "Success" message.

**Expected behavior**
After clicking Close after adding the tenant, the page should auto-reload to reflect the change and allow you to add a new tenant to the list.

**Comment by KelvinTegelaar** [comment]
Fixed, thank you for letting us know! :)
