### ISSUE TITLE
FEATURE REQUEST: Add display name prefix to offboarding user wizard

### ISSUE THREAD

**Issue by KazFraser** [KelvinTegelaar/CIPP#2202]
When offboarding users, we typically prefix their display name with "Archive - ", it would be amazing if the offboarding wizard had a text input that allowed the technician to do this as part of the archive instead of separately.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs

**Comment by KazFraser** [comment]
Apologies @KelvinTegelaar, the pricing states feature request "priority", not exclusivity, may be worth clarifying
![image](https://github.com/KelvinTegelaar/CIPP/assets/111716412/a8454d27-1370-4c46-95e8-c29df5d38e64)
