### ISSUE TITLE
[Feature Request]: Use {tokens} in Standards (and elsewhere?)

### ISSUE THREAD

**Issue by myitguycorp** [KelvinTegelaar/CIPP#2203]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would love to be able to use tenant tokens, e.g. {tenantname} or {tenantdomain}, when editing standards.

e.g. sending *all* security emails to the same generic@mycompany.com email means I'm going to receive a lot of generic Microsoft emails that fail to mention which Tenant this is about.

However, I if could specify that my Security Contact email is  {tenantdomain}@reports.mycompany.com, then each Tenant would end up delivering email to its own email address. I could then identify quickly which tenant this is for by looking at the recipient address.

Thanks!

**Comment by KelvinTegelaar** [comment]
Feature requests are only available to sponsors.
