### ISSUE TITLE
[CIPP-API] NinjaOne workflow file present

### ISSUE THREAD

**Issue by JustinGrote** [KelvinTegelaar/CIPP#2205]
### Description

This is a minor thing but there is a NinjaOne workflow committed to CIPP-API, it should probably be removed and put into whatever specific fork of that is required.

![image](https://github.com/KelvinTegelaar/CIPP/assets/15258962/4126c640-082f-45c8-b907-6604b7880519)

### Environment data

```PowerShell
Base Environment.
```

**Comment by JustinGrote** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, this is used for a specialized branch.
