### ISSUE TITLE
Email & Exchange - Transport - Transport templates - Can't delete a template

### ISSUE THREAD

**Issue by GhalanAutomation** [KelvinTegelaar/CIPP#2207]
### Description

When attempting to delete a transport rule, the action reports as successful, yet the rule remains in place.

![CIPP-TransportRulesDelete](https://github.com/KelvinTegelaar/CIPP/assets/148862003/66c7777d-25b7-4729-b8bc-5b8582ecf223)

**Logs:**
![CIPP-TransportRulesDeleteLogs](https://github.com/KelvinTegelaar/CIPP/assets/148862003/641821fc-adf6-4042-a4d7-55757d7bc4c4)

### Environment data

```PowerShell
Self Hosted 
Frontend: 5.2.1
Backend: 5.2.2
```

**Comment by KelvinTegelaar** [comment]
You have duplicated an ID, you'll have to go into the tables and delete the duplicate. This isn't a bug but user error.
