### ISSUE TITLE
Feature Request: Offboard user at specific time

### ISSUE THREAD

**Issue by Remmy-OSI** [KelvinTegelaar/CIPP#221]
Would it be possible to schedule a user offboarding, so that the actions occur at a specific time/date?
At the moment we rely on our helpdesk offboarding staff reactively or setting calendar reminders to do it at the right time. It would be great if we could complete an offboarding for a user in advance.

**Comment by lwhitelock** [comment]
I like this, we could hook into the notification timer, or even add another 15 min timer for it. Main problem I see is we need to store the PII of the user(s) until they are offboarded.

**Comment by gavsto** [comment]
@lwhitelock All we need really is a user ID and a time. Doesn't need PII - I do agree I also like this idea.

**Comment by KelvinTegelaar** [comment]
Planned for v1.5

**Comment by zenmechanic** [comment]
Oh I like this a lot. Cant count the number of Friday at 5 terminations that kept me at the office for an hour disabling accounts, resetting sessions, revoking 2fa, removing from groups and teams and sites, converting to shared mailbox, setting OOO, email forward, etc.

**Comment by KelvinTegelaar** [comment]
Nixed for this release. There's an issue with how we've approached some things in the backend that need to be resolved first.
