### ISSUE TITLE
Typo: Add Alert Rule - Return set alert message

### ISSUE THREAD

**Issue by freezscholte** [KelvinTegelaar/CIPP#2211]
### Description

When setting up a Alert Rule and choose execute this: Store the log into an azure storage account you get get the message below when confirming. So looks like an typo since its not a webhook.

![image](https://github.com/KelvinTegelaar/CIPP/assets/52416805/dff63067-9120-48e5-af67-953e0b4b3482)

### Environment data

```PowerShell
Non-sponsored
Frontend: Latest: 5.2.1
Backend: Latest: 5.2.2
Tenant Cache clear: false
Token cache clear: false
```

**Comment by KelvinTegelaar** [comment]
This is not a typo - It creates a webhook subscription at Microsoft. :)
