### ISSUE TITLE
[Feature Request]: Deploy and manage compliance policies

### ISSUE THREAD

**Issue by easywaveio** [KelvinTegelaar/CIPP#2212]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I think it would be nice to add the ability to "add and manage compliance policies" from CIPP. It would also make perfect sense to integrate into "Standards" the same way we manage configurations policies. This would make creating baseline compliance for Autopilot devices etc much easier.

**Comment by KelvinTegelaar** [comment]
added compliance policy management to templates.
