### ISSUE TITLE
User edit - TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2220]
### Description

This is since upgrading tot 5.3.0 (in our dev environment), for all tenants

1) Go to Identity management > Users and click on the pencil/edit user button

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/6ebfdc81-1c6d-4fe0-8504-c52900dbcf2c)

### Environment data

```PowerShell
Sponsored instance
Front end version number: 5.3.0
Back end version number: 5.3.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by toroth83** [comment]
Just updated, we are also having this issue.

**Comment by 360it-reg** [comment]
Awesome!

**Comment by 360it-reg** [comment]
I'm still receiving this error (or similar one) on the user edit page. Does the hotfix need to be applied manually?
