### ISSUE TITLE
Users list - "hasArchive" column cannot be hidden

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2223]
### Description

Go to Identity Management > Users, click on button to change the columns
There is no item for the "hasArchive" column, so it cannot be hidden. In below example, I disabled all selected columns, but the "hasArchive' is still show (as there is nothing to disable):

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/59554676-e008-4f90-b86f-d7de3d2945de)

### Environment data

```PowerShell
Sponsored instance
Front end version number: 5.3.0
Back end version number: 5.3.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, this is caused by cookies in your browser in between updates.
