### ISSUE TITLE
[Feature Request]: Create Dynamic Distribution Groups using Cipp

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#2224]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

on groups, we added the ability to create Dynamic Groups, but it seems like now its just Dynamic Security Group, is there a way to create Dynamic Distribution Group please as well?

**Comment by KelvinTegelaar** [comment]
So we can create them, we just can't show them. This is kinda sad but MS likes making things hard for us: https://learn.microsoft.com/en-us/answers/questions/376906/does-graph-api-support-dynamic-distribution-lists

I've added it in CIPP for now, with the note that it's beta until we get them visible too.
