### ISSUE TITLE
Viewing User under All Tenants redirects to a different user in a different tenant

### ISSUE THREAD

**Issue by kevs18** [KelvinTegelaar/CIPP#2225]
### Description

1)Identity management > Administration > Users
2)Click on any user
3)Redirects to wrong user

Confirmed by other discord user he saw the same issue.

### Environment data

```PowerShell
Non-sponsored instance Front end version number: 5.3.1 Back end version number: 5.3.0 Tried Tenant Cache Clear: true Tried Token Cache Clear: true
```

**Comment by kevs18** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev

**Comment by kevs18** [comment]
> Fixed in dev

Still happening in today's update. Was the fix pushed or is it planned for a future release?
