### ISSUE TITLE
FEATURE REQUEST: Bulk Add Guests/Members into a Group with the Global Admin Role

### ISSUE THREAD

**Issue by Intellium-Technology** [KelvinTegelaar/CIPP#2227]
Could we please request a feature in CIPP to bulk invite guests, add them to a Group which then has the Global Admin Role?

Consider the following scenario:

We've recently migrated all our customer relationships from DAP to GDAP.
And as expected, this has now limited or 'broken' our ability to use our invited guest accounts to perform certain workloads like create an Azure VM because the Global Admin role cannot be used alongside our GDAP roles.

So, we are now exploring the 'Tenant Isolation' or 'Client Isolation' practice as per:
https://learn.microsoft.com/en-us/partner-center/csp-security-best-practices#identity-isolation

To achieve this, we are now setting up a separated tenancy ie 'ClientMSP.onmicrosoft.com'
This will have have our named members ie:
member1@ClientMSP.onmicrosoft.com
member2@ClientMSP.onmicrosoft.com
etc
This tenancy will strictly be used only to path into our customers. No GDAP. No CSP licensing.

We then need to invite each member to our customer tenancies, eg Customer1@onmicrosoft.com will have each member as:
member1_ClientMSP.onmicrosoft.com#EXT#@Customer1.onmicrosoft.com
member2_ClientMSP.onmicrosoft.com#EXT#@Customer1.onmicrosoft.com
etc

And each member will then be granted the Global Admin Role so our senior engineers can now perform their required duties.

The challenge is having to 'do' each invite at the customer tenancy level, at the guest level, and at the role level. Rinse/repeat across all our customer tenancies!

Thanks!
Allan @ Intellium Technology

**Comment by KelvinTegelaar** [comment]
No, we're never allowing this. This would decrease the security for everyone around. It's ill advised to have Global Admins that are guest in so many ways. This is exactly why GDAP was created. You might want to look into Azure Lighthouse, which will allow you to use your GDAP environment to manage and create VMs, and get the right permissions.

**Comment by Intellium-Technology** [comment]
Thanks for the quick reply.

We shall explore Azure Lighthouse.

Out of my further curiosity and understanding, have I misunderstood Microsoft's 'isolation' practice?
