### ISSUE TITLE
CIPP Front end wont update

### ISSUE THREAD

**Issue by Intellium-Technology** [KelvinTegelaar/CIPP#2228]
### Description

We are having issues updating out Frontend

Tried to sync the fork. Even gone as far as recreating the token now following the below steps:
static web app instance > Manage deployment token > reset
grab the new token 
go to github
go to the CIPP FRONTEND repo for your org
go to settings up the top 
go to secrets and variables > actions
Add new repo secret and paste that new token in

Fork shows as up to date but CIPP frontend shows out of date.

Any ideas?

### Environment data

```PowerShell
Sponsor
Front end version - Current: 5.2.1
Back end version - 5.3.0
CIPP url - https://cipp.intellium.co.nz/
CIPP Github - https://github.com/Intellium-Technology/CIPP
CIPP API Github - https://github.com/KelvinTegelaar/CIPP-API
```

**Comment by Intellium-Technology** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by Intellium-Technology** [comment]
<img width="172" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/160548772/deeaf454-1b2f-4b87-9d28-39cc833f7164">
<img width="456" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/160548772/5039b90d-748b-427c-a557-5aa815d2c048">

**Comment by KelvinTegelaar** [comment]
Nog a bug but support issue, if you are a sponsor please contact the helpdesk. The information for the helpdesk was in your welcome email :)
