### ISSUE TITLE
CA Policy keeps being duplicated (Continuous Access Evaluation)

### ISSUE THREAD

**Issue by easywaveio** [KelvinTegelaar/CIPP#2230]
### Description

If you create an Conditional Access policy that uses "Continuous Access Evaluation" from the "Sessions" tab it keeps getting redeployed every 3 hour if you deploy it via "Standards".

I don't know if this is also an issue if you select any of the other options under "Sessions". I have only tested this with "Continuous Access Evaluation". If I remove it from the policy it's working fine.

### Environment data

```PowerShell
Backend Version: 5.3.0
Frontend Version: 5.3.1
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true 
Restart Function App: true
```

**Comment by easywaveio** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Please share your JSON template

**Comment by easywaveio** [comment]
> Please share your JSON template

Of course, here you go:

`{
  "conditions": {
    "signInRiskLevels": [],
    "userRiskLevels": [],
    "clientAppTypes": [
      "all"
    ],
    "devices": null,
    "locations": null,
    "times": null,
    "applications": {
      "includeUserActions": [],
      "includeApplications": [
        "All"
      ],
      "includeAuthenticationContextClassReferences": [],
      "excludeApplications": [],
      "applicationFilter": null
    },
    "platforms": {
      "includePlatforms": [
        "windows",
        "macOS",
        "linux"
      ],
      "excludePlatforms": [
        "android",
        "iOS",
        "windowsPhone"
      ]
    },
    "clientApplications": null,
    "users": {
      "excludeGroups": [],
      "includeGuestsOrExternalUsers": null,
      "includeRoles": [],
      "includeGroups": [],
      "includeUsers": [
        "All"
      ],
      "excludeGuestsOrExternalUsers": {
        "guestOrExternalUserTypes": "serviceProvider",
        "externalTenants": {
          "@odata.type": "#microsoft.graph.conditionalAccessEnumeratedExternalTenants",
          "members": [
            "aa1edffe-307f-4d7a-bc02-2ca92513e52f"
          ],
          "membershipKind": "enumerated"
        }
      },
      "excludeUsers": [],
      "excludeRoles": [
        "62e90394-69f5-4237-9190-012177145e10"
      ]
    },
    "deviceStates": null
  },
  "id": "76b71e1c-5f92-466f-96da-d540f4bb5086",
  "state": "enabled",
  "createdDateTime": "2024-03-15T12:00:49.848524Z",
  "displayName": "EW: Users Enforce Continuous Access Evaluation",
  "modifiedDateTime": "2024-03-18T10:28:23.1406564Z",
  "sessionControls": {
    "cloudAppSecurity": null,
    "continuousAccessEvaluation": {
      "mode": "strictLocation"
    },
    "persistentBrowser": null,
    "applicationEnforcedRestrictions": null,
    "secureSignInSession": null,
    "signInFrequency": null,
    "disableResilienceDefaults": null
  },
  "LocationInfo": [
    null,
    null
  ],
  "GUID": "eade9aab-a77a-437e-89f4-54c7e988507a"
}`

**Comment by KelvinTegelaar** [comment]
Resolved in dev, will be releasing a hotfix for this.
