### ISSUE TITLE
[Feature Request]: New Standard for Cross-tenant access settings

### ISSUE THREAD

**Issue by gwenner-endsight** [KelvinTegelaar/CIPP#2233]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When M365 guests authenticate to our clients' tenants, by default they are subject to "double MFA" because our client's tenant doesn't trust the MFA of the guest's Entra tenant. This is now a configurable option in the Cross-tenant access settings, and we'd like it to be in the Standards.  The settings in the M365 GUI are described here: https://techcommunity.microsoft.com/t5/microsoft-entra-blog/cross-tenant-access-settings-notes-from-the-field/ba-p/4081841

I think having a choice in CIPP to enable or disable this setting explicitly would be preferred. 

Specifically, our organization would like to check the box to "_Trust multifactor authentication from Microsoft Entra tenants_", under the trust settings.  The PowerShell to do this should be available via the graph endpoint linked in the later question.  

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/graph/api/crosstenantaccesspolicyconfigurationdefault-update?view=graph-rest-1.0&tabs=powershell

Using this resource type: https://learn.microsoft.com/en-us/graph/api/resources/crosstenantaccesspolicyinboundtrust?view=graph-rest-1.0

And the **isMfaAccepted** property

**Comment by KelvinTegelaar** [comment]
I like it. Planned.

**Comment by KelvinTegelaar** [comment]
added in dev
