### ISSUE TITLE
Can't add policy template

### ISSUE THREAD

**Issue by easywaveio** [KelvinTegelaar/CIPP#2237]
### Description

I have one policy that I can't add to templates anymore. I have tried by manually import the JSON and via "Create template based on policy" button in CIPP. 

This policy worked as a template before, but after adding some extra settings from the "settings catalog" I can't get it to import into policy templates in CIPP anymore. Other policies still works fine, so there have to be one setting that breaks this one. I have tried to remove my last changes but still no go. 

I have attached the JSON, with all the settings as they should be.

[EW_ Hardening_2024-03-20T16_27_48.967Z.json](https://github.com/KelvinTegelaar/CIPP/files/14669882/EW_.Hardening_2024-03-20T16_27_48.967Z.json)

### Environment data

```PowerShell
Tenant cache clear: true
Reset/restart app: true
Tried manual import: true

Frontend: 5.3.1
Backend: 5.3.1
```

**Comment by easywaveio** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
This is a support issue, not a bug. Please contact the helpdesk for support issues.
