### ISSUE TITLE
Enable online archiving as a standard

### ISSUE THREAD

**Issue by etopple** [KelvinTegelaar/CIPP#224]
**Is your feature request related to a problem? Please describe.**
It would really save our team a lot of time and also provide more consistency if we could set enable online archive as a tenant standard via cipp.

**Describe the solution you'd like**
Simply knowing every single mailbox had online archive turned on would be great.

**Describe alternatives you've considered**
Manually doing it(which we are yuckk)

**Comment by AdamWillford** [comment]
Please can you touch on how you enable it currently for your existing tenants?  Is it a policy or a per user "enable" via compliance center?

FYI there is an existing "Archive" column on the Mailbox Statistics under Exchange which shows if it is enabled or not currently

**Comment by etopple** [comment]
At the moment we are mostly manually configuring this but my engineer just gave me this snippet that enables via posh. He said he'd pull a dev branch and look at if he could make the modification as well.

Get-Mailbox -Filter {ArchiveGuid -Eq "00000000-0000-0000-0000-000000000000" -AND RecipientTypeDetails -Eq "UserMailbox"} | Enable-Mailbox -Archive

**Comment by AdamWillford** [comment]
Thanks @etopple - confirms what I suspected.  We'll have to do a "select" feature on a users page.  There is a graph endpoint currently used to list the archive status that I'll see if it allows POST or not

**Comment by KelvinTegelaar** [comment]
After some troubleshooting I've found that with the current partner landscape this isn't possible. Enable-Mailbox is a protected cmdlet and you cannot run that as a delegated admin, only as a current admin. For now we'll close this request but revisit at a later date when this becomes possible.
