### ISSUE TITLE
[Feature Request]: Custom Name option for GDAP Invite Wizard

### ISSUE THREAD

**Issue by DMVGibson** [KelvinTegelaar/CIPP#2240]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When deploying a GDAP relationship invite, it currently states 

> "CIPP will create a single relationship with all roles you've selected for the maximum duration of 730 days using a GUID as a random name for the relationship".

 choosing the name of the relationship and being able to utilize a format or naming convention would allow for control when doing any kind of audit or reporting of relationships.

### PowerShell commands you would normally use to achieve above request

We are using the Microsoft GUI to submit these only because of this section of the GDAP Invite Wizard description: 

>  **using a GUID as a random name for the relationship.**

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs, and this is not a feature we'll implement
