### ISSUE TITLE
[Feature Request]: "Disable All Standards" toggle/button for temporary issues

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2241]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We've been having a lot of 500 errors with our CIPP instance due to Standards attempting to run on a few problematic client tenants.  We'd love an **easy** way to temporarily disable all standards across all tenants to prevent our CIPP instance from locking up so we can find and investigate issues like this without CIPP crashing.   I think this could help with many other scenarios for troubleshooting as well.  

Currently, I think the only options for stopping standards deployment are to either:
- Exclude all tenants, and then have to go back and re-_Include_ them later (we had to do this- this takes a long time to process for 500 tenants)
- Remove all the standards, and have to re-apply them manually later (hopefully took a backup or documented which settings we had!)

We'd love a button/toggle that disables all standards deployment across all tenants and when enable, it displays a banner or hint with a link to re-enable standards deployment. 

### PowerShell commands you would normally use to achieve above request

Invoke-Command "John's magic hands"

**Comment by KelvinTegelaar** [comment]
This isn't something we can implement, as it would require a rewrite of how standards work. Standards themselves also don't lock up an instance but issues with implementation do. As John is researching those this isn't something we're going to implement:)
