### ISSUE TITLE
[Feature Request]: Template Standards 

### ISSUE THREAD

**Issue by AbsaconIT** [KelvinTegelaar/CIPP#2259]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, in the Standards Setup section, we have the ability to define default standards for all tenants, and individual tenants. However, I believe it would be incredibly beneficial to introduce the option to utilize different templates such as Basis, Standard, and Strict.

Here's how it could work:

- Custom Templates: Introduce predefined templates like Basis, Standard, and Strict, each with varying levels of predefined standards and configurations.

- Flexible Application: Allow us to apply these templates directly to individual tenants, giving us the flexibility to tailor standards based on specific needs and requirements.

- Streamlined Management: By having these templates readily available within the Standards Setup, it would streamline the process of setting up standards for different tenants, ensuring consistency and efficiency.

- Enhanced Customization: we can still customize standards within these templates to further tailor them to their unique requirements, while benefiting from a structured starting point.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
