### ISSUE TITLE
[Feature Request]: API Endpoint for Azure App Secrets

### ISSUE THREAD

**Issue by gwenner-endsight** [KelvinTegelaar/CIPP#2260]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Expiring Azure app secrets has become a problem for us due to a lack of visibility and random apps that we don't know about expiring.
The alerting feature in CIPP is great, but like many organizations, mine tracks expirations and renewals for all software and hardware in a separate system. We'd like an API endpoint to be able to grab a list of Azure app secret names, their tenant name/id, and their expiration date.   This would allow us to sync all of the Azure app secret expirations to a separate system.  

### PowerShell commands you would normally use to achieve above request

CIPP already alerts on these so I assume you're pulling this data in some fashion.

**Comment by KelvinTegelaar** [comment]
You can use the `/api/ListGraphRequest` for this:

/api/ListGraphRequest
{
"tenantfilter": "mytenant.onmicrosoft.com"
"endpoint": "/applications'"
"$select": "id,passworcredentials"
