### ISSUE TITLE
[Feature Request]: Send Results to PSA on CA Vacation Mode

### ISSUE THREAD

**Issue by impact-computing** [KelvinTegelaar/CIPP#2261]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi Kelvin and John

When using CA Vacation mode to schedule in the CA exclusions, it would be very useful if the results could be posted back to a ticket (PSA) in same way that the Offboarding wizard does.

This would ensure that the audit trail in tickets is maintained and remove the need for manual checks of the CIPP scheduler.

Thank you.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
