### ISSUE TITLE
"Export Visible Columns" only exporting default columns

### ISSUE THREAD

**Issue by AdaptITAdmin** [KelvinTegelaar/CIPP#2267]
### Description

This applies to both of the following pages but I'm guessing the export functionality is shared
Identity Management -> Administration -> Users
Identity Management -> Administration -> Groups

When you change from the default set of columns on the portal and then select to Export Visible Columns for either PDF of CSV it will export the default set of columns.  
![image](https://github.com/KelvinTegelaar/CIPP/assets/119496392/bc4d8b75-4f85-4536-b573-85c8ad160f8a)

![image](https://github.com/KelvinTegelaar/CIPP/assets/119496392/1c121f73-b131-4f10-899d-5d01198e8f40)

It does not matter if you add more columns than default or remove columns as I have in the example.  Either way it exports the default set of columns.

### Environment data

```PowerShell
Sponsored instance
Front end version number: 5.3.2
Back end version number: 5.3.2
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
Restarted function app: true
```

**Comment by AdaptITAdmin** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
