### ISSUE TITLE
[Feature Request]: Different Standards

### ISSUE THREAD

**Issue by RiesebergFBB** [KelvinTegelaar/CIPP#2273]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Different Standards
We would like to set diffrent standards to diffrent tenants
Almost like with CA create diffrent standards templates to then apply to only the Tenants needed.
For Example if i set 3 diffrent standard template and i apply them to 3 diffrent Tenats it also would be good to be able to update the templates and then they will get updatet on daily bases to the tenants.

**Comment by KelvinTegelaar** [comment]
You can do this with the option "Do not apply all tenants standard" and selecting the tenants you want.
