### ISSUE TITLE
[Feature Request]: Define own SMTP Server for Notifications

### ISSUE THREAD

**Issue by jp-itt** [KelvinTegelaar/CIPP#2274]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have a Partner tenant just for the relationship and run our own tenant in another one. Therefore we do not have any licenses in the partnertenant and cannot create mailbox. This would be great, so I do not have to purchase anything in the partner.
Talking about: https://docs.cipp.app/user-documentation/cipp/settings/notifications

**Comment by KelvinTegelaar** [comment]
You dont need to buy anything, you canbget a trial to enable a shared mailbox and then let the trial expire, or create a shared mailbox using exchabge cmdlets and assign that new user to cipp and the gdap groups. We do not use smtp nor ever will.

**Comment by jp-itt** [comment]
great thank you! I have not thought of that.
