### ISSUE TITLE
Mail test: TypeError: i.MailAddresses.filter is not a function

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2284]
### Description

We've upgraded to the latest version and added the Mail.Read delegated permissions to the app registration. When going to the page "Tools > Mail test", we get the error below. This is happening for all tenants

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/c5d72dfa-3f0d-46b4-98b0-5d551f9174c3)

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.4.0
Back end version number: 5.4.2
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by JohnDuprey** [comment]
This is fixed in dev - in the meantime assign an alias email to the mailbox. There's another bug if there are no emails in the inbox, remedy this by sending an email to it.

**Comment by 360it-reg** [comment]
Thanks! I've added the alias and now its indeed working. Once the new version is released, I'll remove it again and test a new.
