### ISSUE TITLE
Device page is not sorted by default

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2286]
### Description

The page "Identity management > Devices" is not sorted by default. All other pages in Identity Management are default sorted on displayname. 

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/70fbef65-0f0c-4ef7-b6bb-3db4a5c0cd15)

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.4.0
Back end version number: 5.4.2
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Added sort by displayname

**Comment by 360it-reg** [comment]
Thanks!
