### ISSUE TITLE
Onedrive: PDF export is not sorted

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2287]
### Description

At "Teams & Sharepoint > Onedrive", reset the column layout to default and export visible columns to PDF. The PDF export is not sorted in anyway, while the page in CIPP is (on name)

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/8e1ac85d-9899-405c-a14d-ff5888ec8b9a)

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/9ae06b65-b773-42c3-a09f-9dfa4d0768b7)

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.4.0
Back end version number: 5.4.2
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by 360it-reg** [comment]
This is also happening on the export of the Sharepoint list page

**Comment by KelvinTegelaar** [comment]
Fixed, sort is now happening on UPN, which should resolve these issues.
