### ISSUE TITLE
Mailboxes: PDF export contains additionalEmailaddresses column and layout issues

### ISSUE THREAD

**Issue by 360it-reg** [KelvinTegelaar/CIPP#2288]
### Description

On "Email & Exchange > Mailboxes", when you hide the columns "Additional Emailadresses" in the view and then do a PDF export for All Visible Columns, the "Additional Emailaddresses" is still displayed. Also the layout has issues

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/1559ab46-2482-4626-a121-3aac6c4cb742)

![image](https://github.com/KelvinTegelaar/CIPP/assets/160752728/bdfffbdb-d261-40d8-94b8-885bb3417ffe)

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.4.0
Back end version number: 5.4.2
Tried Tenant Cache Clear: true 
Tried Token Cache Clear: true
```

**Comment by 360it-reg** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
solved in dev.

**Comment by 360it-reg** [comment]
Thanks!
