### ISSUE TITLE
[Feature Request]: Ability to view MFA options registered to the users

### ISSUE THREAD

**Issue by DVermeulen-i-LEVEL** [KelvinTegelaar/CIPP#2290]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be nice if we could view the MFA options registered to the users. Like Authenticator app, Authenticator app (passwordless), software OATH, hardware OATH, etc. 

The reason why we submit this FR is because when we're doing migrations or implementing CA we ask the users to set up MFA with an instruction that also includes passwordless authentication setup. To check if they set it up correctly we need to browse to the user registration details in Entra. 

Making this available in CIPP would help MSPs with migrations and implementations of MFA and also make reports of it.

**Comment by KelvinTegelaar** [comment]
discussed during cipp & sip, we'll implement this.

**Comment by KelvinTegelaar** [comment]
added optional field "MFAMethods".
