### ISSUE TITLE
When adding a new user, auto complete the Display Name

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#230]
**Is your feature request related to a problem? Please describe.**
When creating a new user the current admin centre behavior of auto populating the display name from first name + last name is missing.

**Describe the solution you'd like**
A little bit of javascript to auto populate on first / last name change unless it has been changed.

**Describe alternatives you've considered**
Copying and pasting.

**Other notes**
It would also be good to redirect to the all users view after creation rather than staying on the completed form

**Comment by KelvinTegelaar** [comment]
Staying on the completed form is a functional choice, it allows you to create multiple users in quick succession. Adding the autopopulate.

**Comment by KelvinTegelaar** [comment]
Enhancement added in dev.
