### ISSUE TITLE
[Feature Request]: Change Retention policy

### ISSUE THREAD

**Issue by MSOTec** [KelvinTegelaar/CIPP#2303]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Can chose the retention policy.

### PowerShell commands you would normally use to achieve above request

Set-RetentionPolicy and Get-RetentionPolicy

**Comment by KelvinTegelaar** [comment]
only sponsors can create frs
