### ISSUE TITLE
[Feature Request]: Report on group mailbox capacity

### ISSUE THREAD

**Issue by Grem66** [KelvinTegelaar/CIPP#2304]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

You can review the used/remaining capacity of a regular mailbox and shared mailboxes through web UIs, CIPP etc, but there is no way to report on group mailboxes (like one attached to a Team) via the usual methods (teams are just missing from CIPP when you run statistics) and MS locations such as exchange admin centre and teams admin centre don't report on it at all, and you have to run a powershell command to check the current status (see below)

### PowerShell commands you would normally use to achieve above request

Get-MailboxStatistics <groupname> | ft TotalDeletedItemSize,TotalItemSize

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
