### ISSUE TITLE
Tenant Onboarding wizard failed

### ISSUE THREAD

**Issue by toddjcrane** [KelvinTegelaar/CIPP#2308]
### Description

Tenant Onboarding wizard for new relationship fails on step 3. Step 4 of which (CPV Refresh) is stuck on a spinning icon. Logs show the following error.

Cannot bind parameter 'Context'. Cannot convert the "System.Collections.Hashtable" value of type "System.Collections.Hashtable" to type "PipeHow.AzBobbyTables.AzDataTableContext".

### Environment data

```PowerShell
self-hosted CIPP commit 57d0bf6; CIPP-API commit 984d3cf
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev. :)
