### ISSUE TITLE
FEATURE REQUEST: Add DLP Policies and Alerts into CIPP

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#231]
**Is your feature request related to a problem? Please describe.**
I would like to see DLP policies and alerts in CIPP. It would be double great if we could see alerts across all clients

**Describe the solution you'd like**
A place to see DLP alerts that have triggered and DLP policies in place

**Describe alternatives you've considered**
Logging in to the Admin portal? YOU JOKER!

**Comment by KelvinTegelaar** [comment]
This one is pretty terrible, SCC is blocked for most newer partners so getting DLP policies is nigh-impossible with SAM. I haven't found any other APIs for it except maybe the security center API introduced for MSSPs, but I don't even know if DLP data is streamed there.

**Comment by KelvinTegelaar** [comment]
current not possible. Closing but will revisit in future.

**Comment by itworkscomputer** [comment]
Can this be revisited please?

**Comment by KelvinTegelaar** [comment]
> Can this be revisited please?

Sponsors can create feature request. Feel free to sponsor and make a feature request.
