### ISSUE TITLE
Domain Error, check permissions

### ISSUE THREAD

**Issue by Cloud-CBM** [KelvinTegelaar/CIPP#2312]
Hi,

We have "Domain Error, check permissions" error for a small handful of tenants and having trouble figuring out how to solve the issue.  We tried CPV refresh and we get the following message.

- We've already added our Service Principal to *client name*
- Added 0 Application permissions to

Would you be able to provide some insight on how to solve the issue?

Thanks,

Blake

**Comment by KelvinTegelaar** [comment]
This is a support issue - Support issues should be reported to helpdesk@cyberdrain.com if you're a sponsor. :)
