### ISSUE TITLE
[Feature Request]: CIPP Columns don't match

### ISSUE THREAD

**Issue by CrypNZ** [KelvinTegelaar/CIPP#2313]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

For example, under Intune > Device Management > Devices;

When filtering the columns, two of the columns is called "deviceName, managedDeviceOwnerType"
The corresponding columns in the table is "Name, Used by"

I get one will be a friendly name and that's why there is some differential - but would be handy to know which is which when going through the filter.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
