### ISSUE TITLE
[Feature Request]: Remove Global Admin from existing GDAP relationships

### ISSUE THREAD

**Issue by AdaptITAdmin** [KelvinTegelaar/CIPP#2315]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Microsoft have recently added the capability to remove Global Admin from a GDAP relationship in the partner portal.  

Removing Global Admin from existing relationships would allow partners to auto extend relationships that were created before it was announced that relationships would be extendable if they did not contain the global admin role.

The functionality in the partner portal is limited to 25 relationships at a time and the page for doing it is not very usable.

It would be great if an action to remove the Global Admin role from relationships could be added to the GDAP Management -> GDAP Relationships page with the ability for the action to be run against individual, multiple or all relationships.

### PowerShell commands you would normally use to achieve above request

unknown

**Comment by KelvinTegelaar** [comment]
Seems like Microsoft doesn't allow to do this with our default token, it has to be a web action. sorry :)
