### ISSUE TITLE
Cannot edit a user if New User Attribute Defaults is empty

### ISSUE THREAD

**Issue by ZomoXYZ** [KelvinTegelaar/CIPP#2316]
### Description

To replicate the issue:

- In the CIPP Dashboard, under Settings go to CIPP > User Settings
- Make sure there are no attributes set under New User Attribute Defaults
- In the CIPP Dashboard, Under Identity Management go to Administration > Users
- Click the Edit Action icon for a user

Expected behavior: The app should allow me to edit the user without having anything set in New User Attribute Defaults. Or, if New User Attribute Defaults is required, the error should be caught and this requirement should be displayed.

Error: Cannot read properties of undefined (reading 'reduce')

Error Location: TypeError: Cannot read properties of undefined (reading 'reduce') at Te (\[HOST\]/static/EditUser-Dsj5Psl_.js:1:2700) at JV (\[HOST\]/static/index-BPd03XSz.js:39:64291) at aD (\[HOST\]/static/index-BPd03XSz.js:39:76061) at Cve (\[HOST\]/static/index-BPd03XSz.js:39:117702) at bve (\[HOST\]/static/index-BPd03XSz.js:39:112868) at Rwt (\[HOST\]/static/index-BPd03XSz.js:39:112791) at m_ (\[HOST\]/static/index-BPd03XSz.js:39:112640) at vD (\[HOST\]/static/index-BPd03XSz.js:39:108984) at gve (\[HOST\]/static/index-BPd03XSz.js:39:107930) at C (\[HOST\]/static/index-BPd03XSz.js:31:1540)

![image](https://github.com/KelvinTegelaar/CIPP/assets/11318718/fdc774fd-db13-4859-a836-467c56422692)

Further investigation:

Error location maps to: ./src/views/identity/administration/EditUser.jsx:140:81

Commit 2e99c74e3af71b0c0222047695403f2f12460565 added the line at fault
Commit b08a54c2318a1f40f3da4bd7ebf9d4b9bfbec0e7 added some type safety checks

It appears the type safety checks are incomplete and do not check the last key in the line. The line `currentSettings?.userSettingsDefaults?.defaultAttributes.reduce()` will still throw an error in the following situation:

- `currentSettings` is an object
- `userSettingsDefaults` is an object
- `defaultAttributes` is null or undefined

So this error may be caused by the lack of `?` operator to check `defaultAttributes`. A safer option is `currentSettings?.userSettingsDefaults?.defaultAttributes?.reduce()` as this checks all three `currentSettings`, `userSettingsDefaults`, and `defaultAttributes`. Also, if the value should be an empty array by default instead of undefined, this could be safely done by appending `?? []` after `.reduce()`.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 5.4.2
Back end version number: 5.4.4
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Solved in dev

**Comment by ZomoXYZ** [comment]
Is there an ETA for the stable release of this?

**Comment by KelvinTegelaar** [comment]
Sponsors can ask support to deploy the hotfix to their environment, non sponsors will have to wait until we release. That could be tomorrow, or in 2 weeks from now.
