### ISSUE TITLE
FEATURE REQUEST: Add Phishing Policies in to CIPP

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#232]
**Is your feature request related to a problem? Please describe.**
Add phishing policies in to CIPP

**Describe the solution you'd like**
To be able to see phishing policies for a tenant, and ideally all phishing policies at once

**Comment by KelvinTegelaar** [comment]
Duplicate of the spamfilter request maybe?

**Comment by KelvinTegelaar** [comment]
Added in Dev
