### ISSUE TITLE
Settings not reported correctly thru CIPP Standards v1.0 report

### ISSUE THREAD

**Issue by CrestOfAKnave** [KelvinTegelaar/CIPP#2328]
### Description

Hi Kelvin and others,

It seems the status for "laps" is not reported correctly in the BPA->CIPP Standards v1.0 report, This setting is disabled in the tenant and graph explorer reports the status as false, yet the report shows this settings as enabled, see screen shots. Bug? Thanks!

![image](https://github.com/KelvinTegelaar/CIPP/assets/166439122/ce195c0c-27cc-4528-beda-3f35b1c945a8)
![image](https://github.com/KelvinTegelaar/CIPP/assets/166439122/b079b42a-b625-4008-ae51-713a068bb8ff)

### Environment data

```PowerShell
Non-sponsored (Currently Evaluating)
Frontend Version: 5.5.0
Backend API Version: API5.5.1

Tenant Cache Clear: true (tried numerous times)
```

**Comment by KelvinTegelaar** [comment]
This is more of a support issue, only sponsors can receive support :)

**Comment by CrestOfAKnave** [comment]
I see. The email alerts do show the correct status, so we'll use that for now. Thanks!
