### ISSUE TITLE
FEATURE REQUEST: See amalgamated security alerts for all tenants

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#233]
**Is your feature request related to a problem? Please describe.**
It would be really beneficial to be able to see ALL security alert in one view - preferably live.

**Describe the solution you'd like**
One screen with all security alerts

**Comment by gavsto** [comment]
Version Alpha is currently in dev.

**Comment by homotechsual** [comment]
@KelvinTegelaar I think this is done now with 2.0.1?

**Comment by KelvinTegelaar** [comment]
I think so, gavin still had worries on missing alerts, that i believe we can pull in with the new defender endpoints
