### ISSUE TITLE
[Feature Request]: Ability to add contacts as group member

### ISSUE THREAD

**Issue by jp-itt** [KelvinTegelaar/CIPP#2333]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Some clients use ("missuse) distribution groups as internal mailing list with either customers or close partners. At the moment we can create an external contacts via CIPP, but have to log into the tenant to add the contact to an existing group.

This would solve this issue.

---

It would also be great if we would be able to create a contact standard, so we can distribute our helpdesk contact to the customer automatically. (Name,Mail,Number)

---

Btw. I think the edit contact button is broken right now. At least for my hosted instance nothing happens when I press it.

**Comment by KelvinTegelaar** [comment]
You can already add contacts to distribution groups: 

![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/285939e9-d678-41fd-b13e-5eb7dad25e79)
