### ISSUE TITLE
[Feature Request]: Hide or change update notification message 

### ISSUE THREAD

**Issue by QNPICT** [KelvinTegelaar/CIPP#2337]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

CIPP displays a notification at the top of the screen when a new update is available. All our CIPP users receive this message. When we hosted CIPP ourselves, I would install the update to remove the notification. However, with the hosted version, it can take up to 48 hours to receive the update.

My coworkers keep messaging me to install the update.

Is it possible to implement one of the following options:

- Display the update notification only for Owners.
- Display the update notification along with an additional message indicating that it will be installed within 48 hours.
- Hide the update notification for CIPP hosted.

**Comment by KelvinTegelaar** [comment]
No - Normally speaking updates are installed within hours of launch, and this isn't something we're going to entertain as it will prevent people from updating entirely.
