### ISSUE TITLE
FEATURE REQUEST: See apps installed in a particular team

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#234]
**Is your feature request related to a problem? Please describe.**
Be able to see third party apps that are attached in individual teams in a tenant

**Describe the solution you'd like**
Ability to see apps that are installed across a tenant and per team

**Comment by KelvinTegelaar** [comment]
Teams overview is getting overhaul is 1.5 based on view user page. Planned for 1.5

**Comment by KelvinTegelaar** [comment]
The new Teams view page has this in dev.
