### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Converge-IT** [KelvinTegelaar/CIPP#2340]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

copy user,
possibilty to copy a user or use an existing user as a template for a new user, eg all access permissions are copied, both teams access as (shared) mailbox access.

we get a lot of requests asking to reate a new user who can do the same as another user, but it's timeconsuming to get all the access permissions

### PowerShell commands you would normally use to achieve above request

/

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs

**Comment by Converge-IT** [comment]
we are a sponsor
