### ISSUE TITLE
[Feature Request]: Set User Enabled

### ISSUE THREAD

**Issue by kosli** [KelvinTegelaar/CIPP#2343]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The User list shows the "Enabled" status of a user (and allows filtering by it) and it would great if users could be enabled (in bulk). e.g. provide an action "Enable user"

I tried using the "Unblock signin" action which prompts "Are you sure you want to **enable** these users?" but the users have not been enabled afterwards.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
