### ISSUE TITLE
Unblock Sign In doesn't work for guest users

### ISSUE THREAD

**Issue by kosli** [KelvinTegelaar/CIPP#2345]
### Description

When using the Unblock Sign In function on an entra **guest** user it asks  for "Are you sure you want to enable this user?" but the guest user does not get enabled (cross checked via Azure Entra portal).

As soon as I enable the user in azure Entra portal the users shows as enabled in CIPP.

May be related to #2344 and #

### Environment data

```PowerShell
Sponsored
Frontend: 5.5.0 
Backend: 5.5.3
Tried Tenant Cache clear: false
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Resolved in dev.
