### ISSUE TITLE
Ability To Re-Order Favorites

### ISSUE THREAD

**Issue by dspengeman-stf** [KelvinTegelaar/CIPP#2347]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Looking to see a way to change the order of CIPP Favorites without having to delete and re-add them in a chronological order to get the list to be visible the way you want (Alphabetical, etc.).

### PowerShell commands you would normally use to achieve above request

N/A

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
