### ISSUE TITLE
[Feature Request]: Single table view for partner relationships

### ISSUE THREAD

**Issue by drb-sleptThruCS** [KelvinTegelaar/CIPP#2348]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Why: MSPs are really sloppy around removing previous partner relationships when they onboard new customers.

Create a single table view that let's me see all the partner relationships for my tenants, ideally leaving my MSP off (and maybe a toggle for our disti.) The use case would be to review for any old relationships that need to be removed. Talked to John and the data is already there.

Bonus: alert on these other relationships, especially if a new one shows up

### PowerShell commands you would normally use to achieve above request

I'm really bad at powershell, not going to embarrass myself here.

**Comment by KelvinTegelaar** [comment]
Feature requests can only be submitted by sponsors.

**Comment by KelvinTegelaar** [comment]
So no one saw me close this.

**Comment by KelvinTegelaar** [comment]
Added in dev
