### ISSUE TITLE
FEATURE REQUEST: Teams VOIP Reporting

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#235]
**Is your feature request related to a problem? Please describe.**
Be able to see an overview and information about Microsoft 365 Business Voice

**Describe the solution you'd like**
I'd like to be able to see things like a list of users who are using it, IVR details, DDIs, phone call info etc

**Comment by KelvinTegelaar** [comment]
Planned for v1.5

**Comment by KelvinTegelaar** [comment]
added in dev.
