### ISSUE TITLE
[Feature Request]: OneDrive Health Reports

### ISSUE THREAD

**Issue by daniel-reactcp** [KelvinTegelaar/CIPP#2353]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like the ability to pull in the OneDrive sync health reports, it currently seems under developed in terms of no ability to generate regular reports/alerts on this, from an MSP point of view I have to log into every tenant I want to check, being able to centrally collate these reports without having to sign in to every tenant would greatly improve it's useability 

![image](https://github.com/KelvinTegelaar/CIPP/assets/98557639/4baf938a-03e1-4113-b883-5a5a90a32818)

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
