### ISSUE TITLE
[Feature Request]: ORCA Report

### ISSUE THREAD

**Issue by cippzurichnetgroup** [KelvinTegelaar/CIPP#2355]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

With the Orca Report it is possible to check the anti-spam and anti-malware settings in an Office 365 tenant.

If this could be built into CIPP in a report or also in the BPA report to display the recommendations?
In addition, it should be possible to display the HTML report per tenant.

https://github.com/cammurray/orca

### PowerShell commands you would normally use to achieve above request

Get-ORCAReport

**Comment by KelvinTegelaar** [comment]
OCRA uses cmdlets not accessible via GDAP, so this is a no.
