### ISSUE TITLE
[Feature Request]: Standards Templates Amendments

### ISSUE THREAD

**Issue by chrisharris8** [KelvinTegelaar/CIPP#2358]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have been using the new feature of creating Standards templates and would like x2 potential features adding if possible.

1- A section to view your created templates in CIPP so that these can be modified or deleted

We can't see an option for this right now. It would be very useful to make small changes to existing templates or delete older ones

2- The ability to apply multiple Standards templates to one tenant. 

We would like to create Standards Templates for each of the sections (Entra, Exchange, SharePoint etc), then have the ability to apply multiple templates to the same tenant.  At the moment it seems that if we apply a template, then apply a second one, this overwrites the settings in CIPP. We'd like the possibility to see a list of all templates and apply the ones we want for that tenant, so we can be more granular with deployments. We will have some customers that may not want/require the Standards for some sections.

### PowerShell commands you would normally use to achieve above request

n/a

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
