### ISSUE TITLE
FEATURE REQUEST: Logical Groups for Tenant and Users with Access to CIPP

### ISSUE THREAD

**Issue by bearmerino** [KelvinTegelaar/CIPP#236]
We limit our techs to certain accounts to limit the amount of exposure we have as an organization to any one/group of our clients. We call these teams of people "Pods" and have clients assigned to Pods. 

By doing this we typically provide the necessary access and controls to a Pod which may also have some layers in it depending on the size of Pod and responsibilities. 

What I would like to see is the ability to assign users within one of these pods (admin, contributor, user) access to a grouping of tenants and that's all the access they have. I rarely need the ability for one pod to access another pod's clients but that could be secondary. The primary focus would be Client A, B, and C are in a classification "Client Pod 1" and My Techs 1, 2, 3  are part of POD1 which is assigned "admin role" to the tenants in Client Pod 1.

As a side benefit, we would then be able to open up CIPP to internal tenants as we have our internal environment assigned only to one of our PODs that are responsible for our internal tenant. I know this was a concern with the current setup of CIPP.

**Comment by KelvinTegelaar** [comment]
This has been discussed before, but doing this would mean tracking user groups, states, and storing  sensitive information. The risk vs reward is too high to allow this as one mistake could mean giving a user full access. Marking as "wontfix".
