### ISSUE TITLE
[Feature Request]: Meeting Rooms and Meeting Room lists

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2360]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

IIRC Microsoft's Implementation of this feature is pretty nasty and hidden.
I would like a better UI for querying and editing Meeting Rooms and the Meeting Room lists

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/graph/api/place-list

We would need `Place.ReadWrite.All` as `Delegated`

* Query and view Room `https://graph.microsoft.com/v1.0/places/microsoft.graph.room`
* Query and view List `https://graph.microsoft.com/v1.0/places/microsoft.graph.roomlist`
* Query and view Rooms under a list `https://graph.microsoft.com/v1.0/places/room@list.com/microsoft.graph.roomlist/rooms`
* View settings for a specific Room `https://graph.microsoft.com/v1.0/places/<RoomID>`
* View settings for a specific List `https://graph.microsoft.com/v1.0/places/room@list.com`
* Update (and create?) a Room
```
PATCH https://graph.microsoft.com/v1.0/places/<RoomID>
Content-type: application/json

{
  "@odata.type": "microsoft.graph.room",
  "nickname": "Conf Room",
  "building": "1",
  "label": "100",
  "capacity": 50,
  "isWheelChairAccessible": false
}
```
* Update (or create?) a List
```
PATCH https://graph.microsoft.com/v1.0/places/room@list.com
Content-type: application/json

{
  "@odata.type": "microsoft.graph.roomList",
  "displayName": "Building 1",
  "phone":"555-555-0100",
  "address": {
    "street": "4567 Main Street",
    "city": "Buffalo",
    "state": "NY",
    "postalCode": "98052",
    "countryOrRegion": "USA"
  },
  "geoCoordinates": {
    "altitude": null,
    "latitude": 47.0,
    "longitude": -122.0,
    "accuracy": null,
    "altitudeAccuracy": null
 }
}
```

**Comment by OfficialEsco** [comment]
Thinking of looking into this myself if i can wrap my head around how to implement a button for it, not 100% sure what category i could go under

**Comment by KelvinTegelaar** [comment]
Exchange -> Room Management?

**Comment by KelvinTegelaar** [comment]
added in dev. Great work Esco!
