### ISSUE TITLE
[Feature Request]: Ability to export, view and add Compliance Policies in Intune

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2364]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

For Microsoft Intune, the built in feature for marking devices as compliant, then utilising Conditional Access based on this compliance status is a big one for us for device security and data access for our customers.
We have over 30 customers utilising a pretty standard format, which is a pain to have to dial into each tenant manually and either run a custom PowerShell script/function or add manually each time we want to adjust.

This would be the same ability as the current Intune section in CIPP with the configuration profiles.

We are a sponsor under: FutureITNZ

**Comment by KelvinTegelaar** [comment]
Feature requests are only available to sponsors.

**Comment by KelvinTegelaar** [comment]
Hold on there bot, a little bit too fast.

**Comment by KelvinTegelaar** [comment]
![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/cbd0057a-2e11-475c-97e0-7943c361d4f0)
This already exists. :)
