### ISSUE TITLE
[Feature Request]: Ability to schedule the new secure score report as PDF in a printable format and send to customers email.

### ISSUE THREAD

**Issue by meanturtle** [KelvinTegelaar/CIPP#2377]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Ability to schedule the new secure score report as PDF in a printable format and send to customers email. 
The layout of the new secure score report is excellent to show customers their secure score and compare it to others with the description of each item that is being covered. Pressing print on the page displays this strangely unless I turn off margins but it also includes the top part and is not schedulable. 

We spend a lot of time manually creating the secure score review for each customer manually in the format similar that is displayed in cipp which with automation is very hard to get right. We then email this to the customer who stores this for compliance and for insurance purposes. I would imagine there are other msps have a similar procedure.

**Comment by KelvinTegelaar** [comment]
While we're never going to have the ability to e-mail end users, we are going to add this to an emailable report to the notification address(es), and maybe generate a PDF. :), so partially planned and on the roadmap.

**Comment by meanturtle** [comment]
thank you.
