### ISSUE TITLE
[Feature Request]: Standard: Set Office Release Preference

### ISSUE THREAD

**Issue by bpbmcs** [KelvinTegelaar/CIPP#2382]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Ability to set the office release channel such as to targeted or not would be great to add into the standards list. We typically always update to targeted and would be one less thing to have to manage separately.

This would benefit everyone just by being able to manage centrally in the standards section.

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/release-options-in-office-365?view=o365-worldwide&redirectSourcePath=%252fen-us%252farticle%252fSet-up-the-Standard-or-Targeted-release-options-in-Office-365-3B3ADFA4-1777-4FF0-B606-FB8732101F47

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
Whoops, wrong FR. I tried working on it a few months ago but could not figure it out :(

**Comment by KelvinTegelaar** [comment]
No API access to this, and MS is moving everyone over to monthly anyway in the next couple of months so seems like a moot point. :)
