### ISSUE TITLE
[Feature Request]: Standard - Quarantine Digest and Report Addon

### ISSUE THREAD

**Issue by bpbmcs** [KelvinTegelaar/CIPP#2383]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be really great to be able to set the quarantine digest email timeframe (ie. Within 4/hr) along with deploying/configuring the report email button/addon.

Right now this is a standard we always do and being one thing to set in CIPP and forget would really be great.

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
@bpbmcs Report Email button is already a standard fyi :)
![billede](https://github.com/KelvinTegelaar/CIPP/assets/31723128/176b5b54-17b2-42a6-b2ce-3860ef983308)

**Comment by bpbmcs** [comment]
Thanks, I missed somehow 👍
