### ISSUE TITLE
Compliance Policy Templates in Standards Duping

### ISSUE THREAD

**Issue by MWGMorningwood** [KelvinTegelaar/CIPP#2384]
### Description

1. Create a template of an intune compliance policy
2. Load template into intune template standard, set to remediate
3. Run standards more than once
4. (I believe) the lack of an `else` on lines 45/46 of [Invoke-CIPPStandardIntuneTemplate](https://github.com/KelvinTegelaar/CIPP-API/blob/a7296ba427e405e0caf0c0e70771c14eea817ad2/Modules/CIPPCore/Public/Standards/Invoke-CIPPStandardIntuneTemplate.ps1) is causing the function to add a new instance of the policy each time it runs.
![image](https://github.com/KelvinTegelaar/CIPP/assets/2997336/29e62e50-b622-46a4-94dd-5318158b0073)

### Environment data

```PowerShell
Sponsored
FE Ver: 5.6.1
BE Ver: 5.6.1
Cache clears: no
```

**Comment by MWGMorningwood** [comment]
I would like to work on this please!

**Comment by MWGMorningwood** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
That is absolutely right, and you deployed I fix. I think I might have a crush on you.

**Comment by MWGMorningwood** [comment]
Fix added in dev :D
hopefully I can keep em comin'.
