### ISSUE TITLE
[Feature Request]: Add PSTN telephone number to MS Teams Phone user

### ISSUE THREAD

**Issue by AADAutomatisering** [KelvinTegelaar/CIPP#2385]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

If you use a SIP Trunk and want to link the telephone number to a Teams user, this is currently only possible via Powershell.
If you want to do this for multiple users, this requires a lot of actions.
It would be great if in CIPP you could assign a phone number to a user via a UI.

### PowerShell commands you would normally use to achieve above request

Add phonenumber to user
Set-CsPhoneNumberAssignment -Identity [gebruiker@voorbeeld.com] -EnterpriseVoiceEnabled $true
Set-CsPhoneNumberAssignment -Identity [gebruiker@voorbeeld.com] -PhoneNumber +31******** -PhoneNumberType DirectRouting

https://learn.microsoft.com/en-us/powershell/module/teams/set-csphonenumberassignment?view=teams-ps

Add VoiceRoutingPolicy
Grant-CsOnlineVoiceRoutingPolicy -Identity [gebruiker@voorbeeld.com] -PolicyName "Calling"

https://learn.microsoft.com/en-us/powershell/module/teams/grant-csonlinevoiceroutingpolicy?view=teams-ps

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests

**Comment by Ovalis-IT-Manager** [comment]
+1 for this feature please
