### ISSUE TITLE
Even after applying the standard to change the anonymised data reporting - data is still anonymised.

### ISSUE THREAD

**Issue by danmansfield** [KelvinTegelaar/CIPP#239]
Applied the standard 2 weeks ago and still not showing the non-anonymised data.
Onedrive and sharepoint lists affected.

**Comment by danmansfield** [comment]
1.3.0 of both.

**Comment by gavsto** [comment]
Can you check in one of the client tenants directly to see if it is still enabled?

If it is still enabled then it's likely CIPP, if it isn't then it's something in MS365.

**Comment by KelvinTegelaar** [comment]
Also do a tenant check via configuration settings for the tenant it did not change, both tests have to be succesful.

**Comment by KelvinTegelaar** [comment]
suspecting this is fixed, closing. if it's not, feel free to reopen.
