### ISSUE TITLE
[Feature Request]: Custom CSS Phishing Warning Image for branding and contact info

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2390]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When users encounter a phishing site, we not only want users to be alerted not to enter their password, but also to contact us.  We want to embed our contact info and logo into the image. We're happy to make a custom image with specific dimensions and properties if that's what's required. Currently, users just see the big orange warning, and sometimes they don't contact us.  We want to make it clear this protection came from **our** systems/settings, and give them contact info to contact us directly. 

### PowerShell commands you would normally use to achieve above request

We'd like to be able to upload an image _somewhere_ to replace the default image that's used for warnings on phishing pages.

**Comment by KelvinTegelaar** [comment]
Not putting this under consideration - this image is a encoded binary filed and having users edit this themselves feels like a very bad idea
