### ISSUE TITLE
Publishing choco apps does not work

### ISSUE THREAD

**Issue by markkoele** [KelvinTegelaar/CIPP#2394]
### Description

Als er een choco app in de queue wordt gezet wordt deze niet gepubliceerd naar intune/mdm. niet handmatig en niet na 48 uur.

When a choco app is placed in the queue, it is not published to intune/mdm. not manual and not after 48 hours.

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.6.1
Back end version number: 5.6.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
This isn't the place for support, if you're a sponsor you can contact the support address.
