### ISSUE TITLE
[Feature Request]: Add GDAP Roles Viva Goals Administrator and Viva Pulse Administrator

### ISSUE THREAD

**Issue by peter-fisher** [KelvinTegelaar/CIPP#2396]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Noticed that [Viva Goals Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#viva-goals-administrator) and [Viva Pulse Administrator](https://learn.microsoft.com/en-us/entra/identity/role-based-access-control/permissions-reference#viva-pulse-administrator) roles were missing from the GDAP options. I just added them to the two JSON files in my repo and it seems to work fine.

Here is the updated JSON file - 
[GDAPRoles.json](https://github.com/KelvinTegelaar/CIPP/files/15191984/GDAPRoles.json)

**Comment by MWGMorningwood** [comment]
Why not make a PR to dev?

**Comment by peter-fisher** [comment]
> Why not make a PR to dev?

I've never contributed before and the CIPP docs say to create an issue first. I'm also not well-versed in making pull requests to be honest. When I attempted the PR, it looked like it was going to also include a commit for the github workflow yml file and I didn't know how to take that out.

**Comment by MWGMorningwood** [comment]
Check out https://docs.cipp.app/dev-documentation/cipp-dev-guide/setting-up-for-local-development
`.gitignore` is how you'd exclude specific files, but making a local dev env solves the problem indirectly.

**Comment by peter-fisher** [comment]
> Check out https://docs.cipp.app/dev-documentation/cipp-dev-guide/setting-up-for-local-development `.gitignore` is how you'd exclude specific files, but making a local dev env solves the problem indirectly.

Thanks. I started that process. For now, it looks like if I just submit the PR from the dev branch instead of main it doesn't include any workflow files so I'll do that now.

**Comment by peter-fisher** [comment]
I would like to work on this please!
