### ISSUE TITLE
[Feature Request]: New alert to monitor for empty distribution lists

### ISSUE THREAD

**Issue by fenz85** [KelvinTegelaar/CIPP#2402]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Empty distribution lists can lead to emails disappearing. It's happened to us a few times that the only member of a distribution list leaves the company and emails are lost. I came up with the below powershell script to capture the outcome on AllEmptyDLs.

I believe it has stopped working though as our RMM was throwing errors. I'm far from being a powershell expert and troubleshooting this is way above my skills.

### PowerShell commands you would normally use to achieve above request

Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -MsGraphAccessToken $graphToken.AccessToken

$customers = Get-MsolPartnerContract -All | Where-Object { $_.DefaultDomainName -notin $skiplist }

$AllEmptyDLs =  @()
	foreach ($customer in $customers) {
    write-host "Getting started for $($Customer.name)" -foregroundcolor green
    $token = New-PartnerAccessToken -ApplicationId 'a0c73c16-a7e3-4564-9a95-2bdf47383716'-RefreshToken $ExchangeRefreshToken -Scopes 'https://outlook.office365.com/.default' -Tenant $customer.TenantId
    $tokenValue = ConvertTo-SecureString "Bearer $($token.AccessToken)" -AsPlainText -Force
    $credential = New-Object System.Management.Automation.PSCredential($upn, $tokenValue)
    $customerId = $customer.DefaultDomainName
    $session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "https://ps.outlook.com/powershell-liveid?DelegatedOrg=$($customerId)&amp;BasicAuthToOAuthConversion=true" -Credential $credential -Authentication Basic -AllowRedirection
    Import-PSSession $session -allowclobber -Disablenamechecking
    $EmptyDLs = Get-DistributionGroup -ResultSize Unlimited | ? { (Get-DistributionGroupMember $_.PrimarySMTPAddress | Measure-Object).Count -eq 0 } | select DisplayName,PrimarySMTPAddress
	$AllEmptyDLs += $EmptyDLs
}

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests
