### ISSUE TITLE
[Feature Request]: Extension Automapping - Hide Mapped Customers

### ISSUE THREAD

**Issue by martinyelland** [KelvinTegelaar/CIPP#2405]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

To simplify the process of reviewing mapped vs unmapped customers, the 'Select a Tenant' dropdown should only show Tenants not yet mapped.

This makes it easier for the User to identify which tenants are not yet mapped to a PSA Customer. 

![image](https://github.com/KelvinTegelaar/CIPP/assets/20192623/7b4576ef-0272-480e-834c-050aed50f06b)

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests :)

**Comment by martinyelland** [comment]
Fair enough, I am a sponsor through my GitHub Org though 👍 
> Only sponsors can create feature requests :)

**Comment by KelvinTegelaar** [comment]
Perfect, if you lrt us know the org name we'll reopen it for you :)

**Comment by KelvinTegelaar** [comment]
would also resolve https://github.com/KelvinTegelaar/CIPP/issues/2407

**Comment by JohnDuprey** [comment]
Implemented in dev, this will be in the next release
