### ISSUE TITLE
[HaloPSA Extension] Auto-Mapping Duplicates Mappings

### ISSUE THREAD

**Issue by martinyelland** [KelvinTegelaar/CIPP#2407]
### Description

When the Auto-Mapping Feature is used, it creates the mappings in the table - but it does not first check if the mapping already exists. 

**Expected Outcome:**
CIPP ignores the existing mappings where identical
CIPP updates an existing mapping, where a tenant is assigned to different Client Name. 
CIPP does not duplicate the existing mappings, or allow duplicates to be committed. 

**Actual Outcome:**
New Mappings are added
All existing mappings are duplicated in the UI and the Table when saved.

**Steps to Reproduce:** 
- Configure the Extension 
- With an empty mapping list, click 'Automap HaloPSA Clients'
- Mappings are created
- Click Save Mappings
- Remove one or two of the mappings, leaving at least one mapping. 
- Click Save
- Click 'Automap HaloPSA Clients' 
- (Optionally) Click Save

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.6.2
Back end version number: 5.6.3
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
combing this with your feature request and reopening that one :)
