### ISSUE TITLE
[Feature Request]: Add the creation date to user mailbox rules overview

### ISSUE THREAD

**Issue by redanthrax** [KelvinTegelaar/CIPP#2410]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Add creation date to User Mailbox Rules

**Comment by kris6673** [comment]
There is no property on the rule itself to show creation date, seems like it needs to be found by looking (through the unified audit log.)[https://learn.microsoft.com/en-us/purview/audit-troubleshooting-scenarios?view=o365-worldwide#determine-if-a-user-created-an-inbox-rule] 
Can't think of a good way to implement this, hope one of the big guns can

**Comment by KelvinTegelaar** [comment]
Nope, sorry Gary. :(
