### ISSUE TITLE
[Feature Request]: Enable Standard and Strict preset security policies in Exchange Online

### ISSUE THREAD

**Issue by SLYNETAG** [KelvinTegelaar/CIPP#2413]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As discussed in CIPP & SIP from 06.05.2024:

Tenants with e.g business premium can use the following feature
![ksnip_20240506-184530](https://github.com/KelvinTegelaar/CIPP/assets/120649264/3291f992-9e81-48be-a276-b50a67ac84dd)

We'd like to be able to enable this using CIPP, best case using the standards feature as we enable it for most of our tenants with appropriate licensing.

### PowerShell commands you would normally use to achieve above request

We don't, we use the GUI

**Comment by MWGMorningwood** [comment]
I would like to work on this please!

**Comment by MWGMorningwood** [comment]
I was hoping to have this done by tonight but there are still a few things to hammer out. This will likely be in the release after tomorrow's if the PR is accepted.

**Comment by MWGMorningwood** [comment]
Sorry, @SLYNETAG, I tried my damndest to work around this, but Microsoft seems to be serious about this one.
Trying to create the sub-policies does not have a good result, and I cannot find a way to create the sub-policies correctly without doing it through the portal as they state below:
![image](https://github.com/KelvinTegelaar/CIPP/assets/2997336/98ede494-9762-4b3c-a56c-aeba4072388f)

I think the better solution here would be to try to get as many controls from the manual policies into Standards and take a [Configuration Analyzer](https://learn.microsoft.com/en-us/defender-office-365/configuration-analyzer-for-security-policies) approach with it. @OfficialEsco has been killing it with this, and I'm going to try to work with him after MSPGC to get more in there cleanly.

**Comment by MWGMorningwood** [comment]
^ for now

**Comment by SLYNETAG** [comment]
@MWGMorningwood allright, thank you anyway. Then we'll continue to set this manually. Was hoping Microsoft provides some switch in their API to enable this feature.

**Comment by KelvinTegelaar** [comment]
close for now.
