### ISSUE TITLE
Feature Request: Add job title field to create/edit user forms

### ISSUE THREAD

**Issue by dsghi** [KelvinTegelaar/CIPP#242]
**Is your feature request related to a problem? Please describe.**
It would be beneficial to have a job title as an option on both the create user and edit user forms. Currently, there is a department and company field, but the job title is not available.

**Describe the solution you'd like**
Add a field for the Job Title.

**Comment by KelvinTegelaar** [comment]
Planned for v1.5.0

**Comment by KelvinTegelaar** [comment]
added in dev.
