### ISSUE TITLE
Secure Score Overview page is broken.

### ISSUE THREAD

**Issue by MBstatsara** [KelvinTegelaar/CIPP#2422]
### Description

Go to Administration - SecureScore, then page loads with errors.

This seems to have been broken in the last update hotfix.
The page does work on the 5.6.1 front end, but when our dev one is updated to 5.6.2 the page no longer works.
We get these error on the page

Cannot read properties of undefined (reading '1')

TypeError: Cannot read properties of undefined (reading '1') at fe (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/SecureScore-K4Wz8Lmf.js:1:4775) at ZV (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:64291) at sD (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:76061) at Eve (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:117702) at bve (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:112868) at Mwt (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:112791) at p_ (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:112640) at _D (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:108984) at hve (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:39:107930) at C (https://XXXXXXXX.XXXXXXXXXX.azurestaticapps.net/static/index-C3biHfVF.js:31:1540)

### Environment data

```PowerShell
Non-Sponsored.
Front End - 5.6.2
Back End - 5.6.3

Tried clearing tenants Cache.
Tried Clearing all cache.
```

**Comment by KelvinTegelaar** [comment]
As a sponsor you can request a hotfix for this, otherwise wait until the next release.
