### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by philhop1** [KelvinTegelaar/CIPP#2426]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Mailtips , disable option 
or option for 
MailTipsAllTipsEnabled                : True
MailTipsExternalRecipientsTipsEnabled : True
MailTipsGroupMetricsEnabled           : True
MailTipsLargeAudienceThreshold        : 25
MailTipsMailboxSourcedTipsEnabled     : True

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests
