### ISSUE TITLE
[Feature Request]: Identify shared mailboxes that have sign-in enabled

### ISSUE THREAD

**Issue by phintec** [KelvinTegelaar/CIPP#2432]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Many third-party tools that integrate with Microsoft 365 determine billable users as any user account with sign-in enabled.  Shared mailboxes do not generally use the sign-in ability, yet the user account is left as enabled by default unless blocked.  unless it is an exception.  This would allow you to audit the shared mailboxes that have sign-in allowed and block those that are not blocked.  This makes for a more secure tenant and also provides a better count of actual users.

**Comment by kris6673** [comment]
And a report to identify them on this url: /email/reports/SharedMailboxEnabledAccount or EMAIL & EXCHANGE -> Reports -> Shared Mailbox with Enabled Account
