### ISSUE TITLE
[Feature Request]: A way to sort and segregate customer tenants 

### ISSUE THREAD

**Issue by svcCippApp** [KelvinTegelaar/CIPP#2444]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As we are supporting customers in different geographical regions and are under regulatory restrictions on some of our customers, we would like to be able to grant access to customers based on rules. 

Our GDAP permissions for instance for each customer is assigned based on the regulatory requirement for the customer.
Then our technical staff is assigned membership based on their work country.

But using the tool, we can only give access to all customers, unless we want to deploy an instance of the tool for each country or regulatory region.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests
