### ISSUE TITLE
[Feature Request]: Offboarding Wizard for multiple users

### ISSUE THREAD

**Issue by JRivett-ITSG** [KelvinTegelaar/CIPP#2447]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

A multi select in the offboarding wizard would be fantastic.
Please note my sponsorship is under the organization profile:
https://github.com/ITSupportGuys

**Comment by JRivett-ITSG** [comment]
I would like to upgrade the priority of this request

**Comment by KelvinTegelaar** [comment]
Already exists, with a maximum of 3 users.

**Comment by JRivett-ITSG** [comment]
Could it be expanded to allow more?
