### ISSUE TITLE
Unable to add multiple aliases at once to a user

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2451]
### Description

Within Identity -> Admin -> Users
We are unable to add more than one alias at a time. The 'Add Aliases' box advises to put 'One per line' however this doesn't work and shows the below error.

We've failed to create the Aliases: Invalid value specified for property 'mail' of resource 'User'.

*Adding a single alias works without issue here.

I am a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.6.2
Back end version number: 5.6.3
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by JohnDuprey** [comment]
Thanks for the report, this is fixed in dev and will be in the next release.
