### ISSUE TITLE
[Feature Request]: Schedule TAP Codes

### ISSUE THREAD

**Issue by joeldeteves** [KelvinTegelaar/CIPP#2456]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

\*CIPP Sponsor\*

We often deal with new user accounts that are set up ahead of schedule to start on a future date.

IMO, it is better to use a TAP code than a temporary password as it's more secure.

Currently, CIPP just generates an instant TAP code that is valid for 2 hours.

Whereas the Entra Portal, you can generate a TAP code that is valid on a future date and with a specific validity period.

In the interests of time savings and less mouse clicks when setting up new users, we would love to be able to provision them with a TAP code at a future date right from the CIPP portal (in fact, we would love to have the option to provision them with a start date and TAP code that is valid from that start date automagically).

See screenshot of the Entra portal feature below:

<img width="440" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/33190570/7d0f329e-2f28-4783-ad39-2d12b6683dc0">

**Comment by KelvinTegelaar** [comment]
You can already do this via the scheduler, for example:
![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/f74746d9-c4a3-4505-a8c9-d8491fe1bbc2)

**Comment by joeldeteves** [comment]
Thank you @KelvinTegelaar
