### ISSUE TITLE
Add Status Page not applying 'Block device usage during setup'

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2457]
### Description

When trying to deploy the 'Status Page' for enrolled devices, the option 'Block device usage during setup' is not being deployed.

The options selected;
<img width="514" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/73685575/ec979caf-a626-4e57-a2dd-5b7084ffab27">

The status page settings in Intune following successful deployment.
<img width="596" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/73685575/677d9ae3-f0c4-4877-a917-57628b2b6ea3">

This is the case for multiple tenants. Other settings within appear to deploy without issue.

We are a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.6.2
Back end version number: 5.6.3
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Fixed by @kris6673
