### ISSUE TITLE
[Feature Request]: Optional Input for Activity based Timeout

### ISSUE THREAD

**Issue by worktopia** [KelvinTegelaar/CIPP#2460]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Requesting an _Optional Input_ to the existing '**Enable 1 hour activity based Timeout**' Global Standard.

![image](https://github.com/KelvinTegelaar/CIPP/assets/137702212/8e0142bb-fbd2-480e-915d-ccb19fd0fd13)

The option for a custom timer (in minutes), or longer presets, do exist within M365 Admin Portal. The hard 1 hour from Global Standard in CIPP doesn't always suit... but could with this Optional Input to a custom timer :)

![image](https://github.com/KelvinTegelaar/CIPP/assets/137702212/5b6b45a6-3b48-4b2a-9043-d3c0b24b3389)

 If this is doable, would be great for all of us MSPs hoping to do it all in CIPP!

**Comment by kris6673** [comment]
@KelvinTegelaar This is one i have been thinking about myself, and ill make it myself if you accept the FR.
Do you think it would be too "dangerous" to let MSP's decide for themselves with full custom time in minutes?
Would providing only the options 1, 3, 6, 12 and 24 hours be the move, or fully custom from the getgo?

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
Just FYI @worktopia I discussed it with Kelvin and came to the conclusion that adding the default options in M365 as a dropdown was the best solution. 
I should have it ready at the next releasedate :)

**Comment by kris6673** [comment]
Added in dev
