### ISSUE TITLE
Applying an App Protection Policy from template fails with DisplayName error

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2461]
### Description

When applying an app protection policy from a template, on submission the following error is present.

Failed to add policy for *tenant*: policy.DisplayName : The DisplayName field is required.

This happens for both Android and Apple based app protection policies.

I am a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.7.0
Back end version number: 5.7.1
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by twelch-ricohnz** [comment]
Same issue here.

**Comment by KelvinTegelaar** [comment]
Resolved in dev, you must use the template wizard to add.
