### ISSUE TITLE
Display name error when deploying app configuration policies from template

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2462]
### Description

We receive the error of: Failed to add policy for *tenant*: policy.DisplayName : The DisplayName field is required.

This is the same for both Android and Apple based templates. (I had created new policy templates, but that made no difference)

I am a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.7.0
Back end version number: 5.7.1
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Resolved in dev, you must use the template wizard to add.
