### ISSUE TITLE
[Feature Request]: Ability to select multiple Compliance/Configuration policies and action (delete etc)

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2465]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

As an MSP and managing multiple tenancies and standardised requirements across our customer base, every month or so we are replacing our compliance and configuration policies/profiles with newer ones (as CIPP cannot amend existing ones).
It would be very beneficial to be able to have a tick box option for us to bulk update these policies.

Sponsor under: FutureITNZ

**Comment by KelvinTegelaar** [comment]
added to dev
