### ISSUE TITLE
[Feature Request]: Allow limiting access to tenants for users

### ISSUE THREAD

**Issue by techiemate** [KelvinTegelaar/CIPP#2468]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great if we can select tenants or all tenants when creating a user for access to CIPP. That way we can control access.
Example, we have users who only need to manage 1-2 clients so don't want to give them access to all
Also, it can help limit the access to internal tenant only for users who manage internal infrastructure

**Comment by KelvinTegelaar** [comment]
Only sponsors can create Feature Requests, we do not see any active sponsorship under your acount.
