### ISSUE TITLE
Domain Analyser not bringing in all customer domains. 

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2469]
### Description

Seems we are only getting 1 domain per customer in the domains analyser and in a lot of cases its just the onmicrosoft.com domain. 

No permissions issues
No failed log entries. 

### Environment data

```PowerShell
Hosted Instance
Front end: Latest: 5.7.0 (Dev release)
Back End: Current: 5.7.1 (Dev Release)
```

**Comment by catalytic-it** [comment]
Can confirm - We are finding that Domain Analyser is not showing the customers domains. Only showing the tenant.onmicrosoft.com domain.
However, on the 'Dashboard' view of the customer it lists every domain as expected.

**Comment by KelvinTegelaar** [comment]
Fixed in special hf build, will be in release later.
