### ISSUE TITLE
Applying Compliance Policy template to a tenant fails with compliancePolicy.DisplayName : The DisplayName field is required

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2471]
### Description

When applying any compliance policy template (either pulled directly from a tenant, or importing the JSON and specifying Compliance Policy in 'Select Policy Type') we are unable to apply this template. We get the below.

<img width="678" alt="image" src="https://github.com/KelvinTegelaar/CIPP/assets/73685575/662287fd-49ea-48a8-b950-e6d64b210b5c">

Previously raised under #2414 

I am a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.7.0
Back end version number: 5.7.2
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev - all policies must now be created using the three dots menu in list compliance policies to prevent this issue.
