### ISSUE TITLE
[Feature Request]: Option to remove completed scheduled tasks after X Days

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2473]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We currently have an azure runbook that achieves this for us, but i do wonder if its worth building something in to CIPP. Maybe with an application option to set the time period you want (In our instance 7 days). (Other MSP's may want 14 or 30 days for example)

If of no interest, of course feel free just to ignore and close this :)

### PowerShell commands you would normally use to achieve above request

$tasks = Invoke-RestMethod -Uri "$CIPPAPIUrl/api/ListScheduledItems" -Method GET -Headers $AuthHeader -ContentType "application/json"

$currentUnixTime = [int][double]::Parse((Get-Date -UFormat %s))
$sevenDaysInSeconds = 7 * 24 * 60 * 60

foreach ($task in $tasks) {
    try {
    # Calculate the difference in seconds
    $timeDifference = $currentUnixTime - $task.ScheduledTime
    if ($timeDifference -gt $sevenDaysInSeconds -and $task.taskstate -eq "completed") {
        Write-Output "$($task.Name) is $($Task.TaskState) and is older than 7 days and can be deleted"
        $delete = Invoke-RestMethod -Uri "$CIPPAPIUrl/api/RemoveScheduleditem?ID=$($task.rowkey)" -Method POST -Headers $AuthHeader -ContentType "application/json"
        Write-Output "Delete Response $delete"
    } else {
        #$false
        Write-Output "$($task.Name) is not ready to be deleted "
    } 
} catch {
    Write-Error "Error: $($_.Exception.Message)"
}
}

**Comment by KelvinTegelaar** [comment]
I think this is best left up to the user, some might want a default log that returns all jobs always, others might want less. :)
