### ISSUE TITLE
Application stuck as processing

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2475]
### Description

After trying to deploy a Microsoft Store application (via Winget) it will most of the time get stuck as Processing, forever.
A similar issue was happening to GDAP Onboarding before, which got fixed.

### Extended Information

| | |
| ------------------------------------| ---------------------------- |
Install as | user
Restart behaviour | undefined
Assigned to groups | false
Created at | 2024-05-14T17:50:08Z
Modified at | 2024-05-14T17:50:08Z
Featured App | false
Publishing State | processing
of Dependent Apps | 0
Detection Type | No detection rule
Detection File Folder Name | No detection rule
Detection File/Folder Path | No detection rule

In InTune it stays as "Your app is not ready yet. If app content is uploading, wait for it to finish. If app content is not uploading, try creating the app again."

### Environment data

```PowerShell
Sponsored / Non-sponsored instance: Sponsored
Front end version number: 5.7.0
Back end version number: 5.7.2
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by OfficialEsco** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Discussed in Discord - not a bug but unsupported as MS made a change.
