### ISSUE TITLE
Cannot successfully add more than 100 users via management.cipp.app portal

### ISSUE THREAD

**Issue by abacusgroupllc-systems** [KelvinTegelaar/CIPP#2478]
### Description

Create invite with user's email address through https://management.cipp.app > User Management. Invite link successfully created. Link given to user. User successfully authenticates, grants consent, receives 403 error when redirected to main page.

### Environment data

```PowerShell
Hosted instance. Frontend version 5.7.0 / Backend version 5.7.2
```

**Comment by JohnDuprey** [comment]
Bug confirmed, even using the management portal. More users cannot be added.

**Comment by KelvinTegelaar** [comment]
Transefered to support :)
