### ISSUE TITLE
Scheduled Offboarding failing to complete, and not able to carry out some of the required tasks. 

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2482]
### Description

Identity Management > Offboarding Wizard > Select Tenant > Select User > Select the following options:

Revoke All Sessions (works fine)
Remove All Mobile Devices (Not mentioned at all in the logs, so assume its not working/running)
Remove All Rules (Not mentioned at all in the logs, so assume its not working/running)
Remove License (works fine)
Remove users mailbox permissions (Unsure if this is working or not right now - No log entry)
Convert to Shared (works fine)
Disable Sign in (works fine)
Reset Password (Works fine)
Remove from all Groups (Works fine)
Hide from Global address list) (Works fine)
Set out of office (Works fine)
Give Other user full access on mailbox with Auto Mapping (Does not work, fails with error seen below)
Give other user Full access on OneDrive (Does not work, fails with error seen below)
Forward email (Works fine)

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/be18ac16-f359-4185-9a4c-c5523d6b53af)

The task also never shows as completed

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/d9c1bd0c-b929-428a-9105-84bdbfcae3f9)

### Environment data

```PowerShell
Sponsor
Hosted
Currently running a HF Version (Known by JD)
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
