### ISSUE TITLE
[Feature Request]: Improve search fields

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2485]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

1. Currently the Tenant selector makes you scroll to the top pretty much every time when you search, either add autoscroll or start at top of new search
2. Currently when searching it searches per letter which causes lag/freeze (For example user search), add a little wait time so you can finish typing unless it can be smoother.

**Comment by KelvinTegelaar** [comment]
Fuzzy search improved to only show items found so list is smaller, and doesn't need to push back up as it'll naturally happen.
