### ISSUE TITLE
HaloPSA Extension Mapping

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2487]
### Description

Whilst the new extension mapping page for HaloPSA looks good, it has actually removed or reduced usability. It has made it much harder to identify customers that have not been mapped.

That coupled with the fact you cannot type to filter in the pull down menu's makes it very difficult to use on bulk.  

The old way allowed you to see all CIPP tenants, and which had or had not been mapped. This made life much much easier to identify and resolve any missing mappings.   

### Environment data

```PowerShell
Hosted
Frontend: 5.7.0
Backend: 5.7.3
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
The fields are now searchable again, dropdowns only show unmapped tenants.
