### ISSUE TITLE
[Feature Request]: Ability to set 'Language (Region)' option in Autopilot profile

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2498]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

With an autopilot profile, there is currently no option to set the Language (Region).
When we have used the CIPP autopilot deploy, it is setting everything to US & UTC - 8.
On a manual autopilot setting via Endpoint Manager, there is an option to set the 'Language (Region)' which corrects this.

I am a sponsor under: FutureITNZ

**Comment by KelvinTegelaar** [comment]
added, default(blank) is OS-Default
