### ISSUE TITLE
Domain analyser exports [object Object] for ActualMXRecords

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2499]
### Description

- Go to the DA.  
- Show ActualMXRecords as a field.  
- Export either visible fields or all fields, to either PDF or CSV.
- Welcome to [object Object] land!

### Environment data

```PowerShell
Selfhosted
Frontend: 5.7.0
Backend: 5.7.3
Tried Tenant Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
That;s on purpose to show you how pretty the object is(fixed in dev, will be in full release)

**Comment by kris6673** [comment]
I should have probably fired up my dev instance before submitting this lol (thanks a ton tho!)

**Comment by kris6673** [comment]
@KelvinTegelaar Just FYI this is fixed for CSV, but still present for PDF reports on V 5.8.0
