### ISSUE TITLE
Templates Standard Deployment / Group Templates: Dynamic group rules are not updated when changed

### ISSUE THREAD

**Issue by swissbuechi** [KelvinTegelaar/CIPP#2512]
### Description

1. Go to <https://CIPP_URL/identity/administration/group-add-template?customerId=AllTenants> to add a Group Template
- Display Name: `cipp_test_dynamic_update`
- username: `cipp_test_dynamic_update`
- `Dynamic Group`
```
(
   user.userType -ne "Guest"
and 
   user.accountEnabled -eq True
)
```

2. Go to <https://CIPP_URL/tenant/standards/list-applied-standards?customerId=AllTenants> to apply a Standard
- Scroll down to Group Template, enable `Remediate` and select `cipp_test_dynamic_update`
- Save and deploy the Standard
- Wait till completion (check log) for message: `Created group cipp_test_dynamic_update with id <ID>`

4. Go to <https://CIPP_URL/identity/administration/groups?customerId=ID> to verify the group creation
- Filter: `cipp_test_dynamic_update`
- Validate the `membershipRule` = `"membershipRule": "(\n   user.userType -ne \"Guest\"\nand \n   user.accountEnabled -eq True\n)",`

5. Go to <https://CIPP_URL/identity/administration/group-templates> to edit the Group Template
- Filter: `cipp_test_dynamic_update`
- View the JSON
- Replace `"MembershipRules": "(\n   user.userType -ne \"Guest\"\nand \n   user.accountEnabled -eq True\n)",` with `"MembershipRules": "(user.accountEnabled -eq True)",`
- Save changes

6. Go to <https://CIPP_URL/tenant/standards/list-applied-standards?customerId=AllTenants> to apply a Standard
- Deploy the Standard
- Wait till completion (check log) for message: `Group exists cipp_test_dynamic_update. Did not create`

7. Go to <https://CIPP_URL/identity/administration/groups?customerId=ID> to verify the group update
- Filter: `cipp_test_dynamic_update`
- Validate the `membershipRule` = `"membershipRule": "(\n   user.userType -ne \"Guest\"\nand \n   user.accountEnabled -eq True\n)",`
-  `membershipRule` should now be `"MembershipRules": "(user.accountEnabled -eq True)",` but it does not update...

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 5.7.1
Back end version number: 5.7.4
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by swissbuechi** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug. Sponsors can contact support.

**Comment by swissbuechi** [comment]
Alright thanks...

So could this be solved with the support?

We are currently evaluating cipp to support us with managing 100+ Microsoft 365 customers. If our initial tests go well, we are also looking forward to sponsoring this awesome project.

**Comment by swissbuechi** [comment]
Hi @KelvinTegelaar 

We are now a sponsor of CIPP 🎉
Please verify via my employee https://github.com/axelionAG

Could you please review our issue again? Or should we reach out to the cyberdrain helpdesk directly?

Thank you!
