### ISSUE TITLE
Invoke-ListUserConditionalAccessPolicies does not work

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2521]
### Description

Invoke-ListUserConditionalAccessPolicies does not work

Returns no data. 

### Environment data

```PowerShell
Frontend: 5.7.1
Backend: 5.7.4
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Fixed in dev
