### ISSUE TITLE
Enabling/Disabling SpamFilter

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2524]
### Description

This currently fails in both the front end, and the API with error: 

System.Management.Automation.RuntimeException: |Microsoft.Exchange.Data.Directory.InsufficientPermissionsException|Source server:LO3P123MB2985.GBRP123.PROD.OUTLOOK.COM doesn't have write permission to target DC:. Usually it indicates that target forest isn't an account partition of source forest. The user has insufficient access rights.

I would assume its missing an -anchor

### Environment data

```PowerShell
Frontend: 5.7.1
Backend: 5.7.4
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by BNWEIN** [comment]
This one is a bit strange, because once in a while it does work, but if you manage to enable it and then try and disable it a few minutes later it fails.

**Comment by KelvinTegelaar** [comment]
Fixed in dev by @kris6673
