### ISSUE TITLE
[Feature Request]: GraphHelper for Connect-MicrosoftTeams

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2526]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to have a GraphHelper to connect to `Connect-MicrosoftTeams` similar to `New-ExoRequest`.
This would require the `MicrosoftTeams`/`MicrosoftTeamsPowerShell` module since i would like to execute these commands
* Set-CsTeamsMeetingPolicy
* Set-CsTeamsMessagingPolicy
* Set-CsTenantFederationConfiguration
* Set-CsTeamsClientConfiguration

### PowerShell commands you would normally use to achieve above request

Connect-MicrosoftTeams doc: https://learn.microsoft.com/en-us/powershell/module/teams/connect-microsoftteams?view=teams-ps#example-7-connect-to-microsoftteams-using-access-tokens-in-the-delegated-flow
Unsure if its method 6 or 7 that should be used, from the looks of it we can use [Get-ClassicAPIToken](https://github.com/KelvinTegelaar/CIPP-API/blob/master/Modules/CIPPCore/Public/GraphHelper/Get-ClassicAPIToken.ps1)

Command you can test with
```
Get-CsTeamsMeetingPolicy -Identity Global
Set-CsTeamsMeetingPolicy -Identity Global -AllowAnonymousUsersToJoinMeeting $false
```

**Comment by OfficialEsco** [comment]
I am not working on it as it looks abit advanced

**Comment by KelvinTegelaar** [comment]
We'll pick this up somewhere, but cant make any promises, commenting to keep open.

**Comment by rvdwegen** [comment]
We already have New-TeamsAPIGetRequest no?

**Comment by OfficialEsco** [comment]
I was messing with that 3 months ago and gave up when `New-TeamsAPIGetRequest` spammed `Teams API Get Request failed. Error: Response status code does not indicate success: 404 (Not Found).` because of

https://github.com/KelvinTegelaar/CIPP-API/blob/b879351569f199d19eb6719b3559aa6e7073e77a/Modules/CIPPCore/Public/GraphHelper/New-TeamsAPIGetRequest.ps1#L27

**Comment by KelvinTegelaar** [comment]
Added in dev
