### ISSUE TITLE
Error 403 when trying to add a autopilot device

### ISSUE THREAD

**Issue by v1corp** [KelvinTegelaar/CIPP#2527]
### Description

I am trying to add an Autopilot device to one of my tenants via Microsoft Product Key ID. I go through the steps of adding it and on Step 4 once I submit it. I receive an error message saying Failed to create autopilot devices. Response status code does not indicate success: 403(Forbidden).

I attempted to conduct some troubleshooting to see why I am experiencing this issue. I attempted to add an autopilot device to a different tenant just to see if this an issue affecting all tenants. I was able to get the device enrolled into a separate tenant using the same Product Key ID method. I then removed it from the test tenant I added it to. Then manually got the HW info and manually added the device through the windows autopilot devices page in the tenant. Which was a success. I have 3 more devices that I need to add to the tenant and all of them are receiving the error message. I have attempted to clear tenant cache, CPV refresh on  the tenant in question, and run a tenant access check which was successful, none of which have helped. I am fairly new to CIPP but, I feel like I have exhausted my troubleshooting steps with this.
![CIPP Autopilot Failure](https://github.com/KelvinTegelaar/CIPP/assets/170590996/572d5756-877f-4973-898c-83ff14f87d5e)

### Environment data

```PowerShell
Sponsored Instance
Front End Version: 5.7.1
Back End Version: 5.7.4
Tried Tenant Cache Clear: True
Tried Token Cache Clear: False
```

**Comment by v1corp** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
403 forbidden most likely means that your CIPP service account is not in AdminAgents or the correct GDAP groups. This is a support issue, hit up our helpdesk as you're a sponsor :)

**Comment by v1corp** [comment]
When I first signed up, I knew I could reach out to support. What would be the best way of getting in contact with them to open a ticket or get assistance? Thank you!

**Comment by KelvinTegelaar** [comment]
helpdesk@cyberdrain.com is the best method, you'll receive an auto-reply with a ticket number if you ever need to reference that. Another option is Discord #quicksupport channel. https://discord.gg/cyberdrain. :)
