### ISSUE TITLE
[Feature Request]: Allow editor User to apply Standards to single Tenants

### ISSUE THREAD

**Issue by cippzurichnetgroup** [KelvinTegelaar/CIPP#2531]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, it is only possible to apply standards to all tenants or to individual tenants as an admin.

We would like to allow our normal users to apply standards to individual tenants.

The All Tenant Standard can still only be customized and applied by admins

### PowerShell commands you would normally use to achieve above request

?

**Comment by KelvinTegelaar** [comment]
with the new right management system you'll be able to decide these permissions yourself.
