### ISSUE TITLE
FEATURE REQUEST:  Deploy Teams Custom Apps as Standard

### ISSUE THREAD

**Issue by TahdenHerra** [KelvinTegelaar/CIPP#2539]
### **Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.**

It would be great to be able to upload a custom app for Teams that can be Installed or set as part of a Standard. The use case is for a custom app such as "CloudRadial" as a client portal that can be installed on every customers Teams app and added to the Global App policy (So all users will have access by default). This would make Onboarding a new customer that much easier

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
