### ISSUE TITLE
[Feature Request]: Intune Template Standard Revamp

### ISSUE THREAD

**Issue by MWGMorningwood** [KelvinTegelaar/CIPP#2540]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, with the Intune Template Standard, you can only assign a batch of policies in one way for the entire batch.
If the UI were adjusted to be a table of entries, where the entries can be dropdowns or select boxes, controlling how each policy is assigned would be much easier and more intuitive.

Along with usability, many policies have a best-practice assignment method (device or user, depending on what it is doing). The current setup does not allow for easily deploying *all* desired policies in the best-practice configuration for each via standards.
This would also make setting up exclusion groups and breaking out policies for them easier.

**Example:**
| Policy Template | Assigned Group(s) | |
|------------------|----------------------|----------|
| `CIPP: Enable OneDrive Silent Logon` | `All Users`, `All Devices` | **X** |
| `CIPP: Automatic Configuration of Outlook` | `All Users` | **X** |
| `MSP: Configure ASR` | `Dynamic Device Group {bla}` | **X**  |
| *Dropdown to add new* | *Dropdown to add new* | **+** |

* Group DisplayName -> ID evaluation should probably be stolen from the Conditional Access function and turned into its own helper function, as it would likely be handy here.
* Multiple groups should be able to be chosen or entered
* Group options for `All Devices`, `All Users`, `{Custom Group}`, and `None/Unassigned`
* Would likely need a decently hefty change to the API function for Intune Templates

### PowerShell commands you would normally use to achieve above request

UI / Existing functionality change

**Comment by KelvinTegelaar** [comment]
Implemented in dev
