### ISSUE TITLE
Deploy Intune policy with custom group failed

### ISSUE THREAD

**Issue by rootadmin1** [KelvinTegelaar/CIPP#2541]
### Description

When we try to deploy a policy to Intune with a the assignment AllDevices  it fails with the following error.
"Could not assign policy to AllDevices. Policy ID is 7fac75cd-e9ed-4e00-adc4-e48a6812652b. Error: Resource not found for the segment 'deviceConfigurations'."

Also when we are using a custom group we get the same error.

I found this on the internet about the issue.

I had the same issue. Intune support eventually confirmed that the /deviceManagement/deviceConfigurations/{deviceConfigurationId}/microsoft.graph.windowsUpdateForBusinessConfiguration/deviceUpdateStates endpoint won't be supported anymore.

I worked round my issue by using the generic deviceManagement/deviceConfigurations/{deviceConfigurationId}/deviceStatuses endpoint instead. This won't give you the current feature / quality versions of the devices (although that is available elsewhere) but it does return a compliance status for each device.

### Environment data

```PowerShell
Non-sponsored
5.8.0
5.8.0
true
true
```

**Comment by rootadmin1** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug.
