### ISSUE TITLE
[Feature Request]: Secure Score Third Party Remediation Templates

### ISSUE THREAD

**Issue by AdaptITAdmin** [KelvinTegelaar/CIPP#2542]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Where a non MS product is used that meets the requirements for a secure score action  It would be useful to define a set of secure score action plans for those tools to apply to a tenant.

For example a third party spam filter with identity protection might satisfy 10 actions.  Rather than setting those actions individually it would be great to be able to define a Spam filter template and apply it in one go.

### PowerShell commands you would normally use to achieve above request

unknown

**Comment by KelvinTegelaar** [comment]
We only(and already) do this for CIPP remediations. We wont support third party products unless they are a direct sponsor.

**Comment by Ben-ITLogic** [comment]
Hi @KelvinTegelaar , I think what OP was meaning was a way to bulk set Secure Score items and as a further extension to this have the ability to use templates to automatically bulk change secure score items. Eg. Template sets these 5 secure score items to "Third Party" with the comment "XYZ Product replaces this."

I would settle for bulk actions on the Secure Score side of things as currently its a bit faster to use the Security portal to set 5 or so items this way than in CIPP.

I see this as a generic extension to the current functionality. It can be done in CIPP one by one currently.
