### ISSUE TITLE
Minor: Misleading text on multiple policy deletion

### ISSUE THREAD

**Issue by SGeeves** [KelvinTegelaar/CIPP#2545]
### Description

Really minor one here.
When selecting and deleting multiple compliance policies in one go, the confirmation box text is a little off... 

![image](https://github.com/KelvinTegelaar/CIPP/assets/73685575/4db58dcf-43d3-4e25-9c7d-cab057983bff)

Continuing anyway still achieves the goal of deleting the policies.

I am a sponsor under: FutureITNZ

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 5.8.0
Back end version number: 5.8.0
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev, thanks for catching!
