### ISSUE TITLE
[Feature Request]: Halo PSA Extension Mapping Change

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2547]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Right now you can only map one Microsoft/CIPP tenant to one Halo PSA customer

We have several Halo customers who have more than 1 tenant.  

One potential fix is to hide already mapped Microsoft/CIPP Tenants from the left pull down menu
but leave all Halo tenants in the right pull down menu even if mapped

What we don't want, is for an already mapped Microsoft/CIPP tenant to still show in the left hand pull down menu.

**Comment by KelvinTegelaar** [comment]
Changed this behaviour in dev.

**Comment by BNWEIN** [comment]
I am afraid this still doesnt work. You cannot select a customer in the right hand box (Select HaloPSA Client) that already has a tenant mapped.

**Comment by BNWEIN** [comment]
Discussed with JD.  Whilst you can now make the relevant selections, if the halo customer already has a mapping the + Button doesnt do anything

**Comment by BNWEIN** [comment]
Please can we not let this close @JohnDuprey

**Comment by KelvinTegelaar** [comment]
fixed in dev
![image](https://github.com/user-attachments/assets/9ce9944e-f1c3-4279-8b8e-6d6defc04c11)
