### ISSUE TITLE
[Feature Request]: Offboarding Users - Remove Calendar Events Option

### ISSUE THREAD

**Issue by sctcraig** [KelvinTegelaar/CIPP#2548]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would like to see the ability to cancel a user's calendar events during the offboarding process. This can currently be achieved with PowerShell: https://learn.microsoft.com/en-us/powershell/module/exchange/remove-calendarevents?view=exchange-ps

This is helpful for canceling meetings an offboarded user is the organizer. Clients will often request this to prevent issues with future meetings being organized by an inactive user.

### PowerShell commands you would normally use to achieve above request

Remove-CalendarEvents -QueryWindowInDays 730 -CancelOrganizedMeetings -Confirm:$false

It would be helpful have _QueryWindowInDays_ take input so that can be dynamic.

**Comment by chase-vgo** [comment]
I just submitted a PR that adds this feature 🙂

**Comment by sctcraig** [comment]
> I just submitted a PR that adds this feature 🙂

Awesome! Many thanks!
