### ISSUE TITLE
[Feature Request]: Mailbox & Calendar Rights from an specific user

### ISSUE THREAD

**Issue by Link-itSupport** [KelvinTegelaar/CIPP#2554]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When you click on "Read and manage" on a mailbox, you have a list of users.
![image](https://github.com/KelvinTegelaar/CIPP/assets/140384150/9b70d6b3-705f-4a7f-a7c1-2cd505e8737e)

We would like to see when you click on a user (Administration -> Users -> User), what they all have rights to, i.e. which calendar and mailbox. (like the process above but in reverse)
Instead of going through every mailbox/calendar to see if that person is entitled to it.

### PowerShell commands you would normally use to achieve above request

Calendar Rights:
Get-Mailbox | % { Get-MailboxFolderPermission (($_.PrimarySmtpAddress.ToString())+”:\Agenda”) -User <USER> -ErrorAction SilentlyContinue} | select Identity,User,AccessRights

Mailbox Rights:
Get-Mailbox | % { Get-MailboxPermission (($_.PrimarySmtpAddress)) -User <USER> } | select Identity,User,AccessRights

**Comment by KelvinTegelaar** [comment]
This is impossible, as it requires a query for all users and all permissions - This would take hours to finish on small tenants, days or weeks on large tenants.
