### ISSUE TITLE
[Feature Request]: Block Sign In for Newly Created Shared Mailboxes

### ISSUE THREAD

**Issue by PremierOneData** [KelvinTegelaar/CIPP#2555]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The page /email/administration/add-shared-mailbox in CIPP allows you to create a new shared mailbox. The create mailbox is attached to a user account that is enabled by default.

My request is that new shared mailboxes created through this page would be automatically disabled (sign in blocked).

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
I'll have a bash at it next week :)
I thought they were disabled by default when they were created, but apparently nope. Great idea!

**Comment by KelvinTegelaar** [comment]
Added in dev, waiting to merge, but will be in tomorrows release. :)
