### ISSUE TITLE
Cannot apply Device Management policies to AllDevices

### ISSUE THREAD

**Issue by RustyBarrel** [KelvinTegelaar/CIPP#2566]
### Description

When applying policy templates to a tenant, we cannot use the option AllDevices. The following error message is given:
Could not assign policy to AllDevices. Policy ID is b132ebc1-5fa1-4105-8fb4-0c3c209cc035. Error: Resource not found for the segment 'configurationPolicies'.
Successfully added policy for Customerxxx.onmicrosoft.com

### Environment data

```PowerShell
Non-sponsored instance, I think.
Frontend version 5.8.5
Backend version 5.8.5
Tried Tenant Cache clear: False
Tried Token cache clear: false
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev
