### ISSUE TITLE
[Feature Request]: Add a Enterprise App registration trough the Standards

### ISSUE THREAD

**Issue by ITaanspreekpunt** [KelvinTegelaar/CIPP#2568]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have multiple integrations like HaloPSA / Microsoft / Ninja / Lastpass etc.
For each new tenant we have to manually consent those applications. We can use the application approval function within Cipp and use our id's with the copy permissions function set. However this is a manual proces. Everytime we need to copy our Id's and sometimes we forget it on our customers and than no sync happens.

Would be great to allow certain application ID's in the standards. So all our customers get for example the HaloPSA CSP and SSO apps activated.

**Comment by KelvinTegelaar** [comment]
added in dev
