### ISSUE TITLE
[Feature Request]: Dashboard with the VPP, DEP and Push certificate status of all tenants added in CIPP

### ISSUE THREAD

**Issue by gijsverbruggen** [KelvinTegelaar/CIPP#2570]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi Kevin, we are administrating 30+ intune tenants with Cyberdrain. We love the product so far, but we have 1 feature request if possible. We would like a dashboard that shows the status of all our customers DEP, VPP and Push certificates in just one overview.
After a quick google I noticed that there are already a few powershell/graph scripts that can extract that kind of information. 
Hopefully you can integrate them in a nice dashboard.

Best regards,

Gijs Verbruggen

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs

**Comment by BVGorp** [comment]
Sponsored by Ictivity
