### ISSUE TITLE
No way to tell status of "All external senders to email this group" for Distribution Lists

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#2571]
### Description

When viewing a Distribution List from the [IDENTITY MANAGEMENT > Administration > Groups] page there is no indication of the status of the "All external senders to email this group" setting and the "Let people outside the organization email the group" checkbox does not "pre-check" if the setting is on. This requires opening the MS Admin center to check or change this setting with confirmation.

When the option is enabled:
![When Enabled](https://github.com/KelvinTegelaar/CIPP/assets/93686819/4e2a8aed-9bac-4b38-99d6-e5d0411ff4b6)

When the option is disabled:
![When Disabled](https://github.com/KelvinTegelaar/CIPP/assets/93686819/15235887-3209-427b-8879-57601c7f3555)

### Environment data

```PowerShell
Sponsored instance Front end version number: Current: 5.8.5
Back end version number: 5.8.5
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by JeremyMcM** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

I did find this feature request https://github.com/KelvinTegelaar/CIPP/issues/1100 that appears to be the genesis of the check box being in the Group admin section at all, but I can't find any mention of the current status not being shown.

Thanks!

**Comment by KelvinTegelaar** [comment]
@BNWEIN feel free to PR what you made so far so I can finish it. :)

**Comment by KelvinTegelaar** [comment]
Finished and implemented.
