### ISSUE TITLE
Standards - Disable Shared Mailbox AAD accounts - No longer Disabling Shared Mailbox Accounts

### ISSUE THREAD

**Issue by gosvalthar** [KelvinTegelaar/CIPP#2572]
### Description

This standard does not disable accounts for recently converted shared mailbox accounts. The Shared Mailbox with Enable Account report does return shared mailboxes that are not disabled.

We discussed this in the CIPP discord. I was advised that Microsoft stopped saying the exchange online account state.

### Environment data

```PowerShell
Non-sponsored instance.
Frontend version 5.8.5
Backend version 5.8.5
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
Permissions check: No issues.
GDAP Check: No issues.
Tenant Access Check: No issues.
```

**Comment by gosvalthar** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by KelvinTegelaar** [comment]
Fixed in dev
