### ISSUE TITLE
[Feature Request]: Disable -BccSuspiciousOutboundMailTo

### ISSUE THREAD

**Issue by AaronSEQ-IT** [KelvinTegelaar/CIPP#2573]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have some Clients that have the:
"Send a copy of suspicious outbound messages or message that exceed these limits to these users and groups" 

Set going to either an internal address or the previous IT provider. We would like to disable (optimally) or just remove any addresses here as to stop any SPAM being sent out or internally. 

CIPP can currently disable the alert or change the address it doesn't seem like it can stop the forward of the SPAM mail. 

![Anti-SPAM](https://github.com/KelvinTegelaar/CIPP/assets/173437126/41d2a3ff-8bbc-40ab-882e-af5fa108fe70)

### PowerShell commands you would normally use to achieve above request

# Step 1: Install the Exchange Online PowerShell Module (if not already installed)
Install-Module -Name ExchangeOnlineManagement -Force -AllowClobber

# Step 2: Import the module and connect to Exchange Online
Import-Module ExchangeOnlineManagement
Connect-ExchangeOnline -UserPrincipalName your-email@example.com -ShowProgress $true

# Step 3: Modify the default outbound spam filter policy to stop forwarding suspicious messages
Set-HostedOutboundSpamFilterPolicy -Identity "Default" -BccSuspiciousOutboundMailTo $null

# Step 4: Disconnect the session
Disconnect-ExchangeOnline -Confirm:$false

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
