### ISSUE TITLE
[Feature Request]: Schedule add user / Onboarding for new users

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2577]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Since JIT can schedule start date i would like to schedule a creation date for new Users.
Currently we get orders for new users similar to user offboarding (a few months ahead).
A simple addition would be to add creation date to the add user form.
The long way would be to create a Onboarding Wizard for new users, this could include a few more options like for example Shared Mailbox delegation and Group memberships

**Comment by KelvinTegelaar** [comment]
I like it. Planned .

**Comment by KelvinTegelaar** [comment]
> I'd like to add a suggestion to this: Per-tenant user onboarding templates, which could contain stuff like:
> 
> * Naming conventions ([j.doe@contoso.com](mailto:j.doe@contoso.com), [john.doe@contoso.com](mailto:john.doe@contoso.com) etc.)
> * Default roles with their corresponding group memberships/licenses (Sales, director etc.)

Only sponsors can create FRs, this will not be taken into consideration.

**Comment by KelvinTegelaar** [comment]
No worries, I'll remove the posts. :)

**Comment by KelvinTegelaar** [comment]
Added in dev
