### ISSUE TITLE
[Feature Request]: Configure priority for SpamFilter

### ISSUE THREAD

**Issue by cipptesting** [KelvinTegelaar/CIPP#2581]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

There is currently no option to configure priority when deploying new spamfilter.

I have already submitted a pull request in CIPP and CIPP-API for this.

**Comment by cipptesting** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Implemented in dev
