### ISSUE TITLE
Complex filter "or" dosnt seem to work

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2583]
### Description

I am testing in the MFA report.
In complex filters "or" dosnt seem to work, even if the [code](https://github.com/KelvinTegelaar/CIPP/blob/4269a2ca00f3d4a2c39bbde58b0bd8ea4b90823c/src/components/tables/CippTable.jsx#L287) says it should
"Complex: PerUser like enforced or disabled" only returns the enforced one and ignores the disabled ones. 
"Complex: PerUser like enforced or PerUser eq disabled" returns all users like no filtering has happened

### Environment data

```PowerShell
Self-hosted
Front and backend version: 5.8.5
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by kris6673** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/c39a3485-8ae3-42d7-9fe2-f662170c35dd)
Works fine here. :) Also using your filter:

![image](https://github.com/KelvinTegelaar/CIPP/assets/49186168/272b6277-8a20-43ba-932f-7cf1f81a2adf)
