### ISSUE TITLE
[Feature Request]: More granular anti-phishing policy configuration within standards

### ISSUE THREAD

**Issue by kakaiwa** [KelvinTegelaar/CIPP#2593]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

There are several parameters for anti-phishing policy not configurable in standards. These includes:
AuthenticationFailAction, SpoofQuarantineTag, TargetedUserQuarantineTag, TargetedDomainQuarantineTag

Adding these will help admin make more granular quarantine decision depending on the detection.

**Comment by kakaiwa** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Closing the issue as the PR is in place, and about to be accepted with one minor change :)
