### ISSUE TITLE
Deploy Named Locations wizard summary is blank

### ISSUE THREAD

**Issue by Ben-ITLogic** [KelvinTegelaar/CIPP#2603]
### Description

When going through the **Deploy Named Locations** wizard on Step 3, the "Rule Settings" section is completely blank.

It doesn't seem to matter if IP addresses or countries are picked. The Rule Settings section is always blank. Tenant data shows fine though.

![image](https://github.com/KelvinTegelaar/CIPP/assets/51980872/bf0ec763-cddc-47cc-80cb-31fadaf07514)

### Environment data

```PowerShell
Front end version number: Current: 5.9.0
Back end version number: Current: 5.9.2
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by Ben-ITLogic** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, we just don't show any settings at this point for named locations.
