### ISSUE TITLE
CA Tempaltes page no longer loads after adding new template

### ISSUE THREAD

**Issue by Ben-ITLogic** [KelvinTegelaar/CIPP#2604]
### Description

I added a new template (JSON below) and ever since then - the CA Templates page throws up an error. I can't remove the template to confirm it was this. But it was working before I added this as a template.

It seems as though I can deploy this template as I had to use the deployment tool to get a copy of the JSON.

Error: can't convert null to object
Error Location: `nn@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10066 FE/_r</nn/</<@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10290 FE/_r</nn/<@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10259 nn@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10075 FE/_r</br<@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10790 FE/_r<@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:10770 Qme@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:68703 hr.useMemo@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:15:6259 FE@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:268:9321 ZV@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:64291 cD@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:76061 Tve@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:117950 yve@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:112871 xwt@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:112794 m_@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:112640 bD@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:108984 _ve@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:39:107930 C@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:31:1541 x@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:31:1899 @https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:23:79559 jH@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:23:79299 rK@https://cipp.<REDACTED>.com.au/static/index-nhlDm9Qv.js:23:79363`

JSON of the newly important CA Template:
`{
  "displayName": "Geo-Blocking",
  "modifiedDateTime": "2024-06-26T05:44:03.4478334Z",
  "grantControls": {
    "customAuthenticationFactors": [],
    "builtInControls": [
      "block"
    ],
    "operator": "OR",
    "authenticationStrength": null,
    "authenticationStrength@odata.context": "https://graph.microsoft.com/beta/$metadata#identity/conditionalAccess/policies('5e49789c-c8fd-46e4-ba03-b40e2542d02f')/grantControls/authenticationStrength/$entity",
    "termsOfUse": []
  },
  "createdDateTime": "2024-06-26T05:20:11.1924237Z",
  "id": "5e49789c-c8fd-46e4-ba03-b40e2542d02f",
  "state": "enabledForReportingButNotEnforced",
  "conditions": {
    "signInRiskLevels": [],
    "clientApplications": null,
    "platforms": null,
    "deviceStates": null,
    "applications": {
      "includeApplications": [
        "None"
      ],
      "excludeApplications": [],
      "applicationFilter": null,
      "includeUserActions": [],
      "includeAuthenticationContextClassReferences": []
    },
    "locations": {
      "excludeLocations": [
        "Philippines (Used for Geo-blocking)",
        "Australia (Used for Geo-blocking)"
      ],
      "includeLocations": [
        "All"
      ]
    },
    "userRiskLevels": [],
    "devices": null,
    "times": null,
    "users": {
      "includeUsers": [
        "All"
      ],
      "excludeGuestsOrExternalUsers": {
        "guestOrExternalUserTypes": "serviceProvider",
        "externalTenants": {
          "@odata.type": "#microsoft.graph.conditionalAccessEnumeratedExternalTenants",
          "members": [
            "<REDACTED>"
          ],
          "membershipKind": "enumerated"
        }
      },
      "excludeRoles": [],
      "excludeUsers": [],
      "includeGroups": [],
      "excludeGroups": [],
      "includeRoles": [],
      "includeGuestsOrExternalUsers": null
    },
    "clientAppTypes": [
      "all"
    ]
  },
  "LocationInfo": [
    null,
    [
      {
        "@odata.type": "#microsoft.graph.countryNamedLocation",
        "displayName": "Philippines (Used for Geo-blocking)",
        "countriesAndRegions": [
          "PH"
        ],
        "includeUnknownCountriesAndRegions": false,
        "countryLookupMethod": "clientIpAddress",
        "policyInfo": null
      },
      {
        "@odata.type": "#microsoft.graph.countryNamedLocation",
        "displayName": "Australia (Used for Geo-blocking)",
        "countriesAndRegions": [
          "AU"
        ],
        "includeUnknownCountriesAndRegions": false,
        "countryLookupMethod": "clientIpAddress",
        "policyInfo": null
      }
    ]
  ],
  "GUID": "5ad59482-1693-4430-bb35-4b2bade3ed2f"
}`

### Environment data

```PowerShell
Front end version number: Current: 5.9.0
Back end version number: Current: 5.9.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: false
```

**Comment by Ben-ITLogic** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev
