### ISSUE TITLE
[Feature Request]: Searchable user field for Assign device in Autopilot devices

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2606]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently it get really hard to find the right user when there is 50+ users in a tenant. 
Having a searchable single user selectable field like in Edit user - Set Manager would be very helpful.
Would probably help with a lot of the modals and make them behave and feel nicer.

### PowerShell commands you would normally use to achieve above request

None

**Comment by kris6673** [comment]
I would like to not work on this anymore please!

**Comment by kris6673** [comment]
I thought it would be a simple copy paste from Edit user - Set Manager to the modal, but thats really not how the hidden modals work. I fiddled a bit and didnt understand what i was doing ^^
And my brain was overloaded from all the damn heat ^^
Im farly sure there needs to be a new part added in the modal, so you can pick between different modal modes. Idearly it would be very nice to be able to use all the different CIPP custom selector components

**Comment by kris6673** [comment]
Bumb

**Comment by KelvinTegelaar** [comment]
Added to dev. dropdowns are now select search.
