### ISSUE TITLE
[Feature Request]: Push Allow/Blow Lists across All Tenants

### ISSUE THREAD

**Issue by bpbmcs** [KelvinTegelaar/CIPP#2609]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When we find there is a bad email or even good domain we want to whitelist or block list, it would be ideal to be able to push this once instead of having to go tenant by tenant which is very painful. This would save a lot of time especially for MSPs.

Section of the CIPP portal I'm referring to is Email & Exchange -> Tenant Allow/Block Lists and then pushing for "All Tenants".

**Comment by KelvinTegelaar** [comment]
Added All Tenants support to Add Tenant Allow/Block list. We do not support listing for all tenants yet.
