### ISSUE TITLE
CIPP Defender deployment wizard disconnects Intune from the Defender portal

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2611]
### Description

When we run the Defender deployment on any tenant, it breaks the connection from the Defender portal to Intune. To fix it, I just have to go into the Defender portal, turn off the Intune connection, save, and then turn it back on and save again.

- Verified on two separate CIPP instances, all with the recommended GDAP roles mapped
- Same results observed across 12 different tenants
- Bobby also saw this same behavior. 

![image](https://github.com/KelvinTegelaar/CIPP/assets/32371708/494a324d-a212-4391-8e9a-ff66d90ed28c)

![image](https://github.com/KelvinTegelaar/CIPP/assets/32371708/360a4792-6115-4ce7-8fee-d74332b3c8b4)

I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

### Environment data

```PowerShell
Both CIPP instances are hosted/sponsored

Front-end version number: 5.9.3
Back end version number:  5.9.3
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by CDSFounder** [comment]
We also observed this issue today.

**Comment by HappyEarthDay** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a CIPP issue, after loads of troubleshooting this turned out to be a MS issue that they are solving. Expected fix is next month. issue U389478.
