### ISSUE TITLE
[Feature Request]: Set Out of Office enhancements

### ISSUE THREAD

**Issue by msoukhomlinov** [KelvinTegelaar/CIPP#2619]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

# Enhanced Out of Office (OOF) Feature Request for CIPP

## Current Limitations

The existing Out of Office (OOF) functionality in CIPP (Cloud Identity and Policy Platform) has two primary limitations:

1. Inability to set start and end dates for OOF status
2. Lack of HTML styling options for OOF message content (both internal and external)

## Proposed Enhancements

We propose expanding the current OOF feature to include:

1. **Date Range Setting**: Allow users to specify start and end dates for OOF status.
2. **HTML Styling**: Enable HTML formatting for both internal and external OOF messages.

### 1. Improved Flexibility and Planning

By allowing users to set start and end dates for OOF status, MSPs can:
- Plan and schedule OOF messages in advance
- Automate the process of enabling and disabling OOF status
- Reduce manual intervention and potential oversight in managing OOF statuses

### 2. Enhanced Message Customization

Enabling HTML styling for OOF messages will:
- Allow for more professional and visually appealing OOF responses
- Provide options to include formatted text, links, and potentially even images in OOF messages
- Enhance brand consistency by allowing MSPs to use client-specific styling in OOF messages

### 3. Expanded Use Cases

These enhancements would significantly broaden the applicability of the OOF feature beyond just off-boarding scenarios. Potential use cases include:

- Vacation planning and management
- Temporary reassignments or role changes
- Planned absences for training or conferences
- Seasonal business closures

### 4. Centralized Management for MSPs

With these improvements, MSPs would gain:
- A centralized tool to manage OOF settings across multiple clients
- Increased efficiency in handling client requests related to OOF status
- Better visibility and control over OOF statuses across their managed user base

### 5. Competitive Advantage

Implementing these features would:
- Align CIPP more closely with native Microsoft 365 OOF capabilities
- Provide a unique selling point for MSPs using CIPP to manage client environments
- Potentially reduce the need for additional third-party tools to manage OOF settings

## Conclusion

By enhancing the OOF functionality with date range settings and HTML styling options, CIPP would provide MSPs with a more robust, flexible, and efficient tool for managing Out of Office statuses across their client base. This improvement would extend the feature's usefulness beyond off-boarding scenarios, making it a valuable asset for day-to-day operations and client management.

**Comment by KelvinTegelaar** [comment]
Only sponsors cam create frs

**Comment by BNWEIN** [comment]
Whilst it doesnt have the HTML Editing at the moment, it already has the ability to schedule the OOO in several ways

1: Using a scheduled task
![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/720cee8e-7902-4156-8e13-dadd96a6644a)


2: when editing a mailbox 
[msoukhomlinov](https://github.com/msoukhomlinov)
