### ISSUE TITLE
[Feature Request]: Rename user during off-boarding

### ISSUE THREAD

**Issue by shinomen** [KelvinTegelaar/CIPP#2623]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When we off-board users, we typically turn them into shared mailboxes and keep them that way for quite some time for archival purposes.  There can be quite a few mailboxes of past employees that are in this archived state.  Initially we started renaming them with "z(Archived) User First Name Last Name" so that we could move these archived users to the bottom of our users list and prevent them from being inter mingled with the active users in the company address book.  I know there is an option to hide the user from the address book so that they don't show up when users access the GAL but it's still beneficial to have this grouping of archived mailboxes show up at the bottom of the users list when doing administration tasks in CIPP.  For me it helps signal that these users mailboxes are archived and it keeps them out of my face when looking at the users list.  Additionally if I want to do a quick search or operation on the archived mailboxes, I can type in z(Archived) in the filter in CIPP and they quickly show all the different accounts that are archived.  
Currently with the off-boarding wizard I have to go back to each user we off-board, click the edit user button, wait for it to load all the info and then rename their display name that way.  Sometimes as well, if I'm too quick to edit their display name when it comes up in CIPP, I have found that CIPP is still loading information about the user even though I can start editing.  I'll be half way through renaming the user when CIPP finalizes the loading of the different user data and reverts what I had typed causing me to have to re-type it and then save the edit.  
I think this could be executed a couple of different ways.  In the off-boarding wizard, you could have it coded as an option to add "z(Archived)" to the beginning of the users display name when you select the "convert to shared mailbox" option.  Or you could have an option where you ask the admin what they want to append/prepend to the display name as a separate off-boarding option and take their input to add to the display name.

### PowerShell commands you would normally use to achieve above request

Get-MsolUser -UserPrincipalName user@domain.com | Set-MsolUser -DisplayName ("z(Archived) " + $_.DisplayName)

**Comment by KelvinTegelaar** [comment]
this has been a repeated request - we don't do this as everyone is asking for something else. Some want to prepend, some want to append, some want to send a custom property, some want to change the middle name, some want to change the manager field. Because there are too many permutations we suggest to do this by hand.
