### ISSUE TITLE
[Feature Request]: Standards - Deploy standard user to all tenants

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2624]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Our organization struggles with getting a standard MSP user across all of our tenants.  We acquired a couple of MSPs and the admin Display Name and other properties are not standardized, leading to confusion from client users and employees. 

We want to deploy a standard user with the following properties configured from CIPP:
- Display Name, as well as First Name and Last Name
- Hidden from GAL
- Recovery email 
- Other Mails
- MailTip in Exchange
- Admin roles

### PowerShell commands you would normally use to achieve above request

Update-MgUser
https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users/update-mguser?view=graph-powershell-1.0

**Comment by HappyEarthDay** [comment]
@KelvinTegelaar  @JohnDuprey 
Can I attach the following to this feature request? Happy to make a separate one if that makes it easier for you.

We just used the CIPP API credentials to create a standard **contact** for our MSP support email address.  Since the Standard GA account should be hidden from the GAL, we need to publish the MSP's support contact information so users know where to email for support.  We deployed a contact with the following properties (where MSP has their info):

DisplayName "MSP Support" 
FirstName "MSP" 
LastName "Support" 
ExternalEmailAddress 'support@endsight.net' 
ModerationEnabled $false -Name "MSP Support" 
Name "MSP Support" 
Company "MSP" 
WebPage "https://www.MSP.com"  
Phone "MSP TELEPHONE" 
OtherTelephone "MSP TELEPHONE"  
Title "IT Support" 
CountryOrRegion "US" 
StateOrProvince "CA"

Using New-MailContact and Set-Contact/Set-MailContact Cmdlets

**Comment by JudgeDreddKLC** [comment]
So we set up a GA for every customer, we configure that GA to forward all e-mails to a client shared mailbox on our tenant. That shared mailbox then forwards e-mails to the helpdesk. 

How can we automate creation, configuration, and administration of this GA via a template, using variables to create the user on each tenant, configure forwarding to their designated e-mail at our tenant, create the shared mailbox in our tenant, etc. ?

Why do we use a shared mailbox? We use that shared mailbox for all alerts for the tenant, if we ever need to stop those coming in to our helpdesk, we're in full control of that shared mailbox - and we can shut it down centrally. 

I'd love to be able to manage both our GA accounts and Global Reader through a CIPP standard.

**Comment by HappyEarthDay** [comment]
> So we set up a GA for every customer, we configure that GA to forward all e-mails to a client shared mailbox on our tenant. That shared mailbox then forwards e-mails to the helpdesk.
> 
> How can we automate creation, configuration, and administration of this GA via a template, using variables to create the user on each tenant, configure forwarding to their designated e-mail at our tenant, create the shared mailbox in our tenant, etc. ?
> 
> Why do we use a shared mailbox? We use that shared mailbox for all alerts for the tenant, if we ever need to stop those coming in to our helpdesk, we're in full control of that shared mailbox - and we can shut it down centrally.
> 
> I'd love to be able to manage both our GA accounts and Global Reader through a CIPP standard.

We used to do this as well, but during our client's external audits, and they always flag external forwarding as an issue if it is enabled on _any_ mailbox.

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
