### ISSUE TITLE
[Feature Request]: Retreive OneDrive Automount URLs

### ISSUE THREAD

**Issue by STG-Tanner** [KelvinTegelaar/CIPP#2625]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The ability to retrieve OneDrive Automount URLs for Sharepoint sites for easy deployment with methods like Intune and Immy.bot

https://learn.microsoft.com/en-us/sharepoint/use-group-policy#configure-team-site-libraries-to-sync-automatically

**Comment by KelvinTegelaar** [comment]
added in dev, with a copy button.
