### ISSUE TITLE
Links in CIPP to documentation returns a 404 page

### ISSUE THREAD

**Issue by greenlighttec** [KelvinTegelaar/CIPP#263]
**Describe the bug**
Specifically when being told your roles are outdated, and also I've seen in other areas too, there's a link included that points to https://github.com/KelvinTegelaar/CIPP/tree/master/Documentation/Roles.md which returns a 404

**To Reproduce**
1. Login with the wrong role assigned (reader)
2. Wait for the message "Error: We have introduced a new role management system. You are currently accessing the system as a unsupported role. Please remove the old role "reader" and change your role to "readonly", "editor", or "admin". Find the documentation about this here
3. Click on the word "here"
4. You'll get a 404

**Expected behavior**
It should link to a doc explaining the changes about the security roles.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] MS Edge
 - Version [e.g. 22] 95

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KelvinTegelaar** [comment]
Fixed
