### ISSUE TITLE
Delete toggle in Offboarding Wizard no longer functions

### ISSUE THREAD

**Issue by lancefogle** [KelvinTegelaar/CIPP#2634]
### Description

1. Go to Offboarding Wizard
2. Select a Tenant
3. Select a user to delete
4. Select delete user toggle
5. Select Next
6. Delete user is not shown in the list of selected options on the confirmation page
7. Select Submit anyways to confirm if UI bug
8. User is not deleted from M365 tenant so it is definitely not being "selected" even when toggled on.

All other functions of the offboarding wizard that have been tested appear to work as normal and deleting users has worked in the past with no changes to GDAP permissions, etc.

### Environment data

```
Non-sponsored instance
Front end version: 5.9.3
Back end version: 5.9.4
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by lancefogle** [comment]
"I confirm that I have checked the documentation thoroughly and believe this to be an actual bug."

**Comment by lancefogle** [comment]
![image](https://github.com/KelvinTegelaar/CIPP/assets/23724891/ac48b656-200e-48ff-a77e-f4d9cd4bdbfb)

**Comment by KelvinTegelaar** [comment]
Delete is missing from the list, but should execute, we've just tried one and it worked with just delete selected.

The list has been updated in dev.

**Comment by lancefogle** [comment]
I did try that with just delete selected on the user as well for the one that we were trying to delete and it did not delete them. It just resulted in a blank green box as below and the user still existed. I ended up going to the M365 admin center to manually delete.

![image](https://github.com/KelvinTegelaar/CIPP/assets/23724891/81c18ce4-51a7-4638-9b3f-73bf10da45a7)

**Comment by KelvinTegelaar** [comment]
Tried multiple options but we can't replicate this on the latest version. Can you try another test user?

**Comment by KelvinTegelaar** [comment]
cannot replicate.
