### ISSUE TITLE
365 License Reports Don't Distinguish NonProfit Licenses

### ISSUE THREAD

**Issue by ARainTech** [KelvinTegelaar/CIPP#2641]
### Description

When running a license report under "Tenant Administration > Reports > License Report" the license names do not properly report say whether it is a Nonprofit license or Commercial, and there is no column for that either. 

Example:
- "Microsoft 365 Apps for Enterprise (Nonprofit Staff Pricing)" will show as "Microsoft 365 Apps for Enterprise" in CIPP
- "Microsoft 365 Business Premium (Nonprofit Staff Pricing)" will show as "Microsoft 365 Business Premium" in CIPP

It would be nice if the license names were properly reported like they are in the CSP or if there could be columns in CIPP license report added for "Segment" specifying if this is Commercial or Nonprofit license. It would also be nice to have a column for "NCE" as yes/no instead of just "Term unknown or non-NCE license" that lacks clarity, but that's more of a feature request than an issue so I can add it as a feature request once this is resolved. 

Thanks!

### Environment data

```PowerShell
Self-hosted non-sponsored instance
```

**Comment by ARainTech** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

I could not find anything for non-profit or nonprofit in the documentation search link provided.

**Comment by KelvinTegelaar** [comment]
This is a feature request, not a bug, only sponsors can create FRs.
