### ISSUE TITLE
[Feature Request]: Defender Exceptions

### ISSUE THREAD

**Issue by mriga277** [KelvinTegelaar/CIPP#2650]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Looking for the ability to add exceptions to all tenants for defender features such as firewall and defender for endpoint. 

This would allow us to put in exceptions for RMM tools, firewall rules for things such as webex that may be deployed to all clients.

### PowerShell commands you would normally use to achieve above request

Through the UI. Manually.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs
