### ISSUE TITLE
[Feature Request]: Links to Documentation directly in the CIPP interface

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2651]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would love to see documentation links directly in the CIPP interface, especially for the integrations.  This is more of a nice to have, but also might help solve some issues and reduce your support tickets.  

For example, on the Hudu integration, maybe just have a tooltip or book icon at the top of the page that links back to https://docs.cipp.app/user-documentation/cipp/extensions/hudu

**Comment by KelvinTegelaar** [comment]
Talked about during Office Hours, this is there! :)
