### ISSUE TITLE
[Feature Request]: Hudu Integration - Optionally Sync policies/settings/reports into Hudu

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2652]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We'd love to optionally sync more things into Hudu assets.  For example, a full report/audit of settings and policies deployed to the M365 tenant.  Some things that may be cool to kick over to Hudu:

DNS Health Check results per domain (asset for each domain)
User reports
FULL MFA REPORT
Risky Users
Security Defaults (Enabled or Disabled)
Total Mailboxes
Total Inactive Mailboxes Last X Days
REGISTERED APPLICATIONS
ENTERPRISE APPLICATIONS
DEVICE COMPLIANCE POLICIES
DEVICE CONFIGURATION POLICIES
DEVICE ENROLLMENT CONFIGURATIONS
MANAGED APP POLICIES
Conditional Access Policies
Teams
SharePoint Sites
List of Email Protection Policies, Including Anti-Spam, Anti-Phishing, Anti-Malware, etc.
Defender Configuration / Deployment Status

I'm sure there is a bunch of additional things in CIPP that I would love to have in Hudu automatically as well, like pretty much all of the built-in CIPP reports. The cool thing about Hudu is we can easily share Assets with clients via the Portal, so we'd love to do that for some of these reports (especially MFA report).  I don't think we can add to Portal via API, but we can add to the Portal manually after it is created by an integration.

**Comment by MWGMorningwood** [comment]
SYNC ALL THE THINGS!
