### ISSUE TITLE
Add group template failed

### ISSUE THREAD

**Issue by 2azure** [KelvinTegelaar/CIPP#2658]
### Description

When I try to add a group template I get the warning that I need to enter a displayname, while it is entered. 

Group Template Creation failed: You must enter a displayname

![image](https://github.com/KelvinTegelaar/CIPP/assets/53003664/e1400660-b092-46cf-8a10-d631dbaa87fc)

### Environment data

```PowerShell
Non-sponsored instance
Frond end version number: 6.0.2
Back end version number: 6.0.2
Tried Tenant Cache Clear: false
Tried Toke cache clear: false
```

**Comment by 2azure** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, support issue. If you're a sponsor feel free to hit up the helpdesk.

**Comment by 2azure** [comment]
Not a sponsor yet, evaluating the product. I noticed more issues in the closed section around this topic. Might I suggest to add the missing part to the documentation or the FAQ?
