### ISSUE TITLE
Issue loading log book

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2660]
### Description

Since the latest update we have had issues loading the logbook. Its intermittent, but doesnt load more than it does load.

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/6c6b744f-34ba-484b-afed-be8f644cd950)

### Environment data

```PowerShell
Both front and backend:
Current: 6.0.2
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
