### ISSUE TITLE
Setting unified audit log

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2661]
### Description

This maybe missing an anchor 

`Failed to apply Unified Audit Log. Error: |Microsoft.Exchange.Configuration.Tasks.CmdletProxyNotAvailableException|Cmdlet needs proxy. Current Server FQDN : LO0P123MB6111.GBRP123.PROD.OUTLOOK.COM, Required Server FQDN : CWXP123MB1734.GBRP123.PROD.OUTLOOK.CO`

### Environment data

```PowerShell
Front and backend
Current: 6.0.2
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in hotfix
