### ISSUE TITLE
Halo PSA Tickets

### ISSUE THREAD

**Issue by BNWEIN** [KelvinTegelaar/CIPP#2662]
### Description

Seems the latest update may have broken CIPP's ability to log a ticket in HaloPSA

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/aca53e30-28eb-42e2-ad01-934906c03aed)

### Environment data

```PowerShell
Front and Backend
Current: 6.0.2
```

**Comment by BNWEIN** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Solved in dev
