### ISSUE TITLE
Group Template Creation Fails due to Displayname missing even when it is provided.

### ISSUE THREAD

**Issue by SHurley-BECA** [KelvinTegelaar/CIPP#2663]
### Description

1. Go to Identity Management > Group Templates
2. Click Add Group Template button
3. Type in a display name and description.
4. Select group type (Security Group chosen).
5. Click Add Group Template button.
6. Receives error message "You must enter a displayname".

![image](https://github.com/KelvinTegelaar/CIPP/assets/174642359/fe8a636a-de98-403e-badf-54b5bb6c619d)

### Environment data

```PowerShell
Non-sponsored
Front-End Version: 6.0.2
Back-End Version: 6.0.2
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false

In Invoke-AddGroupTemplate.ps1 changed $Request.body.displayname to $Request.body.displayName
```

**Comment by BNWEIN** [comment]
I just tested this in my environment and it worked fine

![image](https://github.com/KelvinTegelaar/CIPP/assets/28929905/eb20b653-9d19-4c4f-a32c-ac3662c40c8e)

Could you show me a picture/screenshot with Dev Tools open as per my screen shot above?

**Comment by SHurley-BECA** [comment]
![image](https://github.com/KelvinTegelaar/CIPP/assets/174642359/33bc30da-787b-411e-9cdc-e6d332dfe6be)

**Comment by SHurley-BECA** [comment]
Also, had a similar issue with guid vs GUID in Invoke-ExecEditTemplate.ps1

**Comment by KelvinTegelaar** [comment]
Fixed in dev
