### ISSUE TITLE
[Feature Request]: Microsoft365 'Unified' Group Creation

### ISSUE THREAD

**Issue by rwllr** [KelvinTegelaar/CIPP#2664]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Unified modern groups are the future of groups and existing groups can already be modified by CIPP.
This is possible and documented in the Graph docs, so should be an easy addition to make.

https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http

`POST https://graph.microsoft.com/v1.0/groups
Content-type: application/json

{
  "description": "Self help community for library",
  "displayName": "Library Assist",
  "groupTypes": [
    "Unified"
  ],
  "mailEnabled": true,
  "mailNickname": "library",
  "securityEnabled": false,
  "visibility": "Public"
}`

Making a group Teams enabled is a separate API call so should probably a separate API call and so should probably be a separate request.

**Comment by KelvinTegelaar** [comment]
There is a way to add Microsoft teams groups in the teams section, we also added this to both the groups and the group templates.
