### ISSUE TITLE
"Set the destination email for user reported emails" standard not working as intended

### ISSUE THREAD

**Issue by kakaiwa** [KelvinTegelaar/CIPP#2666]
### Description

Currently, the **Set the destination email for user reported emails** standard does not work as expected. This is most likely because the standard currently only updates ReportSubmissionRule and not the ReportSubmissionPolicy.

https://learn.microsoft.com/en-us/defender-office-365/submissions-user-reported-messages-custom-mailbox

Expected result: the **Add an exchange online mailbox to send reported messages to** value for user submission policy should be the value configured in the standard
Actual result: the **Add an exchange online mailbox to send reported messages to** value is empty even after the standard is ran. Log shows **User Report Destination Email is already set to ...**

### Environment data

```PowerShell
Sponsored
Front end version: 6.0.1
Back end version: 6.0.0
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by kakaiwa** [comment]
I would like to work on this please

**Comment by KelvinTegelaar** [comment]
Microsoft has merged these contacts into only that contact. The others are no longer being used.

**Comment by KelvinTegelaar** [comment]
My comment was about another standard entitely. Nevermind

**Comment by kakaiwa** [comment]
@KelvinTegelaar Thank you very much for checking. I might also consolidate the 2 standards into a single standard. I can see a situation where the Invoke-CIPPStandardUserReportDestinationEmail runs before Invoke-CIPPStandardUserSubmissions, causing an error because the policy doesn't exist yet.

**Comment by KelvinTegelaar** [comment]
implemented in dev, good job on your first pr! if you are in Discord tag me so I can mark you a contributor.
