### ISSUE TITLE
[Feature Request]: Defender Standard - Add additional email to "User requested to release a quarantined message" alert policy

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2667]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Currently, when a user requests a message from quarantine, it defers to the built-in alert policy (called "_User requested to release a quarantined message_") in the Security portal, which has the default value of '_TenantAdmins_.'  We can manually go to the alert policy and update it with additional addresses and it works with external email addresses.  Our organization wants to use this to control where the requests go when users request an email be released.  

To edit this setting in the GUI: M365 Security Center, go to: _Email & Collaboration < Policies & Rules< Alert Policies< User requested to release a quarantined message_

Ideally, this would be in a standard, so we could just input our destination email address, like support@MSP.com, and have the alert policy be updated across all tenants. 

### PowerShell commands you would normally use to achieve above request

~~From my research, it _might_ not be possible to edit **built-in** alert policies via API, but if there is a way, I'm sure you all could figure it out.~~  Confirmed [here that you can't edit the default alert policy with this cmdlet](https://learn.microsoft.com/en-us/powershell/module/exchange/set-protectionalert?view=exchange-ps#:~:text=Note%3A%20You%20can%27t%20use%20this%20cmdlet%20to%20edit%20default%20alert%20policies.%20You%20can%20only%20modify%20alerts%20that%20you%20created%20using%20the%20New%2DProtectionAlert%20cmdlet.), but maybe there is any other way via direct graph? 
https://learn.microsoft.com/en-us/powershell/module/exchange/set-protectionalert?view=exchange-ps

**If it is not possible to edit the built-in policies,** I wonder if CIPP could instead create and manage a new standard Alert Policy that does the same thing using: https://learn.microsoft.com/en-us/powershell/module/exchange/new-protectionalert?view=exchange-ps

**Comment by KelvinTegelaar** [comment]
added in dev
