### ISSUE TITLE
Device Management > Configuration Policies > actions > Delete

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#2668]
### Description

When deleting a policy within Device Management > Configuration Policies > Delete, click the 3 dots, then deleting the policy works.

When using the check box to tick policies, then selecting actions and then "delete policy" it says 
Confirm
Are you sure you want to convert these users to a shared mailbox?

### Environment data

```PowerShell
Front
6.0.2
Back
6.0.3
```

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
https://github.com/KelvinTegelaar/CIPP/pull/2673
