### ISSUE TITLE
Permissions Check Spelling Mistake

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#2669]
### Description

When running a permissions check, one of the permissions is not spelled correctly. It should read MailboxSettings.ReadWrite

<img width="1347" alt="image" src="https://github.com/user-attachments/assets/f0bcd5dc-021b-4780-a897-135ff0ae2242">

### Environment data

```PowerShell
Not applicable.
```

**Comment by KelvinTegelaar** [comment]
Fixed in dev, thanks!
