### ISSUE TITLE
[Feature Request]: Set Language / localization for shared mailboxes

### ISSUE THREAD

**Issue by weservit-raoul** [KelvinTegelaar/CIPP#2670]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Shared mailboxes are being created with English language and localization. All our customers are from The Netherlands and we need to change the settings for each Shared Mailbox. Would be a lot easier if we can change it from CIPP.

**Comment by KelvinTegelaar** [comment]
Added in dev.
