### ISSUE TITLE
[Feature Request]: Chocolatey support custom package argumetns

### ISSUE THREAD

**Issue by kosli** [KelvinTegelaar/CIPP#2671]
It would be great if it would be possible via CIPP UI and/or the install.ps1 to provide arguments to the Chocolatey to be installed. 
e.g. for [Adobe reader](https://community.chocolatey.org/packages/adobereader) you can provide `/OverwriteInstallation `
or for the [Choco Upgrade all at](https://community.chocolatey.org/packages/choco-upgrade-all-at) package we could provide a custom time for the task to run etc etc.
`choco install choco-upgrade-all-at --params "'/TIME:23:00'"`
instead of the current
`choco install choco-upgrade-all-at`

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
