### ISSUE TITLE
[Feature Request]: Standards for Teams policies

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2674]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have standards for Exchange, SharePoint, etc, but not many for Teams.  

- We want to disable file and storage options that are available in the Teams Admin Center < Teams < Teams settings Files tab: 
![image](https://github.com/user-attachments/assets/243b91eb-5eda-4f50-b2b4-fd928f6f7264)
- We want to disable both of the options for external access under Teams Admin Center < Users < External access:
- Teams accounts not managed by an organization (this prevents CONSUMER accounts from being able to message the org - commonly used for phishing)
- Skype users
![image](https://github.com/user-attachments/assets/ddefbe14-0cb7-4d43-b7a5-d697552432af)

We'd like to be able to set the value for _Choose which external domains your users have access to_: 
![image](https://github.com/user-attachments/assets/3369df33-1f0a-417b-a14e-66305c11c166)

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/powershell/module/teams/set-csexternalaccesspolicy?view=teams-ps
    Set-CsExternalAccessPolicy -EnableOutsideAccess $False
    Set-CsExternalAccessPolicy -EnableFederationAccess $False
    Set-CsExternalAccessPolicy -EnablePublicCloudAccess $False
    Set-CsExternalAccessPolicy -EnablePublicCloudAudioVideoAccess $False

https://learn.microsoft.com/en-us/powershell/module/teams/set-csteamsclientconfiguration?view=teams-ps
Set-CsTeamsClientConfiguration
[-AllowDropBox <Boolean>]
[-AllowEgnyte <Boolean>]
[-AllowBox <Boolean>]
[-AllowGoogleDrive <Boolean>]
[-AllowShareFile <Boolean>]

**Comment by OfficialEsco** [comment]
Been looking into this over the last 3 months, Teams uses a rusty old API, so i've requested this https://github.com/KelvinTegelaar/CIPP/issues/2526 which needs to be in place before we can do anything.

**Comment by KelvinTegelaar** [comment]
Added in dev
