### ISSUE TITLE
Favorites not sticking after browser reload

### ISSUE THREAD

**Issue by swanny246** [KelvinTegelaar/CIPP#2677]
### Description

Favorites are not sticking around on the left-hand navigation bar after your browser reloads. This has persisted across multiple installs of CIPP now.

1. Go to Settings > CIPP > User Settings
2. Select "Favorite Menu Items" to add to the navigation bar
3. Either "Save Settings" or "Save for all users", doesn't matter which you choose.
4. Favorites will appear.
5. Close and reopen any CIPP tabs you have. Favorites will no longer appear under the Home.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 6.0.2
Back end version number: 6.0.4
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by swanny246** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Known issue, hotfix available for sponsors, you can hit save twice.
