### ISSUE TITLE
[Feature Request]: Bulk delete contacts

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2679]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We sometimes add contacts in bulk, and would like a way in CIPP to remove contacts in bulk.  We have the ability to add contacts already, but we are not currently able to select multiple at once and bulk delete.  Is this a possibility? 

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/remove-mgcontact?view=graph-powershell-1.0

remove-mgcontact

**Comment by BNWEIN** [comment]
@OfficialEsco added to Dev
