### ISSUE TITLE
Link to Tenant Subscription Page in CSP.

### ISSUE THREAD

**Issue by lbrunton0** [KelvinTegelaar/CIPP#268]
**Is your feature request related to a problem? Please describe.**
So I'm hoping to eventually have our Operations working out of this portal more then the CSP Portal. We sell customers Licensing through the CSP. 

**Describe the solution you'd like**
Ideally we'd want to be able to Add and Remove Licenses automatically as we're adding/removing them from users, to their subscriptions through the portal, and that's a big ask, and probably mostly overkill though it would be a very nice to have.
Then I'd probably also want a "standard" to remove any unused licenses, from their subscriptions.

**Describe alternatives you've considered**
The Simplest solution at this point would be on the Tenant Administrations -> Administrations -> Tenants view, If we can add a link that would take us direct to the customers Subscriptions under the CSP Portal.

If we have a tenant who's ID is:  12222222-3333-4444-5555-66666666666

It appears the link would currently be: https://partner.microsoft.com/commerce/customers/12222222-3333-4444-5555-66666666666/subscriptions

**Comment by KelvinTegelaar** [comment]
This is a no for now, but we will add the access link to the tenant administration page soon(tm)
