### ISSUE TITLE
[Feature Request]: Edit existing contacts

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2680]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We can currently add a contact and remove individual contacts via CIPP, but we can't update existing contacts.  We'd love to be able to use CIPP to update an existing contact.  

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/update-mgcontact?view=graph-powershell-1.0

update-mgcontact

**Comment by BNWEIN** [comment]
I will work on this

**Comment by BNWEIN** [comment]
Added to Dev.
