### ISSUE TITLE
[Feature Request]: Alert on Non Compliant Devices And/Or Compliance Policies in Intune

### ISSUE THREAD

**Issue by hfit-manage** [KelvinTegelaar/CIPP#2686]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The native compliance policies in 365 allow you to configure a notification that goes to the end user and an additional recipient. For an MSP, this isn't particularly helpful as we would rather that the user didn't receive any notification and it came straight to us. I can't find any sort of workaround to achieve this with native Microsoft functionality.

It would be great if CIPP's alerting mechanism could alert on a non compliant device in intune.

To go a step further, we use individual compliance policies (Bitlocker/AV etc) separated out rather than having one compliance policy that has all the compliance checks in - this makes it easy to see why something is non compliant. It would be awesome if the alerting could even report on which compliance policy the device is non compliant in and/or configure it for specific compliance policies so you only get alerts for compliance policies you care about.

This has various benefits, including MSP's receiving centralised alerts for multiple tenants at once and quick configuration. Even if we took the approach to go the native way, configuring the alerts for many tenants and compliance policies is quite tedious and time consuming.

**Comment by KelvinTegelaar** [comment]
added in dev
