### ISSUE TITLE
[Feature Request]: Ability to Exclude in MFA Alerts

### ISSUE THREAD

**Issue by hfit-manage** [KelvinTegelaar/CIPP#2687]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Unfortunately, there are some cases we have to make exceptions/exclusions in conditional access for MFA. For example for service accounts that don't currently support it and would entirely break it. Or for other possible MFA exceptions. Whilst I don't advocate not having MFA on anything there are exceptions that have to be made in business.

In the current e-mail alert it lists all accounts with no MFA which works correctly. The real ask here is if there's a way to exclude certain accounts from triggering the alert so we don't get accounts that require no action, as from an alerting point of view we only want to receive these alerts to the service desk if they're actionable to avoid alert fatigue/noise.

**Comment by KelvinTegelaar** [comment]
No, CIPP is dedicated to making MSPs more secure, most MSPs would use any excuse to say a account has to be excluded from MFA, and would force the CEO accounts etc in the exclusion list. By not offering any exclusion it forces MSPs to make a choice. 

As modern authentication is now mandatory for all M365 services except SMTP **all** applications that currently work with M365 work with MFA, as modern authentication makes sure of this, so there is no more reason for these type of exclusions.
