### ISSUE TITLE
FEATURE REQUEST: 

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#2698]
It would make more sense after the wizard completes to have the "Submit" button change. Maybe to "Start again" that takes you to the back of the wizard.

![image](https://github.com/user-attachments/assets/b141b2c0-ba9d-40da-85a1-b96dab659ec9)

**Comment by KelvinTegelaar** [comment]
Incomplete

**Comment by procradminator** [comment]
Weird! Comment of "incomplete" followed by completing the issue.
