### ISSUE TITLE
[Feature Request]: Standard for "Disable Automatic Email Forwarding" & reporting on mailboxes with automatic forwarding

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2699]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

During external audits, one of the most common things that arises is that external forwarding is enabled on any mailbox. 

By default, Microsoft now disables email forwarding (new tenants only) tenant-wide in the Security portal < Policies and Rules < Threat Policies < Anti-Spam < default Outbound policy.  By default, this is set to _System-controlled_, which typically disables email forwarding for all users. I would like an option to specifically change this value:  

![image](https://github.com/user-attachments/assets/3aa569fa-9887-4fb5-920c-c0d0617728cb)

CIPP is already editing this policy to update the standard called "**Set Outbound Spam Alert e-mail**"

We would include this standard in a template for a subset of our clients. We would also love a report of users with automatic forwarding enabled, along with the recipient address. If that information could be made available via API and in the CIPP UI, it could save us a bunch of time on remediations. 

### PowerShell commands you would normally use to achieve above request

I can't find the PowerShell cmdlet/switch for this, but I also can't find where CIPP is already setting the **Outbound Spam Alert e-mail** on the same policy.

https://learn.microsoft.com/en-us/defender-office-365/outbound-spam-policies-external-email-forwarding
^ Information about this setting and info about how to report on it

**Comment by kris6673** [comment]
Set-HostedOutboundSpamFilterPolicy -AutoForwardingMode [Automatic, Off, On]

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
@HappyEarthDay Alright PR in for both things :)
The forwarding options for each mailbox was added as selectable colums under Email & Exchange -> Administration -> Mailboxes. See the screenshot below
![billede](https://github.com/user-attachments/assets/f4ff774e-d645-46c2-ab2a-e4abeef6b771)

**Comment by KelvinTegelaar** [comment]
added in dev
