### ISSUE TITLE
[Feature Request]: Simple Phishing Simulation through Microsoft Graph API

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2700]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

KnowBe4 and Sophos recently added a method for sending mail internally for phishing simulation purposes, what they call "_Direct Message Injection_." This newer method uses the Graph API to deliver messages directly into the recipient's Inbox, bypassing all filtering, including SafeLinks, Safe Attachments, Anti-spam, etc.  This method will likely become industry-standard method for phishing simulation emails due to the much easier configuration within the tenant (no whitelisting or account creation required).  
- https://docs.sophos.com/central/customer/help/en-us/ManageYourProducts/PhishThreat/SystemSettings/PTM365DirectDelivery/index.html
- https://support.knowbe4.com/hc/en-us/articles/360054494394-Direct-Message-Injection-DMI-Configuration-Guide

We would love to have some very basic functionality in CIPP UI for phishing simulation:
- Specify sender (can be internal or external)
- Select multiple recipients (existing mailbox list)
- Paste in HTML email body
- Simple subject line

Use the below logic with Graph to loop through each recipient and deliver the message directly to the recipient's inboxes. 

**Notes:**
- I personally don't need link-click tracking and can use a separate service for that. 
- The ability to save HTML templates would be nice, but not required. 

### PowerShell commands you would normally use to achieve above request

This process starts and ends in the target (recipients) mailbox, using 3 Graph calls.  
1. POST: Create draft and convert it so it appears as a new inbound - draft_url: https://graph.microsoft.com/v1.0/users/{to_email}/messages
2. GET: Get the users Inbox ID so we can move the draft.   inbox_url = https://graph.microsoft.com/v1.0/users/{to_email}/mailFolders/Inbox
3. POST: Move the draft from the drafts folder to the inbox.   move_url:  https://graph.microsoft.com/v1.0/users/{to_email}/messages/{draft_message_id}/move

There's an extended property in the message object in this first call that is important (_Convert draft to new email_): 
```
message = {
        "subject": subject,
        "body": {"contentType": content_type, "content": body_content},
        "toRecipients": [{"emailAddress": {"address": to_email}}],
        "from": {"emailAddress": {"address": from_email, "name": from_name}},
        "singleValueExtendedProperties": [
            {
                "id": "Integer 0x0E07",  # 2.792 PidTagMessageFlags - Convert draft to new email
                "value": "4",  # status = submitted
            },
            {
                "id": "Integer 0x0017",  # 2.739 PidTagImportance
                "value": "2",  # High
            },
        ],
    }

```

**Comment by KelvinTegelaar** [comment]
Decided against this, to do this we'd need write access into mailboxes, and we're not comfortable with having that enabled by default. This is a no for now. :)

**Comment by MWGMorningwood** [comment]
Could approaching the defender for office simulations with standards/templates possibly be the way?

**Comment by HappyEarthDay** [comment]
> Could approaching the defender for office simulations with standards/templates possibly be the way?

Can you explain this more?  What do you mean?

**Comment by MWGMorningwood** [comment]
@HappyEarthDay I'll pop open a new FR (and maybe PR) for it next week. It's a bit out of scope for this one.
