### ISSUE TITLE
[Feature Request]: Certain 'non-teams' licenses do not show on the CIPP Users page.

### ISSUE THREAD

**Issue by AlexJamesHaines** [KelvinTegelaar/CIPP#2704]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

If you are using the 'non-teams' version of a SKU it does not show up that the user is licensed within CIPP.

The known affected SKU and ID are:

**Microsoft 365 Business Basic (no Teams) -> 21502a13-c8dc-4744-be9c-177fd9d2eafc
Microsoft 365 Business Standard (no Teams) -> 5a1c7b8d-0739-4ca8-bf69-ec87e69133ac
Microsoft 365 Business Premium (no Teams) -> 00e1ec7b-e4a3-40d1-9441-b69b597ab222**

Whilst some 'non-teams' SKU are listed in the Microsoft documentation below, my current working theory is that those are EEA versions and that the SKU listed above are non-EEU i.e. for the UK.

https://learn.microsoft.com/en-us/entra/identity/users/licensing-service-plan-reference
https://api.partnercenter.microsoft.com/internal/v1/customers/{any_tenant_id_it_seems}/products/all/skus?targetSegment=Commercial&targetView=OnlineServices

![image](https://github.com/user-attachments/assets/66e13124-0e36-4d92-8d5c-f8a24a74d6eb)
The above shows the licenses as displayed in the tenancy.

Fixing this obviously stops any issue whilst working in CIPP thinking that a user is not correctly licensed.

The biggest issue here is that the SKU are not listed on the Microsoft documentation so will need to be manually added until they are. Whilst it wouldn't help with this issue as the SKU are not on the list, on Discord, Bobby suggested that it may be beneficial to have this moved into a table instead of JSON and then have it autoupdate in the future.

**Comment by KelvinTegelaar** [comment]
Fixed by @kris6673  I think, just waiting for his confirmation.

**Comment by kris6673** [comment]
I cannot find the SKU ID's you are referring to, nor the names.  
I can find these in the docs tho: Microsoft 365 Business Standard EEA (no Teams) - ffa3a2a0-3820-462a-aa81-8a4d741f0cba

From where did you get the SKU ID's? :)

**Comment by AlexJamesHaines** [comment]
https://admin.microsoft.com/Adminportal/Home#/licensedetailpage/21502a13-c8dc-4744-be9c-177fd9d2eafc
https://admin.microsoft.com/Adminportal/Home#/licensedetailpage/5a1c7b8d-0739-4ca8-bf69-ec87e69133ac
https://admin.microsoft.com/Adminportal/Home#/licensedetailpage/00e1ec7b-e4a3-40d1-9441-b69b597ab222

![image](https://github.com/user-attachments/assets/b72417e9-1c05-41e3-bb64-2c7e04b02307)

As I previously alluded to, I have a feeling that these will be UK specific SKUs but IDK.

**Comment by KelvinTegelaar** [comment]
The ids listed are not SKUIDs according to Microsoft, but uniquel IDs for that specific tenant.

**Comment by KelvinTegelaar** [comment]
The next version of CIPP will show the GUID if it cant be found, so we can add it later on. For now this is case closed :)

**Comment by AlexJamesHaines** [comment]
During the CIPP Office Hours yesterday I mentioned this issue and Kelvin let me know that Microsoft acknowledged this and that they had made a mistake and that you just needed to re-order the products to get the correct SKUS. Do we know when the correct SKU became available because an order I placed on the 06th August still doesn't show up in CIPP.

![image](https://github.com/user-attachments/assets/e37cd091-0ad4-48f2-80a6-f733818298f4)

**Comment by AlexJamesHaines** [comment]
And just an update for the record that a brand new licenses ordered today with a completely different CSP also does *not* show up in CIPP. Is it possible that the changes to SKU have not been communicated to the CSP?

How would one find out what the 'actual' global SKU is so that I can find that out for troubleshooting?

**Comment by kris6673** [comment]
```powershell
Get-MgSubscribedSku | Select-Object SkuPartNumber, SkuId | ft -AutoSize
```
The above command should show the right SKU

**Comment by ce-frank** [comment]
We just noticed this on our CIPP.
Today from PAX8 we purchased subscription named "Microsoft 365 Business Standard (no Teams) [New Commerce Experience]"
PAX8 shows SKU MST-NCE-WLJ-C100
CIPP shows skuId 5a1c7b8d-0739-4ca8-bf69-ec87e69133ac
I can apply the license to a user in CIPP; license name is all caps with underscore between words MICROSOFT_365_BUSINESS_STANDARD_NO_TEAMS but don't see it on user list page.

**Comment by AlexJamesHaines** [comment]
> Get-MgSubscribedSku | Select-Object SkuPartNumber, SkuId | ft -AutoSize

I appreciate your efforts so far on this @kris6673 but unfortunately the #3329 does not fix our issue and I think it is because the edits in there mainly allowed for E3 style licenses. We are having trouble with the Basic, Standard and Premium versions.

I got around to running the command you provided above but this was new to me. For anyone else who may run this I was unable to do so without granting Directory.Read.All access during connection:

`Connect-MgGraph -Scopes "Directory.Read.All"`

The output showed the following:

`SkuPartNumber                               SkuId
-------------                               -----
Microsoft_365_Business_Basic_(no Teams)     21502a13-c8dc-4744-be9c-177fd9d2eafc
Microsoft_365_ Business_ Premium_(no Teams) 00e1ec7b-e4a3-40d1-9441-b69b597ab222
MICROSOFT_365_BUSINESS_STANDARD_NO_TEAMS    5a1c7b8d-0739-4ca8-bf69-ec87e69133ac`

The last one on that list matches @ce-frank output and we also use PAX8 in the UK.
@KelvinTegelaar had previously suggested that Microsoft were saying that these were unique IDs per tenant but this does not appear to be the case.

Thoughts?
