### ISSUE TITLE
[Feature Request]: APP NinjaOne MSP App for auto deployment

### ISSUE THREAD

**Issue by DigitalDynamicsAus** [KelvinTegelaar/CIPP#2709]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Under the Intune section we would like to deploy NinjaOne. We see there are other RMM Apps on it already. We would need to be able to specify a numeric based Organization ID and a Location ID, so we can link customers' Intune to the Ninja organization.

### PowerShell commands you would normally use to achieve above request

This does not work 100% due to some API errors, but this is the rough code for what we want to accomplish.
Param($Location, $OrgID)

#Get Acess Token
$tokenUrl = "https://app.ninjarmm.com/ws/oauth/token"
$clientID = ""
$clientSecret = ""
$scope = "management"

Start-Process -FilePath "msiexec" -ArgumentList "/i "$msiFilePath" /qn" -Wait
Start-Sleep 60

**Comment by Cyclone47** [comment]
Hello,

I would also love to see Ninja RRM as MSP app. Can someone please re-open this? 

I think this could work by using the Copy link feature when creating an Installer

<img width="579" height="481" alt="Image" src="https://github.com/user-attachments/assets/903e8dd4-ef72-4d9c-b66d-94da02c07f2c" />

The link copied would look like this
https://eu.ninjarmm.com/agent/installer/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/11.0.5792/NinjaOne-Agent-XXXXXXXXXXX-Intune-Auto.msi

I believe this could work like 

- Select MSP Tool: Ninja RRM
- Intune Application Display Name
- MSI URL: https://eu.ninjarmm.com/agent/installer/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/11.0.5792/NinjaOne-Agent-XXXXXXXXXXX-Intune-Auto.msi


Also see similar case: https://github.com/KelvinTegelaar/CIPP/issues/2066

**Comment by DigitalDynamicsAus** [comment]
I read the fishbowl notes and I thought they said, they did every feature request! I checked for this MSP App immediately!! I'll open a new one as it was github that auto shut it!
