### ISSUE TITLE
[Feature Request]: Don't include null lines in Risky Users/Risk Detections

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2710]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

This is not really a feature request but a quest for a frontend magician...
When you sort Risky Users and Risk Detections by newest date on All Tenants you get a bunch of null lines from tenants which do not have a license for the feature. I'd like these lines to be hidden.

**Comment by KelvinTegelaar** [comment]
The data is actually stored in the CIPPStatus and Tenant column, you don't want to fail silently but show the user that the tenant doesn't have a license, because of that I auto-add the two columns now if all tenants is selected. That solves this. :)
