### ISSUE TITLE
[Feature Request]: Edit Room

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2711]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like the ability to edit Rooms.

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
Bump to keep this open from the triggerhappy closing monster that is github-actions

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
