### ISSUE TITLE
Cannot rename tenant from CIPP

### ISSUE THREAD

**Issue by MrNickIE** [KelvinTegelaar/CIPP#2718]
### Description

Administration
Tenants
Edit Tenant.
Change Name
Appears to work, but does nothing.

Would like this to actually rename the tenant in Entra please.  No way to do this in CIPP

### Environment data

```PowerShell
Sponsored 
Latest: 6.1.0
Current: 6.1.0
```

**Comment by MrNickIE** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by MrNickIE** [comment]
Duplicate of https://github.com/KelvinTegelaar/CIPP/issues/71

**Comment by KelvinTegelaar** [comment]
No longer possible, Microsoft saves the name after creating a relationship. Only way to edit this is to remove relationships, change the tenant name, and create new relationships. You'll have to ask MS for the ability to have this back. :)

**Comment by MrNickIE** [comment]
Fair.  Though sucky :)
