### ISSUE TITLE
[Feature Request]: Add a feature to edit existing Allowed Countries and IP lists already assigned to CA policies

### ISSUE THREAD

**Issue by MrNickIE** [KelvinTegelaar/CIPP#2719]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We used Named locations for our customers.  We have the Allowed Countries in our existing Intune templates. 

IMAGE SENT IN EMAIL

We need to be able to edit these lists and countries via CIPP so our engineers do not need to keep going in and out of the tenant.  We also would LOVE if the feature always left in place a "home country" that we set within our parameters in CIPP.

**Comment by KelvinTegelaar** [comment]
added in dev.
