### ISSUE TITLE
FEATURE REQUEST: Change permissions on user calendar 

### ISSUE THREAD

**Issue by AntoJUICT** [KelvinTegelaar/CIPP#272]
**Is your feature request related to a problem? Please describe.**
When we need to change the permissions on a end users calendar we always use powershell to change it. For example user1 needs auditor rights on the calendar of user2. 

**Describe the solution you'd like**
I would be nice to see a interface to change/add/remove permissions on the calendar of a specific user.

**Describe alternatives you've considered**
The alternative is to use powershell. This is how we change it at the moment.

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
@AdamWillford  If you are, please place this under the actions in Mailbox administration. We have a nice hamburger menu there in dev. :)
