### ISSUE TITLE
[Feature Request]: Add "Is Hidden" column to Mailbox Rules

### ISSUE THREAD

**Issue by AADAutomatisering** [KelvinTegelaar/CIPP#2720]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We recently had an issue where a user's mail was being forwarded, but we couldn't figure out why. After contacting support it appeared that there were some hidden rules that were enabled and kept forwarding the mail.
These rules were quite easy to get with `Get-InboxRule -IncludeHidden`, so I thought it would be nice to be able to see the hidden rules in CIPP too, and to add a column to show if a rule is hidden or not.

Having hidden rules can also pose a security risk if those emails are getting forwarded somewhere, but you can't easily find the rule that is forwarding it.

The code implementations seemed quite simple at first, but when i started looking into the CIPP-API code I don't think I could figure this one out on my own, but I'd be happy to help :)

### PowerShell commands you would normally use to achieve above request

`Get-InboxRule -IncludeHidden`

**Comment by kris6673** [comment]
Heya, inbox rules dont have a property to show if it's hidden or not, and you would have to get all the mailbox rules twice to do a compare. Getting these rules is already incredibly slow, and this would double the execution time
I'll add the switch to the current places the command is used, so it atleast shows the hidden ones too. Is that good enough? :)

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Fixed in dev
