### ISSUE TITLE
Departmental Alerts/Email Notification

### ISSUE THREAD

**Issue by JGizmoW** [KelvinTegelaar/CIPP#2721]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Many MSP's have departments like infrastructure, network, security, helpdesk/service desk. When specific alerts fire off they should goto the department they are related to. Right now its one list and everyone gets it. Would like to see when a specific alert happens you can select which email to send it to along with a webhook.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create frs
