### ISSUE TITLE
[Feature Request]: New standard to manage the read receipts setting on all mailboxes

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2722]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Spammers actively use **read receipts** to verify email addresses and track user behavior, and Microsoft recommends disabling them: https://support.microsoft.com/en-us/office/10-tips-on-how-to-help-reduce-spam-55f756e8-688b-41c3-a086-8f68ccc592f6#:~:text=Turn%20off%20read%20and%20delivery%20receipts

Our organization recommends disabling read receipts on all mailboxes and would like to do this with CIPP.  We want to set this value to **NeverSend** on all mailboxes.  However, I imagine that some clients would like to have these enabled, so having a dropdown for the three options (listed below) would be preferred so we can override them at the tenant level. 

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailboxmessageconfiguration?view=exchange-ps

`Set-MailboxMessageConfiguration kai@contoso.com -ReadReceiptResponse "NeverSend"`

-ReadReceiptResponse
The ReadReceiptResponse parameter specifies how to respond to requests for read receipts for the user in Outlook on the web. You can use the following values:

DoNotAutomaticallySend
AlwaysSend
NeverSend

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by kris6673** [comment]
Blocking read receipts on a mailbox level would be an extremely slow process and since the end goal is to block all read receipts, doing it with transport rules is far more efficient :)  
It's split into 2 rules and can be deploy via standards under Templates Standard Deployment: https://github.com/KelvinTegelaar/CIPP-API/pull/1021

**Comment by KelvinTegelaar** [comment]
Added template.
