### ISSUE TITLE
Duplicate Alerts being sent from the Alert Engine

### ISSUE THREAD

**Issue by ashley-mspgeek** [KelvinTegelaar/CIPP#2726]
### Description

When setting up alerting for the detection of new Inbox Rules, the notifications are being generated twice with identical content for multiple tenants. Expected Result is a single email notification for each new Inbox Rule detected.

Steps to Reproduce:

- Configure alerting for new Inbox Rules
- Wait for the alert to trigger.
- Observe that two identical email notifications across multiple tenants.

### Environment data

```PowerShell
Sponsored instance Front end version number: Latest Back end version number: Latest Tried Tenant Cache Clear: true Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
This seems to be solved, let us know if you still experience it.
