### ISSUE TITLE
Feature Request: List of Partner Relationships

### ISSUE THREAD

**Issue by DarrenChap** [KelvinTegelaar/CIPP#273]
It would be handy to have a list of the Partner Relationships for each tenant (and the permissions they have) so we could keep an eye on who has Delegated Admin Access to customer tenants.  Maybe as an extra column in the BPA analyser?

**Additional context**
https://www.microsoft.com/security/blog/2021/11/22/how-to-investigate-service-provider-trust-chains-in-the-cloud/

**Comment by KelvinTegelaar** [comment]
this will be in the larger tenant overview that we are planning, closed for now.
