### ISSUE TITLE
Manage Users/Groups link on some pages point to a broken URL

### ISSUE THREAD

**Issue by dloughland87** [KelvinTegelaar/CIPP#274]
**Describe the bug**
The Manage Users/Groups hyperlinks on the top right-hand corner of some pages point to a broken URL that ends in .html and returns a 404 error.
-https://cipp.domain/index.html?page=users.html

**To Reproduce**
The following pages have the incorrect hyperlink URL for Manage Users and/or Manage Groups:
-https://cipp.domain/index.html?page=DeviceList
-https://cipp.domain/index.html?page=BasicAuth
-https://cipp.domain/index.html?page=tenants
-https://cipp.domain/index.html?page=ConditionalAccessPoliciesList
-https://cipp.domain/index.html?page=BestPracticeAnalyserList
-https://cipp.domain/index.html?page=DomainAnalyserList
-https://cipp.domain/index.html?page=AutopilotProfileList
-https://cipp.domain/index.html?page=OnedriveList
-https://cipp.domain/index.html?page=SharepointList
-https://cipp.domain/index.html?page=TeamsList
-https://cipp.domain/index.html?page=TeamsActivity
-https://cipp.domain/index.html?page=MailboxStatisticsList
-https://cipp.domain/index.html?page=MailboxList
-https://cipp.domain/index.html?page=MailboxCASList
-https://cipp.domain/index.html?page=Messagetrace
-https://cipp.domain/index.html?page=PhishPolicyList

**Expected behavior**
Hyperlinks should be:
-https://cipp.domain/index.html?page=users
-https://cipp.domain/index.html?page=groups

**Screenshots**
![image](https://user-images.githubusercontent.com/58795759/142961206-84383603-d736-49b9-a955-fcc20e3c8dc8.png)
![image](https://user-images.githubusercontent.com/58795759/142963310-9f3b27ca-3be8-4b66-a9e9-c9886ae8171d.png)

**Comment by KelvinTegelaar** [comment]
thanks for reporting, we're working on a big UX project that'll change how we do things. This is marked as a wontfix because it's resolved in the new interface. :)
