### ISSUE TITLE
[Feature Request]: Make the Spam Filter Standard slightly more granular

### ISSUE THREAD

**Issue by kakaiwa** [KelvinTegelaar/CIPP#2741]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The Spam Filter Standard is missing some configurable parameters, particularly the bulk threshold value. Being able to adjust this value would greatly enhance the filter's flexibility, allowing for more precise control over the classification of bulk emails.

**Comment by kakaiwa** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Thank you for adding the FR, and making it!
