### ISSUE TITLE
[Feature Request]: Allow preview of quarantined message

### ISSUE THREAD

**Issue by AADAutomatisering** [KelvinTegelaar/CIPP#2744]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We are able to release and deny quarantined messages via CIPP already, but it would be nice if we are able to preview the message before making a decision on it.

I could see this implemented as a preview button as the first button in the Quarantine Management table, and clicking on it would open a popover with the messages preview.

This will allow us to manage the quarantined messages without having to go to the defender portal.

### PowerShell commands you would normally use to achieve above request

Preview-QuarantineMessage -Identity <QuarantineMessageIdentity>

**Comment by JohnDuprey** [comment]
Implemented in dev
