### ISSUE TITLE
Click to deploy: ResourceDeploymentFailure

### ISSUE THREAD

**Issue by EnterfusionFL** [KelvinTegelaar/CIPP#2753]
### Description

When using the "Deploy to Azure" button for the cipp installation I receive the following error:
![image](https://github.com/user-attachments/assets/7ae0da90-15c6-45ce-9034-4666809f36a6)
Error details: {"code":"ResourceDeploymentFailure","target":"/subscriptions/{subId}/resourceGroups/cipp/providers/Microsoft.Web/sites/cipprbtsk/sourcecontrols/web","message":"The resource write operation failed to complete successfully, because it reached terminal provisioning state 'Failed'."}

I triple checked my input repository URLs and Github token, everything looks exactly as it should according to the install guide.

### Environment data

```PowerShell
Azure
```

**Comment by KelvinTegelaar** [comment]
Support issue, support is only for sponsors.

**Comment by EnterfusionFL** [comment]
> Support issue, support is only for sponsors.

Account upgraded to sponsor. Please re-open.
