### ISSUE TITLE
[Feature Request]: Differentiating Alert Target 

### ISSUE THREAD

**Issue by BeheerIctivity** [KelvinTegelaar/CIPP#2760]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When creating alerts you have the choice to send them to email, webhook or PSA. We would like to have the option to differentiate email addresses based on which alert. Depending on the situation other people or departments should be alerted. For example a security related alert should go to another email address, than a mailbox full alert. 

When the alert wizard itself would contain the desired target each alert can have its own target. In case of using email, then the alert wizard would contain a box in which the desired address can be entered.

To keep it simple for companies or alerts which do not need differentiation, an option "use system default" would keep things simple.

Sponsored via Ictivity

**Comment by CDSFounder** [comment]
+100 (can I do that?)  We also want this for reports - really anywhere there is an email field. 

Another use case that would greatly help us is for storing reports into our client facing portal. The portal has a unique email address for each report type and client.

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
