### ISSUE TITLE
[Feature Request]: Onedrive Sync Alerts

### ISSUE THREAD

**Issue by BeheerIctivity** [KelvinTegelaar/CIPP#2761]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When a OneDrive sync fails, and the user does not see it, there is a major risk of loosing data. We now periodically check the sync dash, but that is manual labor. We found a script on your page which can gather the sync status. 

How great would it be to have a default option in CIPP to check OneDrive sync and generate an alert to webhook, email or PSA when it has an error status. This way we could automatically inform the first line Service desk and proactively contact the user to solve the issue. With the alert "differentiation" (other feature request), we could even alert an ICT manager at some customers who support the end users themselves. 

Sponsored via Ictivity

**Comment by KelvinTegelaar** [comment]
Not Possible, there is no API for this.
