### ISSUE TITLE
Missing "Tenant Mode" selector in SuperAdmin Settings

### ISSUE THREAD

**Issue by jdr8** [KelvinTegelaar/CIPP#2767]
### Description

In the SuperAdmin Settings tab of Application Settings, Tenant Mode does not allow you to select an option.
1) Click on "CIPP -> Application Settings" as a superadmin user
2) Navigate to the SuperAdmin Settings tab (visible when logged in as superadmin)
3) When loading completes - no option to select a tenant mode. 
![image](https://github.com/user-attachments/assets/0f16acc0-d40e-4131-a4f4-308e926fad28)

Non-sponsored instance front end version 6.2.0 backend version 6.2.0
All caches cleared, different browser tested, "incognito" tested.
Re-sign in tested.

Inspected elements, noticed nothing renders for a drop down or selection box, and no errors in console for this to not be appearing.

I can see the network response of ExecPartnerMode?Action=ListCurrent responds with TenantMode: "default", but there is no component rendering.

**Comment by jdr8** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by ccalbreath** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by lismorediocese** [comment]
I am also having this issue

**Comment by jdr8** [comment]
Looks like the following is missing from src/views/cipp/app-settings/SettingsSuperAdmin.jsx after line 68:

`            <CRow>
              <CCol sm={12} md={12} className="mb-3">
                <p className="fw-lighter">Tenant Mode</p>
                <Form
                  onSubmit={onSubmit}
                  initialValues={partnerConfig.data}
                  render={({ handleSubmit }) => (
                    <>
                      {partnerConfig.isFetching && <CSpinner size="sm" className="me-2" />}
                      <CForm id="submitForm" onSubmit={handleSubmit}>
                        <RFFCFormRadio
                          name="TenantMode"
                          label="Multi Tenant - GDAP Mode"
                          value="default"
                        />
                        <RFFCFormRadio
                          name="TenantMode"
                          label="Multi Tenant - Add Partner Tenant"
                          value="PartnerTenantAvailable"
                        />
                        <RFFCFormRadio
                          name="TenantMode"
                          label="Single Tenant - Own Tenant Mode"
                          value="owntenant"
                        />
                      </CForm>
                    </>
                  )}
                />
                {webhookCreateResult.isSuccess && (
                  <CippCallout color="info" dismissible>
                    {webhookCreateResult?.data?.results}
                  </CippCallout>
                )}
              </CCol>
            </CRow>`

**Comment by KelvinTegelaar** [comment]
Fixed in dev
