### ISSUE TITLE
[Feature Request]: Delete Named Locations

### ISSUE THREAD

**Issue by aitp-eric** [KelvinTegelaar/CIPP#2769]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Add an option to DELETE a Named Location from inside of CIPP.  

When setting up a new Named Location, there is currently the ability to add multiple Named Locations with the same name. This would be one use case for why this is required.  

One additional check that should be made, before a Named Location is removed, is a check to make sure it is not use already in a Conditional Access Policy.  If the Named Location is not in use, then the ability to delete the Named Location should be granted. If the Named Location is in use, the delete request should be denied. 

Ex: https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/remove-mgidentityconditionalaccessnamedlocation?view=graph-powershell-1.0

### PowerShell commands you would normally use to achieve above request

Connect-MgGraph -Scopes 'Policy.ReadWrite.ConditionalAccess'

Remove-MgIdentityConditionalAccessNamedLocation -NamedLocationId $namedLocationId

**Comment by KelvinTegelaar** [comment]
Only sponsors can create FRs, if you are a sponsor please included the organization you sponsor as.

**Comment by aitp-eric** [comment]
We are a sponsor under or organization:  AiTechPros

**Comment by aitp-eric** [comment]
We are a sponsor under or organization: AiTechPros

Thanks!
