### ISSUE TITLE
[Feature Request]: Ability to delete mailboxrules

### ISSUE THREAD

**Issue by AADAutomatisering** [KelvinTegelaar/CIPP#2771]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Since 2.6.0 we now have the ability to view the hidden mailbox rules, but it would be nice if we could also delete them from that same view. Saves us from having to do this via PowerShell.

### PowerShell commands you would normally use to achieve above request

`Remove-InboxRule -mailbox <UserUPN> -Identity <InboxRuleID>`

**Comment by kris6673** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
added in dev.
