### ISSUE TITLE
FEATURE REQUEST: preview emails in Quarantine

### ISSUE THREAD

**Issue by Techsavv-MSP** [KelvinTegelaar/CIPP#2774]
Please add the option to preview emails in Quarantine Management, as it will help in making better decisions when allowing emails.

**Comment by KelvinTegelaar** [comment]
Feature requests are only for sponsors, if you are sponsoring please let us know the user account you're sponsoring as.

**Comment by MWGMorningwood** [comment]
@KelvinTegelaar can I bump this one?
I had mentioned this would be a sweet feature during the last Office Hours.

I can resubmit with the proper template if you'd prefer
