### ISSUE TITLE
[Feature Request]: Ability to change Key Vault Name

### ISSUE THREAD

**Issue by PeterVive** [KelvinTegelaar/CIPP#2775]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi,

We have our own Key Vault with M365 SAM secrets.
I noticed that CIPP-API uses the environment variable "WEBSITE_DEPLOYMENT_ID" to get the VaultName.

This makes us unable to switch to using that Key Vault, since it's not an environment variable that can be altered.
We can easily change the references for TenantID, RefreshToken etc. in the Function App - but since it will keep calling the wrong Key Vault, updates wont happen.

I suggest storing the Key Vault Name somewhere, either in a Table or as an Environment Variable

Is this something you could look into?

**Comment by KelvinTegelaar** [comment]
Feature requests are only for sponsors, and this is something we wont edit to keep the integrity of security in place.
