### ISSUE TITLE
[Feature Request]: Access to BitLocker Key From Admin > Devices

### ISSUE THREAD

**Issue by csp-gm** [KelvinTegelaar/CIPP#2777]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to open a feature request to be able to retrieve BitLocker Recovery Keys for our customer devices from Admin > Devices instead of having to go through Intune > Device Management > Devices. More broadly I would say that actions being where they're most relevant would be a benefit - for example Intune specific actions in the Intune section and Entra specific actions in the Entra section. 

Many of our customers don't have Intune licensing but still have their BitLocker recovery keys stored in Entra. It would be beneficial for our team to be able to access those in the CIPP portal. 

I imagine many other MSPs have customers who might not leverage/have correct licensing for Intune but have devices enrolled in Entra with BitLocker keys stored and being able to access those in this manner would allow us to more fully move away from the Partner Portal/Direct customer portal access.

### PowerShell commands you would normally use to achieve above request

UI Change - No relevant PowerShell (?)

**Comment by MWGMorningwood** [comment]
It also caught me off-guard when I was looking for this, as I went directly to `/identity/administration/devices` to do this.
In my opinion, the actions available should probably correspond to the "Original" MS portal the page refers to in any instance.

I think `/identity/administration/devices` would represent entra devices, whereas `/endpoint/reports/devices` would represent intune ones.
