### ISSUE TITLE
BUG: Notification Settings 

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#278]
**Describe the bug**
If you add a webhook and tick the option below, when you click save and refresh the page the webhook address is filled in but the tick boxes are all unchecked.

**To Reproduce**
1. Go to Setting
2. Click on notifications

**Expected behavior**
The options to apply

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 96.0.1054.29

**Comment by KelvinTegelaar** [comment]
This is a known interface bug, the actual settings do get applied.

**Comment by Pukkahq** [comment]
2 things were against me, I was ticking the boxes and then creating an account but it was not sending the webhook. I now see it only sends them every 30 min.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
