### ISSUE TITLE
[Feature Request]: Standard to handle unlicensed users OneDrive data

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2780]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

This reddit thread alerted us of the upcoming changes to default behavior for unlicensed OneDrive users: https://www.reddit.com/r/sysadmin/comments/1eeyrae/psa_effective_january_2025_onedrive_access_for/
 
This Microsoft article shows how for unlicensed users '_Beginning January 27, 2025, any OneDrive user account that has been unlicensed for longer than 90 days becomes inaccessible to admins and end users. The unlicensed account is automatically archived, viewable via admin tools, but remains inaccessible until administrators take action on them.'_
and 
'_Archive unlicensed OneDrive account
If no action is taken, the account remains archived through [Microsoft 365 Archive](https://learn.microsoft.com/en-us/microsoft-365/syntex/archive/archive-overview). Archiving the account lets you keep the OneDrive account and its data for long periods of time in case you need to retrieve it later._'
https://learn.microsoft.com/en-us/sharepoint/unlicensed-onedrive-accounts#:~:text=If%20no%20action%20is%20taken%2C%20the%20account%20remains%20archived%20through,pricing%2C%20see%20Pricing%20model%20for%20Microsoft%20365%20Archive%20(Preview).
 
I think there are probably a lot of ways to handle this, but it will undoubtedly be an issue for many MSPs who have been leveraging the easy delegation of OneDrive for former employees.  I am very open to other options and ideas may have to address this issue. Right now, my preferred options to avoid additional archival costs would be:
- Automatically move unlicensed user OneDrive data to a specific SharePoint library after 89 days.
- Automatically delete unlicensed user OneDrive data after 89 days

VERY open to other potential options for how to handle this data.

### PowerShell commands you would normally use to achieve above request

Not sure....

**Comment by CDSFounder** [comment]
For user offboarding scenarios - would be cool if there was a check box to "Automatically store in direct manager's OneDrive". When checked, it creates a folder named "Former Employees\<NameOfTheEmployee>" and moved the offboarded OneDrive data there.

**Comment by kris6673** [comment]
As a temp fix I added a 30 and 90 day option to the standard: https://github.com/KelvinTegelaar/CIPP/pull/2781

**Comment by KelvinTegelaar** [comment]
We're not going to mess with data migrations, it remains accessible for admins after 89 days using the current standard - after investigation admins can just browse to the link to retrieve any data.
