### ISSUE TITLE
[Feature Request]:  Add report of all mailboxes with their delegated permissions.

### ISSUE THREAD

**Issue by 3DKs** [KelvinTegelaar/CIPP#2785]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be nice to have a report of all delegated mailbox permissions tenant wide.
This would make it easier to audit access across the tenant.

### PowerShell commands you would normally use to achieve above request

**Full Access**
Get-Mailbox -resultsize unlimited | Get-MailboxPermission | Select Identity, User, Deny, AccessRights, IsInherited| Where {($_.user -ne "NT AUTHORITY\SELF")}

**Send as**
Get-Mailbox -resultsize unlimited | Get-RecipientPermission | where {($_.Trustee -ne 'nt authority./self') -and ($_.Trustee -ne 'Null sid')} | select Identity,Trustee,AccessRights

**Send on behalf**
Get-Mailbox -resultsize unlimited |?{$_.GrantSendOnBehalfTo -ne $null }| Select PrimarySmtpAddress,GrantSendOnBehalfTo,RecipientTypeDetails

**Comment by KelvinTegelaar** [comment]
Only sponsors can create Frs
