### ISSUE TITLE
[Feature Request]: Out of Office Message HTML Editor

### ISSUE THREAD

**Issue by MrNickIE** [KelvinTegelaar/CIPP#2794]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Our team have recently started using CIPP.  One of the items that first level do constantly is set users out of office messages and forwarding messages on mailboxes.

Currently, this is provided as a single line editor.  Which the customer does not like.

Please can you add a proper HTML editor or at least the ability to do multi-line Out of Office message editing.  (Much like this very Github editor!)

**Comment by MrNickIE** [comment]
Auto close?

**Comment by KelvinTegelaar** [comment]
Interface rwrite, closing because we dont need it.

**Comment by MrNickIE** [comment]
When you say "we dont need it".  Do you mean us?  Or something else?

My team are actually asking for this quite a lot.
