### ISSUE TITLE
Duplicate MDM Policy deployment

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2796]
### Description

Just checked the MDM policys of a tenant and noticed the duplicate Policys (This is in every tenant where i run standards)
![image](https://github.com/user-attachments/assets/557f76b6-40af-4f5b-ba98-c6d5b7c05f5f)

This time it appears to be
* Android Restriction policy
* MacOS Endpoint policy
* Health Monitor policy
* Windows Update Ring Policy

2 of the Policy runs seems to have happened before the 6.2.1 update

### Environment data

```PowerShell
Frontend: 6.2.1
Backend: 6.2.1
Sponsored
Cleared Tenant cache: false
```

**Comment by MWGMorningwood** [comment]
+1
![image](https://github.com/user-attachments/assets/c093f757-9fe1-467d-a58c-c7fd56972e6d)

**Comment by MWGMorningwood** [comment]
I believe this will be resolved in the upcoming hotfix
I think @JohnDuprey's working on it still

**Comment by KelvinTegelaar** [comment]
Fixed in hotfix
