### ISSUE TITLE
Permissions Checker missing 'M365 License Manager' - 'LicenseManager.AccessAsUser'

### ISSUE THREAD

**Issue by itlogic-github** [KelvinTegelaar/CIPP#2802]
### Description

The standard "Disable Self Service Licensing" requires the permission "M365 License Manager" - "LicenseManager.AccessAsUser". However the permissions checker does not check for this permission. So the standard fails with a permissions error until this specific permissions is added in to the Enterprise App.

Managed to resolve myself by finding @rvdwegen's blog post (Who I guess made the standard). https://blog.vdwegen.app/posts/disable-selfservice-licenses/

But definitely needs to be part of the permissions checker, or a warning on the standard that this specific permission is needed.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 6.2.1
Back end version number: 6.2.1
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by itlogic-github** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by rvdwegen** [comment]
Woops, I think I completely forgot to add that haha

**Comment by itlogic-github** [comment]
Happens to the best of us!

Gonna try and get this out of the Unconfirmed by user status again.

I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by MoltenTesseract** [comment]
I did a bit of digging on this. The permissions are in SAMManifest.json as of 3 weeks ago. But I was definitely having the issues post this change. Might need someone else to confirm they also have the issue?

**Comment by MoltenTesseract** [comment]
@JohnDuprey  I did a bit more digging I believe you may have fixed this and it was in today's release. I have found the GUIDs for the permissions in the file now. If you have, feel free to close this one off.
