### ISSUE TITLE
Failed adding Autopilot Profile [AutoPilot Profile Name]

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2803]
### Description

Currently seeing this error on pretty much all tenants where the Autopilot Profile Standard is enabled
`
Failed adding Autopilot Profile [AutoPilot Profile Name]. Error: { "_version": 3, "Message": "Another Profile 743f7ed9-e9d8-4646-a21b-7a84f59da221 is already assigned to All Devices. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: f1374a61-32e8-4d9f-8883-b4b25917c5b1 - Url: https://fef.msub06.manage.microsoft.com/DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeploymentProfiles('743f7ed9-e9d8-4646-a21b-7a84f59da221')/assignments?api-version=5023-06-28", "CustomApiErrorPhrase": "", "RetryAfter": null, "ErrorSourceService": "", "HttpHeaders": "{}" }
`

Currently it fails to see that the profile exists and tries to create a new one instead of patching the old one
![image](https://github.com/user-attachments/assets/dfa6b2e1-c136-4402-b17f-ef3caf889047)

### Environment data

```PowerShell
Sponsored
Frontend: 6.2.1 (+ hotfix)
Backend: 6.2.1 (+ hotfix)
false
```

**Comment by KelvinTegelaar** [comment]
Fixed in hotfix
