### ISSUE TITLE
[Feature Request]: how to assign a license to the user

### ISSUE THREAD

**Issue by sonalm1999** [KelvinTegelaar/CIPP#2809]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

x

### PowerShell commands you would normally use to achieve above request

x

**Comment by KelvinTegelaar** [comment]
Not the place for support. If you want support, please contact the helpdesk. The email address of the helpdesk can be found when you've paid for your sponsorship.
