### ISSUE TITLE
Feature request: Option to view the status of "Self-service Purchase" and the ability to disable (or enable)

### ISSUE THREAD

**Issue by baitsops** [KelvinTegelaar/CIPP#281]
Not sure if it's possible, but we're an indirect reseller (using a CSP) for our clients and a number of them have been surprised by Microsoft charges appearing on their credit card statements due to the "Self-service Purchase" option that Microsoft enables by default. 

It looks like you can disable this function via a PowerShell module: https://docs.microsoft.com/en-us/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell?view=o365-worldwide

**Comment by KelvinTegelaar** [comment]
New standard available in dev.
