### ISSUE TITLE
[Feature Request]: Please show Archive size under Reports->Mailbox statistics

### ISSUE THREAD

**Issue by unifieditgit** [KelvinTegelaar/CIPP#2819]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The mailbox statistics report is brilliant but it doesn't show the archive size which makes it limiting. Hopefully this can be implemented.

**Comment by KelvinTegelaar** [comment]
This is a sad no. Microsoft doesn't report Archive sizes, so it would have to be a per user query which would make this too slow to function. I love the idea though so please try again later in case Microsoft updated these APIs: https://learn.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-1.0&tabs=http

**Comment by unifieditgit** [comment]
Thanks, I understand that opening the mailbox in CIPP can report on archive size so perhaps a function where it doesn't load automatically but clicking the button, even a separate report where it can take 5-30 mins to pull the data and show it. It's a valuable information when deciding which license to upgrade/downgrade/migrate users to
