### ISSUE TITLE
Feature request: Option to globally exclude certain SKUs from appearing

### ISSUE THREAD

**Issue by baitsops** [KelvinTegelaar/CIPP#282]
Much like how you can exclude certain tenancies globally, it would be good if we could exclude certain 'junk' SKUs like any that contain the words like: "FREE", "EXPLORATORY", "NONPROFIT_PORTAL" and "TRIAL" ?

As an example, this could apply for when you click on the "SKUs with Unassigned Licenses" and keep it clean to only SKUs we care about.

**Comment by KelvinTegelaar** [comment]
I think @gavsto was working on something for this. not 100% sure.
