### ISSUE TITLE
[Feature Request]: Allow access options to choose tenants to access for users

### ISSUE THREAD

**Issue by unifieditgit** [KelvinTegelaar/CIPP#2822]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

2 x different scenarios:
1st scenario: We can have our own tenancy in there but only want primary admins of the business to have access to internal tenancy
Staff who are dedicated to 1 client only are currently unable to use CIPP as we cannot limit their access to a single tenant

**Comment by KelvinTegelaar** [comment]
This already exists, check the "role" documentstion here: https://docs.cipp.app/setup/installation/roles
