### ISSUE TITLE
[Feature Request]: Intune Template Exclude

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2823]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to have a option to exclude groups from the Intune Template standard

**Comment by MWGMorningwood** [comment]
I meant to include this as a column in my original FR- figured a least-viable version of it would make sense for now, though.
Definitely a +1 from me.

**Comment by HappyEarthDay** [comment]
We would also love this!

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
