### ISSUE TITLE
[Feature Request]: Set-CalendarProcessing for Rooms

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2824]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like the option to run `Set-CalendarProcessing -Identity [Room mailbox] -ProcessExternalMeetingMessages $true -DeleteComments $false` from within CIPP instead of having to login as local admin to configure a teams meeting room

https://learn.microsoft.com/en-us/powershell/module/exchange/set-calendarprocessing?view=exchange-ps

**Comment by kris6673** [comment]
Should probably be added as a part of a "Edit Room" feature, it's on my todo list to have a look at making, but I'm unsure when I'll get the time

**Comment by OfficialEsco** [comment]
Yep was thinking the same, but since Edit Room frontend scares me and none replied in the FR i looked into a workaround, but if you got this on your TODO i should probably wait until then since it will be a way better way to do it

**Comment by kris6673** [comment]
Scares me too q.q React is spooky  
Getting resources added is also on my todo, but idk when that will happen

**Comment by kris6673** [comment]
Bump to keep this open from the triggerhappy closing monster that is github-actions

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
