### ISSUE TITLE
[Feature Request]: View assigment information about Policies

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2825]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to see for example Assignments and Exclusions in
* Configuration Policies
* Compliance Policies
* Protection Policies

**Comment by OfficialEsco** [comment]
I got a branch improving this, we'll see if i can get the Group DisplayName to work

**Comment by OfficialEsco** [comment]
Compliance Policies and Compliance Policies uses ListGraphRequest which means there is no easy way to translate the assignment GroupId to the Group DisplayName

**Comment by KelvinTegelaar** [comment]
1 of 3 implemented, more coming after rewrite.
