### ISSUE TITLE
Intune - Add MSP App: ImmyBot

### ISSUE THREAD

**Issue by bbuchan10** [KelvinTegelaar/CIPP#2826]
### Description

Hi, when attempting to deploy ImmyBot via CIPP Intune section under "Add MSP App", I am getting error: "The property 'displayName' cannot be found on this object. Verify that the property exists and can be set." when attempting to submit the app. This happens no matter what settings I change.

![image](https://github.com/user-attachments/assets/85937032-c946-4d5a-a0e6-c058759f7465)

### Environment data

```PowerShell
Non-Sponsored Instance
Front: 6.2.2
Back: 6.2.3
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug
