### ISSUE TITLE
[Feature Request]: Added CA Vacation mode like feature for groups

### ISSUE THREAD

**Issue by unifieditgit** [KelvinTegelaar/CIPP#2828]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Example: A user require read or write access for USB storage for their device which is done by a group, added to "Exclusions" to the intune USB storage block policy.

Would be great to have a setting where we can add a device and add a date to remove the device from the exclusion group

**Comment by KelvinTegelaar** [comment]
We recommend using the scheduler for this, here's some examples:

![image](https://github.com/user-attachments/assets/a8368a15-d9d5-443b-812e-2c4375990d6e)


![image](https://github.com/user-attachments/assets/3c8c6d92-e1ee-49c8-9963-36bdf1dcd396)

**Comment by unifieditgit** [comment]
Thanks but it's not realistic when we have to find the GroupType and GroupID ourselves so the feature request still stands
![image](https://github.com/user-attachments/assets/314dbb12-292c-419d-9942-96f2c749e4ac)
