### ISSUE TITLE
[Feature Request]: Create default Exchange Retention Policies

### ISSUE THREAD

**Issue by Dadgey** [KelvinTegelaar/CIPP#2829]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

There's a standard for adding Online Archives. As more of our clients have been with 365 for a considerable time now we're experiencing more with issues around mailbox size. We can either resolve this through putting them on Exchange Plan 2 or we can move them to Online Archives. Having the ability to turn this on en masse, is great but that's only half the job as we then need to setup the retention policies to allow the Online Archives to fill automatically without relying on the user to do this manually. It would be great to see the ability to add retention policies from within either that standard directly or a seperate standard.

### PowerShell commands you would normally use to achieve above request

I can see that you can map retention policies to mailboxes via Powershell but not sure we can create the actual policies themselves. https://learn.microsoft.com/en-us/purview/set-up-an-archive-and-deletion-policy-for-mailboxes

Which might be why this hasn't been done?

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.

**Comment by karnophage** [comment]
So did this happen?
