### ISSUE TITLE
BUG: Filtering users with "Enabled / Disabled" shows no users

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#283]
When on the user list for a tenant (Identity > Users > List > ) All users are loaded.
When using the filter at the bottom of the list of "Account Enabled" or "On Premise Sync" to filter enabled or disabled, it returns no users.

**Expected behavior**
Users should be filtered to Enabled / Disabled depending on the filter option

**Screenshots**
![image](https://user-images.githubusercontent.com/92956722/143160428-8496a555-036d-4442-8744-2e0d24878462.png)

**Additional context**
I believe this is known, but I couldn't find a related bug report.

**Comment by KelvinTegelaar** [comment]
known issue and fixed in dev
