### ISSUE TITLE
Failed to create group: An error occurred while processing the write request.

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2832]
### Description

I'm seeing this error message quite a lot from the Groups Standard, these are mainly Dynamic Groups, but they have been deployed before, it just seems like the reruns fails.
`Failed to create group: An error occurred while processing the write request.`

### Environment data

```PowerShell
Sponsored
Front end version: 6.2.2
Back end version: 6.2.2
Cache clear: false but also probably
```

**Comment by OfficialEsco** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
