### ISSUE TITLE
[Feature Request]: Make scheduler smarter so we don't have to input Group Type and Group ID and can select from the list

### ISSUE THREAD

**Issue by unifieditgit** [KelvinTegelaar/CIPP#2840]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Original feature request that was closed: #2828
The remove from Group ideally show show the drop down menu like:
Group Type - Options to select
Group Name - Name of groups
Member Type - User or Device
Members - Based on member type, show list of users or devices

![image](https://github.com/user-attachments/assets/01498c46-db99-4a9b-bdd0-ff93578d1055)

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
