### ISSUE TITLE
[Feature Request]: Tenant Groups for standards deployment

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2843]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Our MSP services a wide variety of industries with varying needs. For example, the standards we'd like to deploy to our **Legal** clients differ drastically from the standards we'd like to deploy to our **hospitality** clients.   The current standards deployment makes it very difficult to deploy standards to subsets of tenants.  The _All tenants_ feature and the ability to exclude tenants from the _All tenants_ standard are great, but it doesn't allow us to deploy standards to specific subsets of clients without going into each tenant making the changes, which makes it very difficult to keep track of which settings are applied to tenants.  

There are so many amazing features in CIPP that we want to utilize, but we can't deploy most of them to all tenants for whatever reason.  For example, we want to deploy the _Quarantine Release Request Alert_ standard to all of the clients that don't have their own IT.  However, we don't want to exclude those 20% of our tenants that have internal IT teams from the other standards that we have configured on _All Tenants._  Having tenant groups would allow us to more accurately deploy standards to our clients based on which category they fall under.

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
