### ISSUE TITLE
[Feature Request]: scripted cipp alert for inactive users that still have assigned licenses

### ISSUE THREAD

**Issue by TechRiverMSP** [KelvinTegelaar/CIPP#2844]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would like to alert on inactive and disabled user accounts that still have licenses assigned to them.  We autocalculate billing based on licensed users and this will help make sure we aren't wasting customer money by having licenses assigned to inactive users and billing for services.  

### PowerShell commands you would normally use to achieve above request

##not tested
# Define the necessary permissions scope 
$Scopes = "User.Read.All" 
  
# Authentication parameters 
$ClientId = "your-client-id" 
$TenantId = "your-tenant-id" 
$ClientSecret = "your-client-secret" 
$AuthUrl = [https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token](https://url.avanan.click/v2/___https:/login.microsoftonline.com/$TenantId/oauth2/v2.0/token___.YXAzOnRlY2hyaXZlcjphOm86MTQ5MmExNDJkNWY3MTlmNTE0MDBjOTE2NGQ0OTMzODM6NjpkZDhhOjdmZGM5M2FlMzk2MmIzNTkyYmYwNDQ4MDYzZTk5ODFjOWQxYzk1MjQxYTRkNjkwMzc2M2UyYTRmMjQyYzg0MWY6aDpUOk4) 
$GraphApiUrl = [https://graph.microsoft.com/v1.0](https://url.avanan.click/v2/___https:/graph.microsoft.com/v1.0___.YXAzOnRlY2hyaXZlcjphOm86MTQ5MmExNDJkNWY3MTlmNTE0MDBjOTE2NGQ0OTMzODM6NjozOWYzOmJkYjYzOWU2NzQyOWE0ZDliMmM2NWI3OGM2MDJlZTVjMWZlOTZiM2Q4NmIzZDVhY2IwNTgyNjIzNjc5ZDg0MWU6aDpUOk4) 
  
# Acquire the OAuth 2.0 token 
$Body = @{ 
    client_id     = $ClientId 
    scope         = $Scopes 
    client_secret = $ClientSecret 
    grant_type    = "client_credentials" 
} 
  
$TokenResponse = Invoke-RestMethod -Method Post -Uri $AuthUrl -ContentType "application/x-www-form-urlencoded" -Body $Body 
$AccessToken = $TokenResponse.access_token 
  
# Get all users 
$UsersUrl = "$GraphApiUrl/users" 
$Headers = @{ 
    Authorization = "Bearer $AccessToken" 
} 
  
$AllUsers = Invoke-RestMethod -Uri $UsersUrl -Headers $Headers -Method Get -ContentType "application/json" 
  
# Define the inactivity threshold (e.g., 90 days) 
$InactivityThreshold = (Get-Date).AddDays(-90) 
  
# Loop through each user to check for licenses and last sign-in activity 
$InactiveLicensedUsers = @() 
  
foreach ($User in $AllUsers.value) { 
    $UserPrincipalName = $User.userPrincipalName 
    
    # Get user sign-in activity 
    $SignInActivityUrl = "$GraphApiUrl/auditLogs/signIns?&$filter=userPrincipalName eq '$UserPrincipalName'" 
    $SignInActivity = Invoke-RestMethod -Uri $SignInActivityUrl -Headers $Headers -Method Get -ContentType "application/json" 
    
    if ($SignInActivity.value.Count -eq 0 -or ($SignInActivity.value | Where-Object { $_.createdDateTime -gt $InactivityThreshold }) -eq $null) { 
        # Get user's license information 
        $LicenseDetailsUrl = "$GraphApiUrl/users/$($User.id)/licenseDetails" 
        $LicenseDetails = Invoke-RestMethod -Uri $LicenseDetailsUrl -Headers $Headers -Method Get -ContentType "application/json" 
        
        if ($LicenseDetails.value.Count -gt 0) { 
            # User is inactive and still has a license 
            $InactiveLicensedUsers += [PSCustomObject]@{ 
                UserPrincipalName = $UserPrincipalName 
                DisplayName       = $User.displayName 
                LastSignIn        = ($SignInActivity.value | Sort-Object createdDateTime -Descending | Select-Object -First 1).createdDateTime 
                LicenseDetails    = ($LicenseDetails.value | ForEach-Object { $_.servicePlans | Where-Object { $_.provisioningStatus -eq 'Success' } }).servicePlanName -join ", " 
            } 
        } 
    } 
} 
  
# Output the list of inactive users who are still licensed 
$InactiveLicensedUsers | Format-Table -AutoSize 
  
# Optionally, export the results to a CSV file 
$InactiveLicensedUsers | Export-Csv -Path "InactiveLicensedUsers.csv" -NoTypeInformation

**Comment by KelvinTegelaar** [comment]
Added to dev.
