### ISSUE TITLE
[Feature Request]: Standard to exclude specific user from Registration campaign

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2845]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We use a password management solution for all of our GA accounts in all of our client's tenants.  This requires the use of the Auth method _Third-party software OATH tokens_.  When we implement conditional access, sometimes we use regulation campaigns to enforce the use of Microsoft Authenticator for all users.  However, we don't want this requirement to be enforced for our GA account that is shared by engineers.   We'd like to have a standard to exclude a specific MSP user from the registration campaign.  

We'd like this to be separate from the existing standard for enabling or disabling the registration campaign (_Sets the state for the request to setup Authenticator_).  We don't apply this standard to all tenants, and some tenants are still set to the default value (Microsoft Managed).  Some clients use other third-party MFA providers or have other requirements. 

### PowerShell commands you would normally use to achieve above request

- Find the user with UPN that was specified in the standard setting (Get-MgUser)
- Update the Authentication methods policy top exclude the user: https://learn.microsoft.com/en-us/entra/identity/authentication/how-to-mfa-registration-campaign#:~:text=Update%20the%20registrationEnforcement%20and%20authenticationMethodsRegistrationCampaign%20section%20of%20the%20policy%20to%20enable%20the%20nudge%20on%20a%20user%20or%20group
```PATCH https://graph.microsoft.com/v1.0/policies/authenticationmethodspolicy```

**Comment by KelvinTegelaar** [comment]
This is a no, the issue is that too many MSPs would use this as a method to exclude GAs or other VIP accounts from MFA. We purposely don't allow that in any policy.

**Comment by HappyEarthDay** [comment]
> This is a no, the issue is that too many MSPs would use this as a method to exclude GAs or other VIP accounts from MFA. We purposely don't allow that in any policy.

This would not impact MFA requirements.  IT would only disable the prompt for the user to configure Microsoft Authenticator  MFA, which would still very much be required for the user via CAPs.

**Comment by MWGMorningwood** [comment]
@KelvinTegelaar IMO this should be governed by Conditional Access (or per-user MFA if no P1 is present). This is just a way to make sure they have _stronger_ authentication.  

This might be one of the few instances I opt to have something other than CIPP handle the setup of our new tenants (specifically regarding this toggle, not the rest obvs)
