### ISSUE TITLE
[Bug] MSP App for ConnectWise Automate Deployment is Broken

### ISSUE THREAD

**Issue by CDSFounder** [KelvinTegelaar/CIPP#2846]
### Description

If you deploy an MSP App via Intune section > Add MSP App and configure the settings you will find that the deployment fails during Autopilot. 

It appears that this is related to a recent change ConnectWise has made to the installation. A discussion about this can be found here: https://forums.mspgeek.org/topic/6768-automate-patch-upgrade-guide-2022-versions-before-20235-are-vulnerable/page/18/#comments 

I believe the solution is to update the deployment PowerShell script CIPP is using.

### Environment data

```PowerShell
Sponsored
Front End: 6.3.0
Current: 6.3.0
```

**Comment by CDSFounder** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by JohnDuprey** [comment]
Related to https://github.com/christaylorcodes/ConnectWiseAutomateAgent/issues/3
