### ISSUE TITLE
[Feature Request]: Add anti-spam and anti-phishing policies to tenant backup

### ISSUE THREAD

**Issue by cipptesting** [KelvinTegelaar/CIPP#2848]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Being able to backup anti-spam and anti-phishing policies would be great for recovery purpose

**Comment by cipptesting** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Thank you for adding!
