### ISSUE TITLE
403 Error when editing user without refreshing/changing screen after tenant change

### ISSUE THREAD

**Issue by Zack-Intellica** [KelvinTegelaar/CIPP#2850]
### Description

If you are sitting Email and Exchange > Administration > Mailboxes as 1 tenant.
Change the Tennant to another one (Doesn't matter which)
The screen you are on will change and show data ~ Expected
if you go to edit a user you get a 403 stating the user can't be found in the tenant, and shows you the tenant before you changed it

If you refresh the screen then it works.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 6.3.0
Back end version: 6.3.0
Tried Tenant Cache: true
Tried Token Cache Clear: true
```

**Comment by Zack-Intellica** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by Zack-Intellica** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Frontend bugs are on a dev stop, we don't accept them at the moment due to a potential change in frontend management.
