### ISSUE TITLE
Filtering Policy Template bugs out

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2860]
### Description

So i've been experiencing this interesting bug, when i type anything in filter it causes the entrys to be all mixed up
For some reason the default BitLocker Template seems to be the main issue, in this example it actually appears twice, but if you actually search it will most likely be there
![image](https://github.com/user-attachments/assets/c66725be-10e7-4701-a50a-c8125e28013c)

HOWEVER thats not the worst, because when this happens and you go to view a policy IT OPENS A DIFFERENT ONE
![image](https://github.com/user-attachments/assets/b0bacb04-263e-449f-8939-ee861a23999b)

### Environment data

```PowerShell
Sponsored
Frontend: 6.3.0
Backend: 6.3.0
Cache Clear: false
```

**Comment by OfficialEsco** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
This is a nofix, because of the interface rewrite that's coming :)

**Comment by OfficialEsco** [comment]
Unless the bug carried over 👀 okok we'll hope not
