### ISSUE TITLE
Disable Guest accounts currently ignores `Last interactive sign-in`

### ISSUE THREAD

**Issue by OfficialEsco** [KelvinTegelaar/CIPP#2861]
### Description

Disable Guest accounts currently look for `Last non-interactive sign-in` so it does not block guests who are signed in via Microsoft Teams. However there might be guests who are not teams guests for other reasons.
Therefore the `Disable Guest accounts` standard should look for both `Last non-interactive sign-in` and `Last interactive sign-in`

### Environment data

```PowerShell
Sponsored
6.3.0
```

**Comment by OfficialEsco** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

Well in theory its a feature/improvement request, but it does disable active guests which should be considered a bug 👀

**Comment by KelvinTegelaar** [comment]
This Feature Request is being closed as we are having a development stop for our frontend rewrite. We will reopen feature requests when this has been performed.
