### ISSUE TITLE
License count does not aggregate when multiple license periods

### ISSUE THREAD

**Issue by itstart-mattb** [KelvinTegelaar/CIPP#2864]
### Description

I have a tenant who has two license periods for 18 licenses each. Seem image below:

![image](https://github.com/user-attachments/assets/0e6d9085-361b-4bc0-8fdb-d98cdc5539b3)

The licenses are then only showing as 1 of the license periods and not summing together the two.

![image](https://github.com/user-attachments/assets/6a17c3ac-32ee-4f14-ba30-fdfef634b4fb)

This then naturally flows on and shows up as an alert for over provisioned licenses

### Environment data

```PowerShell
Current front end 6.3.0 and backend same
```

**Comment by KelvinTegelaar** [comment]
Not a bug, support issue. If you're a sponsor you can contact support.
