### ISSUE TITLE
FEATURE REQUEST: Tenant groups

### ISSUE THREAD

**Issue by Srobitas** [KelvinTegelaar/CIPP#2866]
When setting up alerts, we can either do all tenants or specify the specifics. Can you add a feature to add a tenant group so that we can maintain the alerts to a group, and include the tenants within the group who we want to be alerted for?

**Comment by KelvinTegelaar** [comment]
Currently not allowing new feature requests, feel free to come back next month as we're planning a major rewrite of CIPP.
