### ISSUE TITLE
Action With Dropdown Unexpected Re-Trigger

### ISSUE THREAD

**Issue by jonc3tech** [KelvinTegelaar/CIPP#2870]
### Description

1) Go to /identity/administration/users
2) Select any amount of users using the multiselect boxes
![image](https://github.com/user-attachments/assets/d3572534-279d-4baa-b8aa-e0cb9732e6ea)
3) Select the Actions Dropdown
![image](https://github.com/user-attachments/assets/7ae4986c-0a77-4a69-81f7-eaa3163eadc4)
4) Select any action that prompts a confirmation dropdown  (ex: Create OneDrive Shortcut)
![image](https://github.com/user-attachments/assets/68c1147f-952e-4924-b3f9-d4ce3a4f6017)
5) Execute action, cancel, or exit the window 
6) Click or unclick any multiselect boxes
![image](https://github.com/user-attachments/assets/738726da-c8a1-4664-af6b-4882224237b4)
7) The last action confirmation dropdown re-appears
![image](https://github.com/user-attachments/assets/6cc4e523-1392-45ed-9fd4-7882d4afd61e)

This has happened for all dropdown confirmations I can find that have multiselect > actions available.

### Environment data

```PowerShell
[Sponsored] / Non-sponsored 
instance Front end version number: 6.3.0
Back end version number: 6.3.0
Tried Tenant Cache Clear: [true]/false 
Tried Token Cache Clear: [true]/false
```

**Comment by KelvinTegelaar** [comment]
Currently not allowing new feature requests, feel free to come back next month as we're planning a major rewrite of CIPP.
