### ISSUE TITLE
[Feature Request]: Group Tenants for Templates

### ISSUE THREAD

**Issue by lennysdead** [KelvinTegelaar/CIPP#2879]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The ability to group tenants, say all Business Premium tenants, etc or Tag them somehow - then apply templates to a group.

This would allow broader and easier setup of Business Premium tenants and features vs Business Standard tenants.

### PowerShell commands you would normally use to achieve above request

n/a is a CIPP interface request

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests, we also have a temporary feature stop.
