### ISSUE TITLE
CIPP integration with MSP gradient not working 

### ISSUE THREAD

**Issue by Awinishk1** [KelvinTegelaar/CIPP#2881]
### Description

We have integrated CIPP with MSP gradient and as per configuration guide we mapped the vendor API and partner API key. 

It does shows gradient is connected and on MSP gradient it does not shows CIPP under vendor list. 

checked with MSP gradient support team, as per support team there is no issue at  Gradient end. 

### Environment data

```PowerShell
CIPP is production environment.
```

**Comment by KelvinTegelaar** [comment]
This is a support issue, not a bug. If you are a sponsor you can contact our support team at helpdesk@cyberdrain.com

**Comment by DevAccountnovatech** [comment]
Hello Kelvin, 

Would it be fine if we are on self hosted account and can sign the GITHUB for with tenant and get the sponsorship or does it have other process to migrate from one to another?
