### ISSUE TITLE
[Feature Request]: Re-order Shared Mailbox Permissions tab

### ISSUE THREAD

**Issue by JeremyMcM** [KelvinTegelaar/CIPP#2882]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The current UI/UX for modifying Mailbox Permissions is inconsistent. For Full Access, it's ordered "Remove / Add" but then for Send-As permissions it's ordered "Add / Remove" and for Send On Behalf" it's "Add / Remove" again.

![image](https://github.com/user-attachments/assets/77174c87-e88a-42c2-99c2-829e0a544c7e)

I suggest breaking the permissions into "Add" and "Remove" sections (although sectioning on the permission in question would be okay too) and then order the permissions in the same order in those groups. 

Here's a mock-up of what I'm imagining:

![image](https://github.com/user-attachments/assets/f610178d-d8bf-4708-bb63-3d71494274dd)

Thanks for considering!

**Comment by JeremyMcM** [comment]
I would like to work on this please!

**Comment by JohnDuprey** [comment]
@JeremyMcM we currently have a feature freeze as we are working on a new frontend. Feel free to join us on the dev channel in Discord if you want to help contribute that in the new UI.

**Comment by JeremyMcM** [comment]
> @JeremyMcM we currently have a feature freeze as we are working on a new frontend. Feel free to join us on the dev channel in Discord if you want to help contribute that in the new UI.

Sounds like fun. Thanks for the info and guidance!
