### ISSUE TITLE
Identity Management \ Administration \ Users \ All Tenants now produces timeout

### ISSUE THREAD

**Issue by bandicootlimited** [KelvinTegelaar/CIPP#2883]
### Description

Select Identity Management \ Administration \ Users. Select All Tenants. After 3 minutes an error 'The Azure Function has taken too long to respond. Try selecting a different report or a single tenant instead 500 - Request failed with status code 500' appears.

The same report for All Tenants used to run OK in June July and August.

If I also reduce the tenants down to only two tenants by going to Settings \ CIPP \ Application Settings \ Tenants and setting all but two as Excluded. Return to Identity Management \ Administration \ Users. Select All Tenants I get the same error. 

### Environment data

```PowerShell
Sponsored 
Front end version number: 6.4.0
Back end version number: 6.4.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: not sure. I have done 'Clear All Cache' if that helps?
```

**Comment by bandicootlimited** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by bandicootlimited** [comment]
It worked once Thursday morning. Other than that failed maybe 300 times on different computers different browsers, including setting to exclude all but two tenants. Times out after 3 minutes. Was working fine in August.

**Comment by KelvinTegelaar** [comment]
This is a support issue, not a bug.
