### ISSUE TITLE
[Feature Request]: Sync Assigned License Usage to Gradient

### ISSUE THREAD

**Issue by nathan-reformit** [KelvinTegelaar/CIPP#2884]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great to have the assigned usage value synced to Gradient as well as the total license count for each license SKU, we bill customers on a per user per month basis and having the assigned license count allows us to then invoice for services based on this number and ensure when users are offboarded/onboarded the contracts in our PSA are then updated accordingly. Currently it appears that only total licenses are synced.

I have just got off an onboarding call with Gradient and they advised to log a feature request here.

If this is possible it may well answer our long standing issue of how we maintain active user count at each of our clients :)

**Comment by KelvinTegelaar** [comment]
We currently have an Feature Request stop as we're doing a rewrite; outside of our feature stop, only if you are sponsoring at the $99,- dollar level you are able to make feature requests.
