### ISSUE TITLE
Offboarding Submit Button Doesnt Vanish

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#2885]
### Description

When offboarding a user, you get to the end of the process and after it has completed, the submit button is still visable. This causes confusion as the user tries to click the button multiple times. Please can the button be removed when it is no longer required.
![image](https://github.com/user-attachments/assets/2ffe71bf-78a8-489b-a84b-751df5f30389)

### Environment data

```PowerShell
Non-Sponsored instance
Front end version number: 6.4.0
Back end version number: 6.4.0
Tried Tenant Cache Clear: false 
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
We're currently doing an interface rewrite, this is included in that. :)
