### ISSUE TITLE
[Feature Request]: Tenant Grouping

### ISSUE THREAD

**Issue by georgychacko007** [KelvinTegelaar/CIPP#2888]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It will be good to implement grouping to tenants like all tenants which belongs to a particular standard. For example a class of tenants there will be like gold standard, then silver standard etc. So this enables appying different standards to tenants depending on the requirements

**Comment by KelvinTegelaar** [comment]
We currently have an Feature Request stop as we're doing a rewrite; outside of our feature stop, only if you are sponsoring at the $99,- dollar level you are able to make feature requests.
