### ISSUE TITLE
[Feature Request]: API-driven inbound provisioning for Active Directory

### ISSUE THREAD

**Issue by wsherwenaspire** [KelvinTegelaar/CIPP#2889]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The current capabilities of the CIPP for offboarding cloud-only users are robust. However, it is important to note that the majority of businesses operate within Hybrid Environments. For Managed Service Providers (MSPs), a significant portion of time is consumed by the onboarding and offboarding processes for new users. In the past, custom automation and settings were necessary, and it was understandable that no tool on the market could easily meet these requirements.

With the introduction of the Microsoft API-Driven Inbound Provisioning, a uniform and standardized approach is now possible. As detailed in the Microsoft documentation, this API allows for a consistent method of deployment: [In An external link was removed to protect your privacy. ).

By maintaining the process at its fundamental levels, such as disabling the user, appending a prefix to the display name, and converting to a shared mailbox, CIPP could implement this as a standardized tool. The only requirement for initial setup would be the Secret/Client data for the token and the API URL. To convert a user to a shared mailbox, the necessary attributes would need to be incorporated into the API settings, which could also be standardized.

Implementing this feature would offer MSPs significant time savings and enhance the value of the CIPP product.

**Comment by KelvinTegelaar** [comment]
We currently have a feature stop as we're doing a big rewrite, but I want to make sure to note something that is false in your FR:

>  However, it is important to note that the majority of businesses operate within Hybrid Environments. 

This is not true. Microsoft says only 16% of all M365 environments are. For MSPs that number is a little higher at 18% but hybrid environments should entirely be considered legacy. As we won't support legacy this is something that we won't consider. :)
