### ISSUE TITLE
Feature Request: Exclude Azure AD Sync accounts from the Per-User MFA Standard

### ISSUE THREAD

**Issue by kfear27** [KelvinTegelaar/CIPP#289]
When applying the standard called 'Enable per-user MFA for all users' this enables MFA for the 'On-Premises Directory Synchronization Service Account'

This in turn breaks the sync as you would need to configure MFA for that account.
For said account this is a system managed account, passwords and configuration are unknown.

From a standard Azure AD subscription you are unable to exclude certain IP addresses from MFA too.

Is there a best practice around this setup which I am unaware of?

Thanks

**Comment by KelvinTegelaar** [comment]
added in dev.
