### ISSUE TITLE
Editing User - Can't remove all licenses

### ISSUE THREAD

**Issue by mmccollum2** [KelvinTegelaar/CIPP#2895]
### Description

When editing a user, there's an option to "replace licenses" and then there's an option to "Remove All Licenses". When picked, we get a successful popup, but with a failed message that I'm not sure is valid, and because of the message, i'm not positive that all licenses were removed from the user. Or maybe the message is misleading?
![image](https://github.com/user-attachments/assets/f52bcf6c-a3eb-4d34-b998-ef9bbaa798c4)

The expected result should be a "Success we've removed (List of licenses removed)"

### Environment data

```PowerShell
Sponsored - Hosted with CIPP
FE 6.4.0 / BE 6.4.0
Tried Tenant Cache Clear: true Tried Token Cache Clear: true
```

**Comment by mmccollum2** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in current release
