### ISSUE TITLE
Accented characters in Transport Rules Templates cause error 500 while deploying

### ISSUE THREAD

**Issue by github-inosek-com** [KelvinTegelaar/CIPP#2898]
### Description

1.) Create any transport rule with "If the message includes these words in the message subject: "Ne pas transférer".
2.) Turn it to a template using CIPP.
3.) Deploy the template using "Deploy Transport rule". 
4.) A bug appears "Could not create transport rule for domain.tld: Response status code does not indicate success: 500 (Internal Server Error)." Deploying it using standard doesn't lead to an error, the rules simply doesn't appear on the tenant.

Removing "é" from the rules fixes the bug. Rules work correctly on tenant if deployed manually.

### Environment data

```PowerShell
Sponsored instance 
Front end version number: 6.4.0
Back end version number: 6.4.0
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by KelvinTegelaar** [comment]
Microsoft has this same issue when running the PowerShell version - It seems only the webinterface for MS and not their APIs have support for accented characters, seeing as this is an MS issue we'll have to close. https://learn.microsoft.com/en-us/powershell/module/exchange/set-transportrule?view=exchange-ps
