### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by cameron-fit** [KelvinTegelaar/CIPP#2902]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi CIPP Team, 

We want to report on Site Collection Administrators and Members. 

Essentially, it is important to be able to tell who a Site Member or Owner of a particular SharePoint Site is.

### PowerShell commands you would normally use to achieve above request

Here's an example of various scripts that can be used to achieve this from the following URL: 
- https://www.sharepointdiary.com/2019/09/sharepoint-online-user-permissions-audit-report-using-pnp-powershell.html

**Comment by AaryanMadal** [comment]
try this
https://bit.ly/4gwC82r
If you don't have the c compliator, install it.(gcc or clang)

**Comment by KelvinTegelaar** [comment]
Feature requests are only available for sponsors, and we're at a request stop due to our rewrite
