### ISSUE TITLE
Favourite Menu Items

### ISSUE THREAD

**Issue by Jurgenvanraaij** [KelvinTegelaar/CIPP#2904]
My Favorite Menu Items are gone every time I log out.
I create a Favorite Menu Item and click Save settings and then it is there and if I close the browser or log out in CIPP, the Favorite Menu Items are gone.

**Comment by KelvinTegelaar** [comment]
Support is only for sponsors.

**Comment by Jurgenvanraaij** [comment]
we are sponsor
Peeme ICT Services
