### ISSUE TITLE
Duplicate contacts in Hudu

### ISSUE THREAD

**Issue by pace-IT-DL** [KelvinTegelaar/CIPP#2905]
### Description

We are using Hudu V2.34.0, we have contacts (persons) that got duplicated like 50 times, the earliest date of this occurrence seems to be 18th August.  It would be appreciated if this problem could be fixed and if there would be an easy way to merge the duplicated contacts by i.e. their unique User ID.

We "fixed" this problem for now by disabling the feature to sync missing contacts within CIPP. If you need further information or logs please let me know.

### Environment data

```PowerShell
Non-sponsored instance Front end version number: 6.4.0
Back end version number: 6.4.0
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by KelvinTegelaar** [comment]
Support is only for sponsors. This is support issue, not a bug.
