### ISSUE TITLE
[Feature Request]: Static Header on table of tenants

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#2909]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Have the title row showing the name of the portal and the filter input static as the table is scrolled. Maybe also have the 'last page and 'next page' on the top as well as the bottom.

**Comment by procradminator** [comment]
Do you think it would be too much trouble to add a comment on why the suggestion has been marked as "compelted" ?

I have no idea if it's a crap idea. If it's already been suggested or if you've just implemented it in the last 6 hours.

**Comment by KelvinTegelaar** [comment]
Sorry, was typing during our office hours, this is implemented in our rewrite.

**Comment by procradminator** [comment]
Thanks. Much appreciated.
