### ISSUE TITLE
[Feature Request]: Improve mailbox rule functionality

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2911]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

For rules, it doesn't seem we can disable rules, we can only delete - i would also love the ability to be able to either click into the rule to view it or edit it, or get a deep link to microsoft to allow the sam

**Comment by KelvinTegelaar** [comment]
Feature exist and is coming in the new release :)
