### ISSUE TITLE
[Feature Request]: reports on risky users via webook, e-mail, or psa

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2912]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

can we currently get reports on risky users via webook, e-mail, or psa?

this may be a modular design where we can configure other alerts for items in CIPP

**Comment by jonmonsystems** [comment]
I like this idea!

**Comment by JudgeDreddKLC** [comment]
bumping to make sure it doesn't auto-close!
