### ISSUE TITLE
[Feature Request]: Improve navigation for subject of interest

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2913]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Improve the navigation for subject of interest, if you're in a tenant wide view, then allow quick switching to other pages in CIPP that are tenant related. Same for users, if I'm in a user specific view, let me go to any other view in CIPP that is also user specific. For example, if I'm in the user detail view, allow me to switch into the BEC view, exchange view, onedriev view, etc - basically if I'm already interacting with a user or other object, it should be easy for me to switch into any other view/page that is related to that user

**Comment by JudgeDreddKLC** [comment]
bumping to make sure it doesn't auto-close!

**Comment by KelvinTegelaar** [comment]
In the new interface you'll be able to jump from BEC to other user based screens and vice-versa
