### ISSUE TITLE
[Feature Request]: Tenant Groups for standards deployment

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2917]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Duplicate of https://github.com/KelvinTegelaar/CIPP/issues/2843, which was closed for the rewrite of the UI

Our MSP services a wide variety of industries with varying needs. For example, the standards we'd like to deploy to our Legal clients differ drastically from those we'd like to deploy to our hospitality clients. The current standards deployment makes it very difficult to deploy standards to subsets of tenants. The All tenants feature and the ability to exclude tenants from the All tenants standard are great, but it doesn't allow us to deploy standards to specific subsets of clients without going into each tenant making the changes, which makes it very difficult to keep track of which settings are applied to tenants.

There are so many amazing features in CIPP that we want to utilize, but we can't deploy most of them to all tenants for whatever reason. For example, we want to deploy the Quarantine Release Request Alert standard to all of the clients that don't have their own IT. However, we don't want to exclude those 20% of our tenants that have internal IT teams from the other standards that we have configured on All Tenants. Having tenant groups would allow us to more accurately deploy standards to our clients based on which category they fall under.

**Comment by JudgeDreddKLC** [comment]
bumping to make sure it doesn't auto-close!
