### ISSUE TITLE
[Feature Request]: Purview management

### ISSUE THREAD

**Issue by jonmonsystems** [KelvinTegelaar/CIPP#2918]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

I would like to manage purview settings and policies in CIPP. I know MS has changed and moved around so much and is making it pain for everyone. I am sure you are use to many requests always wanting more manageable settings in CIPP. I am sure adding in Purview management would be an undertaking but I feel it's critical as it's here to stay and I would love to manage just about everything in CIPP lol. Thank you!
We are a CIPP monthly sub customer.

**Comment by KelvinTegelaar** [comment]
Microsoft does not expose purview via APIs, so this is a can't do, at least not now. Check back later. :)

**Comment by jonmonsystems** [comment]
Ah that is a shame! Good to know. How often does MS open up new APIs for additional management? I will watch for news on this front for the future.

**Comment by ForestGreen23** [comment]
Is this still a 'can't do'?
