### ISSUE TITLE
[Feature Request]: Add a standard to enable or disable "Show keep user signed in"

### ISSUE THREAD

**Issue by mcabreralvl2** [KelvinTegelaar/CIPP#2919]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Add a standard to enable or disable "Show keep user signed in"  

Improved admin User Experience to centrally manage tenant option in CIPP For environments with strict security policies.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create Feature Requests

**Comment by JudgeDreddKLC** [comment]
@KelvinTegelaar Manny works for RYC, please re-open. Thanks.

**Comment by KelvinTegelaar** [comment]
Ty Kent!
