### ISSUE TITLE
[Feature Request]: Deploy 'Enable MFA Allow' by Group

### ISSUE THREAD

**Issue by mcabreralvl2** [KelvinTegelaar/CIPP#2920]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Deploy 'Enable MFA Allow' by Group

Currently, administrators can only apply "Enable MFA Allow" settings broadly across the tenant. There is a need for more granular control to apply these settings by group, which allows for targeted security enforcement and gradual rollout within an organization.

Add functionality within CIPP to enable "Enable MFA Allow" based on specific groups rather than at the tenant-wide level. This would provide flexibility to administrators to apply MFA policies in stages or to specific subsets of users, such as high-security roles, departments, or pilot groups.

Manual application of MFA settings through Azure AD per group, which is time-consuming and does not benefit from the streamlined automation and management that CIPP offers.

The ability to apply MFA policies by group within CIPP will improve security management and allow for better customization of user access policies based on organizational needs. It can also help MSPs better align with client security policies and requirements.

**Comment by KelvinTegelaar** [comment]
Only sponsors are allowed to create feature request, and even then this would not be a feature request we entertain; MSPs would use this to decrease the security of tenants, not improve. All your users require MFA, no exceptions.

**Comment by JudgeDreddKLC** [comment]
@KelvinTegelaar Manny works for RYC, please re-open. Thanks.
