### ISSUE TITLE
[Feature Request]: Customize Report

### ISSUE THREAD

**Issue by loub2001** [KelvinTegelaar/CIPP#2926]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Customize the report with an own css

**Comment by KelvinTegelaar** [comment]
Thanks for submitting your feature request. However, it’s incomplete as it lacks the following required details:

- A more in-depth explanation of the feature, including the reasoning and benefits for MSPs. For feature requests we ask for atleast one or two complete paragraphs with situational explanations. Requests written by AI will be closed as these often contain too much yapping, not a lot of actual context.
-  we also ask for PowerShell commands you would normally use to achieve the requested customization, if applicable so we can make sure the request does what you need.


We’ve closed the issue for now. Feel free to submit a new, complete request at any time.
