### ISSUE TITLE
After switching tenant on Mailboxes list, the mailboxes refresh but the edit link uses old tenant

### ISSUE THREAD

**Issue by incedIT** [KelvinTegelaar/CIPP#2927]
### Description

Select a tenant from the dropdown at top of CIPP
Go to Email & Exchange, Mailboxes to load list for that tenant
Switch tenant using dropdown at the top of CIPP, this loads the new tenant's mailboxes
The Edit button on the listed mailboxes shows the previous tenant
e.g. https://cipp.mydomain.com/email/administration/edit-mailbox-permissions?tenantDomain=**tenant1**.com&userId=mailbox@**tenant2**.com
Refreshing the tenant box or mailbox list does not fix, refreshing the web page does

### Environment data

```PowerShell
Non-sponsored
Frontend: 6.4.1
Backend: 6.5.0
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by incedIT** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in rewrite.
