### ISSUE TITLE
[Feature Request]: CIPP API endpoint for expiring app secrets

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2931]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We understand we can use Graph directly to grab a list of expiring app secrets.  However, this is a widespread use case and one that we would love to use via the CIPP API and CIPP PowerShell module. 

We want to sync all expiring app secrets into our other systems and rely on the CIPP API. 

All we would need is a new endpoint that gives a list of expiring app secrets for a specific tenant.

**Comment by KelvinTegelaar** [comment]
As we already have alerting for this, we wont be adding the endpoint.
