### ISSUE TITLE
Deployment of default Intune Policies with variables do not replace variables

### ISSUE THREAD

**Issue by PeterVive** [KelvinTegelaar/CIPP#2935]
### Description

Hello,

By default there is an Intune Policy called "CIPP: Enable Onedrive Silent Logon and Known Folder Move".
Deploying this using the "Standards" feature results in the "%tenantid%" being deployed into the actual policy on the tenant.

![image](https://github.com/user-attachments/assets/7011f0d9-ced7-4569-8860-ed03c652834e)

Manually deploying the template policy does work since you can specify the value to replace the variable with.

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 6.4.1
Back end version number: 6.5.0
Tried tenant cache clear: true
Tried token cache clear: true
```

**Comment by PeterVive** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Support issue, not a bug. Feel free to contact our support if you are a sponsor!
