### ISSUE TITLE
Documentation has a duplicate for and is missing store details

### ISSUE THREAD

**Issue by agileit-team** [KelvinTegelaar/CIPP#2936]
### Description

Both URLs have the same documentation for chocolatey with none for the "Add Store app"

https://docs.cipp.app/user-documentation/endpoint/applications/add-choco-app
https://docs.cipp.app/user-documentation/endpoint/applications/add-winget-app

### Environment data

```PowerShell
This is from the public website for the documentation
```

**Comment by agileit-team** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug


Thank you,

Liam O’Brien | Senior Solutions Consultant

Direct +613 8652 9564







AGILE IT SOLUTIONS PTY LTD

Phone 1300 859 910 | Web: www.agileit.com.au<http://www.agileit.com.au/>



________________________________

**Comment by nts-brien** [comment]
this is still the case and I've not seen an update in my discord searches either.
