### ISSUE TITLE
Missing newer Microsoft Subscriptions

### ISSUE THREAD

**Issue by 5q-cipp** [KelvinTegelaar/CIPP#2939]
### Description

CIPP does not have handling for newer SKUs within the "Users" report, showing which licenses are assigned to each user. For example, we have a user who has two newer SKUs: Microsoft Teams Enterprise, and Microsoft 365 E5 (no Teams), along with an older Microsoft Power Automate Free license.  Viewing the API call results for the user reveals that it sees all three SKUs:

    "assignedLicenses": [
      {
        "disabledPlans": [],
        "skuId": "f30db892-07e9-47e9-837c-80727f46fd3d"
      },
      {
        "disabledPlans": [],
        "skuId": "7e31c0d9-9551-471d-836f-32ee72be4a01"
      },
      {
        "disabledPlans": [],
        "skuId": "18a4bd3f-0b5b-4887-b04f-61dd0ee15f5e"
      }
    ]

However, in the "Users" list, only the older Power Automate license shows up, the other two are not reflected at all.

![image](https://github.com/user-attachments/assets/ba238a17-ed5f-429a-901a-8d40da5c659b)

### Environment data

```PowerShell
Non-sponsored instance, currently patched, cleared all caches with no impact.
```

**Comment by KelvinTegelaar** [comment]
Not a bug, support issue. If you're a sponsor feel free to contact support.

**Comment by 5q-cipp** [comment]
> Not a bug, support issue. If you're a sponsor feel free to contact support.

Can you clarify this statement a bit? It is not displaying the subscription data properly when queried so what designates this as a sponsor issue versus a bug? The subscriptions for any client, sponsor or not would be the same and if the application is not displaying the data correctly, does that not constitute a bug?

Is this something which would be fixed in an upcoming release or no? Otherwise, the validity of the data is not trustworthy?

**Comment by KelvinTegelaar** [comment]
As I said, this isnt a bug but a support issue and has to do with permissions. If you're a sponsor you can contzct the helpdesk and they'll get you setup right.
