### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by telstrasupport** [KelvinTegelaar/CIPP#2941]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

When using the offboarding wizard is it possible for the display name of the ex-employee to be updated. 
With some tenant we do not delete the user however we do add a ZZ- to the front of the display / username. 

This allows for all ex-employees to be moved to the bottom of the tenant for easy management when they are happy to delete the user. 

### PowerShell commands you would normally use to achieve above request

Set-MsolUser -UserPrincipalName "user@example.com" -DisplayName "New Display Name"

**Comment by mpersak** [comment]
Hey, if you are doing this, I would also add ability to change primary email address to .onmicrosoft (without keeping any aliases) in case they don't want to receive emails to those accounts anymore

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests
