### ISSUE TITLE
[Feature Request]: Smart Task handling with error handling

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2951]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Tasks should not be executed live, instead they should be stored in db, and tasks should be tried sequentially. We should run verification scripts for each part and keep retrying until complete. Especially for cases of API throttling.

For example, I should be able to queue up 100 users to offboard, and it should go 1 by 1, checking each step, and repeating. 

I know this is a big one, and maybe it's already on the roadmap

**Comment by KelvinTegelaar** [comment]
This isn't the way CIPP is designed to work, nor how it will work. This is a wontfix :)
