### ISSUE TITLE
[Feature Request]: adding a custom repo for winget instead of just using the MS store

### ISSUE THREAD

**Issue by b2bcorbit** [KelvinTegelaar/CIPP#2952]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We would love to use https://winget.run/ to push apps within CIPP as they have a way bigger catalogue.

**Comment by KelvinTegelaar** [comment]
Only sponsors can create feature requests.
