### ISSUE TITLE
[Feature Request]: Intune Device - Assign user

### ISSUE THREAD

**Issue by kennyt2097** [KelvinTegelaar/CIPP#2956]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Hi, for Intune devices we really need the capability to assign the user to the device, most of our clients use targeted application deployments, these do not work if the user is not assigned to the machine. We also need to be able to set some machines with no user so they effectively become multi user machines. 

At the moment we have to switch to the intune management console to do this, we would ideally like to have this option in the console and then in time have it as an option to assign a user to a machine on user creation. We are missing a device onboarding/offboarding option.

### PowerShell commands you would normally use to achieve above request

not 100% but something along the lines of this.

https://github.com/Mr-Tbone/Intune/blob/master/Intune-Set-PrimaryUsers.ps1

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for your interest in improving CIPP! To keep our development process focused and manageable, feature requests are limited to paying users. This policy helps us prioritize improvements that directly benefit those actively supporting CIPP and ensure we can sustain our development and support.

When a sponsor makes a feature request, their support covers training, development, documentation, and security checks. Allowing non-sponsor requests could lead to a backlog that would slow down updates and stretch resources thin, ultimately impacting the quality and sustainability of CIPP.

While we’ve closed this request, we appreciate your input, and you’re always welcome to participate in ongoing discussions or contribute to open issues. If you are a developer yourself, feel free to create a PR that includes your feature request or type "I'd like to work on this!" to assign the issue to yourself.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment and we'll reopen the issue.

Thank you for understanding,
The CIPP Team

**Comment by kennyt2097** [comment]
we are a paying member, what do you need from me to show this?

**Comment by kennyt2097** [comment]
We are a paying member and have our instance hosted by you.

***@***.***

Is this not good enough?

Thanks

Kenny Thornton​​​​
Technical Director
Signal Networks Ltd. trading as Signal IT Solutions is a company registered in England and Wales under number 04020291.
Registered office:3 Middle Bridge Business Park, Bristol Road, Portishead, BS20 6PN United Kingdom.
​Signal Networks Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.

**Comment by kris6673** [comment]
It is, but if the github account you are making the FR with, is not linked to the domain/enterprise account of the sponsoring org, we can't see if you are a sponsor or not 😊
