### ISSUE TITLE
Standards: Automatic version history on document libraries

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2957]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

https://learn.microsoft.com/en-us/sharepoint/plan-version-storage#understand-version-storage-under-automatic-limits

“Take an example of a file with a consistent version creation pattern between the months of June and January. When set to automatic, intermittent versions are purged as the versions age, resulting in a ~94% reduction 🤯 in version storage used compared to applying count limits only. 🥰”
By: Patrick Feninger

**Comment by kris6673** [comment]
Just wanted to pop in here and say that we currently cant do this, as setting the EnableAutoExpirationVersionTrim property is not possible right now, sorry :(
