### ISSUE TITLE
App consent request alerts seems to be broken and not triggering

### ISSUE THREAD

**Issue by kris6673** [KelvinTegelaar/CIPP#2962]
### Description

1. Enable the alert on a tenant
2. Wait one MS moment
3. Create an app consent request in a customer tenant the alert was enabled on
4. Wait fruitlessly for the alert to arrive :(

### Environment data

```PowerShell
Sponsored instance
Frontend: 6.4.1
Backend: 6.5.2
Tried Tenant Cache Clear: true
Tried Token Cache Clear: true
```

**Comment by kris6673** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Thanks boo! Fixing in the next hotfix.

**Comment by kris6673** [comment]
Bump to keep open

**Comment by KelvinTegelaar** [comment]
Fixed in dev
