### ISSUE TITLE
New Standard: set Exchange Rule Size 

### ISSUE THREAD

**Issue by JudgeDreddKLC** [KelvinTegelaar/CIPP#2967]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Apparently there is a limit of how much stage is consumed for email rules. The default is 64GB and can be set to a range of 32kb to 256kb

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules

another potential standard can be to truncate rule names to a certain amount of characters, by default some default rule names can be very long and when you have 60 such rules the li t rule names eat away at the rule shelve limit. 

An alert when a user is approaching this limit could also be helpful 

### PowerShell commands you would normally use to achieve above request

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules

Set-Mailbox -Identity <MailboxIdentity> -RulesQuota "<32 KB to 256 KB>"

**Comment by kris6673** [comment]
The default in Exchange 2010 is 64KB, but in Exchange Online it's the max of 256KB :)
https://learn.microsoft.com/en-us/powershell/module/exchange/set-mailbox?view=exchange-ps#-rulesquota

**Comment by KelvinTegelaar** [comment]
This is default, so no need! :)
