### ISSUE TITLE
[Feature Request]: Standard for Guest invite settings in Entra

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#2971]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would like a standard for the following setting in Entra, and be able to select from any of the options listed. 
![image](https://github.com/user-attachments/assets/7db957a1-2966-4712-932c-1cef20e94a55)

### PowerShell commands you would normally use to achieve above request

Unknown (to me), but apparently Kelvin knows! https://discord.com/channels/905453405936447518/905453405936447521/1303785004530405459

**Comment by KelvinTegelaar** [comment]
added in dev
