### ISSUE TITLE
[Feature Request]: Allow custom GDAP relationships

### ISSUE THREAD

**Issue by landiscipp** [KelvinTegelaar/CIPP#2985]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

It would be great to have the ability to use GDAP relationships that don't include all the CIPP recommended roles. Currently, the tenant onboarding wizard in CIPP does not continue unless the relationship has all of the recommended roles.
https://docs.cipp.app/setup/gdap/recommended-roles

For example, the permissions for the Cloud App Security Administrator role are all included in the Security Administrator role.

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for your interest in improving CIPP! To keep our development process focused and manageable, feature requests are limited to paying users. This policy helps us prioritize improvements that directly benefit those actively supporting CIPP and ensure we can sustain our development and support.

When a sponsor makes a feature request, their support covers training, development, documentation, and security checks. Allowing non-sponsor requests could lead to a backlog that would slow down updates and stretch resources thin, ultimately impacting the quality and sustainability of CIPP.

While we’ve closed this request, we appreciate your input, and you’re always welcome to participate in ongoing discussions or contribute to open issues. If you are a developer yourself, feel free to create a PR that includes your feature request or type "I'd like to work on this!" to assign the issue to yourself.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment and we'll reopen the issue.

Also checking your feature request, the information is incorrect: several graph apis require this role explicitly.

Thank you for understanding,
The CIPP Team
