### ISSUE TITLE
[Feature Request]: Automated Membership Management for Microsoft Teams Subchannels via Graph API Integration

### ISSUE THREAD

**Issue by kennypollock** [KelvinTegelaar/CIPP#2987]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

The proposed feature involves the addition of functionality in the CIPP platform to automate user membership management for Microsoft Teams subchannels (Shared and Private Channels) through integration with the Microsoft Graph API. Specifically, this feature would allow for the automatic addition and removal of users to designated subchannels based on department, role, or other user attributes, similar to how dynamic groups currently operate for Teams sites.

Current Limitation:
Microsoft Entra's dynamic group membership automatically manages user access to Teams sites but does not extend this capability to subchannels. Currently, adding users to subchannels must be done manually, even if users are automatically added to the parent Teams site.

Proposed Solution Using Graph API:
By leveraging Microsoft Graph API capabilities (reference: [Channel Membership API Documentation](https://learn.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-beta&tabs=http)), CIPP can extend its automation capabilities to manage subchannel memberships programmatically. This would enable users to:

Automatically add or remove members from subchannels based on predefined criteria (e.g., department).
Provide more granular and automated management of Teams channel access without manual intervention.
Reduce administrative burden and ensure consistent user experience during onboarding, transitions, or role changes within organizations.
Benefits for MSPs:
Increased Efficiency: Automating user addition/removal in subchannels streamlines user onboarding and reduces manual steps.
Enhanced User Experience: Ensures consistent access for users based on their roles without requiring manual adjustment, improving productivity and reducing potential access issues.
Time Savings: Automates repetitive and error-prone processes, freeing up IT staff time for higher-value tasks.
Scalability: Facilitates seamless management for larger organizations or MSPs handling multiple clients with complex channel structures.
Alignment with Zero Trust: Provides more granular control over who has access to specific communication channels, strengthening security practices.

### PowerShell commands you would normally use to achieve above request

# Get the Team and Channel details
$team = Get-Team -DisplayName "Sales Team"
$channel = Get-TeamChannel -GroupId $team.GroupId -DisplayName "Private Subchannel Name"

# Add a user to the subchannel
Add-TeamChannelUser -GroupId $team.GroupId -ChannelId $channel.Id -User "user@domain.com"

**Comment by rwllr** [comment]
I'd like to reopen this FR as a sponsor if possible.
This is better documented than #2069
