### ISSUE TITLE
[Feature Request]: Option to Rename User as part of Offboarding

### ISSUE THREAD

**Issue by PurpleGriffin** [KelvinTegelaar/CIPP#2992]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We have a few clients that like to rename users when they leave the company, usually x-Staff Name, z-Staff Name or Staff Name (Archive). This currently isn't possible via the offboarding wizard so it requires an additional step. This would just need to be the display name.

### PowerShell commands you would normally use to achieve above request

Get-MgUser -Filter "UserPrincipalName eq '$UserID'" | Update-MgUser -DisplayName $NewDisplayName

**Comment by KelvinTegelaar** [comment]
Requested before, this is a wontfix. Each msp does this different and we'd end up having to maintain 100 permutations and options. See old requests for this.

**Comment by PurpleGriffin** [comment]
It sounds like you're imagining needing to maintain multiple different rename templates or tick boxes to make a specific change automatically.
What I'm asking for is just a text box to allow a manual name change so a MSP can rename the account manually however they see fit.

Luke Manning
intense|technology
D 02 8318 9717  | P 02 9712 4888
