### ISSUE TITLE
Feature request: Message Trace

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#30]
Ability to run a message trace. "summary report" with an option of getting more details 
Input
- Time Range "2 days default setting"
- Senders address (drop down list of accounts or free textbox) 
- Recipients address (drop down list of accounts or free textbox) 

Output
- Date
- Recipient
- Subject
- Status

Get-MessageTrace
Get-MessageTraceDetail

**Comment by KelvinTegelaar** [comment]
v1 is finished. Unfortunately, we can't currently retrieve the detailed report for any e-mail older than 24 hours, which is why I've not yet implemented this part of the Feature Request yet. The code in the API is present for when it becomes available for longer than 24 hours.
