### ISSUE TITLE
[Feature Request]: New Standard for setting MDE Endpoints Security Alerts

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#3000]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

On this page in the Security portal (https://security.microsoft.com/securitysettings/endpoints/email_notifications?childviewid=alerts), you can configure email alerts for Endpoints based on severity.  We'd like this to be configurable in CIPP standards to easily deploy it to all clients. 

For example, we'd like to create a new Alerts notification rule with values similar to the following:
Alert Name: _MyMSP Alerts_
Recipients: _security@mspdomain.com_ 
Include organization name: _Yes_
Include organization-specific portal link: _Yes_
Include device information: _Yes_
Alert severity:  _Medium, High_

![image](https://github.com/user-attachments/assets/e80afe18-db49-4ead-a1db-65e6985a2172)

![image](https://github.com/user-attachments/assets/f36c6a8f-3f39-41dc-9955-c94d199351ad)

### PowerShell commands you would normally use to achieve above request

I don't actually know if this is possible. 😃

**Comment by HappyEarthDay** [comment]
I got lucky number #3000!!!!! What do I win?

**Comment by KelvinTegelaar** [comment]
You win the sad news that this isn't behind an API we can use :( I'm sorry HappyEarthDay
