### ISSUE TITLE
[Feature Request]: Automated Inactive Users report

### ISSUE THREAD

**Issue by HenrikAone** [KelvinTegelaar/CIPP#3003]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Automation of the Inactive Users report.

We are exploring the possibility of automating the Inactive Users report to facilitate sending it to customers on a regular basis.

It should be possible to indicate a Custom Mailaddress to send the report to. If possible, a customized report depending on who the customer are, as not all customers need all fields in the report.

The above would save a lot of manual time for MSPs and provide better service for customers.

Thank you.

**Comment by JohnDuprey** [comment]
@KelvinTegelaar - Ticket 17055568997

**Comment by KelvinTegelaar** [comment]
You can use the graph explorer for this, CIPP will never have the ability to email clients directly.
