### ISSUE TITLE
[Feature Request]: Allow Admins to hide CIPP Built-in Intune & CAP templates from other CIPP users

### ISSUE THREAD

**Issue by HappyEarthDay** [KelvinTegelaar/CIPP#3004]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

We want to be able to grant CIPP access to more people in our org, but it can get confusing for our techs when the first CAP or Intune template name they see in the list matches the sentiment of our custom templates but is different.  Our techs have been deploying the wrong templates, and we would like an ability in the Admin settings or similar to hide the CIPP built-in templates. 

For example, our CAPs templates include our partner tenant exclusion and standard naming convention, but the CIPP builtin templates do not.

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new setting to hide built-in templates in the SettingsGeneral component. This includes a new state variable, a toggle switch, and a function to update the setting. The change allows MSPs to hide CIPP built-in templates to prevent confusion and incorrect template deployment.

You can review changes in this commit: https://github.com/kkpo4553/KelvinTegelaar-CIPP-3004/commit/efd04b886ab20270cfdc285ed8db8a26bbb155f1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by KelvinTegelaar** [comment]
Deletion of default policies is possible in new interface
