### ISSUE TITLE
[Feature Request]: Ninja enhancement - LAPS link inside of Ninja (Microsoft 365 Device Links)

### ISSUE THREAD

**Issue by Pip513** [KelvinTegelaar/CIPP#3006]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Would provide quicker access to LAPS. The link below goes directly to the page that will contain all LAPS passwords for the tenant which is easier to use in cases where you're remoted into multiple devices at once to "fix something now."

### PowerShell commands you would normally use to achieve above request

https://entra.microsoft.com/"TENANTDOMAIN.COM"/#view/Microsoft_AAD_Devices/DevicesMenuBlade/~/LocalAdminPassword/menuId/Devices

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for your interest in improving CIPP! To keep our development process focused and manageable, feature requests are limited to paying users. This policy helps us prioritize improvements that directly benefit those actively supporting CIPP and ensure we can sustain our development and support.

When a sponsor makes a feature request, their support covers training, development, documentation, and security checks. Allowing non-sponsor requests could lead to a backlog that would slow down updates and stretch resources thin, ultimately impacting the quality and sustainability of CIPP.

While we’ve closed this request, we appreciate your input, and you’re always welcome to participate in ongoing discussions or contribute to open issues. If you are a developer yourself, feel free to create a PR that includes your feature request or type "I'd like to work on this!" to assign the issue to yourself.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment and we'll reopen the issue.

Thank you for understanding,
The CIPP Team
