### ISSUE TITLE
FEATURE REQUEST: 

### ISSUE THREAD

**Issue by cphinxxx** [KelvinTegelaar/CIPP#3009]
Requesting the following licenses be added to the excluded list:

Defender_for_Business_servers (needs to be purchased but is not assigned to users/devices)
Rights Management Adhoc
Nonprofit Portal
Communications Credits

I'm sure we'll stumble across more as we go but I think these are a few of the most annoying right now.

**Comment by KelvinTegelaar** [comment]
We don't add licenses to the list as some users might want to report onthem, for example; excluding these would mean not getting a reminder if a defender server is expiring, etc etc.
