### ISSUE TITLE
BUG: Code scanning has found issues in Userview.JS

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#302]
Codescanning has found issues in Userview.js: 

Directly writing user input (for example, a URL query parameter) to a webpage without properly sanitizing the input first, allows for a cross-site scripting vulnerability.

List of issues:

js/UserView.js:60
js/UserView.js:65
js/UserView.js:170
js/UserView.js:220

**Comment by lwhitelock** [comment]
I'll do this one
