### ISSUE TITLE
[Feature Request]: Custom Standards

### ISSUE THREAD

**Issue by gtgamit** [KelvinTegelaar/CIPP#3024]
### Description of the new feature - must be an in-depth explanation of the feature you want, reasoning why, and the added benefits for MSPs as a whole.

Started utilizing the tenant standards and found that I was able to think of a bunch of options i'd like to deploy and unify to my clients but they were not created yet (for example, setting a unified password expiration time limit as opposed to no expiration at all)
And although I'm sure this can be created, I think in the long term solutions would be to have the ability to set a custom PS code that will be pushed to the tenant in question. perhaps even creating a "store" like option of standards you can get from community shared ones.

### PowerShell commands you would normally use to achieve above request

For this example: Set-MsolPasswordPolicy -ValidityPeriod 365 -NotificationDays 14

**Comment by KelvinTegelaar** [comment]
Hello,

Thank you for your interest in improving CIPP! To keep our development process focused and manageable, feature requests are limited to paying users. This policy helps us prioritize improvements that directly benefit those actively supporting CIPP and ensure we can sustain our development and support.

When a sponsor makes a feature request, their support covers training, development, documentation, and security checks. Allowing non-sponsor requests could lead to a backlog that would slow down updates and stretch resources thin, ultimately impacting the quality and sustainability of CIPP.

While we’ve closed this request, we appreciate your input, and you’re always welcome to participate in ongoing discussions or contribute to open issues. If you are a developer yourself, feel free to create a PR that includes your feature request or type "I'd like to work on this!" to assign the issue to yourself.

Did you get this notification in error? Reply with a screenshot of your sponsorship payment and we'll reopen the issue.

Thank you for understanding,
The CIPP Team

**Comment by gtgamit** [comment]
Hey there,
I'd like to reopen this now that we're sponsors.

**Comment by KelvinTegelaar** [comment]
Hi @gtgamit.

Custom standards will never be possible in CIPP, we've explained this adnaseum in our discord. In general MSPs would use this too much to decrease the level of security available, one of our most requested features is "How do we disable MFA for all users" "How do we reset all user passwords to a password we know" and "How we do disable security features".

CIPP is made to implement best practices, and as such anything that goes what is regarded as best practices, e.g. NIST, CIS, etc will not be implemented.
