### ISSUE TITLE
BUG: Code scanning has found issues in datatablesMailboxMobileDevices.js

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#303]
Codescanning has found issues in datatablesMailboxMobileDevices.js:

Directly writing user input (for example, a URL query parameter) to a webpage without properly sanitizing the input first, allows for a cross-site scripting vulnerability.

List of issues:
js/datatables/datatablesMailboxMobileDevices.js:8
js/datatables/datatablesMailboxMobileDevices.js:9

**Comment by homotechsual** [comment]
I would like to work on this please!
