### ISSUE TITLE
BUG: Basic auth protocols all enabled after applying the Modern Auth standard

### ISSUE THREAD

**Issue by dloughland87** [KelvinTegelaar/CIPP#313]
**Describe the bug**
After applying the Modern Authentication standard to a tenant, all basic authentication protocols are enabled, even if previously disabled.

**Expected behavior**
Basic authentication protocols should be captured before enforcing modern authentication standards and reapplied to avoid allowing a previously disabled protocol unknowingly.

**Comment by KelvinTegelaar** [comment]
Confirmed by @homotechsual in discord. The API we use for this has unexpected behaviors:

![image](https://user-images.githubusercontent.com/49186168/143848385-4cc81295-9963-4e1b-b9d3-2dc4996b57a9.png)

**Comment by KelvinTegelaar** [comment]
Resolved in dev
