### ISSUE TITLE
FEATURE REQUEST:  Pull In Current License Usage

### ISSUE THREAD

**Issue by scootrz32** [KelvinTegelaar/CIPP#315]
**Is your feature request related to a problem? Please describe.**
I would like to see current license usage so I know whether I need to login and provision a new license tghrough our CSP vendor  or if there is an existing license available I can assign without logging into the partner portal to see free licenses.

**Describe the solution you'd like**
Maybe a spot to see current license usage and free licenses

**Describe alternatives you've considered**
Logging into the current partner portal to verify liceneses. 

**Additional context**

**Comment by KelvinTegelaar** [comment]
Planned to have in new tenant overview
