### ISSUE TITLE
BUG:  Slow performance while checking versions

### ISSUE THREAD

**Issue by karstentredion** [KelvinTegelaar/CIPP#317]
**Describe the bug**
Whenever the portal is opened for the first time it will check the version of CIPP on the frontpage, this casues my Edge tab to time out and ask me to close it.  This also happens with a empty cache.

**To Reproduce**
1. Go to the portal on Edge, make sure you cache is cleared.
2. The version numbers will be checking the current version with the newest version.
3. This proces sometimes take quite long and causes the tab to timeout and freeze.
4. When you wait it will get the correct numbers and after that you won't have any issue with it.

**Expected behavior**
To not freeze with new accounts or a emtpy cache.

**Screenshots**
![image](https://user-images.githubusercontent.com/47554581/144230471-4506ef6e-1403-4eb3-96ee-b87b6e6617a9.png)

**Desktop (please complete the following information):**
 - OS: W11
 - Browser Edge
 - Version  96.0.1054.34 (Officiële build) (64-bits)

**Comment by karstentredion** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by KelvinTegelaar** [comment]
fixed in dev
