### ISSUE TITLE
FEATURE REQUEST: Report/Change Sharepoint/Onedrive auditing

### ISSUE THREAD

**Issue by Robby-Swartenbroekx** [KelvinTegelaar/CIPP#321]
I want to be able to check in Unified Audit Log Ingestion is enabled for a tenant or not and be able to enable this if it isn't. Maybe a possibility to enable this in bulk

Get-AdminAuditLogConfig | FL UnifiedAuditLogIngestionEnabled

**Comment by lwhitelock** [comment]
Is this different from the Enable Unified Audit Log standard?
https://kelvintegelaar.github.io/CIPP/TenantAdministration/Standards.html

**Comment by KelvinTegelaar** [comment]
Closed as duplicate, available in bpa and standards
