### ISSUE TITLE
Feature Request: Tenant Baseline

### ISSUE THREAD

**Issue by svenga** [KelvinTegelaar/CIPP#341]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When onboarding a new tenant, we currently need to apply settings in diffrent portals and use some distributed posh scripts for the default settings (AAD, Teams, Intune, Defender, Compliance.... You name it, the whole settings are.). 
Since most of the small SMBs have the same configuration baseline, a feature like a "1 click configuration" would be a gamechanger. 
My inspiration is you normal "Standards" Section. 

What I got in my mind is the following: 
1. Choose Tenant 
2. Choose a tenant baseline (As an MSP, you have diffrent types of customers so there )
3. Enter the client's name to create a naming default for groups, Intune policies, Autopilot Profiles, etc. 
4. Configure the tenant 
5. If there are configurations drifts, the admin will get alerted and can approve the change or stick to the baseline 
![grafik](https://user-images.githubusercontent.com/25662851/144844502-3e23cf4f-1028-4767-847d-6c9f0d4ffa4f.png)

**Describe alternatives you've considered**
- Using posh-scripts
- Using Microsoft 365DSC 
- Using commercial availbale tools

**Additional context**

**Comment by KelvinTegelaar** [comment]
Not accepting new FRs due to temporary freeze. Try again after December.
