### ISSUE TITLE
Feature request: Add user defaults

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#41]
When adding a "user" allow system wide default setting for "Usage location"

**Comment by KelvinTegelaar** [comment]
Good one. @redanthrax  was speaking about adding cookies recently and I am thinking we'll have to for this feature. We can't and don't want to store any info server side.

**Comment by KelvinTegelaar** [comment]
Used localstorage, it no reuses the last location when you refresh; this also makes it each if you're adding users in bulk that need a different location.
