### ISSUE TITLE
FEATURE REQUEST: Display Product Name Instead of SKU Name Under Unused Licenses in BPA

### ISSUE THREAD

**Issue by ROI-Admin-User** [KelvinTegelaar/CIPP#412]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. 

**Describe the solution you'd like**
It would be helpful if CIPP showed the product name instead of the sku name when you click on the SKU count under the Unused Licenses column in the BPA. Example: "Dynamics 365 for Financials for IWs" instead of "Project_Madeira_Preview_IW_SKU"  

**Describe alternatives you've considered**
We can just log into the admin console and go to licensing for now. Just wanted to raise this request to help improve, assuming it's worth the effort. :)

**Additional context**
Currently, CIPP shows the SKU name and not the product name. Sometimes that lines up or gives you a ballpark (ex: EXCHANGESTANDARD) but sometimes it is wildly different (ex: PROJECT_MADEIRA_PREVIEW_IW_SKU).

**Comment by KelvinTegelaar** [comment]
will be done with react rewrite
