### ISSUE TITLE
Bug: Report\Mailbox List does not display correctly 

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#42]
**Describe the bug**
Report\Mailbox List does not display correctly missing items on right. if you zoom the page to 80% it shows

**To Reproduce**
1. Go to reports
2. Click on Mailbox Statistics
3. Pick company

**Screenshots**
![image](https://user-images.githubusercontent.com/15746724/137640437-022abf57-aa28-44db-9504-ecd05276ac97.png)
![image](https://user-images.githubusercontent.com/15746724/137640460-9bdbf0ff-d5d7-469d-b501-eaaba249235e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser edge
 - Version  94.0.992.50

**Comment by KelvinTegelaar** [comment]
This is an autohide feature, if you click on the line when the item is hidden, it should show the remaining columns. I'm thinking maybe we need to disable this feature or make it more clear.

@gavsto Maybe one you could look at?

**Comment by Pukkahq** [comment]
When its at 80% it looks ok. When you click on the line, with lots of additional email address its looks a mess.

![image](https://user-images.githubusercontent.com/15746724/137640793-bb91a35d-f6dc-4a53-a356-9621fed4d84a.png)

**Comment by Pukkahq** [comment]
@gavsto 1920x1080

**Comment by gavsto** [comment]
@Pukkahq I've made some changes to make the overall body size a bit more condensed and the padding. It's not necessarily a direct fix for this because it can only fit in what it can fit in and it looks like you have a UPN somewhere in that table that is extremely long. Let me know what you think of this change.
