### ISSUE TITLE
Permission Missing from Installation Instructions

### ISSUE THREAD

**Issue by halsey51013** [KelvinTegelaar/CIPP#434]
**Describe the bug**
I ran the permission checker after setting everything up and it listed I was missing the delegated permission Channel.Delete.All. Channel.Delete.All does not appear in the installation instructions at https://cipp.app/GettingStarted/Installation/ 

**Screenshots**
Error
![image](https://user-images.githubusercontent.com/30665665/145895836-2753aadf-5f70-4f13-a07c-3c19c5fc5e70.png)

Installation instructions with listed permissions
![image](https://user-images.githubusercontent.com/30665665/145896172-38d58bc6-2af5-4891-b219-a1a0f2cecd21.png)

**Comment by KelvinTegelaar** [comment]
added
