### ISSUE TITLE
Domain analyser for non email domains

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#439]
Not for a problem

Looking to get all green on the domains analyser page.

Some domains are not used for email and therefore there are recommended DNS records in place that appear as errors (red) on the page. Maybe have a checkbox next to each domain to mark as "email/not email" domain and the checks change for non email domains in line with something like these recommendations.

NOTE : sometimes we have domains in M365 only used for UPN, SharePoint or the like. Maybe CIPP can check the usage in M365 and avoid the need for a switch??

https://www.gov.uk/guidance/protect-domains-that-dont-send-email 

![image](https://user-images.githubusercontent.com/47219254/146024321-fbb9a8ea-8d08-467b-876d-c23005f30a33.png)

DNS records are as follows: 
![image](https://user-images.githubusercontent.com/47219254/146024559-ce205ea0-511f-4cb6-9c72-5e5390c207e0.png)

**Comment by KelvinTegelaar** [comment]
already fixed in dev
