### ISSUE TITLE
FEATURE REQUEST:  automatic license acquisition if the sku is MS direct.

### ISSUE THREAD

**Issue by zenmechanic** [KelvinTegelaar/CIPP#446]
I understand why this request may not be possible if licenses are purchased via CSP indirect as many CSP direct resellers may not have an API for it, but if the customers SKU is with MS direct, is it possible to automatically acquire a new license when editing a user if their free license count is 0? When logging in as a GA local to the tenant, if there are no free licenses, it will auto acquire one to assign.

**Comment by KelvinTegelaar** [comment]
Not going to be doing this, discussed earlier. Too little reward and a lot of possible issues with it :)
