### ISSUE TITLE
BUG: CIPP.app ssl cert expired

### ISSUE THREAD

**Issue by silver0a1** [KelvinTegelaar/CIPP#449]
https://cipp.app uses HSTS and the cert is expired according to firefox. Just FYI, please close this when read.

**Comment by KelvinTegelaar** [comment]
not correct, seems like this is a local issue: 
![image](https://user-images.githubusercontent.com/49186168/146388760-5c2b7bf9-75cf-487e-ba50-c3f891c7a623.png)

**Comment by lwhitelock** [comment]
Just checked and the cert is valid to March. Is it that you have filtering software like Cisco Umbrella trying to do a redirect for it being a newly registered domain?

**Comment by silver0a1** [comment]
Probably the darn DNS filter

**Comment by KelvinTegelaar** [comment]
Considering closed, but, thanks for reporting of course. If there is a new issue, let us know. :)
