### ISSUE TITLE
FEATURE REQUEST: Group List - Add option to pull group membership 

### ISSUE THREAD

**Issue by audian-benp** [KelvinTegelaar/CIPP#450]
**Is your feature request related to a problem? Please describe.**

NO

**Describe the solution you'd like**

Just had one of our customers request a list of memberships to all their groups.  Would be really nice to be able to have an option list all the groups, and then a button to save w/ or w/out memberships to the various formats (and likely would need a warning that it will take time to pull it)

**Describe alternatives you've considered**

**Additional context**

**Comment by KelvinTegelaar** [comment]
We currently don't accept any feature request, try again next year :)
