### ISSUE TITLE
FEATURE REQUEST: Management of Endpoint Analytics | Proactive remediations scripts

### ISSUE THREAD

**Issue by SEI-Mkittok** [KelvinTegelaar/CIPP#451]
**Is your feature request related to a problem? Please describe.**
I would like a way to centrally manage my Proactive remediation scripts in Intune

**Describe the solution you'd like**
I envision this as an extension for the interface for managing Intune applications/policies

**Describe alternatives you've considered**
Managing scripts every tenant *bleh*

**Additional context**
Example use case is cloudlaps:
https://msendpointmgr.com/cloudlaps/
I could push this remediation script out to each client and in the event, I need to update/change it then it is centrally managed.

**Comment by KelvinTegelaar** [comment]
We currently don't accept any feature request, try again next year :)
