### ISSUE TITLE
FEATURE REQUEST: Group Tenants

### ISSUE THREAD

**Issue by TP-REdwards** [KelvinTegelaar/CIPP#452]
**Describe the solution you'd like**
The ability to Group tenants.

E.g, where we work we have multiple teams that focus on specific clients and their specialities. It would be great to create a group for each team.

**Additional context**
Maybe a filter box or some other UI element on the Tenants choice page:
![image](https://user-images.githubusercontent.com/80802320/146706141-1b849112-24e1-4368-a8fb-d906199825f1.png)

**Comment by KelvinTegelaar** [comment]
We currently don't accept any feature request, try again next year :)

**Comment by jasontherand** [comment]
Hello from next year. I would like also like to see tenant groups, that way we can apply standards to all the tenants that use us for 365 security, while not applying them to the tenants we only do licensing/user management for.

**Comment by KelvinTegelaar** [comment]
Was recently requested and closed, not yet.
