### ISSUE TITLE
BUG: No Tenant  

### ISSUE THREAD

**Issue by hytekcomputersrocky** [KelvinTegelaar/CIPP#456]
**Describe the bug**
after successfully  deploying it on Azure no tenant will show up 
- all the permission is good 
![image](https://user-images.githubusercontent.com/95777976/146837819-e701cd46-08f4-40c1-af76-7db00719df3b.png)

![image](https://user-images.githubusercontent.com/95777976/146837935-f97cc35a-d0d5-4539-891a-508e2d87a689.png)

- there is error with access check 
![image](https://user-images.githubusercontent.com/95777976/146837879-ff953b28-3a90-40f4-9746-4222fd6ef45f.png)

any idea what we are doing wrong ? or what is the issue ?

**Comment by hytekcomputersrocky** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Not a bug, please check your tokens, they do not have an MFA claim, are not valid, or are blocked via conditional access.  The testing script in the documentation can also tell you more about the error.

**Comment by hytekcomputersrocky** [comment]
good day thank you for your replay the test script did not give me any error as you can see and permission check pass could you please advice me what could be the issue ? 
![image](https://user-images.githubusercontent.com/95777976/147592684-ed361a37-7b07-43ca-87c7-31efd7fe1153.png)
