### ISSUE TITLE
Bug: Insufficient Privileges when copying group membership from other user

### ISSUE THREAD

**Issue by mr-macedawg** [KelvinTegelaar/CIPP#468]
When creating a new user and using the "Copy group membership from other user", it attempts to copy dynamic groups which you cannot manually add users to.

In this instance, it is the All Users group.
Created user.
Username: testuser@x.com.au
Password: ********
Assigned licenses.
We've failed to add the group All Users: Insufficient privileges to complete the operation.
Added group: Some Group

Can this function ignore dynamic groups?

**Comment by KelvinTegelaar** [comment]
will be fixed in frontend rewrite
