### ISSUE TITLE
FEATURE REQUEST: Whitelist Intune Device Licenses from "Unused Licenses" Check in BPA

### ISSUE THREAD

**Issue by cnolan-nt** [KelvinTegelaar/CIPP#470]
**Is your feature request related to a problem? Please describe.**
Since Intune Device Licenses are not actually assigned, they will always be "unused" even when they are needed. 

**Describe the solution you'd like**
It would be nice to have these not trigger the "Unused Licenses" column in the Best Practices Analyser

**Describe alternatives you've considered**
Currently I just ignore these, but it would be nice to turn these reds into greens.

**Comment by mdewart-springpoint** [comment]
Custom thresholds on all licenses would be nice. - Being able to mark a SKU as ignored or say "This client always keeps 5 extra of this SKU so they don't have to contact us for new hires, ignore up to 5 unused licenses, become noncompliant when it hits 6."

**Comment by dan-baird** [comment]
> Custom thresholds on all licenses would be nice. - Being able to mark a SKU as ignored or say "This client always keeps 5 extra of this SKU so they don't have to contact us for new hires, ignore up to 5 unused licenses, become noncompliant when it hits 6."

Agree this FR should really be custom license thresholds. For example Stream trial or Universal Print shows up with a 1000 licenses it can mess with the reports
