### ISSUE TITLE
React pre-release task: Check all functionality on pages - Bounty: $200,-

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#479]
This is a task for QA testing. Each function on the new react pages must be checked, if a function does not work as expected, a new issue must be created. This includes spelling mistakes, interface bugs, etc.

This is also the first issue in which we try out our new bounty program, that are possible thanks to sponsors. The bounty can only be claimed upon **full** completion of the task,  and will be offered in the form of an amazon gift card. If multiple users work on the issue at the same time, the split will be done equally amongst the users.

Deadline: **Sunday 9th of January.**

# Identity Management

## Administration

- [ ] Users
    - [ ] View User
    - [ ] Edit User
    - [ ] Research Compromised Account
    - [ ] Send MFA Push to User
    - [ ] Convert to Shared
    - [ ] Block Sign-in
    - [ ] Reset Password (Must Change)
    - [ ] Reset Password
    - [ ] Delete User
- [ ] Groups
    - [ ] Edit Group
- [ ] Roles
- [ ] Offboarding Wizard

## Reports

- [ ] Devices
- [ ] MFA Report
- [ ] Basic Auth Report

# Tenant Administration

## Administration
- [ ] Tenants
    - [ ] Edit Tenant
- [ ] Conditional Access Policies

## Standards
- [ ] List Applied Standards
    - [ ] Delete Standard
- [ ] Apply Standard
- [ ] Best Practice Analyzer
- [ ] Individual Domain Check
- [ ] Alert List (Alpha)

# Endpoint Management

## Applications
- [ ] List
    - [ ] Edit Applications
    - [ ] Assign to all Users
    - [ ] Assign to all Devices
    - [ ] Assign Globally (All Devices, All Users)
- [ ] Add Choco App

## Autopilot
- [ ] Add Device
- [ ] Add Profile
- [ ] Add Status Page
- [ ] List Devices
    - [ ] Delete Device
- [ ] List Profiles
    - [ ] Edit Profile
- [x] List Status Pages
    - [x] Edit Status Page

## Intune
- [x] List Intune Policies
    - [x] Edit Policy
- [x] Apply Policy
- [x] Add Policy Template
- [x] List Templates
    - [x] Delete Template

## Defender
- [ ] List Defender for Endpoint
    - [ ] View Device
    - [ ] Execute Quick Scan
    - [ ] Execute Full Scan
    - [ ] Remote Wipe

# Teams & Sharepoint

## OneDrive
- [x] List OneDrive
    - [x] Edit User
## Sharepoint
- [x] List Sharepoint
    - [x] Edit Group
## Teams
- [ ] Business Voice
    - [x] View Team Settings
- [x] List Teams
    - [x] View Team Settings
    - [x] Edit Group Members
    - [x] Delete Team
- [x] Add Team
- [x] Teams Activity

# Email & Exchange

## Administration
 - [x] Mailboxes
    - [x] View User
    - [x] Edit Mailbox Permissions
    - [x] View Mobile Devices
    - [x] Convert to Shared Mailbox
    - [x] Convert to User Mailbox - 
- [x] Contacts
    - [x] Edit Contact
 
## Reports
- [x] Mailbox Statistics
- [x] Mailbox Client Access Settings
- [x] Message Trace
- [x] Phishing Policies

# Settings

## CIPP
- [x] Documentation
- [x] Settings

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
View User #480

**Comment by homotechsual** [comment]
BEC page is blank #363

**Comment by homotechsual** [comment]
MFA push displays blank modal. #481

**Comment by homotechsual** [comment]
Convert to Shared Mailbox #482

**Comment by homotechsual** [comment]
Block sign-in #483

**Comment by homotechsual** [comment]
Working on users only currently. Feel free to pick another page!

**Comment by AdamWillford** [comment]
#485 DNS Resolver Selection

**Comment by AdamWillford** [comment]
#486 Excluded Tenants

**Comment by AdamWillford** [comment]
#487 Backend Buttons

**Comment by AdamWillford** [comment]
#488 Set Notifications Results

**Comment by AdamWillford** [comment]
#494 Edit Contacts

**Comment by AdamWillford** [comment]
#495 Edit Mailbox Perms

**Comment by AdamWillford** [comment]
#496 View Mobile Devices

**Comment by AdamWillford** [comment]
#497 Convert to User / Shared Mailbox

**Comment by AdamWillford** [comment]
#498 List Teams dropdown

**Comment by AdamWillford** [comment]
#499 Sharepoint List Dropdown

**Comment by AdamWillford** [comment]
#500 Edit User on OneDrive

**Comment by AdamWillford** [comment]
#503 Edit MEM Policy

**Comment by AdamWillford** [comment]
#505 Autopilot Profiles Dropdown

**Comment by AdamWillford** [comment]
#507 List Autopilot Devices - Dropdown

**Comment by AdamWillford** [comment]
#510 Edit Application - Dropdown

**Comment by AdamWillford** [comment]
AW's updated list so far (05/01)
> 
> # Identity Management
> ## Administration
> * [ ]  Users
>   
>   * [ ]  View User
>   * [ ]  Edit User
>   * [ ]  Research Compromised Account
>   * [ ]  Send MFA Push to User
>   * [ ]  Convert to Shared
>   * [ ]  Block Sign-in
>   * [ ]  Reset Password (Must Change)
>   * [ ]  Reset Password
>   * [ ]  Delete User
> * [ ]  Groups
>   
>   * [ ]  Edit Group
> * [ ]  Roles
> * [ ]  Offboarding Wizard
> 
> ## Reports
> * [ ]  Devices
> * [ ]  MFA Report
> * [ ]  Basic Auth Report
> 
> # Tenant Administration
> ## Administration
> * [ ]  Tenants
>   
>   * [ ]  Edit Tenant
> * [ ]  Conditional Access Policies
> 
> ## Standards
> * [ ]  List Applied Standards
>   
>   * [ ]  Delete Standard
> * [ ]  Apply Standard
> * [ ]  Best Practice Analyzer
> * [ ]  Individual Domain Check
> * [ ]  Alert List (Alpha)
> 
> # Endpoint Management
> ## Applications
> * [X]  List
>   
>   * [X]  Edit Applications
>   * [X]  Assign to all Users
>   * [X]  Assign to all Devices
>   * [X]  Assign Globally (All Devices, All Users)
> * [X]  Add Choco App
> 
> ## Autopilot
> * [ ]  Add Device
> * [ ]  Add Profile
> * [X]  Add Status Page
> * [X]  List Devices
>   
>   * [X]  Delete Device
> * [X]  List Profiles
>   
>   * [X]  Edit Profile
> * [X]  List Status Pages
>   
>   * [X]  Edit Status Page
> 
> ## Intune
> * [X]  List Intune Policies
>   
>   * [X]  Edit Policy
> * [X]  Apply Policy
> * [X]  Add Policy Template
> * [X]  List Templates
>   
>   * [X]  Delete Template
> 
> ## Defender
> * [ ]  List Defender for Endpoint
>   
>   * [ ]  View Device
>   * [ ]  Execute Quick Scan
>   * [ ]  Execute Full Scan
>   * [ ]  Remote Wipe
> 
> # Teams & Sharepoint
> ## OneDrive
> * [X]  List OneDrive
>   
>   * [X]  Edit User
> 
> ## Sharepoint
> * [X]  List Sharepoint
>   
>   * [X]  Edit Group
> 
> ## Teams
> * [ ]  Business Voice
>   
>   * [X]  View Team Settings
> * [X]  List Teams
>   
>   * [X]  View Team Settings
>   * [X]  Edit Group Members
>   * [X]  Delete Team
> * [X]  Add Team
> * [X]  Teams Activity
> 
> # Email & Exchange
> ## Administration
> * [X]  Mailboxes
>   
>   * [X]  View User
>   * [X]  Edit Mailbox Permissions
>   * [X]  View Mobile Devices
>   * [X]  Convert to Shared Mailbox
>   * [X]  Convert to User Mailbox -
> * [X]  Contacts
>   
>   * [X]  Edit Contact
> 
> ## Reports
> * [X]  Mailbox Statistics
> * [X]  Mailbox Client Access Settings
> * [X]  Message Trace
> * [X]  Phishing Policies
> 
> # Settings
> ## CIPP
> * [X]  Documentation
> * [X]  Settings

**Comment by AdamWillford** [comment]
#550  Submit Standards

**Comment by AdamWillford** [comment]
#551 Dropdown on List Standards

**Comment by AdamWillford** [comment]
#555 Offboarding Wizard Bug

**Comment by AdamWillford** [comment]
#556 Offboarding Results + Tasks

**Comment by KelvinTegelaar** [comment]
And this Q&A round is done. We've paid out a bounty to @homotechsual and @AdamWillford. :)
