### ISSUE TITLE
BUG: View User page throws 500 error if no conditional access policies. [React] [QA]

### ISSUE THREAD

**Issue by homotechsual** [KelvinTegelaar/CIPP#480]
**Describe the bug**
The view user page throws a 500 API error if there is no 

**To Reproduce**
1. Go to 'Identity Management > Users'
2. Click on 'Any user without a CA policy applied and view user.'

**Expected behavior**
No error loading user details. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2288257/148253677-ff13cf38-f553-4c1d-af91-adbca597de25.png)
![image](https://user-images.githubusercontent.com/2288257/148253742-573a1cbe-a35d-4d63-be9f-21d3ec0e1cef.png)

**Additional context**
Nothing is present in the logs.

**Comment by AdamWillford** [comment]
Confirmed and same images~

`{
  "type": "users/executeQuery/rejected",
  "payload": {
    "status": 500,
    "data": "",
    "message": "Request failed with status code 500"
  },
  "meta": {
    "arg": {
      "type": "query",
      "subscribe": true,
      "subscriptionOptions": {
        "pollingInterval": 0
      },
      "endpointName": "listUserConditionalAccessPolicies",
      "originalArgs": {
        "tenantDomain": "xxxxxxx.onmicrosoft.com",
        "userId": "xxxxxxxxxx"
      },
      "queryCacheKey": "listUserConditionalAccessPolicies({\"tenantDomain\":\"xxxxxx.onmicrosoft.com\",\"userId\":\"xxxxxx\"})"
    },
    "requestId": "g0dNOLijFIi7VPoGXI9Tt",
    "rejectedWithValue": true,
    "requestStatus": "rejected",
    "aborted": false,
    "condition": false
  },
  "error": {
    "message": "Rejected"
  }
}`

**Comment by KelvinTegelaar** [comment]
expected behaviour when there is no P1 license. wondering if we should do something with this.

**Comment by homotechsual** [comment]
We at least need to handle that error gracefully imo.

**Comment by KelvinTegelaar** [comment]
Made sure that api returns 'n/a' by wrapping in try catch block.
