### ISSUE TITLE
BUG: Send MFA Push - blank modal - no push. [React] [QA]

### ISSUE THREAD

**Issue by homotechsual** [KelvinTegelaar/CIPP#481]
**Describe the bug**
Sending an MFA push from the actions menu for a user results in a confirmation box, confirming the operation shows a blank modal and does not trigger the MFA push notification.

**Expected behavior**
MFA push should be sent - box should confirm?

**Screenshots**
![image](https://user-images.githubusercontent.com/2288257/148256008-96f67078-7052-4cd6-b30d-b0ee7c8bc485.png)

**Comment by KelvinTegelaar** [comment]
resolved
