### ISSUE TITLE
BUG: Convert to Shared - Infinite spinner/blank modal. [React] [QA]

### ISSUE THREAD

**Issue by homotechsual** [KelvinTegelaar/CIPP#482]
**Describe the bug**!
When selecting a user and triggering convert to Shared Mailbox from the actions menu the result is a modal with an infinite spinner or a blank modal.

Nothing appears to be triggered on the API.

**Expected behavior**
The user should be converted to a Shared Mailbox and confirmation provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/2288257/148257677-f0e26f5b-8645-4fcd-ae4f-f6395b92797b.png)

**Comment by KelvinTegelaar** [comment]
resolved
