### ISSUE TITLE
BUG: Block sign-in - infinite spinner/blank modal [React] [QA]

### ISSUE THREAD

**Issue by homotechsual** [KelvinTegelaar/CIPP#483]
**Describe the bug**
Triggering the block sign-in action presents an infinite spinner or blank modal.

**Expected behavior**
The user sign-in should be blocked.

**Screenshots**
![image](https://user-images.githubusercontent.com/2288257/148259988-85655fc4-056e-4271-ad07-bf90802ba3ae.png)

**Comment by KelvinTegelaar** [comment]
resolved
