### ISSUE TITLE
BUG: [React] [UX] CIPP Settings - DNS Resolver Buttons

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#484]
**Describe the bug**
Styling of the buttons on the DNS Resolver settings as per image below

![image](https://user-images.githubusercontent.com/30923966/148264976-ce2c28c1-b4df-471a-8e3e-8aa3c87012d7.png)

Page: CIPP > CIPP > Settings

@homotechsual

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
tagging @johnduprey for the actual api changes

**Comment by KelvinTegelaar** [comment]
duplicate,
