### ISSUE TITLE
BUG: [React] [QA] DNS Resolver Selection

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#485]
**Describe the bug**
Select a provider, has a green banner but no text

![image](https://user-images.githubusercontent.com/30923966/148265190-51ead954-840e-4bcd-9d01-b1fa6ec86513.png)

Page: CIPP > CIPP > Settings

**Comment by johnduprey** [comment]
This is fixed in https://github.com/KelvinTegelaar/CIPP-API/commit/3bf176ef52b01be0068645698eb07d8ce8fc0da4#diff-8dba3c5f3e51d51f0da6cd2b56f4b542dbf02a3d3038bf4d5655b56c3055db5a
