### ISSUE TITLE
BUG: [React] [QA] Backend Buttons

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#487]
**Describe the bug**
On all of the cards, none of the buttons link to an actual URL - so nothing occurs to get to the resource

![image](https://user-images.githubusercontent.com/30923966/148265826-01c1e1ff-7248-4dc3-addc-06fe5c9e092c.png)

Page: CIPP > CIPP > Settings > Backend

**Comment by KelvinTegelaar** [comment]
backend now returns object.

**Comment by KelvinTegelaar** [comment]
fixed
