### ISSUE TITLE
BUG: [React] [QA] No results modal on "Set Notifications" button

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#488]
**Describe the bug**
When clicking "Set Notification Settings" on the Settings page, it saves them but no confirmation.  Refresh does persist the details.

Page: CIPP > CIPP > Settings > Notifications

![image](https://user-images.githubusercontent.com/30923966/148266241-ca591e5c-0250-49d0-a665-c8194db240ba.png)

**Comment by KelvinTegelaar** [comment]
fixed
