### ISSUE TITLE
BUG: [React] [UX] Text on Buttons - Settings 

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#489]
**Describe the bug**
Settings > Excluded Tenants
Settings > Notifications

On both the pages above, the text on the buttons is white text, instead of dark text

![image](https://user-images.githubusercontent.com/30923966/148266769-c56c7521-fe7c-43ea-a052-6c296ff463bc.png)
![image](https://user-images.githubusercontent.com/30923966/148266779-c40bc693-7c84-4dd1-9fd2-d0bbdec2fd59.png)

@homotechsual

**Comment by KelvinTegelaar** [comment]
fixed.
