### ISSUE TITLE
BUG: [React] [UX] Expand Status on Message Trace

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#491]
**Describe the bug**
When an error occurs on Message Trace, the error gets cut off on the table.  Need to amend to expand the status column

![image](https://user-images.githubusercontent.com/30923966/148267690-2d0cd26e-7f64-49ba-8c60-2e31f1906f3e.png)

@homotechsual

**Comment by KelvinTegelaar** [comment]
fixed by not placing the error there but in the toast, where it should go. :)
