### ISSUE TITLE
BUG: [React] [UX] Message Trace - Default not expanded

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#492]
**Describe the bug**
When in Message Trace, by default it doesn't expand the table for data entry - took me a hot second to realise there was an arrow to click.  Probably needs a default expand on it

![image](https://user-images.githubusercontent.com/30923966/148268042-0697aeb3-0d5c-4565-b46c-540bb275b997.png)

@homotechsual

**Comment by KelvinTegelaar** [comment]
expanded per default, collapse when query is executed.
