### ISSUE TITLE
BUG: [React] [UX] List Contacts - Dropdown Overflow

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#493]
**Describe the bug**
Dropdown overflow not fixed on this page

![image](https://user-images.githubusercontent.com/30923966/148268590-cbc26d49-b7dc-4303-ab8b-7730417be248.png)

@homotechsual

**Comment by homotechsual** [comment]
What page is this @AdamWillford ?

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by AdamWillford** [comment]
Sorry thought I had put page on them all, it's 

CIPP
Email & Exchange
Email Administration
List Contacts

@homotechsual

**Comment by KelvinTegelaar** [comment]
resolved
