### ISSUE TITLE
BUG: [React] [QA] Edit Contact

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#494]
**Describe the bug**
Edit Contact page - no content

CIPP
Email & Exchange
Email Administration
Edit Contact (Dropdown)

**Comment by KelvinTegelaar** [comment]
EditContact in current release forwards to MS portal:

https://outlook.office365.com/ecp/@${row.tenantdomain}/UsersGroups/EditContact.aspx?exsvurl=1&realm=${tenant.id}&mkt=en-US&id=${row.id}

Replicating behavior in react now

**Comment by KelvinTegelaar** [comment]
replicated behavior's.
