### ISSUE TITLE
BUG: [React] [QA] View Mobile Devices

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#496]
**Describe the bug**
Status 500:

![image](https://user-images.githubusercontent.com/30923966/148269351-a257e8fd-454f-4e9b-a4c6-bf0cf61a8cd5.png)

`{
  "type": "datatable/executeQuery/rejected",
  "payload": {
    "status": 500,
    "data": "",
    "message": "Request failed with status code 500"
  },
  "meta": {
    "arg": {
      "type": "query",
      "subscribe": true,
      "subscriptionOptions": {
        "pollingInterval": 0
      },
      "endpointName": "listDatatable",
      "originalArgs": {
        "path": "/api/ListMailboxMobileDevices",
        "params": {
          "TenantFilter": "xxxxxx.co.uk"
        }
      },
      "queryCacheKey": "listDatatable({\"params\":{\"TenantFilter\":\"xxxxxx.co.uk\"},\"path\":\"/api/ListMailboxMobileDevices\"})"
    },
    "requestId": "eHyygLV0dHmTVmRIsPBi0",
    "rejectedWithValue": true,
    "requestStatus": "rejected",
    "aborted": false,
    "condition": false
  },
  "error": {
    "message": "Rejected"
  }
}`

CIPP
Email & Exchange
Email Administration
View Mobile Devices

**Comment by KelvinTegelaar** [comment]
fixed
