### ISSUE TITLE
BUG: [React] [QA] Exchange Mailboxes - No conversion possible

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#497]
**Describe the bug**
Trying to convert either shared or user mailbox fails due to no link to API on the dropdown

![image](https://user-images.githubusercontent.com/30923966/148269619-0351332d-be3a-44d5-9ecf-4c14d9d42813.png)

Page: CIPP
Email & Exchange
Email Administration
List Mailboxes

**Comment by KelvinTegelaar** [comment]
resolved
