### ISSUE TITLE
BUG: [React] [QA] Sharepoint List - Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#499]
**Describe the bug**
Edit Group not linked to API correctly, needs amending 

![image](https://user-images.githubusercontent.com/30923966/148270557-b1ab119c-2083-494c-8ed5-d728e9c44b9c.png)

Page: CIPP
Teams & Sharepoint
Sharepoint
List Sharepoint

**Comment by KelvinTegelaar** [comment]
resolved
