### ISSUE TITLE
BUG: [React] [uX} Hamburger Colour on Templates

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#501]
**Describe the bug**
Action dropdown hamburger be the wrong colour yo

![image](https://user-images.githubusercontent.com/30923966/148271580-1017900d-e70e-4bc1-9b7b-f0e93517c809.png)

Page: CIPP
Endpoint
MEM
List Intune Policy Template

@homotechsual

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed by #524
