### ISSUE TITLE
BUG: [React] [UX] MEM Policy - Filter Tenant

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#502]
**Describe the bug**

On the wizard, need a tenant filter on the "Select a tenant" page

![image](https://user-images.githubusercontent.com/30923966/148271852-1f6cc09a-945b-40a5-92a7-8e2c299ebf34.png)

Need to amend card title to MEM from Intune also

@homotechsual

**Comment by KelvinTegelaar** [comment]
I see a tenantfilter, cannot reproduce. :)

**Comment by AdamWillford** [comment]
I'm intrigued.  Where does your filter tenant show?

![image](https://user-images.githubusercontent.com/30923966/148392650-9a879bc6-e803-45df-a13e-bdaad1fd6517.png)

**Comment by homotechsual** [comment]
I just get a select-table for tenants.

**Comment by homotechsual** [comment]
Those fields are built with `<CippDatatable
        keyField={keyField}
        columns={columns}
        striped
        path={path}
        tableProps={{
          selectableRows: true,
          onSelectedRowsChange: this.handleSelect,
          subheader: false,
        }}
      />`

**Comment by homotechsual** [comment]
So no header = no filter.

**Comment by homotechsual** [comment]
![image](https://user-images.githubusercontent.com/2288257/148396097-2792cfcd-57be-41ec-b120-158d5b77c5f0.png)

**Comment by homotechsual** [comment]
This fix will be PR'd soon.

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed :-)
