### ISSUE TITLE
BUG: [React] [QA] Edit MEM Policy - No Content

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#503]
**Describe the bug**
Amending policy via dropdown goes to blank page with no content

![image](https://user-images.githubusercontent.com/30923966/148272317-ba64fce8-152d-45de-b454-287d20cbecb9.png)

Page: CIPP
Endpoint
MEM
Edit MEM Policy

**Comment by AdamWillford** [comment]
On prod

Intune > List Intune Policies > Action cog

![image](https://user-images.githubusercontent.com/30923966/148393057-b437d4f4-2373-46f8-a95f-f466fa6aec30.png)

**Comment by KelvinTegelaar** [comment]
And right you are sir, Fixed.
