### ISSUE TITLE
BUG: [React] [QA]  Autopilot Status Page Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#504]
**Describe the bug**

Edit Status Page via dropdown goes to a 404

![image](https://user-images.githubusercontent.com/30923966/148272615-337eb19a-4aed-4b32-b333-cb41d644d0d3.png)

Page: CIPP
Endpoint
Autopilot
List Status Pages

**Comment by KelvinTegelaar** [comment]
resolved
