### ISSUE TITLE
BUG: [React] [QA] List Autopilot Profiles - Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#505]
**Describe the bug**
Dropdown goes to a 404 on Edit Profile

![image](https://user-images.githubusercontent.com/30923966/148273246-0facbebe-8d45-42a2-9fa0-89f979b2d91e.png)

Page: 
CIPP
Endpoint
Autopilot
List Profiles

**Comment by KelvinTegelaar** [comment]
resolved
