### ISSUE TITLE
BUG: [React] [QA] Autopilot List Devices - Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#507]
**Describe the bug**
List Devices - Dropdown not working for Delete Device (not linked anywhere)

![image](https://user-images.githubusercontent.com/30923966/148273489-b800084b-4e36-4d11-8abd-764fb57e50c6.png)

Page: 

CIPP
Endpoint
Autopilot
List Devices

**Comment by KelvinTegelaar** [comment]
resolved
