### ISSUE TITLE
BUG: [React] [UX] Wizard Tenant Selector Pages 

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#508]
**Describe the bug**
On the first step, tenant selector, on the wizard pages it feels like the Next is in the wrong position.  Should be on the right, not on the left?

![image](https://user-images.githubusercontent.com/30923966/148273822-ef15e8b3-6f8f-47f3-b8e3-3d2cf3225ae6.png)

Affects all wizards (Guessing it'd DRY'ed somewhere)

@homotechsual

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed.
