### ISSUE TITLE
BUG: [React] [UX] Autopilot Profile Add - End Success Message

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#509]
**Describe the bug**
At the end of the wizard, there's a <br> text in the string

![image](https://user-images.githubusercontent.com/30923966/148274207-0ae3de87-3f6f-482c-a999-d4dba7965ecf.png)

CIPP
Endpoint
Autopilot
Add Profile

@homotechsual

**Comment by KelvinTegelaar** [comment]
removed linebreak from api
