### ISSUE TITLE
BUG: [React] [QA] Edit Application - Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#510]
**Describe the bug**
None of the actions work on the dropdown for Edit Applications

![image](https://user-images.githubusercontent.com/30923966/148274588-d90a5754-6aa0-4b98-8769-a8df445168a9.png)

404's on the func for Edit, none of the others are linked anywhere

**Comment by KelvinTegelaar** [comment]
fixed
