### ISSUE TITLE
BUG: [React] [UX] Wizard Add Choco App

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#511]
**Describe the bug**
On the confirmation page, it is missing the styling of the other wizards and is purely text based - no icons etc

![image](https://user-images.githubusercontent.com/30923966/148276754-ad4899d6-0751-43b7-8884-255b69217cd9.png)

This is on step 3, after you hit next on step 2

CIPP
Endpoint
Applications
Add Choco App

@homotechsual

**Comment by KelvinTegelaar** [comment]
Correct. This was a choice as it only has text headers. Will probably revise the way we do this centrally, after release. :)
