### ISSUE TITLE
BUG: [React] [UX] "List" under Applications

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#512]
**Describe the bug**
I just really don't like this, so I'm making you not like it either and hopefully you'll make it look better...

![image](https://user-images.githubusercontent.com/30923966/148276350-899903f8-e0e2-46f5-82a2-e8d1d6aaad57.png)

CIPP
Endpoint
Applications
List

@homotechsual

**Comment by KelvinTegelaar** [comment]
replaced with "List Applications"
