### ISSUE TITLE
BUG: [React] [UX] Settings Page - Search on Access Check

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#516]
**Describe the bug**
On Access Check, Select Search doesn't actually "Select" a tenant

Can't really screenshot, but it's obvious enough when you try :)

@homotechsual

**Comment by homotechsual** [comment]
I'd like to work on this please.

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
Cannot reproduce.

**Comment by homotechsual** [comment]
Okay this is a confusing UX issue - will revisit.

**Comment by KelvinTegelaar** [comment]
I think this is looking fine now, it's multi select and with the changes to the interface that become more clear, let me know if more changes are needed.
