### ISSUE TITLE
BUG: [React] [UX] Tenant Access Check - Results on Impact theme

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#517]
**Describe the bug**

The results table isn't themed for Impact

![image](https://user-images.githubusercontent.com/30923966/148358560-035a6d94-9759-4f9a-8a41-f60d78d63910.png)

(NB: There is another UX issue with the Select Search, so it's a little difficult to get to this stage where you can actually test a tenant - issue has been logged for that)

@homotechsual

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed.
