### ISSUE TITLE
BUG: [React] [UX] Button Loading Symbol

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#518]
**Describe the bug**

Noticed on every button that has a "loading" icon when clicked, that it needs a space between it and the text really

![image](https://user-images.githubusercontent.com/30923966/148358835-1a535bb7-a432-47e2-914b-a1127a974a07.png)

Maybe it's me being picky on this one... 

@homotechsual

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed :-)
