### ISSUE TITLE
BUG: [React] [UX] Dropdown Icons

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#519]
**Describe the bug**
Feel like we need a space between the icons on the dropdowns

![image](https://user-images.githubusercontent.com/30923966/148377227-7b875b4d-d6df-4948-986b-5832690eb679.png)

@homotechsual

**Comment by homotechsual** [comment]
Fixed by 56a4e2b

**Comment by homotechsual** [comment]
@KelvinTegelaar this can be closed :-)
