### ISSUE TITLE
BUG: Autopilot Add Policy Template loads the `MEMAddPolicyTemplate` screen. JS file for `AutopilotAddPolicyTemplate` is unfinished. [React] [QA]

### ISSUE THREAD

**Issue by homotechsual** [KelvinTegelaar/CIPP#526]
**Describe the bug**
The Add Autopilot Policy template screen is not built - it redirects to the MEMAddPolicyTemplate screen.

**Comment by KelvinTegelaar** [comment]
as far as I see this is done?

**Comment by KelvinTegelaar** [comment]
Checked, this is done.
