### ISSUE TITLE
BUG: [React] [UX] Breadcrumb navigation

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#530]
**Describe the bug**

To avoid Mikey's memory problems, logging an issue for Breadcrumb navigation

https://coreui.io/react/docs/4.1/components/breadcrumb/

@homotechsual

**Comment by homotechsual** [comment]
So we can't do this right now. Not all breadcrumb parents have an actual page - despite having a route.

**Comment by homotechsual** [comment]
Actually can we leave this open - we can't do it **right now** but I think we can do something in this area :-)
