### ISSUE TITLE
BUG: [React] [UX] "Details" on MX card

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#546]
**Describe the bug**
Not obvious that this is a button and the "onHover" colour makes the text hidden on Impact theme

![image](https://user-images.githubusercontent.com/30923966/148697793-aeb8d523-78c3-4194-8f10-bc62cff3a364.png)
![image](https://user-images.githubusercontent.com/30923966/148697795-040b9819-c757-408a-9fa7-3b9872229cde.png)

@homotechsual

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Resolved
