### ISSUE TITLE
BUG: [React] [UX] Domain Analyser Spinner

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#547]
**Describe the bug**
Okay this is a REALLY nitpicky one...

Feel like the loading spinner is too close to the border, should be more in line with the title header?

![image](https://user-images.githubusercontent.com/30923966/148697815-0d841275-f5d3-45d5-b5a2-d2c0cf7d5aed.png)

@homotechsual

**Comment by homotechsual** [comment]
Those are on my radar - will be fixing all of them to be centered horizontally **and** vertically in their parent/container.

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Fixed with the new spinner :)
