### ISSUE TITLE
BUG: [React] [UX] Spinner on Wizard Submit

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#549]
**Describe the bug**
Spinner on clicking "Submit" on the wizard page, needs a space

![image](https://user-images.githubusercontent.com/30923966/148699152-c4736eef-229d-41f0-90bc-31f15f081049.png)

@homotechsual

**Comment by KelvinTegelaar** [comment]
removed spinner, replaced with inline spinner.
