### ISSUE TITLE
BUG: [React] [QA] Submit on Standards

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#550]
**Describe the bug**
When clicking submit on the standards wizard, the spinner appears but the result message shows as success - but the spinner keeps spinning

![image](https://user-images.githubusercontent.com/30923966/148699200-9c6896e2-4ee7-4d70-ae34-e11338ff097a.png)

**Comment by KelvinTegelaar** [comment]
removed spinner, replaced with inline spinner.
