### ISSUE TITLE
BUG: [React] [QA] List Applied Standards - Dropdown

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#551]
**Describe the bug**
Not sure if this is the overflow bug or whether the dropdown just doesn't have anything on to do, but the dropdown doesn't currently work

![image](https://user-images.githubusercontent.com/30923966/148699254-521b71c7-4e6f-40db-808a-8d8eb8add5d0.png)

Page:
CIPP
Tenant
Standards
List Applied Standards

**Comment by KelvinTegelaar** [comment]
resolved
