### ISSUE TITLE
BUG: [React] [UX] Tenant - Title Header Colour

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#552]
**Describe the bug**
Card title header is the wrong formatting

![image](https://user-images.githubusercontent.com/30923966/148699881-1e5cdcaf-1c25-41c5-bf74-95051d34c404.png)

@homotechsual

**Comment by AdamWillford** [comment]
Adding The "Edit Tenant" page to this too for the same thing - via the dropdown on tenants page

![image](https://user-images.githubusercontent.com/30923966/148699941-c7bda812-c488-41bd-b2b8-a11eeebd018b.png)

**Comment by AdamWillford** [comment]
Going to throw this in here too @homotechsual 

Everything within the below pages:

CIPP
Identity Management
Reports

All title header formatting

**Comment by homotechsual** [comment]
The title on the Tenants page is correct.
