### ISSUE TITLE
BUG: [React] [QA] Submit button on Edit Tenant Page

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#554]
**Describe the bug**
On the Edit Tenant page, the equivalent "Submit" button doesn't do anything / call the API etc

![image](https://user-images.githubusercontent.com/30923966/148701312-4f8491c3-690c-47a8-a836-c19751b94849.png)

Page: 
CIPP
Tenant
Administration
Tenants
Edit Tenant (from actions)

**Comment by KelvinTegelaar** [comment]
resolved
