### ISSUE TITLE
BUG: [React] [QA] Offboarding Wizard - Step 2

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#555]
**Describe the bug**
On Step 2 of the offboarding wizard, where you select the user, it allows you to open the dropdown during the loading of the state.

The problem is, if there is already some state loaded you then start to get users loaded from a separate tenant

Ideally it needs to be fixed so that the dropdown has isDisabled until state is successfully loaded (similar to the previous step, where the tenant list wont dropdown until loaded) 

CIPP
Identity
Administration
Offboarding Wizard

**Comment by KelvinTegelaar** [comment]
Fixed
