### ISSUE TITLE
BUG: [React] [QA] Offboarding Wizard results

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#556]
**Describe the bug**
Upon completion of whatever task you ask the offboarding wizard to do, the results are pretty crappy as far as formatting etc is concerned:

![image](https://user-images.githubusercontent.com/30923966/148701883-fe34ba4f-77c8-4d2a-96e6-66bb11656e2b.png)

Also important to note that the only task requested was to remove from all groups - so it looks like even if unticked, it still tries to do things around OOOM / OneDrive

**Comment by KelvinTegelaar** [comment]
Fixed with both API changes and display changes
