### ISSUE TITLE
FEATURE REQUEST: Add / Remove / Edit default calendar Permissions

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#573]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually launch powershell and connect to a tenant to edit calendar permissions for a users default calendar

**Describe the solution you'd like**
Similar to the mailbox permissions functionality, the ability to add / remove / edit and report on existing permissions to the users <username>:\calendar folder through the CIPP GUI

**Additional context**
At the moment we have this guide to follow to complete this task. https://intech.eu.itglue.com/551709/docs/930661578588366

**Comment by KelvinTegelaar** [comment]
Being added in latest version, planned.

**Comment by dan-baird** [comment]
Would be good to be able to make changes to multiple calendars at once.

For example a sales manager wants his EA to book appointments with his team and she needs full calendar access for 10 persons.
