### ISSUE TITLE
BUG: [React] [UX] - Individual Domain Flyout from Domain Analyser displaying white text in white box

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#580]
<img width="284" alt="2022-01-13 14_49_26-mRemoteNG - confCons xml - Azure Gavsto CIPP" src="https://user-images.githubusercontent.com/3102057/149352350-cb67fc68-8eb0-4bd2-ad11-446124cc1fc8.png">

**Comment by KelvinTegelaar** [comment]
fixed
