### ISSUE TITLE
BUG: [React] [QA] - Autopilot Device Wizard missing items on Step 2

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#582]
<img width="261" alt="2022-01-13 14_54_29-mRemoteNG - confCons xml - Azure Gavsto CIPP" src="https://user-images.githubusercontent.com/3102057/149353213-85e56588-81db-42df-8393-cd965933bc66.png">

**Comment by KelvinTegelaar** [comment]
page not yet done, see https://github.com/KelvinTegelaar/CIPP/issues/347
