### ISSUE TITLE
BUG: [React] [UX] - Three dotted offCanvas on each user shows the flyout but the links do not work in the menu

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#585]
This is on the /identity/administration/users

<img width="320" alt="2022-01-13 15_56_24-mRemoteNG - confCons xml - Azure Gavsto CIPP" src="https://user-images.githubusercontent.com/3102057/149363978-2c29eac9-68bf-4c27-86b1-bbccbf3a95b8.png">

**Comment by AdamWillford** [comment]
Confirmed~

Doesn't work on any CippActionOffcanvas that uses `link:` without a modal

**Comment by KelvinTegelaar** [comment]
fixed with @homotechsual's fix.
