### ISSUE TITLE
BUG: [React] [UX] - Individual Domain Flyout from Domain Analyser not displaying MX records in Mail Provider Info

### ISSUE THREAD

**Issue by LukeSteward** [KelvinTegelaar/CIPP#586]
On the Individual Domain Check the MX record detail flyout does not show the MX records in the table

![image](https://user-images.githubusercontent.com/29278153/149364828-606497c7-987d-40d7-a176-ef7bdd50d5fb.png)

**Comment by AdamWillford** [comment]
Can't reproduce this, using your domain:

![image](https://user-images.githubusercontent.com/30923966/149371610-1acc79f1-cd05-480d-bb6f-23d262185382.png)

You have the latest build etc?

**Comment by LukeSteward** [comment]
Running latest build and tested with different browsers as its a local issue I will close it.
