### ISSUE TITLE
Feature request: CRUD confirmation

### ISSUE THREAD

**Issue by Pukkahq** [KelvinTegelaar/CIPP#59]
**Is your feature request related to a problem? Please describe.**
User List butons

**Describe the solution you'd like**
Make spacing on buttons wider
Add confimation before running command

**Comment by KelvinTegelaar** [comment]
I am notoriously anti-confirmation.  I've always been a non-conformist now that I think of it. 

We'll actually leave it to the community: If you want ugly and mean confirmation pop-ups that delay your work and tell you you smell of potatoes add a smile to @dbeta's comment.

If you don't want confirmation and love puppies add one to mine.

**Comment by danialtneus** [comment]
How about a compromise, this may be more complicated than it seems, but user or system wide preference for toggling "basic confirmations".

**Comment by dbeta** [comment]
Perhaps a compromise. If a user or system wide option to toggle "basic confirmations". It's probably more work than it sounds like, but I think it would satisfy everybody, especially as long as we could set it as default for all users.
