### ISSUE TITLE
FEATURE REQUEST: Custom Validation Rules for Domains Analyser

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#592]
**Is your feature request related to a problem? Please describe.**
We are not able to get accurate reporting because we delegate SPF handling to Valimail (others may be using Agari, RedSift, etc).  So it shows up as a fail because the SPF is forwarded on to Valimail who handles it privately using an internal mechanism. 

**Describe the solution you'd like**
Add an option to the configuration area to change the validation rules for the Domain Analyser so we can customize with Valimail for example which uses "v=spf1 include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email ~all"
>> Even better would be a way for the SPF analyser to actually query the dynamic SPF record, the same way a mailserver does, so that it can verify that SPF record for O365 is enabled successfully within Valimail's system.

**Describe alternatives you've considered**
Manually checking each client to ensure that the SPF red status is real or just a result of SPF records delegation.

**Additional context**
![image](https://user-images.githubusercontent.com/17422069/149388035-5bf2eb36-8aad-44a0-b4aa-960f3d7c632d.png)

![image](https://user-images.githubusercontent.com/17422069/149388055-c703fdc1-50e2-4876-ba22-8b9cf61141b9.png)

**Comment by homotechsual** [comment]
I would like to work on this!

**Comment by KelvinTegelaar** [comment]
I think @johnduprey already had something for this, not sure.

**Comment by johnduprey** [comment]
We have support for mail providers with the ability to extend to others. Please see https://github.com/KelvinTegelaar/CIPP-API/tree/master/MailProviders for a current list. You can use the provided template to create your own JSON file. Feel free to PR any additions!

**Comment by johnduprey** [comment]
I'm looking at the Valimail docs right now and we don't technically have the ability to support macros yet, but it does look pretty interesting. 

Also the Domain Analyser needs to be updated to the new validation code. The mail provider functionality exists in the individual domain check currently.

**Comment by dan-baird** [comment]
OK, I got it working in the individual domain check. That worked well, thanks for the help, everyone!

As you say @johnduprey the Domain Analyser works different than the individual checker and it is still failing here.

**Comment by dan-baird** [comment]
just FYI here is what the added file looks like:

`{
    "Name": "M365 MX with Valimail Dynamic SPF",
    "MxMatch": "mail.protection.outlook.com",
    "SpfInclude": "include:%{i}._ip.%{h}._ehlo.%{d}._spf.vali.email",
    "Selectors": ["selector1","selector2"],
    "_MxComment": "https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider",
    "_SpfComment": "https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-with-domains/create-dns-records-at-any-dns-hosting-provider",
    "_DkimComment": "https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/use-dkim-to-validate-outbound-email?view=o365-worldwide"
}`

**Comment by dan-baird** [comment]
> Also the Domain Analyser needs to be updated to the new validation code. The mail provider functionality exists in the individual domain check currently.

so I just need to figure out how to do this I guess. Or is updating the Domain Analyser to make it easy to adjust validation already part of a new future release?

**Comment by johnduprey** [comment]
@dan-baird - I don't think we'd need a whole mail provider to parse this one, just some custom logic to macro expand the record. That said, it may be a bit to get that into the module since we'll have to simulate the macro expansion to confirm m365 is part of the includes. Just note, your SPF record is still going to fail validation because our baseline is `-all` not `~all`

**Comment by dan-baird** [comment]
@johnduprey - could there be a part 1 and a part 2 to this?

Part 1 the ability to at least customize the rules for the domain analyser similar to how the individual domain checker can be customized?

Part 2 a more advanced capability that can actually verify 365 is setup correctly on these dynamic records? 

I realize part 2 could be a bit of a project.

Yes, I noted that regarding the -all.  This is the way that Valimail requests it to be setup, so I would have to try it the other way to see if it breaks anything with their SPF delegation.

**Comment by johnduprey** [comment]
@dan-baird Domain Analyser has been updated to use the same logic as individual domain in dev. That should be in the next release.

As far as part 2 goes, I'll have to come up with a way to macro expand based on the mail provider. This would be similar to what I did for services that do SPF flattening.

**Comment by dan-baird** [comment]
Thanks! That is awesome they have the same system now.  That will make it more consistent and easy to customize. 

SPF flattening! Yes, that is the intent of the Valimail system, it's just using macros to do it. Not sure how other flatteners work but I like the way Valimail handles it which adds a bit of privacy, and that's part of the reason we use it.
- The other is that they have a really massive database of mail providers so no need for us to look up obscure help articles for every client's unique apps.

**Comment by paronubimaster** [comment]
@johnduprey - wasn't sure whether to open another FR, report a bug or just leave it here.

- Doing a little research and learning that Forensic Reporting is not delivered by most providers now (including Microsoft) thanks to PII and DOS concerns.

https://dmarcian.com/where-are-the-forensicfailure-reports/

https://www.valimail.com/blog/dmarc-failure-reports-what-are-they-good-for-absolutely-nothing/

These forensic values are not added by Valimail to their record for delegated DMARC management and are no longer considered Best Practice by many other DMARC experts. 

Perhaps it is best to remove this check from the Domain Analyser tool?

**Comment by johnduprey** [comment]
The warning about forensic reporting options being set is only displayed if you are supplying the `fo` parameter without also specifying a `ruf` parameter. Since this is optional, it would be implied that you want a specific type of forensic report (0,1,d,s) and would highlight a potential misconfiguration. Omitting `fo` from your record will remove this warning. 

![image](https://user-images.githubusercontent.com/15741649/149850959-7a0ca550-9530-4a14-afe5-a09f6d7d7d5e.png)

**Comment by paronubimaster** [comment]
> The warning about forensic reporting options being set is only displayed if you are supplying the `fo` parameter without also specifying a `ruf` parameter. Since this is optional, it would be implied that you want a specific type of forensic report (0,1,d,s) and would highlight a potential misconfiguration. Omitting `fo` from your record will remove this warning.
> 

@johnduprey that makes sense, I guess Valimail sets up fo with a value of zero, presumably to switch this off.
`fo=0`

**Comment by johnduprey** [comment]
That might be a misinterpretation on Valimail's part, `fo=0` is a directive to report on emails that fail both DKIM and SPF.

> 0: Generate a DMARC failure report if all underlying authentication mechanisms fail to produce an aligned "pass" result.

The RFC does specify that a mail server must ignore the `fo` parameter if no `ruf` address is specified, but this was designed to assist in proper configuration of records, hence the warning.

**Comment by dan-baird** [comment]
@johnduprey  could that fo=0 be included to add the failure to the aggregate report? Valimail does have an email specified for the aggregate report address.

**Comment by dan-baird** [comment]
Ok, scratch that. Doing a little research, it looks like fo must send to Ruf

...on the other hand the presence of a fo tag does not mean anything with a Ruf tag. In fact one article i read suggests that fo should be ignored if Ruf is not also present. https://seanthegeek.net/459/demystifying-dmarc/amp/

Could the rule look for Ruf instead of fo ? 

![Screenshot_20220117-202939_Firefox.png](https://user-images.githubusercontent.com/17422069/149855584-a7e03360-a2b2-43f1-aa99-e9dfe7718c9c.png)
