### ISSUE TITLE
BUG: [React] [UX] Table sorts A-Z then a-z

### ISSUE THREAD

**Issue by LukeSteward** [KelvinTegelaar/CIPP#602]
A really non important issue but tables separate upper and lowercase entries
![image](https://user-images.githubusercontent.com/29278153/149545974-d4ec1b0d-be6d-4f14-a6c2-679ff68920d6.png)

This screenshot is from Email & Exchange / Email Administration / List Mailboxes but this seems to be global.

**Comment by KelvinTegelaar** [comment]
Yeah, case sensitivity is a thing in react. I'll see if I can fix that.
