### ISSUE TITLE
FEATURE REQUEST: Change SharePoint Online Domain

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#604]
**Is your feature request related to a problem? Please describe.**
No problem with CIPP - but changing the SPO domain can be unfun using Microsoft's manual process

**Describe the solution you'd like**
Help us implement the new option to change SharePoint domain while also providing a report showing specific sites, users, groups that may be impacted by the change: https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name

**Describe alternatives you've considered**
DO it manually, follow the [instructions](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name), try and determine the scope of impact manually, try not to break everything. 

**Additional context**
one option 💡
![image](https://user-images.githubusercontent.com/17422069/149557087-d1757bb1-2b48-4d35-a94c-b7abfce2c0ef.png)

**Comment by KelvinTegelaar** [comment]
Can't access these right API's as a partner right now. It's a good request, and certainly on the map for the future, but have to close it for now.
