### ISSUE TITLE
FEATURE REQUEST: Integrate AzAutomapper into New User Workflow

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#607]
**Is your feature request related to a problem? Please describe.**
Providing a GUI for implementing AzAutomapper - as well as getting status for implementation per user/device for all tenants.

**Describe the solution you'd like**
Implement a way to automap the SharePoint libraries as per https://github.com/KelvinTegelaar/AzAutomapper - ideally as part of adding a new user or some other onboarding feature. Or perhaps within the Intune management area. 
> Perhaps this could take advantage of the Azure Function app that already exists for CIPP tenant access and then deploy the PS script to endpoints similar to how Choco apps are deployed.

**Describe alternatives you've considered**
Create the Azure Function for AzAutomapper and then deploy the PS to each device (or group) within each tenant manually. 

**Additional context**
Couple ideas on how this could look:

![image](https://user-images.githubusercontent.com/17422069/149575531-8a9a6495-d7d4-46c6-b6a9-42cc24fd54a7.png)

![image](https://user-images.githubusercontent.com/17422069/149575551-f9fe684f-dcab-4e99-9220-275274adbbee.png)

**Comment by homotechsual** [comment]
Interesting idea, the screenshots are amusing - interesting to see how far it's come :-D

**Comment by dan-baird** [comment]
> Interesting idea, the screenshots are amusing - interesting to see how far it's come :-D

I try to inspire 😉

**Comment by AdamWillford** [comment]
This is something we were talking about internally this week, so +1 to this fantastic idea.
