### ISSUE TITLE
Feature Request: Reporting on items available to be set with Standards

### ISSUE THREAD

**Issue by DaleMontgomery** [KelvinTegelaar/CIPP#62]
It would by very helpful to report the current status of each item that is settable via the Standards. This would allow a central place to determine if setting to standard would change the tenant's current configuration.

Ideally a single page with a matrix of the tenants and their related settings in regards to the items available to be set to a standard.

A button to refresh on demand would be great.

**Comment by KelvinTegelaar** [comment]
I think this should be a part of the bigger "M365 BPA" @gavsto

**Comment by gavsto** [comment]
I am currently working on this but it will take a few days as there's quite a bit to do to do it properly.
