### ISSUE TITLE
BUG: [React] [UX] - MFA Report not showing exclusions from CA policy

### ISSUE THREAD

**Issue by johnduprey** [KelvinTegelaar/CIPP#620]
**Describe the bug**
MFA report shows a green checkbox even if a user is excluded from CA policy

**To Reproduce**
1. Open MFA report for tenant with CA policy and exclusions
2. Find user that is in the exclusion group
2. Check API response for Excluded from <Policy Name> in Developer Tools

**Expected behavior**
A different icon should be displayed for exclusion and/or text should be returned with the status icon

**Screenshots**
![image](https://user-images.githubusercontent.com/15741649/149798745-4c0e67f8-5df7-4fdf-9471-6847e650fca2.png)
![image](https://user-images.githubusercontent.com/15741649/149798822-bddbd495-49a0-489e-9ec2-92d2b7fe2c47.png)

**Comment by homotechsual** [comment]
This also affects `Per user MFA Status`

**Comment by dan-baird** [comment]
> This also affects `Per user MFA Status`

Yes, we are seeing this impact Per User MFA Status as well.

**Comment by KelvinTegelaar** [comment]
Fixed in dev by removing boolean formatters for non bool values.

**Comment by dan-baird** [comment]
So this should be fixed in 2.1.0 ?
