### ISSUE TITLE
BUG: [CIPP-API] [Basic Auth Report] - Failure logins with basic auth protocol triggering in Basic Auth Report

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#621]
**Describe the bug**
Results are coming back as using basic auth even on failed login attempts.

**Comment by KelvinTegelaar** [comment]
If the log shows failures, the protocol is still enabled. Thus it's basic auth usage, even if its not active.

**Comment by KelvinTegelaar** [comment]
Cleared up explainer text in documentation.
