### ISSUE TITLE
FEATURE REQUEST: Better description for BPA items

### ISSUE THREAD

**Issue by servant42** [KelvinTegelaar/CIPP#622]
**Is your feature request related to a problem? Please describe.**
In the Best Practices Analyzer, verbiage is unclear that anything listed is a warning or non-ideal, but this is especially apparent with the Message Copy for Send As--there's no clarity on the fact that the user count or those listed if you click on it are the ones configured TO copy sent items to the shared/original mailbox, or if these are the ones who keep sent items in their original mailbox (the default, I believe).

**Describe the solution you'd like**
Improve clarity of what being listed on the BPA page means, whether it's "success" or "failure" and specifically, what does that mean for the Message Copy for Send As feature.

![Screenshot 2022-01-17 at 11 01 34 - Safari 2](https://user-images.githubusercontent.com/93614227/149804808-b857632e-28c7-4a00-9f75-d16b839d51fb.png)
![Screenshot 2022-01-17 at 11 18 12 - Safari](https://user-images.githubusercontent.com/93614227/149805153-92bd2660-1d93-4cec-befa-112338ace8de.png)

**Comment by dan-baird** [comment]
+1 for clarity here, i found this confusing as well.

**Comment by KelvinTegelaar** [comment]
pages will get documentation link so users can easily see this soon, closed as that's part of a bigger effort.
