### ISSUE TITLE
BUG: Convert Home to Masonry

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#623]
**Describe the bug**
Need to convert Home.js to use CippMasonry

**Comment by AdamWillford** [comment]
@KelvinTegelaar please can you add to 2.1 milestones

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@AdamWillford any update on this one buddy? If not I'm gonna grab it.
