### ISSUE TITLE
FEATURE REQUEST: Domain Analyser - SPF record based sending services

### ISSUE THREAD

**Issue by fnbronson** [KelvinTegelaar/CIPP#624]
**Is your feature request related to a problem? Please describe.**
Inbound and Outbound mail flow section logic. This would help our Tier1 engineers.   Details on the SPF Records information would  help them troubleshoot. 

Additionally, if the SPF record contains smtp25.com, and they are using Zix messages would be delivered Zix to Zix when sending to other domains using Zix

Inbound Mail Flow:  
- Mail Provider: Proofpoint  (based on MX Record) 

Outbound Mail Flow: 
- Known Providers:  
-AppRiver \ Zix
-Proofpoint
-Flywheel
-SendGrid

**Describe the solution you'd like**
A lot of my clients use Proofpoint for Incoming email, and send out via Zix\Appriver.  Along with a multitude of other services.

**Describe alternatives you've considered**
- SPF Results list: the names of the services that have the ability to send. 
- A checkbox that allows me to select an outbound service 
- Notes where I can type in "They send out via Zix"

**Comment by RedRhombus001** [comment]
Where the domain is managed would be good too, e.g "GoDaddy", "Name Cheap" etc.

**Comment by johnduprey** [comment]
> Where the domain is managed would be good too, e.g "GoDaddy", "Name Cheap" etc.

This is in dev currently. I added two new cards to the individual domain output, registrar and nameservers.
