### ISSUE TITLE
FEATURE REQUEST: Add custom links to Tenant List

### ISSUE THREAD

**Issue by fnbronson** [KelvinTegelaar/CIPP#625]
**Is your feature request related to a problem? Please describe.**
Ability to add a custom Portal link to an external service such as a SPAM Filter, or the IT Glue page associated with the client. 

**Describe the solution you'd like**
- Manual setup, or even auto configuration based on MX record. . This might be tricky, and require manual intervention for different Proofpoint tenants. 

**Describe alternatives you've considered**
- Button or section to add a custom link

**Comment by gavsto** [comment]
It's not really clear what you are asking for here. Could you clarify or mockup an example to help visualise?

**Comment by thelawrencearm** [comment]
![image](https://user-images.githubusercontent.com/20508294/149816109-463799f7-cedc-4d28-8099-71f1fd81f5e4.png)
