### ISSUE TITLE
BUG: MFA Report - Per user MFA Status is Incorrect

### ISSUE THREAD

**Issue by jsmithschilling** [KelvinTegelaar/CIPP#628]
**Describe the bug**
MFA Report - Per user MFA Status is incorrect. It is pulling that all users are MFA enabled (Green Check) however they are actually not enabled for MFA.
This is happening on all tenants
CIPP - 2.0.0

**To Reproduce**
Identity Management > MFA Report > Tenant
Green Checks all across MFA Status

**Expected behavior**
To show accurate MFA enabled status

**Screenshots**
![image](https://user-images.githubusercontent.com/96208986/149815252-332c83e9-ef7c-4a46-b41d-4cde601856b4.png)
![image](https://user-images.githubusercontent.com/96208986/149815345-0d018563-ac65-4936-a5c9-957d04aab0d8.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Comment by KelvinTegelaar** [comment]
Fixed in dev
