### ISSUE TITLE
BUG: [React][UX] MFA Pushes no longer work.

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#629]
**Describe the bug**
When you try to send an MFA push it just displays a message saying "Pushy"

**To Reproduce**
View a user, try to send an MFA push

**Expected behavior**
Send an MFA push and display the response

**Screenshots**
![image](https://user-images.githubusercontent.com/79275328/149815624-c9b68430-8469-4dc5-adac-1b3043c4c125.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Edge
- Version: 2.0

**Additional context**
Going to blame Adam

**Comment by KelvinTegelaar** [comment]
pushy

**Comment by KelvinTegelaar** [comment]
Farewell Pushy, you shall be missed.

**Comment by homotechsual** [comment]
#bringbackpushy
