### ISSUE TITLE
BUG: List user signin logs pdf report blank

### ISSUE THREAD

**Issue by k-grube** [KelvinTegelaar/CIPP#632]
**Describe the bug**
User Sign In Logs section on view user, pdf report is blank

**To Reproduce**

1. Go to a user
2. Click PDF

**Expected behavior**
PDF contains user sign in logs

**Screenshots**
![image](https://user-images.githubusercontent.com/20404989/149818470-e651c0b3-3e0d-4782-aa2a-345031fd629b.png)

**Desktop (please complete the following information):**
Chrome, Windows 10

**Comment by KelvinTegelaar** [comment]
fixed by adding export selectors.
