### ISSUE TITLE
BUG: List User Sign In Logs CSV report contains [object Object] for many columns 

### ISSUE THREAD

**Issue by k-grube** [KelvinTegelaar/CIPP#633]
**Describe the bug**
CSV report for user sign in logs does not show columns correctly

**To Reproduce**

1. Go to view user
2. Click CSV button

**Expected behavior**
Correct data returned

**Screenshots**
![image](https://user-images.githubusercontent.com/20404989/149818748-f217c14d-a3a5-4be5-b486-1d1a1680abec.png)

**Desktop (please complete the following information):**
Chrome, Windows 10

**Comment by KelvinTegelaar** [comment]
Fixed in dev, export selector was wrong.
