### ISSUE TITLE
FEATURE REQUEST: Optional CIPP access to partner tenant

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#634]
**Is your feature request related to a problem? Please describe.**
No access to partner tenant, seems to be intentional, not a problem.

**Describe the solution you'd like**
Simple toggle somewhere to give ourselves access to our internal/partner/MSP tenant within CIPP (should be OPTIONAL since not all partners will want CIPP to access their tenant)

**Describe alternatives you've considered**
We continue to manage our tenant using Microsoft 365 admin consoles instead of within CIPP

**Additional context**
Would be great to help us standardize our processes and security policies internally the same as external.

**Comment by KelvinTegelaar** [comment]
already discussed in the past, we might do this in a later version. here are many dangers involved in this. Fr now this FR is closed.
