### ISSUE TITLE
BUG: [React][UI] Redirect after login always goes to home page instead of passed page

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#635]
**Describe the bug**
When the SWA wants to reauthenticate (which is most times when opening in a new tab) it will always redirect to the home page instead of the actual URL provided.

**To Reproduce**
Copy a page URL such as the users page. Start a new session which isn't logged into CIPP. Visit the page. You will be redirected to the home page instead of the target page.

**Expected behavior**
You would be redirected to the requested page rather than home page.

**Comment by homotechsual** [comment]
We'd need to pass a fully qualified domain name to the login redirect: https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-authorization?tabs=invitations#post-login-redirect

**Comment by KelvinTegelaar** [comment]
did we get a solution for this? something about using the refferer?

**Comment by homotechsual** [comment]
I thought I'd committed it.
One sec!

**Comment by homotechsual** [comment]
#665

**Comment by KelvinTegelaar** [comment]
fixed in dev
