### ISSUE TITLE
FEATURE REQUEST: Alert on Domain Outage that feeds into CIPP notifications

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#636]
**Is your feature request related to a problem? Please describe.**
We had a client impacted by the massive enom outage and we did not know about it until they called.

**Describe the solution you'd like**
The domain analyser grabs the NameServers for each domain (during the initial analysis run) and then stores those NS records somewhere and runs an hourly (or 8x day) check to make sure those NS are online.

**Describe alternatives you've considered**
Using a common status monitoring tool, but the downside is manually figuring out the NameServers, registrar services, and then trying to maintain that list of domains to monitor on that tool. Manual process vs. a synced, automated one.

**Additional context**
Really low priority, more like a nice-to-have wishlist item.

**Comment by KelvinTegelaar** [comment]
CIPP is not a monitoring tool, this isn't in scope.
