### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#637]
**Describe the bug**
>> MatDew — Today at 1:36 PM
few clients that show up as no data in BPA and tried to run that check and got the error.
I don't know why some of these are not pulling data, they were before and we haven't done anything to their CA policies
> DanBaird — Today at 2:41 PM
I was getting this too with a couple client tenants not showing in BPA after the 2.0 update, and then I cleared cache, ran BPA again, waiting like an hour, came back after lunch and it now loads nothing. So that's interesting.  Just a blank page.
> stopped and then started my function app, that let me run BPA again but still only getting a partial tenant list.

**To Reproduce**

1. Click on Standards, drop down 
2. Choose Best Practice Analyser
3. Click button, Force Refresh
3. Wait
4. Wait
5. Refresh page and behold, a partial, incomplete list of tenants will load 😬

**Expected behavior**
Same thing that happened in v1.5 the entire list of tenants will load.

**Screenshots**
![image](https://user-images.githubusercontent.com/17422069/149832600-bbe2cf10-e5b3-46b5-9e83-41164f2106ea.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise (latest version) 
- Browser: Microsoft Edge Version 97.0.1072.55 
- Version: CIPP 2.0, Edge 97, Win10-19043.1348

**Smartphone (please complete the following information):**

Not applicable

**Additional context**
Not the only user seeing this as per Discord comment from MatDew

**Comment by KelvinTegelaar** [comment]
Resolved in latest API, Please update to 1.5.2.

@dan-baird Also, please give bugs and FRs subjects, it's a bit easier for us to sort.

**Comment by dan-baird** [comment]
> Resolved in latest API, Please update to 1.5.2.
> 
> @dan-baird Also, please give bugs and FRs subjects, it's a bit easier for us to sort.

Thanks - I will upgrade my api to 1.5.2

Sorry! this is like sending an email without a subject line, really annoying of me.  For some reason I missed that.  🤡

**Comment by dan-baird** [comment]
Just a note that this fixed it, all tenants loading. Although there is one that is now saying "no data" across all columns.
