### ISSUE TITLE
BUG: Applied Standards page displays default domain instead of tenant name

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#643]
**Describe the bug**
The "Applied Standards" page at `/tenant/standards/list-applied-standards` displays the default domain in the tenant name column

**To Reproduce**

1. Go to '/tenant/standards/list-applied-standards'
2. Look at the Tenant Name column

**Expected behavior**
The column above should show the tenant's name - not the domain.

**Additional context**
Using latest version(s)

**Comment by KelvinTegelaar** [comment]
This is expected behavior, but will clarify the text.

**Comment by KelvinTegelaar** [comment]
Changed in dev

**Comment by wilhil** [comment]
Is there a reason why the default domain is displayed instead of the tenant name?

The standards are applied to a tenant... and some tenants have multiple domains or similar so I can just see this not being as clear as it can or should be.
