### ISSUE TITLE
FEATURE REQUEST: Enable user

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#644]
**Is your feature request related to a problem? Please describe.**
Ability to enable a disabled user

**Describe the solution you'd like**
To enable a user

**Describe alternatives you've considered**
Going to the 365 portal... but, who wants to do that?

**Comment by KelvinTegelaar** [comment]
So I have no clue why we didn't have this, planned for 2.1(not 2.0.1)

**Comment by KelvinTegelaar** [comment]
added in dev
