### ISSUE TITLE
BUG: <BR> doesn't <BR> in "add user"

### ISSUE THREAD

**Issue by ITSRobCan** [KelvinTegelaar/CIPP#646]
**Describe the bug**
When you add a user using the wizard, the output is not formatted and it displays the (LEFT ARROW br RIGHT ARROW) tags

**To Reproduce**

1. Go to 'Home'
2. Click on 'Add a User'
3. Scroll down to 'Tenant of Choice'
4. Add a user as normal
5. Output is broken formatting

**Expected behavior**
Same thing except prettier

**Screenshots**
![image](https://user-images.githubusercontent.com/97260262/149994669-15d823e9-2488-4e45-b34f-4d3fa23f9753.png)

**Desktop (please complete the following information):**

- OS: W10
- Browser Firefox
- Version 95.0.2

**Additional context**
Posted in Discord as well, Adam said he'd fix it for a BRZ.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
