### ISSUE TITLE
Documentation: Update Install documentation with Admin Consent instructions

### ISSUE THREAD

**Issue by likwid9** [KelvinTegelaar/CIPP#647]
**Describe the bug**
Documentation needs updating for instances where Azure is configured to require admin consent for user apps

**To Reproduce**

1. Azure Tenant requires admin approval for user apps
2. Add user to the Azure static app as a new CIPP user
3. User clicks the invite link and is told the app needs admin approval
4. Admin has to go into Azure Enterprise Applications under Azure Static Websites and Grant Admin Consent for all.
5. This will allow the users the ability to grant their own access now.

**Comment by KelvinTegelaar** [comment]
will add to FAQ, issue not required anymore. :)
