### ISSUE TITLE
FEATURE REQUEST: Forward Email as part of offboarding wizard

### ISSUE THREAD

**Issue by drewhack** [KelvinTegelaar/CIPP#666]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem

**Describe the solution you'd like**
During the offboarding Wizard the ability for forward all of a users emails to another employee with or without retaining in current inbox.

**Describe alternatives you've considered**
I can still go in and manually forward as necessary

**Additional context**
More often than not when offboarding an employee mail gets forwarded but this just automates like 7/8 of the steps so thanks

**Comment by dan-baird** [comment]
This would be good. Should be possible, it's one of the things the Microsoft admin centre user deletion wizard has.

**Comment by KelvinTegelaar** [comment]
added in dev
