### ISSUE TITLE
FEATURE REQUEST:  Add the Native External Sender Callouts to Standards

### ISSUE THREAD

**Issue by likwid9** [KelvinTegelaar/CIPP#668]
**Describe the solution you'd like**
Microsoft allows for you to natively tag senders as External which shows up in Outlook for mobile, web, and desktop.  Would be nice to have this as a standard to push to all tenants.

**Additional context**
[Add any other context or screenshots about the feature request here.](https://techcommunity.microsoft.com/t5/exchange-team-blog/native-external-sender-callouts-on-email-in-outlook/ba-p/2250098)

**Comment by KelvinTegelaar** [comment]
Already exists

**Comment by likwid9** [comment]
Indeed.  Guess I need to get better at reading, thanks!
