### ISSUE TITLE
FEATURE REQUEST: Custom PowerShell against tenants.

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#669]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Custom PowerShell to run against multiple tenants. Maybe paste into a text box some code and then select the tenants to run it against. Such as a "New-TransportRule" that you want to add to several tenants.

**Describe alternatives you've considered**
Manually scripted using secure app.

**Comment by KelvinTegelaar** [comment]
Discussed previously; risk vs reward for this is too great. We're not going to do this.

**Comment by procradminator** [comment]
OK – suspected so but searched through closed requests and couldn’t see anything.

Thanks.
