### ISSUE TITLE
FEATURE REQUEST: Add red font or a column to MFA report to indicate Users with enabled accounts no MFA types

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#670]
**Is your feature request related to a problem? Please describe.**
Love the MFA report but can be a bit slow to review each users and check whether they have Enabled account and then check the various MFA types.

**Describe the solution you'd like**
Some sort of logic that looks for all users that meet the following conditions: "Account Enabled = Yes, AND Conditional MFA = No, AND Per user MFA = No, AND Security Default MFA = No" .... then it applies either a formatting, like a red font, or yellow highlight or something to the specific rows, or uses an additional column that we can sort on that has the overall RED FLAG status.

**Describe alternatives you've considered**
Painstaking sorting of the list by enabled account or by per user MFA and then looking for exceptions that do not have any sort of MFA and are still enabled.

**Additional context**
![image](https://user-images.githubusercontent.com/17422069/151032877-744a745f-1850-409c-8885-4db5a59c65c8.png)

**Comment by homotechsual** [comment]
So if all the checks are bad we flag the entire row?

**Comment by KelvinTegelaar** [comment]
reasonable ask, planned for 2.1

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed by #694
