### ISSUE TITLE
BUG: Offboarding users password complexity

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#671]
**Describe the bug**
When performing a password reset during off-boarding a user the password occasionally does not meet the complexity requirements so fails

**To Reproduce**
Off-board a user and reset the password during the process

**Comment by KelvinTegelaar** [comment]
Confirmed bug, will rework password generator.

**Comment by KelvinTegelaar** [comment]
Password generator has been edited to make sure this does not happen anymore in dev.
