### ISSUE TITLE
Feature Request: Add "All Tenants" option.

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#672]

**Comment by KelvinTegelaar** [comment]
To be used in places where it makes sense, such as deployment wizards, standards, etc. 

Idea is to have it as optional component in <tenantselector> and datatables with tenants. This also allows deployment to future tenants.

**Comment by xhoy** [comment]
Especially for "reports' it would be awesome if they where multi-tenant. "show all non-compliant devices" for example.

**Comment by just-jenb-fairoaksit** [comment]
Agreed also to be able to see all anti-spam/malware/phishing/etc. rules in an all-tenant view

**Comment by KelvinTegelaar** [comment]
As these are core roadmap features, we don't process input on these features as that would make developing them overly complex, and impossible to implement. The core team decides on how and where this gets implemented.

**Comment by KelvinTegelaar** [comment]
Add AllTenants option to most locations, and gives the ability to add this to any API that requires it.
