### ISSUE TITLE
FEATURE REQUEST: Password Complexity on Users

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#676]
**Is your feature request related to a problem? Please describe.**

On the pages like Add User / Edit User, there is currently a box (on Add) that allows you to enter a password for the user.

We'd like this to have validation on it - at a minimum for a decent-password, but ideally pulling the configuration from the tenant password policy and ensuring that the added password matches.

There is a slight bug on Edit User that currently it doesn't let you enter a password at all (despite the box looking like it should)

**Comment by gavsto** [comment]
I think having the capability to run this through a server which checks a password is unique or has ever been involved in a breach would be a good optional thing too.

**Comment by KelvinTegelaar** [comment]
Added password complexity validation:
The password is at least 8 characters long (?=.{8,}).

The password has at least one uppercase letter (?=.*[A-Z]).

The password has at least one lowercase letter (?=.*[a-z]).

The password has at least one digit (?=.*[0-9]).

The password has at least one special character ([^A-Za-z0-9]).
