### ISSUE TITLE
BUG: Editing user causes UI to render outside of viewport

### ISSUE THREAD

**Issue by MissFox0810** [KelvinTegelaar/CIPP#678]
**Describe the bug**

When editing an user, if you click "Change licenses" it causes the div to render off the page.
meaning the edit button gets pushed off page with no scroll bar. So you cant save your changes.

**To Reproduce**

1. Edit a user.
2. Click "Change licenses" on a customer with a few licences.
3. watch button disappear before your very eyes.

**Expected behavior**

A scroll bar to appear when div extends past current viewport.

**Screenshots**
Before:
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/4310446/151135564-e9ac8f3f-f0e9-4d17-a566-d32b8ebd2fc3.png">

After:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/4310446/151135728-d4abd694-2d7d-4149-aa2a-cb5449f19e7c.png">

**Desktop (please complete the following information):**

- OS: Win11
- Browser: Chrome
- Version: 97.0.4692.99

**Comment by KelvinTegelaar** [comment]
oh so pretty. @homotechsual Can you check this one out? :)

**Comment by homotechsual** [comment]
Can anyone reproduce this? I can't I get a scroll bar.

**Comment by homotechsual** [comment]
So I've updated this page to the new UI elements `<CippPage>` etc and moved the raw information to an `Offcanvas`:

![image](https://user-images.githubusercontent.com/2288257/151173752-a0214ee9-10ca-4ac6-972d-045064611e15.png)
![image](https://user-images.githubusercontent.com/2288257/151173901-03488d61-697c-49a8-b38c-5bcd4470d432.png)

**Comment by KelvinTegelaar** [comment]
Seems fixed in Dev :)
