### ISSUE TITLE
Feature request: Change max email attachment size 'standard'

### ISSUE THREAD

**Issue by zenmechanic** [KelvinTegelaar/CIPP#68]
Under /?page=Addstandard .. Have the ability to set a 'standard'  for max email attachment size for the tenant.

Get-MailboxPlan | Set-MailboxPlan -MaxSendSize 150MB -MaxReceiveSize 150MB

**Comment by KelvinTegelaar** [comment]
This it a too "one-off" and not recommended by current standards, we'll have to nix this request for now. We'll consider adding it again in a later version.

**Comment by jcutrer84** [comment]
Might revisit this one. Looks like the size calculation might be off at 150MB

<img width="1397" height="584" alt="Image" src="https://github.com/user-attachments/assets/116b089b-db0e-4bfb-b137-b63b9d15c6c7" />
