### ISSUE TITLE
BUG: Applied Standards PDF multi-tenant Report incorrectly grabs the selected tenant name

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#681]
**Describe the bug**
Like most reports the PDF generated by the "List Applied Standards" page uses the tenant that is currently selected in the app to name itself, however this is a multi-tenant report so it shouldn't use a specific tenant name for the report name. 

**To Reproduce**
Go to any other part of the app that requires you to select a tenant and select a tenant, the go to Tenant Administration > Standards > List Applied Standards and click either the PDF or CSV button and you will get the same result. 

**Expected behavior**
it should always be named "multi-tenant" report or "undefined" (as it does if you are starting in a new session)

**Screenshots**
![image](https://user-images.githubusercontent.com/17422069/151398011-1e7ba36b-9522-46fc-baf8-034d402715bf.png)

**Desktop (please complete the following information):**

- OS: Win10
- Browser Microsoft Edge
- Version 97

**Comment by KelvinTegelaar** [comment]
fixed in dev.
