### ISSUE TITLE
BUG: "Success" casting error on applying P2 license to user

### ISSUE THREAD

**Issue by SuburbanTotoro** [KelvinTegelaar/CIPP#682]
**Describe the bug**
When attempting to apply a P2 license to a user, the error received is:
Success. The user has been edited. <br>Succesfully edit user. The password is . We've failed to assign the license. Cannot convert a primitive value to the expected type 'Edm.Guid'. See the inner exception for more details. 

**To Reproduce**

1. Go to "Identity Management"
2. Click on 'Users'
3. Select "Edit user" for a user in a tenant with a P2 license
4. Toggle "change license" in "edit user" pane
5. Apply P2 license

**Expected behavior**
The expectation for this error

**Screenshots**
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/96153222/151444503-db0cbdfd-1db1-4cf5-8b36-e4ea120b6346.png)

**Desktop:**
- OS: Win 11 w/ December 2021 rollup applied
- Browser : Edge
- Version: 97.0.1072.69 or close

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
