### ISSUE TITLE
FEATURE REQUEST: Make all List reports sortable on screen

### ISSUE THREAD

**Issue by JohnK-OCS** [KelvinTegelaar/CIPP#683]
**Is your feature request related to a problem? Please describe.**
Not a problem but a quality of (my) life product enhancement request.

**Describe the solution you'd like**
Make other list reports (Teams, Sharepoint, OneDrive etc.) sortable on screen by clicking on the column header, the same way the Security & Compliance / List Alerts report works.

**Describe alternatives you've considered**
Use the CSV file export to edit in Excel to perform the same task but with many more steps.

**Additional context**
Is none.

**Comment by KelvinTegelaar** [comment]
@homotechsual didn't we fix this in dev already? :)

**Comment by JohnK-OCS** [comment]
> @homotechsual didn't we fix this in dev already? :)

I looked through closed issues for this to make sure I didn't duplicate something that had been worked on.... didn't see it

**Comment by homotechsual** [comment]
Nope, not all pages. But it's an easy enough fix.

**Comment by homotechsual** [comment]
Fixed by #685

**Comment by homotechsual** [comment]
@KelvinTegelaar fixed for 2.1
