### ISSUE TITLE
FEATURE REQUEST: Ability to manage own (non-csp) tenant

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#689]
**Is your feature request related to a problem? Please describe.**
We manage our own infra/tenant just like any other customer and we'd like to see & manage our own tenant from CIPP. 

**Describe the solution you'd like**
Other AzureAD related apps have 2 type of integrations: CSP and non-CSP. Here's an example from CyberCNS https://cybercns.atlassian.net/wiki/spaces/Verison2/pages/1655504913/Azure+AD+and+Office+365+Integration

**Describe alternatives you've considered**

**Additional context**

**Comment by KelvinTegelaar** [comment]
Due to security risk, we're not doing this.
