### ISSUE TITLE
BUG: Edit Password on User

### ISSUE THREAD

**Issue by AdamWillford** [KelvinTegelaar/CIPP#700]
**Describe the bug**
Potential confirmation required, as seems odd that this hasn't been seen elsewhere already

When editing a user, if all you do is tick the box for "Reset Password" or "Reset Password" + "Change at next logon" - you get a "Success" alert message back, but not the actual password.

Likewise, despite it saying success, the password doesn't seem to have changed.

Payload of the EditUser request via console doesn't seem to have any reference to it - not had chance to check the code itself yet 

**To Reproduce**
Edit User via Identity Management 

**Expected behavior**
Password is given / changed

**Comment by KelvinTegelaar** [comment]
Confirmed, something weird going on there. :)

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
