### ISSUE TITLE
Standards - does it deploy something by default

### ISSUE THREAD

**Issue by Shadoxity** [KelvinTegelaar/CIPP#703]
Hey there,
Firstly, awesome work, what a great tool!

I am just not clear,  as the doco seems to indicate that standards get applied every 3 hours.

However there is no section I can find that seems to let you configure your global standards.

I am assuming that they only reapply every 3 hours after doing an initial standard deployment to some clients, and then for those clients it will keep it applied.

Is that correct? Would be good to update the doco on that :D

Just nervous that some standards are going to apply to all our tenants that I do not want and dont seem to have an option to select :o

**Comment by KelvinTegelaar** [comment]
Please read the documentation. Standards are applied via the "Apply Standard" menu.
