### ISSUE TITLE
BUG: Domain Analyzer security score is not the Microsoft secure score

### ISSUE THREAD

**Issue by DChorn-ANS** [KelvinTegelaar/CIPP#706]
**Describe the bug**
The secure score included on the domain analyzer page is supposed to be the tenants Microsoft Secure Score per documentation however it is actually a rating based on the SPF/DKIM/DMARC tests in the domain analyzer.

**To Reproduce**
Compare tenant secure score against the score visible in the domain analyzer

**Expected behavior**
Display the correct value or update documentation/naming to reflect correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/94991453/152424663-f6320520-8341-4400-8c40-42cc3240ad69.png)
![image](https://user-images.githubusercontent.com/94991453/152424835-da56fe4e-4175-46e0-a95b-550a4448cee7.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 97

**Comment by KelvinTegelaar** [comment]
The Secure Score is located at the Best Practice Analyser, last column. Our Domain Security score is not related to Secure Score and is domain based.

**Comment by homotechsual** [comment]
Except our documentation says it's the Microsoft Secure Score.
![image](https://user-images.githubusercontent.com/2288257/152425714-0d0d623f-73f3-465f-ae50-f014d524e49d.png)

**Comment by homotechsual** [comment]
Which I will fix.

**Comment by DChorn-ANS** [comment]
Thanks Kelvin for clarifying but the documentation says otherwise which needs an adjustment


***@***.***


Devon ChorneyFollow Us
Security Analyst
T: 855.515.5777 ext. 7206
E: ***@***.***
W: www.accuratenetworks.ca
201, 17507 107 Ave NW
Edmonton, AB
T5S 1E5

**Comment by DChorn-ANS** [comment]
Thanks for the clarification. It does appear to just be a documentation issue.  Thanks everyone

**Comment by homotechsual** [comment]
Documentation fix will be in "new docs" thanks @DChorn-ANS for the report :-)
