### ISSUE TITLE
Feature Request: Tenant editor

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#71]
**Is your feature request related to a problem? Please describe.**
When Microsoft imports a new tenant contract it only updates that information a single time; at creation. This means if the tenant had the wrong name, or changed names/domains they will forever be listed like that in your contracts list.

We can use the following to edit tenants:
```
•    Log into Azure Graph API through the URL https://graphexplorer.azurewebsites.net  using your Global Admin & Admin agent credentials.  
•    Then execute the GET call to get the list of the Partner Contacts using the following REST Call  
o    GET https://graph.windows.net/myorganization/contracts?     [api-version=1.6]
•    From here copy the Object ID of the customer.
•    With the help of following PATCH call, please update the display domain of the Customer: 
o    PATCH https://graph.windows.net/myorganization/contracts/<object-id-of-contract>?    [api-version=1.6] 
{"defaultDomainName":"NEWDEFAULTDOMAINNAME"}
```

Maybe we can include a edit button on the tenants list, to allow change of the returned properties:
```
    "contractType": "3",
    "customerContextId": "8dde2954-2562-48c7-a555-cccc",
    "defaultDomainName": "cccc.onmicrosoft.com",
    "displayName": "xxxx BV"

```

We could also add the delete button, but this is quite destructive and I'm not 100% confident it's needed.

**Comment by wilhil** [comment]
Well... I just needed it... Thanks so much for the link, I'll try it now... 

Can it be reopened just lowest priority as others may need it in the future.

**Comment by AdamImpelling** [comment]
Happy to take this on if you want to assign to me :)

**Comment by AdamWillford** [comment]
Happy to take this on if you want to assign to me :)

**Comment by KelvinTegelaar** [comment]
Reopened, assigned to @AdamWillford

**Comment by AdamWillford** [comment]
@wilhil This has been merged into dev now, if you want to test and make sure it achieves what you wanted please

**Comment by KelvinTegelaar** [comment]
tested and functional.

**Comment by wilhil** [comment]
Adam or the commit he did?

**Comment by MrNickIE** [comment]
Not functioning, and I would really like this feature back! :)
