### ISSUE TITLE
FEATURE REQUEST: Warn / Notify if a tenant has AD Connect in place during "Add User" workflow.

### ISSUE THREAD

**Issue by NRClay** [KelvinTegelaar/CIPP#714]
**Is your feature request related to a problem? Please describe.**
I think it might be an issue if we start allowing people to create accounts in an AD Sync'd tenant. I don't see any notification and it might cause problems when managing in more advanced scenarios such as an Exchange Hybrid. 

**Describe the solution you'd like**
Notification Banner on the "Add User" Page that indicates that this workflow may not be appropriate. 

**Describe alternatives you've considered**
Blocking or allowing the CIPP admin to "block" creation of "cloud" users? 
Allowing users to create this, but then we would have to soft-link. This isn't an absolute problem, but I don't believe it is the most graceful solution.
Possibly a future integration that would allow us to trigger an AD user creation on premise? (Sounds more complicated than it is worth... possibly causing more problems than it is worth)

**Additional context**

**Comment by homotechsual** [comment]
This is a good request - I like it!

**Comment by gavsto** [comment]
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/3102057/152653394-18895c29-b70c-4a3a-91eb-7861cb6b157c.png">

Added in Dev. Should be in next release. Will appear when directory sync is enabled AND configured.
