### ISSUE TITLE
FEATURE REQUEST: Shorten the License column's default "MAX" length

### ISSUE THREAD

**Issue by NRClay** [KelvinTegelaar/CIPP#715]
**Is your feature request related to a problem? Please describe.**

When viewing "Users" in the portal, certain tenants have an excessively long "License" column that pushes the "Actions" off the page. The scroll bar (Left -> Right) does exist, but is not shown unless you scroll your window's scroll bar to the bottom of the app. This may "hide" functionality to new users who are not aware. ( It happened to me, I thought it was a "Read Only" view )

**Describe the solution you'd like**
Shorten the default "Max" length for the column. Possibly 1/2 of the existing? Maybe dynamically calculate this column's length maximum based on the web browser's window size? 

**Describe alternatives you've considered**
An Introduction walk-through video for each basic tasks?
Getting a 32+" ultra wide screen monitor.

**Additional context**

I'm on a laptop with a FHD (1080P) screen, Windows 10, Rendered in Firefox (latest stable release).
The offending tenant use this for a list of licenses: 

Power BI (free), VISIO ONLINE PLAN 2, MICROSOFT 365 BUSINESS PREMIUM, Microsoft Power Apps Plan 2 Trial, MICROSOFT FLOW FREE, Power BI Pro

**Comment by homotechsual** [comment]
This won't fix in the current implementation in a viable way. We'll fix this for 2.3 or 2.4 with a planned move to DataGrid

**Comment by NRClay** [comment]
Just an FYI as a work around, do 90% zoom seems to strike a good balance of "still readable" and "can see everything". 

Firefox shortcut: "Ctrl" + "-"

**Comment by KelvinTegelaar** [comment]
closing for now, will be picked up at a later date. :)
