### ISSUE TITLE
FEATURE REQUEST: Invite new CIPP User to CIPP portal 

### ISSUE THREAD

**Issue by NRClay** [KelvinTegelaar/CIPP#716]
**Is your feature request related to a problem? Please describe.**
I think adding the ability to invite users to the CIPP portal would be beneficial from an administration view point. Specifically for instances that are hosted.

**Describe the solution you'd like**
Creation of an administration section in the CIPP portal that shows existing users, allows users to be invited, and management of "RBAC" for CIPP. 

**Describe alternatives you've considered**
Self hosting application. May not be a required feature for self hosted.

**Additional context**
I think this might be considered default by most "web apps" so I figured I would post the request. I'm sure it is a duplicate on a roadmap somewhere but I didn't see it in the "Issues" section of Github.

**Comment by KelvinTegelaar** [comment]
Hosted users can get access to azure backend. Not going to fix
