### ISSUE TITLE
FEATURE REQUEST: Audit log for CIPP Portal

### ISSUE THREAD

**Issue by NRClay** [KelvinTegelaar/CIPP#717]
**Is your feature request related to a problem? Please describe.**
Currently there is no log visible in the CIPP portal that shows what is/has/will happen or success status. I think it would be beneficial to be able to soft and view a log in CIPP to find out "what happened" and "who did it".

**Describe the solution you'd like**

An Audit log for CIPP Portal that shows Actions, Originator (User / Schedule), Status (Pending, In Progress, Completed), Tenant, Tenant Object.

**Describe alternatives you've considered**
This should be visible on the individual tenants themselves, but would be a pain to aggregate. 

**Additional context**
There are some security Pros/Cons for this I'm sure. I think the Pros would definitely outweigh the Cons.

**Comment by KelvinTegelaar** [comment]
Top right, under avatar, logbook. :)
