### ISSUE TITLE
FEATURE REQUEST: Exchange Mailbox Statistics - Colorize Mailboxes over 75/90% quota

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#722]
**Is your feature request related to a problem? Please describe.**
When reading & sorting Mailbox statistics reports to identify potential issues, I have to read each line or export to excel and add some formulas to filter mailboxes approaching quota limits

**Describe the solution you'd like**
Colorize mailboxes over 75% (warning / yellow) / 90% (danger / red) to quickly identify potential victims 

**Describe alternatives you've considered**
Email or PSA Alerts for each mailbox approaching quota

**Additional context**
![image](https://user-images.githubusercontent.com/7716697/152644127-47fcc24c-f41c-4eb3-ba86-90a33b64990e.png)

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by homotechsual** [comment]
The pr implements this as `warning` = 80 - 90%, `danger` = 90-100%
