### ISSUE TITLE
BUG: Basic Auth Report throws Error 500 if All Tenants previously selected

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#723]
**Describe the bug**
Error 500 thrown by Basic Auth Report page if previously All Tenants was selected as current tenant

**To Reproduce**

1. Go to Tenant Administration / Domain Analyzer
2. select All Tenants
3. go to Identity Management / Basic Auth Report
4. while loading tenants list => Request failed with status code 500

**Expected behavior**
write "select a tenant first"

**Screenshots**
![image](https://user-images.githubusercontent.com/7716697/152646671-f7c64f0f-a15e-4958-88c0-4ec80ce9d266.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge
- Version 97

**Comment by homotechsual** [comment]
Can confirm this behaviour, this happens when we pass `?customerId=AllTenants` to pages which don't support it. We can probably fix this in `TenantSelector`.

**Comment by KelvinTegelaar** [comment]
seems fixed in dev :)
