### ISSUE TITLE
FEATURE REQUEST: Display SKU friendly License name in BPA report

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#725]
**Is your feature request related to a problem? Please describe.**
BPA Report displays the unused SKUs names as provided by M365 API (i.e O365_BUSINESS_ESSENTIALS, ATP_ENTERPRISE) instead of the friendly name as displayed in Users page (MICROSOFT 365 BUSINESS STANDARD, Microsoft Defender for Office 365 (Plan 1) )

**Describe the solution you'd like**
Display the license names in a consistent manner on all pages, using the official public name (as displayed on Identity / Users page),

![image](https://user-images.githubusercontent.com/7716697/152652781-01dd0c62-2ab8-4859-ada4-96d56b18a3bc.png)

 instead of internal SKU name (as shown in BPA page)

![image](https://user-images.githubusercontent.com/7716697/152652766-d0c426fe-075a-4982-ab41-ce4863a352dc.png)

**Comment by ROI-Admin-User** [comment]
I think we raised this same request previously, and someone replied that it was already planned for the migration to react.

**Comment by homotechsual** [comment]
It might have gotten lost.

**Comment by homotechsual** [comment]
I would like to work on this please!

**Comment by ROI-Admin-User** [comment]
I don't know if my comment counts as activity, but I'm going to throw it out into the ether anyway to hopefully keep this feature request alive...

**Comment by gavsto** [comment]
@ROI-Admin-User You'll be pleased to hear this is now in Dev and should be in the next release! Thank you for the request.
