### ISSUE TITLE
FEATURE REQUEST:  BPA - display the total count of unused licenses (seats) along unused SKUs 

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#726]
**Describe the solution you'd like**
In Unused Liceses column, instead of ```3SKUs``` display ```3SKUs / 10 licenses``` (or seats instead of licenses) 
 
**Additional context**
![image](https://user-images.githubusercontent.com/7716697/152657014-929a1419-9ca0-4cec-9c79-5264c81d80ad.png)

**Comment by gavsto** [comment]
This has been implemented in Dev and should be in the next release.
