### ISSUE TITLE
FEATURE REQUEST:  "Reader" access to internal partner tenant

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#732]
**Is your feature request related to a problem? Please describe.**
Cannot check partner tenant against existing standards or review in BPA or Domain Checker, or get list of policies

**Describe the solution you'd like**
Would it be possible to implement a "read-only" kind of access (no changes can be made, no Standards applied, no policies or apps deployed) to the internal partner tenant?

**Describe alternatives you've considered**
Trying to manually check with the M365 admin portals. Gross

**Additional context**
CIPP team has been clear on their feelings re: the vulnerabilities this could open up if we were to have the ability to access an internal/partner tenant from CIPP ... but perhaps would be open to exploring a read-only solution?

**Comment by KelvinTegelaar** [comment]
working on something for this in the future, it's on the roadmap
