### ISSUE TITLE
BUG: Forwarding Address True for All Accounts

### ISSUE THREAD

**Issue by CHRIS-BRANNON** [KelvinTegelaar/CIPP#735]
**Describe the bug**
When viewing a user under Identity Management > Users the Forwarding Address shows a green check in the Email Settings section.

**To Reproduce**

1. Go to Identity Management
2. Click on Users
3. View a user
4. Scroll down to Email Settings
5. Look at Forwarding Address

**Expected behavior**
Should only be marked off if a forwarding address is set. Right now, it's marked off for all accounts.

**Comment by homotechsual** [comment]
I can reproduce this behaviour for users with forwarding disabled - we're evaluating a string as a boolean I believe.

**Comment by KelvinTegelaar** [comment]
fixed in dev
