### ISSUE TITLE
BUG: OneDrive Details

### ISSUE THREAD

**Issue by CHRIS-BRANNON** [KelvinTegelaar/CIPP#736]
**Describe the bug**
OneDrive Details shows undefined/undefined for Usage and No Data for Percent.

**To Reproduce**

1. Go to Identity Management
2. Click on 'Users
3. View users details
4. OneDrive Details doest not return data.

**Screenshots**
![image](https://user-images.githubusercontent.com/99292551/153078891-733b08f3-1e95-43e7-a83d-ee0053d97e1f.png)

**Additional context**
Going to Teams & SharePoint > OneDrive > List OneDrive does work.

**Comment by KelvinTegelaar** [comment]
Not a bug, please read the documentation and execute the correct standards.
