### ISSUE TITLE
BUG: Teams Business Voice Status code 500

### ISSUE THREAD

**Issue by CHRIS-BRANNON** [KelvinTegelaar/CIPP#737]
**Describe the bug**
Business Voice not loading

**To Reproduce**

1. Go to Teams & Sharepoint
2. Click on Teams
3. Click on Business Voice

**Additional context**
```
{
  "status": 500,
  "data": "",
  "message": "Request failed with status code 500"
}
```

**Comment by KelvinTegelaar** [comment]
Not a bug, tenant is not licensed for business voice. page works
