### ISSUE TITLE
BUG: applying standard as `editor` role gives very ambiguous error message

### ISSUE THREAD

**Issue by k-grube** [KelvinTegelaar/CIPP#738]
**Describe the bug**
Error message is simple 403 with html blob returned as data

![image](https://user-images.githubusercontent.com/20404989/153088397-ab1946fe-5c8e-404a-81cf-9382c9aca37f.png)

**To Reproduce**

1. As editor role user, attempt to assign standard

**Expected behavior**
Return error message stating assigned role does not have access to assign standards, or not even allow the request to be submitted in the first place.

**Comment by KelvinTegelaar** [comment]
Should add to private roles

**Comment by KelvinTegelaar** [comment]
added to private routes in dev.
