### ISSUE TITLE
FEATURE REQUEST: Add Tenant filter to Security / List Alerts

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#744]
**Is your feature request related to a problem? Please describe.**
List Alerts page takes forever to load, perhaps because it queries alerts for all tenants. Most of the time I'm interested in getting the list of alerts for a single tenant, not for all tenants.

**Describe the solution you'd like**
A tenant filter on top of page just like in other pages, to retrieve the alerts for a specific tenant

**Comment by KelvinTegelaar** [comment]
added in dev
