### ISSUE TITLE
List of users are not loading for larger tenant

### ISSUE THREAD

**Issue by Sweggle** [KelvinTegelaar/CIPP#75]
**Describe the bug**
First off, amazing solution - thank you!
I have a tenant with around 2,200 users, for this tenant only, the user list never loads the actual list of users.
It is working for my other tenants with much less users. The app permissions test is coming back ok. 
I've tried leaving it for a while and have tried different browsers - chrome, firefox, edge
The groups seem to load ok and there's 1,350 of those. 

**To Reproduce**
1. Go to Administration -> Users
2. Click on the tenant in question from the drop down
3. Users never load - always 'Loading'

**Expected behavior**
The list of users will appear. 

**Screenshots**
![UsersNotLoading](https://user-images.githubusercontent.com/32654519/137797524-5c4e4736-4abc-4b0b-b17e-22e53ed3204d.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser FireFox 93.0 / Chrome  94.0.4606.81

**Comment by Sweggle** [comment]
Hi Kelvin,

I've double checked and I dont have a upn that matches the one I used for the Secure App Model in that tenant. 

Thanks!

**Comment by benhopperau** [comment]
Is it limited to exactly 999? I see the API functions has a `$top=999` in the graph query.

**Comment by KelvinTegelaar** [comment]
No, thats just the size of the first page it picks up. :)

**Comment by KelvinTegelaar** [comment]
@Sweggle Did you also update your API? It seems that you have the older API combined with a new interface :)

**Comment by KelvinTegelaar** [comment]
@Sweggle and @tombeech  retrieve the latest version of the API and try again.

The CSV file was indeed the problem, but the user request was also extremely large. We're now only pulling our selected fields and made the API considerably faster. 

My tenant of 2200 users now loads in 5 to 7 seconds. @gavsto is still testing the changes but we'd love more feedback. :)

**Comment by KelvinTegelaar** [comment]
Next to pulling the API, you'll also have to force a sync via the Azure Portal -> Azure Functions -> cipp-funcxxxx -> Deployment center-> Sync

**Comment by tombeech** [comment]
Appreciate it, that's what I was missing. 

So it loaded in 7 seconds, which is fantastic work. I'll do some proper testing tomorrow and feedback if anything is odd. Thanks mate

**Comment by KelvinTegelaar** [comment]
Closed as resolved.
