### ISSUE TITLE
BUG: Some tenants are showing an error 500 status

### ISSUE THREAD

**Issue by robm82** [KelvinTegelaar/CIPP#752]
**Describe the bug**
Some tenants are showing an Error 500 on some of the pages within CPP. E.g. IDENTITIY MANAGEMENT | Administration | Users

**To Reproduce**

1. Click on Users within IDENTITIY MANAGEMENT | Administration
2. Change the tenant to one that doesn't work
3. After a few seconds a pop up comes up as per the below screenshot. Request failed with status code 500

**Expected behavior**
Most other tenants display the list of users fine, which is the expected behaviour

**Screenshots**
![image](https://user-images.githubusercontent.com/47445676/154046840-c2f6ad79-7c54-432d-972e-2ed583c54d74.png)

**Desktop (please complete the following information):**
- O/S: Windows 11
- Browser: Edge 98.0.1108.43

**Comment by KelvinTegelaar** [comment]
Not a bug, your tokens are not working for those tenants. Perform access checks and check the documentation on https://cipp.app. You most likely have missed consents, conditional access policies, or have your SAM user as a guest in those tenants.
