### ISSUE TITLE
FEATURE REQUEST: Password options

### ISSUE THREAD

**Issue by ruffmeister69** [KelvinTegelaar/CIPP#754]
Password resets when performed - can there be a randomised password option added so that they automatically get a suggestion like the 365 portal does at present?

Can the ability to email the password reset to a specific email address and if possible have a permenant one selected i.e helpdesk@

**Comment by KelvinTegelaar** [comment]
If you do not enter a password yourself, the password will be generated for you. Cleared this up in interface :)
