### ISSUE TITLE
BUG: Screen Lock Time in Endpoint Manager Template should be set in seconds not minutes

### ISSUE THREAD

**Issue by JPT62089** [KelvinTegelaar/CIPP#756]
**Describe the bug**
Added the "CIPP Default: Set screen lock time to 5 minutes to one of our clients. The value applied by this template is "5" which is meant to be 5 minutes. However, this should be 5 minutes in seconds (300 seconds) per the [Microsoft Docs](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/interactive-logon-machine-inactivity-limit)

**To Reproduce**

1. Go to MEM -> Apply Policy
2. Select Client and add the "CIPP Default: Set screen lock time to 5 minutes" per the defaults
3. Click Next and then Submit
4. Apply to a computer and it will lock after 5 seconds of inactivity.

**Expected behavior**
The computer should lock after 5 minutes of inactivity

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by homotechsual** [comment]
Ooof - that's a doozy!

**Comment by KelvinTegelaar** [comment]
whoops! I actually did this on purpose for my tests, and forgot to rollback. Fixing. :)

**Comment by KelvinTegelaar** [comment]
fixedin dev
