### ISSUE TITLE
FEATURE REQUEST: use red/green checks in user offboarding confirmation page

### ISSUE THREAD

**Issue by mirceamitu** [KelvinTegelaar/CIPP#765]
**Is your feature request related to a problem? Please describe.**

Selected/disabled options in user offboarding wizard confirmation page are all orange and hard to read which ones are selected and which not

![image](https://user-images.githubusercontent.com/7716697/154641851-2d5ce1ec-bcb3-465b-bd1e-aa6fd234e706.png)

**Describe the solution you'd like**
Use a two-color scheme (red/green, green/gray) to differentiate between selected/not-selection options

**Comment by homotechsual** [comment]
Done in Dev - should make today's release.
