### ISSUE TITLE
BUG: Security & Compliance > List Alerts "Set Status to Resolved" and "View source alert in compliance center" not working

### ISSUE THREAD

**Issue by bowatts** [KelvinTegelaar/CIPP#773]
1. Set Status to Resolved - Attempted on several alerts across several tenants, all produce error "Failed to change status: Auth token does not contain valid permissions or user does not have valid roles."
2. Set status to In Progress - Produces same error as Set Status to Resolved.
3. View source alert in compliance center - Doesn't redirect to correct URL, it is, however, appending the current URI with the target link, example: https://cipp.domain/security/reports/list-alerts/https://protection.office.com/viewalerts?id=my_id

Issue observed in Microsoft Edge and Google Chrome on Windows 11 and MacOS

**Comment by KelvinTegelaar** [comment]
the link bug has been fixed. The others really is a permissions thing, can you check if you have both "SecurityEvents.Readwrite.all" on delegate and application permissions?

**Comment by bowatts** [comment]
Permission was missing on application, permissions checker didn't catch that, thanks
