### ISSUE TITLE
FEATURE REQUEST: add columns for individual standards to Applied Standards List and CSV export

### ISSUE THREAD

**Issue by smood922** [KelvinTegelaar/CIPP#776]
Would like for the Applied standards list (and the CSV export) to have a Y/N column for each checkbox. This will make it easier to standardize Standards across our client base, especially as new Standards are added.

**Comment by gavsto** [comment]
@smood922 Do you mean like a column per standard to show what they have and what they don't have in a long list of tenants?

**Comment by smood922** [comment]
Yes, that's right.

**Comment by KelvinTegelaar** [comment]
added in dev
