### ISSUE TITLE
BUG: Logbook UX: Column Sizing Disproportionate to the Data Displayed

### ISSUE THREAD

**Issue by ByteSizedITGuy** [KelvinTegelaar/CIPP#778]
**Describe the bug**
On the logbook page, the columns have odd sizing applied so that there is a lot of wasted space, and potentially useful data can't be seen. As it stands, every column seems to have the same width. So writing "Info" to the "Severity" column is allocated the same amount of space as an entire log message, much of which you might miss because you can only get a few words into the column before it truncates into an ellipse. 

**To Reproduce**
Visit the logbook page within the CIPP app

**Expected behavior**
The columns on the logbook page should either adapt to the data within a fixed percentage of the screensize, or write the data to that fields' tooltip so you can hover and view the data. 

**Screenshots**
![image](https://user-images.githubusercontent.com/99997445/155008463-f86d1b30-17b9-46b2-b9dc-93e774ede8dc.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Pro 21H2
- Browser New Edge [Chromium] 98.0.1108.56
- CIPP: 2.2.0
- CIPP API: 1.7.2

**Additional context**
I believe there was a change made to some of the other pages that had the same column sizing behavior. This might have just been something missed with the move to React, or a "it's not a bug, it's a feature" situation to help with performance and page render time in the future.

**Comment by KelvinTegelaar** [comment]
Will be fixed at later release.
