### ISSUE TITLE
BUG: "License assignment cannot be done for user with invalid usage location"

### ISSUE THREAD

**Issue by jsmithschilling** [KelvinTegelaar/CIPP#783]
**Describe the bug**
When adding a license to a User through Identity Management > Administration > Users
Error after hitting Edit User 

Error - "License assignment cannot be done for user with invalid usage location"

**To Reproduce**

1. Identity Management
2. Administration
3. Users
4. Edit User
5. Assign License
6. Edit User

**Expected behavior**
License to be assigned to user

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

Is there something else that needs to be added in order to assign the license?

**Comment by KelvinTegelaar** [comment]
Just like on the m365 portal the usage location is required, you most likely left this blank.

**Comment by homotechsual** [comment]
Tip: Set the default value in settings!
