### ISSUE TITLE
BUG: Offboarding Wizard, giving other user access to onedrive issue

### ISSUE THREAD

**Issue by steven-techtron** [KelvinTegelaar/CIPP#785]
**Describe the bug**
When using the offboarding wizard, when you select give other user access to their one drive, the summary page still shows its not selected, have not checked if it actually works in the back end.

**To Reproduce**
Steps to reproduce the behavior: run the offboarding wizard and select a user who should be given access to the users OneDrive folder.

**Expected behavior**
In the summary screen giving access to OneDrive folder should be ticket.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows11
- Browser: Edge
- Version 98

**Comment by KelvinTegelaar** [comment]
fixed in dev, visible bug only.
