### ISSUE TITLE
FEATURE REQUEST: Applied Standards grid view - show sortable date/time

### ISSUE THREAD

**Issue by baitsops** [KelvinTegelaar/CIPP#794]
On the Applied Standards grid view, it'd be great if it showed when the standard was applied. Preferably in a sortable column. 
See screenshot.
![image](https://user-images.githubusercontent.com/62867916/155867348-351c1a14-4149-4d47-979a-01d51e7207c4.png)

**Comment by KelvinTegelaar** [comment]
Good idea, added in dev.
