### ISSUE TITLE
BUG: Business Email Compromise report window not scrollable

### ISSUE THREAD

**Issue by JohnK-OCS** [KelvinTegelaar/CIPP#799]
Window that comes up when you run a BEC on a user does not have scroll bars to see all data. Only way to see additonal data is to zoom browser out to 33% or so. Using Chrome Version 98.0.4758.102 (Official Build) (64-bit). Also tested with Microsoft Edge Version 98.0.1108.62 (Official build) (64-bit).

Hosted instance, CIPP 2.2.0, API 1.7.2, Win 11

**Comment by homotechsual** [comment]
Please provide screenshots to illustrate what you're seeing (redacted as appropriate) and also indicate browser, OS and versions of both tested.

**Comment by homotechsual** [comment]
Also confirm CIPP and CIPP-API versions.

**Comment by JohnK-OCS** [comment]
![CIPP](https://user-images.githubusercontent.com/94405553/156046048-ea579cdb-66fd-4ec4-8e6b-638af74d3435.jpg)

**Comment by homotechsual** [comment]
Can confirm and reproduce.

**Comment by homotechsual** [comment]
PR incoming to fix and convert to Masonry
![image](https://user-images.githubusercontent.com/2288257/156055164-fc9ffe34-70b1-4b98-be9c-d6671028569f.png)
