### ISSUE TITLE
FEATURE REQUEST: Additional information in Offboarding wizard at the user selection screen

### ISSUE THREAD

**Issue by jon-tricorelogic** [KelvinTegelaar/CIPP#806]
**Is your feature request related to a problem? Please describe.**
When using the offboarding wizard if there are accounts with duplicate display names there is no way to tell the difference between them

**Describe the solution you'd like**
maybe the display name and the UPN

**Describe alternatives you've considered**
only the UPN and not the displayname

**Additional context**
I can't really add any without giving up personal information but imagine at the user selection screen there are two accounts with the display name "John Doe" and you only need to get rid of one of them. You know their logins are john.doe2 and john.doe but you cannot currently tell them apart in CIPP Offboarding Wizard.

**Comment by KelvinTegelaar** [comment]
fixed in dev
