### ISSUE TITLE
Mailbox / User Reports

### ISSUE THREAD

**Issue by MSP-From-OC** [KelvinTegelaar/CIPP#810]
**Is your feature request related to a problem? Please describe.**
Combine
Identity Management > Administration > Users 
Email & Exchange > Administration > Mailboxes
Email & Exchange > Reports > Mailbox Statistics 

**Describe the solution you'd like**
1. Customizable display column in CIPP, PDF and CSV format
2. Filterable display options.  Remove Guest, Admins / service accounts
3. Automated export, either 1 click to download all clients in PDF or CSV or monthly emailed reports to end clients.

**Additional context**
The information I need clients to review is
Display Name
Email address
Enabled
Licenses
Mailbox type (User or shared)
Last Active
Mailbox Space / Quota / Archiving
MFA Enabled

**Comment by homotechsual** [comment]
From me this is a no, I don't see the benefit of combining these reports in this way in a broad sense.

If we go in this direction in any sense it makes much more sense to build a flexible report builder rather than a series of increasingly specific and niche reports.

Look forward to seeing what others feel on this one though...

**Comment by MSP-From-OC** [comment]
Just this week I had to spend a half day exporting CSV, editing the spreadsheet and emailing to clients for them to review.   There was a lot of missing information that I would like to see.   At the very least a 1 click to download all reports at once or an automated system would save a lot of work on a quarterly basis.   We are looking at another solution to do QBR reports but the data is right there in CIPP.   Sure a flexible report builder would be great too.    Also to get mailbox information you have to goto 3 different areas of CIPP, its confusing.

**Comment by homotechsual** [comment]
So we're working on documenting how you can hit CIPP's API externally to pull data out and I do understand, broadly, the want - but equally we have to keep CIPP easy to maintain and as broadly useful as we can. I like the idea behind scheduling reports as well.

There are some reports we might be able to condense, more flexible display/filtering is coming soon, but broadly I think the reports should stay as they are which is, largely, segregated by the API they hit or the entity they reference.

I like parts of the idea, I just don't like the initial suggestion of combining those reports.
