### ISSUE TITLE
Temporary Access Pass Authentication methods

### ISSUE THREAD

**Issue by MSP-From-OC** [KelvinTegelaar/CIPP#811]
**Is your feature request related to a problem? Please describe.**
Enable Temporary Access Pass in CIPP Tenant Standards
Create Temporary Access Pass for individual mailboxes

**Describe the solution you'd like**
Currently we login to the partner center > Tenant Azure Active Directory > Users > User > Authentication Methods > Add authentication method.   It would be nice to make this quicker.

**Describe alternatives you've considered**
Currently using Azure AD

**Additional context**
![2022-03-07_14h25_47](https://user-images.githubusercontent.com/100248477/157128283-0db62502-4fbe-4c50-a3af-6348f382766b.png)

**Comment by KelvinTegelaar** [comment]
Added to standards and identity options in dev.
