### ISSUE TITLE
BUG: Offboarding Wizard Step 4 Checkmark Wrong with Automapping

### ISSUE THREAD

**Issue by dellop** [KelvinTegelaar/CIPP#812]
**Describe the bug**
Offboarding Wizard: Step 3/4 - In Step 3, you select a user under "Give other user full access on mailbox with automapping". On step 4,  "Give another user access to the mailbox without automap" is checked. "Give another user access to the mailbox with automap" is not checked.

**To Reproduce**
1. Identity Management > Administration > Offboarding Wizard.
2. Select Tenant > Next.
3. Select User > Next.
4. Select another user under "Give other user full access on mailbox with automapping." > Next.
5. View list on Step 4, noticing the checkmark next to "Give another user access to the mailbox without automap."

**Expected behavior**
Checkmark should be next to "Give another user access to the mailbox with automap"

**Screenshots**
![Screenshot 2022-03-08 110321](https://user-images.githubusercontent.com/35943520/157289291-627d8992-59b5-4a9a-9af2-e78f410fba6b.jpg)
![Screenshot 2022-03-08 110303](https://user-images.githubusercontent.com/35943520/157289302-944de7ee-44d1-4a1d-aa0d-e9f525d0dd37.jpg)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version 97.0.2

**Additional context**

**Comment by KelvinTegelaar** [comment]
Checkbox fixed in dev, thankfully just a interface bug :)
