### ISSUE TITLE
BUG: 500 errors during offboarding process - No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by SuburbanTotoro** [KelvinTegelaar/CIPP#813]
**Describe the bug**
During Step 4 of the offboarding process, "request failed with status code 500" appears and all steps appear to fail. No actions appear to occur, and manual offboarding is required. 

**To Reproduce**

1. Identity management -> Offboarding Wizard
2. Select a tenant, user, offboarding settings
3. Review and confirm
4. Confirm and "request failed with status code 500" appears and steps do not complete

**Expected behavior**
The expected behavior is that the offboarding wizard completes the offboarding task. 

**Screenshots**
<img width="724" alt="offboard" src="https://user-images.githubusercontent.com/96153222/157304387-46c5c1b6-199b-4428-9b8b-5691f7d12349.png">

**Desktop (please complete the following information):**
- OS: Windows 11 with Februrary 2022 rollup applied 
- Browser Edge
- Version ~99.0.1150.30

**Additional context**
The console is returning this error:
```
/identity/reports/azure-ad-connect-report?customerId=ac9f8972-f339-4d51-9a5d-aa8a57c226cf:1

Access to manifest at '[https://identity.azurestaticapps.net/.redirect/aad?hostName=cipp.genuine.network&staticWebAppsAuthNonce=H8bG10QpTFYkDQhU%2bTp%2fRbHf2o%2b0qMpa%2bSIglRcJGi44d6awxIBkZ00ukbqQR%2fQi2zSJiZ1m4g3JiohrDQmAGaw0wVDmgou4l4COYr7Rv8UVHxH228gvOBAixQ5MvfH5&functionKeyVersion=0'](https://identity.azurestaticapps.net/.redirect/aad?hostName=cipp.genuine.network&staticWebAppsAuthNonce=H8bG10QpTFYkDQhU%2bTp%2fRbHf2o%2b0qMpa%2bSIglRcJGi44d6awxIBkZ00ukbqQR%2fQi2zSJiZ1m4g3JiohrDQmAGaw0wVDmgou4l4COYr7Rv8UVHxH228gvOBAixQ5MvfH5&functionKeyVersion=0%27) (redirected from '[https://cipp.genuine.network/manifest.json')](https://cipp.genuine.network/manifest.json%27)) from origin '[https://cipp.genuine.network']() has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
identity.azurestaticapps.net/.redirect/aad?hostName=cipp.genuine.network&staticWebAppsAuthNonce=H8bG10QpTFYkDQhU%2bTp%2fRbHf2o%2b0qMpa%2bSIglRcJGi44d6awxIBkZ00ukbqQR%2fQi2zSJiZ1m4g3JiohrDQmAGaw0wVDmgou4l4COYr7Rv8UVHxH228gvOBAixQ5MvfH5&functionKeyVersion=0:1

Failed to load resource: net::ERR_FAILED
users:1

Access to internal resource at '[https://identity.azurestaticapps.net/.redirect/aad?hostName=cipp.genuine.network&staticWebAppsAuthNonce=hTYXuNosX6HGsyyVZq72twc0taztZxcQrhhEGQ2Bn9qTFkNwSWhdLvaWgDudDN8HY3jVNmiDkH6m459GelzVhDy4oLHEHeC0LyOAOe6Kb%2fMP7G97izD%2fsIZ3TYGa03CJ&functionKeyVersion=0'](https://identity.azurestaticapps.net/.redirect/aad?hostName=cipp.genuine.network&staticWebAppsAuthNonce=hTYXuNosX6HGsyyVZq72twc0taztZxcQrhhEGQ2Bn9qTFkNwSWhdLvaWgDudDN8HY3jVNmiDkH6m459GelzVhDy4oLHEHeC0LyOAOe6Kb%2fMP7G97izD%2fsIZ3TYGa03CJ&functionKeyVersion=0%27) (redirected from '[https://cipp.genuine.network/manifest.json')](https://cipp.genuine.network/manifest.json%27)) from origin '[https://cipp.genuine.network']() has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
```

**Comment by KelvinTegelaar** [comment]
CORS is never an issue, and you can ignore that.

Your issue most likely is related to the access token, most tasks there use the Exchange token. Perform an accces check for that tenant to see if its working.

Small note; currently half of the internet is offline due to server disruptions, might also be related to that if this is the only error.

**Comment by SuburbanTotoro** [comment]
Thank you very much Kevin, running the tenant access check shows an error I know how to deal with:
Failed to connect to Exchange: AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator, you must refresh your multi-factor authentication to access '00000002-0000-0ff1-ce00-000000000000'. Trace ID: a3e7f991-dfdf-4b80-bb05-53dfd3eac200 Correlation ID: efe767bb-c6a9-4eeb-8109-e9a4bbb9a37d Timestamp: 2022-03-09 16:58:02Z

I hope you have a great day and really appreciate such a quick response to this,
Benjamin Sanchez​
Senior Automation Engineer

T:
971-288-0880<tel:9712880880>
E:
***@***.******@***.***>
W:
https://genuinetechnology.com<https://genuinetechnology.com/>
[Genuine Technology Logo]<https://genuinetechnology.com/>


Please help us serve you!  Send all requests through the 24/7 support team:

​​Email: ***@***.*** ***@***.***>
​Phone: 9<tel:9718888911>71-888-8911<tel:9718888911>
​
​<https://mygenuine.tech/>Requests made directly to individual staff may ​have a significantly delayed response ​and do not have SLA guarantees
​

**Comment by KelvinTegelaar** [comment]
So fixed :) Will try to have somewhat clearer error messages in a future version too to show its an access token issue.
