### ISSUE TITLE
BUG: Error on deleting user - "Could not delete user: Resource '...' does not exist or one of its queried reference-property objects are not present

### ISSUE THREAD

**Issue by SuburbanTotoro** [KelvinTegelaar/CIPP#814]
**Describe the bug**
When trying to delete users, an error like "Could not delete user: Resource '...' does not exist or one of its queried reference-property objects are not present" is returned and the user is not deleted

**To Reproduce**

1. Go Identity Management > Users
2. Select a tenant
3. Click on "..." menu for user to delete
4. Select "delete user"
5. Confirm to continue

**Expected behavior**
The expected behavior is that the user is deleted without an error when confirmation is provided

**Screenshots**
![image](https://user-images.githubusercontent.com/96153222/157305614-a47eca4b-63da-45e9-8417-363373b64f88.png)

**Desktop:**
- OS: Win11 w/ Feb 2022 rollup
- Browser Edge
- Version  Version 99.0.1150.30

**Comment by KelvinTegelaar** [comment]
This issue only occurs if you do not have permissions to delete on the SAM application or if a user is synced from AD, not a bug.
