### ISSUE TITLE
FEATURE REQUEST: Audit logging within CIPP 

### ISSUE THREAD

**Issue by Rbelmore074** [KelvinTegelaar/CIPP#815]
**Describe the solution you'd like**
In the standard CSP portal we are able to see logs of users and what actions they complete. Using CIPP this only shows the service account making these changes. A nice feature for CIPP would be user activity logging on what actions they perform within the CIPP and maybe logging of user login to the CIPP portal along with this auditing trail. 

Unless I have missed this in the documentation or my navigation within the webapp this would be great added feature for auditing.

**Comment by KelvinTegelaar** [comment]
Already exists, avatar icon, logbook

**Comment by IamBlackmonty** [comment]
Hi Kelvin, it would be good to be able to see the audit logging for all users centrally.  i.e. CIPP admin can view all logs
