### ISSUE TITLE
FEATURE REQUEST: O365 Exchange Transport Rule Templates

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/CIPP#823]
The idea is these would be set up similarly to Intune Templates and would be pushed to a tenant to standardize transport rules.

Scenario is we've got antispam service.  We have two transport rules that need to be applied consistently:
1. If email came from an IP in this <waves hands> big ass list, then bypass spam checking.
2. If email came from an IP that's not in that list, then route email out to MX record for domain (so it does get processed by antispam checker).

Those two would baseline the setup, ensuring consistency of onboarding the service at minimal labor to the project engineer.

**Comment by KelvinTegelaar** [comment]
added in dev
