### ISSUE TITLE
BUG: Tables do not sort columns of integers correctly

### ISSUE THREAD

**Issue by AZweimiller** [KelvinTegelaar/CIPP#824]
**Describe the bug**
CIPP tables, such as Mailbox Statistics, OneDrive List, etc do not sort columns of integers as expected. They seem to be treated as strings.

**To Reproduce**

On the left menu, pick Email & Exchange, then reports, then Mailbox Statistics
Sort the Item Count (Total) column

**Expected behavior**
Column should be sorted in ascending or descending order by integer size

**Screenshots**
![column-sort](https://user-images.githubusercontent.com/69478487/158437946-4a262acf-3c25-46da-ac99-8d8d39166d15.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge
- Version: 99.0.1150.3

**Comment by KelvinTegelaar** [comment]
Fixed in dev by using different sorting mode
