### ISSUE TITLE
BUG: Error when changing pages after selecting AllTenants

### ISSUE THREAD

**Issue by AZweimiller** [KelvinTegelaar/CIPP#825]
**Describe the bug**
Error 400 occured. There is an issue with the token configuration for this tenant. Please perform an access check

This error occurs after selecting "AllTenants" on a supported page and then switching to another page that does not support "AllTenants".

Other Random observation: Menu spells it "Licences" and the table says "Licenses"

**To Reproduce**

1. Go to Tenant Administration -> List Licences.
2. Select AllTenants
3. Switch to Conditional Access Policies in the menu

**Expected behavior**
Pages that do not support AllTenants should default to "Select Tenant" but without the error message.

**Comment by KelvinTegelaar** [comment]
https://github.com/KelvinTegelaar/CIPP/issues/723
