### ISSUE TITLE
BUG: Unable to filter usernames

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#828]
**Describe the bug**
When editing mailbox permissions, I am unable to search/filter the list of usernames to assign the permissions to. Typing in the box does not filter the list, and the list is not even in alphabetical order.

**To Reproduce**

1. Go to Email & Exchange > Administration > Mailboxes
2. Pick a user to edit the permissions for
3. From any of the drop down lists try filtering by a user, either by firstname or by email address

**Expected behavior**
The list should filter and show only the intended user, but it does not.

**Screenshots**
![2022-03-16_09-07-37](https://user-images.githubusercontent.com/20848373/158555320-769df59f-abc7-4c47-bea5-030b03c34c2b.jpg)

**Comment by KelvinTegelaar** [comment]
This is fixed in dev, we changed the filtering and added email addresses to the optional states

**Comment by matstocks** [comment]
@KelvinTegelaar should this be in the release that just came out? If so, i'm still having issues since deploying the update.

**Comment by KelvinTegelaar** [comment]
Missed the one in mailboxes. Next release :)
