### ISSUE TITLE
BUG: Can't remove a field on a user

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#829]
**Describe the bug**
I'm trying to delete a job role on a user, CIPP states that it saves the changes, but, it doesn't.

**To Reproduce**

1. Go to Administration > Users
2. Click on edit under any user
3. Delete the job role.
4. Save
5. Refresh the page
6. The Job role is back

**Expected behavior**
Step 6 above should not see the job role

**Additional context**
I believe https://github.com/KelvinTegelaar/CIPP-API/blob/master/EditUser/run.ps1 / Line 37 is responsible as it isn't looking at blank fields.

**Comment by AdamWillford** [comment]
Can you confirm that the job title isn't removed on the M365 portal @wilhil?

**Comment by wilhil** [comment]
@AdamWillford 

Just opened AAD and edit user in CIPP side by side:

Add in CIPP
Refresh in AAD - it shows.
Remove in CIPP, Refresh in AAD - still there... 

Remove in AAD
Refresh in CIPP - still there :/
... Refresh in CIPP after 15 seconds - It's gone.

Repeated first test, waiting 1 minute, it is still in AAD so I'll go back to thinking this is a bug rather than delay.

So, it looks like it isn't saving from CIPP

**Comment by AdamWillford** [comment]
Can confirm, able to reproduce

**Comment by AdamWillford** [comment]
Fix pushed to dev for release tomorrow

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
