### ISSUE TITLE
FEATURE REQUEST: Ability to audit customer's Global Admin role

### ISSUE THREAD

**Issue by Rbelmore074** [KelvinTegelaar/CIPP#831]
Would like to have a feature where you can pull Global Admins from customer portals as a whole and retain for auditing to ensure this role is not abused or that a customer does not have more Global Admins then needed.

**Comment by KelvinTegelaar** [comment]
Already exists in Identity Management -> Roles and in the new alerting system.

**Comment by Rbelmore074** [comment]
Maybe I did not phrase correctly. Looking for a snapshot view similar to the List Portals where we can see all portals with a number of Global Admin accounts assigned per portal. When you have 1000+ portals connecting to each portal to gather this data is time consuming. Having a snapshot or a way to export to CSV this information for better review.
