### ISSUE TITLE
After deploing when open URL got error 403 

### ISSUE THREAD

**Issue by dogonovm** [KelvinTegelaar/CIPP#833]
Hi, 

I deploy CIPP to my Azure account, but when open app URL I got 403 error. 

<img width="1129" alt="Снимок экрана 2022-03-17 в 16 08 19" src="https://user-images.githubusercontent.com/84489925/158805401-23eb919d-e828-45b4-bde8-8a77e5815f6a.png">
 
How to generate: 

![Снимок экрана 2022-03-17 в 16 03 27](https://user-images.githubusercontent.com/84489925/158805252-7b6d00be-6113-4e0a-93cb-71594a1ef9b8.png)

Where I can take data: 
      LongApplicationID
      LongApplicationSecret
      LongRefreshtoken
      Exchange Refresh Token

**Comment by KelvinTegelaar** [comment]
Please read the docs at https://cipp.app.
