### ISSUE TITLE
FEATURE REQUEST: Conditional Access Visualisation

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#837]
**Is your feature request related to a problem? Please describe.**
Trying to see how conditional access policies are applied in a tenant can be confusing.

**Describe the solution you'd like**
I would like a visual representation to display how they are configured

**Describe alternatives you've considered**
Looking at each policy manually and figuring out how it relates

**Comment by KelvinTegelaar** [comment]
Also related to #809. I'll be working on the templating system for that.

**Comment by lwhitelock** [comment]
Assign me to this please

**Comment by lwhitelock** [comment]
Still working on it

**Comment by lwhitelock** [comment]
Yes I know I will get to it once I finish my Datto webhooks stuff! Stop bullying me damn bot!

**Comment by KelvinTegelaar** [comment]
This issue is stale because Luke likes Lego more than cipping. we'll not close this soon.if you want this feature implemented find a way to steal luke's legos

**Comment by AdamWillford** [comment]
Throwing a comment on to avoid stale'ness

I should stop sending Luke lego sets to buy...

**Comment by IamBlackmonty** [comment]
Lego Mints, to keep things fresh bot
