### ISSUE TITLE
FEATURE REQUEST: Mailbox Automount Management

### ISSUE THREAD

**Issue by jcpit** [KelvinTegelaar/CIPP#840]
**Is your feature request related to a problem? Please describe.**
Mailboxes with Full permissions are set to automount by default.
This means outlook will download the emails into the same OST Cache, which is limited to 50GB and causes performance issues in Outlook.

**Describe the solution you'd like**
To have a way for all mailboxes to have the Automount disabled globally as a standard.
And have the ability to manually managed the automount state of mailbox permissions individually.

**Comment by davewatson91** [comment]
I whole-heartedly second this. 

Current solution to have to do this with powershell scripts is a pain, unfortunately also no way to status the current state, so not sure how you would implement it nicely, but definitely would be worth it!

**Comment by KelvinTegelaar** [comment]
Due to having a lot of items on our action list, we're currently only accepting Pull request where the feature has already been completed, or new feature requests by sponsors.
