### ISSUE TITLE
BUG: When reviewing prior days in logbook getting errors

### ISSUE THREAD

**Issue by Rbelmore074** [KelvinTegelaar/CIPP#841]
![ScreenShotCIPPLogs](https://user-images.githubusercontent.com/101293421/159319430-ce6a3778-a7f9-4a18-ac7a-90fa18ebc1b3.PNG)
When trying to review logs for prior days getting error of API connection. See attached screen shot. This has been the same from time of install of CIPP. Appears to be permission related. Have reviewed permissions listed in the setup and also have run the permission check within the Settings on the portal.

**Comment by gavsto** [comment]
Can you be more specific about what you are doing here? Are you just going to the logbook and then seeing these errors?

**Comment by Rbelmore074** [comment]
When going to the logbook and then expanding the settings. When selecting any of the Log File dates we get this error. When opening the logbook in default sate we are able to see the logs for the current days only. This only happens when trying to review logs from another day.

**Comment by TP-REdwards** [comment]
I also have this issue - same reproduction steps.

**Comment by KelvinTegelaar** [comment]
These are not errors, that's the actual log file. There are corrupt lines which cause this. The new version will have some prevention for this.
