### ISSUE TITLE
FEATURE REQUEST: In the new calendar permissions management account information

### ISSUE THREAD

**Issue by jon-tricorelogic** [KelvinTegelaar/CIPP#843]
Cannot currently scroll in the account information pane of the Edit Calendar Permissions. Some permissions are cut off and unreadable.

**Comment by jon-tricorelogic** [comment]
Refresh does work! Genius! Is it on the roadmap to get the scroll bar on the first load or is that a hard limitation of the tools?

**Comment by KelvinTegelaar** [comment]
Bug on some other pages too, will be fixed in later version :)

**Comment by AdamWillford** [comment]
I think this is a similar problem I get on BECView sometimes - no ability to scroll despite tables that exist below the initial page load.  Refresh doesn't fix it on BEC, so glad it did on this one
