### ISSUE TITLE
FEATURE REQUEST: Revoke user tokens at a whim

### ISSUE THREAD

**Issue by TP-REdwards** [KelvinTegelaar/CIPP#844]
**Describe the solution you'd like**
The ability to revoke tokens (https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken) when blocking sign-in or as a separate option

For example:
![image](https://user-images.githubusercontent.com/80802320/160026651-82bb2830-46ff-4785-8206-ff955a2c41f2.png)

**Comment by KelvinTegelaar** [comment]
Due to having a lot of items on our action list, we're currently only accepting Pull request where the feature has already been completed, or new feature requests by sponsors.
