### ISSUE TITLE
BUG: User Offboarding Wizard - OneDrive flag not working

### ISSUE THREAD

**Issue by davewatson91** [KelvinTegelaar/CIPP#845]
**Describe the bug**
When selecting a user to share the offboarded users OneDrive with, on the confirmation page, it does not show as a tick. I am not sure if it is actually sharing or not at this stage. Tested against a couple of users. 

**To Reproduce**
Attempt to offboard user, providing another user with access to OneDrive. 

**Expected behavior**
Reflect the status of having shared the OneDrive access. 

**Screenshots**
![1](https://user-images.githubusercontent.com/51277302/160050380-cb3b9f3e-7f07-4d39-a01d-aa1c1b7b667a.PNG)
![2](https://user-images.githubusercontent.com/51277302/160050373-a21a7bf0-79d8-4b78-8630-105bde179f70.PNG)

**Desktop (please complete the following information):**

- OS: W10P
- Browser: Chrome
- Version: 99.0.4844.74

**Comment by KelvinTegelaar** [comment]
You're a release behind, this has already been resolved in earlier release.
