### ISSUE TITLE
FEATURE REQUEST: Group / Shared mailbox during user creation

### ISSUE THREAD

**Issue by davewatson91** [KelvinTegelaar/CIPP#846]
**Is your feature request related to a problem? Please describe.**
When onboarding a user, often they require access to Shared mailboxes. The same goes for groups, often with smaller businesses staff may have varying roles and not be replicating another user. 

**Describe the solution you'd like**
It would be ideal to be able to have a multi-select list of mailboxes access is required to, and also groups. 

**Describe alternatives you've considered**
Using the individual tenant management portals - kind of painful, and defeats the purpose of CIPP :)

**Comment by KelvinTegelaar** [comment]
Due to having a lot of items on our action list, we're currently only accepting Pull request where the feature has already been completed, or new feature requests by sponsors.
