### ISSUE TITLE
BUG: SPF Pass Test shows failed when passed.

### ISSUE THREAD

**Issue by karnophage** [KelvinTegelaar/CIPP#849]
See screenshot. Using the domains analyser, it shows the SPF test as missing expected - what is expected exactly?

![image](https://user-images.githubusercontent.com/9065745/160401720-9b6eac3d-4187-40c7-96cf-d6d04206892a.png)

**Comment by johnduprey** [comment]
I would like to work on this please

**Comment by johnduprey** [comment]
@karnophage I've submitted fixes for the SPF bug and the scoring system overall, this should be in the next release once merged.

**Comment by karnophage** [comment]
> @karnophage I've submitted fixes for the SPF bug and the scoring system overall, this should be in the next release once merged.

Perfect! Looking forward to it.
