### ISSUE TITLE
BUG: Best practices Report (PDF) Field data missing

### ISSUE THREAD

**Issue by eaglexeye69** [KelvinTegelaar/CIPP#853]
**Describe the bug**
When you export a Best practices report to PDF, the following fields can appear blank even though on the web GUI and CSV they contain data:

User Cannot Consent To Apps
Modern Auth Enabled
Unused Licenses

**To Reproduce**

Reports -> Best Practice Analyser -> PDF

**Expected behavior**
Would expect data in columns

**Screenshots**
Cannot supply for privacy reasons

**Desktop (please complete the following information):**

- OS: OSX
- Browser Safari
- Version 15.3

**Comment by KelvinTegelaar** [comment]
fixed in dev
