### ISSUE TITLE
BUG: assignedLicenses column in exported CSVs doesn't show license names

### ISSUE THREAD

**Issue by Vespher** [KelvinTegelaar/CIPP#854]
**Describe the bug**
When exporting user lists as a CSV, the assignedLicenses column shows [object Object] once for each assigned license, separated by commas

**To Reproduce**
1. Go to Identity Management -> Administration -> Users
2. Select any tenant
3. Click the "CSV" export button on the top right
4. View the assignedLicenses column on the exported CSV

**Expected behavior**
This column should display the names of each license similarly to how exports directly from M365 Admin work

**Screenshots**
![image](https://user-images.githubusercontent.com/32833951/160904219-f89197f6-6837-4970-866e-3deeb702f6eb.png)

**Comment by KelvinTegelaar** [comment]
known bug, but the data is found in a different column(licJoined). :) Will fix this in new release.
