### ISSUE TITLE
FEATURE REQUEST: Offboarding Suggested Auto Response

### ISSUE THREAD

**Issue by dsghi** [KelvinTegelaar/CIPP#855]
**Is your feature request related to a problem? Please describe.**
Not a specific problem - the Microsoft first-party offboarding wizard has a generic template for the out-of-office reply when converting to a shared mailbox, and this is a nice item to have.

**Describe the solution you'd like**
Add placeholder text on the field for out-of-office reply in the offboarding wizard. Or maybe have a couple of pre-built suggestions that can be added via a dropdown menu

**Additional context**
Microsoft's experience: https://www.screencast.com/t/FsvUhiPHe

**Comment by joelkino** [comment]
Also the box to enter the message is not multi-line. Would be good to have a it as the bottom as a multi-line input.
