### ISSUE TITLE
BUG: Clicking contacts under Exchange Administrations results in error

### ISSUE THREAD

**Issue by 365iT-Solutions** [KelvinTegelaar/CIPP#858]
**Describe the bug**
Clicking contacts under Exchange Administrations results in error

**To Reproduce**

1. Go to 'Email and Exchange -> Administration ->'
2. Click on 'Contacts'

![image](https://user-images.githubusercontent.com/102824527/161391200-baf6b9b2-2870-40bc-b34c-5ce62374b433.png)

**Comment by KelvinTegelaar** [comment]
Confirmed, might run hot patch for this, but is in current dev.
