### ISSUE TITLE
FEATURE REQUEST: Durable function cleanup

### ISSUE THREAD

**Issue by johnduprey** [KelvinTegelaar/CIPP#860]
**Is your feature request related to a problem? Please describe.**
Durable functions write to Azure Blob Storage and have no retention. This is causing storage consumption to increase. As we shift more API calls to Durable Functions this could cause a drastic increase in consumption.

**Describe the solution you'd like**
Automatic blob storage cleanup scheduler. This will help keep storage consumption low by purging old records.

**Describe alternatives you've considered**
Manual cleanup

**Comment by KelvinTegelaar** [comment]
Created beta version of this in dev, currently testing.
