### ISSUE TITLE
BUG: Secure App Model Setup Script drops ObjectId is null exception

### ISSUE THREAD

**Issue by qx-775** [KelvinTegelaar/CIPP#862]
Hi I'm a beginning user and just discovered this tool. Looks amazing from the documentation. However I am having some problems setting up the app using the click to deploy. In the section 'Prerequisites' is where the powershell script `New-SAMAzureADApplication.ps1` fails. I believe the problem is me because I don't have too much idea what I'm doing. Sorry for that. I read all the documentation and proceeded carefully step by step.

**Describe the bug**
When I login using the powershell script and fill in the authentication window prompt it closes and powershell drops ` Cannot bind argument to parameter 'ObjectId' because it is null.` exception.

**To Reproduce**
Setup a new script using the documentation website and run `New-SAMAzureADApplication.ps1`. Login as an administrator with global admin rights, fill in 2 factor authentication and approve login using MFA authenticator.

Precise steps:
1. execute `Secure App Model Setup Script` powershell script as listed on https://cipp.app/docs/user/gettingstarted/prerequisites/
2. For displayName i chose: "test" (since i have no idea what displayname means)
3. A window opens asking me to login
4. I login using my E3 onmicrosoft.com admin account
5. Fill in login credentials and 2FA code press approve login on Microsoft Authenticator
6. Window closes and powershell prompt shows in red `Cannot bind argument to parameter 'ObjectId' because it is null.`

**Notes**
* The user is global admin
* The user is not a risky user
* I tested this with the standard admin account, as well as created a new user account with global admin rights for test purposes. Both 
fails.
* The users are no exemptions on MFA policies in Azure AD since there is no conditional access policy enabled.
* I also installed the PartnerCenter & AzureAD module, both succeeded
* There is no firewall blocking connection because when I manually tested the $app results is not empty.

**Expected behavior**
The authentication form succeeds and I get permissions requests for the Graph API.

**Screenshots**
![image](https://user-images.githubusercontent.com/38159076/161706912-49120dfd-65a0-459c-9bef-86dbdb6092cf.png)

**Desktop:**

- OS: Windows 10
- Browser firefox
- Version 98.0.2
- Script run from powershell version 5.1 using Windows Terminal (and not ISE)

What am I doing wrong? Could the issue be that the license is a E3 trial license, and a partner access is needed? Thanks for the help already!

**Comment by KelvinTegelaar** [comment]
Hi!

Please don't create issues for reports that are not bugs. You can get support from community members on our discord, or on our github community, or direct support as a sponsor, but the issues are really only for bugs and feature requests.
