### ISSUE TITLE
FEATURE REQUEST: Display Primary User for Device

### ISSUE THREAD

**Issue by ITatWork** [KelvinTegelaar/CIPP#866]
**Describe the solution you'd like**
Where a device or list of devices is displayed, display the primary user (if any) assigned to that device.

It would also be lovely to be able to change the assigned primary user for a device.

**Describe alternatives you've considered**
This would be a useful alternative to using device names that related to the primary user of that device.

**Comment by KelvinTegelaar** [comment]
Turns out the API we use to list the devices doesn't expose this info, but we're adding MEM device list and controls in a later release. Will be included in that,.
