### ISSUE TITLE
FEATURE REQUEST: Global Search within Tenant Data

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#868]
Searching for tasks, etc., is great, but what would be truly a timesaver would be if you could search for a user across tenants, or for a mail flow rule, a team, a policy by its name

**Comment by KelvinTegelaar** [comment]
Unfortunately, this is a near impossible ask, especially because we do not store any data in CIPP itself, it only checks the APIs itself. 

You could check out the Graph Explorer option to create your own reports and maybe find it there. :)
