### ISSUE TITLE
Feature request: Multi user selection and perform actions

### ISSUE THREAD

**Issue by freezscholte** [KelvinTegelaar/CIPP#87]
**Is your feature request related to a problem? Please describe.**
We use allot of bulk actions on user level, like changing licenses / group memberships / teams channel memberships / Remove users. But also creating users in bulk would be nice.

**Describe the solution you'd like**
In the users menu/list the option to selection multiple users and a action button where you can choose between different options like mentioned above.

Regarding creating users in bulk I think it would be most simple that you can download a CSV template from the portal fill that in and upload again or some kind of gridview like a online spreadsheet and fill out there all the users.

**Describe alternatives you've considered**
For know we use powershell script to perform bulk actions on users or just the admin portal. Creating bulk users is done from a csv template in a powershell script.

**Additional context**

**Comment by KelvinTegelaar** [comment]
I have underestimated the complexity of this in our current builds, we're nixing this one for at least a couple of releases.

**Comment by KelvinTegelaar** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
We're scratching this one for now, as we're doing a redesign of the frontend that'll have this.
