### ISSUE TITLE
BUG: Typo in Settings

### ISSUE THREAD

**Issue by Arne-RFA** [KelvinTegelaar/CIPP#872]
**Describe the bug**
Typo in Settings

**To Reproduce**

1. Go to Settings under Settings
2. See typo under "Static Web App (Role Management)

**Expected behavior**
"The Static Web App role menagement"

**Screenshots**

![image](https://user-images.githubusercontent.com/74773674/162250882-3f50b0fe-0931-4a4b-b58d-4d9e1bf8ba04.png)

**Desktop (please complete the following information):**

- OS: W10
- Browser: edge
- Version: Version 99.0.1150.55 (Official build) (64-bit)

**Additional context**
Cosmetic only, but stands out...

**Comment by KelvinTegelaar** [comment]
fixed in dev
