### ISSUE TITLE
FEATURE REQUEST: User Offboarding, to remove them from any Shared Mailboxes they may have been assisgned

### ISSUE THREAD

**Issue by yourITca** [KelvinTegelaar/CIPP#876]
**Is your feature request related to a problem? Please describe.**
Most of our Clients have many Shared Mailboxes and depending on your dept and role you could be assigned 5+ with full access, send as etc.  We use Powershell to remove them from the Shared Mailboxes as the first step before the rest of the user offboarding process.

**Describe the solution you'd like**
provide a list of all the Shared Mailboxes they are a member / assigned and then remove them.  Or run against all the existing Shared Mailboxes that exist at the Tenant

**Describe alternatives you've considered**
We use Powershell now run against each shared mailbox at the organization so we do not miss removing them

**Additional context**
PS commands we run for the user being offboarded for each Shared Mailbox
Remove-MailboxPermission -Identity shared@company.ca -User user@company.ca -AccessRights FullAccess,SendAs -InheritanceType All -Confirm:$false

Set-Mailbox -Identity shared@company.ca -GrantSendOnBehalfTo @{Remove="user@company.ca"}

Remove-RecipientPermission shared@company.ca -AccessRights SendAs -Trustee user@company.ca -Confirm:$false

**Comment by RedRhombus001** [comment]
This would be a nice feature.

**Comment by KelvinTegelaar** [comment]
unfortunately, this isn't as easy as it seems with the exchange shell we have and timeout limitations within SWA, for now we'll close this, but feel free to reopen somewhere in the future to revisit.
