### ISSUE TITLE
FEATURE REQUEST: Option to Add vs. Replace Applied Standards

### ISSUE THREAD

**Issue by PremierOne1130** [KelvinTegelaar/CIPP#879]
**Is your feature request related to a problem? Please describe.**
We have many tenants that are often in different stages of rolling out applied standards. At times, we are ready to roll out additional applied standards en masse but want to add on to the currently applied standards and not replace them. For example, we many want to enabled unified audit log for all tenants IN ADDITION to whatever standards they currently have applied.

**Describe the solution you'd like**
We would greatly benefit from an option somewhere in the Apply Standard wizard that allowed us to dictate behavior between Replacing applied standards and Adding to existing applied standards.

**Comment by joshgozar** [comment]
this would be awesome

**Comment by bbeamts** [comment]
+1
