### ISSUE TITLE
FEATURE REQUEST: Extra information for "Edit Mailbox Permissions" view

### ISSUE THREAD

**Issue by tech-squid** [KelvinTegelaar/CIPP#880]
**Is your feature request related to a problem? Please describe.**
The "Edit Mailbox Permissions"] could possibly benefit from extra information.

**Describe the solution you'd like**
If possible, I think it would be beneficial to show which mailbox we're editing in the titel section and to add the automapping status to the "Account Information" section.

![CIPP - mbx editing screen](https://user-images.githubusercontent.com/92542625/163121711-4407dea2-8a0c-4f02-ad41-441ef2994519.png)

**Comment by KelvinTegelaar** [comment]
Not possible, automapping is not exposed by the APIs.
