### ISSUE TITLE
FEATURE REQUEST: Adding a back button

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#882]
When going into edit a user, or mailbox permissions, I would like to go back and then edit a different user or mailbox in the same tenant. I currently click the back button on the browser, which takes me back to the area I need to go to. However it reloads the tenant

**Describe the solution you'd like**
A back button that goes to the previous screen

**Describe alternatives you've considered**
Using the back button currently.

**Comment by KelvinTegelaar** [comment]
this is unfortunately a limitation of our framework and we can't change this. sorry! :)
