### ISSUE TITLE
FEATURE REQUEST: Clear incorrectly selected user in offboarding drop downs

### ISSUE THREAD

**Issue by RedRhombus001** [KelvinTegelaar/CIPP#883]
**Is your feature request related to a problem? Please describe.**
When selecting a user from a drop down (e.g offboarding wizard) there is no way to clear an incorrectly selected user.

**Describe the solution you'd like**
An X or clear button next to each field, a "clear" button that clears the fields.

**Describe alternatives you've considered**
Currently navigating to a different section in CIPP, then navigating back. Pressing back, or previous doesn't clear the incorrect selections.

**Comment by KelvinTegelaar** [comment]
Those dropdowns need some love yes. :) checking if we can still get this in this weeks release.

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
