### ISSUE TITLE
BUG: Clear selected user in dropdowns for Offboarding Wizard (e.g. OneDrive)

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#885]
**Describe the bug**
During a user offboarding, I selected a destination user to receive access to the offboard's OneDrive. In step 4, this failed with a 404.

**To Reproduce**
Go to user offboarding wizard, assign a user to receive the offboard's OneDrive in Step 3
Click through to the next step Step 4, and click Previous button to return to Step 3
Attempt to clear the selected user

**Expected behavior**
I expect to be able to clear any prior choice in any dropdown anywhere in CIPP

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge
- Version 100.0.1185.39 (Official build) (64-bit)

**Comment by KelvinTegelaar** [comment]
duplicate of https://github.com/KelvinTegelaar/CIPP/issues/883
