### ISSUE TITLE
Feature request: Add / Remove Spamfilter Rules

### ISSUE THREAD

**Issue by freezscholte** [KelvinTegelaar/CIPP#89]
**Is your feature request related to a problem? Please describe.**
One of our most common daily tasks is creating /editing and removing spam filter rules in Exchange Online

**Describe the solution you'd like**
In the Email and Exchange menu a option to add/edit/remove spamfilter rules

**Describe alternatives you've considered**
Currently using exchange online admin center

**Comment by freezscholte** [comment]
@KelvinTegelaar Sorry missed the comment, I will get back to regarding this today.

**Comment by freezscholte** [comment]
Url within Microsoft Security Center -> https://security.microsoft.com/antispam
There are 3 set of rules see attachment a screenshot from our test tenant
![image](https://user-images.githubusercontent.com/52416805/140407016-be4ae815-dfdf-4d46-bb0f-c527c6c205b4.png)
Within those rules you can for example edit its contents for the incoming spamfilter:
![image](https://user-images.githubusercontent.com/52416805/140410366-ff197b52-30ec-4df8-b7c6-a1c20cbbb563.png)


WIth for example these commands 
Get-HostedContentFilterPolicy and

Get-HostedContentFilterPolicy -Identity "<PolicyName>" | Format-List [<Specific properties to view>]

You can edit the settings in the last screenshot like accepted domains 
![image](https://user-images.githubusercontent.com/52416805/140409060-7fdc65c6-ddc1-44ad-b22d-15ade80d05ea.png)

In the screen above are also the rules our support mostly needs to change:
AllowedSenders
AllowedSenderDomains
BlockedSenders 
BlockedSenderDomains 

https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/configure-your-spam-filter-policies?view=o365-worldwide

I also think its worth while to think about some other functions in https://security.microsoft.com/ to manage with CIPP not the really in dept ones because you probably could better login in to the portal.

**Comment by KelvinTegelaar** [comment]
started work on this in #232 by Gavin. This will have a bit more of evolution to track that request for future info.
