### ISSUE TITLE
FEATURE REQUEST: Remove Mobile Devices and inbox rules under offboarding wizard

### ISSUE THREAD

**Issue by 365iT-Solutions** [KelvinTegelaar/CIPP#890]
Request to add the following under offboarding wizard:
Remove inbox rules 
Remove Mobile devices from the exchange account.

Following 2 commands will do it

write-host "Removing inbox rules"
Get-InboxRule -Mailbox $user | Remove-InboxRule

Write-Host "Removing Mobile devices"
Get-Mailbox $user | %{Get-MobileDeviceStatistics -Mailbox $_.UserPrincipalName} | Select-Object identity | %{Remove-MobileDevice -identity "$_.identity"}

**Comment by KelvinTegelaar** [comment]
added in dev.
