### ISSUE TITLE
BUG: Backend call failure on Basic Auth reports due to timeout

### ISSUE THREAD

**Issue by MissFox0810** [KelvinTegelaar/CIPP#893]
**Describe the bug**
On some tenants the basic auth report exceeds the timeout of a function call. causing a "500 Backend call failure"

**To Reproduce**

Find a tenant with a large audit log, 
In CIPP run the basic auth report for that tenant
wait 45 seconds
Get a popup with the 500 error

**Expected behavior**
Expected to get a report on a tenant listing users using basic auth.

**Additional context**
There is a little more detail in the discord, See comment chain here: 
https://discord.com/channels/905453405936447518/905454401639047228/966319619637911603
But in short Kelvin thinks it could be due to the Audit log parsing taking too long.

**Comment by KelvinTegelaar** [comment]
Seeing if we can get this fixed by next release with some efficiency improvement.

**Comment by KelvinTegelaar** [comment]
fixed in dev
