### ISSUE TITLE
BUG: Adding mailbox permissions without automapping

### ISSUE THREAD

**Issue by Github-campai** [KelvinTegelaar/CIPP#894]
**Describe the bug**
When adding mailbox permissions without automapping the error:  "Object reference not set to an instance of an object." is given. This happens in all tenants, SAM Permissions OK, Tenant checks 2 green, Cleared cache.

**To Reproduce**

1. Go to Email & Exchange
2. Go to Administration
3. Go to Mailboxes
4. Use the brown notepad/edit button
5. Add a mailbox permission without automapping
6. See screenshots for error.

**Expected behavior**
A new permission entry without automapping to be added to the mailbox permissions, we have used it previously on older builds with no issues.

**Screenshots**
![AddMailboxPerm-NOAutomapping](https://user-images.githubusercontent.com/60176256/164313653-fa6206bf-06c0-48b0-a463-50ce447197c8.png)

![AddMailboxPerm-Automapping](https://user-images.githubusercontent.com/60176256/164313677-d7c7af1e-b5eb-4729-b62c-c36fd2eefa45.png)

It still works fine if we use the standard, with automapping permissions.

**Desktop (please complete the following information):**

- OS: Windows 11 22000.556
- Browser: Edge
- Version 100.0.1185.44

**Additional context**
Frontend 2.5.0
Backend 1.10.0

**Comment by KelvinTegelaar** [comment]
Fixed in dev.
