### ISSUE TITLE
BUG: Server Error on individual domain check for a specific domain

### ISSUE THREAD

**Issue by wilhil** [KelvinTegelaar/CIPP#895]
**Describe the bug**
I am getting a server error on searching for a domain

**To Reproduce**

1. Go to the domain checker
2. Type the domain
3. See server errors popup along with unable to load on sections

**Expected behavior**
No server errors/results populate like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/2283808/164498134-3e27e798-6954-4f9e-bb2c-3d71e818691f.png)

Please note, the domain has customer details, please ping me (Wil) on the server and I will happily give the domain.

**Comment by johnduprey** [comment]
I would like to work on this please!
