### ISSUE TITLE
FEATURE REQUEST: Block known bad attachments as a standard

### ISSUE THREAD

**Issue by mrapoc** [KelvinTegelaar/CIPP#896]
**Is your feature request related to a problem? Please describe.**
Our good friend Fsociety suggested to me about blocking .html files across the board as they are known to be used in phishing. At least sending to quarantine. This will be horrible to do across the client base and would make a good standard.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.](https://techfoundry.co.uk/2016/10/05/office-365-shields-up/) - Set as an option in standards for set tenants or all.

**Describe alternatives you've considered**
Powershell but will need to remember to reapply for new clients 

**Additional context**

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
I'd recommend a transport template instead of a standard :)
