### ISSUE TITLE
FEATURE REQUEST: Excluded MFA Users

### ISSUE THREAD

**Issue by bbeamts** [KelvinTegelaar/CIPP#899]
**Is your feature request related to a problem? Please describe.**
In some situations service accounts may need MFA excluded for certain services. AD Sync is one example. Using standards to enforce MFA for all users is great, but there is no ability to exclude a single user or group from the policy and so MFA gets re-enabled every standards check.

**Describe the solution you'd like**
Ability to select/specify a set of excluded users from the standard/policy.

**Comment by KelvinTegelaar** [comment]
CIPP is made to only apply a secure configuration - The ADSync exclusion is already in place and a huge exception. We will not support making configurations less secure so this is a wontfix.

**Comment by bbeamts** [comment]
Thanks for quick responses Kevin and sorry to have bombarded on a few of these (egg on my face). We have two tenants with MFA forced and ADSync is failing since enabling.
