### ISSUE TITLE
FEATURE REQUEST: User List / View Including Mailbox Type (User vs. Shared)

### ISSUE THREAD

**Issue by bbeamts** [KelvinTegelaar/CIPP#900]
**Is your feature request related to a problem? Please describe.**
When viewing users, there is no easy/clear view to see which are user mailboxes vs. shared in the Administration -> Users list.

**Describe the solution you'd like**
Add a column on the view to see the mailbox type (Member or Shared) and have this also visible when opening up the user as well.

**Comment by KelvinTegelaar** [comment]
Already exists in mailbox administration.
