### ISSUE TITLE
FEATURE REQUEST: Convert to Standard User (from Shared)

### ISSUE THREAD

**Issue by bbeamts** [KelvinTegelaar/CIPP#901]
**Is your feature request related to a problem? Please describe.**
There is currently the ability to convert a mailbox to a shared, but not the reverse. 

**Describe the solution you'd like**
Have the button display as Convert to Standard Mailbox or Convert to Shared based on the mailbox type.

**Comment by KelvinTegelaar** [comment]
Already exists in mailbox administration.
