### ISSUE TITLE
FEATURE REQUEST: Standards Deployment & Updates

### ISSUE THREAD

**Issue by bbeamts** [KelvinTegelaar/CIPP#902]
**Is your feature request related to a problem? Please describe.**
When deploying standards you can't currently see/determine for a single tenant selection what standards are already being managed. You also can't choose to enable certain standards just to "append" to what you have set already. So you can easily overwrite standards you already have set.

**Describe the solution you'd like**
When editing an existing tenants standards, display the existing configuration. This would make it much easier when editing tenants with existing configurations and not damaging any of the current setup.

When adding standards, have the ability to append or replace like licenses. So let's say you append "Unified Audit" being enabled. That doesn't then disable every other standard you have set on the tenants.

**Comment by KelvinTegelaar** [comment]
Please check earlier feature requests, these all have been discussed before.
