### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#905]
When offboarding a user i get the below output which includes an error:

Success. All sessions by this user have been revoked
The new password is xxxxxx
Could not remove user from group 35eaf3ba-e849-xxxxxx
Succesfully removed user from group S6 Invu
Succesfully removed user from group xxxx
Could not remove user from group 74ba51ce-f947xxxxx
Disabled user account for carlos@xxxxx.co.uk
Converted carlos@xxxxxx.co.uk to Shared Mailbox
**Could not add shared mailbox permissions for carlos@xxxxx.co.uk. Error: Cannot process argument transformation on parameter 'User'. Cannot convert value "" to type "Microsoft.Exchange.Configuration.Tasks.SecurityPrincipalIdParameter". Error: "Parameter values of type Microsoft.Exchange.Configuration.Tasks.SecurityPrincipalIdParameter can't be empty. Specify a value, and try again. Parameter name: identity"**
Forwarding all email for carlos@xxxxx.co.uk to info@xxxxx.co.uk
Removed current licenses: MICROSOFT 365 BUSINESS PREMIUM

**Comment by KelvinTegelaar** [comment]
Fixed in tomorrows version, there seems to have been a bit of an issue with our new dropdowns.
