### ISSUE TITLE
FEATURE REQUEST: Include Shared Mailboxes in Mailbox Statistics Report

### ISSUE THREAD

**Issue by PremierOne1130** [KelvinTegelaar/CIPP#908]
It would be very useful to have not only User Mailboxes but also Shared Mailboxes in the Email & Exchange > Reports > Mailbox Statistics report. It would also be helpful to then have a column on this report showing whether the mailbox was User or Shared.

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
adding as planned

**Comment by KelvinTegelaar** [comment]
It's not possible to add these to the same report - The mailbox statistic reports comes from the Graph API and does not expose shared mailboxes, the classic get-mailboxstatistics command is *very* slow and unacceptable for all mailboxes.

**Comment by KelvinTegelaar** [comment]
I've tried making a seperate call for this entirely, with just 60 mailboxes it already reaches the maximum timer, so we're closing this one due to performance.
