### ISSUE TITLE
FEATURE REQUEST: Edit User to Set Auto Response

### ISSUE THREAD

**Issue by PremierOne1130** [KelvinTegelaar/CIPP#909]
There are a number of scenarios where it is useful for an Exchange administrator to set auto-reply responses on behalf of a user. I am suggesting a feature that would allow us to set this auto-response message from within the Edit User page (/identity/administration/users/edit) or somewhere similar.

**Comment by AdamWillford** [comment]
This does already exist in the offboarding wizard :) @PremierOne1130

**Comment by PremierOne1130** [comment]
Understood - could be nice to have outside of the Offboarding Wizard because this is often done apart from offboarding a user, but I see that using the Offboarding Wizard would still work to set the auto-response even if the user isn't actually being offboarded. Thank you!
