### ISSUE TITLE
FEATURE REQUEST: Add Standard to Block User Access to Azure Portal

### ISSUE THREAD

**Issue by LighthouseGitHub** [KelvinTegelaar/CIPP#910]
**Is your feature request related to a problem? Please describe.**
Users can, by default, access portal.azure.com and aad.portal.azure.com. This allows users to create new Azure subscriptions under provided payment methods, or allows an attacker to perform recon on an environment.

**Describe the solution you'd like**
A standard option to block Azure  and AAD portal access for non GA accounts. 

**Describe alternatives you've considered**
Adding the steps listed here to our tenant on boarding process: https://call4cloud.nl/2020/07/the-azure-ad-portal-strikes-back/

**Additional context**

**Comment by KelvinTegelaar** [comment]
I like this as a convience standard, planned.

**Comment by KelvinTegelaar** [comment]
added in dev.
