### ISSUE TITLE
FEATURE REQUEST: Disabling Add shortcut to OneDrive

### ISSUE THREAD

**Issue by sfaxluke** [KelvinTegelaar/CIPP#912]
**Is your feature request related to a problem? Please describe.**
Disabling the add shortcut to OneDrive option in Sharepoint. With this option enabled it can break syncing and cause local issues when users click this without understanding what it does. As it duplicates synced libraries. 

**Describe the solution you'd like**
If this setting is accessible via graph this would likely be added to the convenience standards section.

**Describe alternatives you've considered**
Set-SPOTenant -DisableAddShortcutsToOneDrive $True

**Comment by KelvinTegelaar** [comment]
As Microsoft is moving to use "Add shortcut" over "Sync" as "Add Shortcut" uses a better, and more agile sync engine for OneDrive, in regards to size and speed limits, we're not going to make this a standard.
