### ISSUE TITLE
BUG: Toggling on an off a standard in the Wizard doesn't deselect it.

### ISSUE THREAD

**Issue by lwhitelock** [KelvinTegelaar/CIPP#913]
**Describe the bug**
If you toggle on and then back off a standard in the standards wizard, it will still show as selected in the confirmation screen.

**To Reproduce**
Steps to reproduce the behaviour:

1. Apply a standard
2. Select tenants (tested with all tenants)
3. Toggle a standard on and then back off
4. Proceed to the confirmation
5. The deselected standard will still be shown as selected.

**Expected behaviour**
The deselected option would not show in confirmation.

**Screenshots**
![image](https://user-images.githubusercontent.com/79275328/166658583-6c6332e6-6f4e-4617-96d4-98ac0254247c.png)

![image](https://user-images.githubusercontent.com/79275328/166658618-3b58a09d-90a6-48a7-ad48-97aba90a224e.png)

**Comment by KelvinTegelaar** [comment]
It does deselect it, just with the value "false" - interface bug, we'll need to see a nice way to present that. :)

**Comment by KelvinTegelaar** [comment]
Fixed by showing "Enabled/Disabled" at last screen, as removing the item isn't as pretty.
