### ISSUE TITLE
FEATURE REQUEST: Add Drop Down of Users in Administration / Groups

### ISSUE THREAD

**Issue by DavidHodgsonRITS** [KelvinTegelaar/CIPP#914]
**Is your feature request related to a problem? Please describe.**
When trying to add a user to a group you are required to type in the users UPN, this usually means we have to go check the UPN on another screen before adding them to the group which takes extra time to complete the task.

**Describe the solution you'd like**
On the Groups section under Administration after selecting the tenant and group to edit (actions), it would be great if there was a drop-down list of users in each of the fields (Add Member, Remove Member, Add Owner, Remove Owner) based on the selected tenant.

**Describe alternatives you've considered**
No Alternatives

**Additional context**
None

**Comment by KelvinTegelaar** [comment]
Fixed in dev
