### ISSUE TITLE
FEATURE REQUEST: Enhance user editing to include license checkbox/sliders instead of replacement.

### ISSUE THREAD

**Issue by jbbehar** [KelvinTegelaar/CIPP#915]
Adding a license to users is error prone with the current workflow since it's a replacement of existing licenses. You have to read through the JSON to understand what's currently assigned, make sure to keep those active, then add whatever is additional. The same problem actually exists during removal of a license. This is common to add/remove for things like PowerBI, etc.

During user edit, retain existing licenses by pre-checking the checkbox (or change to sliders) for existing licenses, making adding/removing more visually appealing and easier/quicker.

![image](https://user-images.githubusercontent.com/33136816/166830444-17553a0c-196d-4f22-bff2-f5dd65e0e597.png)

Another nice to have would be under Tenant Administration, a new page that lists of existing licenses (already in License Report but not actionable) like in Microsoft's Admin Center where you can see the total license count per item, and the option to drill into the license and assign/unassign to selected users within the tenant.

**Comment by KelvinTegelaar** [comment]
added in dev, we now precheck the boxes for licenses that the user already has.
