### ISSUE TITLE
BUG: Some lists does not support international characters

### ISSUE THREAD

**Issue by interspaceab** [KelvinTegelaar/CIPP#918]
Lists on some pages does not support international characters. UTF-8 error?

Examples:
Teams & Sharepoint > OneDrive > List OneDrive
Teams & Sharepoint > Sharepoint > List Sharepoint
Email & Exchange > Reports > Mailbox Statistics

Example from Sharepoint list:
![image](https://user-images.githubusercontent.com/99219041/167491268-42098bef-95c7-4698-a1e5-f608b02d0fd6.png)
(Should be: Ägare av Besök brädgårdar)

**Comment by KelvinTegelaar** [comment]
Yeah I hate internationalization so did this on purpose.

(kidding, I think this is because MS decides to return it like that in Graph, I'll see if we can fix that.)

**Comment by KelvinTegelaar** [comment]
Fixed in dev thanks to utf! :)
