### ISSUE TITLE
FEATURE REQUEST: Assign Licenses to Multiple Users at Once

### ISSUE THREAD

**Issue by IamBlackmonty** [KelvinTegelaar/CIPP#919]
**Is your feature request related to a problem? Please describe.**
Within the O365 tenancy we can assign licenses to multiple users (up to 20) at a time.  This cannot be done in CIPP

**Describe the solution you'd like**
Under Identity Management>Administration>Users - Be able to multi-select users with an action of assign licenses

**Describe alternatives you've considered**
The only way to do this is outside of CIPP in the O365 tenancy or via powershell

https://docs.microsoft.com/en-us/microsoft-365/enterprise/assign-licenses-to-user-accounts-with-microsoft-365-powershell?view=o365-worldwide

**Additional context**
Would be really nice.......  Oh also, not having the replace license remove all existing licenses

**Comment by IamBlackmonty** [comment]
Bumpity bump

**Comment by KelvinTegelaar** [comment]
Please dont bump frs, if it times out the issue gets removed of our backlog. If you want this feature also feel free to check out our dev manual on cipp.app.

**Comment by IamBlackmonty** [comment]
Sorry Kelvin. Consider myself smacked

Sent from my iPhone - OAS


 Craig Wallace | Systems and Training Manager 
 OAS Technology, a New Era Technology Company | 75 Shortland Esplanade,  Newcastle NSW 2300
 ph: 02 4940 1800 | oas.com.au 
 
 Newcastle - Upper Hunter - Central Coast - Mid North Coast
  
 We’re Rebranding - In March 2022, OAS Technology joined the New Era Technology family of companies. Learn more about New Era at neweratech.com. 
 
On 17 May 2022, at 6:05 pm, KelvinTegelaar ***@***.***> wrote:

﻿

Please dont bump frs, if it times out the issue gets removed of our backlog. If you want this feature also feel free to check out our dev manual on cipp.app.
