### ISSUE TITLE
BUG: All Tenant License Report - TypeError: t.filter is not a function

### ISSUE THREAD

**Issue by davidpfox** [KelvinTegelaar/CIPP#923]
**Describe the bug**
Unable to run License Report for All Tenants

**To Reproduce**

1. Go to Tenants Administration > Reports > License Report
2. Select All Tenants
3. Error displays

**Expected behavior**
Report for all Tenants

**Screenshots**
![image](https://user-images.githubusercontent.com/51871826/168426017-d10967a7-7cd0-4142-ac69-b243fb1d1fd5.png)

**Desktop (please complete the following information):**

- OS: Win11
- Browser Edge
- Version 101.0.1210.39

**Additional context**

**Comment by KelvinTegelaar** [comment]
Can't simulate this. Can you get more details such as API version etc?

**Comment by davidpfox** [comment]
I ended up rebuilding entire app so will report again if this comes up.
