### ISSUE TITLE
BUG: Secure Application Model Setup Wizard

### ISSUE THREAD

**Issue by matstocks** [KelvinTegelaar/CIPP#924]
Let me start by saying I know this is a beta feature, so bugs are expected.

**Describe the bug**
When trying to use the Secure Application Model Setup Wizard an error is encountered at Step 2. After the application is authorised I am redirected to /api/ExecSAMSetup and an error is shown: 

"No authentication code found. Please go back to the wizard and click the URL again."

**Comment by KelvinTegelaar** [comment]
Resolved by changing how the Wizard handles authentication, seems to no longer appear now.
