### ISSUE TITLE
FEATURE REQUEST: Disable Viva daily emails

### ISSUE THREAD

**Issue by kayvanaarssen** [KelvinTegelaar/CIPP#925]
It would be nice to apply a standard to disable the Daily Viva Emails
This can be done on a per tenant base, but is a pain to do it for all of them manually

https://www.alitajran.com/turn-off-microsoft-viva-daily-briefing/ 
https://docs.microsoft.com/en-us/viva/insights/personal/briefing/be-admin

Did not find an org. wide Powershell command. But maybe its out there.

**Comment by KelvinTegelaar** [comment]
aaded in dev
