### ISSUE TITLE
FEATURE REQUEST: Is it possible to schedule email alerts for custom MS graph reports ?

### ISSUE THREAD

**Issue by 365iT-Solutions** [KelvinTegelaar/CIPP#926]
I am looking to schedule certain MS graph reports that will send results over email/webhook on a set time. I am asking this for MS graph because it opens tons of possibilities of scheduled reports.

Eg: Monthly reports on how many user have not logged on to their account in 3 months.

**Comment by KelvinTegelaar** [comment]
I like this idea, checking on how to tackle

**Comment by 365iT-Solutions** [comment]
Thanks !!
