### ISSUE TITLE
FEATURE REQUEST: Send As and Send on Behalf permissions for Exchange

### ISSUE THREAD

**Issue by NSOCIPPApp** [KelvinTegelaar/CIPP#927]
There is only an option to assign Full Access to a mailbox but no Send As or Send on Behalf permissions. We would really like that option.

**Comment by KelvinTegelaar** [comment]
Good request, was also discussed in Discord. Will add for next release.

**Comment by KelvinTegelaar** [comment]
Added in dev

**Comment by seerxgith** [comment]
Can we get this re-opened to add "Send on Behalf" added as well?
