### ISSUE TITLE
FEATURE REQUEST: Litigation Hold

### ISSUE THREAD

**Issue by nc-azure** [KelvinTegelaar/CIPP#928]
Hi Kelvin,

I love what you have done with CIPP, awesome product.

Would it be possible to add a feature to enable Litigation on mailboxes?

Examples:

This would be the command to enable litigation hold on all mailboxes on a tenant:

Get-Mailbox -ResultSize Unlimited | Set-Mailbox -LitigationHoldEnabled $true

 This would be a command to report on which mailboxes have Litigation Hold enabled:

get-mailbox  | where-object {$_.litigationholdenabled -eq $true} | fl name

**Comment by AdamWillford** [comment]
I would like to work on this please!

**Comment by nc-azure** [comment]
Awesome, thank you Adam :)

**Comment by KelvinTegelaar** [comment]
Not going to implement this; Microsoft no longer recommends using this, but use DLP policies instead: https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-and-litigation-holds

**Comment by nc-azure** [comment]
Hi Kelvin,

Reading that article and then clicking on the second article from that page, it doesn't seem to be referencing Litigation Hold being removed, but more the On-Hold feature being removed.

https://docs.microsoft.com/en-us/microsoft-365/compliance/legacy-ediscovery-retirement?view=o365-worldwide

It is still your call at the end of the day, but I thought I would try get some more clarity on this :)

Thanking you in advance
