### ISSUE TITLE
FEATURE REQUEST: Audit Logs

### ISSUE THREAD

**Issue by nc-azure** [KelvinTegelaar/CIPP#929]
Hi,

Is it possible to view the audit logs from CIPP in regards to, which user made changes on CIPP?
If looking on the customers tenant, after making a change, it refers to the Global Admin account which was used for setting up CIPP rather than the Engineer who made the changes.

If there is a workaround, please advise :)

**Comment by KelvinTegelaar** [comment]
already exists, Avatar icon -> Logbook

**Comment by nc-azure** [comment]
Hi Kelvin,

Thank you for the fast response.

As you could imagine, certain customers would like an export of the logs on certain investigations.
This Logbook doesn't display a username of the Engineer.
Is this already available or is this something that needs to be enabled?

Thank you
Brendan

**Comment by KelvinTegelaar** [comment]
The logbook shows the engineers UPN, e.g: 
```
2022-05-19T09:40:34
Global
ExecDnsConfig
Retrieved DNS configuration
admin@admin.com
Info```

**Comment by nc-azure** [comment]
I do apologize Kelvin, I must be doing something wrong.
Please see screenshots attached of what I can see.
![Logbook](https://user-images.githubusercontent.com/101307591/169254987-8c6144bb-95b0-466d-a9f3-720bb7af5bf2.png)
![Logbook result](https://user-images.githubusercontent.com/101307591/169254997-e1d571fc-5779-4dc1-8461-659b65225a02.png)

**Comment by KelvinTegelaar** [comment]
Standards run under the system user, you can see who setup a standard in the logbooks, or on list applied standards page, in the last two columns.

**Comment by nc-azure** [comment]
I see, thank you for your responses Kelvin.
Really appreciate it and really loving CIPP :)
