### ISSUE TITLE
BUG: Conditional Access policy Excluded locations not accurate

### ISSUE THREAD

**Issue by CalTechCSEngineer** [KelvinTegelaar/CIPP#931]
**Describe the bug**
When looking at the List Policies section under Conditional Access, the Excluded Locations column is not accurately showing what the policies have configured.

**To Reproduce**

1. Go to 'Tenant Administration'
2. Click on 'Conditional Access'
3. Click on 'List Policies'
4. Read list and review Excluded Locations column

**Expected behavior**
I expected that the List Policies section would correctly list all settings related to a CA policy. 

**Screenshots**
![image](https://user-images.githubusercontent.com/74624912/169317079-2901266a-4623-4416-a441-028349c5534f.png)

**Desktop (please complete the following information):**

- OS: Windows 10 Enterprise 21H2 10.0.19044
- Browser Edge, Chrome
- Version Edge 101.0.1210.47,  Chrome 101.0.4951.64

**Comment by KelvinTegelaar** [comment]
Added fix for this; sometimes the API is not able to return a clean name of the location, and it returned a blank field. We're now returning the raw ID, this might not always be pretty, but does make the data more complete.
