### ISSUE TITLE
BUG: Unable to convert to shared mailbox

### ISSUE THREAD

**Issue by jtmaui15** [KelvinTegelaar/CIPP#932]
When trying to convert to a shared mailbox through Identity Management > Administration > Users I get the following message:

**Failed. Response status code does not indicate success: 401 ()..Exception.Message**
![image](https://user-images.githubusercontent.com/105888383/169403483-ee2e9c0d-c04f-4f51-b82c-877ad903aa00.png)

When I try to load the tenant through Email & Exchange > Administration > Mailboxes I get the following message: 

**Error 400 occured. There is an issue with the token configuration for this tenant. Please perform an access check**
If I click details: 
**{
  "status": 403,
  "data": [
    "Error 400 occured. There is an issue with the token configuration for this tenant. Please perform an access check"
  ],
  "message": "Request failed with status code 403"
}**
![image](https://user-images.githubusercontent.com/105888383/169403266-5e29794e-e91c-4693-8182-c8a65ed1b9c9.png)

**To Reproduce**

**Expected behavior**
Mailbox should be converted to shared mailbox.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10 Windows 10 Business
- Browser Chrome 
- Version 101.0.4951.67 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KelvinTegelaar** [comment]
Not a bug, your tokens aren't working.  Please follow the instructions in the error
