### ISSUE TITLE
BUG: MFA Report

### ISSUE THREAD

**Issue by nc-azure** [KelvinTegelaar/CIPP#933]
Not sure if this would be a bug or if the info being pulled is different to the Powershell script I have been running.
However, the results seem to be different.

I have been using this Powershell script from this site.

https://o365reports.com/2019/05/09/export-office-365-users-mfa-status-csv/

Then comparing the results to the MFA report on CIPP, CIPP advises MFA is not enabled by highlighting the users in Red.
Whereby, the users were enabled via Conditional Access.

Please see screenshots below for reference.

**CIPP MFA Report**

![image](https://user-images.githubusercontent.com/101307591/169527432-453968ba-d77a-4248-b588-f170ae90b7e5.png)

MFA Report via the Powershell command

![image](https://user-images.githubusercontent.com/101307591/169527628-c5523b54-591a-4ae7-9a03-88efb137d4d5.png)

**Comment by KelvinTegelaar** [comment]
that script gives false positives; if you ever configured a user for per-user MFA, and afterwards disabled it, that script will still report as enabled, as the device is still configured. The user is just not being challenged.

Check if you really have a Conditional access policy applied to these users that enforces MFA.

**Comment by nc-azure** [comment]
Here is a screenshot of the Conditional Access Policy for this same tenant.
I hope this helps?

The users are apart of the Security Group, linked on this Conditional Access Policy.

![image](https://user-images.githubusercontent.com/101307591/169530204-09d4395e-41d4-4b25-8e29-07541963d70d.png)
