### ISSUE TITLE
MS Group Site Permissions not being applied when adding MS Group members

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#934]
I seem to have an issue when adding users / members to groups.

The user is added to the group as a member (from CIPP) and I can confirm this in the 365 Admin portal.

However, when the user tries to access the underlying group site, they do not have permissions - permissions then need to be added manually via 365 admin portal on the specific group / underlying SharePoint site.

To fix this, I have to remove the member from within CIPP, then re-add using the 365 Admin portal, which then applies permissions to the site. (as expected)

Is this expected behaviour in CIPP? Or a bug? API limitation?

Thanks!

**Comment by KelvinTegelaar** [comment]
bug at the MS side, Graph team/sharepoint team will list this in the known bugs and fix soon(tm)

**Comment by KelvinTegelaar** [comment]
according to MS, this is fixed.
