### ISSUE TITLE
FEATURE REQUEST: Additional Convenience Standards - SendFromAliasEnabled (simple)

### ISSUE THREAD

**Issue by Parad0xMS** [KelvinTegelaar/CIPP#935]
It is an often requested tenant-option from our clients. It would be nice to set it together with the standards.

**Snippet we are using now to check/set the option**

`Connect-ExchangeOnline`
`Get-OrganizationConfig | fl Name, SendFromAliasEnabled`
`Set-OrganizationConfig -SendFromAliasEnabled $true`
`Get-OrganizationConfig | fl Name, SendFromAliasEnabled`
`Disconnect-ExchangeOnline`
___

A not-so-simple aproach to this (and other options) would be to implement a GUI-possibility to define powershell-commands. Some sort of custom setting. Maybe thought to big / too many possible new errors. ;)

Thank you for CIPP. It's great.

**Comment by KelvinTegelaar** [comment]
added in dev
