### ISSUE TITLE
FEATURE REQUEST: Manage Other groups than modern groups

### ISSUE THREAD

**Issue by KelvinTegelaar** [KelvinTegelaar/CIPP#939]
Now that we have complete exo control via a REST API, we should look into managing DLs using that, next to our graph counterparts.

**Comment by dc-castlerock** [comment]
Does this mean issue #934  will be resolved further to this? :)

**Comment by KelvinTegelaar** [comment]
No, seperate thing. :)

**Comment by dc-castlerock** [comment]
Hi - just checking if this is still a potential feature that can be added?

We seem to run into this use-case often where we need to add / remove users from DL's.

Cheers.
