### ISSUE TITLE
BUG: Tenant list does not always retain the tenant

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#94]
**Describe the bug**
Tenant does not maintain the tenant selected

**To Reproduce**
1. Go to Administration > Users
2. Select a tenant, note the data loads
3. Note the tenant selector is empty and doesn't show the tenant name anymore

**Expected behavior**
In all cases the tenant name should be retained in that box, when both selected and a data table loaded and when hit via URL, IE /index.html?page=groups&Tenantfilter=tenant.onmicrosoft.com

**Comment by redanthrax** [comment]
i do this
