### ISSUE TITLE
FEATURE REQUEST: Management of Traditional / Classic SharePoint Sites

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#942]
**Is your feature request related to a problem? Please describe.**
In addition to listing the existing Site information, which is available in ""SharePoint - List SharePoint", it would be great if we had the ability to manage (membership) these traditional / classic SharePoint Sites.

**Describe the solution you'd like**
Simple management of traditional / classic SharePoint sites (members add / remove etc.) which were not built out on a modern 365 group.

**Describe alternatives you've considered**
Just working around the issue by still going through the MS Admin Portal for management of some older traditional / classic sites, which were not built on a modern group.

**Additional context**

**Comment by KelvinTegelaar** [comment]
No sharepoint APIs are available to us :( have to close this.
