### ISSUE TITLE
BUG: Unable to Add User in CIPP v2.6

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#944]
**Describe the bug**
Unable to Add User in CIPP (v2.6)

**To Reproduce**

1. Go to 'Identity Management -> Administration -> Users -> Add User'
2. Try to Add a user

**Expected behavior**
The Add User window should appear, but the text "Select a tenant to get started'' appears

**Screenshots**
![image](https://user-images.githubusercontent.com/105069544/170371543-6cd0a0f9-4c9f-4fc1-9af6-f28682b08e8c.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Version: 101.0.1210.53

**Additional context**

**Comment by Pukkahq** [comment]
We have the same problem. I have tried Edge and Firefox
![image](https://user-images.githubusercontent.com/15746724/170478947-9d39d492-7451-4f3b-bea2-e08e83d4f620.png)

**Comment by KelvinTegelaar** [comment]
Fixed in dev, thanks for reporting. Please remember, you can always fix bugs yourself. Check out https://cipp.app/docs/dev/ for that.
