### ISSUE TITLE
FEATURE REQUEST: Add direct link to SharePoint Admin page

### ISSUE THREAD

**Issue by DavidHodgsonRITS** [KelvinTegelaar/CIPP#947]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Under Tenant Administration and List Tenants we have links to Exchange Portal, 365 Portal etc, would be great to have one to SharePoint Portal for each tenant

**Describe alternatives you've considered**
Without it you can still jump straight into the M365 Portal and then click on SharePoint which is quicker than launching admin.microsoft.com, changing tenant and then going to SharePoint but even quicker to have a direct linl.

**Additional context**
N/A

**Comment by KelvinTegelaar** [comment]
added in dev
