### ISSUE TITLE
BUG: Default usage location under Profile not functioning 

### ISSUE THREAD

**Issue by dc-castlerock** [KelvinTegelaar/CIPP#948]
It would appear that the ''default usage location" feature under Profile in CIPP does not apply when adding new users / licenses.

1. Go to 'Identity Management > Users > Add User' to simulate the bug:

The Default Usage Location is not applied from your profile setting:

![image](https://user-images.githubusercontent.com/105069544/170791926-025d0f6d-b499-4d2b-9ba0-e9e9d9145518.png)

**Expected behavior**
The default usage location should be applied based on your profile setting.

**Comment by KelvinTegelaar** [comment]
fixed in dev
