### ISSUE TITLE
FEATURE REQUEST: New standard: Disable anonymous reports in Microsoft 365

### ISSUE THREAD

**Issue by hanslivden** [KelvinTegelaar/CIPP#949]
**Is your feature request related to a problem? Please describe.**

We utilize a third-party software that pulls user reports through MS Graph, which by default are anonymous on new Microsoft 365 tenants. This makes the reports useless for our customers.

**Describe the solution you'd like**
We would like a new standard which disables this feature.

**Describe alternatives you've considered**
Powershell-script that disables this feature. 

**Additional context**
I got the idea when I was looking for a solution, and found this script.  https://www.cyberdrain.com/automating-with-powershell-disabling-anonymous-reports-for-office365/

**Comment by KelvinTegelaar** [comment]
already exists
