### ISSUE TITLE
FEATURE REQUEST: more licenses / SKUs I think should added to this checks' exclusions

### ISSUE THREAD

**Issue by vitmsadmin** [KelvinTegelaar/CIPP#952]
**Is your feature request related to a problem? Please describe.**
SKU count is showing licenses that should be exempt

**Describe the solution you'd like**
Please exempt the following SKU's
- COMMUNICATIONS CREDITS
- Microsoft Teams Phone Standard - Virtual User
- NONPROFIT_PORTAL

**Describe alternatives you've considered**
No further solution is available to remove SKU license warning

**Additional context**

**Comment by KelvinTegelaar** [comment]
You can add exclusions yourself via the settings menu.
