### ISSUE TITLE
FEATURE REQUEST: 

### ISSUE THREAD

**Issue by RobWellesley** [KelvinTegelaar/CIPP#953]
**Is your feature request related to a problem?
By default any user can create a Team or SPO site.

**Describe the solution you'd like**
The abiltiy to manage who can create 365 groups, specifically, restrict to an AAD group who have permissions to create 365 groups

**Describe alternatives you've considered**
We use the powershell method as discribed here https://docs.microsoft.com/en-us/microsoft-365/solutions/manage-creation-of-groups?view=o365-worldwide#step-1-create-a-group-for-users-who-need-to-create-microsoft-365-groups

**Comment by KelvinTegelaar** [comment]
add in dev to disable standard users from creating sharepoint sites.
