### ISSUE TITLE
FEATURE REQUEST: convert MEM Policy to Endpoint Manager Template

### ISSUE THREAD

**Issue by TheRecovery007** [KelvinTegelaar/CIPP#955]
**Is your feature request related to a problem? Please describe.**
Creating the Endpoint Manager Templates is a pain, it would be very nice to ease this up.

**Describe the solution you'd like**
converting MEM Policy from a tenant to a Endpoint Manager Template

**Describe alternatives you've considered**
getting the raw json in alternative ways but this really only works with Administrative templates

**Comment by dan-baird** [comment]
+1 for this, we really need this functionality. 

There are already a couple open projects which perhaps you can built on to get json files:

- https://github.com/Micke-K/IntuneManagement
- https://github.com/almenscorner/IntuneCD

**Comment by KelvinTegelaar** [comment]
This is on it's way, next release. Tried sneaking it into this one but just too much work. :)

**Comment by KelvinTegelaar** [comment]
added in dev
