### ISSUE TITLE
FEATURE REQUEST: Intune Template to deploy RMM tools

### ISSUE THREAD

**Issue by CalTechCSEngineer** [KelvinTegelaar/CIPP#956]
**Describe the solution you'd like**
Intune template for deployment of RMM tools. 

**Additional context**
![image](https://user-images.githubusercontent.com/74624912/171731903-4d6cae90-a36b-4bf8-ad59-1a35c584c5d6.png)

**Comment by KelvinTegelaar** [comment]
https://github.com/kelvintegelaar/RMMIntunehelper

**Comment by KelvinTegelaar** [comment]
Exists in dev
