### ISSUE TITLE
FEATURE REQUEST: OneDrive Monitoring

### ISSUE THREAD

**Issue by kayvanaarssen** [KelvinTegelaar/CIPP#961]
Would be nice to integrate this in CIPP to see at a glance if there are OneDrive Sync issues;

Sometimes OneDrive gets stuck or Files have incorrect names, and we want to know about it
Or proactively monitor it via CIPP

https://docs.microsoft.com/en-us/onedrive/sync-health

**Comment by KelvinTegelaar** [comment]
This does not have an API yet, soon(tm) :)

**Comment by kayvanaarssen** [comment]
Please keep it on your radar, its a usefull feature😉
