### ISSUE TITLE
FEATURE REQUEST: add CW Command (continuum rmm) to the MSP apps

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#973]
**Is your feature request related to a problem? Please describe.**
We have to this with each individual tenant right now, and manually upload it, and it doesn't have the best installation verification. 

**Describe the solution you'd like**
Built into the MSP/RMM apps wizard

**Describe alternatives you've considered**
Continue to maintain our own...

**Additional context**
Here is the guide from ConnectWise which we used to install RMM via intune: https://chilp.it/3c52dff

**Comment by dan-baird** [comment]
any interest on this one?

**Comment by KelvinTegelaar** [comment]
contributor bump, I won't be picking this up, but leaving it open for another to pick up.

**Comment by vsouthmayd** [comment]
Actually the MSI installer was changed last year to embed the site token in the filename which is pickup by the installer when executed.  If you rename the installer excluding the site token, the installer UI will prompt for the site token.

There is a command line option to pass the site token from the command line.

Msiexec /i ITSPlatform-Installer.msi TOKEN=[Token] /q

**Comment by dan-baird** [comment]
Thanks so much @vsouthmayd !

Considering this new information, that makes this job significantly easier @johnduprey

**Comment by johnduprey** [comment]
I'm going to venture that it would still be easier to just use the Continuum url since that would include any future version updates (and we won't have to add and maintain msi files in the repository)

**Comment by dan-baird** [comment]
In any case does it seem  like it would be a simple addition based off of any of the existing MSP tool wizards that were already built, or is there some other roadblock?

**Comment by KelvinTegelaar** [comment]
Added by the great @johnduprey
