### ISSUE TITLE
FEATURE REQUEST: tenant exclusion to be done by checklist rather than one by one or even 3 at once

### ISSUE THREAD

**Issue by cardonet-helpdesk** [KelvinTegelaar/CIPP#980]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i have to exclude tenants manually one by one, i believe even selecting 3 at once is too manual if you have alot of tenants

**Describe the solution you'd like**
could we have a include/exclude checklist for tenants

**Additional context**
Settings\Tenant Exclusion

**Comment by KelvinTegelaar** [comment]
new version used multiselect
