### ISSUE TITLE
FEATURE REQUEST: Identify open mailbox edit page

### ISSUE THREAD

**Issue by procradminator** [KelvinTegelaar/CIPP#986]
**Is your feature request related to a problem? Please describe.**
Not a problem other than a usability issue

**Describe the solution you'd like**
Mailbox page. 1) Show which mailbox is open on the screen. If you walk away and make a coffee and come back and have forgotten which one is open you have to start again. 2) Show actions taken with a CR/LF. If you do a couple in succession they are on the same lone. 3) Update the access on the right after changes.

**Describe alternatives you've considered**
Not relevant

**Additional context**
Screenshot
![image](https://user-images.githubusercontent.com/47219254/175299973-c26ca3b4-d3b6-44a4-b1d0-d63cc4b45095.png)

**Comment by KelvinTegelaar** [comment]
Fixed in dev
