### ISSUE TITLE
BUG: Cannot remove License items from Exclusions

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#987]
**Describe the bug**
Deleting items from the list of License Exclusions does not actually delete them

**To Reproduce**

1. Go to Settings > Licenses 
2. Click on trash can icon to delete an item
3. You will get a message saying deletion was successful
4. However, license item is not removed and even refreshing the page does not show removal
5. In fact, you cannot add that license again without getting an error, in case you want to prove it is still there on the backend tables

**Expected behavior**
Item is removed.

**Screenshots**
na

**Desktop (please complete the following information):**

- OS: Windows 11 Enterprise
- Browser  MS-Edge 102.0.1245.44
- Version CIPP 2.7

**Comment by KelvinTegelaar** [comment]
Fixed in dev, case sensitivity issue :)
