### ISSUE TITLE
FEATURE REQUEST: List Tenant Name on Reports Instead of Just Default Domain

### ISSUE THREAD

**Issue by PremierOne1130** [KelvinTegelaar/CIPP#990]
**Is your feature request related to a problem? Please describe.**
Some screens/reports such as /tenant/standards/bpa-report list the default domain as the tenant identifier whereas other screens/reports such as /tenant/administration/tenants list the actual name of the tenant as well as the default domain.

**Describe the solution you'd like**
We would benefit from having both the tenant name and the default domain on reports that list multiple tenants. The name of the tenant is often configured to match other systems such as our PSA, so when we pull reports to CSV, having the actual tenant name is helpful to cross-reference other systems. The default domain alone is not always obvious to us who the client is.

**Comment by KelvinTegelaar** [comment]
Executed in dev
