### ISSUE TITLE
FEATURE REQUEST: Alerting / Monitoring of secrets and certificates expire

### ISSUE THREAD

**Issue by hansendennis** [KelvinTegelaar/CIPP#991]
**Is your feature request related to a problem? Please describe.**
App Secrets have a vaild period of 2 years - monitoring af these experations.
Enterprise app certificates has a valid period of 3 years - monitoring af these experations.
Apple Push certificate for MDM has a valid period of 1 year - monitoring af these experations.

**Comment by KelvinTegelaar** [comment]
This feature request has been closed as incomplete, please follow the entire document when making a feature request.
