### ISSUE TITLE
FEATURE REQUEST:

### ISSUE THREAD

**Issue by servant42** [KelvinTegelaar/CIPP#993]
**Is your feature request related to a problem? Please describe.**
When deploying CIPP for the first time, the time investment and complexity to create SAM tokens is high, but the code to do so programmatically exists in the SAM Wizard already.

**Describe the solution you'd like**
I suggest changing the installation flow to wait until after installation to ask for the SAM tokens, and walk the user through the SAM Wizard for the first time (if the tokens don't exist already, for example, which could also trigger if the user deletes the tokens as a way to prompt their regeneration, for admin users at least), with an alternate set of manual directions if it fails or needs troubleshooting, making the experience of first time and updated tokens similar and streamlining the installation.

**Describe alternatives you've considered**
Alternately, a checkbox to bypass the tokens and allow adding after install, if allowing them to be added up front is still desirable as an option. Or, add the wizard into the deployment process, but I suspect that dropping into the SAM wizard if the tokens don't exist on first login but after install is a simpler workflow.

**Additional context**
I admit it's been about a month or so since my last installation and it's possible I'm out of the loop and this is already addressed.

**Comment by KelvinTegelaar** [comment]
already in dev.
