### ISSUE TITLE
licenses inconsistency

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [KelvinTegelaar/CIPP#994]
Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern.
•  Repo License: GNU Affero General Public License v3.0, 
o  Different license : MIT in jest.config.js.
 
Regards, Software Ethics Researcher.

**Comment by KelvinTegelaar** [comment]
Our project is GNU Affero General Public License v3.0 licensed.
