### ISSUE TITLE
BUG: expand logic to include multi-selection on DMARC fo options

### ISSUE THREAD

**Issue by dan-baird** [KelvinTegelaar/CIPP#995]
**Describe the bug**
Getting this error in the Domain Analyser for one of our domains; 
![image](https://user-images.githubusercontent.com/17422069/175837159-5d665f13-3fb2-4a2d-ad95-1601a85556ff.png)

**Expected behavior**
However, according to this resource multiple option can be selected: 
https://mxtoolbox.com/dmarc/details/dmarc-tags/dmarc-failure-reporting-options

**Comment by KelvinTegelaar** [comment]
Confirmed as bug, will see when we create a fix for this

**Comment by johnduprey** [comment]
I would like to work on this please!

**Comment by KelvinTegelaar** [comment]
Fixed in latest release
